### ISSUE TITLE
Ability to use MM CGM with an x22 Pump

### ISSUE THREAD

**Issue by tomasboudr** [LoopKit/Loop#100]
Looking for the ability to use a MM CGM with an x22 pump via loop.

**Comment by loudnate** [comment]
Please file an issue in rileylink_ios as well, as the order of work is to parse sensor data pages. 

Are you willing to lend a hand to building this support out?

**Comment by tomasboudr** [comment]
Hi Nate,
Yes of course. I will create an issue under rileylink_ios as well. I'm a
complete amateur at iOS development but have started the Standford class on
iTunes U and wanted to get into it for a while now, so this is a great
excuse.

**Comment by tmecklem** [comment]
@tomasboudr it's been a while since you opened this issue. Are you still interested in the feature?

**Comment by tomasboudr** [comment]
I got a G5, but I still think this is a useful feature and there are some folks working on it. So this should remain open until they PR those in.

**Comment by oskarpearson** [comment]
This can be closed; functionality now exists since https://github.com/LoopKit/Loop/pull/378

**Comment by Kdisimone** [comment]
closing issue, thanks @oskarpearson
