### ISSUE TITLE
Bolus delivered and extremely high temp basal recorded but not enacted

### ISSUE THREAD

**Issue by bookclimber22** [LoopKit/Loop#1000]
I bolused for a meal, I heard the clicks on my Omnipod, and Loop said it finished. However, five minutes after the bolus, Loop said it did a temp basal of 50.03 U/hour for 10 minutes even though I did not initiate a temp basal (I'm also in open loop mode) and my max basal rate is 1.8 U/hour. I checked the event history too, but it was not there. Also, my meal bolus was 8.3 units, but because of the supposed temp basal, my on board went up to 16.65 units and my projected blood glucose went into the negatives. My phone is an iPhone 6 and I'm running ios 12.3.1. The Loop I'm running is the 1.10.0 Jojo branch. My CGM is the Dexcom G6 and I use the Dexcom App. I'm also using an Omnipod Eros pump. Here is the issue report:

[Loop Report 2019-06-30 10_17_27-04_00.txt](https://github.com/LoopKit/Loop/files/3342975/Loop.Report.2019-06-30.10_17_27-04_00.txt)

Here are some screenshots: 
![IMG_7505](https://user-images.githubusercontent.com/52085356/60397942-d8332500-9b20-11e9-8694-2287e850a3a3.PNG)
![IMG_7511](https://user-images.githubusercontent.com/52085356/60398048-e7ff3900-9b21-11e9-9ff6-f61b723a47b9.PNG)
![IMG_7512](https://user-images.githubusercontent.com/52085356/60398049-eb92c000-9b21-11e9-8d5f-b00d3651265f.PNG)
![IMG_7507](https://user-images.githubusercontent.com/52085356/60397945-db2e1580-9b20-11e9-8410-90f0cebf9898.jpg)
![IMG_7508](https://user-images.githubusercontent.com/52085356/60397946-dec19c80-9b20-11e9-8fa5-72d6ac2799e0.PNG)
![IMG_7509](https://user-images.githubusercontent.com/52085356/60397947-e08b6000-9b20-11e9-887a-447ce7b07f96.PNG)

**Comment by ps2** [comment]
The insulin delivery chart shows delivery relative to reservoir, so boluses can show up there as high rates. Your pump did not get a high temp basal rate set at that rate.
