### ISSUE TITLE
Enhancement Request: add decimals to bolus input field

### ISSUE THREAD

**Issue by schmartmann** [LoopKit/Loop#1003]
Enhancement request: 

The placeholder value for the bolus is `0.0`, but, when entering a value like `1.05`, a user has to manually insert the `.`, and, if a user is not careful, a user could wind up with a bolus of `105`, as opposed to `1.05`.

Proposal: add decimal to input such that entering `1`, will return `0.01`, `10`, will return `0.10`, and `100` will return `1.00`, etc.

**Comment by elnjensen** [comment]
I’m not sure this hits the right balance of safety and convenience, given other safeguards in place. It would require extra button presses for every bolus, and has significant potential to be confusing. (“I entered 2!  Why didn’t I get a 2-unit bolus?”). The max bolus setting in Loop settings provides a backstop against large boluses (e.g. your 105 unit example couldn’t happen with a properly set max bolus). Also, tapping the bolus recommendation number copies it to the input field, making it easier to avoid typos.

**Comment by naromero77** [comment]
@schmartmann I very much like this idea and have run into this issue myself. This is not very different from an ATM interface. 

The max bolus setting here helps to some extent, but not as much as you think. You can be bolusing for 0.3 gram snack and have the max setting bolus setting at 3U.
