### ISSUE TITLE
Carbs absorbing in minutes.  Just tonight I had a 30 g diner  that loop absorbed in minutes and that it est to be 285 g.  Also none of insulin on board is showing up on my front page.  It shows up on night scout.  Any thoughts 

### ISSUE THREAD

**Issue by kspengel** [LoopKit/Loop#1007]

**Comment by dm61** [comment]
Please check your settings for Insulin Sensitivities (ISF) and Carb Ratios (CR). Something is probably way off, either CF is extremely high or ISF is extremely low, or both. Another possibility is that you recently used a drastic temporary override that made large temporary adjustments to CR and ISF settings, which are then reflected in completely unrealistic absorption outcomes.

**Comment by Kdisimone** [comment]
closing this issue as there has been no additional follow-up information to help troublehsoot. If problem has persisted, please reopen and add information including Issue Report from Loop.
