### ISSUE TITLE
Incorrect IOB, Falsely High Temp Basal on Open Loop

### ISSUE THREAD

**Issue by johntwohy** [LoopKit/Loop#1008]
Loop app showed 9.08U IOB at 1:30pm, even though roughly adding the most recent boluses (1.2U 12:57pm, 5.15U 11:59am, 1.2U 7:47am) is less (Image 1).

In addition, Insulin Delivery graph shows temporary basal rates significantly higher than max basal threshold (2.5 U/hr) with 48.8 U/hr at 12:00pm, 23.99 U/hr at 1:14, 5.9 U/hr at 1:24pm, and approx 25 U/hr at approx 1:35pm (Images 2-3).

All of this occurred while on open loop (changed sensor this morning so keeping loop open until sensor becomes more accurate).

Not a safety concern - I don't think the high temporary basals actually occurred, since it was above max basal threshold, I was on open loop at the time, no noticed omnipod clicking at that time, and blood glucose is not dropping as the loop app predicts based on the (incorrect) high IOB / COB ratio.

IMAGE 1
![IMG_2595](https://user-images.githubusercontent.com/51167446/60834411-46619280-a186-11e9-8a9a-0941989b4fa5.PNG)
IMAGE 2
![IMG_2596](https://user-images.githubusercontent.com/51167446/60834409-45c8fc00-a186-11e9-8476-cd0c31ec1ba2.PNG)
IMAGE 3
![IMG_2597](https://user-images.githubusercontent.com/51167446/60834410-45c8fc00-a186-11e9-88b8-55cac9e3c4fc.PNG)

(edits - improved image formatting)

**Comment by shabanaj25** [comment]
We also experienced the same as above while in Open Loop. I'm attaching the screenshots that show the false high temp basals that makes the Active Insulin incorrect (more than double what we bolused for dinner). 

I did snag an Issue Report but it won't attach due to the file type. Please let me know if there's a different way to attach it or where I should send it.  

Thanks!

![IMG_4231](https://user-images.githubusercontent.com/28721805/61572649-9b46b800-aa66-11e9-880a-c6d7b9fd64f2.JPG)
![IMG_4234](https://user-images.githubusercontent.com/28721805/61572651-9da91200-aa66-11e9-87f6-52c866b69549.JPG)

**Comment by ps2** [comment]
You can zip up your issue report and attach it.

**Comment by shabanaj25** [comment]
> You can zip up your issue report and attach it.

Done! Thanks.

**Comment by jilldade** [comment]
We also had the same issue of open loop reporting high temp basals we never accepted and showing a larger amount of IOB than should have been. One of the temps was over our max temp basal limit.

**Comment by jilldade** [comment]
IMG_0228.PNG

**Comment by creefederico** [comment]
We have intermittently had the same issue on Master, Medtronic, closed loop.  Tonight it showed 11 units IOB when it was really 5.5.  Basal temp’d to zero.  At one point, loop shows a temporary basal >60 units per hour.  Force Closing the app and restarting clears the extra IOB but the zero temp basal remains.  
![63E3213B-2EA3-4A5A-A58D-AC0128D92953](https://user-images.githubusercontent.com/50082048/68078028-ecc04c00-fda4-11e9-864f-cf1178847be9.jpeg)

**Comment by ps2** [comment]
Also see discussion in Zulip: https://loop.zulipchat.com/#narrow/stream/144111-general/topic/Open.20Loop.20Display

**Comment by bjornoleh** [comment]
Another discussion in Zulip on this topic: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Possible.20solution.2Fclue.20for.20double-counted.20boluses

**Comment by ps2** [comment]
This should be fixed in dev with https://github.com/LoopKit/LoopKit/pull/344
