### ISSUE TITLE
IOB rounding issue

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#1009]
As [reported by Marko Myllyaho](https://loop.zulipchat.com/#narrow/stream/148543-Loop/topic/Loop.20IOB):

IOB value shift happens after the phone and Loop has been idle for several hours (not opening the phone or Loop), so usually this happens at night. When I open Loop app, I see lower IOB value, which will shift to a greater value after Loop updates next time.
I have reproduced this issue many times as described and the IOB value shift has been something between 0.05U to 0.6U. Here is one example more. See BEFORE/AFTER issue reports and screenshots. I think smaller value is incorrect or is there any good explanation for this?

![LoopIOB-20190629](https://user-images.githubusercontent.com/14649/60838990-b295c380-a191-11e9-86c9-f02b621b7a56.png)

BEFORE: https://www.dropbox.com/s/azdapi0ae4hg7ld/Loop%20Report%202019-06-29%2004-29-09%2B03-00-BEFORE.txt?dl=0
AFTER: https://www.dropbox.com/s/a45u4h173w2ypr9/Loop%20Report%202019-06-29%2004-33-56%2B03-00-AFTER.txt?dl=0

**Comment by ps2** [comment]
Marko has confirmed that the fix is working for him.

**Comment by Kdisimone** [comment]
closing with fix (has worked for us too)
