### ISSUE TITLE
Avoiding duplication of carb entries

### ISSUE THREAD

**Issue by denvergail** [LoopKit/Loop#1012]
**Describe the bug**
When carb entry is confirmed while BG is below threshold, no bolus is required. The bolus administration screen does not appear. This has created confusion for some less-sophsiticated users who then continue to input carbs under the false assumption that the entry was not input into Loop. They continue to enter carbs. 

This was reported in Looped group a couple of weeks ago as happening at a summer camp. One of the CDEs from the camp sought me out at a medical conference this weekend and asked if there could be a confirmation when those carbs are entered showing that 1) carbs have been entered into Loop and 2) confirmation that no bolus is currently recommended. Should another carb entry be attempted,  a second confirmation message could appear that requires a response such as "xx carbs were entered at xx:xx time. do you want to add these additional carbs?" 

I would be happy with NO BOLUS IS CURRENTLY RECOMMENDED message.

**Attach an Issue Report**
N/A

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**
Having a positive confirmation screen would go a long way in alleviating the first impression that carbs were not entered. Having this message could avoid more incidents as reported by other (not only this most recent incident).

Thanks!

**Comment by Nightfoxy** [comment]
Yes, some kind of confirmation needs to appear. At a minimum, the bolus screen should come up with a 0.00 recommendation. This has happened a few times teaching my daughter to use her loop app, with my mother, and with a few tech savvy care-givers. In all cases, they entered the carbs until the bolus screen appeared (2 to 3 entries).

**Comment by jcarlisto** [comment]
This has happened to my daughter. I agree that at a minimum, the bolus screen should come up with a 0.00 recommendation.

**Comment by ps2** [comment]
This is being addressed in Tidepool work, that should make it into DIY loop soon. https://github.com/tidepool-org/Loop/pull/41
