### ISSUE TITLE
Temp basals not working (green loop)

### ISSUE THREAD

**Issue by TheaSusanne** [LoopKit/Loop#1013]
PROBLEM: Loop working perfectly first two days of pod. Day three, hour 3: temp basal has not changed last 90 minutes. Time stamp on temp basal in Loop app says last review was 8.32 pm, time at the moment was 10.12 pm. Temp basal had runned out the 30 minutes, then resumed to schedule basal since. 

INFO: Closed loop. Green loop. Dexcom G6 values working nicely. Able to bolus without an issue. Nightscout sometimes saying some kind of temp bolus running infrequently, not matcing Loop temp basal info. 

TRIED TO: Soft reset Loop and Dexcom app not working. Hard reset Iphone 7 not working. RileyLink turned off, waited few minutes, then on not working. Suspend delivery and resuming not working. Still no new temp basal. 

WORKING: Deleting all insulin data in Health app -> soft reset Loop app -> waited 10 minutes -> working again.

During night, this happened two more times. Again in the morning from 9.14 am to 10.40 am (picture attached - look at time stamp and time at the moment. I know it stayed in scheduled basal during this time which worked nicely, yet yesterday that was not the case, but do not have picture). Unstable ON/OFF temp basal updates (not updating every 5 minutes) without deleting data in Apple Health during rest of the day, but stayed in closed loop. Able to bolus and working with frequently checking basals. 

PICTURE OF ISSUE (fourth time, in the morning): 
https://user-images.githubusercontent.com/52893426/61395332-79fa9600-a8c5-11e9-96b8-03bf728fbf85.png)

HAS NOT: rebuilt app (not able to at the moment). Changed pod (going to in 2 hours when 80-hour-pod-time runs out). 

ISSUE REPORT: reported no problems. No changes from earlier issue reports during well-working loop. Not able to reproduce problems due to it's random appearance with no identifiable reasons to set off problem. 

PHONE: Iphone 7, iOS 12.1.4, available capasity 80,79 GB.
 
LOOP VERSION:           
 - Version Number: V1.10.0DEV-JOJO
 - Repo: Loopkit/Loop/Kdisimone/Jojo branch (don't know it that is the right way to say repo, sorry)

CGM: Dexcom G6 with Dexcom G6 app

PUMP: Omnipod 

(Thank you so much, anyhow. I love Loop and I am so grateful).

**Comment by ps2** [comment]
If you are below your target range, and predicted to be higher than your target range, Loop will not set a positive basal until you are above your target range. So it looks like things are working as expected.

**Comment by TheaSusanne** [comment]
Thank you for your fast reply! I know, so I realize the picture isn't the best to illustrate the issue, but when this happened the first time, I was above target (9,2 mmol/L). Nightscout sometimes registrered some elevated temp basals (I did not bolus as the time to test if temp basals would reactivate and make me come down - prediction was slightly above as well), yet it was not shown in Loop. I will repost a new pic if it happens again. It has been stable since change of pod so far.

**Comment by samwohns** [comment]
I'm having this same issue!

**Comment by ps2** [comment]
Loop not high temping when you are below target is the system working as designed.  If you see a different problem where you are above target and Loop is not high temping you, please open a new ticket.

**Comment by samwohns** [comment]
I wasn’t below target
