### ISSUE TITLE
Riley link lost connection with pump when pump battery ran low.  I tried to forget pump and reconnect but pump not being recognized.  Getting message that says peripheral device did not resopond in time. 

### ISSUE THREAD

**Issue by footphysio** [LoopKit/Loop#1020]
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by ps2** [comment]
The pump will turn off the radio when the battery gets low enough, to conserve more energy for the more critical operation of delivering insulin.

**Comment by footphysio** [comment]
I replaced the battery and the problem did not remedy itself.  Is there another way to turn the radio back on on the pump?

Paradigm 522
Riley link versine 1.9.5

Scott Fraser
Sports Physiotherapist Allan McGavin Sports Medicine Center
Head Therapist and Coordinator Trainer Services UBC Athletics
Appts: 604-822-0150
Office: 604-822-2641


________________________________

**Comment by ps2** [comment]
Sounds like you may need to reboot your RileyLink.

**Comment by footphysio** [comment]
OK thank you very much for your help. I have never done this reboot before does this mean I’m deleting the app from my phone and then re-loading it from my computer by plugging it in with the wire? Or is there a resource or link that I can use for how this reboot takes place?

Scott Fraser
Sports Physiotherapist Allan McGavin Sports Medicine Center
Head Therapist and Coordinator Trainer Services UBC Athletics
Appts: 604-822-0150<tel:604-822-0150>
Office: 604-822-2641<tel:604-822-2641>

Sent from Scott Fraser's iPhone
Please excuse spelling, punctuation  and brevity.

On Jul 19, 2019, at 4:20 PM, Pete Schwamb <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds like you may need to reboot your RileyLink.

**Comment by ps2** [comment]
Nope, just toggling the power switch on the side. You should generally refer to the troubleshooting steps at loopdocs if you have issues.  Here's a page about the kind of comms problems you're having: https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/#bluetoothrl-issues

**Comment by footphysio** [comment]
great I got it sorted.  Thanks again.  I can't beleive what a game changer this system is and the support that you offer.  It is unfortunate that big pharma did not have the service and patient centered approach that your group does.

two thumbs up.

My A1C has dropped to .67 since being on loop and standard deviation is incredibly more consistent. This system is fantastic.

Scott Fraser
Sports Physiotherapist Allan McGavin Sports Medicine Center
Head Therapist and Coordinator Trainer Services UBC Athletics
Appts: 604-822-0150
Office: 604-822-2641


________________________________
