### ISSUE TITLE
Neutral basal command not sent

### ISSUE THREAD

**Issue by marcusfpereira** [LoopKit/Loop#1024]
To test the basal rate I’ve set a wide target override (using jojo). BG was stable and in target but had a slow, may be noise, up spark. Loop set a high temp basal. On next check BG returned to the stable point. Loop seems to calculate to return to neutral basal on top of the screen, but on bottom active insulin graph the temporary basal was still set. It keeps with this temp basal for the entire 30 minutes.

**To Reproduce**
1. Set a wide target override
2. With BG stable and in target but near the top boundary simulate a higher BG measure, probably loop will try to compensate with a high temp basal.
3. On next check BG return to the stable point.
4. See if Loop return the bottom graphic to neutral basal.

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: 1.10.0
 - Repo: jojo with spike integration added

I have the Loop Report but did not find how to attach it on this form. 

**CGM**
 - Device: Freestyle Lubre
 - Manager app: Spike

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros

![2E7D87E8-04B1-4ACC-8C53-3A0A28D4C59A](https://user-images.githubusercontent.com/53144306/61591721-6cccf800-aba0-11e9-83a2-f7685f75f7bc.png)

![9E73B899-379E-41AA-BBC0-12C2BB9C8BB1](https://user-images.githubusercontent.com/53144306/61591722-6cccf800-aba0-11e9-93d8-90cf1cb668f2.jpeg)

**Comment by Kdisimone** [comment]
Please attach an Issue Report

**Comment by marcusfpereira** [comment]
Report from the high temporary basal described above:
[Loop Report 2019-07-21 09_41_43-03_00.md.txt](https://github.com/LoopKit/Loop/files/3414728/Loop.Report.2019-07-21.09_41_43-03_00.md.txt)

After I've sent this issue it happened again but now with negative temporary basal. For 1 check Loop set a negative temporary basal for a low spike BG measure. The next check the BG returned to the stable value but Loop kept the temporary basal on the Graph but it was neutral on the top of the screen.

**Comment by ps2** [comment]
The temp basal *was* actually canceled at 2019-07-21 12:25:20 +0000, but the DoseStore does appear to think it's still running. Please let me know if you are able to reproduce this.

**Comment by marcusfpereira** [comment]
I have 2 more reports with the same issue.
It is easier to reproduce configuring a wide target area and with a stable and in range BG simulate a high or low spike. Loop will probably set a temporary basal to correct. The next check with the normal stable BG Loop should cancel the temp basal. But it is not always happening.

The screenshots below happened yesterday with a high spike, no Issue Report this time.
![TmpNotCancelled1 2019-07-24 at 08 16 26](https://user-images.githubusercontent.com/53144306/61889948-cb65df00-aedc-11e9-8fd5-61227e71b2d5.jpeg)
![TmpNotCancelled2 Image 2019-07-24 at 08 17 48](https://user-images.githubusercontent.com/53144306/61889947-cacd4880-aedc-11e9-9562-0db9fd7c5c5c.jpeg)

**Comment by marcusfpereira** [comment]
It happened again today, but it was on a different scenario.
On early morning BG was below target and negative IOB (basal too high, I already fixed this).
At 7:24 predictions were leading to a BG in target, so Loop "cancelled" the 0 temp basal. But only on top screen it was cancelled, on Insulin Delivery graph and on Event History there were no cancellation. The "negative" temp basal kept running during the full 30 minutes since the predictions kept lying on target and there were no need to change basals.

![TmpNotCancelled2 Image 2019-07-25 at 07 42 43 (1)](https://user-images.githubusercontent.com/53144306/61891693-9cea0300-aee0-11e9-8d6b-63d5b0e28379.jpeg)
![TmpNotCancelled1 Image 2019-07-25 at 07 42 43](https://user-images.githubusercontent.com/53144306/61891694-9cea0300-aee0-11e9-8b52-6d60a3d08a0f.jpeg)
[Loop Report 2019-07-25 07_41_55-03_00.md.txt](https://github.com/LoopKit/Loop/files/3432476/Loop.Report.2019-07-25.07_41_55-03_00.md.txt)

**Comment by marionbarker** [comment]
I believe this is the same problem mentioned in zulipchat. Here is a link to my Delivery Reconciliation notes which includes the pointer to the Google spreadsheet with reconciliation for 4 pods.  

https://loop.zulipchat.com/#narrow/stream/144120-omnipod_dev/topic/Delivery.20reconciliation/near/171865496

**Comment by ddaniels1** [comment]
This has happened to us as well.  Will attach screenshots and issue report at the next opportunity.

**Comment by ddaniels1** [comment]
I just read the Zulip post above.  @ps2 can you confirm if setting neutral temp basals should help with this? Based on dosestore thinking the TB is still running will it indeed affect the IOB calculation as is?  @Kdisimone mentioned that setting neutral temp basals may increase the incidence of late screamers, but most of our pod life is a temp basal positive or negative at this point anyway.  Any confirmation that screamers are more likely with neutral TBs besides theoretical battery issues?
