### ISSUE TITLE
Temporary Override - changing times after starting override causing crashes

### ISSUE THREAD

**Issue by typeonerogue** [LoopKit/Loop#1028]
**Describe the bug**
I generally use the temporary overrides that I save as a template for starting up an override in the near future. 
I have one override I use for my martial arts class:
1. and this time I decided to start it at 5:30PM CST. 
2. Thinking about it a bit, I decided I needed a few more minutes of temp override before my class started at 6:30PM CST
3. so I went into the override and changed the time backwards to 5:15PM CST.

Once I did that last action, the Loop app crashed and would not startup

**Attach an Issue Report**
https://gist.github.com/rogue-bryan/bbf4bca1669ed2339eccc573015d502d

**To Reproduce**
1. Go to Overrides
2. Click on a defined override
3. Change the start time of the override and save it to begin the override
4. Open the scheduled override using the top bar in Looop again and update the start time (backwards)

(Please note that I don't dare do this again, so the repro steps are from what I remember doing)

**Expected behavior**
Loop shouldn't crash when changing times for a future running override.

**Screenshots**

**Phone**
 - Hardware: iPhone 8 Plus
 - OS Version: iOS 12.3.2

**Loop Version**
 - Version Number: V1.10.0DEV-JOJO (I believe this was installed after a bug fix that came through at the end of May)
 - Repo: https://github.com/Kdisimone/Loop/tree/jojo

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom Mobile App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod EROS
 - Firmware version: 2.9.0

**Notes**
The code described here is what was breaking:
```
    public var endDate: Date {
        get {
            return startDate + duration.timeInterval
        }
        set {
            precondition(newValue > startDate) <------ This is the line it was breaking on
            if newValue == .distantFuture {
                duration = .indefinite
            } else {
                duration = .finite(newValue.timeIntervalSince(startDate))
            }
        }
    }
```

@ps2 described how to disable some code to get Loop running again:
- Comment out this line of code:
`self.scheduleOverride = TemporaryScheduleOverride(rawValue: rawOverride)`
- Change this line of code:
`overrideHistory: TemporaryScheduleOverrideHistory = UserDefaults.appGroup?.overrideHistory ?? .init()`
to this:
`overrideHistory: TemporaryScheduleOverrideHistory =  .init()`

**Comment by ps2** [comment]
This appears to be fixed.
