### ISSUE TITLE
Loop JoJo Suspend Threshold Not Working with Override Preset

### ISSUE THREAD

**Issue by shainey** [LoopKit/Loop#1029]
**Describe the bug**
Loop JoJo Suspend Threshold is not working when I have the Override Preset on. Have had this occur multiple times to me when having workouts presets on.

  
![Pic 1](https://user-images.githubusercontent.com/22161266/61676561-7e122380-acca-11e9-9101-143fc2caa850.JPG)
![Pic 2](https://user-images.githubusercontent.com/22161266/61676562-7e122380-acca-11e9-868f-ff7e00a776c9.JPG)
![Pic 3](https://user-images.githubusercontent.com/22161266/61676563-7e122380-acca-11e9-84ef-057982db6224.JPG)

[Loop Report 2019-07-22 214129-0400.pdf](https://github.com/LoopKit/Loop/files/3419783/Loop.Report.2019-07-22.214129-0400.pdf)

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**
Temp basal to be turned off when glucose level drops below the threshold value of 80.

**Screenshots**

**Phone**
 - Hardware: iPhone 8 Plus
 - OS Version: iOS 12.4

**Loop Version**
 - Version Number: V1.10.0
 - Repo: DEV-JOJO

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: subg_rfspy 2.2 / ble_ble_rfspy 2.0

**Additional context**
Would also be nice to have an updatable threshold value for each Override Preset being user might want different ones when working out versus regular day to day or other presets.

**Comment by Kdisimone** [comment]
Loop was suspending insulin here. The confusion is regarding the format of the HUD display. The temp basal display in the HUD is showing the offset from your scheduled basals AS ADJUSTED BY THE OVERRIDE. So, take your scheduled basal, decrease to 20% of its value and that is the assumed "new" basal that the offset/delta is drawn with for showing the graphic and text.
