### ISSUE TITLE
Temp basals stopped working

### ISSUE THREAD

**Issue by samwohns** [LoopKit/Loop#1031]
PROBLEM/INFO: Green closed loop, but the temp basals all of the sudden stopped working.

TRIED TO: Turned off iPhone 10 XR and that didn't work, neither did rebooting Riley Link or doing soft app reset.

DID WORK: Deleting all insulin info from Apple Health. (Phew!)
[Loop Report 2019-07-23 22_38_29-05_00 (1).txt](https://github.com/LoopKit/Loop/files/3429549/Loop.Report.2019-07-23.22_38_29-05_00.1.txt)

PICTURE OF ISSUE:
https://scontent-msp1-1.xx.fbcdn.net/v/t1.0-9/67139444_10214108614890020_747093841558896640_n.jpg?_nc_cat=108&_nc_oc=AQklYnZYKDmhLkAP-FpIYXxbTZZQ0ZECuNUA9zaHCNpUygtykmt1WBGatgjinBcRH8Q&_nc_ht=scontent-msp1-1.xx&oh=49fcfab163fe75237348796f9faf6480&oe=5DE932FB

NOT YET TRIED: rebuilt app (don't have computer with me for two more weeks). changed CGM or changed pod.

CGM: Dexcom G6 with Dexcom G6 app
PUMP: Omnipod

**Comment by ps2** [comment]
If your current BG is below your target range, Loop will not high temp you, even if you are predicted to go high eventually.

**Comment by samwohns** [comment]
My current bg was *not* below target!

**Comment by loudestnoise** [comment]
@samwohns it sure looks like you were from your screenshot. 
![00EADCF8-5521-4263-B13A-1388C9B73688](https://user-images.githubusercontent.com/194853/62099126-be394f00-b252-11e9-9bba-6a4580a21f2e.jpeg)

**Comment by samwohns** [comment]
My suspend threshold was 55 at the time

**Comment by loudestnoise** [comment]
A suspend threshold is a BG at which basal insulin delivery is suspended. When you say “temp basals stopped working”, do you mean high temp basals stopped working? Your current BG was under the target range, and therefore no high temp basals were going to be recommended and enacted.

**Comment by samwohns** [comment]
It was a recurring problem that happened even when BG was high, I don't have all the screenshots, I'll post again if it recurs

**Comment by samwohns** [comment]
This happened again where all the sudden it acts as if the most recent temp basal was many hours ago (see screenshot below), even though I entered 20 G carb and only bolused for half of the recommended amount, which usually triggers a higher temp basal.

![image](https://user-images.githubusercontent.com/52500912/62341435-5896ce00-b4b1-11e9-8ee7-75880a831572.png)

**Comment by ps2** [comment]
Please attach an issue report with the screenshot when you see something dosing related.

**Comment by samwohns** [comment]
See attached


[Loop Report 2019-08-01 23_27_57-04_00.txt](https://github.com/LoopKit/Loop/files/3459485/Loop.Report.2019-08-01.23_27_57-04_00.txt)

**Comment by ps2** [comment]
The way correction range schedules work in loop can be confusing (and at least partially because of this, people end up using a single correction range in their schedule).  At any given time Loop is making a forecast, it is looking at your *eventual* bg, which is typically six hours out. The correction range scheduled for that time is what is used to deliver insulin.  So, if your current BG is 87, and six hours out, your target range is 95-95, then Loop will not high temp you, even if your eventual BG is above your range.  Remember Loop does not high temp unless the entirety of your forecast is above the lower end of your correction range. I believe the two details above explain what you are seeing.

**Comment by samwohns** [comment]
Eventual BG is 200+, way above target, so how does that explain away this issue?

**Comment by samwohns** [comment]
And how do you explain the weird time change in the orange in the top middle of the screen, way off base?

**Comment by ps2** [comment]
Please read my response again, and I don't see anything obviously wrong with your active insulin graph. If you have another issue, please open a separate ticket.
