### ISSUE TITLE
Bolus in progress Indicator no longer visible

### ISSUE THREAD

**Issue by smartdigger** [LoopKit/Loop#1032]
Since Updating to the latest version (to support the new dexcom transmitters) the bolus indicator progress bar no longer displays when a bolus is in progress
This happens in both closed and open loop mode.

![Bolus Indicator - Location](https://user-images.githubusercontent.com/47868089/61867458-31e40080-aecf-11e9-9845-02f613c2e81d.PNG)
![Bolus Indicator](https://user-images.githubusercontent.com/47868089/61867459-31e40080-aecf-11e9-8967-fe8655a4b3ab.PNG)
![Pump Status](https://user-images.githubusercontent.com/47868089/61867462-327c9700-aecf-11e9-954a-514fae65cdaa.PNG)

**Comment by smartdigger** [comment]
[Loop Report 2019-07-25 112407+0100.zip](https://github.com/LoopKit/Loop/files/3431069/Loop.Report.2019-07-25.112407%2B0100.zip)

**Comment by ps2** [comment]
Does this still happen after restarting the app?  There is a bug where certain events aren't working after switching pumpmanagers.

**Comment by smartdigger** [comment]
Hi Pete I rebooted the phone and it has reappeared. It was consistent behaviour across 2 installs though. I reinstalled the app on the phone but did not reboot the phone between reinstalls. Thanks for the quick reply - I got the same advice on the facebook group. Cheers
![Bolus Indicator - Fixed](https://user-images.githubusercontent.com/47868089/61885708-366fdf80-aef6-11e9-8240-a5228587bc51.PNG)
