### ISSUE TITLE
IOB accounting

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#1034]
**Describe the bug**
IOB tracking does not appear to be correct...

**Attach an Issue Report**
Don't have Issue Report, but do have data spreadsheet to illustrate.

https://docs.google.com/spreadsheets/d/1IXVDX_hM2O1cwRCKpOJoIomfy-GmPDTXzabkZMsrSP0/edit?usp=sharing

**Pump**
pods

**Additional context**

User's scheduled basal during this period of time was 0.2 u/hr.  During this one hour span, temp basals were set every five minutes and always below 0.6 u/hr (the minimum required basal rate to guarantee a click of basal delivery within the 5 min in worst case scenario...as partially discussed here in this issue https://github.com/LoopKit/Loop/issues/1015 ). No Loop drops during this one hour, everything was running smooth.

I have two concerns:

1. IOB, as reported by the Loop pill in NS, was recorded in column C. (User reports that the Loop app had been freshly opened, so I don't think this is a repeat issue of the IOB rounding in another issue).  From 4:42am to 5:22am, the temp basal rate that was set by Loop was always below scheduled basal rate...yet the IOB continued to rise. This is the incorrect trend that IOB should be making. I calculated the IOB, based on the set temp basals (column D), that I would have expected.

2. Column D IOB in this situation still doesn't represent the actual user experience as the basal click timer was being reset every five minutes for the hour captured in the spreadsheet. So, over the one hour, no clicks of any basal were delivered and the "in body" iob would've been closer to column E. Looking at how significant this might be...the difference between column d and column e at end of an hour is about 0.133 units IOB, this user's ISF is 185...so 25 mg/dl difference in the predicted curve. 

However, current user experience is the difference between column C and column E...and that gets to be more significant at 63 mg/dl in predicted curve difference.

<img width="510" alt="Screen Shot 2019-07-25 at 4 15 43 PM" src="https://user-images.githubusercontent.com/12402160/61915005-7d120980-aef7-11e9-8b0f-8ccc78174ad4.png">

<img width="1129" alt="Screen Shot 2019-07-25 at 2 00 43 PM" src="https://user-images.githubusercontent.com/12402160/61914982-653a8580-aef7-11e9-8c9a-c9cac5a33a2f.png">

<img width="730" alt="Screen Shot 2019-07-25 at 1 58 14 PM" src="https://user-images.githubusercontent.com/12402160/61915090-d9752900-aef7-11e9-9e65-f63ee40e05f3.png">

**Comment by Kdisimone** [comment]
Second Sheet was added to the google doc sheet listed in the original post. The second Sheet has a different set of data than the first; probably a more robust example.

**Comment by ps2** [comment]
This is a known issue with Loop using rounding of doses in certain places in LoopKit that assume Medtronic type of delivery (pulse halfway through the period). The accounting above shows how it can add up in certain situations, and should definitely be fixed.  Thanks for digging into this, Katie.

**Comment by Kdisimone** [comment]
closed with the fix above
