### ISSUE TITLE
IOB does not match insulin delivery

### ISSUE THREAD

**Issue by j4cbo** [LoopKit/Loop#1035]
**Describe the bug**
This morning I observed a mismatch between reported IOB and reported basal delivery:

![2019-07-26 07 11 10](https://user-images.githubusercontent.com/537158/61958603-dc672c80-af7e-11e9-9204-871136182421.png)

Between 5:30 and 7am, Loop reports that it was delivering a neutral temp basal but that IOB rose from -0.5 to +1.0 over that time. This doesn't make sense... with a neutral temp (which would have been expected as my blood sugars were normal at the time), IOB should have been decaying towards zero.

**Attach an Issue Report**
[Loop Report 2019-07-26 07:11:28-06:00.md.txt](https://github.com/LoopKit/Loop/files/3436126/Loop.Report.2019-07-26.07.11.28-06.00.md.txt)

**Expected behavior**

**Screenshots**
See above

**Phone**
 - Hardware: iPhone X
 - OS Version: iOS 12.3

**Loop Version**
 - Version Number: 1.10.0-dev, commit 5c631359983d94c0966100694105b4fa38096197
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod
 - Firmware version: 2.8.0 / 2.8.0

**Additional context**
My basal rate this time of day is 1.35 U/hr, so I don't think this is a rounding / phase issue like #1015. It may be related to (or even the same as ?) #1034

**Comment by marionbarker** [comment]
I believe this can be closed based off Pete's note referencing Issue 1059.

**Comment by j4cbo** [comment]
Seems likely. I haven't noticed anything similar since then.
