### ISSUE TITLE
Feature Request: pull from HealthKit when app becomes active

### ISSUE THREAD

**Issue by j4cbo** [LoopKit/Loop#1036]
I'd love it if Loop checked for new Apple Health events whenever the app is opened / brought to the foreground, instead of waiting for the next loop cycle.

This would be helpful for several use cases:
- Manually-entered BGs would appear immediately.
- External insulin doses would cause an immediate update to the displayed prediction.

I've started using an InPen insulin pen which automatically syncs its doses to Apple Health, and they show up promptly in the Apple Health app but don't appear in Loop until after Loop's next, uh, loop. It would be very helpful to see that the dose has appeared and an updated insulin prediction right away. :)

**Comment by ps2** [comment]
Loop actually gets notifications from HealthKit when new values are stored, so any therapy related changes should be triggered off of this. Display-only changes can be triggered off foreground/background events, like refreshing a graph.

**Comment by j4cbo** [comment]
Ah, gotcha - so a better description would be "HealthKit updates should cause Loop to recalculate predictions and update UI"?

**Comment by ps2** [comment]
Yes, generally that is true, and Loop already does that; if you find times where it isn't doing that, then that specifically can be addressed.

**Comment by j4cbo** [comment]
I'll close this, gather some logs, and then open a proper bug report.
