### ISSUE TITLE
External boluses not immediately reflected in Loop display

### ISSUE THREAD

**Issue by j4cbo** [LoopKit/Loop#1037]
**Describe the bug**
When an outside bolus is added to HealthKit, it should promptly be reflected in Loop's UI (predicted glucose, active insulin, and insulin delivery graphs)

**Attach an Issue Report**
[Loop Report 2019-07-26 09:57:56-06:00.md.txt](https://github.com/LoopKit/Loop/files/3436525/Loop.Report.2019-07-26.09.57.56-06.00.md.txt)

Console logs filtered to `process:Loop`: 
[console.txt](https://github.com/LoopKit/Loop/files/3436531/console.txt)
The first log entry corresponds to switching away from the Loop app. I logged the insulin dose around the same time. Loop's only output while I was adding doses in the Health app was the `WCSession` / `WCXPCManager` lines.

**To Reproduce**
1. Switch from Loop to Apple Health app
2. Log a large insulin dose (navigate to insulin delivery, press + in top right corner)
3. Switch back to Loop

**Expected behavior**
I expect to see the new dose promptly reflected in Loop's UI and prediction displays.

**Screenshots**
n/a

**Phone**
 - Hardware: iPhone X
 - OS Version: iOS 12.3

**Loop Version**
 - Version Number: 1.10.0-dev
 - Repo: LoopKit/Loop, dev branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod

**Additional context**
The use case I'm most interested in is actually doses coming from a Companion Medical InPen... but manual entry to HealthKit seems to provide similar results and is easier to reproduce :)

**Comment by j4cbo** [comment]
Another observation: today I went out for brunch and left my RL at home (whoops!). I bolused by pen, but noticed that pen boluses recorded in Apple Health did not appear in Loop's UI until after I got home and Loop started up again.

**Comment by j4cbo** [comment]
Yet another note: if I:
- Open up Loop, enter carbs, get a recommended bolus
- Deliver that bolus via InPen, causing it to be written to Apple Health
- Close and re-open the Loop bolus wizard

Then the "active insulin" and bolus recommendation in the bolus wizard *does* reflect the delivered dose. Additionally, tapping on the graph on the main screen to get into the Predicted Glucose display also provides an updated graph that reflects the new dose. So this is just a matter of the main screen graphs not updating.

**Comment by marionbarker** [comment]
Has this been addressed?  I see one change merged and one open. Is it true that external boluses should always appear immediately in Loop or just be checked prior to an updated insulin delivery recommendation?

**Comment by j4cbo** [comment]
Unfortunately I'm not able to check right now (I'm stuck on an old version of Loop for complicated reasons), but it should be easy for someone to verify with a more recent build.
