### ISSUE TITLE
Overrides correction range units issues

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#1039]
**Describe the bug**
Overrides store correction ranges without an associated unit. If the user switches their preferred blood glucose unit, the unit will be displayed wrongly.  Also, in dev there is this line: https://github.com/LoopKit/Loop/blob/dev/LoopUI/Extensions/ChartPoint.swift#L63, which assumes the unit is mg/dL, which is wrong for users with mmol/L.

The unit of the defined correction range should be stored in the override settings, or enforce a fixed storage unit, like mg/dL.

**Comment by Kdisimone** [comment]
closed with fix
