### ISSUE TITLE
"Insulin delivery" displays 0 (zero) no mater how much insulin delivered in Omnipod-testing branch

### ISSUE THREAD

**Issue by tpradu** [LoopKit/Loop#1041]
**Describe the bug**

On the dashboard, the "Insulin delivery" total counter displays 0 (zero) no mater how much insulin has been delivered since 00:00 a.m. (basal and/or bolus)

**Attach an Issue Report**

[Loop Report 2019-07-28 11_26_31+03_00.txt](https://github.com/LoopKit/Loop/files/3438994/Loop.Report.2019-07-28.11_26_31%2B03_00.txt)

**To Reproduce**

Please see screenshots. error visible on Loop dashboard

**Expected behavior**
"Insulin delivery" should display the total amount of insulin (both basal and bolus) delivered since 00:00 a.m. 

**Screenshots**

![IMG_7544](https://user-images.githubusercontent.com/10376067/62004689-e3ce3780-b130-11e9-9350-b4eb43b4bd7a.PNG)
![IMG_7543](https://user-images.githubusercontent.com/10376067/62004691-e761be80-b130-11e9-8943-f0ccde12dd05.PNG)

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: Omnipod-testing branch - LoopV1.10DEV
 - Repo: 

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod +RileyLink
 - Model: Omnipod: Lot: L44501, TID: 0410493; PI Version: 2.9.0; PM Version 2.9.0
 - Firmware version: Riley: subg_rfspy 2.2/ble_rfspy...

**Additional context**

**Comment by bluemaguilu** [comment]
Having exact same issue
Omnipod Loop
Phone: iPhone XR 
Software version 12.3.1
Loop Version: v1.10.0deb
Dexcom G6
Dexcom app
Omnipod Loop + RL

First noticed it on August 13

**Comment by benndy72** [comment]
Same basic issue, though mine displays as "1 U Total".

New Loop user, running first Loop.  Pod activated ~9:30AM, Under "Pod Settings" Insulin Delivered shows correct amount @ 15.25 U, but  Dashboard shows Insulin Delivery as 1 U Total.

---

**Phone**
Hardware: iPhone X
OS Version: iOS 12.4.1

**Loop Version**
Version Number: Omnipod-testing branch - LoopV1.10DEV
Repo:

**CGM**
Device: Dexcom G6
Manager app: Dexcom App

**Pump**
Manufacturer: Omnipod +RileyLink
Model: Omnipod: Lot: L44485, TID: 0721255; PI Version: 2.9.0; PM Version 2.9.0
Firmware version: Riley: subg_rfspy 2.2/ble_rfspy / ble_rfspy 2.0

**SCREENSHOTS**
![IMG_1513](https://user-images.githubusercontent.com/55364726/64928233-0cd28680-d7ca-11e9-8f83-d6456f3f3810.jpg)
![IMG_1514](https://user-images.githubusercontent.com/55364726/64928234-0cd28680-d7ca-11e9-94f1-685f103aa372.jpg)
