### ISSUE TITLE
lots of failures loop/omnipod

### ISSUE THREAD

**Issue by jonboy688** [LoopKit/Loop#1042]
i have had two in a row, with code 064 within 24 ours, and one before this with same code earlier this week, two different batches of pods also... had a few 052 codes which is to be expected with failures on the 3rd day close to the 72 hour mark... but three pod failures in less then a week from two different batches has me a little worried... last night was 2am in the morning

**Comment by RyRyCeratops** [comment]
Error code 064 means there is an interruption in the flow of insulin. You can find out more about error codes on Omnipod here - [https://forum.fudiabetes.org/t/omnipod-alarm-explanations/3022]. There are also other groups out there that have similar information.  Have you tried moving to a different site area? Are you pinching up on the skin before the cannula inserts into the skin?

**Comment by Kdisimone** [comment]
closing this as there is little to go on for debugging purposes. You can reopen with captured debugging logs, issue reports, and further useful information if you get them with further pod failures.
