### ISSUE TITLE
Loop suddenly absorbing carbs and changing glucose estimation JOJO

### ISSUE THREAD

**Issue by Saikoudaze** [LoopKit/Loop#1043]
Hi,

Loop 1.10.0DEV-JOJO. iOS 12.4. iPhone 7 plus. Dexcom G6, Omnipod. 

Some loop behaviour I can't explain. Unfortunately I don't have pre screenhots. My blood glucose was at this level but the estimated target at 6 hours was 3mmol/L. Absorbed carbs were 107g out of 130g. Target bg was 5.5mmol/L.

I wasn't happy with the time it was taking to come down so I decided to hit the premeal target button (just moves my target slightly to 4.5mmol/L). Suddenly my predicted glucose shot down to -10.8mmol/L and all my carbs absorbed. I can't explain why moving my target by such a small amount would do all that and my glucose is continuing to rise with a suspended basal so I've switched to open loop. Any ideas?

**Attach an Issue Report**
https://drive.google.com/open?id=1TfZJaV0Xp2kCb4RwqNKMXn82eEyvVjB0

**Comment by Kdisimone** [comment]
closed with fix
