### ISSUE TITLE
Correction Range first line should be fixed

### ISSUE THREAD

**Issue by marcusfpereira** [LoopKit/Loop#1044]
First line of configuration page of Correction Range should be fixed as on Basal Rates and Carb Ratios pages.
When clicking on Edit button it is possible to move the fist line, if moved the initial time is changed and the final configuration does not start at 00:00 hour.
The only way to restore the 00:00 hour us to remove all lines and redo all configurations.

**To Reproduce**
1. Go to 'Configuration->Correction Range'.
2. Click on '+' and add a second line.
3. Cluck ob 'Edit' and move the first line to the botton.
4. See that this line is moveable an the initial time was changed.

** Expected Behavior
First line fixed and initial time always at 00:00

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: 1.10.9DEV-JOJO-BEEPS-SPIKE
 - Repo: kdisimone/Jojo-beeps + Spike integration

**CGM**
 - Device: Libre+MiaoMiao
 - Manager app: Spike

**Pump**
 - Manufacturer: Ominipod

**Comment by marcusfpereira** [comment]
Screenshots 
![4AA0B5A5-1EAA-48DE-A374-836B12F8824F](https://user-images.githubusercontent.com/53144306/62150886-7f98a880-b2d5-11e9-8450-5d0a670a5353.jpeg)
![C4C67D17-C2B2-4A65-9682-8E261AE9761E](https://user-images.githubusercontent.com/53144306/62150888-80313f00-b2d5-11e9-89c7-d9a76474069c.jpeg)
![21BAE3AC-DF2C-459B-8FD4-0A380A7C6884](https://user-images.githubusercontent.com/53144306/62150890-80313f00-b2d5-11e9-9ec1-bac1bf8ee053.jpeg)

**Comment by ps2** [comment]
This is not an issue with the new correction, isf, and basal schedule editors in dev.
