### ISSUE TITLE
Loop is Green - CGM Data is Old and Will not Update - Loop Not Operating in Closed Loop even with Green Circle 

### ISSUE THREAD

**Issue by RyRyCeratops** [LoopKit/Loop#1045]
**Describe the bug**
The time on the phone is correct. The loop circle is green.  The time the POD is correct. The CGM data is over 8 hours old and the time under the CGM data is over 8 hours old.  Loop will not give insulin based on BG. It will not auto adjust basal rates and when I input carbs it says to give 0 units. I can manually give insulin. 

The BG dots and the arrow under next to the incorrect number are accurate. If you tap on glucose you get the correct data in the loop app but never on the display. 

I have also lost all predictive data in the Loop app and the app is stuck on an eventual BG of 11. 

**Attach an Issue Report**
There is no "issue report" because the loop is still running green even though NO closed loop functions are operating.

**To Reproduce**
N/A

**Expected behavior**
Show correct CGM data on display
Operate in Closed Loop
Make adjustments to basal rates
Show BG prediction data

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
![IMG_1586](https://user-images.githubusercontent.com/30480280/62260185-13a26700-b3df-11e9-9cca-1593b9b21ea3.png)

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: 1.10.0DEV
 - Repo: I do not know what this is

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom (using Share)
 - Transmitter ID for Dexcom starts with 80 (we have been using this transmitter for several sessions with no problem).

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: 

**Additional context**
App shows green arrow for looping. Pod time is right. Dexcom time is several hours earlier and no where near his actual BG which is much higher. Dexcom Share, Nightscout and Apple Health all have the CGM data correct. Also the dots seem to show his CGM data correctly (maybe) but the reading on the top is wrong.  I have removed G6 from loop, restarted phone, re input G6, I have shut down apps and re opened apps. I have turned off bluetooth and restarted phone and turned it back on. I have turned off the Riley Link and restarted the phone and turned it back on - both with and without deleting the G6 from loop. I have also uninstalled and reinstalled the Dexcom app and I have done a hard reset on the phone between them.

**Comment by RyRyCeratops** [comment]
I have also uninstalled and reinstalled the Dexcom app and I have done a hard reset on the phone.

**Comment by ps2** [comment]
Please capture an issue report and attach it to this ticket (you will need to zip it up)

**Comment by RyRyCeratops** [comment]
It will not generate an issue report. I presume because the loop circle is green. I have tried several times to get it to generate and it will not.  What do you suggest for forcing it to generate a report? I have gone to settings and selected issue report but the report showing up is from an issue I had a few weeks back not this one.

**Comment by ps2** [comment]
Every time you go to the issue report page, it is a new one.  Just send that to yourself, zip it up, and attach it here.

**Comment by RyRyCeratops** [comment]
Got it - Thank you ~ Sorry I missed that. 

[Loop Report 2019-08-01 11:22:48-04:00.md.zip](https://github.com/LoopKit/Loop/files/3457551/Loop.Report.2019-08-01.11.22.48-04.00.md.zip)

**Comment by ps2** [comment]
You have a lot of future BG data in your system for some reason.  Were your clocks off at one point?  There is an older bug where a future BG can be incorrectly stored from Loop, but this looks different; your values are what appear to be valid values, and are evenly spaced at 5 minute intervals, but they're from Sept 2019.

**Comment by ps2** [comment]
Try deleting those entries using the Health app, and then restart Loop.

**Comment by RyRyCeratops** [comment]
So I need to delete all BG data from the health app and then restart loop?  Working on that now. 

We had a problem on 7/9 where the Loop stopped communicating with the POD.  The POD showed a different time than the phone or the Loop. We changed the POD and it was fixed.  Other than that I have never seen a problem with the clocks.  Here is the issue report from that incident if that helps.  It may not be needed but here it is. 

[Loop Report 2019-07-09 18:25:58-04:00.md.zip](https://github.com/LoopKit/Loop/files/3457674/Loop.Report.2019-07-09.18.25.58-04.00.md.zip)

**Comment by ps2** [comment]
No, just delete the future data.

**Comment by RyRyCeratops** [comment]
It changed the number from 50 to 60 but he is reading 67 on the Dexcom app not 60.  We deleted back 7/2 because there was a big jump in the days.  7/2 was our first day of looping.

**Comment by RyRyCeratops** [comment]
We restarted the loop again and now it shows the 67 but it says the time is 2:28 so it is an hour ahead. 
![IMG_1596](https://user-images.githubusercontent.com/30480280/62314264-9fa8a300-b460-11e9-80c7-7018d1e02727.jpg)

**Comment by ps2** [comment]
Sounds like your time is still off somehow?  
Something is odd about your setup. Could you describe all the components you're using? Haven't seen anything like this. Are you using the G6 receiver? What is the date/timezone on it?

**Comment by ps2** [comment]
Please attach another issue report now that you've deleted the future data.

**Comment by RyRyCeratops** [comment]
It is back to having a normal display:

![Image-1-1](https://user-images.githubusercontent.com/30480280/62334999-fbdae980-b497-11e9-91bd-3b8b5d8fde1e.jpg)

BUT it is moving VERY slowly when it comes times to give insulin for food. We input the carbs and hit save and then the screen goes back to the home screen.  About 20 I get the following screen. 

![IMG_1599](https://user-images.githubusercontent.com/30480280/62334695-b2d66580-b496-11e9-8071-858bc8e56cae.PNG)

Then another 30 I get this:
![IMG_1600](https://user-images.githubusercontent.com/30480280/62334698-bc5fcd80-b496-11e9-989b-c810f12fdeda.PNG)

I have never seen the predicted glucose at 10:45 pm before.  I am wondering if I changed a setting here inadvertently when trying to troubleshoot earlier: 
![Image-1](https://user-images.githubusercontent.com/30480280/62334961-ce8e3b80-b497-11e9-929e-586ea65b9201.jpg)

I am not sure if I had Enable Retrospective Correction activated before.  Could this be causing it to run slowly? Here is the current issue report if needed:

[Loop Report 2019-08-01 20:08:07-04:00.md.zip](https://github.com/LoopKit/Loop/files/3459105/Loop.Report.2019-08-01.20.08.07-04.00.md.zip)

 Thank you for your help.

**Comment by RyRyCeratops** [comment]
We are using an iPhone SE, running iOS 12.3.1.  We are using Loop Version Number: 1.10.0DEV.  We use the Dexcom G6 app and not a receiver. The time zone is set with the phone.  We have been running it since 7/2/2019 with no problems until late last night.  We are in EST in Georgia.  Phone is set to satellite clock and date using NY as setting the EST.  Most recent issue report is above with current lagging.

**Comment by ps2** [comment]
More weird clock stuff on this phone. You have forecasts going out to the end of Sept.  What do you mean "set to satellite clock"? There is a `Set Automatically` setting in Settings -> General -> Date & Time, but no "satellite clock" option that I know of.

**Comment by RyRyCeratops** [comment]
It is on Set Automatically and the time zone is New York 

![Image-1-2](https://user-images.githubusercontent.com/30480280/62338448-96422980-b4a6-11e9-9025-3ed832109734.jpg)

Any thought on how to fix it?

**Comment by ps2** [comment]
I've never seen either of the weird things that have shown up in your issue report. I'm beginning to suspect the phone is having hardware issues, or your cell tower is giving you bad time syncs occasionally for some reason.

**Comment by RyRyCeratops** [comment]
I wonder if he is going to need a new phone soon.  He is running on the most current software and the phone still has an 87% battery life but the SE came out between the 6S and the 7 I believe so not the newest phone out there but still available and still working on the newest software. It is smaller so nice for pocket size and readings but we may have to get a newer one soon. 

We are in the metro Atlanta area so you would think the towers would be good but who knows. 

I ran the Apple suggested troubleshooting for the time - under general (toggle off, wait 15 seconds, turn on) and then through privacy to set based on location as well (toggle off, wait, turn on).  

For the FIRST time we do not have the yellow ! in the BG display: 

![Image-1-3](https://user-images.githubusercontent.com/30480280/62340193-aceb7f00-b4ac-11e9-841f-c97202e79195.jpg)

Not sure if this "fixed" anything in the issue report but I am hoping that is good news.  I will let it go tomorrow and I can send another issue report tomorrow evening if this one does not look clear.

[Loop Report 2019-08-01 22:33:26-04:00.md.zip](https://github.com/LoopKit/Loop/files/3459407/Loop.Report.2019-08-01.22.33.26-04.00.md.zip)

Thank you again!!!!

**Comment by RyRyCeratops** [comment]
Newest Report - Looks like it is running better.  

[Loop Report 2019-08-04 21:29:11-04:00.md.zip](https://github.com/LoopKit/Loop/files/3465604/Loop.Report.2019-08-04.21.29.11-04.00.md.zip)
