### ISSUE TITLE
Override mode: wrong negative basal shown in loop

### ISSUE THREAD

**Issue by francesc0-cgm** [LoopKit/Loop#1046]
On loop jojo branch but in dev too, when override mode is enacted and BG is under target, loop shows in upper bar a wrong negative basal.

It should be -0.125 in this case

![72390DC3-E5D7-4E8B-A07B-B60973BC8E67](https://user-images.githubusercontent.com/10731469/62360537-49e40180-b519-11e9-8d1b-8c4a0fe7208d.png)
![2CBC1834-EDBA-4B5F-8406-B33A2D847A2A](https://user-images.githubusercontent.com/10731469/62360540-49e40180-b519-11e9-8a48-34e4dc8b919d.png)
![C1DD53EE-F7F4-430F-9E77-1F30C3ACE57A](https://user-images.githubusercontent.com/10731469/62360627-8879bc00-b519-11e9-8f61-4c0a3f7446d5.jpeg)

**Phone**
 - Hardware: iphone se
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: 1.10.0 dev spike jojo
 

**CGM**
 - Device:  Dexcom G6
 - Manager app:  Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 723
 - Firmware version:  2.3A

**Comment by francesc0-cgm** [comment]
A bit later, same basal segment

![0268B3EB-FF88-4350-9C13-E2B2B8D28F3A](https://user-images.githubusercontent.com/10731469/62361868-279fb300-b51c-11e9-9fda-70647ae306c7.jpeg)
![F5977BD8-DA50-4127-B8CA-83FA0731CB47](https://user-images.githubusercontent.com/10731469/62361870-279fb300-b51c-11e9-9630-021cf7bf9cbc.jpeg)

**Comment by mylma** [comment]
1. image: 
Your current override setting is probably 70% when base basal is 0,125U/h, then 0,7 x 0,125U/h = ~0,088U/h, correct? That HUD graphic adapts to your current override setting, so I think there is no issue.

**Comment by francesc0-cgm** [comment]
Yes it is 70%. Ah ok i understood. My current basal is 0.088 not 0.125. Great...sorry. No issue at all
