### ISSUE TITLE
Apple Health Entry for Basal Insulin delayed during periods with Scheduled Basal

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1049]
**Title**
Apple Health Entry for Basal Insulin delayed during periods with Scheduled Basal

**Describe the bug**
The amount of insulin delivered as reported in Apple Health, while eventually the same as that reported by the Pod, is not updated promptly (just under 2 hours in this example) during long period of Scheduled Basal

**Attach an Issue Report**
Issue Report Name: Loop Report 2019-08-09 06_42_51-07_00_delivSchBasal.md attached as a zip
Example Scheduled Basal start time: 02:03 PDT, 2019-08-09 09:03 UTC
Example Scheduled Basal stop  time: 03:49 PDT, 2019-08-09 10:49 UTC

**To Reproduce**
1. Have "good" basal, no COB (or hormones) and set wide enough range to maintain no need for Loop to enact TB

**Expected behavior**
Currently AH is updated when the next TB starts.
When running same code with Neutral TB, Apple Health was updated every 5 minutes (at cost of more Pod communication)

**Screenshots**
Three screenshots of Apple Health, Event History and Insulin Delivery plot during period of long Scheduled Basal are updated as a single zip and are included in the pdf which summarizes observations and has arrows to point out Sch Basal example. 

**Phone**
 - Hardware: iPhone 7+
 - OS Version: 12.3.1

**Loop Version**
 - Version Number: v1.10.Dev
 - Repo: LoopKit/LoopWorkspace (branch=temp-basal-delivery)

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Uploaded Files**

[AppleHeathDelayedUpdate_SchBasal.pdf](https://github.com/LoopKit/Loop/files/3487786/AppleHeathDelayedUpdate_SchBasal.pdf)

[Loop Report 2019-08-09 06_42_51-07_00_delivSchBasal.zip](https://github.com/LoopKit/Loop/files/3487793/Loop.Report.2019-08-09.06_42_51-07_00_delivSchBasal.zip)

[Three Screenshots.zip](https://github.com/LoopKit/Loop/files/3487803/Three.Screenshots.zip)

**Comment by ps2** [comment]
This is working as expected. HK entries for basal are not recorded until we have a valid end date.
