### ISSUE TITLE
Loop thinks basal was delivered between pod fault and new pod activation

### ISSUE THREAD

**Issue by j4cbo** [LoopKit/Loop#1051]
**Describe the bug**
This evening I was out for a walk when my pod failed. (052 screamer, hour ~70, it happens). Loop recognized the fault and went through the deactivation flow, but deactivation failed (flaky radio?) so I had to tear it off and use a paperclip.

An hour later, I put on a new pod. In the intervening hour Loop seems to think I was getting my normal basal rate, even though it did know that the pod failed and showed a "suspended" display in the meantime.

**Attach an Issue Report**
[Loop Report 2019-08-09 20:45:16-07:00.md.txt](https://github.com/LoopKit/Loop/files/3488482/Loop.Report.2019-08-09.20.45.16-07.00.md.txt)

**To Reproduce**
1. Wait for (or induce?) a pod fault
2. Ensure that Loop is aware that the pod has faulted
2. Instead of replacing the pod immediately, wait a significant amount of time, e.g. an hour
3. Activate a new pod
4. Check IOB

**Expected behavior**
Loop should indicate that no insulin was delivered between when it knew that the pod faulted and when the new pod is started.

**Screenshots**
![2019-08-09 20 46 01](https://user-images.githubusercontent.com/537158/62817247-7804ab00-baf0-11e9-8a24-fb1735a14038.jpg)
![2019-08-09 20 44 59](https://user-images.githubusercontent.com/537158/62817270-923e8900-baf0-11e9-9061-dada9a5f1750.png)

**Phone**
 - Hardware: iPhone X
 - OS Version: iOS 12.3

**Loop Version**
 - Version Number: `LoopKit/LoopWorkspace` `0871df74ee303ce999035d188406f58983f9f325`

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod
 - Firmware version: 2.8.0 / 2.8.0

**Comment by j4cbo** [comment]
Also of note, I experienced this with `LoopKit/LoopWorkspace` after the recent delivery rewrite, but I *don't* think it's a regression... I recall similar issues with previous builds but I never left the pod off long enough to get a clear bug report out of it.

**Comment by naromero77** [comment]
This also occurs when a pod is deactivated and a new pod is paired. A pod failure is not required. For the case that the pod is deactivated, a work around is to do a suspend prior to initiated the pod deactivation process.
