### ISSUE TITLE
Fatal error: Schedule incomplete: file /Users/wolfgang/Downloads/Loop-omnipod-spike/Carthage/Checkouts/rileylink_ios/OmniKit/Model/BasalSchedule.swift, line 72

### ISSUE THREAD

**Issue by Siemensgaertner** [LoopKit/Loop#1053]
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by Kdisimone** [comment]
This looks like a build error and you haven't provided any additional info, so nothing here to work from. Please use the Build Errors page in Loopdocs.org to help troubleshoot, as well as guidance for the info need.ed to include in post asking for help with build errors
