### ISSUE TITLE
Whitespace in Loggly API crashes app

### ISSUE THREAD

**Issue by akbar-shah** [LoopKit/Loop#1054]
**Describe the bug**
App crashes when you put a whitespace in the Loggly API token. 

**Loop Version**
 - Version Number: [e.g. 1.9.6]

The solution will be to urlencode the token or filter input from the UI. I temporarily fixed by editing line 88 in Loop > Models > ServiceAuthentication > LogglyService.swift  from 
 
`return URL(string: "\(base)\(token)/tag/\(tags.joined(separator: ","))/")! 
`
to: 

`return URL(string: "\(base)\(token.trimmingCharacters(in: .whitespacesAndNewlines))/tag/\(tags.joined(separator: ","))/")!`

<img width="1013" alt="Screen-Shot-2019-08-12-at-11 20 41-PM" src="https://user-images.githubusercontent.com/19673934/62986319-e6e34c00-bdef-11e9-9048-36153b928385.png">

**Comment by Kdisimone** [comment]
duplicate, closing to consolidate into one issue.  https://github.com/LoopKit/Loop/issues/655
