### ISSUE TITLE
Loop closes without warning

### ISSUE THREAD

**Issue by cyoung1024** [LoopKit/Loop#1057]
**Describe the bug**

Loop closes unexpectedly upon reaching the 5 minute mark of an update cycle (no white screen, just immediately closes). It then closes every minute afterwards, unable to update. This occurred after downloading and installing the dev branch, which I fetched yesterday. Git confirms that I'm up to date with the origin. Upon opening the project, I was also warned that the AdditionalAssets.xcassets folder does not exist.
Overrides were added before Loop crashed, but all my targets are one number (ex : 120 - 120). No other settings were changed.

**Attach an Issue Report**

[Loop Report 2019-08-16 00:01:11+02:00.txt](https://github.com/LoopKit/Loop/files/3507354/Loop.Report.2019-08-16.00.01.11%2B02.00.txt)

**To Reproduce**

1. Download current dev branch (00c3edc)
2. Run and install
3. Wait for Loop to attempt to update

**Expected behavior**

Loop to successfully complete an update cycle and remain open

**Screenshots**

<img width="1280" alt="Capture d’écran 2019-08-15 à 22 55 42" src="https://user-images.githubusercontent.com/42605906/63130608-4e99c280-bfbb-11e9-80e7-67037a28ca76.png">

I also have a lovely 17 second video of Loop suddenly closing, but don't know the best way to upload it. Will add it in the comments if I figure it out.

**Phone**

 - Hardware: iPhone X
 - OS Version: iOS 12.2, macOS 10.14.5, Xcode 10.3

**Loop Version**

 - Version Number: 1.10.0dev
 - Repo: LoopKit

**CGM**

 - Device: Dexcom G5
 - Manager app: Spike

**Pump**

 - Manufacturer: Medtronic
 - Model: 715
 - Firmware version: 2.3A 1.1 0B 0B

**Additional context**

The issue report was grabbed from a Spike version but I experienced this on both dev and dev-spike. I can re-install with the official version and grab a different issue report, but sadly as I'm on a free dev account I'm out of provisioning profiles for the week (I'm currently changing back to a different version that I had previously unsigned). I can do this next Thursday afternoon (resigned today at 13h Paris time).

**Comment by Kdisimone** [comment]
Dev has known bugs that are being worked out in a different testing branch currently. It’s not recommended to build with dev at this time.

**Comment by ps2** [comment]
If you can catch the crash in Xcode, that would help.  You can ignore the missing assets folder popup.  It's just a warning.

**Comment by cyoung1024** [comment]
[debug-output.txt](https://github.com/LoopKit/Loop/files/3508858/debug-output.txt)
<img width="1280" alt="Capture d’écran 2019-08-16 à 11 03 52" src="https://user-images.githubusercontent.com/42605906/63156833-d9a7a680-c015-11e9-8376-b21168d714de.png">

**Comment by ps2** [comment]
This crash is happening in spike code, which is not part of Loop. You are running custom code and will have to work with whoever wrote that code to diagnose this issue.

**Comment by cyoung1024** [comment]
Sorry about that, thanks for your help
