### ISSUE TITLE
First Correction Range row is not editable after removing other rows

### ISSUE THREAD

**Issue by mylma** [LoopKit/Loop#1060]
**Describe the bug**
When editing correction ranges:
First you probably need only one correction range for the whole day.
1. Add a new correction range and Save changes.
2. Remove the range row that you just added.
3. Now there should be only one (original) range left.
4. Try to edit that range. **It is not editable.**
5. Try to save changes. **Save-button is inactive and only Cancel is active.**
6. You need to create/leave one additional range row (with same settings as original) to be able to Save changes.

**Expected behavior**
You should be able to edit the first correction range row after removing other rows.

**Screenshots**
![IMG_0336](https://user-images.githubusercontent.com/44064056/63183505-c6202e00-c05d-11e9-985f-0ec622a623d8.PNG)

![IMG_0335](https://user-images.githubusercontent.com/44064056/63183796-8b6ac580-c05e-11e9-8a6a-4b3ac730f9bb.PNG)

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.4

**Loop Version**
 - Version: LoopWorkspace temp-basal-deliver branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.4A

**Additional context**
Using mmol/L units.

**Comment by ps2** [comment]
Thanks for the report. The fix is here: https://github.com/LoopKit/LoopKit/pull/294 Will be merged into dev soon.

**Comment by Kdisimone** [comment]
@ps2 FYI I found this same bug behavior on the basal schedule entries just recently.
