### ISSUE TITLE
Override target ranges not used in dosing decisions.

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#1062]
**Describe the bug**
Overrides with target ranges often do not dose to the override target range, but to the scheduled target range.

**Attach an Issue Report**
[Loop Report 2019-08-16 09:20:40-05:00.md.zip](https://github.com/LoopKit/Loop/files/3511636/Loop.Report.2019-08-16.09.20.40-05.00.md.zip)

**To Reproduce**
Engage an override that has a high target range during euglycemia, and wait for a Loop to run. 

**Expected behavior**
Loop should low temp, but does not.

**Screenshots**
![IMG_66DDCA4B59AA-1](https://user-images.githubusercontent.com/14649/63206433-f37ad500-c079-11e9-8ff5-6f03bdc2c279.jpeg)

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: dev. probably applies to any version with overrides.

**Comment by Kdisimone** [comment]
closing with the fix referenced above
