### ISSUE TITLE
Change made to carb ratio caused abnormal/enormous inaccurate Carb absorption numbers and subsequent high temp basal during low BG

### ISSUE THREAD

**Issue by nicholejhasse** [LoopKit/Loop#1063]
**Describe the bug**
I updated the carb ratio from 1:15 to 1:17 last night in response to a pattern of lower BG.  Only one segment was updated (5pm - 12am), and the change took place during that timeframe (approx 10pm).  After returning to the main Loop screen, I saw a high temp basal despite a BG of 67, a downward BG trend, and 0 carbs on board.  The predicted BG was 416.  

When I clicked on the carb absorption screen, entries showing carb absorption changed dramatically with false numbers.  Before updating the carb ratio, both the 6:07pm and 6:23pm entries showed less carbs absorbed than were eaten.  After updating, the 6:07pm carb entry showed 20g eaten with 63g absorbed, and the 6:23pm entry showed 18g eaten but **371**g absorbed!  This caused Loop to give a high temp basal despite BG at 67 and trending low.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
(Not sure if it will reproduce, but this is what I did)

1. Go to Settings
2. Click on Carb Ratio
3. Change carb ratio to a higher number during time period currently active (Changed from 15 to 17)
4. See error in carb absorption screen for carbs eaten during same time period

**Expected behavior**
I expected the carb ratio to update as normal without a bizarre effect on the carb absorption screen.
![IMG_1337](https://user-images.githubusercontent.com/51163000/63215259-ff09e280-c0f1-11e9-95be-5564c527a5ac.JPG)
![IMG_1338](https://user-images.githubusercontent.com/51163000/63215290-6aec4b00-c0f2-11e9-9575-56985d0d1f4d.JPG)
![IMG_1339](https://user-images.githubusercontent.com/51163000/63215293-72abef80-c0f2-11e9-82f9-fb016ed37bc5.PNG)

**Screenshots**

**Phone**
 - Hardware: iPhone XR
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: v1.10.0dev-jojo-beeps
 - Repo: Kdisimone

**CGM**
 - Device: Dexcom G6
 - Manager app:  Dexcom App, Nightscout

**Pump**
 - Manufacturer: Omnipod
 - Model: 
 - Firmware version: 

**Additional context**
I have the issue report saved on my computer but the uploader says it doesn't support this file.  I am unfamiliar with how I can upload it.

**Comment by ps2** [comment]
You need to compress (zip) the file before attaching it to github

**Comment by nicholejhasse** [comment]
[Loop error report 2019-08-16.zip](https://github.com/LoopKit/Loop/files/3516170/Loop.error.report.2019-08-16.zip)

**Comment by Kdisimone** [comment]
There is a known bug with the older version of overrides that is in jojo-branches. The bug is associated with overrides that are ended early, which your issue report indicates had been done. Your bug report matches that issue.  Please rebuild with current dev branch so that you do not encounter the same issue.  Thanks.
