### ISSUE TITLE
Feature Request: Omnipod Bolus Beep Option

### ISSUE THREAD

**Issue by senderob** [LoopKit/Loop#1069]
Feature Request for Omnipod Dev Branch.

I'm currently using JoJo-Beeps and would like the option to have bolus start/end beeps in the main Omnipod Dev branch.  This could be a radio button option in the settings.  I think the ability to have audible beeps is extremely useful and may have broad appeal for Omnipod Loopers who may not need/want to use a JoJo branch (thank you Katie for developing JoJo and JoJo-Beeps).  

Iphone/Omnipod/Rileylink communications can have issues due to where the pod is located vs. the Rileylink and phone, and other things like walls, furniture, other people can interfere with or block communications resulting in a bolus failure.  The option to hear an audible (but not super loud) beep at the start and end of a bolus gives the user an immediate way to know if a bolus succeeded or not, without relying on Loop notifications which may have the same phone notification sound as many other notifications, and therefore may be missed or ignored.  Omnipod beeps are distinct from phone notifications.

**Comment by francescaneri** [comment]
it would be nice as an option

**Comment by jcarlisto** [comment]
This is a great feature in JoJo. An On/Off toggle would be great for quite locations.

**Comment by francescaneri** [comment]
@jcarlisto we hope it will soon be implemented in the "dev" branch.

**Comment by BethanyLauren** [comment]
I would like it with the option to toggle on and off also.

**Comment by britnischipper** [comment]
This option is essential! We have at least one bolus fail to deliver every day. When we switched to JoJo beeps, our A1C and time in range improved significantly because of how many times we thought loop gave a bolus, but the pod never responded that it got the bolus. This is a huge safety concern.

**Comment by anastasiabrien** [comment]
Yes please

**Comment by pfaubel** [comment]
I love this feature also

**Comment by bartsluimer** [comment]
> This option is essential! We have at least one bolus fail to deliver every day. When we switched to JoJo beeps, our A1C and time in range improved significantly because of how many times we thought loop gave a bolus, but the pod never responded that it got the bolus. This is a huge safety concern.

With the failed bolus: did you have it mentioned in the screen? Or only noticed due to missing beep?

**Comment by ddaniels1** [comment]
Working on this, Here is the screen.  Closing in on the code.  
![Screenshot 2019-08-26 00 04 18](https://user-images.githubusercontent.com/18389123/63671932-9b3c8500-c795-11e9-9710-ff36809cfed9.jpg)

**Comment by ps2** [comment]
Dev currently has a toggle for enabling beeps for boluses.

**Comment by Kdisimone** [comment]
closing since this work has already been done.
