### ISSUE TITLE
Red Circle

### ISSUE THREAD

**Issue by ElizabethZ85** [LoopKit/Loop#1074]
I have tuned radio frequency, reset my Riley, turned my phone on and off, completed button press and I can’t get my system to Loop. Please help.

Report:

Use the Share button above save this diagnostic report to aid investigating your problem. Issues can be filed at https://github.com/LoopKit/Loop/issues.

Generated: 2019-08-22 12:00:50 +0000

Loop v1.9.3

## DeviceDataManager
launchDate: 2019-08-22 11:46:14 +0000
cgm: Optional(Loop.CGM.g5(transmitterID: Optional("80BMTP")))
lastError: Optional((date: 2019-08-22 11:55:18 +0000, error: ShareClient.ShareError.loginError(errorCode: "SSO_InternalError")))
sensorInfo: Optional(CGMBLEKit.Glucose(glucoseMessage: CGMBLEKit.GlucoseSubMessage(timestamp: 705293, glucoseIsDisplayOnly: false, glucose: 133, state: 6, trend: -2), timeMessage: CGMBLEKit.TransmitterTimeRxMessage(status: 0, currentTime: 705298, sessionStartTime: 916), transmitterID: "80BMTP", status: CGMBLEKit.TransmitterStatus.ok, sessionStartDate: 2019-08-14 08:20:35 +0000, lastCalibration: nil, readDate: 2019-08-22 12:00:12 +0000))

## G5CGMManager
latestReading: Optional(CGMBLEKit.Glucose(glucoseMessage: CGMBLEKit.GlucoseSubMessage(timestamp: 705293, glucoseIsDisplayOnly: false, glucose: 133, state: 6, trend: -2), timeMessage: CGMBLEKit.TransmitterTimeRxMessage(status: 0, currentTime: 705298, sessionStartTime: 916), transmitterID: "80BMTP", status: CGMBLEKit.TransmitterStatus.ok, sessionStartDate: 2019-08-14 08:20:35 +0000, lastCalibration: nil, readDate: 2019-08-22 12:00:12 +0000))
transmitter: Optional(CGMBLEKit.Transmitter)
providesBLEHeartbeat: true
## DexCGMManager
shareManager: Optional(## ShareClientManager
latestBackfill: nil
)

## MinimedPumpManager
isPumpDataStale: false
latestPumpStatus: Optional(MinimedKit.PumpStatus(clock: calendar: gregorian (fixed) timeZone: GMT-0700 (fixed) year: 2019 month: 8 day: 22 hour: 5 minute: 0 second: 17 isLeapMonth: false , batteryVolts: 1.59 V, batteryStatus: MinimedKit.BatteryStatus.normal, suspended: false, bolusing: false, reservoir: 157.5, model: 722, pumpID: "556071"))
latestPumpStatusFromMySentry: nil
lastAddedPumpEvents: 2019-08-22 12:00:34 +0000
pumpBatteryChargeRemaining: Optional(1.0)
state: ## MinimedPumpManagerState
batteryChemistry: Lithium
preferredInsulinDataSource: Event History
pumpColor: clear
pumpID: ✔︎
pumpModel: 722
pumpRegion: North America
lastValidFrequency: Optional(916.55 MHz)
timeZone: GMT-0700 (fixed)
Optional(RileyLinkBLEKit.RileyLinkConnectionManagerState(autoConnectIDs: Set(["F4C08188-B015-E11B-6F52-32EF68530F12"])))
sensorState: nil

pumpOps: Optional(### PumpOps
pumpSettings: ## PumpSettings
pumpID: ✔︎
pumpRegion: North America
pumpState: ## PumpState
timeZone: GMT-0700 (fixed)
pumpModel: 722
awakeUntil: 2019-08-22 12:01:18 +0000
lastValidFrequency: Optional(916.55 MHz)
lastTuned: 2019-08-22 12:01:18 +0000)
lastWakeAttempt: Optional(2019-08-22 11:52:31 +0000)
configuredDevices: ["F4C08188-B015-E11B-6F52-32EF68530F12"])

## RileyLinkPumpManager
rileyLinkConnectionManager: Optional(RileyLinkBLEKit.RileyLinkConnectionManager)
lastTimerTick: 2019-08-22 11:55:16 +0000

## RileyLinkDeviceManager

central: <CBCentralManager: 0x280821cc0>

autoConnectIDs: ["F4C08188-B015-E11B-6F52-32EF68530F12"]

timerTickEnabled: false

idleListeningState: disabled

## RileyLinkDevice
name: ElizaLink
lastIdle: 0001-01-01 00:00:00 +0000
isIdleListeningPending: false
isTimerTickEnabled: false
isTimerTickNotifying: false
radioFirmware: Optional(subg_rfspy 2.2)
bleFirmware: Optional(ble_rfspy 2.0)
peripheral: <CBPeripheral: 0x282c1d860, identifier = F4C08188-B015-E11B-6F52-32EF68530F12, name = ElizaLink, state = connected>
sessionQueue.operationCount: 0

## StatusExtensionDataManager
appGroupName: group.com.BL335TT7D6.loopkit.LoopGroup
statusExtensionContext: Optional(["lastLoopCompleted": 2019-08-22 12:00:37 +0000, "predictedGlucose": ["unit": "mg/dL", "interval": 300.0, "values": [130.94411221910792, 128.95283875570365, 127.03107702507526, 125.18281073780173, 123.4111668799519, 121.71864691561534, 120.10678978205658, 118.57630222082857, 117.12704144826527, 115.75847591067524, 114.46976260902166, 113.25977524931805, 112.12708154157127, 111.0701004781166, 110.08713523163999, 109.1764965205256, 108.3362251587974, 107.56430209676438, 106.85862354885533, 106.2170435777423, 105.637343589813, 105.11723266979186, 104.65442614163979, 104.24663001134209, 103.89160496115514, 103.5869526887528, 103.33032620901858, 103.11941422231723, 102.95195270495125, 102.82570341568294, 102.73848815563991, 102.68817953732255, 102.67270415353602, 102.6900451802639, 102.73826566012161, 102.81589240988325, 102.92163700047229, 103.05423434691082, 103.21244499401354, 103.39505705437819, 103.6008878303468, 103.82876864971229, 104.07724831904, 104.34459256523459, 104.62763933471206, 104.92477883430053, 105.07538874527546, 104.97907484378871, 104.89420050471054, 104.82014926307556, 104.75632505612495, 104.70209989687027, 104.6564482076763, 104.61836134038128, 104.58683871285521, 104.56112231778155, 104.54057469675186, 104.52459207903527, 104.51260329182546, 104.50406866519052, 104.49849006732418, 104.49560124047937, 104.4950812912295, 104.4950812912295], "startDate": 2019-08-22 12:05:00 +0000], "reservoirCapacity": 300.0, "sensor": ["trendType": 4, "stateDescription": "ok ", "isLocal": true, "isStateValid": true], "version": 5, "netBasal": ["rate": 0.17500000000000004, "start": 2019-08-22 12:00:37 +0000, "end": 2019-08-22 12:30:37 +0000, "percentage": 0.31818181818181823], "batteryPercentage": 1.0])

## LoopDataManager
settings: Loop.LoopSettings(dosingEnabled: true, dynamicCarbAbsorptionEnabled: true, glucoseTargetRangeSchedule: Optional(["timeZone": -25200, "overrideRanges": ["workout": [150.0, 180.0], "preMeal": [80.0, 85.0]], "override": ["context": "workout", "start": 2019-08-22 05:06:55 +0000, "value": [150.0, 180.0], "end": 2019-08-22 06:06:55 +0000], "items": [["value": [85.0, 95.0], "startTime": 0.0], ["value": [95.0, 100.0], "startTime": 28800.0]], "unit": "mg/dL"]), maximumBasalRatePerHour: Optional(1.3), maximumBolus: Optional(10.0), suspendThreshold: Optional(Loop.GlucoseThreshold(value: 85.0, unit: mg/dL)), retrospectiveCorrectionEnabled: false, retrospectiveCorrectionInterval: 1800.0, recencyInterval: 900.0, minimumChartWidthPerHour: 50.0, statusChartMinimumHistoryDisplay: 3600.0)
insulinCounteractionEffects: [
* GlucoseEffectVelocity(start, end, mg/dL/min)
* 2019-08-21 12:00:12 +0000, 2019-08-21 12:05:13 +0000, -0.42140093660536787
* 2019-08-21 12:05:13 +0000, 2019-08-21 12:10:13 +0000, -0.6375257551704279
* 2019-08-21 12:10:13 +0000, 2019-08-21 12:15:12 +0000, -0.6571939776194414
* 2019-08-21 12:15:12 +0000, 2019-08-21 12:20:12 +0000, -0.6749509894950482
* 2019-08-21 12:20:12 +0000, 2019-08-21 12:25:13 +0000, -0.29603323144383575
* 2019-08-21 12:25:13 +0000, 2019-08-21 12:30:12 +0000, -0.12120428943491533
* 2019-08-21 12:30:12 +0000, 2019-08-21 12:35:12 +0000, 0.05409945401536404
* 2019-08-21 12:35:12 +0000, 2019-08-21 12:40:12 +0000, -0.17217298877835005
* 2019-08-21 12:40:12 +0000, 2019-08-21 12:45:12 +0000, 0.0005297447970228574
* 2019-08-21 12:45:12 +0000, 2019-08-21 12:50:12 +0000, 0.5725380900225971
* 2019-08-21 12:50:12 +0000, 2019-08-21 12:55:13 +0000, 0.3429307231995093
* 2019-08-21 12:55:13 +0000, 2019-08-21 13:00:12 +0000, 0.5164076107059743
* 2019-08-21 13:00:12 +0000, 2019-08-21 13:05:13 +0000, 0.08406748782604852
* 2019-08-21 13:05:13 +0000, 2019-08-21 13:10:13 +0000, -0.3429170439410853
* 2019-08-21 13:10:13 +0000, 2019-08-21 13:15:12 +0000, 0.2377329723846711
* 2019-08-21 13:15:12 +0000, 2019-08-21 13:20:13 +0000, 1.2181340704037003
* 2019-08-21 13:20:13 +0000, 2019-08-21 13:25:12 +0000, 2.019916784630399
* 2019-08-21 13:25:12 +0000, 2019-08-21 13:30:12 +0000, 2.008595578521508
* 2019-08-21 13:30:12 +0000, 2019-08-21 13:35:13 +0000, 0.8057393673648426
* 2019-08-21 13:35:13 +0000, 2019-08-21 13:40:12 +0000, 0.6149303756661738
* 2019-08-21 13:40:12 +0000, 2019-08-21 13:45:13 +0000, 0.22066581483848652
* 2019-08-21 13:45:13 +0000, 2019-08-21 13:50:12 +0000, 0.2342188559319056
* 2019-08-21 13:50:12 +0000, 2019-08-21 13:55:12 +0000, -0.15144134491465944
* 2019-08-21 13:55:12 +0000, 2019-08-21 14:00:12 +0000, 0.06638719299260883
* 2019-08-21 14:00:12 +0000, 2019-08-21 14:05:12 +0000, 0.08648828103129559
* 2019-08-21 14:05:12 +0000, 2019-08-21 14:10:13 +0000, 0.1081219236291084
* 2019-08-21 14:10:13 +0000, 2019-08-21 14:15:12 +0000, -0.06807134530036339
* 2019-08-21 14:15:12 +0000, 2019-08-21 14:20:13 +0000, -0.042519329402962894
* 2019-08-21 14:20:13 +0000, 2019-08-21 14:25:13 +0000, -0.21631007007577946
* 2019-08-21 14:25:13 +0000, 2019-08-21 14:30:12 +0000, -0.5911669282896211
* 2019-08-21 14:30:12 +0000, 2019-08-21 14:35:12 +0000, -0.5611567774808632
* 2019-08-21 14:35:12 +0000, 2019-08-21 14:40:13 +0000, -0.1321351775293978
* 2019-08-21 14:40:13 +0000, 2019-08-21 14:45:13 +0000, 0.2963612417657088
* 2019-08-21 14:45:13 +0000, 2019-08-21 14:50:12 +0000, 0.989338870058876
* 2019-08-21 14:50:12 +0000, 2019-08-21 14:55:13 +0000, 1.7643617694278793
* 2019-08-21 14:55:13 +0000, 2019-08-21 15:00:12 +0000, 2.294701866658318
* 2019-08-21 15:00:12 +0000, 2019-08-21 15:05:13 +0000, 3.3299504019767614
* 2019-08-21 15:05:13 +0000, 2019-08-21 15:10:13 +0000, 3.935094247383297
* 2019-08-21 15:10:13 +0000, 2019-08-21 15:15:13 +0000, 4.273418302376076
* 2019-08-21 15:15:13 +0000, 2019-08-21 15:20:12 +0000, 4.215416033473052
* 2019-08-21 15:20:12 +0000, 2019-08-21 15:25:12 +0000, 4.2240849075187
* 2019-08-21 15:25:12 +0000, 2019-08-21 15:30:13 +0000, 3.787771856876013
* 2019-08-21 15:30:13 +0000, 2019-08-21 15:35:12 +0000, 3.7322081265889406
* 2019-08-21 15:35:12 +0000, 2019-08-21 15:40:12 +0000, 3.5872401170480086
* 2019-08-21 15:40:12 +0000, 2019-08-21 15:45:13 +0000, 3.396355324321221
* 2019-08-21 15:45:13 +0000, 2019-08-21 15:50:13 +0000, 3.3856219286989924
* 2019-08-21 15:50:13 +0000, 2019-08-21 15:55:12 +0000, 3.5375748602897854
* 2019-08-21 15:55:12 +0000, 2019-08-21 16:00:13 +0000, 3.8176010526198927
* 2019-08-21 16:00:13 +0000, 2019-08-21 16:05:13 +0000, 4.101173124014178
* 2019-08-21 16:05:13 +0000, 2019-08-21 16:10:12 +0000, 4.1538105644034
* 2019-08-21 16:10:12 +0000, 2019-08-21 16:15:12 +0000, 3.750304056966501
* 2019-08-21 16:15:12 +0000, 2019-08-21 16:20:12 +0000, 4.137343405867318
* 2019-08-21 16:20:12 +0000, 2019-08-21 16:25:13 +0000, 3.892191082929089
* 2019-08-21 16:25:13 +0000, 2019-08-21 16:30:12 +0000, 4.0712432236222735
* 2019-08-21 16:30:12 +0000, 2019-08-21 16:35:13 +0000, 3.7841967618878383
* 2019-08-21 16:35:13 +0000, 2019-08-21 16:40:13 +0000, 3.924351345896946
* 2019-08-21 16:40:13 +0000, 2019-08-21 16:45:13 +0000, 3.641908143351236
* 2019-08-21 16:45:13 +0000, 2019-08-21 16:50:13 +0000, 3.3508458258235914
* 2019-08-21 16:50:13 +0000, 2019-08-21 16:55:12 +0000, 3.4645359366470068

**Comment by babybluesky1** [comment]
Dexcom is having share server issues that have crippled their password management.  Delete the Share Server account from within your CGM in Loop settings. Use only the transmitter ID and keep the share server account information blank/deleted. That should get you back to good working order.

**Comment by Kdisimone** [comment]
Dexcom is having share server issues that have crippled their password management. Delete the Share Server account from within your CGM in Loop settings. Use only the transmitter ID and keep the share server account information blank/deleted. That should get you back to good working order.
