### ISSUE TITLE
Share error

### ISSUE THREAD

**Issue by ashbyakgm-marie** [LoopKit/Loop#1075]
Use the Share button above save this diagnostic report to aid investigating your problem. Issues can be filed at https://github.com/LoopKit/Loop/issues.

Generated: 2019-08-22 14:07:14 +0000

Loop v1.10.0dev

## DeviceDataManager
* launchDate: 2019-08-22 12:50:45 +0000
* lastError: Optional((date: 2019-08-22 14:03:54 +0000, error: ShareClient.ShareError.loginError(errorCode: "SSO_AuthenticatePasswordInvalid")))

## G6CGMManager
latestReading: nil
transmitter: CGMBLEKit.Transmitter
dataIsFresh: false
providesBLEHeartbeat: false
## ShareClientManager
latestBackfill: nil

observers.count: 0

**Comment by Kdisimone** [comment]
Dexcom is having share server issues that have crippled their password management. Delete the Share Server account from within your CGM in Loop settings. Use only the transmitter ID and keep the share server account information blank/deleted. That should get you back to good working order.

**Comment by ashbyakgm-marie** [comment]
Thank you Katie,

I completed the steps you provided yesterday and above.  It’s going odd, the loop is dispensing basal rates and when she eats she needs to Bolus by inputting the units needed.  The loop still shows as a grey circle and gives the glucose source error...

Amy

Any Ashby
713-503-1180

________________________________

**Comment by Kdisimone** [comment]
Can you grab a screenshot of your cgm setting from Loop?  The page where your transmitter ID is showing, scroll all the way down to the bottom of that screen and let’s double check that share account is emptied?  You can post pic here by dragging and dropping the screenshot into comment box.

**Comment by ashbyakgm-marie** [comment]
Yes, my daughter is at school.  I’ll send the screenshot once I pick her up ~3:30pm CST.  Thank you!

Any Ashby
713-503-1180

________________________________

**Comment by ashbyakgm-marie** [comment]
[Image][Image][Image]
Any Ashby
713-503-1180
________________________________
