### ISSUE TITLE
Feature Request: Omnipod-testing: RileyLink battery level monitor

### ISSUE THREAD

**Issue by rhinographix** [LoopKit/Loop#1080]
I'm not sure if this is a feature already being worked on, or if it may already exist, and I'm not seeing it, but it would be nice to have a battery level indicator inside the Loop app and/or posted to the "Batteries" section of the Notification screen on the iPhone that showed the percentage of battery life left on the RileyLink (much like you can with a connected Apple Watch or Apple Pencil on iPad)
![notification-screen](https://user-images.githubusercontent.com/53888192/63666428-210c0080-c795-11e9-858b-6ec6d29f0500.PNG)

I looked under Pod settings and found that the RileyLink shows a dB value, in my experience dB usually stands for decibels, so I'm assuming this is some kind of measure of signal strength between the RileyLink and the Phone, but I see no status of the battery. 

There have been nights where I forget to take the Riley Link out of my pocket at night, and forget to charge it until I wake up in the morning, so it only gets to charge for about an hour before going to work, so it'd be nice to know if that's enough, or if I need to bring a cable with me to work to continue charging.
![pod-settings](https://user-images.githubusercontent.com/53888192/63666429-210c0080-c795-11e9-85ff-e3ee02b0f6e1.PNG)

Above all, I appreciate all efforts on the program so far.

**Comment by elnjensen** [comment]
The RileyLink has no on-board hardware that measures the voltage, so this isn’t possible without a hardware redesign and shipping new RileyLinks.

**Comment by rhinographix** [comment]
Ok. Just thought I’d check. 

Thank you. 
Ryan
