### ISSUE TITLE
Loop not receiving Dexcom G6 cgm data for extended periods

### ISSUE THREAD

**Issue by NRiggall** [LoopKit/Loop#1082]
[](url)
Issue: 
At times I will notice that I'm not Looping (red circle) and it states, 
"The Operation Couldn't Be Completed. (Cgmblekit.Transmittererror Error 1.) 
Error enabling notification: timeout"

The Dexcom area in the top bar still shows the last received bg value (from 1:30h ago). When I click on it - it takes me to the normally functioning Dexcom G6 Mobile app. 

Last time this happened, restarting my iPhone fixed it. This time, I captured some screenshots and logs from the time the issue affected me: (stopped at 10:11AM, still not getting data @ 2019  Aug  30  11:40AM) 

Let me know if I can provide more useful information. 

Logs: https://drive.google.com/file/d/1RqGY8FEqG_IHs2ccWwMYXG6DULBANl8H/view?usp=sharing 

![Image from iOS](https://user-images.githubusercontent.com/36172962/64044224-21045b80-cb1b-11e9-8e9a-499d9dd72921.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/36172962/64044248-2a8dc380-cb1b-11e9-957d-f51dc26f83e2.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/36172962/64044249-2b265a00-cb1b-11e9-8fb6-31142825e19d.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/36172962/64044250-2b265a00-cb1b-11e9-9d50-4737410add23.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/36172962/64044251-2b265a00-cb1b-11e9-9a4c-dad893e7c1a4.png)

**Comment by NRiggall** [comment]
It is now 2019  Aug  30  01:43PM and Loop is picking up new Dexcom Mobile written readings (to health) written after the three hour delay - Loop never recovered to pick up current bg's from Dexcom Mobile. I'm now restarting phone.

**Comment by ps2** [comment]
Is this using the updated G6 support that was pushed to most branches a month or so ago?

**Comment by cboyers1** [comment]
Hi, my son is using Loop and is having this same error,"The Operation Couldn't Be Completed. (Cgmblekit.Transmittererror Error 1.)
Error enabling notification: timeout"

We have a greyed out Loop circle though and nothing we do seems to get the error to go away.  Were you able to resolve this or any suggestions?

**Comment by kpedretti** [comment]
> Hi, my son is using Loop and is having this same error,"The Operation Couldn't Be Completed. (Cgmblekit.Transmittererror Error 1.)
> Error enabling notification: timeout"
> 
> We have a greyed out Loop circle though and nothing we do seems to get the error to go away. Were you able to resolve this or any suggestions?

Was there a fix for this?  Mine has been having this same error for 3 days now.

**Comment by Kdisimone** [comment]
Restart your Loop app
Restart your Rileylink
Wait 5-10 min

Also make sure you've updated your Loop app

**Comment by anderser** [comment]
This just happened to us as well. Loop 2.0 on iPhone SE with latest OS and Dexcom app. 
The Dexcom app showed correct values and was updated, but Loop app first had incorrect value (old value) for a while, then no value and error message as in screenshot. 

Did the following to try to resolve: 
* Restarted Loop app and Dexcom app
* Turned Bluetooth off and on and restartet all apps
* Restarted RileyLink. Waited several minutes minutes. Still no signal in Loop. Dexcom app fine and showed updated values. 
* As a last resort I removed the Dexcom CGM from Loop settings and added it back again. After missing one more reading, suddenly glucose values from Dexcom was back in Loop and Loop turned green. 

The Dexcom transmitter has soon reached it's 3 month end-of-life (in 3 days), but in my head if that was the trouble, I would suppose that the Dexcom app would have problem getting BT-readings as well?

Attaching Loop report. This was exported about 20 minutes prior to glucose values returning in Loop app. 

[Loop Report 2020-01-07 20_55_01+01_00.md.zip](https://github.com/LoopKit/Loop/files/4032699/Loop.Report.2020-01-07.20_55_01%2B01_00.md.zip)
![IMG_0033](https://user-images.githubusercontent.com/88008/71933463-7e33ac00-31a2-11ea-914a-a08f7050945d.PNG)

**Comment by ericalina09** [comment]
Lately, every evening when my daughter goes to sleep, loop stops looping even though there is a bg value on Dexcom.  There is no BG on the loop app though.  I have attached the report and a picture of the latest error message....

 [Loop-Report-2020-03-07-20_46_40-08_00.md](https://loop.zulipchat.com/user_uploads/8196/mcq9kpjH4-mMip9WN9fcpN_y/Loop-Report-2020-03-07-20_46_40-08_00.md) 
[IMG-7340.jpeg](https://loop.zulipchat.com/user_uploads/8196/tk5ON70GxNEBTw4Wlo66h0TZ/IMG-7340.jpeg)

**Comment by ericalina09** [comment]
With troubleshooting, we are able to fix the looping.  However, this problem keeps reoccurring.  Anything I can do to prevent this?

**Comment by francesc0-cgm** [comment]
Same here, look at this too
https://github.com/LoopKit/Loop/issues/837#issuecomment-595872517

Which phone are you using to loop?

**Comment by ericalina09** [comment]
iPhone 6
