### ISSUE TITLE
dev branch not showing temp basal rates in Nightscout basal Pill

### ISSUE THREAD

**Issue by jdsnyc** [LoopKit/Loop#1083]
Now that the 'omnipod_testing' branch is closed, I would like to transfer over to the  'dev' branch, but the dev branch is not showing temp basal rates in Nightscout basal Pill.  I've most recently tested this yesterday.

I am using xcode 10.2, Nightscout 1.4version. , Dexcom G5. Loop V1.10.0DEV

The 'omnipod_testing' branch does show the loop temp basals being used, preceeded by a 'T:' in the NS basal Pill.  

The 'dev' branch however, only shows the NS profile inputted basal rate in the basal pill. 
Can you let me know if this can be updated, and/or how I can edit/update/push the code in the 'dev' branch build to accomplish this.  

It has been mentioned that this may be specific to the 'Omnipod' pump being used, as others who use Medtronic are seeing the temp basal rates in NS using the 'dev' branch. 
Thanks, 
John
p.s. Thank you all for everything you've done to make the looping possible.  VERY much appreciated.

**Comment by glebivanov** [comment]
It affects not just the basal pill, but also the basal chart series too. It feels like there is a latency of 10-20 minutes. So the historic basal is correct, but the recent one is not. Maybe it's not time-specific though. Maybe not all events are triggering the NS update.

**Comment by glebivanov** [comment]
I propose closing this issue. The latest dev build seems to be working correctly.

**Comment by Kdisimone** [comment]
Use the Loop pill to see basal rates. It will have a time stamp associated with the basal rate, which will help you more than NS's basal pill.  Updating instructions are in Loopdocs.org
