### ISSUE TITLE
Alert for when maximal basal is reached

### ISSUE THREAD

**Issue by moranyassour** [LoopKit/Loop#1087]
For us, the best indication of whether we need to intervene is whether the max basal has been reached. 
If we could have an alert for it, it would be great. 
thanks so much for all your work!

**Comment by rfmurphy81** [comment]
Agree! Would love to see this!

**Comment by mgunns** [comment]
I agree as well.

**Comment by ZombieEleos** [comment]
This is a wonderful idea.
