### ISSUE TITLE
No Reservoir Data

### ISSUE THREAD

**Issue by Salasclan1** [LoopKit/Loop#1093]
**Describe the bug**
Under INSULIN DELIVERY there is no data history for the Reservoir.  There is data for Event History.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.
[Loop Report 2019-09-07 16_39_25-05_00.md.txt](https://github.com/LoopKit/Loop/files/3587062/Loop.Report.2019-09-07.16_39_25-05_00.md.txt)

**To Reproduce**
1. Go to 'Open Loop App'
2. Click on 'Insulin Delivery'
3. Click on 'Reservoir'
4. See error - 'No Data'

**Expected behavior**
I hope to get steps on how to fix the Loop app, give me Reservoir data history. 

**Screenshots**
![IMG_0002](https://user-images.githubusercontent.com/18433629/64480614-76321400-d190-11e9-8fdf-6c2108bc5dbc.PNG)

**Phone**
 - Hardware: iPhone 6S
 - OS Version: iOS 12.1.4

**Loop Version**
 - Version Number: V1.10.0DEV
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: DK

**Additional context**
Had an issue with whether or not a bolus gave insulin since I did not hear clicks.  Using the Reservoir data would have been helpful

**Comment by Kdisimone** [comment]
Omnipod does not record reservoir values until below 50U remaining. Same behavior is with PDM. Sorry, just a pod thing.
