### ISSUE TITLE
No pump data, Loop forecast line, temp basals on NS website

### ISSUE THREAD

**Issue by Salasclan1** [LoopKit/Loop#1099]
**Describe the bug**
Today my son went to school while first time Looping, the pump along with the pink forecast line and basal rates were not uploading to the nightscout website.  It will go hours without showing any updates.  This only happens when he is inside his classroom.  When he goes outside for recess or after dismissal, the pump data comes back up.  I asked the school nurse to check the Loop app and the loop green circle is fully green (from what she told).  So the RL is communicating with the cell phone but the cell phone is not sending the pump data.  Also his iPhone is connected to the school wi-fi, celullar data is very low in the school.  I can see the Dexcom data and AR2 forecast.

**Attach an Issue Report**
[Loop Report 2019-09-09 21_48_08-05_00.txt](https://github.com/LoopKit/Loop/files/3593471/Loop.Report.2019-09-09.21_48_08-05_00.txt)

**To Reproduce**
Will need to go to his school to reproduce the error.  

**Expected behavior**
I wonder if there is an update I'm that I'm missing.  Or steps I need to make so I get the pump looop data.

**Screenshots**
during school - 
![Screenshot_20190909-101620_Chrome](https://user-images.githubusercontent.com/18433629/64580942-dd48f780-d34d-11e9-861d-b456f6df93c6.jpg)

![Screenshot_20190909-150125_Chrome](https://user-images.githubusercontent.com/18433629/64580814-5b58ce80-d34d-11e9-9caa-b9190b480cf5.jpg)

after school - 
![Screenshot_20190909-151146_Chrome](https://user-images.githubusercontent.com/18433629/64580824-627fdc80-d34d-11e9-9c39-fdb2fdc9d503.jpg)

Phone
Hardware: iPhone 6S
OS Version: iOS 12.1.4

Loop Version
Version Number: V1.10.0DEV
Repo: LoopKit/Loop

CGM
Device: Dexcom G6
Manager app: Dexcom App

Pump
Manufacturer: Omnipod
Model: Eros
Firmware version: DK

**Additional context**
I've read other threads that mention, the antenna being too week, or the phone case maybe the issue, but the iPhone and RL are in the same fanny bag that my son carries.  The report I am submitting is not the report from when was happening and I couldn't take screen shots.  He was at school and I was at work.

_Thanks for all that you do!!_

**Comment by sleibrand** [comment]
Is the school wifi blocking the uploads? Does it always fail to upload on wifi, and only succeed over cellular?

**Comment by Salasclan1** [comment]
I will check on that, it is a possibility that it blocks uploads. They have two wifi connections and thru connected him to one. I will ask this morning.

**Comment by Salasclan1** [comment]
Today, the Loop app is working intermittently during the day at school and I'm seeing pump data so the issue is resolved.  I will ask for the other wi-fi password if the issue comes up again.
