### ISSUE TITLE
Loop does not install on AppleWatch 

### ISSUE THREAD

**Issue by GerhardFuehrer** [LoopKit/Loop#1100]
I installed loop on my iPhone, but the installation on my Apple Watch fails. If I prompt "install" on the WatchApp it runs up to 100 % but then breaks off for no apparent reason and starts installing again over and over. Restarting the iPhone and the Watch didn't work. The app on the iPhone is working fine.
If I select my iPhone + AppleWatch in Xcode it says: "Unavailable Device" and (paired device unable for development).
A tiptool says: There was an error preparing "AppleWatch" for development. Try reattaching the device to which "Apple Watch" is paired. This device is no longer connected.

I already have reinstalled Loop 5 times now, which took a lot of time and made not change at all.

What can I do?

![IMG_8959](https://user-images.githubusercontent.com/54687194/64721338-89185180-d4cc-11e9-90a2-62421a9420b0.jpeg)

![Bildschirmfoto 2019-09-11 um 19 21 13 (2)](https://user-images.githubusercontent.com/54687194/64719927-9718a300-d4c9-11e9-95bc-ce9c3f15ca24.png)

**Phone**
 - Hardware: iPhone 6
 - OS Version:  iOS 12.4.1]

**Watch**
- AppleWatch 2
- WatchOS 4.3.2

**Loop Version**
 - Version Number: 1.10.0DEV-SPIKE
 - Repo: [Spike]

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [Spike]

**Pump**
 - Manufacturer: [Omnipod]

**Comment by shainey** [comment]
Hi GerhardFuehrer, I had the same problem and for me, it was the Deployment Target value. If you're updating your watch OS you should be up to 5.3 versus the 4.3 on your screenshot.  Change it to the OS for your watch and then update it again. This is covered on Loop Doc Build Errors at the bottom.

All the best, Steve

https://loopkit.github.io/loopdocs/build/build_errors/?fbclid=IwAR3gW22_WCp-ubguEPQTKtqYFhiI9T3Fp8WK1DlY_YM4wRZZQYwHyepOdqA
