### ISSUE TITLE
Active Time Displays "X days, 24 hours" instead of "X+1 days"

### ISSUE THREAD

**Issue by damonbayer** [LoopKit/Loop#1102]
**Describe the bug**
Active Time Displays "X days, 24 hours" instead of "X+1 days" when rounding hours ahead.

**To Reproduce**
1. Wait until some multiple of 24 hours have nearly passed since pod activation.
2. Click on Pod Settings
3. See error in "Active Time"

**Expected behavior**
Active Time should show "X+1 days"

**Screenshots**
![IMG_1015](https://user-images.githubusercontent.com/8095080/64837809-14fdac80-d5a5-11e9-939c-02f36974d3eb.PNG)

**Phone**
 - Hardware:  iPhone XR
 - OS Version: iOS 12.4.1

**Loop Version**
 - Version Number: <https://github.com/LoopKit/LoopWorkspace/commit/2050a8023c3fed4767e21dbb692ae6ebcec94787>
 - Repo: Dev

**Comment by marionbarker** [comment]
This can be closed with Loop v2.2.5 which displays Pod Active Clock as hr and min.
