### ISSUE TITLE
Prediction on Loop Screen says bg eventually -1,100

### ISSUE THREAD

**Issue by ericalina09** [LoopKit/Loop#1103]
My daughters loop screen says her bg will eventually be -1,100. What should I do

**Comment by Kdisimone** [comment]
answered in FB

**Comment by sleibrand** [comment]
Capture an issue report with full details.

**Comment by ericalina09** [comment]
Kadie, I don’t understand what the answer is  on Facebook. What do I need to adjust?

**Comment by Kdisimone** [comment]
Open Loop and wait 6 hours for the issue to age out. And, then read comments about how there is a known bug causing dramatic predictions when you use overrides with limited duration and cancel them early/reset new ones. This has been addressed in fixes in dev branch now...but you need to open loop and read the comments people have provided.

**Comment by ericalina09** [comment]
So will Loop still be able to function properly for these 6 hours?

**Comment by Kdisimone** [comment]
You will not be "looping"...that's the point. You will be using scheduled basals, not using "Loop's basal adjustments". You can still give boluses with Loop though.

**Comment by Kdisimone** [comment]
maybe define "function properly"...yes, you will get scheduled basals for the 6 hours. The docs cover this...perhaps reread the sections about what happens when using open loop.
