### ISSUE TITLE
Omnipod Frequency issue

### ISSUE THREAD

**Issue by snooks55** [LoopKit/Loop#1105]
**Describe the bug**
When paired to the omnipod, the frequency of the rileylink flips back and forth from the necessary omipod frequency of 433 to the medtronic frequency of 916.541 MHZ

**Attach an Issue Report**
I ran this on my son's phone and the uploader doesn't support the file type. I'm not an iphone/mac person so I'm not sure what to do. i did do an xcode log. 

**To Reproduce**
Frequency is just wrong. I'll attach screen shots. 

**Expected behavior**
I expected the RL to have the correct frequency and stay connected to the omnipod. We are unable to bolus insulin. .

**Screenshots**
added below. 

**Phone**
 - Hardware:iPhone 6S
 - OS Version:  iOS 12.4.1

**Loop Version**
 - Version Number: v1.10.0dev-jojo-beeps
 - Repo: ?

**CGM**
 - Device: [Dexcom G6
 - Manager app: . Dexcom App, 
**Pump**

 - Manufacturer: Omnipod
 

**Additional context**
git hub link
https://gist.github.com/snooks55/9324a47f6849893c4f18be978f75c08e
![IMG_0001](https://user-images.githubusercontent.com/3136433/64903520-f1effd00-d677-11e9-8105-b64aa4f5d9ed.PNG)
![IMG_0002](https://user-images.githubusercontent.com/3136433/64903521-f4eaed80-d677-11e9-8316-f1bfe69df4f1.PNG)

**Comment by snooks55** [comment]
https://gist.github.com/snooks55/829c2c5469fe246eaec5827fc858ec4f
6 minute xcode export while loop was running on frequency 916.541 MHz

**Comment by ps2** [comment]
In this log, it looks like Loop set the frequency properly on the RL. If you keep having this issue, could you record Loop starting, and then going to the settings page where you were seeing the 915Mhz?

**Comment by jlucasvt** [comment]
I am testing an RL and Pod here with the exact same issue.  RL was returned because of an intermittent communications failure.

I restarted Loop , Ran "Test Commands" , and Frequency is now correct.  I will continue to test this one today on me.

[Loop Report 2019-10-15 11:09:27-04:00.txt](https://github.com/LoopKit/Loop/files/3730063/Loop.Report.2019-10-15.11.09.27-04.00.txt)
![UNADJUSTEDNONRAW_thumb_6496](https://user-images.githubusercontent.com/19819388/66844912-27209100-ef3d-11e9-916b-50104f009f89.jpg)

**Comment by jlucasvt** [comment]
Loop Report after restart and frequency is correct.

[Loop Report 2019-10-15 11:18:50-04:00 (after restart).txt](https://github.com/LoopKit/Loop/files/3730077/Loop.Report.2019-10-15.11.18.50-04.00.after.restart.txt)

**Comment by jlucasvt** [comment]
About 12 minutes later same issue. (tried "test commands") got "no response"
Restarted loop and Frequency is now correct and "test commands" got "success"

[Loop Report 2019-10-15 11:31:58-04:00-withissue.txt](https://github.com/LoopKit/Loop/files/3730164/Loop.Report.2019-10-15.11.31.58-04.00-withissue.txt)

**Comment by jlucasvt** [comment]
I will continue to test but as it requires loop to be restarted to run I may just swap out in a few hours back to my normal RL.  (bummer we can't swap RL's like with medtronic).

**Comment by itsmojo** [comment]
There is no reason why you cannot swap a RL for Omnipod like you do for a Medtronic. The Omnipod session state is all in Loop and that state is persistent across rebuilds (unless you are doing something like building with a totally different ID). Feel free to swap those RL's ...
