### ISSUE TITLE
Switching from suspended MDT 515 to Omnipod issues

### ISSUE THREAD

**Issue by sefish99** [LoopKit/Loop#1107]
I tore out my medtronic site accidentally and decided to switch to an omnipod for the weekend. I failed to unsuspend the pump prior to deleting the mdt pump and changing to the omnipod. I delete the medtronic, enter all the info for the pod, activate and start the pod, go to the main loop screen and I see "pump suspended tap to resume" on the top bar. I tap the bar and the pod screams. Now it says put a new pod. I put the battery back in my pump, added it to the loop, unsuspend it through the loop, delete the mdt, and add the omnipod. I activate and put on the new pod no issues, and I go back to the main screen and the same thing - Pump suspended. And it said I needed to activate a pod? - even though I had already gone through all of those screens. I tried activating my current pod - didn't work. 

I take a break and all of a sudden I hear a pod basal click. Loop still says pump suspended. Nightscout says I'm getting my normal basal, however the pump info on nightscout for my medtronic pump (prior to change) and not my omnipod. Nightscout also shows that I have resumed delivery multiple times also.

I thought I'd try to rebuild loop to see if anything might change? I rebuilt but nothing is different. I give up and finally click Tap to Resume and just get an error (no screaming this time though) which I didn't screenshot.

I was able to connect the medtronic, prime and get it reconnected. Loop recognized everything correctly thankfully.

**To Reproduce**
1. suspend mdt pump and delete from loop
2. add omnipod, activate and start
3. go back to loop main screen...pump still suspended and stuck on old mdt info.
4. Tap to Resume and pod with error.

**Expected behavior**
When I switched pumps, I thought Loop would delete mdt and status and allow me to continue with omnipod.

![UNADJUSTEDNONRAW_thumb_1f51c](https://user-images.githubusercontent.com/16831963/64916900-853f3600-d73d-11e9-94e9-b52c15ad4d92.jpg)
![UNADJUSTEDNONRAW_thumb_1f51d](https://user-images.githubusercontent.com/16831963/64916901-853f3600-d73d-11e9-8377-2164289ef050.jpg)
[Loading....pdf](https://github.com/LoopKit/Loop/files/3613413/Loading.pdf)

**Phone**
 - Hardware: Iphone XR
 - OS Version: 12.4

**Loop Version**
 - Version Number: V1.10.0DEV-JOJO-X15-FIX
 - Repo: Katie

**CGM**
 - Device: G6
 - Manager app: Dexcom

**Pump**
 - Manufacturer: Medtronic
 - Model: 515
 - Firmware version: 2.2A 1.1

**Additional context**
I'm also using omnipod rileylink with medtronic pump (since my mdt riley is no longer connecting) but I haven't had any issues with connectivity. Riley stays right next to my mdt pump in my pocket at all times.

**Comment by ps2** [comment]
This is fixed in dev.
