### ISSUE TITLE
HUD incorrect temp basal time

### ISSUE THREAD

**Issue by BenRepak** [LoopKit/Loop#1110]
**Describe the bug**
When viewing my HUD temp basal display, I notice an incorrect time stamp only when running at standard basal rate. When temp basal is occurring, the time stamp is correct. But when temp basal rate returns to +0.0, the past incorrect time stamp returns. Whenever the timestamp is incorrect, it always shows the same time 10:23 PM). 

Restarting phone and RileyLink did not resolve. 

**Attach an Issue Report**
Attached

**To Reproduce**
1. View HUD temp basal timestamp with 0.0 rate
2. View HUD temp basal timestamp with a changed rate
3. View HUD temp basal timestamp after returning to 0.0 rate

**Expected behavior**
I expect the timestamp for temp basal to show the most recent time the basal rate changed. 

**screenshots**
See below

**Phone**
 - Hardware: iPhone X
 - OS Version: iOS 12.4.1

**Loop Version**
 - Version Number: 1.10.1
 - Repo: LoopKit/Loop Dev branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod 

**Additional context**
Attaching screenshots and issue report

![BC003912-57FA-40AE-805B-D9118BCD09AE](https://user-images.githubusercontent.com/34491091/64937903-4aaacb80-d819-11e9-8482-167037f37e17.png)
![E69530FC-CFE4-427C-9294-59DB84182F24](https://user-images.githubusercontent.com/34491091/64937904-4aaacb80-d819-11e9-8f69-87010bd0ee09.png)
![F05874BD-EDF2-48AA-9168-D539873612C5](https://user-images.githubusercontent.com/34491091/64937905-4aaacb80-d819-11e9-99bb-d83ce48f1e91.png)
![F4EFE393-CC21-4A2B-9284-F7E055DDCC4B](https://user-images.githubusercontent.com/34491091/64937906-4aaacb80-d819-11e9-832f-bfeef451ae20.png)

**Comment by HowardLook** [comment]
Also seeing this issue. Let me know if an additional screenshot and issue report would be helpful.

**Comment by Trpl7ca** [comment]
I also have the same indication.

**Comment by ps2** [comment]
This should be fixed in dev with https://github.com/ps2/rileylink_ios/pull/552

**Comment by BenRepak** [comment]
Downloaded most recent dev branch today and this appears to be resolved. I’ll keep an eye out for any issues after my next pod change. Thank you!

**Comment by Kdisimone** [comment]
@ps2 reopening for MDT pumps

**Comment by jath622** [comment]
Having this issue with the latest dev version on iOS 13.3, iPhone 7+. Loop dev rebuilt 3 times since thanksgiving figuring this error was something I did wrong. Happy to forward an issue report if it would help Pete or Katie to look at it.

**Comment by ps2** [comment]
Fix for MDT here: https://github.com/ps2/rileylink_ios/commit/2888970adca367922b436d5245e26b0738700c07

**Comment by Kdisimone** [comment]
Thank you @ps2 !
