### ISSUE TITLE
Riley Link Error 

### ISSUE THREAD

**Issue by Janagaston** [LoopKit/Loop#1111]
**Describe the bug**
Riley Link stopped working after a few days of use.  Gave Riley Link Error. 

**Attach an Issue Report**
Report attached
[Loop issue.docx](https://github.com/LoopKit/Loop/files/3619136/Loop.issue.docx)

**To Reproduce**
1. Go to Loop on phone
2. Click on Settings
3. Click on issue report

**Expected behavior**
I just expect it to work and it has stopped. 

**Screenshots**
I can do this if needed but its pretty straight forward. 

**Phone**
 - Hardware: Iphone 8
 - OS Version: [e.g. iOS 12.4.1

**Loop Version**
 - Version Number:  1.9.6
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device:  Dexcom G6
 - Manager app:  Dexcom App

**Pump**
 - Manufacturer:  Medtronic
 - Model: 515
 - Firmware version: 1.2A 1.1 0B 0B]

**Additional context**

**Comment by Kdisimone** [comment]
Did you try rebooting the rileylink by switching it off/on at its physical switch on the side? Have you double checked that the battery is plugged in entirely?  What are the lights on the board doing?  A picture of the battery plug may also help so we can verify

**Comment by Janagaston** [comment]
So my Riley Link mysteriously fired up.  I had changed the battery in my pump.  I am to have surgery here pretty soon and I need to make sure I can rely on this.  Any idea to what caused it to stop working for 2 days?

**Comment by Janagaston** [comment]
Here is a picture.  The battery appears plugged in all the way.  When charging it has a red light.  The green light is on normally.  When I turn the Riley off and on I see the blue light blink.  
![UNADJUSTEDNONRAW_thumb_4011](https://user-images.githubusercontent.com/54345355/65072408-754e6e80-d956-11e9-82d7-03b6b3f0de67.jpg)

**Comment by Kdisimone** [comment]
Proper place for troubleshooting these kind of issues is in Zulipchat's RileyLink stream, thanks! Link to zulipchat is in Loopdocs.
