### ISSUE TITLE
Can't build IPA with latest Dev with Xcode 11-2.

### ISSUE THREAD

**Issue by rsilvers129** [LoopKit/Loop#1117]
I am using the latest Dev and Xcode 11-2. I can build Loop for my phone, but when I try to Archive to make an Ad-Hoc IPA, it says IPA Processing Failed. It seems like part of MiniMed Plugin is having an issue. I see this in the logs:

2019-09-20 02:21:44 +0000 Scanning IPA...
2019-09-20 02:21:46 +0000 Assertion failed: Expected 2 archs in otool output:
/var/folders/8k/7c4406k90ds6vhz585ljmx140000gp/T/IDEDistributionOptionThinning.~~~kZyTmZ/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin:
Mach header
magic cputype cpusubtype caps filetype ncmds sizeofcmds flags
MH_MAGIC_64 X86_64 ALL 0x00 DYLIB 24 3136 NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
Load command 0

**Comment by FlorinBv** [comment]
I have the same issue since few weeks. The problem is not with the Xcode 11, but with the DEV version. I have no issues on creating the IPA with Omnipod-testing version.

**Comment by ludoded** [comment]
I'm having the same issue, any known workaround?

**Comment by ps2** [comment]
You can try this PR: https://github.com/LoopKit/Loop/pull/1126

**Comment by ludoded** [comment]
> You can try this PR: #1126

Doesn't work for me

**Comment by josep1972** [comment]
@ludoded : Can you be more specific as to what you are seeing?

**Comment by ludoded** [comment]
While trying to upload build to AppStore I got this error:

![Скриншот 2019-10-11 00 39 07](https://user-images.githubusercontent.com/4401289/66608589-9570f680-ebbf-11e9-917a-fb71330ca233.png)

And this is the log file while I got the error:
[IDEDistributionPipeline.log](https://github.com/LoopKit/Loop/files/3714725/IDEDistributionPipeline.log)

**Comment by josep1972** [comment]
@ludoded Is hard to understand what you did from the log provided, but it does not seem like you re-built before distributing. In order you make sure this PR fixes the distribution problem, you have to re-Archive and then distribute. You can also run the Validate app step first, which I find to be easier to debug.

**Comment by akashnsmahaswami** [comment]
I have the same issue with DEV version. Omnipod-testing version worked fine for me.
Mac OS-10.14.5
Xcode-11.1
I'am able to get build for my phone and simulator. But not able to **archive** and upload the Loop.
![Screenshot 2019-10-18 at 3 36 41 PM](https://user-images.githubusercontent.com/56542311/67192970-2773cd00-f412-11e9-8840-63a8cb67fe22.png)

**Comment by prassein** [comment]
i have the same issues. it seems the wrapper extension of MinimedKitPlugin target in the rileylink_ios project is incorrect. change it to "framework" would fix the issue.

I fork the rileylink_ios project.  Change the wrapper extension of MinimedKitPlugin target from "loopplugin" to "framework". 

![image](https://user-images.githubusercontent.com/4159280/67837342-cb076080-fb29-11e9-98bb-5c59b2748187.png)

Then i change the cartfile  to use [github "prassein/rileylink_ios" "dev"]
![image](https://user-images.githubusercontent.com/4159280/67837170-65b36f80-fb29-11e9-9011-ebae3d696a48.png)

**Comment by akashnsmahaswami** [comment]
> i have the same issues. it seems the wrapper extension of MinimedKitPlugin target in the rileylink_ios project is incorrect. change it to "framework" would fix the issue.
> 
> I fork the rileylink_ios project. Change the wrapper extension of MinimedKitPlugin target from "loopplugin" to "framework".
> 
> ![image](https://user-images.githubusercontent.com/4159280/67837342-cb076080-fb29-11e9-98bb-5c59b2748187.png)
> 
> Then i change the cartfile to use [github "prassein/rileylink_ios" "dev"]
> ![image](https://user-images.githubusercontent.com/4159280/67837170-65b36f80-fb29-11e9-9011-ebae3d696a48.png)

I followed above steps but still getting same error.

**Comment by akashnsmahaswami** [comment]
> i have the same issues. it seems the wrapper extension of MinimedKitPlugin target in the rileylink_ios project is incorrect. change it to "framework" would fix the issue.
> 
> I fork the rileylink_ios project. Change the wrapper extension of MinimedKitPlugin target from "loopplugin" to "framework".
> 
> ![image](https://user-images.githubusercontent.com/4159280/67837342-cb076080-fb29-11e9-98bb-5c59b2748187.png)
> 
> Then i change the cartfile to use [github "prassein/rileylink_ios" "dev"]
> ![image](https://user-images.githubusercontent.com/4159280/67837170-65b36f80-fb29-11e9-9011-ebae3d696a48.png)

Thank you. Your fix worked for me after changing one more line in my **Cartfile.resolved** file, I changed **github "ps2/rileylink_ios" "88530730f45c6a846f9bb9b2d87893b1350993e2"**
to
**github "prassein/rileylink_ios" "87a3450a0075f2fa9e9759415e8a8a67bb77a4c7"** fixed my issue.
![Screenshot 2019-10-31 at 4 13 00 PM](https://user-images.githubusercontent.com/56542311/67940319-6287b480-fbf9-11e9-9c75-2539bed4310a.png)

**Comment by akashnsmahaswami** [comment]
**Pump list is not visible with the above changes**, if app is installed to device (iPhone 5s, iOS-12.4.1) from Xcode. Pump lists are showing in simulator but not in device.

**Comment by sherribrinson** [comment]
Hi, I also had the same issue, so I followed the above solution, after that, the MinimedKitPlug.framework issue was fixed, but another new issue occurred by the changes.

I can't add any real pump device on Settings, only simulator is added.
![IMG_2397](https://user-images.githubusercontent.com/49903085/69679721-dab98c80-1076-11ea-91ce-efdb9bc81849.PNG)

Xcode version : 11.2.1
iphone 6
iOS : 12.4.3

**Comment by dekimsey** [comment]
XCode: 11.2
OSX: 10.14.6
Loop commit: v2.0

# Issue

When using the _App Store Connect_ option for distribution:

> Code signing "MinimedKitPlugin.framework" failed.

If I try to do a _Development Distribution_ instead I get the error:

> IPA processing failed

If I try to do a _Validation_ instead I get:

> Code signing "MinimedKitPlugin.framework" failed.
 
In any case, the error messages are the same.

Looking at the `IDEDistributionPipline.log` file I see the following (note a successful re-sign followed by the failure):
```
2020-01-02 19:55:14 +0000  Writing entitlements for <IDEDistributionItem: 0x7f9446c12b00; bundleID='com.rileylink.MinimedKit', path='<DVTFilePath:0x7f9446a0aa40:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKit.framework'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7f9446c02090; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7f9447af09a0; name='Apple Development: Daniel Kimsey (FAPJ9H4643)', hash='DEE45C74DFE46623B91099B8A0FBF688BD29786D', serialNumber='538C57883360C264', certificateKinds='(
    "1.2.840.113635.100.6.1.12",
    "1.2.840.113635.100.6.1.2"
), issueDate='2020-01-02 14:49:42 +0000''>', entitlements='(null)', teamID='5SS92Q63F5', identifier='com.rileylink.MinimedKit', executablePath='<DVTFilePath:0x7f9447859ba0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKit.framework/MinimedKit'>', hardenedRuntime='0'>'> to: /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~VkLarG
2020-01-02 19:55:14 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' 'AF8DAA0E06C9F33BF55D58CB4FCFF64FE11DBA5D' '--entitlements' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~VkLarG' '--preserve-metadata=identifier,flags,runtime' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKit.framework'
2020-01-02 19:55:14 +0000  /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKit.framework: signed bundle with Mach-O universal (arm64) [com.rileylink.MinimedKit]
2020-01-02 19:55:14 +0000  /usr/bin/codesign exited with 0
2020-01-02 19:55:14 +0000  Entitlements for <IDEDistributionItem: 0x7f9447a62920; bundleID='com.rileylink.MinimedKitPlugin', path='<DVTFilePath:0x7f9445fa20b0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7f9447940f40; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7f9445e93f00; name='Apple Development: Daniel Kimsey (FAPJ9H4643)', hash='DEE45C74DFE46623B91099B8A0FBF688BD29786D', serialNumber='538C57883360C264', certificateKinds='(
    "1.2.840.113635.100.6.1.12",
    "1.2.840.113635.100.6.1.2"
), issueDate='2020-01-02 14:49:42 +0000''>', entitlements='(null)', teamID='5SS92Q63F5', identifier='com.rileylink.MinimedKitPlugin', executablePath='<DVTFilePath:0x7f9446bed1c0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin'>', hardenedRuntime='0'>'>: {
}
2020-01-02 19:55:14 +0000  Writing entitlements for <IDEDistributionItem: 0x7f9447a62920; bundleID='com.rileylink.MinimedKitPlugin', path='<DVTFilePath:0x7f9445fa20b0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7f9447940f40; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7f9446b8ab70; name='Apple Development: Daniel Kimsey (FAPJ9H4643)', hash='DEE45C74DFE46623B91099B8A0FBF688BD29786D', serialNumber='538C57883360C264', certificateKinds='(
    "1.2.840.113635.100.6.1.12",
    "1.2.840.113635.100.6.1.2"
), issueDate='2020-01-02 14:49:42 +0000''>', entitlements='(null)', teamID='5SS92Q63F5', identifier='com.rileylink.MinimedKitPlugin', executablePath='<DVTFilePath:0x7f9446bed1c0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin'>', hardenedRuntime='0'>'> to: /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~ni3DRd
2020-01-02 19:55:14 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' 'AF8DAA0E06C9F33BF55D58CB4FCFF64FE11DBA5D' '--entitlements' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~ni3DRd' '--preserve-metadata=identifier,flags,runtime' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework'
2020-01-02 19:55:14 +0000  /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework: replacing existing signature
2020-01-02 19:55:14 +0000  /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework: code object is not signed at all
2020-01-02 19:55:14 +0000  /usr/bin/codesign exited with 1
```

Notable bits of the above error log:
```
Loop.app/Frameworks/MinimedKitPlugin.framework: replacing existing signature
Loop.app/Frameworks/MinimedKitPlugin.framework: code object is not signed at all
/usr/bin/codesign exited with 1
```

# Resolution

I applied a cleaned up version of #1126 (the script, build steps, ignoring the other parts) **but** left the ps2/rileylink_ios commit ref at `v3.0`. I _suspect/hope_ the folks altering this value are why they might be experiencing wonkiness with device detection. I won't be able to verify this until I get it installed on my sister's device. But it might be worth tweaking the commit ref at Loop v2.0's default and test that.

Build Validation is mostly successful. App Store Connect fails to upload, but it appears to be a known issue with XCode 11.2 being deprecated but the App Store not yet showing 11.2.1 or something like that. Apparently this is known problem. Using the Ad Hoc distribution bypassed this issue enough for me to provide an ipa. Will update this comment when I can validate on a device in a few days.

**Comment by CrushingT1D** [comment]
akashnsmahaswami @prassein does this still work? I was not able to get the prassein branch to work (I think it may be outdated now) and the wrapperextension change throws this error for me 'Command PhaseScriptExecution failed with a nonzero exit code'

**Comment by azyet22** [comment]
> XCode: 11.2
> OSX: 10.14.6
> Loop commit: v2.0
> 
> # Issue
> When using the _App Store Connect_ option for distribution:
> 
> > Code signing "MinimedKitPlugin.framework" failed.
> 
> If I try to do a _Development Distribution_ instead I get the error:
> 
> > IPA processing failed
> 
> If I try to do a _Validation_ instead I get:
> 
> > Code signing "MinimedKitPlugin.framework" failed.
> 
> In any case, the error messages are the same.
> 
> Looking at the `IDEDistributionPipline.log` file I see the following (note a successful re-sign followed by the failure):
> 
> ```
> 2020-01-02 19:55:14 +0000  Writing entitlements for <IDEDistributionItem: 0x7f9446c12b00; bundleID='com.rileylink.MinimedKit', path='<DVTFilePath:0x7f9446a0aa40:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKit.framework'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7f9446c02090; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7f9447af09a0; name='Apple Development: Daniel Kimsey (FAPJ9H4643)', hash='DEE45C74DFE46623B91099B8A0FBF688BD29786D', serialNumber='538C57883360C264', certificateKinds='(
>     "1.2.840.113635.100.6.1.12",
>     "1.2.840.113635.100.6.1.2"
> ), issueDate='2020-01-02 14:49:42 +0000''>', entitlements='(null)', teamID='5SS92Q63F5', identifier='com.rileylink.MinimedKit', executablePath='<DVTFilePath:0x7f9447859ba0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKit.framework/MinimedKit'>', hardenedRuntime='0'>'> to: /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~VkLarG
> 2020-01-02 19:55:14 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' 'AF8DAA0E06C9F33BF55D58CB4FCFF64FE11DBA5D' '--entitlements' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~VkLarG' '--preserve-metadata=identifier,flags,runtime' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKit.framework'
> 2020-01-02 19:55:14 +0000  /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKit.framework: signed bundle with Mach-O universal (arm64) [com.rileylink.MinimedKit]
> 2020-01-02 19:55:14 +0000  /usr/bin/codesign exited with 0
> 2020-01-02 19:55:14 +0000  Entitlements for <IDEDistributionItem: 0x7f9447a62920; bundleID='com.rileylink.MinimedKitPlugin', path='<DVTFilePath:0x7f9445fa20b0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7f9447940f40; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7f9445e93f00; name='Apple Development: Daniel Kimsey (FAPJ9H4643)', hash='DEE45C74DFE46623B91099B8A0FBF688BD29786D', serialNumber='538C57883360C264', certificateKinds='(
>     "1.2.840.113635.100.6.1.12",
>     "1.2.840.113635.100.6.1.2"
> ), issueDate='2020-01-02 14:49:42 +0000''>', entitlements='(null)', teamID='5SS92Q63F5', identifier='com.rileylink.MinimedKitPlugin', executablePath='<DVTFilePath:0x7f9446bed1c0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin'>', hardenedRuntime='0'>'>: {
> }
> 2020-01-02 19:55:14 +0000  Writing entitlements for <IDEDistributionItem: 0x7f9447a62920; bundleID='com.rileylink.MinimedKitPlugin', path='<DVTFilePath:0x7f9445fa20b0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework'>', codeSigningInfo='<_DVTCodeSigningInformation_Path: 0x7f9447940f40; isSigned='1', isAdHocSigned='0', signingCertificate='<DVTSigningCertificate: 0x7f9446b8ab70; name='Apple Development: Daniel Kimsey (FAPJ9H4643)', hash='DEE45C74DFE46623B91099B8A0FBF688BD29786D', serialNumber='538C57883360C264', certificateKinds='(
>     "1.2.840.113635.100.6.1.12",
>     "1.2.840.113635.100.6.1.2"
> ), issueDate='2020-01-02 14:49:42 +0000''>', entitlements='(null)', teamID='5SS92Q63F5', identifier='com.rileylink.MinimedKitPlugin', executablePath='<DVTFilePath:0x7f9446bed1c0:'/Users/dkimsey/Library/Developer/Xcode/Archives/2020-01-02/Loop 1-2-20, 13.44.xcarchive/Products/Applications/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin'>', hardenedRuntime='0'>'> to: /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~ni3DRd
> 2020-01-02 19:55:14 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' 'AF8DAA0E06C9F33BF55D58CB4FCFF64FE11DBA5D' '--entitlements' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/entitlements~~~ni3DRd' '--preserve-metadata=identifier,flags,runtime' '/var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework'
> 2020-01-02 19:55:14 +0000  /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework: replacing existing signature
> 2020-01-02 19:55:14 +0000  /var/folders/rn/9821bpds6c3_4t2_x7kmd54d2n5085/T/XcodeDistPipeline.~~~5YuZJi/Root/Payload/Loop.app/Frameworks/MinimedKitPlugin.framework: code object is not signed at all
> 2020-01-02 19:55:14 +0000  /usr/bin/codesign exited with 1
> ```
> 
> Notable bits of the above error log:
> 
> ```
> Loop.app/Frameworks/MinimedKitPlugin.framework: replacing existing signature
> Loop.app/Frameworks/MinimedKitPlugin.framework: code object is not signed at all
> /usr/bin/codesign exited with 1
> ```
> 
> # Resolution
> I applied a cleaned up version of #1126 (the script, build steps, ignoring the other parts) **but** left the ps2/rileylink_ios commit ref at `v3.0`. I _suspect/hope_ the folks altering this value are why they might be experiencing wonkiness with device detection. I won't be able to verify this until I get it installed on my sister's device. But it might be worth tweaking the commit ref at Loop v2.0's default and test that.
> 
> Build Validation is mostly successful. App Store Connect fails to upload, but it appears to be a known issue with XCode 11.2 being deprecated but the App Store not yet showing 11.2.1 or something like that. Apparently this is known problem. Using the Ad Hoc distribution bypassed this issue enough for me to provide an ipa. Will update this comment when I can validate on a device in a few days.
> 
> **Update**: I confirmed the PR and keeping the rilelink_ios version at `v3.0` work correctly on the Loop v2.0 build. My sister was able to pair her omnipod successfully.

Hi, Can you help me out with this issue? I am also trying to build the app for my friend and I've never worked with scripts. Can you help me with the exact code you used? You can post it here or send to my email at azuka.okeke@gmail.com. Your assistant will be greatly appreciated.
Thanks!

**Comment by dekimsey** [comment]
Okay, so I ran into this again trying to build Loop v2.2, I've submitted my changes in the linked PR #1324. To test, I cherry-picked the changes onto v2.2.

**Comment by fbernaly** [comment]
I got this error when archiving the app for a friend. I can install the app in my device when iPhone is connected to Xcode, but I am getting: 

```
Code signing "MinimedKitPlugin.framework" failed
```

when archiving the app.

What is the fix? Can someone provide some guidance?

**Comment by fbernaly** [comment]
I got this error when archiving the app. The app runs in my device when iPhone is connected to Xcode12, but I am getting: 

```
Code signing "MinimedKitPlugin.framework" failed.
```

What is the fix? Can someone provide some guidance?

**Comment by haspden** [comment]
I'm trying to run 2.4 but getting the same issue with this still... @dekimsey  do you have a solution with 2.4 ?

**Comment by dekimsey** [comment]
I actually just did a new build today still using my fork. I'll see about getting the pr updated.

Does anyone know how to get dev attention on this issue or why it's gone unresolved for so long? I'm not an iOS developer, so I cannot really comment on why the changes are necessary.

**Comment by haspden** [comment]
Which fork @dekimsey ? Mind if I take a look to compare changes to my fork?

Thanks

**Comment by dekimsey** [comment]
@haspden See the PR, LoopKit/Loop#1324. It should have the necessary changes. Worked with XCode 12.3 on macOS 11.1.

**Comment by haspden** [comment]
Hmm... Still Struggling :/ 

![Screenshot 2021-01-07 at 21 58 06](https://user-images.githubusercontent.com/4039041/103949671-887ce300-5133-11eb-8607-9e59ad17fcf6.png)

**Comment by dekimsey** [comment]
@haspden The only other change I have on disk that's not commited is setting the `DEVELOPMENT_TEAM` to my apple developer account. Perhaps it has something to do with the signing? Other than that, I don't have anything else to offer. Be sure you are running an up-to-date OSX & XCode (I've run into issues with before)

**Comment by haspden** [comment]
got it working using https://github.com/LoopKit/Loop/tree/6b68fb24f38f34b3a45a2f095cb64af504487b58 in the end

**Comment by gestrich** [comment]
I was not able to use the above pull requests. I've added a PR for master which seems to overcome the issues I was having: [1489](https://github.com/LoopKit/Loop/pull/1489/commits/4a0839c1bf71fedbe7a449c7db21b728409aa7e0)
