### ISSUE TITLE
NSBluetoothAlwaysUsageDescription

### ISSUE THREAD

**Issue by SweetGeelz** [LoopKit/Loop#1118]
**Describe the bug**
Updated phone to iOS 13. Loop crashed/wouldn't open. Updated all software (see below)  Rebuilt app.  App crashed during setup upon adding OmniPod.  Kept iPhone plugged to Mac  after build and Health allow to see error in Debugger: NSBluetoothAlwaysUsageDescription needed.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
Rebuild app with new Xcode and iOS
1. tap Settings sprocket
2. Tap "Add Pump"
3. Tap Omnipod
4. Screen freezes

**Expected behavior**
During App setup, I expected to get the Riley Link screen when I hit OmniPod, move forward in setup

**Screenshots**
 I added another line in the Info.plist in Xcode to duplicate the description of  NSBluetoothPeripheralUsageDescription in order to get past the crash.  I forgot to take a screenshot of the error, but I have a screenshot of the line added in the editor.  
New line is about halfway down the screen:
<img width="1025" alt="Screen Shot 2019-09-20 at 9 35 33 AM" src="https://user-images.githubusercontent.com/52388136/65335490-21c46680-db8a-11e9-885b-9470bf968538.png">

**Phone**
 - Hardware: iPhone 8Plus
 - OS Version: 13
**Loop Version**
 - Version Number: 1.10.0dev build 55 (thought I was using Omnipod-testing but don't see that looking at Xcode now)
 - Repo: LoopKit/Loop
**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Eros
 - Firmware version: ?

**Additional context**
App also crashed when I went out of order and tried to setup the Dexcom G6 - I think same Bluetooth permission/dialogue issue.
Maybe not the correct approach, but it kept the app from crashing anymore...
These two links helped me get past the crash. 
https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothalwaysusagedescription?language=objc
https://stackoverflow.com/questions/57987863/nsbluetoothalwaysusagedescription-required-but-bluetooth-is-not-used

**Comment by Kdisimone** [comment]
resolved with the update above
