### ISSUE TITLE
Privacy concern when building Master Branch

### ISSUE THREAD

**Issue by lmacisaac** [LoopKit/Loop#1122]
Rebuilt master branch (I downloaded it this evening at approx 1830 from the LoopDocs page. Version 1.9.6). I am using Xcode 11, iOS13 on iPhone 7+, on a Mac with Mojave 10.14.6. I am using a paid developer account. I am running with a 722 Firmware 2.2A 1.1 and G6 with the Dexcom app.

On the first attempt the app would not open and kept closing within seconds. I tried rebooting the phone as well as turning off bluetooth and then turning it back on. That did not work so I deleted the loop app, restarted my phone and then rebuilt loop a second time. 

This second attempt started off with loading loop, asking for the permissions with apple health and then opened the screen to add my pump, cgm. It however is like the screen is locked here and the following is showing in Xcode. I attempted to close loop, reopen with no success. Now it appears as only a white screen. I turned the phone off and back on which unlocked the screen, however when selecting to add a pump the app now closes. Unable to attach Issue Report from app.

It appears to be a permission thing?!?! Not sure what to do from here.

Thank you. 

<img width="1439" alt="Screen Shot 2019-09-22 at 19 29 16" src="https://user-images.githubusercontent.com/54118793/65395454-6bbb7100-dd71-11e9-9dde-630fad6ee2f8.png">

![IMG_8668](https://user-images.githubusercontent.com/54118793/65395502-e5535f00-dd71-11e9-8392-32c033d8f9d6.PNG)

**Comment by Kdisimone** [comment]
Addressed now with https://github.com/LoopKit/Loop/commit/5df0b4c1110b99947461e6b5047930b18582128d

thank you
