### ISSUE TITLE
Insulin Delivery Doesn’t align with Health App or OmniPod screen 

### ISSUE THREAD

**Issue by duffer5** [LoopKit/Loop#1123]
Using Dev with OmniPod, Xcode 11, iOS 13, iPhone XS.  

The insulin delivery total on the main screen doesn’t align with the OmniPod screen or the health app.  The health app and the main screen do align but the reporting on the OmniPod section always is greater and I believe to be more accurate. I knew this to be a issue in prior builds but I thought this was addressed in the current dev build. Any suggestions?  Thanks.
![D1CF3DBC-F62E-4F14-A27C-7C0834A42A74](https://user-images.githubusercontent.com/54725965/65395860-13cf3b00-dd6e-11e9-8191-73ddbef20431.png)
![3AC36D92-9092-476F-B9B0-AD87F21B2D49](https://user-images.githubusercontent.com/54725965/65395861-1467d180-dd6e-11e9-85bf-71dc4866117e.png)
![431E0332-744A-45E8-B6EA-3D4C2B726F28](https://user-images.githubusercontent.com/54725965/65395862-1467d180-dd6e-11e9-941e-8d6b81480cd0.png)

**Comment by duffer5** [comment]
[loop error report.pdf](https://github.com/LoopKit/Loop/files/3640277/loop.error.report.pdf)

**Comment by woodduckie** [comment]
I believe the figures are different because they represent different measures...

Main loop screen & apple health show insulin delivery from today only.

Pod status shows total insulin delivered since pairing.
