### ISSUE TITLE
Loop crashing after iOS 13 update

### ISSUE THREAD

**Issue by daviddrozh** [LoopKit/Loop#1125]
**Describe the bug**
With the latest update to iOS 13, in loop; when you go to “Add Carb Entry”, at “Food Type” select the Plate. The app with crash

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Go to loop
2. Click on add carb entry
3. Click on the plate
4. App will crash

**Expected behavior**
The app will crash 

**Phone**
 - Hardware: IPhone XR
 - OS Version: iOS 13.0

**Loop Version**
 - Version Number: v1.10.0dev
 - Repo: LoopKit (I believe)

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: omnipod

**Comment by loyalchallenger** [comment]
I also just updated to iOS 13 and when I click Food Type, Loop app force closes.

**Comment by daviddrozh** [comment]
I did find a fix for this. If you rebuild loop it will start working fine. Also, If you updated to the update with “Dark Mode”, enable it, and hate the look it has on the loop app, you can force it to use light mode by editing the info.plist file. More info on this can be found in other app-building forums. Easy fix

**Comment by peculiarimages** [comment]
I updated to 13.2, skipping 13 and 13.1 and it works fine.

**Comment by loyalchallenger** [comment]
I rebuilt the app and it is working again. :)
