### ISSUE TITLE
Feature Request: Support for Medtronic pump through Bayer Contour Plus Link

### ISSUE THREAD

**Issue by attilavassy** [LoopKit/Loop#1128]
**Describe the bug**
The solution only works with certain old Medtronic pumps.

**Expected behavior**
Using the Contour Plus Link from Bayer though it's possible to send boluses. Would it not be possible to somehow link to the Contour Plus instead and use the pre-built solution there to send a bolus? That way a loop could still function.

**Comment by scottleibrand** [comment]
The CNL/CPL can send boluses, but AFAIK can’t set temp basals. Without the ability to set temp basals, you can’t avoid hypos and have the pump automatically return to scheduled basal if the loop loses connectivity. If you schedule a really low (or zero) basal rate and create a microbolus-only loop, you risk DKA if the loop loses connectivity to the pump for an extended period.

**Comment by attilavassy** [comment]
Thanks Scott, you are right, missed the fact that can’t set basal with it. 
Regards,
Attila
