### ISSUE TITLE
Feature Request: apply default carb absorption  icons when no food icons are selected

### ISSUE THREAD

**Issue by NightScoutForSeb** [LoopKit/Loop#1130]
**Describe the bug**
I cannot see historically in Nightscout what carb absorption times are selected. It would help to at least see the icons, such as pizza, lollipop or taco, when no food icon is selected. 

**To Reproduce**
1. Enter a meal, select default absorption time icon pizza, taco or lollipop. 
2. Complete carbs. Save.
3. Complete bolus wizard

**Expected behaviors**
After some minutes, go to Nightscout and review the bolus entry. It doesn’t show any icons though I expect it to display at least the default icons selected earlier.

**Loop Version**
 - Version Number: ? From Sept 24 2019
 - Repo: Dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Comment by Nightfoxy** [comment]
I like it, but I see the carb absorption time when I hover over the carb entry. Its something, though. I'm running Jojo still, so maybe the code is different?

**Comment by Kdisimone** [comment]
Hover over the dot in Nightscout and you'll see the associated absorption time. Also can look in mlab for the data if it is older than 48 hours old.

**Comment by NightScoutForSeb** [comment]
It only shows me the carb absorption time within a few minutes of the bolus and then for some reason changes to “correction bolus” display instead of meal bolus. 


Sent from Yahoo Mail for iPhone


On Wednesday, October 9, 2019, 8:46 AM, katie disimone <notifications@github.com> wrote:


Hover over the dot in Nightscout and you'll see the associated absorption time. Also can look in mlab for the data if it is older than 48 hours old.

**Comment by NightScoutForSeb** [comment]
Oh now the hover over works, never mind my previous comment. I still think seeing the icons would be great. 


Sent from Yahoo Mail for iPhone


On Wednesday, October 9, 2019, 8:46 AM, katie disimone <notifications@github.com> wrote:


Hover over the dot in Nightscout and you'll see the associated absorption time. Also can look in mlab for the data if it is older than 48 hours old.
