### ISSUE TITLE
BG targets don't update with timezone changes

### ISSUE THREAD

**Issue by JamieKeene** [LoopKit/Loop#1135]
**Describe the bug**
While travelling last week I noticed that my BG targets were in the timezone I built the app in (LON, GMT+1) even while my phone was in PST (GMT-8).

The settings screen showed the correct settings, but when rendered on the graph they showed as GMT+1.

Screenshots here 
[1](https://user-images.githubusercontent.com/5185892/66277447-b3281e00-e896-11e9-8e52-1f775ffc8fbb.png), 
[2](https://user-images.githubusercontent.com/5185892/66277452-c33ffd80-e896-11e9-8efb-af14e2b9a881.png); and [issue report](https://github.com/LoopKit/Loop/files/3694964/Loop.Report.2019-10-02.13_46_01-07_00.txt)
 attached.

**To Reproduce**
Because of the travel steps, I'm struggling to repro this. But:
1. Set up app (v. v1.10.1–7b1957164e333f43eb327adb915c7596c332e11b) in one timezone.
2. Change to Pacific Time automatically. Changing manually doesn't seem to trigger this.
3. Note that the targets on the BG graph don't adjust – on the image, at 4am, target should me 7.5-8.5 mmol/l.
4. Note that the targets in settings show correctly.

**Expected behavior**
The target ranges should move in line with the current timezone.

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 13.1.1

**Loop Version**
 - Version Number: v1.10.1
 - Repo: JamieKeene/Loop (minor alterations to build script to loop for Bash profile)

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: 2.9.0

**Additional context**

**Comment by ps2** [comment]
https://loopkit.github.io/loopdocs/troubleshooting/time-change/#traveling-across-time-zones-and-daylight-savings
