### ISSUE TITLE
different basal profiles

### ISSUE THREAD

**Issue by eszcloud** [LoopKit/Loop#114]
Different basal profiles so that one can switch between them without having to re-enter all the data at each switch. 

Not sure what the openaps commands are to change the profile selected on the pump, though that would probably be good to be sure that the two match both by changing it on the pump and verifying that the pump profile is the same as Loop's. 

As a shorter term fix, however, not having to re-enter everything each time I switch would be great.

**Comment by loudnate** [comment]
> openaps commands are to change the profile selected on the pump

@bewest has already decoded these commands, if you needed any more evidence of his genius: https://github.com/bewest/decoding-carelink/blob/83079dd8523b4ffd2741facc4c056f12fa1b33a5/decocare/commands.py#L246

This would certainly create a UX challenge of ensuring consistency between the pump and the app.

**Comment by ArkonPhoenix** [comment]
Surprised this is 2 years old. But yes, this would be most appreciative. Unless someone can come up with an algorithm that is automated and does not need this kind of pattern in order to run.
