### ISSUE TITLE
Riley Link connection error resulting in inability to use Loop

### ISSUE THREAD

**Issue by Janagaston** [LoopKit/Loop#1141]
I have not been able to use loop.  This has happened before.  It looks like it has started again but I have to figure this out because I am relying on this for great control before and after surgery for wound healing.  It has to be reliable.  
[Loop Report 2019-10-11 09_33_48-05_00.rtfd.zip](https://github.com/LoopKit/Loop/files/3718783/Loop.Report.2019-10-11.09_33_48-05_00.rtfd.zip)

**Comment by Kdisimone** [comment]
Please post in Looped group or Zulipchat for help on troubleshooting RileyLink. Include information in a post about the lights you are seeing, whether on or off, what you have tried to do to resolve the issue, and what Loop is showing on main screen including error message. Open the case and show what the battery and board looks like. Github issues isn't the best place for troubleshooting rileylink connections.
