### ISSUE TITLE
Question about the omnipod-testing branch roadmap

### ISSUE THREAD

**Issue by vbaderks** [LoopKit/Loop#1143]
At the moment I am using the Loop app based on the omnipod-testing branch as we have a Omnipod Pump.

Is there a roadmap (that can be shared) when the omnipod-testing branch will be merged with the dev\master branch?

The dev branch is currently the most active branch and gets most of the commits and the master branch is the branch that gets all the "official" release tags.

**Comment by elnjensen** [comment]
I believe the omnipod-testing branch will not be updated. It was intended to be a stable testing branch for initial Omnipod support; the current dev branch has all of that Omnipod support, and more. When dev stabilizes it will be merged into a new master release, and then you can move to master.

**Comment by live4sw** [comment]
This is a useful post from PS on the issue at https://www.facebook.com/groups/TheLoopedGroup/permalink/2380714765478509/

In my case, I was on Omnipod-testing for months but the IOB counting issue was causing a lot of issues, particularly at night, so I decided to switch to dev earlier today. But it's a very personal decision for everyone.

**Comment by smf723** [comment]
My guess is most Loop users don't have the ability to debug through the code to resolve issues they may have with a given build. The Dev branch by definition will change continuously as new features are developed without any notion of a stabilization period. If we had an additional "beta" branch we could take a snap shot of Dev branch at a particular point in time and then only update for bugs that are found in that branch. After a period of time the number of bugs found should in that branch should approach zero and then at that point it could be promoted to a "master" branch.

**Comment by smf723** [comment]
I certainly didn't mean to criticize! I think the Loop technology is probably the biggest improvement in T1D care since synthetic insulin was developed. This was only a suggestion to ease the concerns some may have about using a Dev branch and this was a possible way to address that. The alternative is to review the recent pull requests to try to assess the current stability of the Dev branch which is probably beyond most users abilities including myself.

**Comment by tdawggcat** [comment]
> I certainly didn't mean to criticize! I think the Loop technology is probably the biggest improvement in T1D care since synthetic insulin was developed. 

Understood.  Sometimes I get a little defensive for Pete and the others.  I wouldn't be surprised if we see some changes in the way everything is managed over the next months/year.

**Comment by vbaderks** [comment]
Thanks @live4sw for your answer. Based on the info on https://loopkit.github.io/loopdocs/build/step13/ is was assuming that the omnipod-testing branch was the only branch suitable when using an omnipod pump. Will try how good the dev branch works with the omnipod.

Personally I would find easier if only master and dev would be the long running branches and omnipod-testing would go away.
