### ISSUE TITLE
[omnipod-testing]: iOS 13 loop app getting stuck

### ISSUE THREAD

**Issue by kingst** [LoopKit/Loop#1144]
**Describe the bug**
Sometimes the loop app will stop reading in new Dexcom entries. If I kill the app (swipe up) and restart it picks back up the data. I _think_ this is happening when the phone gets out of range of the Dexcom, but I'm not 100% sure because I'm not the Loop user personally.

**Expected behavior**
When Dexcom is in range and has valid data, the BG value displayed in Loop should be the same.

**Phone**
 - Hardware: iPhone 7
 - OS Version: 13

**Loop Version**
 - Version Number: latest from `omnipod-testing`, the sha is `14eca1a856ecd7170f3f8a91a28c5c0874613719`
 - Repo: [LoopKit/Loop]

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom

**Pump**
 - Manufacturer: Omnipod

**Additional context**
This behavior is different than the iPhone 5 / iOS 12 app that we were on about a month ago. Not sure if it's the new phone or new os or something else.

**Comment by rickggaribay** [comment]
I observe the same behavior from time to time. I am going to switch to the dev branch to see if it addresses any of this and other issues including losing communication with the pump/RileyLink. I'll report back.
