### ISSUE TITLE
Falsely High Temp Basals Displayed on Insulin Delivery Graph

### ISSUE THREAD

**Issue by cmdelano** [LoopKit/Loop#1147]
**Describe the bug**

After delivering a bolus, I'm seeing a drastically high most recent temp basal displayed, for example, 7 units when my max basal is 2 units. I can't tell whether this is a display issue only or whether this affects Loop's predictions and calculations.

**Attach an Issue Report**

[Loop Report 2019-10-12 13_54_32-04_00.md.zip](https://github.com/LoopKit/Loop/files/3721071/Loop.Report.2019-10-12.13_54_32-04_00.md.zip)

I hope this file is okay. GH wouldn't accept a markdown file.

**To Reproduce**

It has happened with every bolus and does not seem to resolve with time. I saw this behavior in JoJo, but the display generally fixed itself. I don't think it's related to the recent use of an override, but I suppose it could be. Apologies for not having better info.

**Expected behavior**

I expected the scheduled/temporary basal to display as presented in Event History/Apple Health

**Screenshots**
![IMG_0341](https://user-images.githubusercontent.com/13289850/66706768-184f9980-ed05-11e9-8c8f-3eb1a4d765af.jpg)

**Phone**
 - Hardware: iPhone 8
 - OS Version: 13.1.2
**Loop Version**
 - Version Number: Loop v1.10.1 
 - Repo: Dev

**CGM**
 - Device: G5
 - Manager app: Dexcom app

**Pump**
 - Manufacturer: Medtronic
 - Model: 522
 - Firmware version: 2.4A
**Additional context**

I'm really, really sorry is this is a duplicate of another issue report. I searched GH, FB, and Zulipchat

**Comment by loyalchallenger** [comment]
I noticed today that Loop logged a .6u/hr temp basal to Apple Health, but my max temp basal is .5u/hr. So, I'm not sure how or why that happened. But it did not actually administer anything during that time...Everything was logged correctly on my nightscout.

**Comment by ps2** [comment]
This issue is being worked in #1133
