### ISSUE TITLE
Slow 2.4G WiFi 

### ISSUE THREAD

**Issue by scottf51** [LoopKit/Loop#1148]
**Describe the bug**

Ok, either I am going mad or either loop or Dexcom app are causing slow WiFi , only on the 2.4GHz band though . Just swapped phones , both iPhone se , both iOS 13.1.2 and slow WiFi / stuttering WiFi calling (likely packet loss or delay ) is following my looping setup . With loop and g6 app I can only get about 16M through WiFi , once I removed both from phone I can get 30-35 and the problem has migrated to the phone I installed them on (it was fine before ) . I am wondering if either the extra debug stuff or the Bluetooth snooping (since it’s also the same band ) is causing this 

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Wipe phone , do WiFi speed test while connected on 2.4G
2. Install loop and g6 app , setup with Riley link and pod 
3. Run speed test again while connected to 2.4G , notice speed it half or less and sometimes drops much further for short periods . 5G networks remain unaffected 

**Expected behavior**
2.4GHz WiFi speed remains constant 

**Screenshots**

**Phone**
 - Hardware: iPhone se 
 - OS Version: iOS 13.1.2

**Loop Version**
 - Version Number: 1.10.1
 - Branch - dev 

**CGM**
 - Device: dexcom g6 
 - Manager app: dexcom app 

**Pump**
 - Manufacturer: omnipod 
 - Model: [e.g. 723] Eros
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**
Pretty sure problem has existed for quite a while , so not a recent iOS bug , up till now I have assumed my WiFi network was at fault but have tried 3 routers now and the issue follows the phone with g6/loop

**Comment by scottf51** [comment]
[Loop Report 2019-10-13 01:27:17+01:00.zip](https://github.com/LoopKit/Loop/files/3721305/Loop.Report.2019-10-13.01.27.17%2B01.00.zip)

**Comment by scottf51** [comment]
Note, it doesn't seem to be enough to just install the app, needs to be setup listening too, narrowed down to Dexcom G6 or Loop but currently don't have the ability to remove / reinstall both without loosing control of my pump. Could try and swap back to the other phone and only do the G6 app, then test speed, then add loop to get the final answer either tomorrow or the next day hopefully

**Comment by scottf51** [comment]
moved back between phones again

doing a simple speedtest yielded the following results 

phone without loop or G6 software - Max around 40M down 

phone with G6 only - Max around 25-30 down 

phone with loop and G6 - Max around 15M down , also very noticeable that speed drops to pretty much zero around the time the dexcom reading is received

**Comment by scottf51** [comment]
[ping.txt](https://github.com/LoopKit/Loop/files/3731799/ping.txt)

**Comment by scottf51** [comment]
uploaded ping output from another host, keeping screen out of standby you get packet loss around the time a BG reading comes in and there is a common pattern around every 60 seconds or so (that ping command was doing 1 per sec approx) where we drop packets. 

Not sure if this is useful or not

**Comment by scottf51** [comment]
tried debug on the phone but the logs are so noisy, can bluetooth scanning quite a lot , but that could be loop trying to get the BLE stuff from dexcom or something else, without some idea of what I am looking for it's like a needle in a haystack unfortunately :/

**Comment by scottf51** [comment]
uninstalled loop and dexcom app, problem, speeds straight back to around 40M

**Comment by scottleibrand** [comment]
This is a pretty common issue, and not unexpected given that both 2.4GHz wifi and Bluetooth use the same frequency band (and often the same radio components on the phone): https://www.reddit.com/r/iphone/comments/8s7zq6/iphone_x_wifibluetooth_and_it_affecting_wifi/

I don't think there's anything Loop or LoopKit can do about it: it's a pretty fundamental RF design issue on the iPhone side.

**Comment by scottf51** [comment]
Thanks 

That talks about slow WiFi even without connected devices. Without loop I don’t see this slowdown and it’s very noticeable when it’s installed . WiFi calling becomes largely useless and keeps cutting out for instance (that’s how I noticed this ) 

I am guessing it’s to do with the Bluetooth scanning / snooping . 

If there really is nothing that can be done to reduce this slowdown then maybe we can just update the docs to let people know it’s expected . I would still much rather have loop and have slow 2.4GHz than not have it that’s for sure ,  but may save others time troubleshooting it if they notice similar
