### ISSUE TITLE
Pod Expiration Notice With No Active Pod

### ISSUE THREAD

**Issue by damonbayer** [LoopKit/Loop#1151]
**Describe the bug**
I received a "Pod Expiration Notice" notification, despite having no active pod. I believe this occurs if you do not replace the pod with a new pump.

**To Reproduce**
1. Deactivate pod.
2. Do not activate a new pod or switch to another pump model.
3. Wait for the old pod expiration timer.
4. Receive erroneous notification.

**Expected behavior**
If there is no active pod, no notification should be sent telling the user to replace the pod.

**Screenshots**
![IMG_0051](https://user-images.githubusercontent.com/8095080/66733563-ceee6f80-ee14-11e9-9369-b6f187544987.png)
![IMG_0052](https://user-images.githubusercontent.com/8095080/66733616-f8a79680-ee14-11e9-8b1d-a2f5f21d4341.jpeg)

**Comment by ps2** [comment]
Potential fix here if someone has the opportunity to test: https://github.com/ps2/rileylink_ios/tree/expiration-reminder-retract
