### ISSUE TITLE
Random scenarios notification 

### ISSUE THREAD

**Issue by BenRepak** [LoopKit/Loop#1152]
**Describe the bug**

Sometimes when unlocking my phone, I will have a Scenarios notification appearing as a modal window (for lack of a better term) on my loop app. Screenshot and issue report attached. 

I cannot definitely barrow down any user behavior that increases the frequency of this notification, but I am fairly certain it only occurs if I first lock my phone while the Loop app is open and then unlock my phone using Face ID (but this issue does not happen every time I unlock my phone with the Loop app previously open). I cannot reproduce on demand, but this modal appears randomly at least a few times per week. 

I am able to swipe down to close the modal or click the cancel button. 

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

Attached. 

**To Reproduce**

I cannot reproduce on demand, but I believe the issue appears periodically when....
1. open loop app
2. Lock phone without closing loop app
3. Unlock phone using Face ID 
4. See Scenarios modal 

**Expected behavior**

I do not expect to see the Scenarios modal. 

**Screenshots**

Attached
![A007BD2E-E0ED-4888-A2D0-BCB012C6E130](https://user-images.githubusercontent.com/34491091/66978495-677c2e00-f067-11e9-8790-04661f05d08d.png)

**Phone**
 - Hardware:  iPhone X
 - OS Version: iOS 13.1.2

**Loop Version**
 - Version Number: 1.10.1
 - Repo: LoopKit/Loop, dev branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod 
 - Firmware version: unknown 

[Loop Report 2019-10-16 22:33:47-06:00.md.zip](https://github.com/LoopKit/Loop/files/3737435/Loop.Report.2019-10-16.22.33.47-06.00.md.zip)

**Comment by Nightfoxy** [comment]
I have been seeing this as well, since moving to Dev last weekend, but since it's on my daughter most of the day, I didn't know if she was doing something. I'll try to grab an issue report next time.

**Comment by ddaniels1** [comment]
It’s when you shake the phone, it’s for debugging I believe. There is a line Of code that can be modified disable it, and I think I found a configuration in Xcode but can’t recall details of either at this moment. I’m sure someone will respond with the answer.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by BenRepak** [comment]
@ddaniels1 thanks for the comment - I was able to reproduce after intentionally shaking the phone.

**Comment by ps2** [comment]
This is changed in 2.0 so that you don’t get this screen unless you have specifically configured it.
