### ISSUE TITLE
Bolus numpad covers the continue button on some phones

### ISSUE THREAD

**Issue by ArkonPhoenix** [LoopKit/Loop#1154]
Similar to issue: iPhone 6s have to scroll down when paging through new Omnipod site #973

It seems most of the app is designed for a larger phone. But when using smaller phones, the home screen does not all fit.

Also the screens taking your through pairing a new pod, each one we have to scroll down to continue.

And now the latest dev branch update, the numpad for entering carbs/bonus amount. It covers the Continue button. Which I feel can lead to issues as you might click on something you dont want trying to get the page to scroll to get to the button that should be there (and was on previous versions).

I can get some screen grabs of all this if you need.

**Comment by live4sw** [comment]
I have the same issue on an iPhone SE at the bolus screen. Not a big issue but requires some scrolling/slows things down a bit.

![IMG-0013 (1)](https://user-images.githubusercontent.com/744935/67144329-4a03bb80-f243-11e9-848f-b77eaf3412b5.PNG)

**Comment by elnjensen** [comment]
Agreed that this is an issue.  On my iPhone SE, it’s actually worse than shown in the screenshot, perhaps because I’m using a larger text size. For me, the “Deliver” button isn’t visible at all - it’s completely under the keypad.
