### ISSUE TITLE
Loop crashed after switch from British Summer Time to winter time (GMT)

### ISSUE THREAD

**Issue by ngnrfsk** [LoopKit/Loop#1163]
Loop crashed repeatedly over several days after the change from Summertime to Wintertime (GMT). The problem was resolved by switching the clock on the insulin pump manually to GMT, which had previously been set to Central European Time.

Issue report isn't available, as the software kept crashing. 

**To Reproduce**
1. Open the loop app.
2. Long stall
3. Crash

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: iPhone 8 Plus
 - OS Version: iOS 13.1.3 & iOS 13.2

**Loop Version**
 - Version Number: 1.9.6
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: [e.g. 2.4A 1.1 0B 0B]

**Additional context**

**Comment by marionbarker** [comment]
I believe this issue should be closed.  From an older version of Loop 1.9.6.
