### ISSUE TITLE
Loop won’t connect to G6 after new transmitter, will only pull from Dexcom Share

### ISSUE THREAD

**Issue by drspike** [LoopKit/Loop#1164]
I’m having an issue were Loop will not get the new Dexcom G6 data without going through Dexcom Share, I have the cloud above the glucose constantly. I deleted the CGM in the Loop app as directed but since adding the newest translations I cannot get it to use the Dexcom directly. I have tried deleting the CGM multiple times from Loop and loading without Share logged in and it will not obtain glucose levels.

I am running iOS 13.2 on an iPhone XS. 
[Loop Report 2019-10-30 08:08:37-04:00.zip](https://github.com/LoopKit/Loop/files/3788742/Loop.Report.2019-10-30.08.08.37-04.00.zip)

**Comment by NightScoutForSeb** [comment]
Which branch are you using? And when was the last time you build/rebuilt Loop with a recent download?

**Comment by drspike** [comment]
Thank you. I went to the zulip chat and it was suggested to rebuild Loop as I received a transmitter starting with 8Hxxxx.

**Comment by Kdisimone** [comment]
Closing as this sounds like the original poster needed to update Loop app for firefly transmitters.
