### ISSUE TITLE
Feature Request: Add prerequisite checking to carthage build phase to address common mistakes

### ISSUE THREAD

**Issue by DConmy** [LoopKit/Loop#1169]
**Describe the bug**
Loop has clearly documented a number of problems a user may encounter, https://loopkit.github.io/loopdocs/build/build_errors/ , yet we still see people not following the documentation, nor finding the error described in the documentation and will instead reach out to the community in the FB Loop forum.

While later in the build there is some indication of the problem, it is often a secondary effect and pinpointing the problem upfront and early would be preferable.

**A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.**
In general, for things that are documented as minimum prerequisites, and which can be checked from a script, add a check and produce a fatal build as early as possible.   Things of this nature are, the following.   They will fail the build with a RED error in the build time output:
- minimum Xcode version
- minimum OSX version
- minimum Brew version
- minimum Carthage version
- detect that an iPhone is connected to the system
- detect that the last reboot time is later than the last XCode update time (i.e. has it been rebooted after an Xcode update)
- ensure that Loop root folder does not contain spaces

The maximum versions are a moving target, but also something that may want to be checked and warned, it will produce a YELLOW warning in the build time output:
- maximum Xcode version
- maximum OSX version
- maximum Brew version
- maximum Carthage version

For maximum versions, the assumption is that, typically, each of the above areas may need some minor work on the Dev branch in order to build as versions progress forward.   It would be expected that the person making the changes to support a newer version would make the change to the prerequisite check script as well.   If deemed too onerous, the max checks could be done for fewer areas, or none at all.

As implemented, each of the versions can provide as much or as little specificity as needed.
For example, an iOS version max of 13.2 would accept 13.2.1, but warn on 13.3.   An iOS version of 13.2.0 would accept 13.2, but warn on 13.2.1 as well as 13.3 and 14.

**Attach an Issue Report**
Not applicable

**To Reproduce**
The script will be added early, during the carthage build.  The script, prereq-checks.sh can be hand tweaked to change the min and/or max versions of each of the checks to see it in failure mode.

**Expected behavior**
If a minimum version is not satisfied, an error: will be output and fail the build
If any other check is mandatory, an error: will be output and fail the build
If a maximum version is not satisfied, a warning: will be output but the build will not be failed.

**Screenshots**   NOTE: These versions were contrived in order to show the failure.
The double "See see" in the screenshots will be fixed in the PR.
![image](https://user-images.githubusercontent.com/4826107/68092852-729fce00-fe5d-11e9-9fe9-674546ba47ba.png)
![image](https://user-images.githubusercontent.com/4826107/68092874-b561a600-fe5d-11e9-8c14-6d44c4bc5c36.png)
![image](https://user-images.githubusercontent.com/4826107/68093770-18a40600-fe67-11e9-8bda-0e771ed92547.png)

**Phone**
N/A

**Loop Version**
Dev branch

**CGM**
N/A

**Pump**
N/A

**Additional context**

NOTE:   I have the above coded and can submit as a PR shortly.

There is likely more that can be checked, but I wanted to get base checks in now, and the script can be augmented over time.   There is one check that I really wanted to include, but was unable to identify that there is any way to make the check:  "Determine if a physical phone is the target device for Xcode" .  While I can determine via the command line that an iPhone is attached, I cannot determine if it is a target, from all that I have researched.

**Comment by mikebash** [comment]
@DConmy - regarding your point about a physical phone being the target, if you do figure that out at some point, I wouldn't want it stopping a build or creating as strong of an error message as some of the other issues.  I always build the first time to a simulator phone so that the build to the T1D's phone is significantly faster (in other words, he's without his phone for a much shorter time).  Just a thought.  Love the idea and work you are doing here.

**Comment by DConmy** [comment]
@mikebash    Agree.   If I could figure it out, I'd output it as a warning.

In XCode, with scripts, you get the following behavior:
- If the script does an echo error: xxxxx and return a non-zero, the build will stop
- If the script does an echo warning: xxxx and returns a zero, the build will continue

The Loop docs say that the warnings can be ignored, so this would work.
But it may not be its desired effect since there are sometimes "Ok" warnings, and people might generally ignore warnings, as instructed.   We could possible change the wording and specifically request individuals pay attention to "important warnings".  I'm open to wording/suggestions on phrasing.

**Comment by ps2** [comment]
I would take a PR that does the following:

Error on:
minimum Xcode version
minimum Carthage version

All of the following are not good checks:

minimum OSX version - Xcode is more specific then macOS version; if you have an acceptable Xcode, you have an acceptable version of macOS
minimum Brew version - Not all devs use brew to install carthage
detect that an iPhone is connected to the system - this is not required, and will fail valid use cases
detect that the last reboot time is later than the last XCode update time (i.e. has it been rebooted after an Xcode update) - This is not required generally, and would prevent people from building in ok circumstances
ensure that Loop root folder does not contain spaces - this just needs to be fixed; there is a PR in review

The warnings on maximum version will often be outdated and might cause people to downgrade unnecessarily, which is problematic itself.
maximum Xcode version
maximum OSX version
maximum Brew version
maximum Carthage version
