### ISSUE TITLE
Omnipod pump is not listed when app is installed to devices.

### ISSUE THREAD

**Issue by akashnsmahaswami** [LoopKit/Loop#1171]
On clicking **add pump** option list of pumps are visible in simulator. But when I installed same app in iPhone 5s, pump was defaulted to simulator. I'm using **Loop-dev** branch.

### **Phone**
 - Hardware: iPhone 5s
 - OS Version: iOS 12.4.1

### **Screenshot of simulator**
on clicking **Add Pump** simulator shows list of pump.
![Screenshot 2019-11-05 at 2 54 01 PM](https://user-images.githubusercontent.com/56542311/68196308-68590d80-ffde-11e9-9f44-d1c2d3062f41.png)

### **Screenshot of device**
on clicking **Add Pump** iPhone5s, app show pump settings.
![Screenshot 2019-11-05 at 3 12 03 PM](https://user-images.githubusercontent.com/56542311/68196436-a6563180-ffde-11e9-9399-8ccba9ca3530.png)

**Comment by Kdisimone** [comment]
I have the same gear available for my test setups and I cannot reproduce the error you are reporting. Please delete all your Loop downloads and start fresh. Delete your existing Loop app on your phone too before reinstalling dev branch. 

Alternatively, finish the pump setup on your phone and then delete whichever pump has been setup to start fresh
