### ISSUE TITLE
CGM data gap

### ISSUE THREAD

**Issue by dwayneianprimeau** [LoopKit/Loop#1172]
**Describe the bug**
I woke this morning to find a red loop and a gap of a few hours of CGM data in Loop.  I am using Dexcom G6.  There ar no gaps in the data in the Dexcom G6 app.  I restarted both Loop and Dex apps.  I then removed the G6 from Loop and Re-entered it.  Data began flowing, however the gap of data in Loop was not filled in.  I do not have Dexcom Share enabled.

The only thing different this morning is that I am travelling in the US (I’m Canadian) and have cellular data turned off.

**Attach an Issue Report**

https://drive.google.com/file/d/1IsrumbNYj1aTCSOEQYxtgpuu11byKsJm/view?usp=drivesdk

**To Reproduce**
1. Go to the Loop app
2. See missing CGM data, and based on that no predictions, looping 

**Expected behavior**
CGM data to be present particularly considering the data is present in the Dex G6 app.

**Screenshots**
![1B49AFEC-AD40-478B-9315-4D2D687E00F4](https://user-images.githubusercontent.com/56934766/68205271-e0501500-ff97-11e9-9e34-cfabe566f430.png)
![966E6515-94BC-4026-ADF2-0AE584031B6D](https://user-images.githubusercontent.com/56934766/68205273-e0501500-ff97-11e9-8c72-10e349c81f14.png)

**Phone**
 - Hardware: iPhone 6s Plus
 - OS Version: IOS 12.4.1

**Loop Version**
 - Version Number: 1.10.1
 - Repo: Dev branch

**CGM**
 - Device: Dexcom G6
 - Manager app:  Dexcom G6 App v1.5.3

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: unknown

**Additional context**
Only that my phone would have been disconnected from the internet during this time (no cell or wifi data connection)

**Comment by Kdisimone** [comment]
Since Loop wasn't getting the cgm data, it cannot be graphed. Dexcom writes to health on a three hour delay. So once you get to more than three hours from the missing cgm data, then it will be back filled.

**Comment by dwayneianprimeau** [comment]
Thanks Katie.  From the logs and detail shared do you know why Loop wasn’t getting the CGM data?
