### ISSUE TITLE
Certain bolus appears to not have actually delivered after Loop duplicated carbs

### ISSUE THREAD

**Issue by ashleysigette** [LoopKit/Loop#1180]
11:25am: Daycare boluses my child for 36g lunch. I see on NS that it WAY overbolused. Red flag. I start clicking around on the NS dots and it looks like there may be two overlapping dots of carb entries. Loop has him on a high temp, even after overbolusing and shows an eventual BG of 300. Something isn't right. So, I head up to daycare to see if the carbs were entered twice. That's my best guess at this point.

11:40am: Get to daycare. Carbs are in twice. Overbolus, high temp, high eventual all make sense now. I delete one of the entries, give my kid a pack of M&Ms to make up for what I believe was close the carb amount he would need to make up for the overbolus.

11:45am: Talk to the person who bolused him who swears she didn't enter the carbs twice. I believe her 100%. She said the bolus did seem to take an abnormally long amount of time to start.
12:15pm: Child is SKYROCKETING. Jumping 20-30 points every dex update. I ask daycare to check the original lunch bolus in Event History. Says certain. 

12:35pm: As he nears 300 (a number we never, ever, ever see), I now come to the conclusion that not only was he NOT overbolused but that he didn't receive any of the bolus. I have daycare bolus him an amount that should cover most of what he ate Bolus is certain. Pod beeps (I heard it in the background while I was on the phone with the office staff). I leave again and go back to daycare to pick my kid up and handle the rest of the situation at home.

1pm: I get him home and change pump thinking maybe that was the problem. Pump looks great, canula looked great. Loop is now red with "old pump data" even though RL and phone are 2 inches from him. Manually turned RL on/off, restarted phone and all apps in case there was some kind of communication error. Put new pump on, bolus.

Finally: He came down. Highest finger poke was over 500. I am certain he did not receive any of the "Certain" boluses. 

Here are the things that seem questionable:
- Carbs showed up twice when the daycare staff says they did not enter them twice.
- Two different boluses said "Certain" when he absolutely did not get those boluses. (I've seen this happen the other way around with Uncertain but never like this with Certain).
- Riley Link died (solid blue light) a few days after this event. Is it possible that had something to do with a communication issue?

Issue Report: https://1drv.ms/u/s!AlnhYchyMSQVhkpQLuHdvbXrcVnU 

**Phone**
iPhone 6+

**Loop Version**
- dev branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Comment by ps2** [comment]
An issue report captured within a short time of the reported issue would've been helpful here. The attached issue report was taken after the pod was replaced, so there is no log of actual pod comms.  There is also no reservoir data to compare against.   The events in question have been deleted, so those can't give any info either.

As for the carbs "showing up twice", I'd have to say this is likely inadvertent double entry.  We don't have any outstanding bugs showing that a single UI action ends up with two entries, but we do know that accidentally entering carbs twice is a common user error and are looking into ways to improve the user interface to make that happen less.

As for the certain bolus, not actually delivering, there isn't much info here to say whether or not the delivery happened or didn't. Again, a timely issue report would maybe change this answer.

As for the RileyLink issue contributing to this issue; without really knowing what happened, it's hard to say.

Sorry for all the non answers, but I don't think we can go much farther in digging into this. Thanks for the report, and we'll keep it mind as we investigate other reports.
