### ISSUE TITLE
Add New Carb Entry selecting food type first error

### ISSUE THREAD

**Issue by Rdeboer180** [LoopKit/Loop#1182]
**Describe the bug**
Since the most recent update i cant adjust the food type / absorption time using the plate icon before amount consumed is first filled out. 

**To Reproduce**
1. Go to 'Add Carb Entry'
2. Click on 'Food type dinner plate icon'
3. see error, the page auto scrolls down, and now if you put in amount consumed / time and try to hit save it wont let you. 

**Expected behavior**
Prior to the patch it didnt matter what order you filled out the carb entry form. if you press the plate icon, find the food item in question it should not scroll down and should still allow you to fill out the ammount consumed, time, and hit save. 

**Phone**
 - Iphone 8
 - OS Version: [iOS 13.2.3]

**Loop Version**
 - Version Number: [1.10.1]
 - Repo: [LoopKit/Dev]

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [Dexcom App]

**Pump**
 - Manufacturer: [OmniPod]
 - Model: [Eros]

**Additional context**
updated for the first time since July, not sure in order to support the new G6 transmitters.

**Comment by Kdisimone** [comment]
Please, You should to fill out the rest of the info for bug reports to really be the most helpful. The version of Loop app you're using is really quite relevant.

**Comment by Rdeboer180** [comment]
should be updated. not sure if there is any firmware associated with Omnipods or where to find it.

**Comment by bfeinzimer** [comment]
for me, selecting two different of the default 3 food types before hitting the extras plate helps alleviate this
