### ISSUE TITLE
App displays mmol/L in configuration instead of mg/dl

### ISSUE THREAD

**Issue by jhetschko** [LoopKit/Loop#1183]
Dear all,

After building the app successfully and setting up the configs within the app I noted that some of the items, e.g. correction range are set up in mmol/L instead of mg/dl. After the connection with Dexcom G6 was established, the main page graph indicated mmol/L, too.
While looking for the root cause I came across the Apple Health app and found that the units were set to mmol/L. I amended to mg/dL and subsequently the app's main page is now correctly displaying the prefered units. However the config still shows and requires mmol/L values.
Is there any solution to overcome this problem and have the config units set to mg/dl, except rebuilding the app (while Apple Health is set correctly) once I need to change the Omni Pod?
Thanks so much and best regards!

**Comment by beached** [comment]
Have you closed the app(hit home twice and swipe the app up to close it) then reopen, or rebooted the phone.  I sometimes have the opposite and it goes to mg/dl instead of mmol/L

**Comment by ArnieWeisbrot** [comment]
I have what looks like the same display problem. First, I am in Canada, so my data is supposed to be in mmol/L. I am using a Dexcom G6 and an Omnipod pump. I am running on an iPhone 7 under iOS 13.3. The Dexcom G6 app is version SW11586, software revision 1.5.4. Loop is V1.10.3. Every function seems to be working correctly.
The display of BG data is correct everywhere except in two relatively minor places. Under Settings/Dexcom G6 the display of Latest Reading Glucose and Trend each show an amount in mg/dL, clearly the incorrect units but the proper value (divide by 18).
Looks like this display problem exists both ways, from mmol/L to mg/dL and vice versa.

**Comment by ArnieWeisbrot** [comment]
I can no longer replicate this behaviour after update to Master 2.0. Can anyone else make this happen? 

Perhaps this issue can now be closed, even though it look like there was no specific fix implemented.

**Comment by ps2** [comment]
There have been several fixes regarding units handling in 2.0 since the last release. I'd agree we can close this if you're no longer seeing the issue.

**Comment by ArnieWeisbrot** [comment]
Thank you, Pete. As a newbie to Github, I couldn't even find out how to close an issue without a Pull Request. I continue to learn!
