### ISSUE TITLE
Basal rate automatically set above max basal limit while in open loop

### ISSUE THREAD

**Issue by nstranberg** [LoopKit/Loop#1188]
**Describe the bug**
My basal was automatically set to over 40 U/hr for a few minutes. My maximum basal rate limit is set to 1 U/hr and I am open looping. It did not ask for my permission to set the basal rate even though I am open looping. My active insulin skyrocketed because of the extreme basal rate, but I think falsely because I did not go low and I don't think the pump can keep up with 40 U/hr. 

**Attach an Issue Report**
[Loop Report and Screenshots.zip](https://github.com/LoopKit/Loop/files/3883152/Loop.Report.and.Screenshots.zip)

**To Reproduce**
I have not been able to reproduce the behavior.

**Expected behavior**
I expected my maximum basal to never be above my maximum basal limit. And I expected it to recommend the basal instead of automatically initiating it.

**Screenshots**
Included in loop report zip.

**Phone**
 - Hardware: iPhone Xr
 - OS Version: 12.4.1

**Loop Version**
 - Version Number: V1.10.0DEV
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Eros
 - Firmware version: NA

**Additional context**

**Comment by ps2** [comment]
This is a display issue on an older build of Loop, where your bolus is being rendered as a temp basal. You did not get any insulin delivery beyond those two boluses, as evidenced by the reservoir values only dropping 5-6 U.  Newer builds do not have this display issue.

**Comment by elnjensen** [comment]
FYI, I still see this periodically on Medtronic with a pretty recent dev build. (I can dig up the exact commit if you want.)   It eventually resolves itself from pump history (as it always has) but it hasn’t gone away - unless the fix you’re referring to is in the past few weeks?

**Comment by ps2** [comment]
This can still happen on Medtronic, yes, but it should also be less frequent and happen for a shorter duration than before. If should not happen at all for omnipod.
