### ISSUE TITLE
When I go to add Pump on the Loop app, it goes straight to Select Riley link, and then just spins and crashes.

### ISSUE THREAD

**Issue by sherribrinson** [LoopKit/Loop#1190]
When I go to add Pump on the Loop app, it goes straight to Select Riley link, and then just spins and crashes. I’ll send you a screenshot of that. According to below instructions it is supposed to ask me which pump type first, before going to Riley link selection. It never asks me which pump type.

Can you help me?

**Comment by sherribrinson** [comment]
![IMG_2033](https://user-images.githubusercontent.com/49903085/69584399-1a1aa700-0fab-11ea-92ef-e45c30a1bf5f.PNG)
![Screenshot 2019-11-24 at 2 37 16 PM](https://user-images.githubusercontent.com/49903085/69584401-1a1aa700-0fab-11ea-832a-a56e422bd088.png)

**Comment by ps2** [comment]
This looks like you might be building the wrong branch. Please start again, using dev, and if you are still having trouble, please ask in Zulip or the facebook Looped group.

**Comment by sherribrinson** [comment]
Thanks for your help.
