### ISSUE TITLE
Basil delivery not being accounted for in IOB with dev branch v1.10.1 built on 11/19/2019

### ISSUE THREAD

**Issue by rolandet** [LoopKit/Loop#1197]
**Describe the bug**
My scheduled Basil delivery is not being accounted for in the IOB. The Insulin is showing up under Pod Settings under "Insulin Delivered" and in Apple Health yet the Balis Insulin delivery does not show up in the Event History under Insulin Delivery. BG was dropping so I had to eat/enter carbs and the Loop app kept recommending a Bolus since it didn't account for the schedule Basil delivery. I have no overrides or temp basil settings in place. I also tried exiting/killing Loop to resolve the issue and also tried "Sync With Pod" under the Basil Rates schedule. I had to suspend the Basil delivery as my BG was going too low.

**Attach an Issue Report**
[Loop Report 2019-12-09 13_45_08-05_00.md.txt](https://github.com/LoopKit/Loop/files/3941288/Loop.Report.2019-12-09.13_45_08-05_00.md.txt)

**To Reproduce**
Not sure why this occurred but I have attached an issue report.

**Expected behavior**
Loop should account for basil delivery in IOB.

**Screenshots**
I'll will attach the appropriate screenshots.

**Phone**
Hardware: iPhone 8+
OS Version: iOS 13.2.3

**Loop Version**
Version Number: v1.10.1
Repo: LoopKit/Loop, Dev Branch
CGM

**CGM**
Device: Dexcom G6
Manager app: Dexcom App

**Pump**
Manufacturer: Insulet
Model: Omnipod Eros
Firmware version: 2.9.0

**Additional context**
None.

**Comment by rolandet** [comment]
![A640B925-F228-42D0-94F4-6E86FC94774D](https://user-images.githubusercontent.com/4328088/70465253-8f4ba900-1a8e-11ea-8741-645ea9df9161.png)
![0DFD033E-7653-4937-A44C-0C549D91D2B6](https://user-images.githubusercontent.com/4328088/70465254-8f4ba900-1a8e-11ea-8c96-9e052d5b0cba.png)
![2BC08B8C-1DF4-4D2C-8D48-B1749E5E58BE](https://user-images.githubusercontent.com/4328088/70465255-8f4ba900-1a8e-11ea-8544-fb29e28f0b4b.png)
![596B2B84-93E9-44F1-B8F5-DBF14F8E7359](https://user-images.githubusercontent.com/4328088/70465257-907cd600-1a8e-11ea-8b86-2d6c02184fe9.png)
![CE4C2E96-212B-4A36-B5C0-FBE99D99691C](https://user-images.githubusercontent.com/4328088/70465258-907cd600-1a8e-11ea-964d-61f32a65fa65.png)
![2CE593DD-7D72-4E16-8E31-87573FC8AA73](https://user-images.githubusercontent.com/4328088/70465259-907cd600-1a8e-11ea-8497-ac14724f8587.png)

**Comment by rolandet** [comment]
![7796AAB1-8B69-4EFF-9797-5ABC406E452B](https://user-images.githubusercontent.com/4328088/70465490-13059580-1a8f-11ea-97ce-da217fdbfa3b.png)

**Comment by rolandet** [comment]
> Your screenshot shows the basal delivery status as "suspended". Go ahead and resume insulin deliveries...

I suspended it after noticing the issue as my BG was dropping to unsafe levels.

**Comment by rolandet** [comment]
Can we not close an issue so quickly before understanding the context of the issue?

**Comment by Kdisimone** [comment]
You were in charge of providing different context if you think there was more to the issue. 

You provided a pretty thorough set of screenshots all pointing to the issue being a suspended pump.  If you have something else you'd like to add, please do and we can reopen the issue if there's more to it than that. But...you'd have to explain more..:

**Comment by Kdisimone** [comment]
There ya go...reopened.

**Comment by marionbarker** [comment]
“ Describe the bug
My scheduled Basil delivery is not being accounted for in the IOB”
Note that scheduled basal is not part of IOB. IOB is supposed to indicate current insulin above or below the amount that would be present with only scheduled basal. Scheduled basal is ideally the basal rate required for  metabolic function in the absence of food or exercise.

**Comment by rolandet** [comment]
@marionbarker Thank for the explanation of how Scheduled Basal is not accounted for in the IOB. I would contend that the scheduled Basal should be tracked somewhere as it can also impact your BG levels. I would need to review the Omnipod PDM to see if that tracks the scheduled basal.

**Comment by marionbarker** [comment]
@rolandet 
All insulin delivered is tracked by Loop. Scheduled basal is reported to Apple Health whenever a rate changes. This can be at a scheduled rate level change or when a Temp Basal is set or a bolus is delivered. (Temp basal and bolus are also reported to Apple Health, but you asked specifically about sch basal accounting.) 

The PDM calculator for IOB only uses boluses. It also uses a linear model for insulin activity. 

I uploaded matched screenshots of Apple Health and the Loop Event List. The Event List time is start of the interval. The Apple Health time is end of interval. My basal rate changes at 4:30, so Loop reports 2 chunks of the delivery to Apple Health (pod didn’t split it up like that -it is just record keeping on either side of a scheduled basal boundary.) This case doesn’t have me running at sch basal but if I were, the Event List would not show TB during that time period, but Apple Health would report delivery at next rate change. 

Hope you find this useful. 

![9908D536-23B4-4A23-BB70-4E64E06BAAE0](https://user-images.githubusercontent.com/19607791/70550211-434e4200-1b2a-11ea-84c4-2c26d74f5f3f.jpeg)
![0409B612-5300-4D67-B8EF-3025F88AC57E](https://user-images.githubusercontent.com/19607791/70550212-434e4200-1b2a-11ea-9f52-3e2324577057.jpeg)

**Comment by Kdisimone** [comment]
Roland and I have had same convo via Zulipchat and now that the clarifying details are also provided here for others to see...I think we can close this issue

**Comment by ps2** [comment]
Thanks @Kdisimone !
