### ISSUE TITLE
OmnipodPumpManager.Storyboard missing translations displays

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#1206]
I am having problems getting the OmnipodPumpManager.storyboard translations to show. The middle text does not appear in storyboard. The header and the footer do. All three are setup in the same file/place (nib seems ok). No errors in translation xliff, have quadruple checked that.

![IMG_29E8FD38A1E3-1](https://user-images.githubusercontent.com/12402160/71305162-7c857e00-2384-11ea-8577-80152ba88d10.jpeg)
![IMG_7734](https://user-images.githubusercontent.com/12402160/71305165-84452280-2384-11ea-8d94-b353e31c22f8.png)

**Comment by ps2** [comment]
I was having similar issues after checking out your branch, but did a clean in Xcode, and removed the app, and now it's running fine. Sometimes installing from Xcode doesn't clean out the ipa folder on the phone very well.

**Comment by ps2** [comment]
It seems to be working for me, with everything translated appropriately, checking out your latest https://github.com/ps2/rileylink_ios/pull/561, and merging in dev.
