### ISSUE TITLE
Override shouldn't save without target range

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#1210]
Currently, Loop lets you save an override preset without a target range. When that happens, Loop will temp basal to 0  u/hr when the override is active.  

Desired behavior would be to have the user not allowed to save the override preset without a target range. This will prevent a user from unknowningly having unintended zero-basal delivery after setting override.

(@mpangburn tagging you, thanks!)

**Comment by Kdisimone** [comment]
(corrected the above to read more accurately...Loop isn't suspending, loop is zero-basaling.)

**Comment by mpangburn** [comment]
Saving without a target range is intended behavior; some overrides should only affect sensitivity changes (I've been running one for the last ~2 weeks while home on break!). I'm unable to replicate this; can you provide some screenshots / issue reports of zero-basaling?

**Comment by Kdisimone** [comment]
Hmmm. Ok. Let me dig deeper in the user's report and find if there was different cause. I'll get my test rig going too. Thank Michael!

**Comment by Kdisimone** [comment]
Indeed. User appears to be wrong. Testing on my rig doesn't agree with what she reported (or I assumed was correct). Thanks for clearing that up. I'll close.
