### ISSUE TITLE
After updating to watchOS 6.1.1 the Loop crashes on Apple Watch 5 during launch

### ISSUE THREAD

**Issue by kulczwoj** [LoopKit/Loop#1211]
**Describe the bug**
After updating watchOS to version 6.1.1 I cannot run Loop on my Apple Watch 5 anymore (I got it yesterday so this was the first OS upgrade on that Apple Watch). A plain screen appears and then the Loop immediately crashes. The same error appears for both 1.9.6 and 1.10.3 versions of Loop. I tried rebooting Apple Watch and iPhone, reinstalling Loop on both Apple Watch, rebuilding the Loop on iPhone and Apple Watch, installing Apple Watch app directly from Xcode, unpairing Apple Watch from iPhone and erasing Apple Watch. None of these methods helped.

I tried debugging Apple Watch app in Xcode and got the following errors:

- 1.9.6:

<img width="1402" alt="Zrzut ekranu 2019-12-25 o 16 53 34" src="https://user-images.githubusercontent.com/58049191/71449566-8d9d0900-274f-11ea-949c-de48c5ff74db.png">
<img width="1400" alt="Zrzut ekranu 2019-12-25 o 16 53 55" src="https://user-images.githubusercontent.com/58049191/71449567-8ece3600-274f-11ea-800f-326e3fb572a7.png">

- 1.10.3:

<img width="1399" alt="Zrzut ekranu 2019-12-25 o 18 43 45" src="https://user-images.githubusercontent.com/58049191/71449570-968dda80-274f-11ea-89d3-a8ee0f98d840.png">
<img width="1398" alt="Zrzut ekranu 2019-12-25 o 18 44 00" src="https://user-images.githubusercontent.com/58049191/71449571-98579e00-274f-11ea-8ede-8b5916f03931.png">

**Phone**
 - Hardware: iPhone 7
 - OS Version: iOS 1.3 (and iOS 1.2.3)

**Loop Version**
 - Version Number: 1.9.6 and 1.10.3
 - Repo: LoopKit/Loop

**CGM**
 - Device: Medtronic Enlite with Minilink Transmitter
 - Manager app: Medtronic Paradigm 722 insulin pump

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.4A 1.1 0B 0B

**Comment by rolandet** [comment]
Just got an Apple Watch Series 5 today, upgraded to 6.1.1, built loop-dev 1.10.3 and the Loop Watch App seems to be working fine so far. Are you really running iOS 13? That was a very problematic release for Apple. What Xcode version are you using?

I have an iPhone 8+ running iOS 13.2.3 and am using Xcode 11.2.1. I also use the Omnipod with the Dexcom G6.

**Comment by kulczwoj** [comment]
I have Xcode 11.3. Sorry, I wrote down my iOS wrongly. Till yesterday I used 13.2.3 and had this problem, so I upgraded to 13.3, but it didn't solve it.

**Comment by Nightfoxy** [comment]
The only solution I know of for this (can happen in any watch and iOS) is to clean the build folder, unpair watch, pair, and build again.

**Comment by kulczwoj** [comment]
> The only solution I know of for this (can happen in any watch and iOS) is to clean the build folder, unpair watch, pair, and build again.

I tried to do it twice. During the second trial I even removed the iPhone app. Unfortunately, it didn't help.

**Comment by kulczwoj** [comment]
When using paid developer account the problem disappears. 

The problem appears only when using free account and seems to be analogical to the issue on iOS 13.3.1 (see https://github.com/LoopKit/Loop/issues/1264).

**Comment by ps2** [comment]
Installation of the watch app has a lot of silent failure possibilities. Please ask in zulip for tips if you continue to have issues installing.
