### ISSUE TITLE
VIsual alignment of dialogs off

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#1213]
**Describe the bug**
The display of dialogs is too low.  This is an iphone 8 with zoom on.  Attached photos.

**To Reproduce**
Click on carb entry, bolus entry, temp override or gears.

**Expected behavior**
The top of the windows aligns with top of the screen so that more of the info shows

**Screenshots**
![IMG_2038](https://user-images.githubusercontent.com/855156/71454984-107a8f80-2761-11ea-9b02-1aa49707f258.PNG)
![IMG_2039](https://user-images.githubusercontent.com/855156/71454985-12445300-2761-11ea-9fdc-9dedd9f8472e.PNG)

**Phone**
 - Hardware:  iphone 8, with zoom 
 - OS Version: 13.3

**Loop Version**
 - Version Number: 1.10.3
 - Repo: [LoopKit/Loop, dev] 
The git revision is a098d6a2

**CGM**
 - Device: [Dexcom G5]
 - Manager app: [Dexcom App]

**Pump**
 - Manufacturer: [Omnipod]
 - Model: [?]
 - Firmware version: [?]

**Comment by mylma** [comment]
This looks like normal UI changes of iOS 13 to me. On iOS13 dialogs are not aligned to top edge of the screen, so they are kind of floating above the main view. If you have a zoom mode on, that would affect too how the content inside a dialog is rendered, for sure. Issue #1260 is more related to the new carb & bolus entry flow UI changes.

**Comment by beached** [comment]
I said it wrong above.  The buttons are off by about as much as the screen is dropped from the top.  I tried to describe why I thought it.  However, the issue is that the buttons are hidden below things or the bottom.  Items like the pod wizard have a lot of blank space but to press the button, one must scroll

**Comment by beached** [comment]
In addition, dialogs like below need to be scrolled, but it isn't easy as the entry itself is scrollable too. 
![image](https://user-images.githubusercontent.com/855156/73800380-77d72680-4786-11ea-9fcf-2ed8f02db19c.png)

**Comment by mylma** [comment]
OK I see, sorry. I think this issue is caused by couple of things: 1) you have a zoom mode on that uses more space than usual, 2) iOS13 UI changes, 3) Loop UI could be optimized better for the smaller screens in many places.

One possible UI fix might be removing the empty table header row on top of the dialog. 

On this particular Override dialog, the Duration row could be above the Enable Indefinitely row, so that it would be easier to access and set.

**Comment by beached** [comment]
Here is another, this is the most commonly encountered one.  The bolus dialog has lots of space, but the deliver button is covered by the number entry. 
![image](https://user-images.githubusercontent.com/855156/73852070-8f50f680-47fc-11ea-9886-c9364375b55a.png)
