### ISSUE TITLE
Timezone do not update correctly in Nightscout 

### ISSUE THREAD

**Issue by skimaniac** [LoopKit/Loop#1215]
**Describe the bug**
I don't understand why Nightscout doesn't keep my time zone settings. It seems that when loop changes the profile, the time zone does not update in the new profile.

It gives that the info box of the basal is distorted, I don't think it affects anything.

As soon as I modify the time zone in the profile the box becomes ok again

**Attach an Issue Report**

**To Reproduce**
1. modify setting in loop 
2. look the basal pill in Nightscout
3. go to profile in Nightscout and add time zone to the profil
4. the basal pill show correct info

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: iPhone 7 Plus
 - OS Version: IOS 13,3 (but I notice that on a older IOS)

**Loop Version**
 - Version Number: LOOP V26121A-FREEAPS (but it's do the same in official Loop version)
 - Repo:  ivalkou/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer:  Medtronic
 - Model:  715
 - Firmware version: VER 2.1A1.1 

<img width="309" alt="Capture d’écran, le 2019-12-27 à 10 59 46" src="https://user-images.githubusercontent.com/44727542/71525601-699d0d00-28a0-11ea-8ff5-3da27778b22c.png">

<img width="643" alt="Capture d’écran, le 2019-12-27 à 11 00 17" src="https://user-images.githubusercontent.com/44727542/71525607-715cb180-28a0-11ea-82e9-b45148506995.png">

<img width="689" alt="Capture d’écran, le 2019-12-27 à 11 01 06" src="https://user-images.githubusercontent.com/44727542/71525608-715cb180-28a0-11ea-8b33-631b809f1831.png">

<img width="305" alt="Capture d’écran, le 2019-12-27 à 11 01 27" src="https://user-images.githubusercontent.com/44727542/71525611-715cb180-28a0-11ea-8d03-9859b2576213.png">

[Loop Report 2019-12-27 12:02:10-05:00.txt](https://github.com/LoopKit/Loop/files/4005848/Loop.Report.2019-12-27.12.02.10-05.00.txt)

**Comment by sulkaharo** [comment]
Can you please try if the branch in #7833 fixes this for you? From what I can see, the issue is Loop uploads time zone data that's almost but not quite compliant with the ISO spec and thus Nightscout fails to recognise the zone. I added code to work around the issue in that branch. Ideally Loop would be changed to send the time zone string using the exact ISO compliant format.

**Comment by marionbarker** [comment]
I will test this and report back. Thank you Sulka.
