### ISSUE TITLE
Not able to set override presets no plus sign to add

### ISSUE THREAD

**Issue by crush180** [LoopKit/Loop#1221]
I just downloaded version 1.10.3, dev branch. I am using an iPhone 7 and Catalina 10.15.2. My loop build was successful but I do not have the option to set override presets in the blue heart. I've rebuilt twice. I'm not sure what I should do. 
![IMG_588115F4BDD7-1](https://user-images.githubusercontent.com/59076105/71558420-1e5e3800-2a21-11ea-910c-ac01f77b5396.jpeg)

**Screenshots attached.

**Phone**
 - Hardware: iPhone 7
 - OS Version: iOS 13.3

**Loop Version**
 - Version Number: 1.10.3

**CGM**
 - Device:Dexcom G6
 - Manager app: Dexcom App

**Pump**
Omnipod

**Comment by ps2** [comment]
This is what happens when you do not have the latest LoopKit. Something is off from your build. If you're building via downloading a zip, then try downloading again.  If you're building from workspace, make sure you have the latest LoopKit.
