### ISSUE TITLE
Basal data not writing to Apple Health

### ISSUE THREAD

**Issue by christopherasnider** [LoopKit/Loop#1227]
Issue: Basal delivery data is not being written to Apple Health. IOB, as a result, is off.

Issue report and xCode debugging report attached.

Things I did to try and resolve this before posting something in Zulip:

1. Searched the Looped Facebook group for recent, similar issues. Didn't find anything relevant though my search skills may not be precise enough to find a post that helps.
2. Swiped up on Loop to close and re-open the app
3. Toggled all Apple Health permissions off then back on.
4. Toggled all Apple Health permissions off, waited for a Loop cycle, and turned them back on.
5. Rebooted my phone.
6. Texted Katie directly somewhere between 2 and 3.

At the time of this issue (December 29, 2019), I was running 1.10.1 Dev. A recent build, but not the most recent build. I am using pods. I am using an iPhone 7 running iOS 12.3.1.

Screenshots attached will show the main loop screen with no IOB, basal delivery documented in the Loop app, and no basal delivery showing in Apple health.

Note: This issue somehow resolved itself about 2 hours after I first noticed it. I did update to the most recent Dev build on the 29th and sometime between that new build being installed and about midnight, basal data started showing up again.

Issue report - https://loop.zulipchat.com/user_uploads/8196/YyIZN9FUTCoCtPUAZMHdIh_M/Loop-Report-2019-12-29-181630-0500.md
xCode debugging logs - https://loop.zulipchat.com/user_uploads/8196/Fqb2vVDLNiaDNiYDvY6VPcse/christophersnider-xcode-debugbing-logs-122919-903pm_EST.txt

Screen shot 1 (Loop app) - https://loop.zulipchat.com/user_uploads/8196/OB8K4vCggsMK8NWH45JZY3OS/IMG_20191229_185633.jpg
Screen shot 2 (Loop insulin delivery) - https://loop.zulipchat.com/user_uploads/8196/eYQ-A93byZW1aIx0EIOE6hC9/IMG_20191229_185642.jpg
Screen shot 3 (Apple Health insulin delivery) - https://loop.zulipchat.com/user_uploads/8196/dFPFc46ihj2c-8Y1epVwSXoh/IMG_20191229_185649.jpg

**Comment by christopherasnider** [comment]
Some discussion on Zulip, for reference. https://loop.zulipchat.com/#narrow/stream/144111-general/topic/Basal.20data.20not.20writing.20to.20Apple.20Health

**Comment by ps2** [comment]
The issue report showed a suspend, around pod change time, but no resume.

**Comment by MoreSolutions** [comment]
I get the same behavior when open looping. If I close loop, then basal data is written a few minutes later (I think at the next 5 minute interval, but haven't confirmed).

**Comment by hgspig** [comment]
When I open loop, I find the basal rates aren't being written to HK, but if I turn on close loop for even a brief period of time, the past 24h of basal data immediately gets written to HK, but no more than the past 24h. I guess a workaround for now would be to make sure to close loop at least once every 24h. I'm still having trouble with my CGM reporting erroneous BG levels to close loop all of the time.
