### ISSUE TITLE
Values for example Bolus or carbonates are not send to Nightscout with version 2.0

### ISSUE THREAD

**Issue by joewet** [LoopKit/Loop#1231]
I updated the app on my iPhone to Version 2.0
Today I saw that only the blood sugar and normal basal rate was transferred to my nightscount account. No Bolus or entered carbonates in the app are shown in Nightscout.

For a test i downgraded to V1.10 and everything is fine in nightscout.
After updating to V2.0 once again data are missing as described.

Can you help me?

**Comment by ps2** [comment]
Please recreate the issue on 2.0, and after waiting a while to make sure that carbs are not being uploaded, generate an issue report and attach it to the ticket.

**Comment by joewet** [comment]
Here is an example. At 22:03 I entered a bolus of 0.1 which is not shown in nightscout.

[Loop Report 2020-01-10 22:19:05+01:00.md.zip](https://github.com/LoopKit/Loop/files/4048031/Loop.Report.2020-01-10.22.19.05%2B01.00.md.zip)

**Comment by joewet** [comment]
And can you please have a look at 6 o'clock in the morning.
I think that there is another bug in v2.0. Because I entered some carbonates but the app doesn't calculate the correct value of insulin. After deleting the entry and entering it tow times again the value was calculated.
Is this a bug or a feature?
This is discussed on Facebook in the Looped Group. But no solution was given.

**Comment by joewet** [comment]
Just a hint for the problem with the missing data. In Nightscout I set a information "without protocol". now all data are transferred successfully.
