### ISSUE TITLE
MinimedKitPlugin” couldn’t be loaded because it is damaged or missing necessary resources

### ISSUE THREAD

**Issue by amazaheri** [LoopKit/Loop#1237]
Adding new Pump throwing the exception:

Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin): Library not loaded: @rpath/MinimedKit.framework/MinimedKit
  Referenced from: /Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin
  Reason: no suitable image found.  Did find:
	/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKit.framework/MinimedKit: no matching architecture in universal wrapper
	/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKit.framework/MinimedKit: no matching architecture in universal wrapper" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin, NSDebugDescription=dlopen_preflight(/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin): Library not loaded: @rpath/MinimedKit.framework/MinimedKit
  Referenced from: /Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKitPlugin.framework/MinimedKitPlugin
  Reason: no suitable image found.  Did find:
	/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKit.framework/MinimedKit: no matching architecture in universal wrapper
	/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKit.framework/MinimedKit: no matching architecture in universal wrapper, NSBundlePath=/Users/alimaz/Library/Developer/CoreSimulator/Devices/C0841953-88E3-4A8D-92F5-E4697A52EAAF/data/Containers/Bundle/Application/68F1A18E-A850-417B-B6C8-E047069F9D50/Loop.app/Frameworks/MinimedKitPlugin.framework, NSLocalizedDescription=The bundle “**MinimedKitPlugin” couldn’t be loaded because it is damaged or missing necessary resources.**}

**Comment by Kdisimone** [comment]
For build errors, can you please instead post the information And screenshots in Zulipchat's Build Problems channel?  That's where previous peoples solutions are too and might match what you're experiencing. Also, make sure to checkout Loopdocs' Build Errors page to check out the specifics of what to post when asking for help. Thanks. Closing comment here as this isn't a Loop big but just a build error.

**Comment by amazaheri** [comment]
Thank you! BTW its not a build error and it happens at runtime, Build runs successfully with no error or warning.
