### ISSUE TITLE
Wifi causing Red Loop?

### ISSUE THREAD

**Issue by markallen2001** [LoopKit/Loop#1239]
HELP! Giving as much detail as possible below, but here is quick summary. For past 2 months Loop has been unstable and I usually get Red Loop several times per day, including overnight. When awake, I can usually reset to green by Rileylink toggle on/off and "Change Time Zone" in Loop. But this doesn't always work. I've tried everything I can think of to resolve this (summarized below) and was beginning to think it was a pump issue. However, 48 hours ago I turned off my iPhone wifi (just running on cellular data) and green loop has run consistently!
Of course, I would like to (and need to) run wifi on my phone so would like help addressing what root cause of Red Loop is? Summary of attempted changes below, and Loop issues history attached.
[Loop Report 2020-01-15 082225-0700.txt](https://github.com/LoopKit/Loop/files/4065788/Loop.Report.2020-01-15.082225-0700.txt)

Red Loop – Actions performed to resolve
My Loop Setup:
o	Dexcom G6 CGM System
o	Medtronic 722 & am also borrowing 754 (Canadian, Ver.2.7a) to test.
o	iPhone X, IOS 13.3
o	RileyLink (obviously)
o	MacBook OS Catalina
Overview:
o	I tried to follow LoopDocs troubleshooting as well as re-reading LoopDocs in full to ensure all settings were correct.
o	Used Loop FaceBook group to search for similar issues.
Here’s the summarized changes I’ve looked at (not in chronological order):
Loop Changes:
o	Removed Nightscout from Loop
o	Ensured delivery limits Basal/Bolus maximums were higher in pump than in Loop
o	Deleted Nightscout information
o	Ensured Dexcom Share was off
o	Changed from Loopdev branch to LoopMaster branch
Nightscout
o	Cleaned Nightscout database (followed all recommendations). This was actually a problem I ran into a month or so before Red Looping started.
iPhone X
o	Rebooted iPhone (multiple times)
o	Toggled on/off bluetooth
o	Eliminated BT earbuds in case they were interfering
o	Reinstalled Loop branch (tried both Loopdev and now LoopMaster)
o	Closed/reopened Dexcom and Loop with RileyLink reboots
o	Ensured background apps closed at various times
RileyLink
o	Restart RileyLink (all the time as this manages to temporarily reset, sometimes after multiple attempts to reboot and link to pump via “Change Time Zone” activation)
o	Tried 2 different RileyLinks: They have always shown green light when “on” in Loop, The decibel level is good on both.
o	Tuned RileyLinks
o	I also have new RileyLink batteries on order, but this is likely not the root cause.
Insulin Pump
o	Tried 2 different pumps
o	Rechecked all pump settings as per Loop setup (remotes, basal rates, patterns, etc)
o	Changed pump batteries (more than once)
Dexcom
o	Changed Dexcom transmitter
o	Confirmed/deleted any Dexcom Share accounts (transmitter entered directly into Loop)
Others notes: Updated to latest versions of software. Ensured xcode, IOS (13.3) & MacOS (Catalina) were all updated to latest versions before loop changes.
Temporary Fix!
-	Shut off WiFi on iPhone. When WiFi is toggled to “off” on the iPhone, I have eliminated the red loop from occurring. However, still don’t understand root cause!
Thanks in advance for any of you that can help with this challenge.

**Comment by rolandet** [comment]
If turning off Wi-Fi does truly fix the issue then I would assume it is a possible network communication issue communicating with a service such as Dexcom or nightscout. Perhaps a DNS issue or a config issue with your router perhaps. What are you using for your home DNS service? There are 3rd party DNS services that are used to block and filter certain websites such aa OpenDNS.

**Comment by markallen2001** [comment]
I was wondering that too, but I've had the same issues on different WiFi networks (at my work and at home). I'm over my head here with understanding of DNS and network settings, but if it helps my DNS server (looking through my MacBook is 198.168.1.1 and shows as "local" under 'Search Domains'.

**Comment by breevis** [comment]
I’m the helper for Loop for my husband(he’s the user). He is having similar Red Loop issues. The toggle on/off of Riley Link usually helps. But, that becomes a problem in middle of night etc. He will try turning off WiFi today and see if that helps. But, also like you we would like to figure out what’s going on and how to get a real fix. Let me know/post on here if you get any fixes. 
He just started Looping Dec 20th so, I’m assuming her has a rather updated version of Loop. Other than connection issues we are loving Loop. When it’s connected it’s Amazing!!! We are using my husband as the test subject and would like to eventually use it for our daughter.

**Comment by markallen2001** [comment]
Solved. Or at least I know the root cause.
The cause of this is my HP Envy 5660 All-In-One Wireless Printer!
If I turn the HP Wifi off, I stop getting red loops. However, if the printer Wifi is ON it seems to interfere with Loop, even if my iPhone has forgotten this network.
I still don't understand exactly why this Wifi network interferes with Loop, but at least I am now back Looping with confidence!

**Comment by JELCRAWFORD** [comment]
We have had troubles with this periodically. I resolved it by turning off WiFi for a period in the phone. Two HP printers with WiFi enabled in the house. It has not been happening as much as usual in the recent weeks.  I will watch and a see next time. Thx for the sleuthing!

**Comment by rolandet** [comment]
Apparently you are not the only one having Wi-Fi interference issues with an HP printer.

https://h30434.www3.hp.com/t5/Printers-Archive-Read-Only/7645-Interfering-with-WiFi/td-p/5642531
