### ISSUE TITLE
Share Error when Offline

### ISSUE THREAD

**Issue by thedug** [LoopKit/Loop#1240]
I just upgraded to an iPhone 11 and I'm getting an error in Loop when I'm on a plane or don't have an internet connection.

Here's a screenshot.

![Screenshot 2020-01-16 at 1 37 30 PM](https://user-images.githubusercontent.com/158122/72637386-ce3f0b00-3926-11ea-8442-5ad76b80760c.png)

**Comment by thedug** [comment]
Here's a log from the app not long after I experienced this again. 

[Loop Report 2020-01-17 06:53:56-06:00.txt](https://github.com/LoopKit/Loop/files/4078363/Loop.Report.2020-01-17.06.53.56-06.00.txt)

**Comment by live4sw** [comment]
Have you removed your share information from settings and made sure your transmitter ID is inputted? Loop should be pulling your #'s directly. The cloud icon where the BG reading should be indicates that it was pulling from share rather than directly from the transmitter.

**Comment by live4sw** [comment]
Also, you might get more responses by posting to the Facebook group on functionality questions like this (this doesn't really look like a bug, I could be wrong).

**Comment by thedug** [comment]
Doh. I never realized that was a "cloud" icon, and I didn't realize I had to reset the loop app every time I upgraded the sensor. I thought the app was pulling data from the health app. 

Thanks!
