### ISSUE TITLE
Basal Line Offset (& Negative)

### ISSUE THREAD

**Issue by kparisella** [LoopKit/Loop#1243]
**Describe the bug***
I’ve had the scheduled-basal baseline in the Insulin Delivery graph temporarily get shifted downward, so that scheduled basals (not temp basals) appear negative (which is, of course, impossible).

This happened this morning for at least an hour, while using Automatic-Bolus branch, but Pete said this has been an issue in other branches as well.

**Attach an Issue Report**
Attached Issue Report 

[Issue report ](https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A394d2ab4-7c93-4111-996c-78a293f4af1c) 

**To Reproduce**
Unfortunately, I have no idea how it happened, but I’ve seen it a few times that I can remember, with different branches.

This morning, I had activated a 200% override before I noticed it.  I subsequently de-activated the override, but that didn’t make the basal offset go away, even after a few cycles.  It eventually resolved itself, but I’m not sure when/why.

**Expected behavior**
I expected the thin line on across the Insulin Delivery graph to represent my regularly scheduled basal rate, which was (positive) 0.6 u/h at the time.  

**Screenshots**
Attached a few screenshots while it was happening, plus screenshot of basal rates.

![AF5AAD56-C53E-41A8-9587-DDB7186FE6B2](https://user-images.githubusercontent.com/38840696/72689840-d55f4800-3ae3-11ea-8773-e59d5914ea32.png)
![38E6DC5D-D3CC-441E-B459-03F94D16E2D7](https://user-images.githubusercontent.com/38840696/72689841-d55f4800-3ae3-11ea-91c3-57f735a92e0c.png)
![358C9974-1224-4780-AD50-9D32BDB4F814](https://user-images.githubusercontent.com/38840696/72689842-d55f4800-3ae3-11ea-9d10-0abce40301d2.png)
![D7D6F930-6DAF-4A61-B3B3-EBA798851C1C](https://user-images.githubusercontent.com/38840696/72689843-d5f7de80-3ae3-11ea-915e-4fdacbd4014c.png)

**Phone**
 - Hardware: iPhone 8 plus
 - OS Version: iOS 13.3

**Loop Version**
 - Version Number: 1.10.3
 - Repo: Automatic-Bolus from Workspace

**CGM**
 - Device: Dexcom G6
 - Dexcom App

**Pump**
 - Medtronic
 - Model: 522
 - Firmware version: 2.4A

**Comment by ps2** [comment]
This was fixed in Loop 2.2
