### ISSUE TITLE
Change Insert Cannula from a button to a "Slide to Unlock"

### ISSUE THREAD

**Issue by jaredwhittle** [LoopKit/Loop#1246]
Similar to the Apple Watch "rotate crown to bolus", I believe the Insert Cannula should have a "Slide to Insert Cannula" instead of a button to prevent accidental insertion before it's ready.

**Comment by dabear** [comment]
I've implemented this in https://github.com/LoopKit/OmniBLE/pull/99

**Comment by dabear** [comment]
This can be closed as solved by https://github.com/LoopKit/OmniBLE/pull/99
