### ISSUE TITLE
Loop not resuming after resuming on pump on automatic-bolus branch

### ISSUE THREAD

**Issue by mitchellhenke** [LoopKit/Loop#1248]
**Describe the bug**
On the [automatic-bolus](https://github.com/LoopKit/Loop/tree/automatic-bolus) branch, when resuming a Medtronic pump from suspend by pressing the buttons the pump itself, Loop does not resume and try to attempt applying automatic boluses.

Can work around by manually telling Loop to resume in app.

**Attach an Issue Report**
[Loop Report 2020-01-21 15:59:17-06:00.txt](https://github.com/LoopKit/Loop/files/4093936/Loop.Report.2020-01-21.15.59.17-06.00.txt)

**To Reproduce**
1. Suspend MDT Pump by pressing ACT > Suspend > ACT > ACT
2. Resume MDT Pump by pressing ACT > ACT
3. Pump will resume, but Loop will not

**Expected behavior**
Loop would resume applying automatic boluses when pump is resumed.

**Screenshots**

**Phone**
 - Hardware: iPhone XR
 - OS Version: 13.3

**Loop Version**
 - Version Number: 2.1.0-dev
 - Repo: My own branch based on dev with automatic-bolus, FPU, and integral retrospective correction. Dev commit [08a6f35a49ec408530a6ae3baf1469efb0e708ef](https://github.com/LoopKit/Loop/commit/08a6f35a49ec408530a6ae3baf1469efb0e708ef) and automatic-bolus commit [0b477bc153f03925bb71c7dc5886a762f3ead0ea](https://github.com/LoopKit/Loop/commit/0b477bc153f03925bb71c7dc5886a762f3ead0ea)

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 522
 - Firmware version: 2.4A

**Additional context**
Potentially related to https://github.com/LoopKit/Loop/issues/1236, also mentioned as being seen by someone in Zulip [here](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Automatic.20Bolus.20Experimental.20Branch.20%28PR.201219%29/near/186227146)

**Comment by jath622** [comment]
I also have this same problem on a MedT 723 running software 2.3A, with an iPhone 7+ with iOS 13.3.1, G5, loop automatic blousing v 2.1.0.

**Comment by cfaagaard** [comment]
Same problem here. With dexcom g6 and MD 522. On auto-bolus branch.
