### ISSUE TITLE
Omnipod: Temp basal in HUD doesn’t show correct value when using override

### ISSUE THREAD

**Issue by MrBennington** [LoopKit/Loop#1251]
**Describe the bug**
Using an override that increases or decreases insulin delivery by percentage leads to showing incorrect basal HUD values for Omnipod system.

I was using a +10% override. Scheduled basal was 0.55 U/h. The HUD on top of the app showed -0.005 U. In Nightscout it showed 0.6 U/h active temp basal which seems to be correct.

1. When using the Omnipod the HUD should just show temp basals in increments the pump does physically support. Like we all know, Pods minimum increment is 0.05 U. -0.005 U/h seems to be a Medtronic related value.

2. The Nightscout page showed an increase of 0,05 U/h (total 0.6 U/h) that matched the basal raise by using the override. The value -0.005 U/h showed a decrease instead. 

3. And despite the sign “-“, I wonder if there's probably another rounding error involved, but   I guess in the end this is not a bug: 0,005U/h would be rounded to 0.01 U/h. And when using an Omnipod this would be closer to zero than to 0.05U/h. So I wonder why there was any raised temp basal at all.

**To Reproduce**
1. Setup override that would raise insulin delivery by 10%
2. Activate override
3. Wait for new temp basal adjustment
4. Compare HUD value to effectively delivered temp basal increase

**Expected behavior**
Showing + 0.05 U/h in HUD instead of -0.005 U/h

**Screenshots**
![29618535-586B-4AD1-A8AC-2A8F0AA52FD5](https://user-images.githubusercontent.com/27304217/73361104-9039d380-42a4-11ea-97b7-f65dbe52bc66.png)
![D471AF1F-E586-41AC-BA4F-66477343A3A9](https://user-images.githubusercontent.com/27304217/73361107-90d26a00-42a4-11ea-87a2-d81c9377c20c.jpeg)

**Phone**
 - Hardware: iPhone 6s
 - OS Version: iOS 13.3

**Loop Version**
 - Version Number: 1.10.3
 - Repo: LoopKit/Loop DEV, built early January

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod

Log-file attached, please rename to .md
[Loop Report 2020-01-29 13_53_35+01_00.md.txt](https://github.com/LoopKit/Loop/files/4128397/Loop.Report.2020-01-29.13_53_35%2B01_00.md.txt)

**Comment by tomgeraghty3** [comment]
Hi,
I think point (1) may be valid but in regards to the HUD ... the way I believe it works is it always shows any Loop basal adjustments RELATIVE to your override/schedule. So if you were getting 0.6U (with 10% override active) and no adjustments were being made by loop then the UI would have +0.0U. In your case Loop was enacting ((0.55U + 10%) - 0.005U) hence why you see -0.005U... If you want to see the actual specific amount (including the override) that is active you can click on the pod and go down to Status you can see "Basal Delivery" and that will show the actual basal units delivery... Son in your case you'd see (0.6U - 0.005U). When there is no override on this simply displays "Schedule". Does that make sense? 


I actually changed a bit of the code in my custom branch to display these differences on the UI just below the HUD. It shows the actual basal being delivered and has the scheduled in brackets (if this differes from the current basal delivery) and also shows the last bolus, how many units and how long ago (like the PDM used to do). I don't know if people would find this useful but I could raise a PR to merge into dev if people wanted ...
@ps2 Pete any thoughts? It's visibility is driven by a harded boolean returning true at the minute but we could make this a configurable option in the settings. It's also hardcoded to OmniPod (as that's what I use) so would need a bit of refactoring...

@MrBennington I think my screenshot shows what I'm trying to explain. When I have the 20% override on it's delivering 1.55U (which is 20% above my Schedule of 1.3U) but the HUD has -0.01U as that's Loops relative basal adjustment (as opposed to the difference between the override and the schedule i.e. +0.25U like you were expecting)

![InsulinDeliveryPnlWithOverride](https://user-images.githubusercontent.com/47372735/73506559-ca52c480-43cd-11ea-972a-2207accda6c8.png)
![InsulinDeliveryPnlWithoutOverride](https://user-images.githubusercontent.com/47372735/73506560-caeb5b00-43cd-11ea-8179-685e35f0c6ef.png)

**Comment by rolandet** [comment]
@tomgeraghty3 I believe your HUD update for basal delivery would make things less confusing. The information on basal delivery In the HUD display has always confused me especially when override are in use. Would be nice to see something like this in the dev branch.

**Comment by bjornoleh** [comment]
@tomgeraghty3 I would love test your custom code for actual basal and recent bolus. Unfortunalely I am not quite up to speed with making code changes, but perhaps you could point me in the right direction to help me get started? 

As the issue report at hand suggests, the UI could be improved to reduce confusion about the current basal delivery. Ideally, this should make its way into Master when it is refined and tested. I believe it reduce the need for some of the  switching between Loop and Nightscout that I keep doing now. Or save users from having to inspect the basal settings, reading pump status, and checking the pump events history.

> I actually changed a bit of the code in my custom branch to display these differences on the UI just below the HUD. It shows the actual basal being delivered and has the scheduled in brackets (if this differes from the current basal delivery) and also shows the last bolus, how many units and how long ago (like the PDM used to do). I don't know if people would find this useful but I could raise a PR to merge into dev if people wanted ...>

**Comment by hhinma** [comment]
Quite apart from the original problem described in the issue, I think the additions to the HUD display would be very useful.   I would be very interested in the code to merge it into my branch.

**Comment by ps2** [comment]
Basal shown in the hud is relative to your *overridden* basal rate. If you have a +10% override, your basal rate is multiplied times 1.1 and that is the value that temp basals are shown relative to.  If you are below the value of your basal * 1.1 but still above regular basal, the hud will show a negative sign, because Loop is low temping you, in an attempt to bring your bg up, even though you're above your non-overridden basal rate.
