### ISSUE TITLE
Question for the developers

### ISSUE THREAD

**Issue by miki3421** [LoopKit/Loop#1254]
Hi Devs Team, 
first thanks for all the amazing job that you've done.
I would like to know if there is a way to bypass the condition that is making the CGM reader not operational until is not activated a real pump. 
My idea is using a real CGM with the Pump Simulator. 
any idea o toughs about that?
If you can tell me where is this condition in the code i can even make a custom version of the software without  bothering you.
Michele

**Comment by novalegra** [comment]
This is currently possible with any of the mainline Loop branches - I do this sometimes to test.
