### ISSUE TITLE
Watch and iPhone apps display different BG predictions

### ISSUE THREAD

**Issue by novalegra** [LoopKit/Loop#1257]
**Describe the bug**
Loop (on the iPhone) is displaying the predicted glucose that includes pending insulin, but the predicted BG curve on the watch does not incorporate the pending insulin. I confirmed this with breakpoints in Xcode.

**To Reproduce**
1. Open Loop app and install Watch app to watch.
2. Navigate to watch's "predicted glucose" screen.
3. Check to make sure a non-neutral temp basal is running.
4. There should be a difference between the prediction on the watch and the main Loop app.

**Expected behavior**
The BG predictions should be the same across the watch and iPhone apps.

** Issue Report **
[Display_bug_report.pdf](https://github.com/LoopKit/Loop/files/4140650/Display_bug_report.pdf)

**Screenshots**
![IMG_3753](https://user-images.githubusercontent.com/31571514/73560833-934fd380-440c-11ea-93fe-ceac6d416dc2.PNG)
![IMG_1056](https://user-images.githubusercontent.com/31571514/73560879-ac588480-440c-11ea-9688-71421dbec7ed.jpg)

**Phone**
 - Hardware: iPhone XS
 - OS Version: iOS 13.0
 - Watch: Series 3, watchOS: 6.0

**Loop Version**
 - Version Number: 2.1.0
 - Repo: LoopKit/Loop, dev

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Simulator version

**Comment by bartsluimer** [comment]
Looks like the same is valid for the IPhone widget

**Comment by bfeinzimer** [comment]
I second this, as well, active insulin is different in the loopapp/watch

**Comment by biesbjerg** [comment]
I noticed a difference between the app and the iPhone widget as well.

I think this issue is fixed in dev by https://github.com/LoopKit/Loop/commit/8642f4c6f6abc5ea3dd3792fadb636bad843134d?

**Comment by novalegra** [comment]
Closing since issue was fixed
