### ISSUE TITLE
Upload Readings publishes decimal date

### ISSUE THREAD

**Issue by glebivanov** [LoopKit/Loop#1259]
After enabling **Upload Readings** feature in Loop [xDrip](https://github.com/NightscoutFoundation/xDrip) failed to load data from Nightscout reporting the following error:  expected a long but was 1580502615952.616.

When checking the entries published to Nightscout it looks like Loop is publishing a decimal value, not long for date:
`{
    "_id": {
        "$oid": "5e348e64c4a89b54fd8f3787"
    },
    "direction": "DoubleUp",
    "device": "CGMBLEKit Dexcom G6 21.0",
    "dateString": "2020-01-31T20:30:15.000Z",
    "sgv": 255,
    "date": 1580502615952.616,
    "type": "sgv",
    "utcOffset": 0,
    "sysTime": "2020-01-31T20:30:15.000Z"
}
`

A normal Dexcom Share entry looks like 
`
{
    "_id": {
        "$oid": "5e34969dc4a89b54fd8f8fa3"
    },
    "sgv": 168,
    "date": 1580504714000,
    "dateString": "2020-01-31T21:05:14.000Z",
    "trend": 6,
    "direction": "SingleDown",
    "device": "share2",
    "type": "sgv",
    "utcOffset": 0,
    "sysTime": "2020-01-31T21:05:14.000Z"
}
`

I suggest we change the date format to long to be compatible with the Nightscout clients like xDrip.

**Comment by dabear** [comment]
Latest xdrip nightly has fixed this compatability issue

**Comment by glebivanov** [comment]
I confirm the issue has been fixed in xdrip codebase, closing this ticket.
