### ISSUE TITLE
Deliver button accessibility on small screens

### ISSUE THREAD

**Issue by mylma** [LoopKit/Loop#1260]
**Describe the bug**
ISSUE 1: Meal bolus and Bolus views
Deliver bolus button is not accessible without scrolling, when the user overrides the Recommended meal bolus amount or gives a manual correction bolus instead of just tapping the Recommended field. This issue is related to smaller screen iPhone models.

ISSUE 2: Meal bolus view
When there is a notification visible on the Meal bolus screen, the deliver button drops partly outside the screen and is not easily accessible without scrolling.

**To Reproduce**
1. Use iPhone SE, 7 or 8.
2. Open the Bolus or Meal bolus screen.
3. Tap the Bolus field to set a bolus amount.
4. Keyboad hides the Deliver button, so user needs to carefully scroll the view down to reveal it.

**Expected behavior**
Essential functions should be visible and accessible without scrolling. 
ISSUE 1: There could be a second Deliver button at the top right corner, AND/OR
ISSUE 2: Prediction chart could be smaller so that the Deliver button always fits on the view.

**Screenshots**
ISSUE 1
![Näyttökuva 2020-2-2 kello 15 17 15](https://user-images.githubusercontent.com/44064056/73609249-88479f80-45d4-11ea-8a32-62145a0e9eb5.png)
![Näyttökuva 2020-2-2 kello 15 17 35](https://user-images.githubusercontent.com/44064056/73609253-909fda80-45d4-11ea-92f3-75d52ffd616a.png)

ISSUE 2
![Näyttökuva 2020-1-28 kello 19 32 45](https://user-images.githubusercontent.com/44064056/73609261-9990ac00-45d4-11ea-9913-ff6299cde0a6.png)

**Phone**
 - Hardware: iPhone SE, 6, 7 and 8
 - OS Version: all 

**Loop Version**
 - Version Number: 2.1.0
 - Repo: dev with the updated add carbs & bolus UI

**Comment by mylma** [comment]
Alternative fix for the issue 1 could be scrolling the view to the bottom when the bolus text field is active, so that the Deliver button will fit on the view area too. Then there wouldn’t be a need for the top right deliver button anymore.

**Comment by beached** [comment]
This is similar to the issue I posted https://github.com/LoopKit/Loop/issues/1213

**Comment by bfeinzimer** [comment]
What happened to the pending insulin calc on the bolus screen, if you want to speed up a temp basal with a bolus?

**Comment by mylma** [comment]
Pending insulin is now included in the bolus recommendation. See https://github.com/LoopKit/Loop/commit/c21180dbf84201a997ef73d03033870bb0035df2

**Comment by bkhx** [comment]
The "hidden deliver button" issue also applies to iPhoneX iOS 13.4.1 with Text Size set to 1 notch below max.
![loopMissingDeliverButton](https://user-images.githubusercontent.com/64649016/80814964-d00da100-8b9a-11ea-85bc-6bb074eee1c0.jpeg)
