### ISSUE TITLE
Pod Failure 

### ISSUE THREAD

**Issue by r212917** [LoopKit/Loop#1262]
Hi! I am receiving repeated pod pairing failures. I followed the trouble shooting measures on the loop docs site (toggled on/on rileylink, moved beeping pods far away out of the house, turned on/off app & Bluetooth). I went through 4 pods and just resorted to my PDM after the 4th. I keep receiving the error “no response move pod closer.” What else should I do? I’m traveling for the next 2 weeks and worried about wasting more pods. I’m using loop v2.0 (built on 1/28), an iPhone XS iOS 13.3, & Omnipod Eros.

**Comment by Kdisimone** [comment]
The best place for these kind of questions would be to post in Looped group or Zulipchat for feedback.  You'll get lots of good suggestions there. The issues list here is more for reporting bugs and providing the useful logs, Issue Reports, sysdiagnose logs, etc. to help resolve the bugs.

(sounds like you should check that your rileylink lights are lighting up as expected...if they aren't that could be a sign that something is wrong with your rileylink. Info on rileylink lights is in loopdocs)
