### ISSUE TITLE
Loop not reading on iPhone after multiple attempts to load per loop docs instructions

### ISSUE THREAD

**Issue by juliebailey-dev** [LoopKit/Loop#1263]
I need help -terminal reads successful Xcode  in running Xcode but the green circle remains grey and loop not showing Dexcom reading I can’t bolus from loop. I’ve reloaded loop at least 12 times trying to fix as recommended. I’m ready to delete ap and reload but I’ll wait for further guidance.

**Comment by Kdisimone** [comment]
Julie...as we discussed earlier, please post this in Looped group and include screenshots. That is the place to get the help for these kind of issues We need you to post the requested info and screenshots that I mentioned earlier.

**Comment by juliebailey-dev** [comment]
I finally have time today -very anxious to get this resolved-Riley is reading Omnipod and Dexcom so a piece of this system is working just not the display on the phone and bolus capacity- but I’ll get it up on loop group
Julie

**Comment by Kdisimone** [comment]
Awesome!!! I know it would be out of the way a bit...but you're welcome to come to paso and I can take a look in person.

**Comment by juliebailey-dev** [comment]
Thank you-I’ll gladly drive up
When are u available
Julie

**Comment by juliebailey-dev** [comment]
Katie 
Do you have time this weekend for me to bring my computer up to try to figure out what the heck is going on with my loop iPhone connection? I’m only in Los osos easy trip to Paso anxious to get this thing fixed and very curious as to where the problem is I’m sure stumped.  
Julie Bailey
