### ISSUE TITLE
Active Insulin value cut off on Apple Watch display

### ISSUE THREAD

**Issue by dirkgastaldo** [LoopKit/Loop#1269]
**Describe the bug**
The first digit of the ACTIVE INSULIN display on the 2nd page of the Loop app on the Apple Watch is cut off by the display border. You can only see about half of the first digit. I would expect to see all of the first digit.

**Attach an Issue Report**
[Loop Report 2020-02-13 002452-0800.txt](https://github.com/LoopKit/Loop/files/4197200/Loop.Report.2020-02-13.002452-0800.txt)

**To Reproduce**
1. Go to Loop app on Apple Watch.
2. Swipe left to display second page of display.
3. If you have IOB you will see the first digit of ACTIVE INSULIN cut off by the lower left corner of the Watch screen display border.

**Expected behavior**
I expected to see 100% of the ACTIVE INSULIN value.

**Screenshots**

![IMG_0327](https://user-images.githubusercontent.com/29110417/74415318-fd4a7e80-4df7-11ea-82d3-cd29ea64b494.jpg)

**Phone**
 - iPhone XR
 - OS Version: iOS 13.3.1
 - Apple Watch Series 5
 - watchOS: 6.1.2

**Loop Version**
 - Version Number: 2.1.0
 - Repo: Automatic Bolusing (downloaded 2/13/2020)

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: OmniPod Eros
 - Firmware version: N/A

**Additional context**
None, other than I apologize if I'm doing something wrong to produce this, or if it's already been reported. I did search, but couldn't find it.

**Comment by marionbarker** [comment]
Without scrolling, my Active Insulin is not clipped on my Series 3 watch. Same version of code and OS.

**Comment by Trpl7ca** [comment]
I also have the same problem. Apple Watch series 5 and IPhone 11 Pro.

**Comment by elnjensen** [comment]
@marionbarker It’s only the Series 4 and 5 that have the rounded corners of the display area, I believe. I see this on my Series 4 as well. 

This was an issue [a while back](https://github.com/LoopKit/Loop/pull/1052) but then seemed to be resolved with WatchOS updates, but now it’s back. I was able to fix it in my own build with a manual offset, but that’s a bit of a hack.
