### ISSUE TITLE
Bolus did not register in app

### ISSUE THREAD

**Issue by nelliebeam** [LoopKit/Loop#1270]
Bolused for dinner (5.4 units), while bolus was audibly dosing (could hear omnipod clicking) the phone froze, screen would not register touch, no buttons worked (iphone 7). Performed soft reset of iphone (power button and down volume button until apple icon screen). At restart of iphone, checked app to make sure everything was ok, noticed the active insulin graph did not have 5.4 units, looked at history, no record of bolus. Waited 15 minutes for loop to run a few times, continually calling for temp basal at max basal limit (ie, loop not knowing about bolus).

not sure how to reproduce, slightly freak accident of phone freezing mid-bolus (never had phone freeze before while using loop)

Checked pump status, sorry didnt get screen shot, but the total units of insulin for today was 5.4 units higher than what were in the loop insulin delivery history. So I manually added the 5.4 unit delivery into the health app, which loop then saw and used in next evaluation.

**Phone**
 - Hardware: iphone 7
 - OS Version: iOS 13.3

**Loop Version**
 - Version Number: 12.0
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: Dexcom G6
 - Manager app:  Dexcom App

**Pump**
 - Manufacturer: Omnipod

[Loop Report 2020-02-13 210413-0500.md.zip](https://github.com/LoopKit/Loop/files/4202382/Loop.Report.2020-02-13.210413-0500.md.zip)

**Comment by ps2** [comment]
Loop freezes should be fixed with this change: https://github.com/LoopKit/LoopKit/pull/317, which is now in dev.
