### ISSUE TITLE
Loop counts basal rate while changing pods (unless suspend first)

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1271]
**Describe the bug**
I normally suspend pod, issue a report (and save it), then replace pod. One time, I did not do this and noticed Loop thought I was getting basal while no pod was attached.

**Attach an Issue Report**
I zipped together the reports before and after the pod change. 
[Loop Reports 2020-01-19_PodChangeBasalQuestion.zip](https://github.com/LoopKit/Loop/files/4209340/Loop.Reports.2020-01-19_PodChangeBasalQuestion.zip)

Timing information:
Loop Report 2020-01-19 08_00_26-08_00_0x18.md 
(ran out of insulin and captured the fault in log)
Last messages:
* 2020-01-19 15:56:50 +0000 send 1f074f9514201a0ebce5ac4d010091013840000c000c160e0000007d00dbba00007d00dbba008249
* 2020-01-19 15:56:51 +0000 receive 1f074f95180a1d290590a800003b6c00038e
* 2020-01-19 15:59:33 +0000 send 1f074f951c030e01000258
* 2020-01-19 15:59:35 +0000 receive 1f074f9520180216020d000000050b22180edd00000edd0000091b0900db8056

Loop Report 2020-01-21 17_03_58-08_00.md
* activatedAt: Optional(2020-01-19 16:28:00 +0000)
* primeFinishTime: Optional(2020-01-19 16:28:55 +0000)
Pod was initialized with 18 messages, 1 AssignID, 1 SetUpPod required
Messages 17 thru 20:
* 2020-01-19 16:37:41 +0000 send 1f05bb83281f1a0ed85151190200ab01008800110011170d0000aa000186a00000000000008255
* 2020-01-19 16:37:43 +0000 receive 1f05bb832c0a1d570017501100002bff02c4
* 2020-01-19 16:38:01 +0000 send 1f05bb8330030e0100037e
* 2020-01-19 16:38:03 +0000 receive 1f05bb83340a1d18001fd00000002bff8309

**Screenshots**
PodChange_BasalAccounting_IMG_1711.jpg was taken from Apple Health that morning
Tidepool_at_pod_change_2020-01-19_0800_PST.png was captured from Tidepool mobile showing that scheduled basal was indicated as being used even while pod was off body up until 8:43 am.

I am in PST therefore 8 hours behind UTC.
End prior pod delivery after 7:57 and before 7:59 PST
Start next pod delivery at 08:37 PST
Basal rate at that time: 1.15 u/hr
The Apple Health screenshot reports basal between 7:59 and 8:43 total was 0.95 units
Basal delivered from 8:37 to 8:43 was ~0.10 u.

![PodChange_BasalAccounting_IMG_1711](https://user-images.githubusercontent.com/19607791/74599202-1c812000-5033-11ea-9093-0544e7761bca.jpg)

![Tidepool_at_pod_change_2020-01-19_0800_PST](https://user-images.githubusercontent.com/19607791/74598910-1b4df400-502f-11ea-9a2c-0931ea93608e.png)

**Other**
 - Hardware: iPhone 11 pro
 - OS Version: iOS 13.3
 - Version Number: automatic-bolus, gitRevision: 69956cdc17e24002c38dbbde19d21c837fec4f97
 - Repo: LoopKit/Loop
 - xcodeVersion: 11C29
 - Device: Dexcom G6
 - Manager app: Dexcom App
 - Pump: Omnipod

**Comment by sraka1** [comment]
I second this issue. Just struck me today. When pod is deactivated or if a non-recoverable alarm (i.e. expired 80 hrs) is received, it should be logged to be in a suspended state.

**Comment by ps2** [comment]
This behavior somewhat by design to prevent large amounts of negative insulin accumulating when users may be taking pump breaks and using other insulin therapy. It is a continued behavior from when Loop only used Medtronic pumps.  But I do agree that a short pod replacement should be treated as no delivery.

**Comment by marionbarker** [comment]
This was modified in Loop v2.2.6 and Loop-dev.  Loop does not count basal insulin between deactivation of the old pod and insertion of the new pod.
