### ISSUE TITLE
Dosing too aggressive after carbs entered without BG data

### ISSUE THREAD

**Issue by mpangburn** [LoopKit/Loop#1279]
**Describe the bug**
When BG data is absent—e.g. during sensor warmup—a user can enter carbs and give insulin. However, insulin counteraction effects are not observed due to the absence of BG data. As a result, when BG data returns—e.g. sensor warmup completes—Loop fails to appropriately acknowledge the absorption of carbohydrates during the time when BG was absent, resulting in an inaccurately high carb effect and a potential over delivery of insulin.

**Attach an Issue Report**
Issue Report: [Loop Report 2020-03-01 13:13:40-08:00.md.zip](https://github.com/LoopKit/Loop/files/4272446/Loop.Report.2020-03-01.13.13.40-08.00.md.zip)

**To Reproduce**
1. Remove source of BG data.
2. Enter carbohydrates and give an appropriate amount of insulin.
3. Wait some time, such that a substantial portion of carbohydrate absorption has already occurred, but not so long that the carb entry is considered expired.
4. Restore the source of BG data.
5. Observe the dosing recommendation.

**Expected behavior**
A larger fraction of carbohydrates should be considered absorbed, resulting in a less aggressive dosing once BG data returns.

**Screenshots**
![IMG_1136](https://user-images.githubusercontent.com/25555889/75634171-19a03680-5bc0-11ea-96de-ee5f5787fc2c.PNG)
![IMG_1137](https://user-images.githubusercontent.com/25555889/75634173-1c9b2700-5bc0-11ea-95ee-ba4069ff754a.PNG)

**Phone**
 - Hardware: iPhone 8
 - OS Version: 13.3

**Loop Version**
 - Version Number: 2.1.0 (Automatic Bolusing)
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 723
 - Firmware version: 2.3A 1.1 0B 0B

**Additional context**
This problem exists on non-AB branches. However, AB's more aggressive dosing algorithm gives Loop substantially less leeway to recover from a large dose delivery, exacerbating this issue.

**Comment by marionbarker** [comment]
I believe this may still be an issue. I recently saved some data during a sensor warmup. I will prepare it and upload in a future comment.
