### ISSUE TITLE
Feature request: Semi open/closed

### ISSUE THREAD

**Issue by FreThor** [LoopKit/Loop#1284]
It would be nice to have a semi open/closed state.
With this I mean a state where you run on the scheduled basal only, no automatic increase.
In this respect it would act like open loop.
But I would still like to have the safety of letting it decrease the basal to avoid lows.
The purpose of this would be when you want more manual control, but still have a safety for lows.

**Comment by Kdisimone** [comment]
You can already do this by setting your max basal only so high as your highest scheduled basal rate
