### ISSUE TITLE
Dexcom not reflecting correct on loop app 

### ISSUE THREAD

**Issue by sandragall** [LoopKit/Loop#1286]
Dexcom won’t reflect numbers on Riley link 

Generated: 2020-03-16 04:57:18 +0000

Loop v2.0
* gitRevision: N/A
* gitBranch: N/A
* sourceRoot: /Users/joaquinolaverria/Downloads/Loop-master
* buildDateString: Wed Jan 15 22:45:28 CST 2020
* xcodeVersion: 11C504

## DeviceDataManager
* launchDate: 2020-03-16 04:47:46 +0000
* lastError: nil
* lastBLEDrivenUpdate: 2020-03-16 04:57:13 +0000

## G6CGMManager
latestReading: Optional(CGMBLEKit.Glucose(glucoseMessage: CGMBLEKit.GlucoseSubMessage(timestamp: 6062185, glucoseIsDisplayOnly: true, glucose: 183, state: 6, trend: 2), timeMessage: CGMBLEKit.TransmitterTimeRxMessage(status: 0, currentTime: 6062185, sessionStartTime: 5797827), transmitterID: "8GE1JS", status: CGMBLEKit.TransmitterStatus.ok, activationDate: 2020-01-06 01:00:48 +0000, sessionStartDate: 2020-03-13 03:31:15 +0000, lastCalibration: nil, readDate: 2020-03-16 04:57:13 +0000))
latestConnection: Optional(2020-03-16 04:57:12 +0000)
dataIsFresh: true
providesBLEHeartbeat: true
## ShareClientManager
latestBackfill: nil

observers.count: 0
## PeripheralManager
peripheral: <CBPeripheral: 0x28251cbe0, identifier = 18B9CE1C-7769-3411-B2D4-573F6CDBF949, name = DexcomJS, state = connecting>
needsConfiguration: false
### Activity log
[11:57:12 PM] Connected
[11:57:13 PM] New reading: 2020-03-16 04:57:13 +0000

## OmnipodPumpManager
podComms: ## PodComms
podState: Optional(### PodState
* address: 1F0B2B2D
* activatedAt: Optional(2020-03-15 20:22:14 +0000)
* expiresAt: Optional(2020-03-18 20:21:04 +0000)
* setupUnitsDelivered: Optional(2.75)
* piVersion: 2.9.0
* pmVersion: 2.9.0
* lot: 45256
* tid: 971629
* suspendState: resumed(2020-03-16 01:32:57 +0000)
* unfinalizedBolus: nil
* unfinalizedTempBasal: nil
* unfinalizedSuspend: nil
* unfinalizedResume: nil
* finalizedDoses: []
* activeAlerts: [:]
* messageTransportState: MessageTransportState(packetNumber: 31, messageNumber: 0)
* setupProgress: completed
* primeFinishTime: Optional(2020-03-15 20:23:09 +0000)
* configuredAlerts: [OmniKit.AlertSlot.slot7: Pod expiration advisory alarm, OmniKit.AlertSlot.slot2: Shutdown imminent alarm]

fault: nil
)
configuredDevices: ["BBBBEF2C-6B2D-DD1B-205C-B7DDAFDE7FA8"]
delegate: true

state: ## OmnipodPumpManagerState
* timeZone: GMT-0600 (fixed)
* basalSchedule: BasalSchedule(entries: [OmniKit.BasalScheduleEntry(rate: 1.3, startTime: 0.0), OmniKit.BasalScheduleEntry(rate: 1.5, startTime: 68400.0), OmniKit.BasalScheduleEntry(rate: 1.5, startTime: 79200.0)])
* expirationReminderDate: Optional(2020-03-18 18:22:14 +0000)
* unstoredDoses: []
* suspendEngageState: stable
* bolusEngageState: stable
* tempBasalEngageState: stable
* lastPumpDataReportDate: Optional(2020-03-16 04:57:15 +0000)
* isPumpDataStale: false
* confirmationBeeps: false
Optional(### PodState
* address: 1F0B2B2D
* activatedAt: Optional(2020-03-15 20:22:14 +0000)
* expiresAt: Optional(2020-03-18 20:21:04 +0000)
* setupUnitsDelivered: Optional(2.75)
* piVersion: 2.9.0
* pmVersion: 2.9.0
* lot: 45256
* tid: 971629
* suspendState: resumed(2020-03-16 01:32:57 +0000)
* unfinalizedBolus: nil
* unfinalizedTempBasal: nil
* unfinalizedSuspend: nil
* unfinalizedResume: nil
* finalizedDoses: []
* activeAlerts: [:]
* messageTransportState: MessageTransportState(packetNumber: 31, messageNumber: 0)
* setupProgress: completed
* primeFinishTime: Optional(2020-03-15 20:23:09 +0000)
* configuredAlerts: [OmniKit.AlertSlot.slot7: Pod expiration advisory alarm, OmniKit.AlertSlot.slot2
### MessageLog
* 2020-03-15 20:22:04 +0000 send ffffffff000607041f0b2b2d0185
* 2020-03-15 20:22:05 +0000 receive ffffffff0417011502090002090002020000b0c8000ed36d8e1f0b2b2d0095
* 2020-03-15 20:22:05 +0000 send ffffffff001503131f0b2b2d1404030f140f160000b0c8000ed36d003e
* 2020-03-15 20:22:08 +0000 receive ffffffff041d011b13881008340a5002090002

**Comment by ps2** [comment]
Please describe what you are seeing, and what you expect to see. I can't make any sense of "Dexcom won’t reflect numbers on Riley link". Also, your issue report is truncated, and not showing much.

**Comment by ps2** [comment]
Not sure what problem this ticket is describing, please reopen if you are still having the issue, and add more details about what is wrong.
