### ISSUE TITLE
mmol target BG range display

### ISSUE THREAD

**Issue by CrushingT1D** [LoopKit/Loop#130]
to duplicate in v0.10, go to Health, switch to mmol in BG.
Restart the app. Go into target BG range and delete your values that were previously set in mg/dl.
Leave and go back in. It will now ask to enter as mmol.
Enter values. See target range in screenshot below

![img_6380](https://cloud.githubusercontent.com/assets/18058098/17836632/2cc9c43c-67dc-11e6-97de-c5f6a6d3ed20.png)

**Comment by loudnate** [comment]
Thanks! Should insulin sensitivities be in mmol/L/U?

**Comment by CrushingT1D** [comment]
I was wondering the same thing. I think it works as is, but i figure if i delete them out and go to add back it will give me mmol option? Let me pull in someone using it.

**Comment by walker0** [comment]
I Haven't had any problems setting up using solely mmol with a sensitivity in mmol/L/U 

![loop_settings](https://cloud.githubusercontent.com/assets/17603635/17840392/81eb9e50-6849-11e6-9457-8b8391d62107.jpg)

**Comment by beached** [comment]
What about mmol/L per U 
or 
mmol/U

mmol/L/U seems like a mouthfull.
