### ISSUE TITLE
Manual bolus from carb entry when glucose unavailable will neither deliver nor error

### ISSUE THREAD

**Issue by ohbrandon** [LoopKit/Loop#1300]
When glucose data is unavailable and carbs are entered a manual bolus (via carb entry) will not deliver or error, but a manual bolus originating from bolus entry will do one or the other.

**Comment by martinlbrook** [comment]
Confirmed. I've been experiencing this since switching to 2.2.

If there is no CGM data then loop will recommend 0 bolus. If I manually enter the amount I want to give, and hit deliver, nothing happens.

**Comment by goldendel** [comment]
Also noticed this (more after moving to Omnipod as I would manually bolus on Medtronic before). Open looping is the workaround.
