### ISSUE TITLE
Temporary Override screens translations not visible

### ISSUE THREAD

**Issue by mylma** [LoopKit/Loop#1304]
**Describe the bug**
While testing the Finnish translations, I noticed that the Overrides section screens are still in English, although correct translations should be in the code (for example here: https://github.com/LoopKit/LoopKit/blob/dev/LoopKitUI/fi.lproj/Localizable.strings). 

**To Reproduce**
1. Choose any language other than English, for example Finnish.
2. Open the Overrides view.

**Expected behavior**
Selected language should be visible. Same issue with Swedish, Norwegian, Italian etc.  

**Screenshots**
![Näyttökuva 2020-4-17 kello 18 51 08](https://user-images.githubusercontent.com/44064056/79589416-0862a900-80de-11ea-9487-1395d4019836.png)
![Näyttökuva 2020-4-17 kello 18 51 53](https://user-images.githubusercontent.com/44064056/79589382-fe40aa80-80dd-11ea-9653-1ca569dd7b0f.png)
**Phone**
 - Hardware: Xcode simulator, also iPhone 8

**Loop Version**
 - Version Number: Current dev (LoopWorkspace and Loop builds), latest commit ac77834, latest master release

**Comment by mylma** [comment]
"Custom Override" title translation is visible, located here: 
https://github.com/LoopKit/Loop/blob/dev/Loop/fi.lproj/Localizable.strings

...but everything else is still in English.

![Näyttökuva 2020-4-17 kello 21 05 12](https://user-images.githubusercontent.com/44064056/79600112-516f2900-80ef-11ea-8259-0dcc9d991349.png)

**Comment by mylma** [comment]
@ps2 Any idea what might cause this issue?

**Comment by peterstreit** [comment]
Same in German


![IMG_4697](https://user-images.githubusercontent.com/63955360/79694983-58737400-8274-11ea-8a54-31749e0ef7d9.jpg)
![IMG_4696](https://user-images.githubusercontent.com/63955360/79694988-5c06fb00-8274-11ea-92bf-4749bb955136.jpg)
![IMG_4695](https://user-images.githubusercontent.com/63955360/79694991-5d382800-8274-11ea-996d-9a584127a588.PNG)

**Comment by mylma** [comment]
@peterstreit Yes, that Override screen represents the same issue as here. Looks like every language has the same issue on override related views.

Missing translations on Bolus and Settings etc views are different. German localization files are missing those translations and needs to be updated. After update should be fine.

**Comment by mylma** [comment]
@ps2 @mpangburn To solve this issue, should `NSLocalizedString` to be changed to `LocalizedStrings` instead? 

For example here:
https://github.com/LoopKit/LoopKit/blob/6940ab10d258b21e0a33aa5729b1111a8d332d77/LoopKitUI/View%20Controllers/OverrideSelectionViewController.swift#L42
and
https://github.com/LoopKit/LoopKit/blob/6940ab10d258b21e0a33aa5729b1111a8d332d77/LoopKitUI/View%20Controllers/OverrideSelectionViewController.swift#L128

I tested this edit for some of the missing strings and it seems to solve it.

**Comment by mpangburn** [comment]
@mylma Yes, all uses of NSLocalizedString should be LocalizedString in these screens. If you can open a PR to make these changes, it would be much appreciated.

**Comment by mylma** [comment]
@mpangburn Great! I'll submit a PR soon.
