### ISSUE TITLE
ISF change with high BGL

### ISSUE THREAD

**Issue by owen7004** [LoopKit/Loop#1307]
I've looked through list of issues here, and it seems that this was discussed in Dynamic ISF Adjustments #431, also #656 and #703, but they are pretty old posts and now closed, and I'm not clear what came out of the discussion posts.
I've been looking at insulin resistance with high BGL. 
I see the issue of stubborn highs a lot with my teenage son. It is sometimes related to set changes and CGM changes (it is often 2 hours before BGL settles after any needle), sometimes ?hormone surges, sometimes stress related (Monday-itis when school is in session. With covid19 school at home, not currently an issue!), sometimes due to a cold/sick day management. It's hard work getting current presets to work in these situations, and often have to go into open loop. Thinking there are 2 ways to address this with loop. 
1) have ISF be one of the options in preset (override) menu. User could see that they are running high (usually stubborn high) and put in a temp override for a lower ISF (increased resistance, therefore getting loop to work harder to bring the high down) for a set period of time. The downside to this is that we don't know upfront how long it will take to get that high down, so close monitoring would be required to prevent a hypo crash. 
2) a harder fix in terms of programming, but safer, would be to have loop "see" a high BGL (maybe above 11.0, maybe user defines) for more than x minutes (maybe 15-20 minutes), then automatically change ISF by a percentage of user's normal ISF. Then when BGL drops to more normal range (maybe just before normal, around 8.5), ISF goes back to user's normal ISF. Thoughts?

**Comment by Schneiderc008** [comment]
There is a discussion about something similar here https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Scaled.20ISF

**Comment by ps2** [comment]
Loop already does react and increase dosing when BGs rise above expected amounts, vi RC. Any updates to RC would need to have some quantitative analysis done to show the expected change in dosing in various situations.
