### ISSUE TITLE
Carb entry that ends with .5 does is not displayed correctly

### ISSUE THREAD

**Issue by eyalzo** [LoopKit/Loop#1309]
**Describe the bug**
The new "Meal Bolus" screen (v2.2) allows to enter 0.5 or 1.5 carbs etc. Both are displayed incorrectly in that screen and in the main screen too.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Click "Add meal" green button.
2. In the "Add Carb Entry" enter 0.5 in the "Amount Consumed" field.
3. Click "Continue" in the upper right.
4. See "0 g" on the carbs field on the next screen ("Meal Bolus").
5. Happens also when text size is small.
6. Click "Save without Bolusing"
7. On the main screen see that if your carbs might be rounded up or down (can be zero if nothing was entered before).
8. The chart itself does show the 0.5 unit but the title above it does not.
9. If you enter 0.5 again you can see that now it's 0 on the "Meal Bolus" screen again, but the sum is right now on the main screen (if it was 0 before the 2 entries).

**Expected behavior**
1. Allow only integers
or
2. Show the .5 at least in the mid screen (and maybe also in main).

**Screenshots**

Note: similar attempt with 1.5 shows 2 in "Meal Bolus".
![IMG_9816](https://user-images.githubusercontent.com/1243760/79640968-686c5480-819d-11ea-85b1-b39047c521eb.jpg)
![IMG_9817](https://user-images.githubusercontent.com/1243760/79640973-6f936280-819d-11ea-9bd9-15cd289a7811.jpg)
![IMG_9818](https://user-images.githubusercontent.com/1243760/79640981-791cca80-819d-11ea-9328-8c0ecd1e04b9.jpg)

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 13.4.1

**Loop Version**
 - Version Number: 2.2
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

Loop v2.2.0
* gitRevision: N/A
* gitBranch: N/A
* buildDateString: Sat Apr 18 11:47:29 IDT 2020
* xcodeVersion: 11E503a

## FeatureFlags
FeatureFlagConfiguration(sensitivityOverridesEnabled: true)

## DeviceDataManager
* launchDate: 2020-04-18 08:47:57 +0000
* lastError: Optional((date: 2020-04-18 10:08:57 +0000, error: Error enabling notification for authentication: timeout))
* lastBLEDrivenUpdate: 2020-04-18 14:38:49 +0000

**Comment by loyalchallenger** [comment]
Just some thoughts to consider from another user.  Please keep all small entries whenever possible. I use the .5 carb option all the time. It helps me accurately track how much I’m bumping my sugar during workouts. I’m only on .15u per hour basal with a carb ratio of 1:49. I need small doses. Initially, I could not use Loop because my doses were so small. I don’t want Loop to end up back at that place. Thanks!
