### ISSUE TITLE
Confirmation after successful Bolus

### ISSUE THREAD

**Issue by amazaheri** [LoopKit/Loop#131]
Not a bug but more like enhancement I am going to add to code to send push notification and test on our side. On a separate note I noticed that in some cases we get the unsuccessful bolus notification but checking the pump showing bolus went through.

**Comment by ELUTE** [comment]
+1, would love to see this

**Comment by eyim** [comment]
Agreed.  One big problem for us is failed bolus with no nitification and my son doesn't notice until much later. A confirmation that it went through would be great

**Comment by amazaheri** [comment]
I have this already added on my repo, ping me if interested. you can do this with Azure or IFTTT

https://github.com/amazaheri/Loop/blob/master/Loop/Managers/NotificationManager.swift#L86

https://blogs.msdn.microsoft.com/alimaz/2016/09/22/azure-logic-apps-azure-sql-and-loop-better-together-part-ii/

**Comment by amazaheri** [comment]
Also added this to [wiki](https://github.com/LoopKit/Loop/wiki/Remote-Push-notifications-for-Loop-activities-and-alerts)

**Comment by amoskane** [comment]
@amazaheri, sounds like you've got this solved for Nightscout, but there's still interest in having a notification for a successful bolus in Loop. I would +1 that!

**Comment by eszcloud** [comment]
Are you imagining a notification similar to that for Loop failure or low reservoir volume that shows up on the home screen?

If so, as with any notification, a successful bolus confirmation should be something that can be turned off/on easily and not implemented globally. For some this notification would be a feature, but for others it would be a nuisance and one more alert to ignore.

**Comment by amazaheri** [comment]
@eszcloud I agree with making the notifications optional, for us (as parents) getting the notifications remotely is key as my son %99.999 of time ignore the local notifications :)

![unknown](https://cloud.githubusercontent.com/assets/8312775/20505030/632540d6-afff-11e6-984b-3b3e4322de62.jpeg)

**Comment by eszcloud** [comment]
Glad we're on the same page, @amazaheri . :-) I think that notifications is one of those things that is especially different for pwds relative to the people who care for pwds.

Minimizing unnecessary notifications means that I now pay attention to more of the notifications that I receive, so there's hope for him. Maybe there should be a way to enable notifications for a follower separately from the person using Loop...

**Comment by amazaheri** [comment]
I like that idea! btw I just added the successful bolus to my repo and testing it.
![unknown-1](https://cloud.githubusercontent.com/assets/8312775/20505861/b374f342-b004-11e6-8e35-aafcb9b67e70.jpeg)

**Comment by marionbarker** [comment]
This is a very old Issue and I think may have been addressed.  Can this be closed?

**Comment by ps2** [comment]
Yes. Generally, we only want to interrupt the user if there is some action that needs to be taken; that's why Loop alerts on failure only.  The bolus progress indicator is one feature that those users who want to verify delivery can use to verify.
