### ISSUE TITLE
App crashes with duplicate reservoir values

### ISSUE THREAD

**Issue by trixing** [LoopKit/Loop#1312]
**Describe the bug**

I have multiple Rileylink (gnarl actually attached) and at least hit once the assertionFailure in addReservoirValues, https://github.com/LoopKit/Loop/blob/master/Loop/Managers/LoopDataManager.swift#L662

Given that the only possible action is to restart the app I think we can do better, e.g.

[...]
 else if let previousValue = previousValue {
                self.logger.error("doseStore.addReservoirValue, duplicate dose.")
                let error = DoseStore.DoseStoreError.persistenceError(description: "addReservoirValue duplicate", recoverySuggestion: "Wait and Retry")
                completion(.failure(error))
            } else {
self.logger.error("doseStore.addReservoirValue, unknown condition.")
                let error = DoseStore.DoseStoreError.persistenceError(description: "addReservoirValue unknown condition", recoverySuggestion: "Wait and Retry")
                completion(.failure(error))
}

**Attach an Issue Report**
App crashed

**To Reproduce**
Hard to reproduce, happened once.

**Expected behavior**
Not to crash but to recover automatically.

**Phone**
 - Hardware: iPhone SE
 - OS Version: 12.4

**Loop Version**
 - Version Number: 2.2
 - Repo: LoopKit/Loop, 

**CGM**
 - Device: Dexcom Share
 - Manager app: n/a

**Pump**
 - Manufacturer: Medtronic
 - Model: 754
 - Firmware version: 2.3A

**Comment by ps2** [comment]
The `addReservoirValue` method currently appears to check for this state, logs an error and returns the appropriate values.  I assume this has been fixed. If not, please reopen.
