### ISSUE TITLE
Feature Request: different color for "save without bolus"

### ISSUE THREAD

**Issue by aaronneitz** [LoopKit/Loop#1320]
To visually differentiate it from "deliver".  A bit of visual warning.

**Comment by mylma** [comment]
@aaronneitz This was discussed on Zulip few weeks ago. You may want to read more and join the conversation here: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/New.20carb.20entry.20flow/near/194896980

**Comment by aaronneitz** [comment]
Wonderful.  Thank you.
