### ISSUE TITLE
Loop application is not displaying data.

### ISSUE THREAD

**Issue by douglodmill** [LoopKit/Loop#1322]
Rebuilt loop application this evening and I am not having any display of data in the loop app.  Please see screen shots and issues report.
![IMG_3579](https://user-images.githubusercontent.com/12072929/80942195-0ca6eb80-8d99-11ea-9d8d-4344dd145d6a.PNG)
[Loop Report 2020-05-03 225054-0700.txt](https://github.com/LoopKit/Loop/files/4573095/Loop.Report.2020-05-03.225054-0700.txt)
![IMG_3577](https://user-images.githubusercontent.com/12072929/80942305-50015a00-8d99-11ea-9f80-7fcd7e48c834.jpg)
![IMG_3578](https://user-images.githubusercontent.com/12072929/80942389-82ab5280-8d99-11ea-86ea-ddf3c4181dd1.PNG)

**Comment by Kdisimone** [comment]
Open the Health app and give Loop access to read and write insulin, carbs, blood glucose.

**Comment by Kdisimone** [comment]
@douglodmill did you get this resolved? If so, please let us know. I'm going to close this assuming you've resolved the health settings now. Thanks.

**Comment by douglodmill** [comment]
This is closed.  My apologies for not closing.  I reloaded the application and it worked perfectly.
