### ISSUE TITLE
Red loop 

### ISSUE THREAD

**Issue by Blair86** [LoopKit/Loop#1326]
Red loop and I get this message several times a day: Device error - pump did not respond in time

**Comment by Kdisimone** [comment]
This is an intermittent error indicating your rl and pump aren't able to communicate. Please follow the steps in Loopdoc's troubleshooting section, there's a page for troubleshooting red loops. 

If that doesn't help, then more appropriate to post in fb or Zulipchat if you have particular information or questions and can provide additional information for troubleshooting. GitHub issues is for posting feature requests or bug reports in general. Thanks!
