### ISSUE TITLE
Can't Review/Edit/Create Overrides While an Override is Running

### ISSUE THREAD

**Issue by tabula-raza** [LoopKit/Loop#1330]
**Describe the bug**
When an override is running, there is no way to create, review, or edit custom overrides (other than pre-meal correction range). Note: this not about editing the currently running override (which is possible by tapping the override banner from the main screen). This is about creating new overrides, or editing the saved preset overrides, while another override is running.

**To Reproduce**
1. Click on Override
3. Select an Override
4. Attempt to create, review, or edit a custom override without canceling the currently running override 

**Expected behavior**
I should be able to create, edit, or review custom overrides while an override is currently running.

**Loop Version**
 - Version Number: 2.3.0
 - Repo: LoopKit/Loop/tree/automatic-bolus

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros

**Comment by loyalchallenger** [comment]
Thank you for bringing this up!
