### ISSUE TITLE
Yellow ! For cgm data. Never ending. Data is not going to Apple health I think. 

### ISSUE THREAD

**Issue by hayleyml** [LoopKit/Loop#1335]
## LoopVersion
* Version: FreeAPS v2.1
* gitRevision: 411790fef2a013d9177043d226faf2a7b1ce9937
* gitBranch: (HEAD detached at 411790fe)
* sourceRoot: /Users/hayleymiller/.Trash/ivalkou/LoopWorkspace/Loop
* buildDateString: Wed May 27 19:34:24 MDT 2020
* xcodeVersion: 11E608c

## FeatureFlags
FeatureFlagConfiguration(sensitivityOverridesEnabled: true)

## DeviceDataManager
* launchDate: 2020-06-10 02:48:34 +0000
* lastError: nil
* lastBLEDrivenUpdate: 2020-06-10 02:49:09 +0000

## G6CGMManager
latestReading: nil
latestConnection: nil
dataIsFresh: false
providesBLEHeartbeat: false
## ShareClientManager
latestBackfill: nil

observers.count: 0
## BluetoothManager
No peripheral

## OmnipodPumpManager
podComms: ## PodComms
podState: Optional(### PodState
* address: 1F48382A
* activatedAt: Optional(2020-06-08 04:26:15 +0000)
* expiresAt: Optional(2020-06-11 04:24:12 +0000)
* setupUnitsDelivered: Optional(2.8)
* piVersion: 2.9.0
* pmVersion: 2.9.0
* lot: 45334
* tid: 91281
* suspendState: resumed(2020-06-09 18:03:26 +0000)
* unfinalizedBolus: Optional(Bolus: 4.85U 6/9/20, 20:49:05 3 minutes, 13 seconds Certain)
* unfinalizedTempBasal: Optional(TempBasal: 0.5 U/hour 6/9/20, 20:48:19 30 minutes, 0 seconds 0.25 U Certain)
* unfinalizedSuspend: nil
* unfinalizedResume: Optional(Resume: 6/7/20, 22:28:06 Certain)
* finalizedDoses: []
* activeAlerts: [:]
* messageTransportState: MessageTransportState(packetNumber: 28, messageNumber: 0)
* setupProgress: completed
* primeFinishTime: Optional(2020-06-08 04:27:10 +0000)
* configuredAlerts: [OmniKit.AlertSlot.slot7: Pod expiration advisory alarm, OmniKit.AlertSlot.slot2: Shutdown imminent alarm]

fault: nil
)
configuredDevices: ["99BF67D1-9688-DD09-ED0B-5D9CC65F9C73"]
delegate: true

state: ## OmnipodPumpManagerState
* timeZone: GMT-0600 (fixed)
* basalSchedule: BasalSchedule(entries: [OmniKit.BasalScheduleEntry(rate: 0.4, startTime: 0.0), OmniKit.BasalScheduleEntry(rate: 0.7, startTime: 21600.0), OmniKit.BasalScheduleEntry(rate: 0.5, startTime: 36000.0), OmniKit.BasalScheduleEntry(rate: 0.45, startTime: 43200.0), OmniKit.BasalScheduleEntry(rate: 0.4, startTime: 79200.0)])
* expirationReminderDate: Optional(2020-06-11 02:26:15 +0000)
* unstoredDoses: []
* suspendEngageState: stable
* bolusEngageState: stable
* tempBasalEngageState: stable
* lastPumpDataReportDate: Optional(2020-06-10 02:49:21 +0000)
* isPumpDataStale: false
* confirmationBeeps: false
* optionalPodAlarms: false
* pairingAttemptAddress: nil
Optional(### PodState
* address: 1F48382A
* activatedAt: Optional(2020-06-08 04:26:15 +0000)
* expiresAt: Optional(2020-06-11 04:24:12 +0000)
* setupUnitsDelivered: Optional(2.8)
* piVersion: 2.9.0
* pmVersion: 2.9.0
* lot: 45334
* tid: 91281
* suspendState: resumed(2020-06-09 18:03:26 +0000)
* unfinalizedBolus: Optional(Bolus: 4.85U 6/9/20, 20:49:05 3 minutes, 13 seconds Certain)
* unfinalizedTempBasal: Optional(TempBasal: 0.5 U/hour 6/9/20, 20:48:19 30 minutes, 0 seconds 0.25 U Certain)
* unfinalizedSuspend: nil
* unfinalizedResume: Optional(Resume: 6/7/20, 22:28:06 Certain)
* finalizedDoses: []
* activeAlerts: [:]
* messageTransportState: MessageTransportState(packetNumber: 28, messageNumber: 0)
* setupProgress: completed
* primeFinishTime: Optional(2020-06-08 04:27:10 +0000)
* configuredAlerts: [OmniKit.AlertSlot.slot7: Pod expiration advisory alarm, OmniKit.AlertSlot.slot2: Shutdown imminent alarm]

fault: nil
)
Optional(RileyLinkBLEKit.RileyLinkConnectionManagerState(autoConnectIDs: Set(["99BF67D1-9688-DD09-ED0B-5D9CC65F9C73"])))
status: ## PumpManagerStatus
* timeZone: GMT-0600 (fixed)
* device: <<HKDevice: 0x29028c280>, name:Omnipod, manufacturer:Insulet, model:Eros, firmware:2.9.0, software:44.0, localIdentifier:1F48382A>
* pumpBatteryChargeRemaining: nil
* basalDeliveryState: tempBasal(LoopKit.DoseEntry(type: LoopKit.DoseType.tempBasal, startDate: 2020-06-10 02:48:19 +0000, endDate: 2020-06-10 03:18:19 +0000, value: 0.5, unit: LoopKit.DoseUnit.unitsPerHour, deliveredUnits: nil, description: nil, syncIdentifier: nil, scheduledBasalRate: nil))
* bolusState: inProgress(LoopKit.DoseEntry(type: LoopKit.DoseType.bolus, startDate: 2020-06-10 02:49:05 +0000, endDate: 2020-06-10 02:52:19 +0000, value: 4.85, unit: LoopKit.DoseUnit.units, deliveredUnits: nil, description: nil, syncIdentifier: nil, scheduledBasalRate: nil))
podStateObservers.count: 1
statusObservers.count: 1
## RileyLinkPumpManager
rileyLinkConnectionManager: Optional(RileyLinkBLEKit.RileyLinkConnectionManager)
lastTimerTick: 2020-06-10 02:50:10 +0000

## RileyLinkDeviceManager

central: <CBCentralManager: 0x280afd880>

autoConnectIDs: ["99BF67D1-9688-DD09-ED0B-5D9CC65F9C73"]

timerTickEnabled: true

idleListeningState: disabled

## RileyLinkDevice
* name: RileyLink
* lastIdle: 0001-01-01 00:00:00 +0000
* isIdleListeningPending: false
* isTimerTickEnabled: true
* isTimerTickNotifying: true
* radioFirmware: Optional(subg_rfspy 2.2)
* bleFirmware: Optional(ble_rfspy 2.0)
* peripheralManager: <RileyLinkBLEKit.PeripheralManager: 0x280ae90a0>
* sessionQueue.operationCount: 0

**Comment by gigich** [comment]
Same here on 2.2 master
