### ISSUE TITLE
communication error between G6 and Loop

### ISSUE THREAD

**Issue by hartcapl** [LoopKit/Loop#1336]
this is something that happens with some regularity. even though dexcom is working (and the share function is also working) Loop fails to pick up the value for blood glucose.

images and pdf of the loop report below.

[Loop Report 2020-06-18 11:25:27-07:.pdf](https://github.com/LoopKit/Loop/files/4800589/Loop.Report.2020-06-18.11.25.27-07.pdf)

![Image-1-1](https://user-images.githubusercontent.com/2480529/85060310-e4612980-b159-11ea-915a-afb2b0663400.jpg)

![Image-1](https://user-images.githubusercontent.com/2480529/85060331-ed51fb00-b159-11ea-9374-64a4ecfaf28b.jpg)

**Comment by sugarfreecane** [comment]
I am having the same issue with the dev branch

**Comment by StephanieAllene** [comment]
I am having the same exact issue (not dev branch)

**Comment by Hencowitz** [comment]
This seems to happen whenever I force close the app.  My fix has been to
delete the cgm and re-add it, sometimes takes 3 times. If I don’t have time
for that I just add in the dexcom login credentials.  It takes about 2
readings for it to sync back up sometimes.

**Comment by stuzog** [comment]
This could be related to the issues I'm having with [G6/Omnipod](https://github.com/LoopKit/Loop/issues/1361#issuecomment-680928800). AFAIKT it's something to do with Health app not sending data to the Dexcom G6 app.

**Comment by Kdisimone** [comment]
@stuzog Apple's Health app does not write data INTO the Dexcom G6 app. The information flows the opposite direction (if you allow it in app permissions)...Dexcom G6 is allowed to write data INTO Health app.
