### ISSUE TITLE
Issue with bolusing

### ISSUE THREAD

**Issue by katelevesque** [LoopKit/Loop#1347]
Hi, I recently built the loop app for managing my 6 yo daughters T1D. Everything has gone well except for boluses which appear to make her drop significantly to the point that without treatment she would be dangerously low. Yesterday, I did basal and ISF testing with her with an Open Loop and not accepting any temp basal recommendations. Her basal seems spot on at 0.3. I went from the basal test into the ISF test. I went to correct her at 257. Her ISF on the pod has been 125, which would have been a 1.5 unit bolus for a 100 BG target. Loop recommended 0.7 units so I went with Loop’s recommendation given the trouble we’ve been having. She was at 99 with under 0.2 units of the 0.7 unit bolus. With about 0.53 IOB she was in the 50s and I treated her with what ended up being 29g of carbs. I don’t understand what could be happening but this type of drop keeps on happening with our boluses on Loop. Any help to triage this issue would be greatly appreciated. Thank you.
![79CD09A6-914D-4ADC-8BB6-FB0D70BAE5D7](https://user-images.githubusercontent.com/63613354/87243684-0d49a700-c406-11ea-9109-a02acc2d36fe.png)
Here is a link to her issue report yesterday.
[Issue Report](https://drive.google.com/file/d/1EZk9iyCKGaA8ts5XY8TJumEiLMD72jXt/view?usp=drivesdk)

**Comment by elnjensen** [comment]
Hi Kate,

Have you made progress on this?   Asking on Facebook Looped group or [Zulip](https://loop.zulipchat.com) is the best way to get help with settings; GitHub is for issues/bugs with the app itself.

**Comment by katelevesque** [comment]
Thanks for replying. I did post on FB as well. Given how significant her
drops were, I was concerned there was and issue/bug with the app which is
why I reported it as well. At this point, I’ve significantly adjusted her
ISF from what it was prior to Looping to try to compensate. It appears that
is really the only thing to do. If you don’t feel this is at all related to
an issue/bug elsewhere in the app or my build (I included an issue report
so you could see my settings), then I presume you can close out the report
here. Thanks!
