### ISSUE TITLE
Auto Bolus not appearing 

### ISSUE THREAD

**Issue by shahzadpandher** [LoopKit/Loop#1349]
Hi, 
I have been using Loop v2 for a while now and decided to update it to a auto-bolus branch . Everything went fine with the build and loop app is also showing ver 2.2 in issue report 
![9FFB6A2E-7A66-444F-B556-F674A55A5151](https://user-images.githubusercontent.com/8053086/88083422-04b54700-cb51-11ea-9fc1-a6e9a5767170.jpeg)
but I couldn’t find the option to switch to auto-bolus in the settings. What else could have gone wrong? Do I need to uninstall the old Loop before installing this one? Thanks in advance

**Comment by loudestnoise** [comment]
How did you get the Loop software on your Mac? Did you `git clone` and forget to checkout the `automatic-bolus` branch, or did you download the [zip](https://github.com/LoopKit/Loop/archive/automatic-bolus.zip) after selecting `automatic-bolus` from GitHub.com on Loopkit/Loop?

**Comment by shahzadpandher** [comment]
I downloaded the .zip from the github under automatic-bolus.

Shahzadpreet Pandher
+1(647) 554-9791
________________________________

**Comment by loudestnoise** [comment]
🤔 Hmm, that should have worked in that case. It looks like you downloaded an older version though, because I'm running V2.3.0

![image](https://user-images.githubusercontent.com/194853/88094959-fa4b7b00-cb59-11ea-85f6-d4ed742ec3d4.png)

**Comment by shahzadpandher** [comment]
ohh..thanks a lot David, I will rebuild it with the correct version.
