### ISSUE TITLE
UnknownResponse error

### ISSUE THREAD

**Issue by ldunn12** [LoopKit/Loop#135]
I've been getting this occasionally: UnknownResponse(nil, "Sent <a7574973 5d00>")...I don't believe the numbers after Sent are the same.  Any way to troubleshoot this?  It seems to be happening when loop is trying to send a new temp basal to my pump (running this with a 522).

**Comment by channemann** [comment]
Just a hunch here--might that be related to the temp basal percentage / absolute setting? On your pump, go into:

Basal > Basal Setup > Temp Basal Type and make sure it is set to Insulin Rate <U/H>

-----
Chris Hannemann
chris.hannemann@gmail.com

**Comment by ldunn12** [comment]
It is set to u/hr. Looks like I just lost connection again for about 1 hour and got the same error message. 

On Aug 26, 2016, at 9:58 AM, Chris Hannemann <notifications@github.com> wrote:

Just a hunch here--might that be related to the temp basal percentage / absolute setting? On your pump, go into:

Basal > Basal Setup > Temp Basal Type and make sure it is set to Insulin Rate <U/H>

-----
Chris Hannemann
chris.hannemann@gmail.com

**Comment by ldunn12** [comment]
Oops, I don't think I had you on my reply Chris.
It is set to u/hr. Looks like I just lost connection again for about 1 hour
and got the same error message

**Comment by ps2** [comment]
This error can happen just from temporary rf interference, or if the pump isn't close enough to the RL.  If it only happens 'occasionally', as opposed to every time, then that's likely what's going on.

**Comment by dm61** [comment]
I've seen a similar error pop up at a time when the Loop was trying to send a new temp command while the pump was still executing a bolus. I assumed that was the root cause of the error, since the pump won't accept a temp command during bolus.

**Comment by ldunn12** [comment]
I'd say I've seen it more than occasionally.  At first I thought it may have been due to a low battery on the RL, which seemed to help temporarily.  I'll keep playing with distance and see if that helps.

**Comment by ashrind** [comment]
@ldunn12 I haven't been getting an error message, but I have been having pretty constant (every 3-4 hours) connectivity issues that last for 45+ minutes. Let me know if you find something that works for you.

**Comment by ldunn12** [comment]
I just try to reconnect with the RL (tuning, fetching history, sending button pushes, etc).  I think that because I'm using a 522 and it's not always broadcasting like the x23s, that may be contributing to inconsistent RF connectivity.

**Comment by ps2** [comment]
I'm assuming you eventually got your setup working? If so, it might be nice to post what your solution was.
