### ISSUE TITLE
Changing number in carb or bolus input is difficult

### ISSUE THREAD

**Issue by cachrisman** [LoopKit/Loop#1350]
**Describe the bug**
When inputting carbs or insulin for bolus, if I go to the next step and need to go back in order to change the number, when I tap on the number the cursor is at the left end of the number. The keyboard is showing the number pad and there I can't use the keyboard trackpad mode to move the cursor. The only way to move the cursor is to tap and hold the screen and move it to the very edge of the screen. This is often quite difficult and prone to error.

**To Reproduce**
1. Go to add carbs
2. Put in some number
3. Tap on 'continue'
4. Tap on '< Carb Entry' to go back
5. Tap on the 'Amount Consumed' row on the number and try to change it

**Expected behavior**
I would expect the cursor to start at the right end of the number so I can easily tap the backspace button to erase the existing number and enter a new number. Or perhaps the number is selected so I can immediately type a number to overwrite.

**Screenshots**
![1FB976AD-8CBF-453C-89DD-275B34F436F8](https://user-images.githubusercontent.com/6521666/88515867-a377f280-cfec-11ea-9153-37c6841be5cf.jpeg)
**Phone**
 - Hardware: iPhone 11
 - OS Version: iOS 13.5

**Loop Version**
 - Version Number: 2.2
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: OmniPod
 - Model: Eros

**Comment by Milesdyer** [comment]
Yes this happens to me too, I have been meaning to send this in so thank you! We are on Loop (Automatic Bolusing) V2.3.0
iPhone 7, iOS 13.5.1
Dexcom 6, Omnipod
When I go to edit a carb entry the cursor is on the left, to get it to the right to delete the old amount I need to tap it about 10 times before it jumps to the end of the number.

**Comment by Trpl7ca** [comment]
I have also had same problem, if you hold for a while you can select all and correct entry but it would be easier if cursor appeared on the right side.

**Comment by Hencowitz** [comment]
Yes!  It never dawned on me to bring it to light, but it’s very difficult
on an iPhone 5!!  II have to tap and slide to the right with exact
precision to get it to highlight.  Also, several times I end up typing
1029, heaven forbid we don’t notice that in time and hit enter!  Thanks!

**Comment by ps2** [comment]
Yes, this should be made easier for sure. There is a relatively obscure feature that can help you in this situation, though, until we make a fix: force press on the keyboard and you can slide your finger left and right to adjust the position of the cursor.

**Comment by Hencowitz** [comment]
Unfortunately, iPhone 5’s don’t have 3D Touch capability so this does not
work for us.  I like the phone because she’s only 6 and it is the smallest
option for her to have to carry around.

**Comment by cyoung1024** [comment]
@Hencowitz in the absence of 3D Touch, I found double tapping the number helps. Double tapping will select the whole number, and you can edit by typing the new number in directly or backspacing and retyping.

**Comment by ps2** [comment]
Even on non-3d touch phones you should be able to long-press *below* the '0' and enable this cursor positioning trick.  It's a little harder, as there is only a very small amount of real estate between actually tapping the '0', and tapping the modal drag bar.

**Comment by marionbarker** [comment]
I updated to iOS 13.6 tonight and difficulty getting cursor placed on this screen is resolved.

**Comment by Hencowitz** [comment]
Darn it, was hoping that would work.  There is no space between the zero
and the home button.  Doesn’t work the 5 unfortunately :(

**Comment by ffsb42** [comment]
Yes this an issue with the "number input"  field and it applies to multiple places... in particular the same applies to the bolus input window as well and that can be a major issue as clicking the input range will automatically put you on the left of the zero... so instead of typing '2' and **expecting to bolus for '2' units you will end up bolusing for '20' units!**
