### ISSUE TITLE
Empty app display screen after rebuild

### ISSUE THREAD

**Issue by mariamastro** [LoopKit/Loop#1355]
![IMG_4016](https://user-images.githubusercontent.com/55663646/89738277-2d33b100-da2c-11ea-8470-0bed2fba0998.jpg)

[Loop Report 2020-08-09 10_24_38-07_00.txt](https://github.com/LoopKit/Loop/files/5048154/Loop.Report.2020-08-09.10_24_38-07_00.txt)

If you click any of the areas that should have a display, it will open the secondary screen.  Wondering if I disconnected the phone too early from the build?  Thank you so much.

**Comment by Kdisimone** [comment]
You don't have all your health permissions turned on for Loop in the Health app. Please go turn those on and that will resolve the issue.

**Comment by mariamastro** [comment]
They were all on (I checked before posting).  But I never got an "Allow" prompt from Health with the build. I went into Health again, turned them Off, then On; restarted the iPhone and, success.  Thank you so very much.
