### ISSUE TITLE
Crash at AppDelegate, Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc

### ISSUE THREAD

**Issue by yansaid** [LoopKit/Loop#1356]
```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001856c0e90 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001856c0244 mach_msg + 76 (mach_msg.c:103)
2   CoreFoundation                	0x0000000185869af0 __CFRunLoopServiceMachPort + 380 (CFRunLoop.c:2641)
3   CoreFoundation                	0x0000000185863ca4 __CFRunLoopRun + 1228 (CFRunLoop.c:2974)
4   CoreFoundation                	0x00000001858632ac CFRunLoopRunSpecific + 596 (CFRunLoop.c:3242)
5   GraphicsServices              	0x000000019191b820 GSEventRunModal + 164 (GSEvent.c:2259)
6   UIKitCore                     	0x000000018a0fff08 -[UIApplication _run] + 1072 (UIApplication.m:3235)
7   UIKitCore                     	0x000000018a1055e8 UIApplicationMain + 168 (UIApplication.m:4698)
8   Loop                       	        0x0000000102315158 main + 68 (AppDelegate.swift:15)
9   libdyld.dylib                 	0x00000001856eef18 start + 4
```

[The exception code 0xdead10cc indicates that an application has been terminated by the OS because it held on to a file lock or sqlite database lock during suspension. If your application is performing operations on a locked file or sqlite database at suspension time, it must request additional background execution time to complete those operations and relinquish the lock before suspending.](https://developer.apple.com/library/archive/technotes/tn2151/_index.html)

**Comment by dabear** [comment]
I have had this crash several times. Not figured out the root cause yet, but it is related to healthkit and the internal sqlite database in loop. If you delete all loop data(start anew with all settings) by deleting loop from the phone, the database will be deleted as well. That might be a workaround you can try

**Comment by yansaid** [comment]
> I have had this crash several times. Not figured out the root cause yet, but it is related to healthkit and the internal sqlite database in loop. If you delete all loop data(start anew with all settings) by deleting loop from the phone, the database will be deleted as well. That might be a workaround you can try

ok, i will try, it doesn't happen very often

**Comment by ps2** [comment]
A sysdiagnose captured after this happens would be useful. Please reopen if seen again, and reference this ticket in zulip in regards to providing a sysdiagnose.
