### ISSUE TITLE
Issue setting up closed loop

### ISSUE THREAD

**Issue by mcooley5** [LoopKit/Loop#1360]
**Screenshots**
![BB19ACB3-F417-42F9-AE47-FB3C9475C730](https://user-images.githubusercontent.com/69894098/90609604-2db11200-e1b9-11ea-812d-d1c129ecda6c.jpeg)

**Phone**
 - Hardware: [e.g. iPhone XR]
 - OS Version: [e.g. iOS 13.6]

**Loop Version**
 - Version Number: [e.g. 2.2.1]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [ Dexcom G6]
 - Manager app: [e.g. Dexcom App]

**Pump**
 - Manufacturer: [Omnipod]

**Additional context**
Dexcom will not sync up with app. I double checked the transmitter ID and added share account. In addition, when I enter carbohydrate amounts it suggests 0 U? I have carbohydrate ratios set. Will attach screen shot.
![12781F4E-923B-41C0-81DF-789C24475A27](https://user-images.githubusercontent.com/69894098/90609825-7668cb00-e1b9-11ea-9008-81e38401bbcd.png)

**Comment by elnjensen** [comment]
The lack of a bolus suggestion with carbs is just a side effect of missing glucose data - if there’s no glucose info, it won’t suggest a bolus.  Once the BG issue is fixed, that will correct itself. 

Double-check your transmitter ID again, and make sure the Dexcom app is running and receiving data.

**Comment by mcooley5** [comment]
Done & done. Not sure what the issue is. Interesting that it shows my glucose in settings but not in the home screen. 
![B7514309-2109-4AE3-960A-B8B5B5B4F987](https://user-images.githubusercontent.com/69894098/90677276-f7ec4780-e211-11ea-9d72-92b67c684484.png)

**Comment by skirby99** [comment]
G6 transmitter should start with an 8, not a 6

**Comment by mcooley5** [comment]
Oops must of messed up when I deleted it and re added it. That still doesn’t seem to be changing things though. 
![FF1502C1-C3E5-4152-B94D-041EAFC8F01C](https://user-images.githubusercontent.com/69894098/90679985-e9079400-e215-11ea-94c0-15d7a5c40e86.png)
![36A933CD-70D5-40E9-99FA-0CACB1804087](https://user-images.githubusercontent.com/69894098/90679990-eb69ee00-e215-11ea-8931-0deeec09c9e2.png)
