### ISSUE TITLE
SSO_authenticateaccountnot found error 

### ISSUE THREAD

**Issue by johntowers369** [LoopKit/Loop#1361]
Using Omnipod and Dexcom G6. Connected a new pod last night. Everything seemed normal except now I have 10 hours red circle. No pod data on the app. Tried restarting this morning, opening closing app, reset Riley link to no avail. I can hear the pod working, but seems like it’s not communicating. Thanks. 
![D3CA03C0-3CDB-4D52-A735-21CCA9CBA3E8](https://user-images.githubusercontent.com/60803465/90777412-004f8b80-e2c1-11ea-8219-a1ea60b14fe0.png)

**Comment by stuzog** [comment]
I'm having somewhat similar issues with G6/Omnipod/Loop. Yesterday looping ceased to work after a Dexcom tech support rep "fixed" the issue of Clarity apparently not linking to my Dexcom account by deleting all but one of the four (!) Dexcom accounts that were previously linked to my Dexcom account from previous iPhone users. 

As far as I can tell, Health App is not sending data to the G6 app, apart from a brief 3-hour burst very early this morning. Another Dexcom tech support person claimed it was the recent update to iOS 13.6.1, which seems unlikely as everything was working before Dexcom applied its "fix".

The issue could be related to [Excessive profile syncing to Nightscout](https://github.com/LoopKit/Loop/issues/1359). Whatever, right now I'm hooping regarding Looping and forced to do emergency MDI.

**Comment by Kdisimone** [comment]
@stuzog Apple's Health app does not write data INTO the Dexcom G6 app. The information flows the opposite direction (if you allow it in app permissions)...Dexcom G6 is allowed to write data INTO Health app. And dexcom's data INTO Health app will always be on a three hour delay before it appears in Health.
