### ISSUE TITLE
Omnipod keeps failing during priming

### ISSUE THREAD

**Issue by jparuolo** [LoopKit/Loop#1365]
**Describe the bug**
I have lost 5 pods due to them ‘screaming’ toward the end of priming. I initially thought it was a problem with my Riley link so tried with a new one. Same problem. I have only been able to start one session using my omnipod PDM but none using loop. I rebuilt loop now version 2.0, I updated iOS to 13.6.1, and still having same problem. The error message was internal pod fault 092. When rebuilding loop, I did not edit the code at all or make any customizations as I did in the past. 
Any ideas of what is going wrong? 

Using a dexcom g6 via the iphone app, have an iphone XS
Using the newer omnipod pumps mailed out to me i.n last 4 months.  

I even tried the stop using omnipod approach, and the. Added my omnipod back after rebuilding loop. 

I will attach an error report below: 

Thanks very much for your time. - Joe

Loading...

Use the Share button above save this diagnostic report to aid investigating your problem. Issues can be filed at https://github.com/LoopKit/Loop/issues.

Generated: 2020-09-01 02:26:57 +0000

Loop v2.0
* gitRevision: N/A
* gitBranch: N/A
* sourceRoot: /Users/sharmaineparuolo/Downloads/Loop-master
* buildDateString: Fri Mar 20 19:27:41 EDT 2020
* xcodeVersion: 11B500

## DeviceDataManager
* launchDate: 2020-09-01 02:26:21 +0000
* lastError: nil
* lastBLEDrivenUpdate: 0001-01-01 00:00:00 +0000

## G6CGMManager
latestReading: nil
latestConnection: nil
dataIsFresh: false
providesBLEHeartbeat: false
## ShareClientManager
latestBackfill: nil

observers.count: 0
## PeripheralManager
peripheral: <CBPeripheral: 0x2813b9040, identifier = 72D2971A-3FB5-B23B-E173-3296689C4FB0, name = Dexcom09, state = connecting>
needsConfiguration: false
## OmnipodPumpManager
podComms: ## PodComms
podState: nil
configuredDevices: []
delegate: true

state: ## OmnipodPumpManagerState
* timeZone: GMT-0400 (fixed)
* basalSchedule: BasalSchedule(entries: [OmniKit.BasalScheduleEntry(rate: 0.7, startTime: 0.0), OmniKit.BasalScheduleEntry(rate: 0.9, startTime: 25200.0), OmniKit.BasalScheduleEntry(rate: 0.9, startTime: 28800.0), OmniKit.BasalScheduleEntry(rate: 1.3, startTime: 39600.0), OmniKit.BasalScheduleEntry(rate: 1.65, startTime: 46800.0), OmniKit.BasalScheduleEntry(rate: 1.45, startTime: 54000.0), OmniKit.BasalScheduleEntry(rate: 1.65, startTime: 63000.0), OmniKit.BasalScheduleEntry(rate: 1.8, startTime: 73800.0), OmniKit.BasalScheduleEntry(rate: 1.3, startTime: 82800.0), OmniKit.BasalScheduleEntry(rate: 1.3, startTime: 84600.0)])
* expirationReminderDate: nil
* unstoredDoses: []
* suspendEngageState: stable
* bolusEngageState: stable
* tempBasalEngageState: stable
* lastPumpDataReportDate: nil
* isPumpDataStale: true
* confirmationBeeps: false
nil
Optional(RileyLinkBLEKit.RileyLinkConnectionManagerState(autoConnectIDs: Set(["6755D538-D4E0-9C82-5051-D056F8699413"])))

### MessageLog

status: ## PumpManagerStatus
* timeZone: GMT-0400 (fixed)
* device: <<HKDevice: 0x280191720>, name:Omnipod, manufacturer:Insulet, model:Eros, software:44.0>
* pumpBatteryChargeRemaining: nil
* basalDeliveryState: suspended(0001-01-01 00:00:00 +0000)
* bolusState: none
podStateObservers.count: 1
statusObservers.count: 1
## RileyLinkPumpManager
rileyLinkConnectionManager: Optional(RileyLinkBLEKit.RileyLinkConnectionManager)
lastTimerTick: 0001-01-01 00:00:00 +0000

## RileyLinkDeviceManager

central: <CBCentralManager: 0x2809b4770>

autoConnectIDs: ["6755D538-D4E0-9C82-5051-D056F8699413"]

timerTickEnabled: true

idleListeningState: disabled

## RileyLinkDevice
* name: RileyLink
* lastIdle: 0001-01-01 00:00:00 +0000
* isIdleListeningPending: false
* isTimerTickEnabled: true
* isTimerTickNotifying: true
* radioFirmware: Optional(subg_rfspy 2.2)
* bleFirmware: Optional(ble_rfspy 2.0)
* peripheralManager: <RileyLinkBLEKit.PeripheralManager: 0x2809ba990>
* sessionQueue.operationCount: 0

## WatchDataManager
lastSentSettings: nil
lastComplicationContext: nil
<WCSession: 0x2813bf3e0, hasDelegate: YES, activationState: 2>
* hasContentPending: false
* isComplicationEnabled: false
* isPaired: false
* isReachable: false
* isWatchAppInstalled: false
* outstandingFileTransfers: []
* outstandingUserInfoTransfers: []
* receivedApplicationContext: [:]
* remainingComplicationUserInfoTransfers: 0
* complicationUserInfoTransferInterval: 93.0 min
* watchDirectoryURL: nil

## StatusExtensionDataManager
appGroupName: group.com.QKYT772X2V.loopkit.LoopGroup
statusExtensionContext: Optional(["version": 5, "netBasal": ["start": 2020-09-01 02:24:35 +0000, "percentage": 0.0, "rate": 0.0], "lastLoopCompleted": 2020-08-23 22:39:31 +0000, "reservoirCapacity": 200.0, "pumpManagerHUDViewsContext": ["pumpManagerHUDViewsRawValue": ["managerIdentifier": Omnipod, "hudProviderViews": {
    alerts =     (
    );
    lifetime = 259200;
    podActivatedAt = "2020-09-01 02:23:40 +0000";
    validTime = "2020-09-01 02:24:42 +0000";
}]]])

## LoopDataManager
settings: LoopCore.LoopSettings(dosingEnabled: true, dynamicCarbAbsorptionEnabled: true, glucoseTargetRangeSchedule: Optional(LoopKit.GlucoseRangeSchedule(override: nil, rangeSchedule: ["items": [["value": [90.0, 100.0], "startTime": 0.0], ["startTime": 28800.0, "value": [85.0, 99.0]], ["value": [95.0, 115.0], "startTime": 79200.0]], "unit": "mg/dL", "timeZone": -14400])), preMealTargetRange: Optional(LoopKit.DoubleRange(minValue: 70.0, maxValue: 75.0)), legacyWorkoutTargetRange: nil, overridePresets: [], scheduleOverride: nil, maximumBasalRatePerHour: Optional(20.0), maximumBolus: Optional(15.0), suspendThreshold: Optional(LoopCore.GlucoseThreshold(value: 90.0, unit: mg/dL)), retrospectiveCorrectionEnabled: true, retrospectiveCorrectionGroupingInterval: 1800.0, recencyInterval: 900.0, batteryReplacementDetectionThreshold: 0.5, defaultWatchCarbPickerValue: 15, defaultWatchBolusPickerValue: 1.0, minimumChartWidthPerHour: 50.0, statusChartMinimumHistoryDisplay: 3600.0, deviceToken: Optional(32 bytes))
insulinCounteractionEffects: [
* GlucoseEffectVelocity(start, end, mg/dL/min)

]
insulinEffect: [
* GlucoseEffect(start, mg/dL)

]
carbEffect: [
* GlucoseEffect(start, mg/dL)

]
predictedGlucose: [
* PredictedGlucoseValue(start, mg/dL)
* 2020-09-01 02:19:33 +0000, 168.0
* 2020-09-01 08:19:33 +0000, 168.0

]
retrospectiveGlucoseDiscrepancies: [
* GlucoseEffect(start, mg/dL)

]
retrospectiveGlucoseDiscrepanciesSummed: [
* GlucoseChange(start, end, mg/dL)

]
glucoseMomentumEffect: []
retrospectiveGlucoseEffect: []
recommendedTempBasal: Optional((recommendation: Loop.TempBasalRecommendation(unitsPerHour: 10.4, duration: 1800.0), date: 2020-09-01 02:26:57 +0000))
recommendedBolus: Optional((recommendation: Loop.BolusRecommendation(amount: 4.3, pendingInsulin: 0.0, notice: nil), date: 2020-09-01 02:26:57 +0000))
lastBolus: nil
lastLoopCompleted: Optional(2020-08-23 22:39:31 +0000)
basalDeliveryState: Optional(LoopKit.PumpManagerStatus.BasalDeliveryState.suspended(0001-01-01 00:00:00 +0000))
carbsOnBoard: nil
error: nil

cacheStore: ## PersistenceController
* isReadOnly: false
* directoryURL: file:///private/var/mobile/Containers/Shared/AppGroup/610D3187-E5C2-4357-AD20-0956200F4C30/com.loopkit.LoopKit/
* persistenceStoreCoordinator: Optional(<NSPersistentStoreCoordinator: 0x283788880>)

## GlucoseStore

* latestGlucoseValue: Optional(LoopKit.StoredGlucoseSample(sampleUUID: 1EADC2F5-ACB2-4964-A274-33DF1D8FE82C, syncIdentifier: "1598926773", syncVersion: 1, startDate: 2020-09-01 02:19:33 +0000, quantity: 168 mg/dL, isDisplayOnly: false, provenanceIdentifier: ""))
* managedDataInterval: 10800.0
* cacheLength: 86400.0
* momentumDataInterval: 900.0
* observerQuery: Optional(<HKObserverQuery E9892D QoS=Default state=active>)
* observationStart: 2020-08-31 02:26:21 +0000
* observationEnabled: true
* authorizationRequired: false

### cachedGlucoseSamples
StoredGlucoseSample(sampleUUID: 3CE8066B-0DF5-4522-9A0B-55265FE5CC12, syncIdentifier: "1598925272", syncVersion: 1, startDate: 2020-09-01 01:54:32 +0000, quantity: 120 mg/dL, isDisplayOnly: false, provenanceIdentifier: "")
StoredGlucoseSample(sampleUUID: 8676EC3A-30C6-4D2F-A7D4-1E8CF1AFE6F8, syncIdentifier: "1598925573", syncVersion: 1, startDate: 2020-09-01 01:59:33 +0000, quantity: 135 mg/dL, isDisplayOnly: false, provenanceIdentifier: "")
StoredGlucoseSample(sampleUUID: 109239B8-3157-4FED-A48C-7C4F730D159B, syncIdentifier: "1598925873", syncVersion: 1, startDate: 2020-09-01 02:04:33 +0000, quantity: 148 mg/dL, isDisplayOnly: false, provenanceIdentifier: "")
StoredGlucoseSample(sampleUUID: 64783B73-191C-4BAB-8D1E-B5542464E755, syncIdentifier: "1598926173", syncVersion: 1, startDate: 2020-09-01 02:09:33 +0000, quantity: 158 mg/dL, isDisplayOnly: false, provenanceIdentifier: "")
StoredGlucoseSample(sampleUUID: DEDC5C7B-6DE3-490B-BEDD-8CDE702E7E46, syncIdentifier: "1598926473", syncVersion: 1, startDate: 2020-09-01 02:14:33 +0000, quantity: 170 mg/dL, isDisplayOnly: false, provenanceIdentifier: "")
StoredGlucoseSample(sampleUUID: 1EADC2F5-ACB2-4964-A274-33DF1D8FE82C, syncIdentifier: "1598926773", syncVersion: 1, startDate: 2020-09-01 02:19:33 +0000, quantity: 168 mg/dL, isDisplayOnly: false, provenanceIdentifier: "")

## CarbStore

* carbRatioSchedule: ["items": [["startTime": 0.0, "value": 7.0], ["startTime": 21600.0, "value": 6.0], ["startTime": 66600.0, "value": 6.0]], "unit": "g", "timeZone": -14400]
* carbRatioScheduleApplyingOverrideHistory: ["items": [["startTime": 0.0, "value": 7.0], ["startTime": 21600.0, "value": 6.0], ["startTime": 66600.0, "value": 6.0]], "unit": "g", "timeZone": -14400]
* defaultAbsorptionTimes: (fast: 7200.0, medium: 10800.0, slow: 14400.0)
* insulinSensitivitySchedule: ["unit": "mg/dL", "timeZone": -14400, "items": [["startTime": 0.0, "value": 17.0]]]
* insulinSensitivityScheduleApplyingOverrideHistory: ["unit": "mg/dL", "timeZone": -14400, "items": [["startTime": 0.0, "value": 17.0]]]
* overrideHistory: TemporaryScheduleOverrideHistory(recentEvents: [], taintedEventLog: [])
* carbSensitivitySchedule: ["timeZone": -14400, "items": [["value": 2.4285714285714284, "startTime": 0.0], ["value": 2.8333333333333335, "startTime": 21600.0], ["value": 2.8333333333333335, "startTime": 66600.0]], "unit": "mg/g·dL"]
* delay: 600.0
* delta: 300.0
* absorptionTimeOverrun: 1.5
* carbAbsorptionModel: Nonlinear
* Carb absorption model settings: CarbModelSettings(absorptionModel: LoopKit.PiecewiseLinearAbsorption(percentEndOfRise: 0.15, percentStartOfFall: 0.5), initialAbsorptionTimeOverrun: 1.5, adaptiveAbsorptionRateEnabled: false, adaptiveRateStandbyIntervalFraction: 0.2)
* observerQuery: Optional(<HKObserverQuery FCCD2E QoS=Default state=active>)
* observationStart: 2020-08-31 18:26:21 +0000
* observationEnabled: true
* authorizationRequired: false

cachedCarbEntries: [
	StoredCarbEntry(sampleUUID, syncIdentifier, syncVersion, startDate, quantity, foodType, absorptionTime, createdByCurrentApp, externalID, isUploaded)
	, FABC9E3C-28F8-4341-BAD5-8BFD6560D46F, EF32448D-3678-4BD3-8668-2CF258A5220D, 1, 2020-08-23 13:26:35 +0000, 40 g, , 10800.0, true, , false
	, 19335A07-B3E5-43FD-AFAF-6B7D241BCFF7, B81C4705-751A-4074-8453-034C528B2782, 1, 2020-08-23 16:34:34 +0000, 30 g, , 10800.0, true, , false
	, 8262CA93-5648-46E3-B4EF-147AA6985633, 5697242B-8BB1-4646-9299-DF4E00A20242, 1, 2020-08-23 19:13:31 +0000, 19 g, , 10800.0, true, , false
	, 6676A972-0CD7-45AD-88E7-AAD78F7F9754, 1E33E327-5171-45A0-A692-FAC1DE15B593, 1, 2020-08-23 19:34:32 +0000, 20 g, , 10800.0, true, , false
]

deletedCarbEntries: [
	DeletedCarbEntry(externalID, isUploaded)
]

## DoseStore

* insulinModel: Optional(fiasp(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3300.0))
* basalProfile: ["timeZone": -14400, "items": [["value": 0.7, "startTime": 0.0], ["startTime": 25200.0, "value": 0.9], ["value": 0.9, "startTime": 28800.0], ["startTime": 39600.0, "value": 1.3], ["value": 1.65, "startTime": 46800.0], ["value": 1.45, "startTime": 54000.0], ["value": 1.65, "startTime": 63000.0], ["startTime": 73800.0, "value": 1.8], ["startTime": 82800.0, "value": 1.3], ["startTime": 84600.0, "value": 1.3]]]
* basalProfileApplyingOverrideHistory ["items": [["value": 0.7, "startTime": 0.0], ["value": 0.9, "startTime": 25200.0], ["value": 0.9, "startTime": 28800.0], ["value": 1.3, "startTime": 39600.0], ["value": 1.65, "startTime": 46800.0], ["value": 1.45, "startTime": 54000.0], ["startTime": 63000.0, "value": 1.65], ["startTime": 73800.0, "value": 1.8], ["startTime": 82800.0, "value": 1.3], ["startTime": 84600.0, "value": 1.3]], "timeZone": -14400]
* insulinSensitivitySchedule: ["timeZone": -14400, "items": [["value": 17.0, "startTime": 0.0]], "unit": "mg/dL"]
* insulinSensitivityScheduleApplyingOverrideHistory ["timeZone": -14400, "items": [["value": 17.0, "startTime": 0.0]], "unit": "mg/dL"]
* overrideHistory: TemporaryScheduleOverrideHistory(recentEvents: [], taintedEventLog: [])
* egpSchedule: ["unit": "mg·IU/dL·hr", "timeZone": -14400, "items": [["value": 11.899999999999999, "startTime": 0.0], ["startTime": 25200.0, "value": 15.3], ["value": 15.3, "startTime": 28800.0], ["startTime": 39600.0, "value": 22.1], ["value": 28.049999999999997, "startTime": 46800.0], ["value": 24.65, "startTime": 54000.0], ["startTime": 63000.0, "value": 28.049999999999997], ["startTime": 73800.0, "value": 30.6], ["startTime": 82800.0, "value": 22.1], ["startTime": 84600.0, "value": 22.1]]]
* areReservoirValuesValid: false
* isUploadRequestPending: false
* lastPumpEventsReconciliation: Optional(2020-09-01 02:24:42 +0000)
* lastStoredReservoirValue: nil
* pumpEventQueryAfterDate: 2020-08-31 02:26:21 +0000
* totalDeliveryCache: nil
* lastRecordedPrimeEventDate: Optional(0001-01-01 00:00:00 +0000)
* pumpRecordsBasalProfileStartEvents: false
* device: Optional(<<HKDevice: 0x2801bf4d0>, name:Omnipod, manufacturer:Insulet, model:Eros, software:44.0>)

* insulinOnBoard: fetchError(description: "No values found", recoverySuggestion: Optional("Ensure insulin data exists for the specified date"))

### getReservoirValues

* Reservoir(startDate, unitVolume)

### InsulinDeliveryStore
* cacheLength: 86400.0
* observerQuery: Optional(<HKObserverQuery 6C85B6 QoS=Default state=active>)
* observationStart: 2020-08-31 02:26:21 +0000
* observationEnabled: true
* authorizationRequired: false
* lastBasalEndDate: Optional(0001-01-01 00:00:00 +0000)

**Comment by itsmojo** [comment]
An 092 fault can occur anytime after the initial prime bolus if things don't look right with the pump SMA wires. I'd guess that you probably have a bad box of pods if you repeatedly are this getting this fault soon after priming. Perhaps this is something that you can replacement pods from Insulet for if this fault is having early enough, although it might be hard to talk your way through this w/o having to admit that you weren't using a PDM. It might be that if they look up the lot # and they already have been having reports of 092 failures from this lot, it might not make a difference to them that you aren't using a PDM.

If this fault happens again and you are able to run a Pod Settings->Read Pulse Log, please run this command on the screaming pod to capture the most recent pulse log entries and then *attach* the resulting Loop Report to this issue (don't try to copy and paste Loop Reports as it's too long and you end up leaving out useful information). The other alternative is to run with an updated Loop built using a Workspace build using my private rileylink_ios update-bundle branch found here: https://github.com/itsmojo/rileylink_ios/tree/update-bundle which will automatically read the latest pulse log entries when deactivating any faulted pod. You can read more about this private branch here: https://github.com/itsmojo/rileylink_ios/wiki.

**Comment by jparuolo** [comment]
Thanks very much for your reply, I will try a pod from a different lot. They just sent me some replacements so I’ll try those. As a precaution I am deleting and rebuilding loop from scratch and rechecking everything is up to date like x code, etc. Now have a new RL too so will be using that to see. I tried 1 pod from old Lot and same result with rebuilt (but not deleted and rebuilt) loop and new RL, so hope that its just a bad lot of pods. Will let you all know. 

Just to clarify this problem always happens toward the end of priming and unlike others I have seen I get zero time with the pod functioning normally.

**Comment by Hencowitz** [comment]
I have been taking a safety pin and breaking the old pod using the little
green dot underneath the adhesive, before I think a new pod. The one time I
didn’t do it, I had what you experienced.  I didn’t learn this from
anywhere, it’s just some thing I thought to do a while ago so I’m not sure
if it’s a coincidence or if it’s actually helping.
