### ISSUE TITLE
Auto-Bolus adds in equivalent high temp basals, incorrectly calculates IOB

### ISSUE THREAD

**Issue by mattgrossbach** [LoopKit/Loop#1366]
**Describe the bug**
Every once in a while, Loop will say I have super high IOB all of a sudden. I check my Insulin Delivery screen and it shows a very high temp basal at the exact same time as each small recent auto-bolus. When I do the math, it appears that the temp basal shown is equivalent to the temp basal required to deliver the same auto-bolus over a 5 minute period - so it has effectively double counted several recent boluses. If I kill the app and re-open it the temp basals disappear, but they re-appear after the next loop. This doesn't cause unnecessary basal suspension fortunately (it seems to calculate IOB correctly for purposes of making a bolus decision, then maybe add the temp basals in afterwards), but it is very confusing. I've noticed this seems to only happen when my pod is nearly empty.

**Attach an Issue Report**
Forgot to get the issue report last time this happened, I'll get one next time.

**To Reproduce**
This only happens occasionally so I can't guarantee it will always be reproducible.
1. Using Omnipod, run the pod down to below 10U.
2. Use Loop as normal and watch the Insulin Delivery screen for the high temp basals.

**Expected behavior**
I expected to only see the auto-boluses in Insulin Delivery and not any high temp basals, plus I expect IOB to be calculated using the boluses, not a high temp basal.

**Screenshots**
![image](https://user-images.githubusercontent.com/61716323/91909024-74ebd800-ec7a-11ea-9799-59ca740be5a2.png)
![image](https://user-images.githubusercontent.com/61716323/91909038-7ddca980-ec7a-11ea-8b6c-e4c64d2a030f.png)
![image](https://user-images.githubusercontent.com/61716323/91909085-94830080-ec7a-11ea-89ca-f73663575c7c.png)

**Phone**
 - Hardware: iPhone XR
 - OS Version: 13.6.1

**Loop Version**
 - Version Number: Automatic Bolusing V2.3.0
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet - Omnipod
 - Model: Eros

**Additional context**
One other strange observation is that some of these temp basals are way above my set max basal rate of 4.0 U/hr.

**Comment by Kdisimone** [comment]
This is already a known issue with an open Issue in GitHub being tracked and discussed.



https://loop.zulipchat.com/#narrow/stream/144111-general/topic/Open.20Loop.20Display
