### ISSUE TITLE
Loop widget not able to load in iOS and WatchOS

### ISSUE THREAD

**Issue by msinkovich** [LoopKit/Loop#1378]
Updated  to iOS 14 and WatchOS 7 without any issues but as of this morning the widget says unable to load and the watch complication won't render.  Loop app is working fine.  

Restarted both watch and phone.

**Comment by msinkovich** [comment]
Here is the issue report

https://www.dropbox.com/s/gz9jrbknkxvxhi5/Loop%20Report%202020-09-20%20111857-0500.md?dl=0

**Comment by michaelmorris101** [comment]
Same thing just happened to me. Using latest ios 14 and WatchOS 7. Happened suddenly, without me making any changes or new installations.

**Comment by msinkovich** [comment]
i reinstalled and the widget was fine.  removed the complication from watch
over night and readded the next day and that brought the watch back

**Comment by michaelmorris101** [comment]
Thanks very much for this.
