### ISSUE TITLE
Grey loop - "operation couldn't be completed" 

### ISSUE THREAD

**Issue by BreanaH** [LoopKit/Loop#1379]
My loop app has had a grey loop for a few days now and won't connect to my CGM even though I'm receiving data through my Dexcom app. When I click on the grey loop it says the operation couldn't be completed. I've tried to delete and reconnect my CGM, and also disconnecting my Riley link. Loop is still letting me bolus but it's not pulling any cgm data so It won't give recommendations or automatic basal every hour. I'm not sure if it's a connection problem or if its as serious as having to go in and update or rebuild the app. 
![IMG_2808](https://user-images.githubusercontent.com/59181550/93724040-9ee93980-fb58-11ea-836c-0e9c32715e8e.png)

**Comment by BreanaH** [comment]
This is a screenshot from the issue report. 
![IMG_2816](https://user-images.githubusercontent.com/59181550/93724104-14550a00-fb59-11ea-8d6f-197fa1acc3cd.png)

**Comment by Kdisimone** [comment]
Please check looped group or recently closed issues here. This has been addressed in the pinned announcements in fb looped group

**Comment by drrogergoddard** [comment]
P
