### ISSUE TITLE
Incorrect display in active carbs when sensor offline (changeover)

### ISSUE THREAD

**Issue by KheldarUK** [LoopKit/Loop#1384]
I think this is more of a UI issue than an actual problem, but submitting it anyways

Had my lunch, shortly after my sensor expired and I had a few hours off (with a snack in the middle, started my new sensor and then and my evening meal)

I’ve noticed looking at the graph that the lunch carbs never seemed to go away - they persisted in a horizontal line.

The carbs I had in the afternoon “decayed” as expected.
![285DF822-2F62-4607-9010-CAFCF1CF216B](https://user-images.githubusercontent.com/29229592/94063529-25fc1300-fde0-11ea-9e73-6681be111526.png)
![BDCB50E0-5E23-493A-8920-2F6EEF05D09A](https://user-images.githubusercontent.com/29229592/94063540-28f70380-fde0-11ea-9273-27fd3e51d0e2.png)

You can see that almost as soon as my new sensor fired up, Loop appears to have worked it all out and sharply dropped the active carbs so I’m not terribly concerned, but the UI does not behave as I’d expect

I can’t work out how to upload my Loop log from mobile but I can do it from a PC if needed?

Thanks ❤️

**Comment by marionbarker** [comment]
I think this is still a problem.

**Comment by marionbarker** [comment]
Bump
