### ISSUE TITLE
Carb entries not queued for upload to Nightscout when Internet access is not avaiable

### ISSUE THREAD

**Issue by Nightfoxy** [LoopKit/Loop#1385]
**Describe the bug**
When internet access is not available, Loop queues up bolus and temp basal actions and uploads those to Nightscout when Internet access returns. Carb entries entered during this same period are never uploaded to Nightscout.

**Attach an Issue Report**
N/A

**To Reproduce**
1. Disable access to the internet
2. Enter at least 1 carb entry
3. restore internet access and wait at least 1 loop (5 minutes)
4. Carb entry is not in nightscout.

**Expected behavior**
Once Loop can reach Nightscout, it should upload carb entries as well as bolus and temp basal data. Carb entry behavior should mimic bolus/basal behavior.

**Screenshots**

**Phone**
 - Hardware: iPhone 7
 - OS Version: iOS 13.6.7

**Loop Version**
 - Version Number:
 - Repo: FreeAPS and Loop/Dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: [Omnipod]

**Additional context**
Replicated on Latest Dev (as of 9/15/20) and FreeAPS (as of 9/20/20)

**Comment by Nightfoxy** [comment]
This is still a problem and can be quite alarming for parents who see an insulin entry without a carb entry. That's when this usually comes up.

**Comment by Nightfoxy** [comment]
![image](https://user-images.githubusercontent.com/46848705/174399908-639d8c93-f211-4dad-80ba-5388f0af6b36.png)

**Comment by Nightfoxy** [comment]
@ps2 Just bumping this and tagging you to make sure this is on the roadmap for 3.0. It is still an issue. It happened again today. Luckily the loop pill shows an increase in COB, so I know carbs are entered.

**Comment by ps2** [comment]
It looks like the issues is that while they *are* queued, and will eventually upload, they will not do so until a CarbStore event triggers the upload, like editing carbs, or adding more carbs. I will change this so that any pending carbs are uploaded with each loop (both failed and successful loops).

**Comment by ps2** [comment]
Should be fixed with #1838
