### ISSUE TITLE
Carthage workaround no longer works with Xcode 12.0.1

### ISSUE THREAD

**Issue by jebeck** [LoopKit/Loop#1389]
The workaround from 48ae356156051a426a18e7b190ca7aae714edc93 no longer works with Xcode 12.0.1 that was released today. It resulted in the [Carthage #3019 error](https://github.com/Carthage/Carthage/issues/3019).

I have verified by manually download Xcode 12.0 via Apple Developer and building just by running that out of my Downloads folder, and it worked!

**Comment by filippovdev** [comment]
Same issue, perfectly work with Xcode 12.0.0 and doesn't work with 12.0.1.

**Comment by jebeck** [comment]
@filippovdev there's already a fix on dev in 9dea8a8c9ca0c95c0ab99d666d7b952abd86b75c courtesy of Pete :)
