### ISSUE TITLE
Don’t know how to troubleshoot

### ISSUE THREAD

**Issue by mianla8** [LoopKit/Loop#1399]
I’ve been using loop for well over a year and have never had this current issue. My loop app will not communicate with my omnipod pump through my Riley link. 

I tried a test command and this was the result: 

Testing Commands…

commsError(error: RileyLinkBLEKit.RileyLinkDeviceError.peripheralManagerError(RileyLinkBLEKit.PeripheralManagerError.timeout))

When I try to read pump status it says:

Read Pod Status…

peripheralManagerError(RileyLinkBLEKit.PeripheralManagerError.timeout)

I tried searching these codes online and can’t find anything unfortunately.

**Comment by Kdisimone** [comment]
Here you go. Troubleshooting page 👍

https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/

**Comment by mianla8** [comment]
I did try all the items on that page too but could not resolve.

**Comment by loudestnoise** [comment]
@mianla8 Try turning your RL off and back on again. When I get that sort of persistent error when Testing Commands that normally does the trick.

**Comment by mianla8** [comment]
It was the page you quoted before closing my article that referred me to
post it here.

**Comment by mianla8** [comment]
I have tried turning it off and on several times for various periods of
time. I’ve also tried charging it more and trying to connect while plugged
in.

**Comment by loudestnoise** [comment]
What about turning Bluetooth off and back on? Do it in Settings - Bluetooth and tap the toggle off and back on.

**Comment by mianla8** [comment]
I did try turning the Bluetooth on my phone off and on for various amounts of time as well. Including turning off my phone for various amounts of time as well as closing the app several times too. I’ve been trying various combinations of this stuff for 9 hours and can’t deliver insulin from my day old omnipod. 

I’m not sure I understand why my article was closed either. I’m not a programmer and just want my pod to communicate with the app to deliver insulin again. I have an iPhone XS With up to date iOS. (14.0.1)

**Comment by loudestnoise** [comment]
If that's the case, I would wonder if something is wrong with your RL. As to why @Kdisimone closed your "Issue" -

Github Issues are supposed to be mostly for issues with the software, not so much troubleshooting like this. You might have better luck asking for help in Looped on Facebook or in the [Zulip chat](https://loop.zulipchat.com/login/)

**Comment by mianla8** [comment]
The article seemed to suggest to try posting here for help trying to resolve my red loop. I’m worried something is wrong with my RL too. I’m just not sure how to determine that.

**Comment by mianla8** [comment]
I also don’t want to risk wasting supplies and insulin by trying new pods or sensors. I just don’t know what to do. I posited to the general forum on tulip. 

I love this setup, my A1c hasn’t been as good as it is now in over 18 years. I’ve just never had a problem like this for just over a year.
