### ISSUE TITLE
BG is always displayed as mg/dl in the main view (top and graph).

### ISSUE THREAD

**Issue by cfaagaard** [LoopKit/Loop#1406]
**Describe the bug**
When running Loop in simulator on mac and have chosen CGM-simulator as sensor the blodsugar is always shown as mg/dl on the main view (both in the graph and in the top bar). Everywhere else in loop and in health it is shown correct as mmol/L.
If I click the BG-graph it also shown, correct, in mmol/L.

**To Reproduce**
See above.

**Expected behavior**
I would expect the number at the top-left to be shown in mmol/L. 
I would expect the graph to show numbers in mmol/L.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-10-09 at 21 29 11](https://user-images.githubusercontent.com/25353502/95650629-102b6500-0ae5-11eb-9aea-a9c57c61292a.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-09 at 21 32 00](https://user-images.githubusercontent.com/25353502/95650633-13265580-0ae5-11eb-9d98-76f735ed1c2b.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-09 at 21 33 56](https://user-images.githubusercontent.com/25353502/95650635-16b9dc80-0ae5-11eb-89ac-89b4bce224da.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-09 at 21 57 26](https://user-images.githubusercontent.com/25353502/95650637-19b4cd00-0ae5-11eb-858a-a7d3b43b78e7.png)

**Phone**
 - Hardware: Macbook - using the simulator via xcode build
 - OS Version: "14"

**Loop Version**
 - Version Number: 2.3.0.57
 - Repo: dev-branch

**CGM**
 - Device: Simulator

**Pump**
 - Manufacturer: Simulator

**Comment by cfaagaard** [comment]
Fixed.

![Simulator Screen Shot - iPhone 11 - 2020-10-11 at 15 52 05](https://user-images.githubusercontent.com/25353502/95680419-d720ec80-0bd9-11eb-890d-d089f98725e9.png)

**Comment by iMaces** [comment]
@cfaagaard  - How did you fix this? I’m having the same problem.

**Comment by cfaagaard** [comment]
@iMaces 
I did not fix it. Pete did with this commit: https://github.com/LoopKit/Loop/commit/beb7d25ab9c5a9b7adcb740044c25fa805b6248b
