### ISSUE TITLE
Battery Status Empty

### ISSUE THREAD

**Issue by ashrind** [LoopKit/Loop#141]
Any thoughts as to why my battery status might not be filling in? Running on a 722, changed the battery when I started with Loop last night
![img_7367](https://cloud.githubusercontent.com/assets/21300821/18098995/7fb8d52a-6e99-11e6-81c9-11afdf2a8c62.PNG)

**Comment by loudnate** [comment]
This is a know issue with the x22 pumps. @jlucasvt has started documenting the time-voltage curve for a lithium battery. I'm hoping someone can do the same for an alkaline as well.

**Comment by ashrind** [comment]
@loudnate Thanks for the answer!

**Comment by jlucasvt** [comment]
I'm finally committed to gathering Alkaline data.  Should have it mapped out in about a week.

**Comment by tomasboudr** [comment]
Awesome that this is getting some love! Always wondering why it was blank since you could see the voltage in pump status.

**Comment by jlucasvt** [comment]
Alkaline and Lithium Battery data.

https://docs.google.com/spreadsheets/d/19FpO5YO5ewQrdph_4iIXuear6xRGzl-AYTiFeHwPcVk/edit?usp=sharing

**Comment by loudnate** [comment]
Very awesome!

**Comment by loudnate** [comment]
@jlucasvt my personal recommendation would be to expose a voltage-to-percentage remaining function on the PumpModel enum in MinimedKit, in the rileylink_ios repo.

**Comment by jlucasvt** [comment]
Yes if we use the linear eq's it should be pretty simple.  I  I did do a quick run with excel to generate a 4th Ord Polynomial Eq for both but they may be a bit overboard..  

![screen shot 2016-09-25 at 10 45 21 am](https://cloud.githubusercontent.com/assets/19819388/18815997/a7a2f4d4-830d-11e6-9962-292219f63077.png)

**Comment by loudnate** [comment]
Ideally there is no user setting for choosing their battery type.

**Comment by tomasboudr** [comment]
I agree with you nate, ideally - but if its tricky to detect in software, you have to realize its a switch that will be used very rarely. I would rather time be spent on other things and there be a switch.

**Comment by jlucasvt** [comment]
Yeah , My one touch ping made you choose on battery swap (ALK or LITH).  It will be ideal to not worry about the battery type.  Something that can be improved if we want to track battery swaps and actual decay.  

In the past I wired this up in the DeviceDataManager.assertCurrentPumpData just after batterystatus is set and before NSUpload.
  
```
if let sentrySupported = self.pumpState?.pumpModel?.larger where !sentrySupported {
        self.setBatteryStatusforNonMySentryPumps(status.batteryVolts, IsLithium)
}

I am going to start here and and then will need some guidance on the next steps

**Comment by scottleibrand** [comment]
We could certainly make is a 3-way selection: unspecified, alkaline, or lithium. If unspecified (default) we use an average decay curve that does something reasonable for both. If specified, we can be more accurate...

**Comment by jlucasvt** [comment]
I am sure this is woefully bad Swift and probably belongs in the bin.   

2 modifications to DeviceDataManager.swift
1 modification to StatusTableViewController.swift

You will need to set BatteryIsLithium = false Alkaline
[BatteryIsLithium = false](https://github.com/jlucasvt/Loop/commit/11cc14a8ba20b63a1b98051c6c83d5f1c21c1bfa#diff-e49b73a75143263adce7ce2d8d0f763aR385)

Also you will get a build warning because one of the if statements (Lithium or Alkaline ) won’t be executed.

**Comment by jlucasvt** [comment]
Updated to latest v1.1 Loop Code Testing this week and will do a PR. 

[https://github.com/jlucasvt/Loop/tree/master-1.1-x22BatteryStatus
](https://github.com/jlucasvt/Loop/tree/master-1.1-x22BatteryStatus
)

**Comment by jlucasvt** [comment]
Doing some testing now with battery and alerts. It's working pretty good.  
## x22 Battery Inidication
![img_6151](https://cloud.githubusercontent.com/assets/19819388/19651429/cd163f12-99da-11e6-9798-40785990d085.jpg)

## Lithium Enable Switch
![img_6152](https://cloud.githubusercontent.com/assets/19819388/19651435/d13cfef0-99da-11e6-8a01-90c246bcbdf2.jpg)

**Comment by tomasboudr** [comment]
That looks good! Nice work.

**Comment by ashrind** [comment]
This is awesome!

**Comment by jlucasvt** [comment]
I have rebuilt the UI to allow selection of Alkaline or Lithium and a description explaining the difference for the user.  I've made all the requested changes from my last PR and hopefully it will be accepted this time.    Here is the current source it's based on dev 1.1.1 

[https://github.com/jlucasvt/Loop/tree/dev-1.1.1-x22BatteryStatus](https://github.com/jlucasvt/Loop/tree/dev-1.1.1-x22BatteryStatus
)

![img_6206](https://cloud.githubusercontent.com/assets/19819388/20319651/f986d7aa-ab3c-11e6-95b6-c04fffe4ce12.jpg)

**Comment by ps2** [comment]
More lithium battery history:
<img width="869" alt="devicestatus" src="https://cloud.githubusercontent.com/assets/14649/20533604/bdb9786a-b0a3-11e6-9b13-e47d570b00c9.png">

**Comment by tomasboudr** [comment]
This is working... One minor note though is that in practice with normal Duracell (alkalines) my battery has lasted 30-40% (ballpark) longer than loop's current algorithm predicts. I have had it warm me for 0% and the pump still had 2/4 bars on the battery meter.
