### ISSUE TITLE
Missing localization - onboarding (PR is ready for merge)

### ISSUE THREAD

**Issue by cfaagaard** [LoopKit/Loop#1411]
**Describe the bug**
Fresh install of loop. When Loop starts the onboarding starts. There are some text in English (should be in Danish)

**To Reproduce**
1. Start loop

First screen shows english text.
Click "jeg er klar" (I am ready)
English text in second screen.

Also at the "insulinmodel"

**Expected behavior**
The text should be in Danish.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-10-11 at 17 06 47](https://user-images.githubusercontent.com/25353502/95682366-1d2f7d80-0be5-11eb-9480-907cf7eaf15d.png)

![Simulator Screen Shot - iPhone 11 - 2020-10-11 at 17 13 58](https://user-images.githubusercontent.com/25353502/95682376-2b7d9980-0be5-11eb-8528-7bc3c2a756c8.png)

![Simulator Screen Shot - iPhone 11 - 2020-10-11 at 17 45 51](https://user-images.githubusercontent.com/25353502/95683141-b3fe3900-0be9-11eb-943d-397db09b929d.png)

**Phone**
 - Hardware: Macbook - using the simulator via xcode build
 - OS Version: "14"

**Loop Version**
 - Version Number: 2.3.0.57
 - Repo: dev-branch

**CGM**
 - Device: Simulator

**Pump**
 - Manufacturer: Simulator

**Comment by mylma** [comment]
Also, the last screen says there are **two** insulin models to choose (which is true in Tidepool-Loop). However, in DIY-Loop there are currently four options.

**Comment by mylma** [comment]
Onboarding: Nightscout Login button is not localized.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-13 at 14 19 58](https://user-images.githubusercontent.com/44064056/95863601-129ff000-0d6d-11eb-9993-c76eefbda557.png)

**Comment by cfaagaard** [comment]
> Also, the last screen says there are **two** insulin models to choose (which is true in Tidepool-Loop). However, in DIY-Loop there are currently four options.

I think you should move this to a separate issues. I think it needs more work than just a "localization"-fix.

**Comment by mylma** [comment]
> > Also, the last screen says there are **two** insulin models to choose (which is true in Tidepool-Loop). However, in DIY-Loop there are currently four options.
> 
> I think you should move this to a separate issues. I think it needs more work than just a "localization"-fix.

https://github.com/LoopKit/Loop/issues/1423
