### ISSUE TITLE
Therapy settings: Correction Range info units, add mmol/L

### ISSUE THREAD

**Issue by mylma** [LoopKit/Loop#1418]
**Describe the bug**
The new Therapy Settings Correction Range info text should have mmol units too, see below: 

"If you've used a CGM before, you're likely familiar with target range as a wide range of values you'd like for your glucose notification alerts, such as **70-180 mg/dL** or **90-200 mg/dL**."

**To Reproduce**

Start Onboarding
OR
1. Go to Settings > Therapy Settings > Correction Range.
2. Click on 'i' icon to view the longer info text.

**Expected behavior**
Mmol units should be visible too, not just mg/dL

**Screenshots**
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-13 at 14 22 15](https://user-images.githubusercontent.com/44064056/95876929-45051980-0d7c-11eb-9ff4-2886dd7a40da.png)

**Phone**
 - Hardware: iPhone 8 and Simulator
 - OS Version: iOS 14.0.1

**Loop Version**
- Version Number: 2.3.0.57
- Repo: dev-branch

**Pump**
 - Simulator

**Comment by mylma** [comment]
Also possible to just convert those values to mmol's by translator.

**Comment by cfaagaard** [comment]
In the Danish translation I have just translated it to mmol/L:
"Hvis du har brugt en CGM tidligere er du sandsynligvis bekendt med at få advarsler ud fra et blodsukker interval, såsom 5-10 mmol/L eller 6-12 mmol/L."

**Comment by mylma** [comment]
Yup, I did the same!
