### ISSUE TITLE
New Settings view: Alert permissions localization

### ISSUE THREAD

**Issue by mylma** [LoopKit/Loop#1419]
**Describe the bug**
Some of the translations are missing in the new Critical alerts and Notifications settings screen, see screenshot below.

**To Reproduce**
1. Choose any other Loop language than English.
2. Turn off Loop notifications in iOS Settings.
3. Open Loop Settings view.
4. Tap ’Critical Alerts...’ button.
5. Info texts are missing translations.

**Screenshots**
![AD90D208-0DE9-46A2-8483-8D88BA63CF00](https://user-images.githubusercontent.com/44064056/95886680-923ab880-0d87-11eb-84c5-680a5fd6e3dc.png)

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 14.0.1

**Loop Version**
 - v2.3.0.57
- dev branch

**Comment by cfaagaard** [comment]
The text is there, but I has something to do with this issue: https://github.com/LoopKit/Loop/issues/1422
