### ISSUE TITLE
New Settings view Carb ratios & ISF: saving new entries

### ISSUE THREAD

**Issue by mylma** [LoopKit/Loop#1420]
**Describe the bug**
When you add a new carb ratio or ISF value and tap Save, Loop asks authentication. Then looks like Loop didn’t save the new entry although new entry is visible. Cancel button is visible, and if you tap it, nothing happens. You need to swipe the screen down to get back to the Therapy settings view. New entry is not visible if you check the Carb Ratios view. When you close the Settings screen and then open it again, go to Therapy Settings, Loop shows the new entry. See a video below.

**To Reproduce**
1. Go to Settings view > Therapy Settings
2. Tap Carb Ratios and add a new entry.
3. Tap Save button. Authenticate. Tap Cancel button. New entry appears on the list, but Cancel button is still visible.
4. Swipe down.
5. Check Carb Ratios, no new entry visible on the list.
6. Close settings view and open again. Go to Therapy settings and see Carb Ratios section. The previously entered new entry is now visible.

**Expected behaviour**
When tapping Save, you should see the new entry on the list. You should go back when tapping the Back button.

**Video**
https://www.dropbox.com/s/qsrrf9aqxb510lg/RPReplay_Final1602606926.MP4?dl=0

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 14.0.1

**Loop Version**
 - Version Number: 2.3.0.57
 - Repo: dev

**CGM**
 - Device: Simulator

**Pump**
 - Manufacturer: Simulator

**Comment by elnjensen** [comment]
Just wanted to second this - however, I'm only seeing it for ISF, not for carb ratio.  For carb ratio, authenticating and saving works correctly.  But for ISF, I get the behavior described above - the settings are saved correctly after authentication, but there is no indication of that in the interface.  The only way out of the ISF settings view is to swipe down on the settings sheet. 

Loop 2.3.0.57.
