### ISSUE TITLE
All software up to date, successful build, "phone not connected" error.

### ISSUE THREAD

**Issue by dwaldny** [LoopKit/Loop#1432]
Time for a yearly update.  (Omnipod + Dexcom G6)
-Paid for another year of developer account.
-Agreed to licensing agreement.
-Updated my 2017 15" MacBook Pro to OS 10.15.7, 
-Updated Xcode to 12.1 (and restarted after). 
-Updated iPhone 11 Pro to iOS 14.2
-Downloaded new Loop-master files.  
-Followed instructions slowly and line-by-line.  
-Received "build successful" message.
-Received the following message:  "{nameofphone} is not available. Please reconnect the device."  
-Device was plugged in via Apple USB-C to lightning cable, was charging, and was recognized by name by Apple Music.  

No report to attach - unable to install app on phone. 
[Device_Not_Available.pdf](https://github.com/LoopKit/Loop/files/5527072/Device_Not_Available.pdf)

[Device_Not_Available.pdf](https://github.com/LoopKit/Loop/files/5527089/Device_Not_Available.pdf)

**Comment by dwaldny** [comment]
Restarted phone and computer and re-built (4) times. Same Error.
Tried different lightning cables - all connected directly to USB-C port (no adapters).
Not using and Beta versions.

**Comment by scrappy** [comment]
> On Nov 11, 2020, at 14:29, dwaldny <notifications@github.com> wrote:
> 
> 
> Time for a yearly update. (Omnipod + Dexcom G6)
> -Paid for another year of developer account.
> -Agreed to licensing agreement.
> -Updated my 2017 15" MacBook Pro to OS 10.15.7,
> -Updated Xcode to 12.1 (and restarted after).
> -Updated iPhone 11 Pro to iOS 14.2
> 

iOS 14.2, doesn’t it need 12.2(beta)?

**Comment by dwaldny** [comment]
You nailed it. Sorry I didn't catch it, and thanks for your time and attention.  Up and looping again!

**Comment by stephmilne** [comment]
Hi! This is my first time rebuilding the app! And I ran into the same issue.  (Omnipod + Dexcom G6)
-Paid for another year of developer account.
-Agreed to licensing agreement.
-Updated my 2020 15" MacBook Air Big Sur 11.2.3
-Updated Xcode to 12.4
-Updated iPhone 8 14.4
-Downloaded new Loop-master files.
-Followed instructions slowly and line-by-line.
-Received "build successful" message.
-Received the following message: "iPhone is not connected. Xcode will continue when iPhone is connected"
-Device was plugged in via Apple USB-C to lightning cable, was charging, and was recognized by name by Apple Music.

No report to attach - unable to install app on phone. Help? 
<img width="1396" alt="Screen Shot 2021-03-12 at 7 14 46 PM" src="https://user-images.githubusercontent.com/80541129/111017485-c4693a00-8368-11eb-89fa-1611dffebfa4.png">
