### ISSUE TITLE
Question using the Spike App with the Loop App

### ISSUE THREAD

**Issue by snics** [LoopKit/Loop#1439]
Hi, I wanted to ask the community if it is possible to use the [Spike App](https://github.com/SpikeApp/Spike) instead of the Dexcom App? I read that there is a possibility. But I'm not sure if I need an adapted loop version. Has any experience with this?

**Comment by Kdisimone** [comment]
That question is best asked in the Looped group on Facebook. Loop doesn't officially support spike so you'll need to use support channels outside of the GitHub issues to get input from spike users. Yes, you'd have to use a different version of loop. Please use the search feature in Facebook for the Looped group's posts that already exist on the topic. Thanks.

**Comment by snics** [comment]
@Kdisimone ok, thanks!
