### ISSUE TITLE
ICR Table - times are'n shown correct after slide down

### ISSUE THREAD

**Issue by fdotta74** [LoopKit/Loop#1440]
**Describe the bug**
The ic setting times aren’t shown correctly.  initially the table looks correct, then if you slide down, the times change automatically.  If you select them, however, they appear correctly (in blue).  See also video on FB post https://www.facebook.com/groups/TheLoopedGroup/permalink/2699357606947555/  
I had the issue with Iphone SE (old model), Iphone 12 mini and different loop branches

**To Reproduce**

1. choose carbratio table
2. slide the table down and up
3. look at the times
4. press on one of the times and (in blue) you will see the correct time

**Phone and LOOP branch**

- Iphone SE (old model) + IOS 14.0.1 + Master 2.2.4
- Iphone 12 mini + IOS 14.1 + AB 2.2.4
- Iphone 12 mini + IOS 14.1 + FREEAPS V2.1 (174)

**CGM**
Dexcom G6
    

**Pump**
Omnipod Eros

![picture](https://user-images.githubusercontent.com/62246679/100073323-a9b49900-2e3d-11eb-961d-1ed7d1a47050.jpg)

**Comment by vmyshak** [comment]
I'm having the exact same issue happening.

Phone and LOOP branch

    Iphone 7 + IOS 14.2 + Master 2.2.4

CGM
Dexcom G6

Pump
Omnipod
