### ISSUE TITLE
Error: pump data is 80 minutes old NEW USER

### ISSUE THREAD

**Issue by Ecwelsh** [LoopKit/Loop#1441]
We are new users. My son's riley link wasn't working properly but we did an update over the weekend. Now today he is getting a message that says pump data is 80 minutes old. He tried to deactivate his pod to insert a new one because he was due to do one later today but the loop app wouldn't pair his new pod. He put the new pod on with his omnipod PDM but has anyone seen this before and what did you do to resolve it. We are frustrated because it's new to us and we have had issues a lot of the time.

**Comment by loudestnoise** [comment]
Hi @Ecwelsh you may have a lot better help getting troubleshooting on either the 

- [Looped FB Group](https://www.facebook.com/groups/1782449781971680)
- [Loop Zulip chat](https://loop.zulipchat.com)

but I would start with checking out the [LoopDocs](https://loopkit.github.io/loopdocs/), and specifically the [Red Loop](https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/) page.

I know when my Loop is giving me that message it's normally related to my RileyLink having trouble communicating with my iPhone and Pod. Maybe try repositioning it relative to the phone and pod.

The Issues here on GitHub are supposed to be more related to troubleshooting the code or submitting bugs/problems with the app, not general troubleshooting. 😄

**Comment by Ecwelsh** [comment]
Thank you!!
