### ISSUE TITLE
Can't add Dexcom G6, only CGM simulator available

### ISSUE THREAD

**Issue by seanknox** [LoopKit/Loop#1445]
**Describe the bug**

When adding a CGM, 'CGM Simulator' is the only option. My Dexcom G6 (already running in the app) isn't presented as an option. The `automatic-bolus` branch doesn't have this problem.

**Attach an Issue Report**
[Loop Report 2020-11-29 12:02:36-08:00.txt](https://github.com/LoopKit/Loop/files/5612779/Loop.Report.2020-11-29.12.02.36-08.00.txt)

**To Reproduce**
1. Go to Settings > Add CGM
1. CGM Simulator is the only option, Dexcom G6 not shown

**Expected behavior**
Can add Dexcom G6

**Screenshots**
![IMG_0002](https://user-images.githubusercontent.com/1231630/100554309-b4f63300-3248-11eb-8a5d-f0971d3fbd22.PNG)

**Phone**
 - Hardware: iPhone 12 Mini
 - OS Version: iOS 14.2

**Loop Version**
 - Version Number: 9cf96f2a3baaebca57aa6b78338bd46f4f267460 (dev)
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: PI/PM Version: 2.9.0

**Additional context**
Setting up on a brand new iPhone.  Possibly related: https://github.com/LoopKit/Loop/issues/1444

**Comment by Martata83** [comment]
same issue

**Comment by iMaces** [comment]
Same problem as well. Had to go back to the previous dev beta.

**Comment by hirschthomas** [comment]
Same here, 
can not add a CGM only Simulator !

**Comment by sascha-egerer** [comment]
I think it has been broken by 0acf966a89ab63f73ebbccf655de613b050a06cd

**Comment by ZombieEleos** [comment]
Having the same issue.

**Comment by ps2** [comment]
This is a build issue, generally caused by not using the LoopWorkspace build.
