### ISSUE TITLE
Feature Request: Option for Daily Carbohydrates Report

### ISSUE THREAD

**Issue by Paulfamilyof6** [LoopKit/Loop#1448]
**Problem**: Dosing for food with unknown carb amounts usually requires a Wild A$$ Guess (WAG) carb entry.  This can result in unwanted highs/lows.  I've found that if I go back into the "Carbohydrates" screen at the end of the day and compare what my WAG was with what Loop actually recorded for carbs and absorption time, the next time I bolus for the same meal, its not as much of a WAG... The problem is that it is a pain in the butt to have to remember to go back and check at the end of the day, and record the results to compare to what was entered. 

**Solution**: Add an option in the settings to send a daily report of the "carbohydrates" screen to the desired email address. This way the user (if desired) can automatically get the details from the previous day and have a better way to compare the WAG to reality. 

![IMG_20201203_103733](https://user-images.githubusercontent.com/33383442/101060787-65b84700-3555-11eb-8d38-7a84c1eda912.jpg)

**Loop Version**
Version Number: 2.3.0
Repo: LoopKit/Loop/tree/automatic-bolus

**CGM**
Device: Dexcom G6
Manager app: Dexcom App

**Pump**
Manufacturer: Omnipod
Model: Eros

**Additional context**

**Comment by absmindedprof** [comment]
Seconded. Some sort of method for enabling morning-after review would be terrific. The carb data from the prior evening is gone by the time I wake up in the morning. It's a really great tool for trouble-shooting, but only if you can access it!
