### ISSUE TITLE
Loop Insulin Delivery Graphs and Reservoir Summary Showing Incorrect (Double) Total Insulin Delivered

### ISSUE THREAD

**Issue by garykidd** [LoopKit/Loop#1451]
Total delivered insulin is showing incorrectly, periodically.  Screen shots and event Event History, below. 

- Loop  Autobolus Branch (v 2.2.4)  
- Minimed 723 (v 2.3A1.1)
- Dexcom G6 
- iPhone 12 Pro Max (iOS 14.2.1)

### _**OVERSTATED INSULIN SUMMARIES:**_ 

[Fetch Recent History.txt](https://github.com/LoopKit/Loop/files/5647774/Fetch.Recent.History.txt)

![image](https://user-images.githubusercontent.com/17712640/101261951-dfdcfd00-3708-11eb-9e7a-f7ab383a8981.png)
![image](https://user-images.githubusercontent.com/17712640/101261962-ef5c4600-3708-11eb-82ea-fe4cdcc7105e.png)

And few mins later...

### _**CORRECT INSULIN DELIVERY SUMMARIES:**_

[Fetch Recent History.txt](https://github.com/LoopKit/Loop/files/5647776/Fetch.Recent.History.txt)

![IMG_1052](https://user-images.githubusercontent.com/17712640/101262022-685b9d80-3709-11eb-8fbc-5a2228bca347.jpg)
![IMG_1051](https://user-images.githubusercontent.com/17712640/101262025-727d9c00-3709-11eb-89ba-6eeaaee76b71.jpg)

**NOTES:** 
_[1] IOB and actual reservoir remaining appear correct in all instances.
 [2] In the overstated insulin delivery case,  the total value of insulin delivered since [TIME X], appears to be twice the actual value.  
[3] This occurs periodically at undetermined intervals.  
[4] The values always seem to correct themselves some time following (although not immediately following) a manual 'FETCH RECENT HISTORY' request. 
[5] Regardless of issue, Loop seems to function correctly._

**Comment by elnjensen** [comment]
I see the same issue, running 2.2.4 with a 523 pump. 
![A1748A55-986F-45D1-8A10-B232956DBFC8](https://user-images.githubusercontent.com/2545845/101358950-9526c680-3869-11eb-9a05-49c8949c6b18.jpeg)
![5CD55082-7BD4-4095-BE47-A8B4340EE417](https://user-images.githubusercontent.com/2545845/101358953-95bf5d00-3869-11eb-995a-b6afe1f9dd5b.jpeg)

**Comment by Trpl7ca** [comment]
Also see this problem, using Omnipod, G6, FreeAps.
![CF13124B-D84A-4D0F-90EF-84185BB90C0D](https://user-images.githubusercontent.com/52380252/101503033-86eab000-3926-11eb-98d6-51b233ca3896.jpeg)
![841BB368-EA01-4165-AC06-47803C0F5EBA](https://user-images.githubusercontent.com/52380252/101503039-88b47380-3926-11eb-8900-4ac4755ae70e.jpeg)
