### ISSUE TITLE
Duplicate ar.lproj directories break Time Machine backups

### ISSUE THREAD

**Issue by dennisrjohn** [LoopKit/Loop#1452]
**Describe the bug**
When Time Machine is backing up on my computer, it errors because there are two ar.lproj directories in the root directory.

**To Reproduce**
1. On OSX machine with Time Machine enabled, clone git repository
2. Allow Time Machine to back up.
3. An error will appear that time machine has exited with "an error has occurred copying files"
4. (TimeMachine) [com.apple.TimeMachine:General] Failed to copy '/Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/XXXX/2020-12-04-162249/Macintosh HD - Data/Users/XXXX/Development/LoopXCode12.2/Loop/ar.lproj/Main.strings'to '(null)', error: -8062, srcErr: NO

**Expected behavior**
Time Machine should complete
Manually deleting one of the directories fixes the issue.

**Loop Version**
 - Autobolus branch, but the duplicate directory also exists in  master.

**Comment by sascha-egerer** [comment]
This was fixed in 8cbc4b0590f6411918aa69c7453992540885588d

**Comment by dennisrjohn** [comment]
Thanks. Closing.

**Comment by sascha-egerer** [comment]
Issue does still exist in master branch

**Comment by dennisrjohn** [comment]
Sorry. Misunderstood, will leave open until same fix is applied to Loop.

**Comment by ps2** [comment]
I believe the files are all removed in dev.

Master gets updated when a new release is cut.
