### ISSUE TITLE
Feature Request: iOS 14 Widgets

### ISSUE THREAD

**Issue by snics** [LoopKit/Loop#1454]
Hi guys, wanted to know if there are plans to support the new iOS 14 widgets? Otherwise I would like to take care of the topic. If I can solve the problems I just had with the simulator 😅 .

**Comment by fmb787** [comment]
looking to the new widget as i want to see my Loop status on the home screen once i unlock my iPhone .

kindly fix you simulator problems and take care of this task 😅

**Comment by snics** [comment]
@ps2 I have just taken a look at this and started to work on widgets. But I still have a few questions is there an event or place in code where I can save insulin, blood glucose, OmniPod, and loop status via AppGroup for the widgets and make them available? Maybe you can help me so that I can implement it properly.

**Comment by idoodler** [comment]
> @ps2 I have just taken a look at this and started to work on widgets. But I still have a few questions is there an event or place in code where I can save insulin, blood glucose, OmniPod, and loop status via AppGroup for the widgets and make them available? Maybe you can help me so that I can implement it properly.

Do you need any help?
