### ISSUE TITLE
CGM input freezing and causing crashes

### ISSUE THREAD

**Issue by emma18kleck** [LoopKit/Loop#1457]
Hi all, I'm a long time Looper but first time GitHub poster. I am having some issues with the auto bolus branch freezing and crashing. I think I have narrowed it down to the CGM input, as every time this happens, I have a red loop due to no CGM data (even though my Dexcom is working without issue). I have already re-built Loop a number of times, cleared my health data history, and wiped/restored my iPhone for good measure. 

Trying to attach the issue report, but this is only in .md files so not sure if there is another way to get the issue report on to this post. Please let me know if this is a known problem (a quick read through previous issues says no), and if so, how I can fix it. Thanks!

**Comment by Robert1er** [comment]
I've had a similar problem for the past week or so. I haven't figured out what triggers it. Sometimes it's stable for half a day, sometimes I can only get one meal in before a reboot is necessary.

Shutting down the app doesn't help. When I open the app it freezes immediately. I've gotten resolution by powering the phone down and starting back up.

[Loop Report 2020-12-11 09_55_32-05_00.txt](https://github.com/LoopKit/Loop/files/5684140/Loop.Report.2020-12-11.09_55_32-05_00.txt)

**Comment by mrrossi76** [comment]
Same happens to me, Long time Looper, red loop for hours, even though correct glucose is shown in loop app. Once a day app crashes only be fixed by restarting the phone.

Hardware: iPhone 12
OS Version: iOS 14.2.1
Loop Version Automatic Bolus V2.2.4

**Comment by lmacmama** [comment]
I am having the same issue.  When app crashes I have to restart my phone as well.  I haven't figured out what is causing the issue either.  It's happening about once a day for me.

Hardware: iPhone Xr
OS Version: iOS 14.2
Loop Version Automatic Bolus V2.2.4

**Comment by mrrossi76** [comment]
Finally resetting the phone and installing everything fresh was solving the issue. I am looping again.

**Comment by emma18kleck** [comment]
I don’t want to jinx it, but I think that this is now resolved. Per a post on the Looped Facebook page, I think the issue was my Nightscout connection. Reset my phone, and deleted my NS connection, it’s been working for the past 3 days now.

**Comment by MooseV2** [comment]
I'm also experiencing this. I'll try deleting my NS and see if that fixes it. Thanks for the suggestion.

**Comment by ps2** [comment]
Crash reports, found in Settings -> Privacy & Security -> Analytics & Improvements -> Analytics Data -> Loop-YYYY-MM-DD-HHMMSS.ips can help us determine what is causing a crash.  If this issue is still occurring for some people, please reopen and attach crash reports. Thanks!
