### ISSUE TITLE
First carb entry of day "disappears"

### ISSUE THREAD

**Issue by kevinmelia** [LoopKit/Loop#1458]
Long-time Loop user, but first issue report. My child is the Looper - using AutoBolus v.2.2.4 on an iPhone7 (iOS 13.6.1) with Dexcom G6 and Minimed 522.

The issue is that the first carb entry of the day often disappears. I can't reliably reproduce it with consistency (because I only get one opportunity a day to do it). We pre-bolus breakfast (typically about 10-15 minutes). At first I would have to enter the carbs twice because the first entry would just go away on its own. In reviewing Nightscout data I determined that it did not disappear, but rather was added to the day before exactly 24 hours earlier. Now I pay particular attention to the date when changing the time for the carb entry. It appears if I go too many minutes into the future, the date rolls back one day on its own. Not a huge deal now since I determined a work-around, but may annoy others and corrupt their Nightscout and Apple Health data.

**Comment by ps2** [comment]
I think this is fixed with some (now pretty old) changes to the time entry in the carb interface.
