### ISSUE TITLE
Using Bolus Tool the recommended value changes when screen is rotated

### ISSUE THREAD

**Issue by JBB2068** [LoopKit/Loop#1459]
**Describe the bug**
The recommended bolus changes when the phone is rotated. It only changes when I type in a bolus value and the change is equal to the amount I type in.

**To Reproduce**
Example:
Tap the Bolus tool while phone is portrait oriented.
Recommended shows 1.0 U
Change Bolus field to 0.7 U
Rotate phone to landscape orientation
Recommended now shows 0.3 U
Bolus field now shows 0.0 U
Rotate phone back to portrait orientation
Recommended now shows 1.0 U
Bolus field now shows 0.0 U

**Expected behavior**
I expect the numbers would not change when rotating the phone.

**Phone**
 - Hardware: iphone 6s
 - OS Version: 13.6.1

**Loop Version**
 - Version Number: 2.2.4
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Additional context**
I asked about this in Looped FB group and others are able to repeat the behavior.

**Comment by human911** [comment]
**Phone**
iPhone XR

**Loop**
v2.2.4

**Pump**
Medtronic

Attached screenshots for reference.
![IMG_4660](https://user-images.githubusercontent.com/10080856/102382870-c09f6480-3f7f-11eb-9461-81e15542cd01.PNG)

![IMG_4659](https://user-images.githubusercontent.com/10080856/102382885-c39a5500-3f7f-11eb-948d-93b34839c0d1.PNG)
