### ISSUE TITLE
Tempoary overide time do not become what is chosen

### ISSUE THREAD

**Issue by lad52** [LoopKit/Loop#1460]
When setting time for override to 30 min it becomes 15 min. It may be happining only when passing over to a new kour

**Comment by novalegra** [comment]
I looked into this bug, and it seems like it occurs when the duration picker is moved to 0 hr 0 min; the picker automatically corrects to 0 hr 15 mins, but the first time the minutes picker is changed after that, the change notification isn't sent. This seems to be an Apple bug that's been a problem for a while (see https://developer.apple.com/forums/thread/67113).

Uploading RPReplay_Final1609344066.MP4…
