### ISSUE TITLE
Pump did not respond in time

### ISSUE THREAD

**Issue by ElizabethZ85** [LoopKit/Loop#1465]
Any advice on this error screen? I have restarted my phone, app, flipped the RileyLink switch on and off, used a completely different pump and it still appears to be stuck.

![image](https://user-images.githubusercontent.com/46429901/104084676-11605100-51fe-11eb-8585-b56cb6617dc8.png)

**Comment by elnjensen** [comment]
That’s a standard Loop error message; just retry the bolus.  It just means there was a temporary loss of communication between pump and RileyLink.

**Comment by ElizabethZ85** [comment]
Thank you for your response!


Sent from Yahoo Mail for iPhone


On Saturday, January 9, 2021, 6:57 AM, Eric Jensen <notifications@github.com> wrote:




That’s a standard Loop error message; just retry the bolus. It just means there was a temporary loss of communication between pump and RileyLink.
