### ISSUE TITLE
AB branch cuts basal when prediction curve is above target

### ISSUE THREAD

**Issue by mattgrossbach** [LoopKit/Loop#1467]
**Describe the bug**
Loop frequently cuts my basal rate down to zero even when I am above target and no part of the prediction curve is below target. My target is 95-105 and suspend threshold is 90, but the same thing happened when my target was 100-100 and when my suspend threshold was 80.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.
[Loop Report 2021-01-15 09_41_10-05_00.docx](https://github.com/LoopKit/Loop/files/5821329/Loop.Report.2021-01-15.09_41_10-05_00.docx)

**To Reproduce**
It happens seemingly randomly when I'm above target using closed loop. You can see the issue when the basal is cut despite the prediction curve being above target.

**Expected behavior**
If I'm above target and every part of my prediction curve is above target I expect that my basal rate is not cut back all the way to zero.

**Screenshots**
![image](https://user-images.githubusercontent.com/61716323/104743458-b953ae00-5719-11eb-8662-15f8ef00448b.png)

**Phone**
 - Hardware: iPhone XR
 - OS Version: iOS 14.3

**Loop Version**
 - Version Number: Automatic Bolusing V2.2.4
 - Repo: Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Eros
 - Firmware version: 

**Additional context**
I've noticed that if I suspend the pump and then resume that my basal goes back to zero and the problem temporarily goes away. Killing the app and reopening it doesn't fix the issue however.

**Comment by ps2** [comment]
Your Issue Report is from 2021-01-15 14:41:10 +0000, right after your glucose reading of 129 at 9:37. But your screenshot is from 9:44, after your glucose reading of 128. I think for the dosing decision that happened at 9:38, your forecast went below your dosing threshold, so Loop low temped you to 0.

Temp basals last for 30 minutes; the newly scheduled 30 minutes of 0 U/hr basal when your normal basal is 1.6 U/hr and your ISF is 75 means that the 0 temp will have a 60mg/dL impact on your eventual BG.  This makes your forecast now predict you'll be entirely above range. 

I'm not sure what happened on the dosing decision at 9:43, where it let the 0-temp continue to run, but it might have been a similar situation.

You may consider moving your suspend threshold a little lower. When your forecast hits your suspend threshold, Loop reacts quite strongly.
