### ISSUE TITLE
Build error during Copy Framework with Carthage for "rileylink_ios"

### ISSUE THREAD

**Issue by isallam** [LoopKit/Loop#1468]
I'm running into a build error during the "Copy Framework with Carthage" stage using the latest "master" and Carthage 0.36.1. The error make sense but I'm not sure why the "lipo" call is not getting a proper command.

Here is the error during the build phase:

> Copy Frameworks with Carthage
> A shell task (/usr/bin/xcrun lipo /Users/ibrahim/Library/Caches/org.carthage.CarthageKit/DerivedData/12.3_12C33/rileylink_ios/4ca67f4ac2dd5b15c6b7e19c448eb2d52b9592a7/Build/Intermediates.noindex/ArchiveIntermediates/Shared/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RileyLinkKit.framework//RileyLinkKit -output /var/folders/td/_xz2nqd152g2vhsnnrvr65700000gn/T/carthage-lipo-tjxolI/RileyLinkKit) failed with exit code 1:
> error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: one of -create, -thin <arch_type>, -extract <arch_type>, -remove <arch_type>, -replace <arch_type> <file_name>, -verify_arch <arch_type> ... , -archs, -info, or -detailed_info must be specified
> 

**Things I tried**
- Cleanup of cached files. 
- Made sure I have the latest updates for both OS and Xcode.
- Rebooted the machine after the updates.
- Cloned and built "rileylink_ios" separately with no issues.

**Phone**
 - Hardware: iPhone SE 
 - OS Version: iOS 14.3

**Loop Version**
 - Version Number: I tried "master", "dev", "v2.2.4_xcode12" (which I believe is master) 
 - Repo: LoopKit/Loop

**Build Environment**
- OS Version: 10.15.7 (19H114) 
- XCode Version: 12.3 (12C33)
- Carthage Version: 0.36.1

Appreciate any help on how to debug this issue or if anyone else saw similar problem.

**Comment by Kdisimone** [comment]
Some suggestions to try

https://stackoverflow.com/questions/9189259/command-usr-bin-lipo-failed-with-exit-code-1-error

**Comment by hpc4fun** [comment]
The issue and a work-around is described here: https://www.loopandlearn.org/carthage-0-36-0/

**Comment by isallam** [comment]
@Kdisimone and @hpc4fun, Thank you for the prompt reply! The stackoverflow link is different than my issue, I believe it's related to multiple architecture support, but the link from @hpc4fun to the "[loopandlearn](https://www.loopandlearn.org/carthage-0-36-0/)" article did solve the problem by just using the LoopWorkspace to build.
