### ISSUE TITLE
Changing date on iPhone (back and forth)

### ISSUE THREAD

**Issue by cfaagaard** [LoopKit/Loop#1469]
**Describe the bug**

The kid changed the date on the loop-phone (two days ahead) so he could play pokemon go.... (something to do with license :-) ) 
After 30 minutes he changed it back to the correct date. 
But then there were future bg in loop/health as readings from dexcom of course kept coming in (with the wrong dates). 
The problem/bug were that AB kept giving him insulin.

Loop stopped the prediction at the time where the date changed.  1hr10min after the prediction stopped, AB started giving 0.3 every 5 minutes. And kept going.
![image](https://user-images.githubusercontent.com/25353502/104925010-8706b280-599e-11eb-89f5-cd2637435541.png)
![image](https://user-images.githubusercontent.com/25353502/104925033-8f5eed80-599e-11eb-8464-fd24dfaa7b5e.png)
![image](https://user-images.githubusercontent.com/25353502/104925052-9685fb80-599e-11eb-81e0-b00a37e87270.png)
![image](https://user-images.githubusercontent.com/25353502/104925065-9dad0980-599e-11eb-8566-0ecec5a34b77.png)
![image](https://user-images.githubusercontent.com/25353502/104925103-a998cb80-599e-11eb-91fc-c58aee4272bb.png)

The date was changed on 17.1.21 at 13.13 (loop log time) and changed back 17.1.21 at 13.35. (the date might have been set two times; first one date ahead and then 2 days ahead)

**Attach an Issue Report**

[Loop-Report-2021-01-17-1923270100.txt](https://github.com/LoopKit/Loop/files/5830611/Loop-Report-2021-01-17-1923270100.txt)

Look at lines: 
Wrong dates/readings from dexcom: 2564-2578
Missing 35 minutes due to "new" date: 2155-2156 
Wrong predictedGlucose: 2982-2985

**To Reproduce**
The bug can be reproduced in dev-branch (dev-branch version 2.3.0.57 - build 14.12.20):
1. set the date 2 days ahead on the iphone
2. enter a high bg in health (lets say 230)
3. set the date back to the correct date.

No matter what bg-value comes into loop from this point, the current bg and the predicted bg will be 230. 
And loop will give you insulin based on this value... all the time, no matter the real bg-values. Even if they are coming into Loop.
screenshot from dev:
Entered 10 as the wrongful bg via health. Even with very low BG the temp basal is still on max.

![image](https://user-images.githubusercontent.com/25353502/104926040-ef09c880-599f-11eb-952b-ec34eca79054.png)

**Expected behavior**
Of course there is an issue that the kid can change the date (parental control on iphone).
But I think Loop should not use future bg in prediction and it should warn about future bg. 
Maybe even give a red loop until the future BG is deleted in health.
Or maybe Loop should use RTC in its date-handling? (if Dexcom has this).
Because the dexcom follow looks good:
![image](https://user-images.githubusercontent.com/25353502/104927124-54aa8480-59a1-11eb-88a6-fe143d36f89f.png)

**Screenshots**
See above.

**Phone**
 - Hardware: Iphone 11
 - OS Version: 14.3

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: tested on AB and dev, but I think it is on master too.
 -
**CGM**
 - Device: Dexcom G6 and simulator
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: Omnipod and simulator

**Comment by ps2** [comment]
Reposting from Zulip: Incorrect BG data is just one of the many possible issues that a date change could trigger in Loop and cause risky dosing issues. In the dev branch there is code that checks the time against public NTP servers periodically and generates alerts to help make you aware of this problem. An additional thing I'd recommend that parents do is set a screen time passcode for your kid's phone. It will prevent them from turning off automatic time sync.
