### ISSUE TITLE
Loop app crash

### ISSUE THREAD

**Issue by KristinHagins** [LoopKit/Loop#1470]
**Describe the bug**
Loop app was working at 5 am. At around 7 am, the app went to white screen and reverted back to Home Screen upon tap. Restarted phone several times. Didn’t fix issue. App was still notifying that Loop had not been completed. Only phone use between 5 am and 7 am was Apple CarPlay plug in. Phone is XR and was using iOS 13.7. App built in September 2020 on paid developer account. Not updated since. Few issues recently with delay start to app upon tap to open. No changes to settings recently. Updated to 14.3 in anticipation of having to rebuild app this evening (using Big Sur). After update, app says no longer available. 

**Attach an Issue Report**
Cannot obtain an issue report as app won’t open. 

**To Reproduce**
Won’t open

**Expected behavior**
Open to Home Screen of Loop

**Screenshots**
After 14.3 update:
![9AC83670-5779-4B54-A820-A63CE67B8558](https://user-images.githubusercontent.com/77792318/105366316-33c67700-5bcd-11eb-999f-171cba83c08a.png)

**Phone**
 - Hardware: iPhone XR
 - OS Version: was 13.7

**Loop Version**
 - Version Number: don’t know, can’t confirm, downloaded 9/2020
 - Repo:

**CGM**
 - Device:Dexcom G6]
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros 
 - Firmware version: sorry, don’t know

**Additional context**
Only fix I see is to rebuild app. Concerns over Big Sur and 14.3 working well with Loop. Pages don’t look updated yet for Big Sur.

**Comment by ps2** [comment]
Yes, you do need to rebuild. The current master works fine on Big Sur.
