### ISSUE TITLE
Loop not working and software hanging up

### ISSUE THREAD

**Issue by rajeevvijay** [LoopKit/Loop#1471]
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

Hi, I have been using Loop for 4 months without any problem. While changing my insulin refill and pump battery couple of days ago I got a Red circle on Loop that did not go away. On clicking it I got a message ‘the pump delivering bolus’ though it was not. I then switched On/off Rileylink it didn’t work. Rebooted the iPhone and it stopped showing Dexcom values. Error messages are below. 
While initially it looked like a pump problem but it appears Loop is not showing CGM values on main screen while it continues to read it through Dexcom app. The screenshot from Health App shows that and also when you click on the Dexcom page on the Loop app. 
I have tried deleting the CGM app from Loop and reinstating it, Bluetooth On/Off, reinstalling Loop application 3 times, iPhone On/off, deleting Health App data but nothing seems to be working for more than 36 hours.
After reinstalling Loop software it shows CGM data initially for last few readings but then doesn’t seem to work. If you click on grey circle or other places, at times App is hanging up, it shows a spinning wheel on a black screen and the Loop App exits. As of now it is showing nothing other than Dexcom data on Dexcom page in the loop.
When I try to download Issue Report, the screen just remains Loading... and nothing happens. I have waited for more than 5min but nothing happens. So Issue report not attached here. 
Use iPhone X, iOS 14.3, Loop V2.3.0, Dexcom G5, Medtronic Minimed722 WWB, VER 2.4A1.1
I use Nightscout for sharing data.
Kindly advise. For info, I am based in India so in a different time zone.
![89B608A4-144F-4075-8D0B-1A81A713BA98](https://user-images.githubusercontent.com/74164093/105569356-057c9f00-5d67-11eb-9d77-f5f61ec9fb15.png)
![56A0663D-15D9-493B-AD11-180E5FEFE041](https://user-images.githubusercontent.com/74164093/105569360-0b728000-5d67-11eb-9678-c63b7892caf9.png)
![5AEB2FF6-0935-4AE3-BA11-B8030449C704](https://user-images.githubusercontent.com/74164093/105569362-0dd4da00-5d67-11eb-997d-a659e845ff8e.png)
![602AF9A4-FF0C-4FDC-BCDA-CB07B4856E4C](https://user-images.githubusercontent.com/74164093/105569364-10373400-5d67-11eb-93c9-0791ad3954f9.png)
![8078A86F-08B3-4745-9814-E4E869312804](https://user-images.githubusercontent.com/74164093/105569365-10cfca80-5d67-11eb-8b31-791f9efd7cea.png)
![19C052DC-6888-4A7B-BD45-F6376CB00027](https://user-images.githubusercontent.com/74164093/105569366-1200f780-5d67-11eb-9000-4ae0dc28304b.png)
![1EBFB12D-B11D-44DA-9033-317070BB57F2](https://user-images.githubusercontent.com/74164093/105569367-13322480-5d67-11eb-9a19-e9beb6f7f503.png)
![9C052FF6-7AB8-4C21-AFFD-A8B9E84E88E2](https://user-images.githubusercontent.com/74164093/105569372-16c5ab80-5d67-11eb-90b7-82b0a1e12d68.png)
![24B0B6F2-4B41-4195-B951-C8E3B59EA235](https://user-images.githubusercontent.com/74164093/105569375-17f6d880-5d67-11eb-98fb-32b5ce819281.png)

**Comment by rajeevvijay** [comment]
Sorry, I forgot to delete instructions.

**Comment by MooseV2** [comment]
I am experiencing this too, using Loop 2.2.4 (Automatic Bolus). Rebooting my phone seems to fix it temporarily, but it still stops after a few hours.

I use Omnipod and Dexcom G6. Interestingly, before I rebooted my phone I was also getting invalid readings from Dexcom Share when using [pydexcom](https://pypi.org/project/pydexcom/), and rebooting also fixed that. I don't know how that would be related, however, since I don't have Dexcom Share set up in Loop.
