### ISSUE TITLE
-142 in blodsugar

### ISSUE THREAD

**Issue by AnetteDalsgaard** [LoopKit/Loop#1474]
**Describe the bug**

Loop says my blod sugar Will be -143.... expects normal blodsugar.... 
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by human911** [comment]
Anette, Can you share a screenshot of the issue you are having? Does it appear to Double you IOB temporary in Loop after a bolus?
