### ISSUE TITLE
A question about omnipod dash

### ISSUE THREAD

**Issue by nadavv** [LoopKit/Loop#1475]
Hi
In the Docs I read that "Loop will not work with DASH pods". My question is, might this change in the future? Is there a chance that looping with dash pods CAN happen sometime?
Thanks

**Comment by marionbarker** [comment]
I suggest this issue be closed. This will not happen until a volunteer working with other volunteers solves this issue and implements a solution in swift. If you want to volunteer, please start here in the documents:
https://loopkit.github.io/loopdocs/#development-history
