### ISSUE TITLE
Scroll animation on value fields in reversed order on Carb Ratio page

### ISSUE THREAD

**Issue by Lytrix** [LoopKit/Loop#1479]
I am currently testing the new Dev build with the new UI using the pump and cgm simulator on an iPhone SE 2 running iOS 14.4.
On the Carb Ratio Page when adding a first value, the scrolling animation of the value fields seem to slide in the wrong direction, so scrolling up animates a scroll down and vice versa. 
See the animation in [this](https://www.dropbox.com/s/apfy3q7txj3ihkk/scroll%20animation%20reversed%20in%20carb%20ratio%20time%20fields.MP4?dl=1) video.

**Comment by loudestnoise** [comment]
I noticed this as well, but honestly didn't think twice about it. It almost felt like it was the spinning wheel in The Price is Right 😂😂😂

**Comment by ps2** [comment]
This is finally fixed correctly in dev with the latest commits.
