### ISSUE TITLE
Changing glucose unit in Health does not switch all units

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#148]
If I switch the unit to mg/dl in Apple Health from mmol/L the target glucose values or the insulin sensitivity values.  One cannot delete them and read them either.

Tried reseting app and it doesn't convert or allow the entry of new unit types.

**Comment by loudnate** [comment]
What's the expected behavior?

**Comment by beached** [comment]
I think the expected behaviour is to utilise the system glucose unit for entry/display and response to changes.

So if I change the unit in Apple Health and reset Loop, I should see all previous entries in the new unit of measure.  The entry should be in that unit too.

**Comment by loudnate** [comment]
OK, I believe it's currently intentionally displaying the value in the original unit used on purpose, since there isn't any way to specify sig digits in HKQuantity conversions that I know of.

**Comment by beached** [comment]
Are there ever more than 3 when dealing with pump data?  Its always a unsigned integral with <=3 sig digits in mg/dl

Also, i tried deleting the values and re-entering them but it would only allow the original unit type.

**Comment by marionbarker** [comment]
This is a very old Issue and I think may have been addressed.  Can this be closed?
