### ISSUE TITLE
Loop app not loading upon open most of the time

### ISSUE THREAD

**Issue by sumairs** [LoopKit/Loop#1486]
**Describe the bug**
When I open the loop app, it does not load and bolus and override buttons are not clickable. 
Sometimes if I wait the app does load eventually (takes 5+ minutes)
Other times it does not after the waiting period so I restart the app (actually shut it down and restart) - issue still occurs
Also restart my phone - issue still occurs
This issue is occurring 90% of the time I use the loop app. I recently re-built the app but it did not solve the issue

**Attach an Issue Report**
[Loop Issue Reports.zip](https://github.com/LoopKit/Loop/files/6007208/Loop.Issue.Reports.zip)

I attached issue reports from 3 different occasions where the issue occurred. 

**To Reproduce**
1. Open loop app (sometimes already in open apps, but other times from closed)
2. Screeen is not loaded fully (graphs are empty)
3. Bolus, override and carb entry buttons are not clickable 
4. Sometimes #2 above ccurs without #3 occurring

**Expected behavior**
Expect the loop app to load and all the data to be displayed and bolus and override buttons to be clickable. 

**Screenshots**

![image](https://user-images.githubusercontent.com/57295742/108448885-8a58bc80-7230-11eb-9c05-2c29ef2833cb.png)

![image](https://user-images.githubusercontent.com/57295742/108449473-8bd6b480-7231-11eb-96ba-4c82494c136e.png)

![image](https://user-images.githubusercontent.com/57295742/108449494-94c78600-7231-11eb-9ad2-1066046d7fde.png)

![image](https://user-images.githubusercontent.com/57295742/108449517-9e50ee00-7231-11eb-8c8f-f7aae22a5644.png)

**Phone**
 - Hardware: iPhone 11
 - OS Version: iOS 14.4

**Loop Version**
 - Version Number: V2.2.4
 - Repo: LoopKit/Loop
 - Branch: Master

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - TID: 1081619
 - PM Version: 2.9.0
 - PI Version: 2.9.0
 - Lot: L45982
 - Assigned Address: 1F04F013

**Additional context**
I have a paid apple Developer account that is functional (renewed July 2020). I used the latest Loop-master files when I rebuilt on Jan 12, 2021.

The app also takes much longer to pair a pod. Prior to the priming step, the app stays loading for sometimes 5 mins before the priming (clicking starts).

**Comment by MooseV2** [comment]
I also have this issue. My suspicion is that it has to do with the Dexcom G6, but I can't confirm this.

**Comment by Typ1er** [comment]
same errors here

Dexcom works solo after reinstallation, without problems. adds the RileyLink (754), and then adds the factors for the carb ratios, the error looks the same. 

The error occurred after the dexcom share error. Deleted the share, the loop app has not worked since.

iPhone X 14.4.1
Loop version does not matter (AB, Master, freeAPS (174/176))

**Comment by DanSeller** [comment]
Same error here. At some times Loop opens & works fine, at other times it won't even open. Rebuilding doesn't fix it. Using iPhone XR 14.4.2, Loop AB branch. Have Developer account.

**Comment by christophebirkeland** [comment]
I have the same issue. Running automatic bolus branch on iphone 7, and dexcom g6. Restarting the phone helps sometimes, sometimes restarting loop helps. Seems the problems arises when the dexcom app has an error message?

**Comment by SAVAPL** [comment]
someone in looped facebook group suggested i delete the nightscout URL and it worked for me.
