### ISSUE TITLE
Task failed exit code 65:  detected encoding of input file as Unicode (UTF-8) (in target 'OmniKitUI' from project 'RileyLink')

### ISSUE THREAD

**Issue by audreyvb36** [LoopKit/Loop#1488]
**Describe the bug**
Because I had to renew my develeper account, I needed to rebuild LOOP. I keep getting the same error message:

Showing Recent Issues
Command PhaseScriptExecution failed with a nonzero exit code

I read that it could be a home-brew issue so I reinstalled in the terminal. I restarted my computer, I am still getting this message

**Screenshots**
![Screen Shot 2021-03-05 at 12 58 34 PM](https://user-images.githubusercontent.com/80129251/110172824-88573780-7db2-11eb-8bea-6eea645cdda5.png)

**Phone**
 - Hardware: Phone 11
 - OS Version: iOS 14.4

**CGM**
 - Device:  Dexcom G6

**Pump**
 - Manufacturer: OmniPod

Please help! Thank you

**Comment by audreyvb36** [comment]
Also, I updated Xcode to 12.4 and restarted my computer and cleared my cache. Still getting that error

**Comment by Kdisimone** [comment]
Delete old downloaded folders of loop. Download new loop code and clear cache before building again.

**Comment by audreyvb36** [comment]
Got it - that worked, thank you!
