### ISSUE TITLE
The dependency graph contained a cycle while using Forked LoopKit

### ISSUE THREAD

**Issue by ZUCheema** [LoopKit/Loop#1493]
**Describe the bug**
I'm trying to develop a modified version of LoopKit dependecy and want to include it on Loop project with new features. 
When I tried to add a fresh fork of LoopKit in Cartfile (setting the carfile.resolved to pick the same commit from forked repo)and tried to build it, It gave the follow error: 

"The dependency graph contained a cycle"

I think the issue is due to LoopKit being used by dependencies of Loop project. Like G4SharedSpy, riley_link, BLEKit and dexcom is also using LoopKit as dependency. 

But the error won't appear if I use LoopKit/LoopKit in Loop project instead of using forked repo, i.e ZUCheema/LoopKit. 

**Attach an Issue Report**
Here's what XCode outputs: 
`
The dependency graph contained a cycle:

Amplitude-iOS: 

CGMBLEKit: dexcom-share-client-swift, LoopKit

MKRingProgressView: 

dexcom-share-client-swift: LoopKit

LoopKit: SwiftCharts

SwiftCharts: 

G4ShareSpy: dexcom-share-client-swift, LoopKit

rileylink_ios: MKRingProgressView, LoopKit

`

**To Reproduce**
1. Go to Cartfile
2. Replace github "LoopKit/LoopKit" "dev" to your own forked repo
3. Build XCode project

**Expected behavior**
XCode project would not build with forked LoopKit repo. 

Thanks

**Comment by ZUCheema** [comment]
I tried to clone all the dependencies and used forked repo of LoopKit for all but it created more issues like git index.lock conflict and would download multiple versions of LoopKit while doing carthage update.

**Comment by novalegra** [comment]
If you want to use a different LoopKit, I'd highly recommend building with a [Loop Workspace](https://github.com/LoopKit/LoopWorkspace), which will eliminate this dependency issue
