### ISSUE TITLE
Pump/Cgm change should trigger Cage/Sage restart

### ISSUE THREAD

**Issue by gigich** [LoopKit/Loop#1499]
When changing Pump and CGM Cage and Sage should be triggered to automatically set to 0 again. So the user should to set it manually. 
AAPS is able to do that. So it should technical be possible. 
especially on Omnipod, but also other pumps it would be great to see that future.

**Comment by Nightfoxy** [comment]
I would add a few details to this.
1. New pods should add the lot and sequence numbers into the notes of the CAGE entry. This is the info I enter regularly that is needed to call in a pod for replacement. It would be very useful to have it added automatically.
2. Sensor changes should add the transmitter ID to the transmitter ID field in the SAGE entry. This is also needed for calling in sensor/transmitter issues.

**Comment by marionbarker** [comment]
This is a very desirable feature. Please keep it open.

**Comment by ps2** [comment]
This is in testing in the `dev` branch.
