### ISSUE TITLE
Loop not uploading insulin amounts to Nightscout

### ISSUE THREAD

**Issue by olr245b-ns** [LoopKit/Loop#1500]
**Describe the bug**
Insulin amounts are not uploaded to Nightscout. Neither insulin meal bolus nor temp basal rates are displayed in Nightscout. I have checked the raw data in mongodb.com and the insulin amounts are not present. All other Loop data is uploaded as expected.

**Attach an Issue Report**
Attached

**To Reproduce**
Not applicable as this is an automatic process once the Nightscout URL & API secret are entered into Loop

**Expected behavior**
I would expect Nightscout to display meal bolus circle in Nightscout to show a circle; upper part of circle shows carbs grams and lower part of circle shows units of insulin delivered; see screenshots for actual behaviour (upper circle filled with carbs, lower circle empty)

**Screenshots**
See attachments

**Phone**
 iPhone 11 Pro
 14.4.2

**Loop Version**
2.2.4
master source zip downloaded 4/8
[Loop Report 2021-04-10 13_30_58-04_00.zip](https://github.com/LoopKit/Loop/files/6290681/Loop.Report.2021-04-10.13_30_58-04_00.zip)
![Screenshot 2021-04-10 161019](https://user-images.githubusercontent.com/57688136/114283345-4b1c4000-9a17-11eb-8da4-0cb34491fbf6.png)

/2021

**Comment by human911** [comment]
Can you verify the Nightscout features as seen in this wiki.
Your screenshot also show loop isn't connected.

https://nightscout.github.io/nightscout/setup_variables/

**Comment by felixthecat64** [comment]
I am seeing the same behavior.
