### ISSUE TITLE
Significant Miscalculation of IOB and Delivered Insulin

### ISSUE THREAD

**Issue by kenstack** [LoopKit/Loop#1501]
**Describe the bug**
Loop user had a long low and was coming back up.  See screenshot (low had nothing to do with Loop as far as I know).  Loop correctly had zero temped for quite a while, leading to significant negative IOB (expected).  Then, all of a sudden, user noticed IOB has jumped to a positive value.  See screenshot.  Somehow, Loop thought that a very short term basal rate of 196.4U/hr had actually been delivered (not possible obviously) - max basal rate set to 12 u/hr.  This was not a display only issue - this was the actual IOB value / insulin delivered and it persisted, incorrectly thinking there was positive IOB thru 5 hours (DIA).  I've never seen this behavior before, and once the DIA passed things were fine.  Same data was uploaded to NS.  

Note there was an override on a the time. 

I checked res values over the period and obviously this amount was never given.  In fact over that period essentially no insulin was given.  So this means the error in terms of repeating insulin delivered / IOB calculations was constant and persisted even though loop was reading the pump for history.  Just noting this as it may help debugging.

User has been complaining of "Missing Data: Insulin Effects" errors on and off.  Likely happened 2-4 times yesterday.  Rebooting phone seems to help for ones that dont correct, but it is an intermittent issue and usually corrects eventually (though sometimes takes 2-3 loops).  This may have nothing to do with this error, just noting the odd behavior.  I believe @jlucasvt  may have noted this a while ago, but I dont remember if there was a resolution.  

Loop performing normally since.

**Attach an Issue Report**
attached below (could not attach md file had to convert to PDF)

**To Reproduce**
Cannot reproduce 

**Expected behavior**
Calcs agree with actual insulin delievered 

[Loop Report 2021-04-10 033803-0400.pdf](https://github.com/LoopKit/Loop/files/6290724/Loop.Report.2021-04-10.033803-0400.pdf)

**Screenshots**

**Phone**
 - Hardware: XS
 - OS Version: 14

**Loop Version**
 - Version Number: 2.2.4 workspace
 - Repo: LoopKit/Loop

**CGM**
 - Device: G6
 - Manager app: Dexcom

**Pump**
 - Manufacturer: MDT
 - Model: 723
 - Firmware version: VER 2.4A1.1

**Additional context**

[
![IMG_5625](https://user-images.githubusercontent.com/8536751/114283581-6fc4e780-9a18-11eb-8338-db3e8c14b528.PNG)

](url)

**Comment by jlucasvt** [comment]
My issues were directly related to HealthKit data store being corrupted.   My final act was to wipe the loop phone to bare OS and redeploy Loop to phone.  I have not had any IOB or HealthKit data issues since full wipe and OS restore.
