### ISSUE TITLE
Module compiled with Swift 5.3.2. cannot be imported by the Swift 5.4 compiler

### ISSUE THREAD

**Issue by hansdampf01** [LoopKit/Loop#1504]
Hey Guys,

Just trying to rebuild Loop Workspace to implement the latest OrangeLink Patch,
Im on both iOS 14.5 and Xcode 12.5. 
Looks like the Loopkit Module wants a recompile.
<img width="711" alt="2021-04-29_11-43-36" src="https://user-images.githubusercontent.com/55264284/116532494-99b74e80-a8e0-11eb-9d6a-e6ea6e7e6879.png">

Anyone already faced the same?

**Comment by hansdampf01** [comment]
Probably my incompetence again.

**Comment by corbin-miller** [comment]
Not much of an answer, is it.

**Comment by dabear** [comment]
Clean project solves these problems
