### ISSUE TITLE
DanaRS pump support **Looking for somebody to mentor driver development**

### ISSUE THREAD

**Issue by renegadeandy** [LoopKit/Loop#1505]
I would like to request support for DanaRS on loop.

I know there has been 2 other issues opened first in 2018 to discuss the need and desire for DanaRS pump compatibility.

DanaRS is supported fully in Android APS where there is a driver which has been fully coded. I would be interested in adding support for DanaRS (I am a programmer) But I would need help from the community as I have never used Loop (I was an android user and want to switch to iOS).

Has anybody started any level support for DanaRS which I can piggyback on? If not - who is up for helping with a focussed effort on adding this support?

**Comment by 4gra** [comment]
I'd be very willing, but not perhaps the most able. I'd suggest asking on Zulip where a better discussion could be had.

**Comment by elnjensen** [comment]
This isn’t a direct answer to your question, but I just saw [this vulnerability alert](https://us-cert.cisa.gov/ics/advisories/icsma-21-012-01) that includes the RS pumps.   I don’t think it’s a huge cause for concern (security issues exist for old Medtronic pumps, which is what makes them loopable) but useful to be aware of.  It looks like Sooil has issued updated code with a fix, but I don’t know if that affects the ability of the existing Android code to work with the pumps, i.e. if it requires some new coding there for updated pumps. 

As mentioned in previous threads on this, one challenge is finding developers who are interested *and* who can actually get their hands on one of these pumps for testing.

**Comment by renegadeandy** [comment]
@elnjensen A fix is already applied to all firmware versions >=3 which AndroidAPS works with so we should be fine and will keep this in mind!

@4gra terrific! What is Zulip!!!

**Comment by elnjensen** [comment]
https://loop.zulipchat.com/

Discussion forum for Loop development, issues, support, etc. Not as active as the Looped Facebook group, but somewhat more technical on average.

**Comment by renegadeandy** [comment]
Okay added topic there - I suggest we get started with this! How do we begin - shall I just start hacking something together?
