### ISSUE TITLE
Phantom temp basals causing significant miscalculation of IOB

### ISSUE THREAD

**Issue by swebster** [LoopKit/Loop#1511]
**Describe the bug**
Loop is double-counting the boluses I gave my son this morning in the form of very short-lived temporary basal rates. These appear at the same time as I gave him those boluses, massively exceed his permitted maximum basal rate and add up to the equivalent amount of insulin that he was given via boluses. After a few minutes, Loop recalculates IOB, these phantom basals disappear and IOB seems fine, but minutes later they come back again and IOB is twice what it should be. Note that at no point are these phantom basal rates listed in the "Event History".

This means that we are stuck with an open loop for hours, otherwise Loop would suspend his basal until most of this insulin is deemed to have worn off. Of particular concern is that this behaviour is not visible in NightScout (which is just displaying the correct information), so had he been at school today I would have been oblivious to the problem until he had a massive spike after lunch. Presumably, Loop would not only have suspended his basal insulin but would also have recommended next to no bolus insulin for his next meal.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.
[Loop Report 2021-07-07 12-15-32+02-00-1.md](https://github.com/LoopKit/Loop/files/6776437/Loop.Report.2021-07-07.12-15-32%2B02-00-1.md)

**To Reproduce**
This is the only time this has happened. I switched Loop to "open" when my son got up this morning to manually correct his high blood glucose as I knew he would be eating soon. About twenty minutes before he was due to eat I entered the carbs in Loop and gave him a pre-bolus of about 0.5E, but noticed that this had been double-counted. However, Loop seemed to fix this error, so five minutes before he ate I gave him the recommended outstanding bolus amount. Shortly afterwards, Loop started double-counting this bolus as well.

**Expected behavior**
I expect Loop to NOT display these phantom basals, to calculate IOB correctly and to not recommended suspending basal insulin delivery (or to do so automatically when in closed mode!) when it is completely inappropriate.

**Screenshots**
Main screen displaying just the given boluses:
![actual_boluses](https://user-images.githubusercontent.com/1191873/124745873-919f0f00-df20-11eb-8015-feb87f7e529e.jpeg)

Same screen displaying phantom basals (including negative rates after the boluses, bizarrely):
![phantom_basals](https://user-images.githubusercontent.com/1191873/124746010-b5625500-df20-11eb-8aad-32531904a9dd.jpeg)

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 14.6

**Loop Version**
 - Version Number: v2.2.4
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: (unknown; "PI version" 2.9.0, "PM version" 2.9.0, if that helps)

**Additional context**
Is it likely that this issue would be resolved by [this fix](https://github.com/elnjensen/LoopKit/commit/6ffc8db1fbf10cc5668a17fb1df04d0ca4f4bf16)? If so, are there any plans to cherry-pick it for inclusion in the master branch? This seems to be a serious issue that poses a significant risk of hyperglycemia.

In the meantime, are there any suggested workarounds that would prompt Loop to stop miscalculating IOB every few minutes?

**Comment by swebster** [comment]
I should add that force restarting Loop resulted in correct IOB for a couple of minutes, but then the issue recurred.

**Comment by human911** [comment]
@swebster  Yes, This is the fix. 
https://github.com/elnjensen/LoopKit/commit/6ffc8db1fbf10cc5668a17fb1df04d0ca4f4bf16

You can do a workspace build and update the one line of code. 

This will resolve your issue.
