### ISSUE TITLE
Loop dev allows conflicting settings when upgrading

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1518]
**Describe the bug**
Unable to modify Glucose Safety or Correction Range settings in certain situation.
See link to zulipchat: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/dev.20branch.20v2.2E3.2E057/near/247222886

**Attach an Issue Report**
Did not save report (but could add it if desired).

**To Reproduce**
1. Built Loop AB using zip build onto phone (no Loop app installed initially)
2. Deliberately set Suspend Threshold higher than Correction Range using simulator for CGM and pump
3. Build Loop dev (using workspace build) on same phone
4. During onboarding, accept existing settings despite warning messages
5. Loop app appears to run but unable to modify either  Glucose Safety (no action accepted) or Correction Range (app crashes)

**Expected behavior**
Expect either:
1. Refusal to allow Glucose Safety to be higher than Correction Range during onboarding
2. Ability to change either Glucose Safety or Correction Range after they were accepted during onboarding

**Screenshots**
See zulipchat link above.

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 14.7

**Loop Version**
 - Version Number: v2.3.057, clone on 7/24/2021
 - Repo: cloned LoopWorkspace, dev branch

**CGM**
 - simulator

**Pump**
 - simulator

**Additional context**
When connected to mac, halted at
Line 157 of
LoopKit, LoopKitUI, Views, GlucoseRangePicker.swift
Debug message:
```
2021-07-26 08:36:32.356428-0700 Loop[408:14745] [StatusTableViewController] Update net basal to Optional(Loop.NetBasal(rate: -0.8, percent: -1.0, start: 2021-07-26 15:28:18 +0000, end: Optional(2021-07-26 15:58:18 +0000)))
Unable to present. Please file a bug.
Unable to present. Please file a bug.
Swift/arm64-apple-ios.swiftinterface:5643: Fatal error: Range requires lowerBound <= upperBound
2021-07-26 08:40:18.672668-0700 Loop[408:11342] Swift/arm64-apple-ios.swiftinterface:5643: Fatal error: Range requires lowerBound <= upperBound
```

**Comment by ps2** [comment]
Should be fixed with this change: https://github.com/LoopKit/LoopOnboarding/commit/cbe73595a95cd600d43d7faabc280d7441959e56
