### ISSUE TITLE
Loop loses Enlite cgm settings (dev branch)

### ISSUE THREAD

**Issue by Typ1er** [LoopKit/Loop#1520]
I switched from the freeAPS version to the dev version 2 months ago, since then I have to set the cgm every time after a reboot from the iPhone or the restart of the Loop app.
My pump is a Medtronic 554 and as cgm I use the enlite sensor.

Here is another problem with connecting, maybe the two are related.

If I turn flight mode on and off again. If the Loop app gets no more data from the Rileylink, I have to restart the app. After that it works again, I have to set the CGM again.

**Comment by ps2** [comment]
Should be fixed in dev
