### ISSUE TITLE
Dosing strategy description text is cut off in v2.2.5 

### ISSUE THREAD

**Issue by damonbayer** [LoopKit/Loop#1525]
**Describe the bug**
Dosing strategy description text is cut off in v2.2.5.

**To Reproduce**
1. Navigate to "Dosing Strategy" screen in v2.2.5.
2. Depending on chosen dynamic text size, some of the description for the methods may be cutoff.

**Expected behavior**
Full description should be displayed.
![IMG_1394](https://user-images.githubusercontent.com/8095080/129954954-1cbdfacf-1692-44af-bd57-bac742cc2d7c.PNG)
![IMG_1395](https://user-images.githubusercontent.com/8095080/129954972-9e2b2bab-6341-4f84-aef5-d72e28ba98c2.PNG)

**Screenshots**

**Phone**
 - Hardware: iPhone 11
 - OS Version: e.g. iOS 14.7.1

**Loop Version**
 - Version Number: 2.2.5

**Comment by ps2** [comment]
Should be fixed with https://github.com/LoopKit/Loop/commit/003eb14190574cfd2e56170083c300ae80093756
