### ISSUE TITLE
User Returned to Meal Bolus Screen after succesful passcode entry when Bolus Rec changes while on Auth Screen

### ISSUE THREAD

**Issue by mattlumpkin** [LoopKit/Loop#1528]
**Describe the bug**
Caregiver attempts meal bolus on 17 U carb entry. Rec is 4.5 U.  They "Save and Deliver."  They fail Face ID b/c they aren't saved in the phone and they are wearing a mask.  They get prompted for passcode, succeed and then land on the Meal Bolus screen with updated bolus rec, higher than previous. INSTEAD OF landing on Home screen (expected). 

She then completes the cycle again, multiple times attempting to "Save and Deliver."  Multiple carb entries are created with the same time-stamp.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. create carb entry
2.  continue
3. "Save and Deliver"
4. Fail Face ID
5. Wait until new cgm number causes new bolus rec
6. Complete Passcode entry
7. See return to Meal Bolus Screen with updated bolus rec.

**Screenshots**
![Image from iOS (1)](https://user-images.githubusercontent.com/3538520/130132214-76de5050-3c90-4939-a2d2-19ab131fa73e.png)

**Phone**
- iPhone 12 mini, iOS 14.6
With real Rileylink + omnipod and Dexcom CGM

**Loop Version**
Loop Dev Branch - v2.3.0 (57) From 8-14-21

**CGM**
 - Dexcom G6
 - Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Eros

[Loop Report 2021-08-18 20:09:30-07:00.md](https://github.com/LoopKit/Loop/files/7017293/Loop.Report.2021-08-18.20.09.30-07.00.md)

**Comment by mattlumpkin** [comment]
Thanks for the kind attention @ps2.

**Comment by ps2** [comment]
Thanks Matt! Should be fixed with https://github.com/LoopKit/Loop/pull/1526
