### ISSUE TITLE
Double insulin entry on v 2.2.5

### ISSUE THREAD

**Issue by rileylisaa** [LoopKit/Loop#1531]
**Describe the bug**
I built version 2.2.5 this morning and after the build I had to re-enter my pump information. After the pump was re-entered, it double counted my bolus entry that was given before the build from v 2.2.4. I deleted the extra bolus from apple health & momentarily the prediction line was correct, but then went back to the prediction with the double count. The deleted insulin entry has been re-entered. I got 2 issue reports, 1 before I deleted the extra entry and 1 after the extra entry re-appeared.
[Loop Report 2021-08-23 11_36_16-04_00.md](https://github.com/LoopKit/Loop/files/7033303/Loop.Report.2021-08-23.11_36_16-04_00.md)
[Loop Report 2021-08-23 11_52_06-04_00.md](https://github.com/LoopKit/Loop/files/7033335/Loop.Report.2021-08-23.11_52_06-04_00.md)

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**
I expected loop would remember my pump, not double count my insulin entry and not re-enter the insulin entry once I deleted it.

**Screenshots**

**Phone**
 - Hardware: [iPhone 8 Plus]
 - OS Version: [14.7.1]

**Loop Version**
 - Version Number: [2.2.5]
 - Repo: [master]

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [Dexcom App]

**Pump**
 - Manufacturer: [Medtronic]
 - Model: [722]
 - Firmware version: 2.2A1.1

**Additional context**

**Comment by ps2** [comment]
Was the entry only doubled in Apple Health, or was it doubled in Loop in any way?

**Comment by rileylisaa** [comment]
It seems to only be in Apple Health. Posting Screenshots for your review. 
![IMG_8082](https://user-images.githubusercontent.com/48630011/130484357-a38616fb-d08a-47c6-9096-fd6ada5f186d.jpg)
![IMG_8081](https://user-images.githubusercontent.com/48630011/130484367-4d656d52-5118-4e47-a2da-46d553a39809.jpg)
