### ISSUE TITLE
First basal screen for Add Pump allows basal time start other than midnight

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1535]
**Describe the bug**
New Loop user (Patrick Dempsey) entered basal rates and managed to get first rate start time set to 12:30 am (I was able to reproduce this)

**Attach an Issue Report**
Attached below

**To Reproduce**
1. Delete any existing Loop app from the phone
2. Select Omnipod pump
3. Connect RileyLink
4. Enter max basal and max bolus
5. Enter basal rates - You must make the error in this one step
6. Entered a few rates, changed the first row to 12:30 am, hit back on the menu
7. Issue the report attached below (Basal Schedule starts at 1800 sec, not 0 sec)
8. Attempt to modify the starting time of 12:30 to be midnight and cannot adjust the time on the first row

**Expected behavior**
The user interface for basal rates should not allow the start time to be anything other than midnight in the onboarding menu.

**Screenshots**
Please see information in zulipchat:
https://loop.zulipchat.com/#narrow/stream/144111-general/topic/Loop.20v2.2E2.2E5.20Crash/near/251057158

**Phone**
 - several

**Loop Version**
 - master v2.2.5 zip download
 - Repo: [LoopKit/Loop]

**CGM**
 - Device: N/A

**Pump**
 - Onboarding to Omnipod
 - I was also able to do this with the simulator pump

[Loop Report 2021-08-28 172205-0700.md](https://github.com/LoopKit/Loop/files/7071701/Loop.Report.2021-08-28.172205-0700.md)

**Comment by itsmojo** [comment]
I tried running v2.2.4 on old iPhone (I was unable to build the v2.2.4 simulator) and was able to reproduce this same behavior. The initial Add Pump procedure which sets basal program for an Omnipod doesn't look any different than it does when running v2.2.5. Thus it appears that this is actually a long standing bug when creating the initial basal program and that there is no new onboard procedure in v2.2.5.

**Comment by itsmojo** [comment]
A basal schedule not starting at midnight can be created when setting up the initial basal schedule by running Add Pump on simulated iPhone and then selecting any of the Omnipod, Medtronic, or Simulator pump types. I don't have permissions to update the issue title to something more appropriate.

**Comment by ps2** [comment]
Yes, this is a long standing issue with the old basal schedule editor. I believe the new one does not allow this kind of behavior.

**Comment by marionbarker** [comment]
Not a valid scenario, but it did accept the bogus basal rates carried over from non-dev Loop.
It will not allow me to modify the first row to midnight. (The editor shows midnight, but row doesn't update the time.)
I'll delete the app and start fresh.

**Comment by marionbarker** [comment]
This is fixed.
