### ISSUE TITLE
IOB issue with 2.2.5

### ISSUE THREAD

**Issue by jenhamm** [LoopKit/Loop#1538]
As you can see from the insulin delivery, she should have about 12 units on board right now, but it is showing only 2.49 on board. This is the latest version - 2.2.5

![IMG_7019](https://user-images.githubusercontent.com/52714569/131555200-c7fc87c7-c83f-43a6-81fc-38fb5e02eff5.PNG
[Diagnostic report.txt](https://github.com/LoopKit/Loop/files/7086033/Diagnostic.report.txt)
)
![IMG_7022](https://user-images.githubusercontent.com/52714569/131555205-8d959fa6-a5fb-427e-a6bc-a77f4ea47dd1.PNG)
![IMG_7023](https://user-images.githubusercontent.com/52714569/131555209-48a32945-fa66-49c4-9d80-6c7f85126bd0.PNG)
![IMG_D5316BEF7236-1](https://user-images.githubusercontent.com/52714569/131555212-1ceabf28-1ada-4cde-a2dd-e188488df186.JPEG)

[Diagnostic report.txt](https://github.com/LoopKit/Loop/files/7086037/Diagnostic.report.txt)

**Comment by ps2** [comment]
Please update to https://github.com/LoopKit/Loop/releases/tag/v2.2.6, there is a fix for this there.
