### ISSUE TITLE
Excessive insulin delivered by watch

### ISSUE THREAD

**Issue by Trpl7ca** [LoopKit/Loop#1542]
<img width="1772" alt="Screen Shot 2021-09-06 at 7 36 59 AM" src="https://user-images.githubusercontent.com/52380252/132245720-4548abbd-38fa-43ee-bcf6-52ba2e1a54ba.png">
<img width="1603" alt="Screen Shot 2021-09-06 at 7 38 03 AM" src="https://user-images.githubusercontent.com/52380252/132245731-604a510d-691d-4eb1-ab68-f94119b2612a.png">
<img width="1599" alt="Screen Shot 2021-09-06 at 7 40 31 AM" src="https://user-images.githubusercontent.com/52380252/132245738-4e8a616b-0789-404a-a586-cf09b5bfa7c2.png">
https://github.com/LoopKit/Loop/files/7113655/podState_Trpl7ca_20210901_1928_2.csv

**Comment by Trpl7ca** [comment]
I was using watch to enter carbs and bolus and ended up with over 20 units of insulin, way more than I needed. I thought it was somehow my fault but maybe not. I did not grab an issue report and have not seen a reoccurrence. Also 2.2.5

**Comment by Trpl7ca** [comment]
Did not get screen shots as it was a social event and my purpose of using the watch was to be discreet. Low alarm and noticed an enormous amount of insulin was delivered. I took issue report. Then headed to desert bar for 3 chocolate chip cookies and a piece of cake :) That worked and I never got below 65 so not as severe as arlego. As I recall I was blousing with watch and kept getting bolus failed and used the watch to retry. That happened several times so maybe that was a problem, Actually getting bolus but recognizing on watch. Again social setting trying not to be freaked. Thanks for you work, nothing is perfect and stuff happens.

**Comment by ps2** [comment]
It's possible this was fixed in https://github.com/LoopKit/Loop/releases/tag/v2.2.6.

**Comment by Trpl7ca** [comment]
@ps2 Building now, do we want HK read/write on or off?

**Comment by ps2** [comment]
You want to keep it on. Turning it off should no longer cause an immediate issue, but released Loop versions are designed to have write access to Apple Health

**Comment by marionbarker** [comment]
Only the author of the issue or the developers who own the repository have privileges to close an issue once it is opened. 
If you believe your issue has been resolved, please consider closing it (with or without comment) - that saves time for the developers.

**Comment by marionbarker** [comment]
This may be related to the Bolus screen not showing up after Carb entry problem with the Watch.
Please see two issues posted under the loopnlearn LoopWorkstatus fork.
* [Watch: Bolus not following carb entry](https://github.com/loopnlearn/LoopWorkspace/issues/15)
* [Carb Entry/Delete Problem](https://github.com/loopnlearn/LoopWorkspace/issues/14)

Note - I reproduced both of these problem with Loop v2.2.6 so I believe it is in the common portions of those code bases.

**Comment by Trpl7ca** [comment]
I think it has to do with timing of watch sync with phone.  if using watch to enter carbs and bolus the recommended bolus does not update until a sync with watch. If AB is being used then you could get an automatic bolus before the bolus recommendation is updated on watch and if you then use that amount to bolus from watch you just got more insulin than desired. Maybe there could be a way to see timing of next sync on watch.

**Comment by Trpl7ca** [comment]
This is what I think happened. If you make a carb entry on watch or phone, you will get a recommended bolus amount. EX. 25 carbs recommend 5 units.  If you then do a partial ex 2.5 units, bolus from the phone, the bolus is not accounted for on the watch until the next cycle of loop. So if you then bolus from the watch before the cycle you would see the same original recommended bolus amount suggested, 5 g. If you were not keeping track of that you could get more insulin than desired.  
Going the other way bolus from phone the amounts are updated immediately on the watch.
Marion Barker has suggested a work around. if you select any override it will force the watch to sync and match. That seems to work for me.
