### ISSUE TITLE
CGM reporting higher than actual reading

### ISSUE THREAD

**Issue by Encrypt512bit** [LoopKit/Loop#1546]
[loop report 2021-09-10 224752-0400.txt](https://github.com/LoopKit/Loop/files/7147093/loop.report.2021-09-10.224752-0400.txt)
![D2E81415-F763-4489-9100-DEE4C7CEC044](https://user-images.githubusercontent.com/90489463/132933640-58231611-9881-4bbb-99a7-fda239b796d0.png)
**Describe the bug**
Inside the main screen of loop, my CGM is displaying at the top 179, while the reading in the chart is saying the actual reading, which is 134. I’m worried that loop is suggesting a basal rate based off the number at the top and not in the chart. 

This problem occurred after my child “accidentally” changed the time settings on my phone and all my data from loop disappeared. I ended up deleting the application and rebuilding it onto my phone.  

even after deleting and rebuilding the application, 179 still shows at the top like it’s stuck. 
 
**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Change your phone time date 
2. Go back to loop
3. CGM data at top of screen sticks to the last value. 

**Expected behavior**
Data from the CGM should appear accurate to what the chart is displaying. 

**Screenshots**

**Phone**
 - Hardware: iPhone 12 Pro
 - OS Version: iOS 14.7.1

**Loop Version**
 - Version Number: 2.2.6
 - Repo: LoopKit/Loop master

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod 
 - Model: 
 - Firmware version: 

**Additional context**

**Comment by Encrypt512bit** [comment]
Upon checking health app data, it wrote values for future dates to my health data which is why 179 stayed constant. I deleted the health data generated with future dates / times and it cleared things up.

**Comment by Encrypt512bit** [comment]
What is more interesting is that the Dexcom app never wrote the future date/times my phone had been changed to, is there a way to make the application pull from a UTC time server?

**Comment by elnjensen** [comment]
The Dexcom app is purposely designed to make it difficult/impossible for other apps to use its CGM data in real time - it only writes data to Health with a three-hour delay.  Loop works around this by eavesdropping on each Bluetooth CGM value as it comes in.  Those are written to Health, but removed by Loop after three hours when they are replaced by the Dexcom-written values. 

Regarding the time server, Loop in general tries to avoid duplicating identical functionality that already exists on the phone, and of course iOS can sync the system time - as long as no one turns off that setting!  If you want to prevent that from being changed, you can do so in [Screen Time](https://protectyoungeyes.com/12-ingenious-screen-time-hacks-how-to-beat-them/). 

If this addresses your issue, maybe mark it as “closed”?

**Comment by ps2** [comment]
Just adding a note that the dev branch does have an NTP checker and warning alert if you change your phone time.  If you are a parent, and your kid may try changing the time, know that if you set up parental controls and enable screen time, then iOS will not allow the kid to change the time on their phone.
