### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by frankstutz** [LoopKit/Loop#1548]
**Describe the bug**
Unable to compile with Xcode 13 with "Command PhaseScriptExecution failed with a nonzero exit [code"](url)

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**
When I try to compile with Xcode 13 for IOS 15/iWatch 8 it dies very early in the process with "Command PhaseScriptExecution failed with a nonzero exit code".   See the attached build target Cartile for reference

[Build target Cartfile_2021-09-21T11-19-54.txt](https://github.com/LoopKit/Loop/files/7205382/Build.target.Cartfile_2021-09-21T11-19-54.txt)

I tried to compile with Debug vs Release but no difference.  Also here's git diff for reference:

[git_diff_from_master.txt](https://github.com/LoopKit/Loop/files/7205410/git_diff_from_master.txt)

**Phone**
 - Hardware: iPhone XR (or any other version)
 - OS Version: 15

**Loop Version**
 - Version Number: Master from Git or ZIP
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by frankstutz** [comment]
Also forgot to added did standard clean up (build clean up),
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf ~/Library/Caches/org.carthage.CarthageKit

**Comment by frankstutz** [comment]
Closing ticket, as lurked on what ps2 did with LoopWorkspace and see that needed to compile with that as the primary source for Loop

**Comment by vallard** [comment]
I didn't see what ps2 did, but was able to get past it by using part of the script from https://github.com/Carthage/Carthage/issues/3201#issuecomment-859516176.  Inside of xcode 13 Loop/Scripts/carthage, I made mine look like this: 

```
# carthage.sh
# Usage example: ./carthage.sh build --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.

CURRENT_XCODE_VERSION="$(xcodebuild -version | grep "Xcode" | cut -d' ' -f2 | cut -d'.' -f1)00"
CURRENT_XCODE_BUILD=$(xcodebuild -version | grep "Build version" | cut -d' ' -f3)
echo "EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_${CURRENT_XCODE_VERSION}__BUILD_${CURRENT_XCODE_BUILD} = arm64 arm64e armv7 armv7s armv6 armv8" >> $xcconfig
 
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_'${CURRENT_XCODE_VERSION}' = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_$(XCODE_VERSION_MAJOR)__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
"${SRCROOT}/bin/carthage" "$@"
```

**Comment by Mairead101** [comment]
> Closing ticket, as lurked on what ps2 did with LoopWorkspace and see that needed to compile with that as the primary source for Loop

Any chance you could point me in the direction of ps2's work that resolved this for you? I am running into the same error immediately upon trying to build, and for some reason I do not have Loop(Workspace) available as an option with this particular Loop folder. Xcode 13.2, MacOS 11.15.1, iOS 15.2

**Comment by Forterc** [comment]
One reason you could get this error is if you're choosing the "Loop" Project instead of "Loop Workspace" in the XCode build target.
