### ISSUE TITLE
Feature Request: Loop settings Import/Export functionality

### ISSUE THREAD

**Issue by becksen** [LoopKit/Loop#1549]
**Describe the Feature**
It is basically a feature request. Didn't find a bette place. As it is possible that during testing of different branches the settings which might have consumed some time gets lost. In order being able to recover quickly the Loop setting I'm suggesting to build an export/import functionality where all configuration settings can be backed-up and imported in case the config is gone

**Expected behavior**
Create a new area Import/Export in the settings menu and have two items, one for export and one for import. Saving the file locally on the phone and having a naming convention which is considering date and time.

**Comment by Nightfoxy** [comment]
This feature exists in FreeAPS and would be great to merge or edit for use in Loop.

**Comment by Willbumster** [comment]
Great idea 
R

**Comment by marionbarker** [comment]
This would be a welcome addition to Loop-dev.
Use cases:
* females who have regular menstrual cycles and want to load profiles during different days
* shift workers who may need a different pattern for shifts versus days off
* students who need a different pattern during the school week vs the weekend
* travelers who know a different pattern will be required during vacation or work travel

**Comment by ps2** [comment]
backup/restore is a big use case here

**Comment by marionbarker** [comment]
Bumping this up. This feature recently requested on facebook regarding menstrual cycle changes.

**Comment by Trpl7ca** [comment]
Now that some of us do not use Nightscout, this would speed up set-up on new versions. Hope it is considered.

**Comment by Laura-Zh** [comment]
Bumping this up. I use this feature of profile switching in FreeAPS very frequently. It would be great to see this incorporated into Loop 3. Use case:

- Multiple profiles with menstrual cycle hormones through the month ( I use 5 profiles currently with different Basal and ISF). It is incredibly handy to switch these seamlessly. My needs change on a dime eg. most recently I had to switch profiles in the middle of the night. This feature in FreeAPS makes switching safe, easy, simple and hassle free. It also mitigates safety concerns.For instance I could easily see entering a mistaken basal rate or ISF in the night half awake if I had to search through my phone notes app to find my settings and input new settings. Without profile switching there is a greater chance of entering an incorrect setting while half-asleep that could cause dangerous lows. Having a labeled setting I can import allows me to safely select my new profile quickly and without concern for entering wrong settings. 

- Parents with kids with different school vs weekend, summer/camp vs school year setting

- Work week vs weekend for adults with different settings

**Comment by Mia021** [comment]
Bumping up ✌🏻
More and more user coming back to Loop 3 from freeAPS continue to request this feature that looks to be very useful for many.
Woman during their cycles
Shift workers
Kids and students 
Too many would take advantage of it to facilitate their daily lives 🙏🏻

**Comment by culdeus** [comment]
Also wanted to echo this and bring it up. As many users of Dash have not purchased a PDM, it would be highly beneficial to have a backup phone setting that is cloud-based in the event of a lost or damaged phone.

Others have already highlighted the clear benefit of having separate weekday and weekend settings, and I would like to echo their sentiment.

Furthermore, the current method for enacting overrides may not be the most efficient. Instead of a time-out or a percentage change of the current settings, it would make more sense for long-term endurance sports to have a pure setting that directly changes the current settings directly rather than some fraction of the current settings.  

This feature is one of the key reasons I have switched from APS to Loop3, but have since moved back to APS.

**Comment by afshopify** [comment]
Weekends - vastly different setups for children with different activity levels, different stress/anxiety levels, etc. Saturday and Sunday look nothing like M-F for school aged children.

**Comment by afshopify** [comment]
Work schedules - those who have more grueling lines of work including physical labor, “on your feet” 8+ hour shifts with lots of movement/heavy lifting/walking/exercise - these days look nothing like “days off” which are likely much more restful to recharge for the high activity work days.

**Comment by afshopify** [comment]
Athletes - perhaps 4 days a week filled with games and intense practice sessions that impact insulin needs for an extended (~24 hr) period even after the session completes.

The ~3 other recovery days each week then have drastically different insulin profiles.

**Comment by afshopify** [comment]
Travel days for people who travel often (for work or pleasure) - travel days have vastly different needs of insulin - example drivers of changes in insulin provide include different stress levels while traveling (perhaps higher for work or lower for vacation), different mobility levels while traveling (again, may be higher or lower).

**Comment by afshopify** [comment]
People attempting to tune settings - may wish to save off profiles when they *think* they’re close but want to continue making a change. Or perhaps safe a baseline profile before making changes.

I have 3-5 screen shots saved of Loop settings in “shared albums” on my iPhone for instance for “September Great Loop Settings” and “October Great Loop Settings” and so on, as baselines in case I need to revert at some point. Saving a profile would be a much more effective and appropriate way to do this.

**Comment by bjorkert** [comment]
+1

**Comment by LandlockedJack** [comment]
+2Sent from my iPhoneOn Feb 19, 2023, at 10:51 AM, Jonas Björkert ***@***.***> wrote:﻿
+1

**Comment by Laura-Zh** [comment]
Bumping up. Exercise like swimming where overides don’t work as phone out of range is another example of why having alternate profiles would be so helpful. This way a user could have a dedicated exercise profile they can easily enact for those exercises where OR don’t work.

**Comment by marionbarker** [comment]
This issue is still important and should remain open. PR #2002 is an attempt at solving this, but needs more work.

**Comment by Laura-Zh** [comment]
Agreed. Still relevant. I’m still waiting to use Loop because this feature isn’t offered.

**Comment by marionbarker** [comment]
This issue should remain open until the work started with #2002 is completed.
