### ISSUE TITLE
building on Xcode13 for iOS 15 yields error building Amplitude

### ISSUE THREAD

**Issue by vnephologist** [LoopKit/Loop#1552]
**Describe the bug**

bin % /usr/bin/xcrun lipo -create /Users/andy.daniel/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Intermediates.noindex/ArchiveIntermediates/Amplitude_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude /Users/andy.daniel/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude -output /Users/andy.daniel/Downloads/BuildLoop/Loop-Master-210925-1400/LoopWorkspace/Loop/Carthage/Build/iOS/Amplitude.framework/Amplitude
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/andy.daniel/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Intermediates.noindex/ArchiveIntermediates/Amplitude_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude and /Users/andy.daniel/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude have the same architectures (arm64) and can't be in the same fat output file

**Screenshots**
<img width="657" alt="image" src="https://user-images.githubusercontent.com/9338647/134817632-3cf059c4-0ebe-4a2a-bba0-7c9c9ffa622f.png">

**Phone**
 - Hardware: iPhone 13 mini
 - OS Version: iOS 15

**Loop Version**
 - Version Number: Loop-Master-210925-1400
 - Repo: LoopKit/Loop

I have tried removing Carthage, removing all cache, and even uninstalling Xcode and re-installing.

**Comment by marionbarker** [comment]
Carthage no longer works with Xcode 13 (required for iOS 13).  You will need to use the workspace build method.

Please check LoopDocs.  Trying to keep up with the iOS 15 flurry - docs haven't been fully updated, so not all info is consistent, but this should help.

https://loopkit.github.io/loopdocs/build/step13/#xcode-13-ios-15-changes

**Comment by marionbarker** [comment]
Only the author of the issue or the developers who own the repository have privileges to close an issue once it is opened.
If you believe your issue has been resolved, please consider closing it (with or without comment) - that saves time for the developers.

**Comment by vnephologist** [comment]
@marionbarker I’m using workspace method via loopandlearn script.

**Comment by marionbarker** [comment]
Select Loop(Workspace) at top left of Xcode. Item with Red 2 in this graphic. If you use the build-select script as suggested, the graphic is automatically displayed. 
 
https://www.loopandlearn.org/workspace-build-loop/

**Comment by vnephologist** [comment]
My sincere apologies @marionbarker. ID10T error here. I totally overlooked that specific selection!
