### ISSUE TITLE
Find devices option is missing in the orangelink pro menu

### ISSUE THREAD

**Issue by djh2020** [LoopKit/Loop#1558]
According to the [rileylink / orangelink pro documentation](https://getrileylink.org/product/orangelink) there should be a "find devices" option in the orangelink pro menu.  There is even a screenshot that shows that option.  However it is missing in the latest 2.2.6 build
![Screen Shot 2021-10-07 at 1 30 23 PM](https://user-images.githubusercontent.com/6467508/136458231-3a990eae-cc36-40b1-b9a7-e53e4393cb4f.png)
.

**Comment by marionbarker** [comment]
There is a patch found here. It adds the Find Devices for OL Pro.

https://github.com/ps2/rileylink_ios/issues/686

**Comment by marionbarker** [comment]
In addition to the patch listed above for Loop master.  This has been fixed for Loop-dev.  
Please close this issue.
