### ISSUE TITLE
Developing a carb suggestion pop up

### ISSUE THREAD

**Issue by ddaniels1** [LoopKit/Loop#156]
I suggest we develop a a pop up warning when impending hypoglycemia based on the prediction line is within 45 minutes. Then suggest a number of carbs to treat with to stay in target range based on G needed = (target-predicted)/(ISF/I:C). 

THis would allow us to be more aggressive on bolusing for a meal to prevent the spike while cushioning the crash in a way not possible with insulin suspension alone, especially in young kids because the basal:bolus ratio is slanted to a 25:75 instead more like 50:50 and therefore low temping doesn't help prevent hypos as much as it does in adults.  even in adults with a large meal and potential for inaccuracy in insulin dosing. A planned "pre low treatment" as above will be much more effective than taking carbs late and would likely help improve overall glycemic control. Thoughts?

**Comment by CrushingT1D** [comment]
I agree with adding an alert for carb correction as long as there is a way to dismiss it with no action and have it go away for 1 hour or some configurable time.
