### ISSUE TITLE
Rileylink Bluetooth Issue

### ISSUE THREAD

**Issue by StephanieAllene** [LoopKit/Loop#1560]
Hi there- 
I did a site change last night via loop. Since that site change, I have had a red loop.  My rileylink is no longer showing up as a device on my loop pump screen and is no longer showing up in my bluetooth devices on my phone, however, the green light is still on on the rileylink.  When I turn the rileylink power switch off/on, I get a quick flash of a blue light and the green light stays on.  Help please!  How do I put my rileylink into pairing mode to reconnect the bluetooth?

**Comment by Bryn4316** [comment]
What was the resolution?
