### ISSUE TITLE
Loop app shows pump suspended when unsuspended from pump and looping stops

### ISSUE THREAD

**Issue by jenslade5** [LoopKit/Loop#1563]
**Describe the bug**
When the minimed pump is suspended, it registers on the app. When the pump is unsuspended from the pump, it will not register on the app. When realized and unsuspended from the app, the insulin calculated is incorrect for food or high blood sugar because the app thinks the pump has been suspended 

**Attach an Issue Report**
None

**To Reproduce**
1. Suspend pump
2. Unsuspended pump from pump
3. Unsuspended does not register on app
4. Manually have to unsuspended on app

**Expected behavior**
Unsuspend on pump, pump will register as unsuspended on app. This is new and has been happening since 2.2.4 version that I’m aware of..

**Screenshots**

**Phone**
 - Hardware: [iPhone XR and 11]
 - OS Version: [iOS 14.8]

**Loop Version**
 - Version Number: [2.2.6]
 - Repo: [?? LoopKit/Loop, jenslade5 is my Username?]

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [Dexcom App]

**Pump**
 - Manufacturer: [Medtronic]
 - Model: [722]
 - Firmware version: [2.4A 1.1]

**Additional context**

**Comment by elnjensen** [comment]
Thanks for noting this.   This is true on the current dev branch as well, and I had been meaning to file an issue, so thanks for reporting it.

**Comment by jenslade5** [comment]
Thank you!  This one is strange to me because it didn’t happen before 2.2.4 that I can remember. I really appreciate you and the team that keeps all this working for us. It’s an incredible program and I’m very thankful. 
Have a great rest of your weekend!

Sent from Yahoo Mail for iPhone


On Saturday, October 30, 2021, 10:00 AM, Eric Jensen ***@***.***> wrote:




Thanks for noting this. This is true on the current dev branch as well, and I had been meaning to file an issue, so thanks for reporting it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yogary9** [comment]
Yes, thanks for filing.  This behavior started for me sometime within the last year after I updated.  Quite annoying as sometimes I forget to double check the Loop app to unsuspend and then I end up inadvertently Open Looped for a long  time.  I'm using Medtronic 523 vw 2.4A.  Attaching an Issue Report taken while Loop is in this "Pump is Suspended" state but the pump is not suspended.  Scanning the Issue Report, I also find it peculiar that it says "useMySentry: true" but I do not have MySentry enabled in the Loop app UI.
[Issue 1563 Loop Shows Suspended But Pump Not Suspended.md](https://github.com/LoopKit/Loop/files/7533334/Issue.1563.Loop.Shows.Suspended.But.Pump.Not.Suspended.md)
