### ISSUE TITLE
Red loop all the time 

### ISSUE THREAD

**Issue by edurnegopegui** [LoopKit/Loop#1565]
hi all 
I hope you can help me. I’m quite desperate. 

Pump model Medtronic 754, now 554
Iphone Xs 
ios 14.7.1
Dexcom g6
Loop (Automatic Bolusing) v2.2.4

This error has been happening to me for the last year like once a month, in a day two or three times. Then it went back to normal.
But now it doesn’t go away. 2 days ago my loop started being red again and again. I restart rileylink manually and turn my Bluetooth off and on and then it goes green. But after 20 minutes, it goes red again. I’ve tried changing to my brand new backup rileylink, and my backup pump, the problem persists. After 20 minutes it goes red. Is this a problem with my phone? I haven’t upgraded software yet, I am in 14.7.1. Please help me! I feel very insecure going to sleep and having had red circle for 6 hours. 

Regards

**Comment by elnjensen** [comment]
Look at step 3 in the docs here, under the “pump is not responding” section, to make sure that you have MySentry set up properly: https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/#pump-is-not-responding

**Comment by edurnegopegui** [comment]
Thank you for your time.
I was very hopeful with this, as apparently there was a device in my 554 pump on the top of the list.
I have followed mysentry directions. Last message was, success!

unfortunately, after two hours, loop is red again. 
I’ve tried again mysentry. 

Now it’s given me this error:
On your pump, go to the Find Device screen and select "Find Device".

Main Menu >
Utilities >
Connect Devices >
Other Devices >
On >
Find Device

deviceError(RileyLinkBLEKit.RileyLinkDeviceError.peripheralManagerError(RileyLinkBLEKit.PeripheralManagerError.timeout))

please help!!

**Comment by codelinx** [comment]
I think this should be closed.🙂
