### ISSUE TITLE
Phone restart loses omnipod settings

### ISSUE THREAD

**Issue by loopguy90** [LoopKit/Loop#1566]
**Describe the bug**
I restarted my iPhone and lost the settings for a pod I paired successfully yesterday. The pod worked fine and loop connected for a day until I restarted my phone. The pod is still active but is only giving my basal only. I cannot bolus or run loop basals.![image](https://user-images.githubusercontent.com/93505591/139622989-341e3797-d098-419d-a548-1b77c1eba255.png)

**Attach an Issue Report**
Attached
[Loop Report 2021-10-31 090348-0700 (1).md](https://github.com/LoopKit/Loop/files/7450821/Loop.Report.2021-10-31.090348-0700.1.md)

**To Reproduce**

1. Restart iphone.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/93505591/139622989-341e3797-d098-419d-a548-1b77c1eba255.png)

Hardware: iphone Xs Max
 - OS Version: ios 14.7.1

**Loop Version**
 - Version Number: 2.2.4
 - Repo: loop master

**CGM**
 - Device: dexcom g6
 - Manager app: Dexcom App 

**Pump**
 - Manufacturer: omnipod eros

I've never experienced this issue before.

**Comment by mkitchingh** [comment]
FYI, nice documentation and data capture on this.

**Comment by ps2** [comment]
Fix attempt here: https://github.com/LoopKit/Loop/pull/1702

**Comment by Hencowitz** [comment]
Is there a way to merge this in to my current build, without updating Dev
completely?  I’m trying to keep my version stale from about a month ago.  I
 fearful of this happening to my daughter’s when I’m out of state
traveling.
