### ISSUE TITLE
Apple Watch series 5 OS 8.0 failed to install loop v2.2.4

### ISSUE THREAD

**Issue by huangzhidao** [LoopKit/Loop#1567]
I successfully built the loop on my iPhone and watch and used it normally. When I restore the data from the watch, when my friend’s iPhone is paired with the watch, it shows that the loop cannot be installed.

Tip: this APP could not be installed at this time, could not install at this time

How can I solve this problem and ask everyone for help!

**Comment by gigich** [comment]
Watch has to be paired to the same phone as loop was builded. It has to be trusted to the mac as well. Rebuild with paired and trusted watch
