### ISSUE TITLE
Loop stops obtaining dexcom data resulting in red loops

### ISSUE THREAD

**Issue by jmphillips33** [LoopKit/Loop#1568]
**Describe the bug**
Loop randomly stops getting dexcom data from the transmitter resulting in red loops and no looping for many hours. We get a yellow exclamation point where the dexcom number should be displayed. We have no share credentials entered. Loop doesn't seem to attempt to reconnect to transmitter even when transmitter is in range. Dexcom app displays data the whole time. This seems to happen at any time of day. We have run through all of the troubleshooting steps. This began after we updated our loop to 2.2.6.

**Attach an Issue Report**
I have the report, its really long. Is there a specific part that would be helpful?

**To Reproduce**
I am not sure how to reproduce this as it happens randomly on both of our loop setups.

**Screenshots**
I have taken many screenshots that I can post if there is one that would be helpful. 

**Phone**
 - Hardware: iphone 11 and iphone 12 mini
 - OS Version: 14.8

**Loop Version**
 - Version Number: 2.2.6

**CGM**
 - Device: DexcomG6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Comment by bjornoleh** [comment]
@jmphillips33, I believe you should attach the whole Issue Report file here.

@marionbarker, perhaps you could parse the Issue Report when it lands here?
