### ISSUE TITLE
error: ShareClient.ShareError.dataError(reason: "Failed to decode SGVs as array after trying to reauth: ")))

### ISSUE THREAD

**Issue by ronniereed** [LoopKit/Loop#1569]
Loop has been red and the error is : error: ShareClient.ShareError.dataError(reason: "Failed to decode SGVs as array after trying to reauth: ")))

I have rebooted phone, app, RL and deleted NS from Loop app and still no luck.
[Loop Report 2021-11-08 05_25_16-08_00.md](https://github.com/LoopKit/Loop/files/7497402/Loop.Report.2021-11-08.05_25_16-08_00.md)
.

**Comment by marionbarker** [comment]
Answered in zulipchat:
https://loop.zulipchat.com/#narrow/stream/144111-general/topic/Error/near/260675503

Remove your share client credentials.

If this solves your problem, please close this issue.
