### ISSUE TITLE
error in WatchApp Extension pops up when I try to build Xcode

### ISSUE THREAD

**Issue by tkht1d** [LoopKit/Loop#1571]
When I try to build LoopWorkspace on Xcode, the following message shows up:

Entitlements file "WatchApp Extension.entitlements" was modified during the build, which is not supported. You can disable this error by setting 'CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION' to 'YES', however this may cause the built product's code signature or provisioning profile to contain incorrect entitlements.

I'm not sure how to fix this, although I am the only one experiencing this or there is a step I'm missing or everyone has already figured this out because I haven't seen an issue similar, if I'm correct.

Loop version: 2.2.6 Master
device: iPhone 12 mini
Xcode version: 13.0

Thanks for any help anyone can provide me with!

**Comment by marionbarker** [comment]
Please see build errors help in LoopDocs.
https://loopkit.github.io/loopdocs/build/build_errors/#xcode-13-indexing-not-finished-watchapp-extension-entitlements

Then please close this issue.  Thanks much.

**Comment by tkht1d** [comment]
thank you!
