### ISSUE TITLE
loop code will not download from terminal

### ISSUE THREAD

**Issue by cgeye** [LoopKit/Loop#1573]
**Describe the bug**<img width="583" alt="Screen Shot 2021-11-22 at 6 22 02 PM" src="https://user-images.githubusercontent.com/59522556/142954287-1e1b96f8-6212-40d6-bda6-2658db3190bb.png">What I expect to see is no errors present after starting the download post command inputs into Terminal. What I see is a error stating that the active developer path does not exist. This is despite verifying the developer account is active and assigned to the correct places in Xcode. I am not a new looper but I am new to the current download process. 

**Attach an Issue Report**
I have no access to the loop app as it is saying it is not available in similar fashion to the issues others have had. 

**To Reproduce**
1. Copy the command prompt into the terminal window from the Loopkit website.
2. Agree to the risk agreement. 
3. Select the build loop option.

**Expected behavior**
I expected to be able to download the code and open Xcode, this did not happen. 

**Screenshots**
<img width="583" alt="Screen Shot 2021-11-22 at 6 22 02 PM" src="https://user-images.githubusercontent.com/59522556/142954356-7a0579e8-d80f-4544-98a9-819681498136.png">

**Phone**
 - Hardware: [ iPhone 12]
 - OS Version: [iOS 14.8.1]

**Loop Version**
 - Version Number: [N/A]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [Dexcom App]

**Pump**
 - Manufacturer: [OmniPod]
 - Model: [Eros?]
 - Firmware version: [?]

**Additional context**
Computer used to download is an iMac with os: [Monterey 12.0.1]
Xcode version: [13.1]

**Comment by elnjensen** [comment]
Have you tried running `xcode-select  --install` as suggested in the error message?  What does that do?

**Comment by cgeye** [comment]
I was able to figure it out using that and a few other commands I found, thank you very much!

**Comment by elnjensen** [comment]
Great!  If your problem is resolved, could you please close this issue?  Thanks!
