### ISSUE TITLE
Loop Crashes When Entering Carbs in Open Loop Mode

### ISSUE THREAD

**Issue by gestrich** [LoopKit/Loop#1574]
**Describe the bug**

With fresh install of Loop dev, it will crash in open Loop mode when tapping the "+" button to add carbs. This occurred for my myself another Loop dev user. Also, maybe related, you can't delete carb entries from the Carbohydrates view while in open loop.

**To Reproduce**
1. Turn on open Loop.
2. Open Carbohydrates view.
3. Tap the "+" button
4. Loop Crashes

**Screenshots**

![Screen Shot 2021-11-30 at 7 10 01 AM](https://user-images.githubusercontent.com/3207996/144044913-ff9098a5-c73b-4e46-87da-57e4fdc774fd.jpg)

**Phone**
 - Hardware: iPhone Xs
 - OS Version: 15.1

**Loop Version**
 - Version Number: Dev Workspace commit `6e3fcfac632aa28d55c2b5dc156b1525c4b2b01e`, Loop Commit: `75db2fed403373e5caa65b54227c79deac72e64f`
 - Repo: LoopKit/Loop

**CGM**
 - Device: Simulator
 - Manager app: Simulator

**Pump**
 - Manufacturer: Simulator
 - Model: Simulator
 - Firmware version: Simulator

**Comment by gestrich** [comment]
The fix may be something like this. It seems to be missing the environment object.

```
diff --git a/Loop/View Controllers/CarbAbsorptionViewController.swift b/Loop/View Controllers/CarbAbsorptionViewController.swift
index 5baf9dc4..441114f5 100644
--- a/Loop/View Controllers/CarbAbsorptionViewController.swift  
+++ b/Loop/View Controllers/CarbAbsorptionViewController.swift  
@@ -513,7 +513,7 @@ final class CarbAbsorptionViewController: LoopChartsTableViewController, Identif
             navigationWrapper = UINavigationController(rootViewController: carbEntryViewController)
         } else {
             let viewModel = SimpleBolusViewModel(delegate: deviceManager, displayMealEntry: true)
-            let bolusEntryView = SimpleBolusView(viewModel: viewModel)
+            let bolusEntryView = SimpleBolusView(viewModel: viewModel).environmentObject(DisplayGlucoseUnitObservable(displayGlucoseUnit: .milligramsPerDeciliter))
             let hostingController = DismissibleHostingController(rootView: bolusEntryView, isModalInPresentation: false)
             navigationWrapper = UINavigationController(rootViewController: hostingController)
             hostingController.navigationItem.leftBarButtonItem = UIBarButtonItem(barButtonSystemItem: .cancel, target: navigationWrapper, action: #selector(dismissWithAnimation))
```

**Comment by ps2** [comment]
Just pushed a fix to dev. Thanks for reporting.
