### ISSUE TITLE
Comman PhaseScriptExecution Failed with a nonzeroexit code 

### ISSUE THREAD

**Issue by EllaBesserer** [LoopKit/Loop#1577]
**Describe the bug**
I would like to build my loop on my new phone without this building error/fail 

**Attach an Issue Report**
[Build target Cartfile_2021-12-05T11-26-54.txt](https://github.com/LoopKit/Loop/files/7656398/Build.target.Cartfile_2021-12-05T11-26-54.txt)

**To Reproduce**
I have been not able to fix this bug. Unsure how to reproduce 

**Expected behavior**
Unsure at this time 

**Screenshots**
![image](https://user-images.githubusercontent.com/95582439/144755188-a51ddb09-2d70-4b40-a6b4-0a68e627cc5d.png)

**Phone**
 - Hardware: iPhone 13
 - OS Version: IOS 15.1

**Loop Version**
 - Version Number: 13.1
 - Repo: LoopKit/Loop, Ella

**CGM**
 - Device:  Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Additional context**
I am new to looping and coding. I was able to successfully get my loop to work on my old phone with a Orange RileyLink but I am having incredible difficulty getting this build to run. I know this is alot to ask but if someone to break down this bug and how to fix it in a step by step fashion for me this would be greatly appreciated. I am slow at this but willing to learn so that I can fix my own bugs in the future. Ive looked at similar issues and fixes but havent been able to navigate them independently. Thank you from a fellow looper.

**Comment by marionbarker** [comment]
You don’t include the screenshot but pretty sure you did not select LoopWorkspace. 
Step 2 in graphic in section linked below. If that fixed the problem please close this issue. 

https://loopkit.github.io/loopdocs/build/step14/#wait-for-xcode-to-finish-indexing

(Follow the docs about the watch app error - happens a lot - easy fix in LoopDocs.)

**Comment by EllaBesserer** [comment]
![image](https://user-images.githubusercontent.com/95582439/144756610-ee347c65-fdf9-4474-afd2-d646bf97397e.png)

So Im not seeing the LoopWorkspace tab - Unless im being blind

**Comment by EllaBesserer** [comment]
Woooooow Im so dumb - I selected to build in the loop workspace just like you said I was just looking in the wrong corner.... Thank you so much it looks like its building now! I wont close this until Its built uncase I run into any other errors but this is super appreciated.
