### ISSUE TITLE
Loop -> TestFlight Uploading fails due to NSHealthShareUsageDescription

### ISSUE THREAD

**Issue by scrappy** [LoopKit/Loop#1578]
**Describe the bug**

I've been working with a local Endo to build / share Loop with his patients via TestFlight ... the last build I was able to successfully do was back on Sept 9th, no problems.   

Today, using the latest master branch, I'm getting an error message concerning NSHealthShareUsageDescription ( see attached screen shot )

The build itself works fine, using instructions found at LoopnLearn ... and I've started with a clean clone of the repo, just in case ... its only when I go to Archive, and it gets to the Uploading stage, that I hit an issue ...

I've checked going back to the code release from just before Sep 9th, as there were two commits since then for Xcode issues ... the first failed with rileylink build issues ( suspect that is what was fixed with the Xcode 13 fixes ) and the second one built find, but then once more failed at the Archive/Uploading stage.

Suspect that something on Apple side got more strict, but from looking at the code ... looking under Info in Xcode, I see that it is defined for Loop, but not the other 3 ( Loop Status, Watch, Watch Extension ) ... does it need to be added there too, or is in Loop supposed to be. enough?

Please advise, thx ...

**Screenshots**
![Screen-Shot-2021-12-04-at-21 52 41](https://user-images.githubusercontent.com/609712/144777498-7f45043d-a5f2-4d2a-b313-b3be11a546b7.png)

**Comment by scrappy** [comment]
In order to resolve this, I had to add key's for both:

	<key>NSHealthShareUsageDescription</key>
	<key>NSHealthUpdateUsageDescription</key>

to Loop/Loop Status Extension -and- Loop/WatchApp Extension ... adding them to Loop/WatchApp generated an error about invalid key.

I don't know if Apple has regional privacy requirements for this sort of thing, but I am in Canada ... someone on the Zulip build channel tested the process, and reported that they didn't have to do anything special to get it to upload to TestFlight, so *something* is different ...

He and I are running same OS / Xcode ... which is why I suspect the Apple App Connect side of things being where things are different ..

**Comment by scrappy** [comment]
Patch to correct issue in Loop attached:

[Loop.diff.gz](https://github.com/LoopKit/Loop/files/7665385/Loop.diff.gz)

**Comment by ps2** [comment]
Thanks for the patch. The modification of the status extension plist is not needed, but the watch extension is.

**Comment by ps2** [comment]
[This PR](https://github.com/LoopKit/Loop/pull/1585) has just the fix for the watch extension.
