### ISSUE TITLE
No loop connection for hours

### ISSUE THREAD

**Issue by tkht1d** [LoopKit/Loop#1580]
**Describe the bug**
Yesterday afternoon, I stopped getting a closed loop, with a strange message I've never seen before screenshotted below. It is only Dexcom not connecting to the loop app.

**Attach an Issue Report**

https://drive.google.com/file/d/1li5EftvlqTnTja68NYeJpwKeVynLkbj9/view?usp=drivesdk

**To Reproduce**
I'm not sure how I caused it but to get the message in the screenshot I just clicked on the red loop.
**Expected behavior**
I expect my sensor and pod to work together in a closed loop.
**Screenshots**
![image](https://user-images.githubusercontent.com/90116022/145406996-f9bbfb19-104f-47db-83e4-4128230cac4d.png)
**Phone**
 - Hardware: iPhone 12 mini
 - OS Version: iOS 15.1.1

**Loop Version**
 - Version Number: v2.2.6
 - Repo: Loopkit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom app

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: I think it is 2.10.0

**Additional context**
I am running master branch with Xcode 13.0 release.

**Comment by dybs** [comment]
I think this is the same issue as #1576

**Comment by tkht1d** [comment]
Yes, it is. My bad.

**Comment by codelinx** [comment]
Think based on the info out there there's an ongoing issue with the date JSON changed on dexcom's backend, and it's unable to be used by the loop app.

**Comment by dybs** [comment]
Most people shouldn't need to use Share with Loop anyway, so clearing the Share credentials should fix it for the typical user.  See https://www.facebook.com/groups/TheLoopedGroup/permalink/2999936863556293

**Comment by tkht1d** [comment]
Now that I believe the problem is solved, I'm going to close this issue.
