### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by Mairead101** [LoopKit/Loop#1581]
**Describe the bug**
Trying to build Loop 2.2.4 (for a number of reasons that I'm happy to discuss separately, but are not relevant to this discussion re: build error), and we are getting the error "Command PhaseScriptExecution failed with a nonzero exit code". I do not have an option for Loop(Workspace) when I try to build this version - this may or may not be relevant but seems significant based upon other issues that have been posted related to this error message.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.
Not relevant.

**To Reproduce**
1. Download v2.2.4 from this link: https://github.com/LoopKit/Loop/tags?fbclid=IwAR3fiAeccfhQ-LknP64HGsymgLsyTl1dKqCoOQgV-YZjn51psHiQUBDVT-U
2. Unzip and open Loop-2.2.4/Loop.xcodeproj
3. Wait for indexing to complete. Clean build folder via Product < Clean Build Folder
4. Press build button.
5. Immediately get error message (attached) and pop up "Build Failed"

**Expected behavior**
Expected build to complete.

**Screenshots**
<img width="1018" alt="Screen Shot 2021-12-23 at 5 24 10 AM" src="https://user-images.githubusercontent.com/50084497/147231485-ed6fe129-0001-43a7-834c-b26aa08cdfa7.png">

**Phone**
 - Hardware: Tried on both our iPhone XS and iPhone 8. Neither worked.
 - OS Version: iOS 15.2 on both phones.

**Loop Version**
 - Version Number: 2.2.4
 - Repo: 

**CGM**
Dexcom G6

**Pump**
 - Manufacturer: Insulet
 - Model: Eros

**Additional context**
Xcode 13.2
MacOS 11.5.1

**Comment by elnjensen** [comment]
Because of changes in Xcode 13 (which is required to build for iOS 15), only LoopWorkspace builds are now possible with your iOS version.  So the errors you’re seeing are expected (unfortunately) with a non-workspace build. 

You can download the 2.2.4 workspace version here: https://github.com/LoopKit/LoopWorkspace/tree/v2.2.4

and then build as outlined in the docs.

**Comment by marionbarker** [comment]
Did you resolve this?  If so, please close this issue. This saves the developers time. TIA.

**Comment by pulsar1230** [comment]
hi i have the same problem can anyone help please 
![IMG_5502](https://user-images.githubusercontent.com/55031418/203321823-12bdc47e-36d5-42c9-9074-7bec4e156973.JPG)

**Comment by elnjensen** [comment]
@pulsar1230 You need to select "Loop (workspace)" (not Loop) in upper left, and select your own phone (not a generic device) to the right of that.  Please see the documentation: https://loopkit.github.io/loopdocs/build/step14/#select-loop-workspace-and-your-phone

**Comment by pulsar1230** [comment]
Hi I had my phone showing when I hit build and workspace it’s just showing for a minute then it goes back to any iso device


Sent from the all-new AOL app for iOS


On Tuesday, November 22, 2022, 1:25 pm, Eric Jensen ***@***.***> wrote:




@pulsar1230 You need to select "Loop (workspace)" (not Loop) in upper left, and select your own phone (not a generic device) to the right of that. Please see the documentation: https://loopkit.github.io/loopdocs/build/step14/#select-loop-workspace-and-your-phone
