### ISSUE TITLE
PhaseScriptExecution. No git branch found, not setting com-loopkit-loop-git-branch

### ISSUE THREAD

**Issue by bulatchik** [LoopKit/Loop#1583]
**Describe the bug**
I see the "Command PhaseScriptExecution failed with a nonzero exit code" error.
It is different to others issues (Command PhaseScriptExecution) due to the additioning  WARN: No git branch found, not setting com-loopkit-loop-git-branch

**Attach an Issue Report**
---

**To Reproduce**
Just trying to build the App

**Expected behavior**
Successful building

**Screenshots**
![screen1](https://user-images.githubusercontent.com/56740779/148692851-99af75b8-fa91-4d94-a1fd-2c3798baf4ce.JPG)

**Phone**
 - Hardware: iPhone 12
 - OS Version: Big Sur 11.6

**Comment by marionbarker** [comment]
Did you resolve this?  If so, please close the issue.
