### ISSUE TITLE
Inconsistencies between openloop mode and closed loop model for latest DEV alone and vs. the 2.2.6 release

### ISSUE THREAD

**Issue by hpc4fun** [LoopKit/Loop#1586]
**Describe the bug**
A couple of observations on inconsistencies in OPEN LOOP mode between current DEV and the 2.2.6 release of Loop and between current DEV in OPEN LOOP mode vs in CLOSED LOOP mode.

It shall be stressed that these issues are *NOT* a result of the latest DEV updates. They were present in DEV before too but to the best of my knowledge only one of the issues have been raised earlier for a earlier version of DEV and I can now confirm that the issue persist with the latest updates (it the other others have been reported earlier too, please bear with me and just ignore current reporting). I saw the highly appreciated latest updates to DEV as a good opportunity to provide this feedback.

1. In the Active Carbs Menu: Adding carbs by pressing PLUS leads to a crash in current DEV (this has been reported for earlier versions of DEV too, cf. issue https://github.com/LoopKit/Loop/issues/1574) but works fine for the 2.2.6 release of Loop and works fine for DEV in CLOSED LOOP mode.

2. In the Active Carbs Menu: Trying to adjust the carbs entered in an earlier event, say go from 20 g total to 30 g total is not possible in current DEV but works fine for the 2.2.6 release of Loop.

3. In the Active Carbs Menu: The edit option in the upper right corner to the left of the PLUS sign is missing in DEV.

4. When switching from CLOSED LOOP MODE (temp basal only setting) into OPEN LOOP MODE while the current basal is adjusted the current basal is reset to the default setting in DEV whereas it runs for the 30 duration in the 2.2.6 release of Loop. This might be an intentional change but since its inconsistent with the 2.2.6 release I will mention it for the sake of completeness.

**To Reproduce the behavior reported in 1:**

0. Switch to OPEN LOOP mode
1. Enter 20g of carbs
2. Go to Active Carbs menu
3. Push the blue plus sign in the upper right corner and loop will crash (*the inconsistency*)
4. If you switch back to CLOSED LOOP mode, 3 will work as expected and will lead you to the submenu 'Add Carb Entry'

**Expected behavior**
I expect same behavior as I see both in OPEN LOOP mode and in CLOSED LOOP mode in the 2.2.6 release and as I see in CLOSED LOOP mode for DEV.

**To Reproduce the behavior reported in 2:**

0. Switch to OPEN LOOP mode
1. Enter 20g of carbs
2. Go to Active Carbs menu
3. Pushing the 20g event and nothing happens (*the inconsistency*)
4. If you switch back to CLOSED LOOP mode, 3 will work as expected and will lead you to the submenu 'Edit Carb Entry'.

**Expected behavior**
I expect same behavior as I see both in OPEN LOOP mode and in CLOSED LOOP mode in the 2.2.6 release and as I see in CLOSED LOOP mode for DEV.

**To Reproduce the behavior reported in 3:**

0. Switch to OPEN LOOP mode
1. Enter 20g of carbs
2. Go to Active Carbs menu
3. Observe that there is NO 'Edit' option to the left of the '+' sign in the upper right corner of the menu (*the inconsistency*)
4. If you switch back to CLOSED LOOP mode, and repeat step 3 you will notice the 'Edit' option to the  left of the '+' sign in the upper right corner of the menu

**Expected behavior**
I expect same behavior as I see both in OPEN LOOP mode and in CLOSED LOOP mode in the 2.2.6 release and as I see in CLOSED LOOP mode for DEV.

**To Reproduce the behavior reported in 4:**

0. Set basal to 0.5 throughout the day, set basal limit to 1.0
1. Add CGM simulator with HIGH BG to enforce closed loop mode to increase to 1.0 when its switched on
2. Switch on CLOSED LOOP mode with temp basal
3. Confirm that the pump simulator will increase the temp basal to 1.0
4. Switch CLOSED LOOP mode off again
5. Observe that current DEV will reset the temp basal to 0.5 when CLOSED LOOP is turned off despite the fact that the 1.0 has not run for a 30 min duration (*the inconsistency*)

**Expected behavior**
I do not consider this to be a bug per see. This could be a different rationale than what was used for 2.2.6 but as it is inconsistent with previous rationale I merely want to make sure that this is an intended change of behavior in DEV.

**Loop Version**
 - Version Number: latest DEV branch, sha: a1e4f9956f839b31b2948eb5a7ab9155bf9fd3a2

**CGM**
 - Device: Simulator

**Pump**
 - Manufacturer: Simulator

**Comment by hpc4fun** [comment]
@Pete Hats off for a rapid addressing of the issues mentioned above (and related ones :)).

With current dev of Loopworkspace (7659667), issue 1 have been resolved. For issue 2-3, the current master version semantics of open loop mode is now reintroduced in dev. Moreover, a few more openloop mode glitches have been fixed too. This implies that documentation of how openloop works in loopdocs, looptips, .... now again remains valid for the dev version.

Issue 4 is confirmed to be an improvement and I agree to that.

Again, thanks to to Pete for addressing this.

**Comment by ps2** [comment]
Thanks for sharing!

**Comment by pete** [comment]
> @pete Hats off for a rapid addressing of the issues mentioned above

@hpc4fun Thank you, but I cannot take credit.
