### ISSUE TITLE
[dev] WatchApp crashes during initialization on first launch (until debugger is attached)

### ISSUE THREAD

**Issue by billybooth** [LoopKit/Loop#1597]
**Describe the bug**
When building the `dev` branch, the WatchApp has always failed to launch / crashed for me after it is installed to my watch until I launch it with the debugger attached.  This has basically been happening to me for the entire time I've used Loop.  The workaround is easy enough, I just switch to the WatchApp scheme, press the `Run` button, and all is well.  Subsequent launches even after a force quit are successful.

**Attach an Issue Report**
Loop Report:
[Loop Report 2022-01-26 08_11_19-06_00.md](https://github.com/LoopKit/Loop/files/7944344/Loop.Report.2022-01-26.08_11_19-06_00.md)
Crash Report:
[WatchApp Extension  1-25-22, 11-14 PM.crash](https://github.com/LoopKit/Loop/files/7944350/WatchApp.Extension.1-25-22.11-14.PM.crash.txt)

**To Reproduce**
1. Probably have an unlucky combination of phone model / watch model / face type / complication type.
2. Build / deploy a dev build of Loop to a phone that does not currently have it installed.
3. Try to launch the WatchApp from a complication on the face.
  For me, this has almost always been the Modular face with the complication in the bottom left corner, in case that's relevant.

**Expected behavior**
The WatchApp should initialize correctly and launch, instead of crashing.

**Phone**
 - Hardware: iPhone 11 Pro Max
 - OS Version: iOS 15.2.1

**Loop Version**
 - Version Number: v2.3.0 (57): https://github.com/LoopKit/Loop/commit/23f4e857db102a3d81a5740f380c9e1b619ea958
 - Repo: [LoopKit/Loop](https://github.com/LoopKit/Loop)

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet / Omnipod
 - Model: Omnipod

**Additional context**
There is probably some related discussion on ZulipChat:
https://loop.zulipchat.com/#narrow/stream/144182-development/topic/dev.20branch.20v2.2E3.2E057/near/235921199
https://loop.zulipchat.com/#narrow/stream/144182-development/topic/WatchApp.20on.20dev/near/269413953
And the following Issue may be related:
#1517

I didn't step through, but I assume I'm using either a `.graphicCorner` or `.graphicCircular` complication family by putting the Loop complication into the bottom left corner of the `Modular` face and hitting a `tintColor` initializer here that's producing the crash:
https://github.com/LoopKit/Loop/blob/8c5c688963a015716496bb37616395b005313b08/WatchApp%20Extension/ComplicationController.swift#L197-L216

**Comment by JohnKitching** [comment]
I had the same problem as this with dev downloaded and installed yesterday. 
Your workaround worked thank you. 
Does this mean the fix didn't fix it? I'm assuming (but don't really know) that the fix is in the latest dev.

**Comment by billybooth** [comment]
There is no fix yet for this particular issue. That PR only restored the WatchApp scheme (which was removed unintentionally in the `dev` branch) and make the workaround easier to use.

**Comment by JohnKitching** [comment]
Ah ok. Thanks for the information.

**Comment by aidan-gibson** [comment]
Ditto

iPhone 12 16.0.2
watch 9.0.2
Complication on Modular Watchface

Rebuilt WatchApp directly, works.
