### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code.

### ISSUE THREAD

**Issue by Charles124175** [LoopKit/Loop#1598]
**Describe the bug**
Hi, I am having an issue building the app on my iPhone XR and watch SE. It fails on every attempt with the error "Command PhaseScriptExecution failed with a nonzero exit code"
I recently updated my phone to 15.3 and then I had to update my Xcode to version 13.2.1 my Mac is running macOS Big Sur 11.4. I tried to troubleshoot steps outlined on loop docs for this error but I can't see the lock-unlock button in keychain access. I'm not super techie so I'm sure there is an easy fix, I just can't figure it out. I've tried to build it on my iPhone 8 running 14.8.1 and it failed as well. It worked on an older iPhone SE before the updates. Please help! 

**Attach an Issue Report**
NA

**To Reproduce**
1. Run macOS Big Sur 11.4
2. iPhone XR 15.3 
3. Xcode 13.2.1
4. Build the app

**Expected behavior**
app to finish building on watch and iPhone 

**Screenshots**
   /usr/bin/codesign --force --sign - --timestamp\=none --generate-entitlement-der /Users/stephencasson/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Products/Release-iphonesimulator/Amplitude.framework

** BUILD SUCCEEDED **

Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/stephencasson/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Intermediates.noindex/ArchiveIntermediates/Amplitude_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude /Users/stephencasson/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude -output /Users/stephencasson/Downloads/Loop-2.2.6/Carthage/Build/iOS/Amplitude.framework/Amplitude

This usually indicates that the project itself failed to compile.
Command PhaseScriptExecution failed with a nonzero exit code

**Phone**
 - Hardware: iPhone XR
 - OS Version: 15.3

**Loop Version**
 - Version Number: I have tried 2.2.4, 2.2.5, and 2.2.6 as well as an older dev branch and master 
 - Repo: I'm not sure. 

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: 
 - Firmware version:

**Comment by marionbarker** [comment]
You did not select Loop (Workspace). Please look at the graphic in this section very carefully-especially the Step 2 detail highlight. 
https://loopkit.github.io/loopdocs/build/step14/#wait-for-xcode-to-finish-indexing

**Comment by Charles124175** [comment]
> You did not select Loop (Workspace). Please look at the graphic in this section very carefully-especially the Step 2 detail highlight. https://loopkit.github.io/loopdocs/build/step14/#wait-for-xcode-to-finish-indexing

![Screen Shot 2022-01-29 at 10 54 14 PM](https://user-images.githubusercontent.com/98678452/151690053-939cb539-fbbf-4987-b028-706b3718a591.png)


Hi, Thank-you for responding. I looked for the loop workspace but I'm not seeing it. I followed all the steps

**Comment by marionbarker** [comment]
If you have not figured this out by going step-by-step through LoopDocs please reach out on zulipchat or facebook to get a mentor to help you.  This is not the correct place for what is a user-error in trying to build.  Perhaps you did not download the workspace build clone that is required now. It is a new build method that I tried to explain clearly in LoopDocs.

I am not trying to be mean - but the Issue channel is meant to report bugs, not to ask for help. 

Please close this issue and read these 3 sections and reach out in a different place.
1. https://loopkit.github.io/loopdocs/#search-then-post
2. https://loopkit.github.io/loopdocs/build/step13/#build-select-script-workspace-method
3. https://loopkit.github.io/loopdocs/build/build_errors/#posting-for-help

You may also find this video helpful
* [How to Build Loop](https://youtu.be/gddhljzsNkM)
