### ISSUE TITLE
backfill existing Loop data onto Nightscout server

### ISSUE THREAD

**Issue by gabroo** [LoopKit/Loop#1604]
I recently setup a Nightscout server and connected my Loop (dev) client to it. The server seems to be working fine and the client is uploading data in real-time.

I'd like to have all my previous data on the NS server as well. Is there a recommended way to backfill the existing data that's stored on my phone?

**Comment by marionbarker** [comment]
Please close this - it will save the developers time if you do so. Loop uploads to NS from the time you tell it to start. There is no backfill. The discussion remains available  but doesn’t show up as an open issue that needs to be fixed.

**Comment by gabroo** [comment]
@Nightfoxy Thanks!
