### ISSUE TITLE
Auto Bolus Given While in Open Loop

### ISSUE THREAD

**Issue by acarterclark** [LoopKit/Loop#1615]
**Describe the bug**
I was in Open Loop doing basal testing and opened my screen and saw an auto bolus going through. 

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.
[Loop Report 2022-02-28 11 45 55-05 00 - Unknown.pdf](https://github.com/LoopKit/Loop/files/8158229/Loop.Report.2022-02-28.11.45.55-05.00.-.Unknown.pdf)

**To Reproduce**
I haven't been able to reproduce this.

**Expected behavior**
I expected there to be no automatic boluses while in Open Loop.

**Screenshots**
I didn't screenshot fast enough to catch it saying "Starting Automatic Bolus", but this is when the bolus was going through. A second screenshot is given to show that the temp basals showing in the first one were eventually cleared (which I am not worried about).
![IMG_5407](https://user-images.githubusercontent.com/100653725/156089819-d7d583de-85f4-49e4-8b68-725bac658756.PNG)
![IMG_5408](https://user-images.githubusercontent.com/100653725/156090383-7cc3f156-9d71-4636-826e-5f0b3354228f.PNG)

**Phone**
 - Hardware: iPhone7
 - OS Version: iOS 15.2

**Loop Version**
 - Version Number: ?
 - Repo: ?
 - I rebuilt my Loop with the Master branch using the new (easier) build process a couple of months ago

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: Unknown (screen goes blank except when on homescreen, so cannot check)

**Additional context**

**Comment by marionbarker** [comment]
This has been reported before. On my phone now. I’ll drop the link to the other issue report later. 

Most likely scenario is that Loop suggested an automatic bolus (on the HUD) and you tapped the line without noticing. Even in open loop, the recommendation is provided and enacted when you tap on it. There is no confirmation required when this happens.
