### ISSUE TITLE
Touching Bolus Amount in the Meal Bolus/Recommended Bolus Entry Triggers Keypad

### ISSUE THREAD

**Issue by Hencowitz** [LoopKit/Loop#1617]
**Describe the bug**
When choosing NOT to use the Recommended bolus in either the Meal Bolus screen or in the Bolus screen, you must push on the Bolus line to change the amount to your desired amount.  It is supposed to default to 0.0 when touching the number, but in most instances when pushing the keypad is triggered.  If moving to quickly through this screen and you expect the "save without bolusing" button to show up, you inadvertently end up pushing a whole number, like 8!  On a small phone like a iphone mini or SE, it is even easier to hit a whole number and not because as you are trying to hit the DONE button, you finger can also hit the number 3 at the same time.  It is terribly dangerous. I think it should be a double tap to bring up the keypad and one tap for the bolus to go to 0.0.  There are some times when if you hit the EXACTLY right space (and I'm still not sure exactly where that is) it may default to 0 and you can hit save without bolusing.  This makes doing quick entries even harder because of the reasons stated above.  I think it's better when hitting the Recommended Bolus would fill in the Bolus line, and it defaults to 0.0 instead.  On the iphone SE
**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Go to Recommended Bolus 
2. Click on the Bolus line, in the amount area
3. keypad is triggered
4. See how easy it is to hit a whole number while trying to exit the screen

**Expected behavior**
There is no quick and consistent way to get the Bolus to go back to 0 without risking the keypad coming up and going through an amazing amount of additional finger swipes to get the desired result

**Screenshots**

**Phone**
 - Hardware: [iphone SE]
 - OS Version: [15.1]

**Loop Version**
 - Version Number: [v2.2.3 (57)]
 - Repo: [Remote Bolus/Carbs]

**CGM**
 - Device: [ Dexcom G6]

**Pump**
 - Manufacturer: [omnipod]
 - Model: [eros]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**
There should be a quick way to be able to enter carbs without bolusing for them by mistake and not having to mess with a keypad to get a 0 figure in the bolus line.  This makes entering carbs for a future time really dangerous as well.  There are many instances where someone may want to enter in carbs and not take action on them right away or to let loop does it's 40% as the BG's fluctuate.

**Comment by ps2** [comment]
It is intentional that the keypad comes up. When you tap the edit area, the app assumes you wish to edit the recommendation.

**Comment by Hencowitz** [comment]
I was able to record this on a screen recording.  It won’t let me attach on my phone so I’ll do it when I get home.  There is a very small area you can tap but the U in the bolus amount field that will Zero out the bolus and “save without bolusing will appear! Easy done.  The problem arises where the touch area is not consistent and if you don’t touch it in the exact right place they keypad will pop up when you are expecting to be hitting the save button and you end up hitting a whole number and then having to delete it, then having to hit zero and then a done button, which is right announce the number three and on the small phones you can hit done and 3 at the same time and the 3 will go it, after thinking you had hit zero.  This is not stable.  Please take a second look when I can get the video uploaded.   I start hitting the field all the at to the right of the U and slowly start tapping left and it will sometimes zero out as Eric mentioned in the Zulip chat I will tag you in.

**Comment by ps2** [comment]
Will work on the bug where it fails to bring up the keyboard in https://github.com/LoopKit/Loop/issues/1618
