### ISSUE TITLE
Touching the same location on Bolus Amount triggers two different actions

### ISSUE THREAD

**Issue by Hencowitz** [LoopKit/Loop#1618]
In the conversation with Eric https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Clear.20bolus.20field.20when.20editing/near/273836277
he says that simply touching the Bolus Amount Field should zero out the number and he's right, in a VERY small area. If you start tapping to the right of U on that line and slowly move left while tapping, there is a very small area that if you touch it just right it will indeed zero out and the "SAVE WITHOUT BOLUSING" button will show up. This is fabulous. However, it is dangerous and unstable too. If you expect that you hit it in the right place to zero out the bolus, and you go to hit the save button, all of a sudden the keypad can pop up an cause you to hit 8 or 9 on the smaller phones, you then have to go and delete that and then you have to go to the top of the keypad to hit the "DONE" key, while doing that you can simultaneously also hit the number 3 and the keypad will close saving the 3, which you had just changed to being zero, after accidentally hitting 8/9. That is, if you see it and don't deliver a 3 unit bolus. Then you have to go back in and do it all over again. A young kid, or temporary caretaker has way too much space for error here.

I think that there should either be a keypad icon that you can press that would bring up the keypad for entry, and the whole touch sensitive area should default to 0.0 when tapped. That makes any deviation from the recommended insulin incredibly purposeful. Basically, within this function there are two ways to enter the same data, and the user can't rely on one or the other consistently. Only one thing should happen when you touch that line. My video first shows how tapping near the U will zero out and bring up the button, this is FINE if it works all of the time! The second entry will show you how touching the same area again, without as much preciseness, will then unexpectedly bring up the keypad causing multiple touch strokes to occur for what should be a very straightforward and purposeful action.

[recommendedbolusissue.MOV.zip](https://github.com/LoopKit/Loop/files/8171945/recommendedbolusissue.MOV.zip)

**Comment by ps2** [comment]
I'll take a look at fixing this so the keyboard comes up reliably. Thanks!

**Comment by marionbarker** [comment]
I think this issue should be closed.  It has been fixed.
