### ISSUE TITLE
DEV: Target indicator not shown when override without a target is selected

### ISSUE THREAD

**Issue by jgefaell** [LoopKit/Loop#1620]
**Describe the bug**
The target indicator on the HUD is not shown when an override that does not specify a target is selected

**Attach an Issue Report**
N/A

**To Reproduce**
1. Select an override that does not specify a target
3. Observe that the target indicator is absent from the HUD for the duration of the override

**Expected behavior**
Activating an override that does not specify a target should display the current target indicator on the HUD.

**Screenshots**

1. Override does not specify a target
![NoTargetSpecified](https://user-images.githubusercontent.com/653168/156482072-2c4f6635-b2b3-4290-a989-8107ada4f572.jpg)

2. The target indicator is absent from the HUD for the duration of the override
![NoTargetShown](https://user-images.githubusercontent.com/653168/156482082-e704bd0f-8ab5-419b-a753-2d75595a65d7.jpg)

**Phone**
 - Hardware: iPhone Xs Max
 - OS Version: 15.2.1

**Loop Version**
 - Version Number: 2.3.0
 - Repo: dev

```
* gitRevision: 4b1951e
* gitBranch: N/A
* workspaceGitRevision: 9363702
* workspaceGitBranch: dev
```

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Dash (TWI)  
 - Firmware version: 4.10.0

**Additional context**
N/A

**Comment by marionbarker** [comment]
Thanks for posting this Jon.  I noticed this as well but never got around to creating an issue.
In my case - when I hit the 3rd day pod override (which is indefinite in duration) I can wind up with no correction range showing up at all on my HUD.

**Comment by jgefaell** [comment]
This behavior is still present 

## Build Details
* appNameAndVersion: T1Pal Loop Dev v2.3.0 (99)
* profileExpiration: 2023-06-03 12:12:26 +0000
* gitRevision: 6e7f0e1
* gitBranch: N/A
* workspaceGitRevision: 0bdc76c
* workspaceGitBranch: dev
* sourceRoot: /Users/jongefaell/src/LoopDevSwitcher/Loop
* buildDateString: Fri Jun  3 08:23:24 EDT 2022
* xcodeVersion: 13E500a

**Comment by ps2** [comment]
This should be fixed in dev. Please re-open with screenshots and details if you see this on current dev.

**Comment by jgefaell** [comment]
I confirm that this is corrected. Thank you!
