### ISSUE TITLE
DEV: Premeal preset indicator tape not shown in Nightscout 

### ISSUE THREAD

**Issue by jgefaell** [LoopKit/Loop#1625]
**Describe the bug**
When the premeal preset is selected the indicator tape does not appear in Nightscout.

**Attach an Issue Report**
N/A

**To Reproduce**
1. Select and confirm the premeal preset
2. Observe that the tape indicating the premeal preset is not displayed in Nightscout.

**Expected behavior**
When the premeal preset is in effect the indictor tape should appear in Nightscout. 

**Screenshots**
1,) Nightscout dashboard during premeal preset
     The period when the premeal preset was active was coincident with the depicted boluses, I enabled a couple of other presets in between to show they appear, then I enabled the premeal preset again until the current time shown. 
![image](https://user-images.githubusercontent.com/653168/156912933-6e5732bc-b46b-4d8f-bfe6-2462ef0d9b85.png)

**Phone**
 - Hardware: iPhone Xs Max
 - OS Version: 15.2.1

**Loop Version**
 - Version Number: 2.3.0
 - Repo: LoopKit/Loop
```
* gitRevision: 7c6b7c1
* gitBranch: N/A
* workspaceGitRevision: 8d9072c
* workspaceGitBranch: dev
```
**Nightscout Version**
  - 14.2.6

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Dash (TWI)
 - Firmware version: 4.10.0 (BLE 1.4.0)

**Additional context**
I filed this under Loop/Loopkit dev because I'm not aware of any complementary development of Nightscout to accommodate possible interface changes with Loop. I can't specifically remember if this worked as I expect it to with Loop master, but I assume it did. I only observed it now because I'm paying attention.

**Comment by Trpl7ca** [comment]
I have noticed the same issue using current dev with dash. All other overrides display normally on NS

**Comment by jgefaell** [comment]
Bumping this gently in case it hasn't been seen yet. Thank you.

**Comment by jgefaell** [comment]
@marionbarker ?

**Comment by ps2** [comment]
This would be a great starter bug for someone looking to dip their feet into Loop development.

**Comment by jgefaell** [comment]
This behavior is still present 

## Build Details
* appNameAndVersion: T1Pal Loop Dev v2.3.0 (99)
* profileExpiration: 2023-06-03 12:12:26 +0000
* gitRevision: 6e7f0e1
* gitBranch: N/A
* workspaceGitRevision: 0bdc76c
* workspaceGitBranch: dev
* sourceRoot: /Users/jongefaell/src/LoopDevSwitcher/Loop
* buildDateString: Fri Jun  3 08:23:24 EDT 2022
* xcodeVersion: 13E500a

**Comment by jgefaell** [comment]
I confirmed this appears to be corrected with this build. Thank you!

## Build Details
* appNameAndVersion: T1Pal Loop Dev v2.3.0 (2022080900)
* profileExpiration: 2023-07-28 19:19:49 +0000
* gitRevision: 6ae754e
* gitBranch: N/A
* workspaceGitRevision: b6a3671
* workspaceGitBranch: dev
* sourceRoot: /Users/jongefaell/src/mobile/ios/LoopDevSwitcher.2022080900/Loop
* buildDateString: Tue Aug  9 21:06:53 EDT 2022
* xcodeVersion: 13F100

![image](https://user-images.githubusercontent.com/653168/184553566-b2fbfbcc-6d82-4fa6-90d3-28eabc1d7aa5.png)

**Comment by jgefaell** [comment]
My apologies for the previous comment. I removed it. 

This behavior is still present.

## Build Details
* appNameAndVersion: T1Pal Loop Dev v2.3.0 (2022080900)
* profileExpiration: 2023-07-28 19:19:49 +0000
* gitRevision: 6ae754e
* gitBranch: N/A
* workspaceGitRevision: b6a3671
* workspaceGitBranch: dev
* sourceRoot: /Users/jongefaell/src/mobile/ios/LoopDevSwitcher.2022080900/Loop
* buildDateString: Tue Aug  9 21:06:53 EDT 2022
* xcodeVersion: 13F100


![image](https://user-images.githubusercontent.com/653168/184553790-2390ffb8-f133-4c85-a468-10f901fb6737.png)

![image](https://user-images.githubusercontent.com/653168/184553829-d4ec7462-9468-47ef-ae19-048d2f35f5d0.png)

**Comment by jgefaell** [comment]
Is this being tracked for resolution?

**Comment by bjorkert** [comment]
Since Loop 3 can have both an override and pre-meal at the same time, I think it would be problematic to show them both in Nightscout as overrides. Can Nightscout even have more than one override active?

**Comment by bewest** [comment]
Yes, I don't think Nightscout has any issue here.
