### ISSUE TITLE
DEV - Red loop

### ISSUE THREAD

**Issue by scottf51** [LoopKit/Loop#1626]
Hi

Maybe just a one off, but since I am using Dev I thought I would get a report in with logs in case they are of any use.

Basically I woke up to a red loop (first night with dev loop version) , looks like it had been working most of the night but had been red for about 15 mins, everything was close by and pretty sure I have never seen a red loop since I went to OL. Also, weirdly, I think Orangelink was not flashing, take this with a small pinch of salt as I was half asleep. Red loop recovered about 5-10 mins after issue report taken.

After rebooting phone Orangelink was also flashing again. Tempted to try upgrading my OL to 3.2 as it is currently on 2.5, which I found the most stable for older version of loop and AAPS.

Will try and leave this version just in case you need more info and just monitor 
[Loop Report 2022-03-06 12:17:10Z.md](https://github.com/LoopKit/Loop/files/8192614/Loop.Report.2022-03-06.12.17.10Z.md)

**Comment by scottf51** [comment]
Nothing jumped out at me in the logs, thinking it may be the lack of something rather than something bad in the logs, like it just lost connection, just seems weird.

**Comment by scottf51** [comment]
This has not happened again since, seems like a one off

**Comment by Kdisimone** [comment]
I’ll close this issue then. Thanks for the follow up info.
