### ISSUE TITLE
Feature Request: Cancel Override Siri Shortcut

### ISSUE THREAD

**Issue by damonbayer** [LoopKit/Loop#1629]
Currently there is no way to cancel an override from a shortcut automation. This would primarily be useful for location-based automations. You could enable an override when arriving at the gym and cancel it when leaving the gym, for example.

**Comment by bjorkert** [comment]
There is the "Temporary Override Cancel" command, see below:

https://loopkit.github.io/loopdocs/nightscout/remote-overrides/#shortcuts

https://github.com/LoopKit/Loop/raw/4699417/Shortcuts/Cancel%20Override.shortcut

**Comment by damonbayer** [comment]
Unfortunately, that shortcut requires a nightscout site and an internet connection.

**Comment by damonbayer** [comment]
Bump

**Comment by damonbayer** [comment]
bump
