### ISSUE TITLE
“No Maximum Bolus Configured” when Maximum Bolus is Configured

### ISSUE THREAD

**Issue by damonbayer** [LoopKit/Loop#1641]
**Describe the bug**
"No Maximum Bolus Configured" occasionally shows up when I do have a maximum bolus configured. It seems to be accompanied by a slower than usual forecast generation. It has happened while blousing from a recent CGM value and also after manually entering a finger stick value.

This has been reported on new and old devices: [Zulip Topic](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Clear.20bolus.20field.20when.20editing)

**To Reproduce**
TBD

**Comment by elnjensen** [comment]
I’ve seen it too.  Anecdotally, for me it seems to be related to trying to bolus when there isn’t recent pump data, but I was unable to reproduce just now by toggling off my RileyLink until “no data” showed.
