### ISSUE TITLE
Loop is doing Remote Data Synchronization of SGVs in dev branch without option enabled

### ISSUE THREAD

**Issue by loudestnoise** [LoopKit/Loop#1642]
**Describe the bug**
As discussed [here](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Nightscout.20Client.20CGM/near/275252524) in Zulip, users of `dev` branch of Loop are missing the trend arrow in their Nightscout instances. It would appear Loop is uploading the SGV values, despite the option for "Upload Readings" not being enabled in the CGM manager.

**To Reproduce**
1. Build Loop `dev` branch on iPhone.
2. Configure Nightscout as one of your Services.
3. View Nightscout site and observe missing trend arrow. 
4. Check Loop and confirm Upload Readings is not enabled in CGM Manager.

**Expected behavior**
Unless enabled, Nightscout should ingest SGVs from Nightscout user's already configured setting.

**Screenshots**
Dave's example of how if he added a manual value to Apple Health that this was shown in Loop and then uploaded to his Nightscout.
![image](https://user-images.githubusercontent.com/194853/158906655-9dd58905-dfff-4d94-9559-678af92ccb18.png)

**Phone**
 - Hardware: iPhone 13 Mini
 - OS Version: iOS 15.4

**Loop Version**
 - Version Number: v2.3.0 (57)
 - Repo: LoopKit/LoopWorkspace `dev` branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod DASH

**Additional context**
Attached entries.json from ` /api/v1/entries.json` text file from Dave's Nightscout - https://cgms.davediabet.es

[entries.txt](https://github.com/LoopKit/Loop/files/8293455/entries.txt)

**Comment by gestrich** [comment]
A few hints for whenever this can be looked at:

The CGMManager includes a `shouldSyncToRemoteService` bool; however, that flag is not being respected in dev. See the screenshot below for where that flag is read in master. 

In dev, the RemoteDataServicesManager handles carb uploads. That is probably where we need to access the `shouldSyncToRemoteService`. That class does not appear to have a reference to the CGMManager, so a new delegate between RemoteDataServicesManager and DeviceDataManager may help here (RemoteDataServicesManager has a reference to CGMManager)

![Screen Shot 2022-05-22 at 7 18 37 PM](https://user-images.githubusercontent.com/3207996/169721182-c7143fcc-202f-4c2d-adb9-061ce9d34f4a.jpg)

**Comment by bill-foreflight** [comment]
This should now be fixed by https://github.com/LoopKit/Loop/pull/1700
