### ISSUE TITLE
v2.3.0 Dev - Correction Range Bar Disappears Using Overrides with Empty Target Values

### ISSUE THREAD

**Issue by rfmurphy81** [LoopKit/Loop#1644]
**Describe the bug**
Throughout the day, I have two different correct ranges. One while awake and one while asleep (slightly higher). Using the v2.3.0 Dev branch from March 9, it appears that when an override is enabled that does not have a target range, the blue bar on the predicted glucose view disappears from view. When using another override with target range values set or disabling an override, the blue bar on the predicted glucose view displays as expected. 

**Attach an Issue Report**
See attached. 

**To Reproduce**
1. Set up an override as just a percentage without any values in tha target range
2. Ensure you have a correct range established and it displays as a blue bar in the predicted glucose view
3. Enable said override

**Expected behavior**
The blue bar for the correction range should not disappear when an override without a target range value is enabled

**Screenshots**
See attached for video. 

**Phone**
 - Hardware: iPhone 13 Pro
 - OS Version: iOS 15.2.1

**Loop Version**
 - Version Number: v.2.3.0
 - Repo: LoopWorkspace Dev from March 9

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: OmniPod
 - Model: Dash
 - Firmware version: 4.10.0

**Additional context**
N/A

[Loop Report 2022-03-20 19:22:28-07:00.md](https://github.com/LoopKit/Loop/files/8312730/Loop.Report.2022-03-20.19.22.28-07.00.md)

https://user-images.githubusercontent.com/26353970/159198354-8bf47458-7d5c-4a49-b82a-2973ea11a342.mp4

**Comment by Nightfoxy** [comment]
I was about the report this same thing. Nicely documented.
I think the behavior currently in master is sufficient: the existing correction range is boldened or made less opaque on the graph.

**Comment by jgefaell** [comment]
#1620

**Comment by biesbjerg** [comment]
Don't know if it helps, but if `Pre-Meal Preset` is activated before activating a preset, the correction range is shown.

![image](https://user-images.githubusercontent.com/230182/180038324-df753977-2099-4580-8925-41324f9bbf93.png)

**Comment by marionbarker** [comment]
I just built with the "fix" for this. It now shows the correction range, but it is not enhanced with a dark bar - can't tell when override starts and stops from the graph.
LoopWorkspace: 551baa72
Loop: f3e5cbcd

Graphic below - left side before rebuild, right side after rebuild.
Override is one that does not have the correction range filled in, only a sensitivity change.


![issue_1644_wip](https://user-images.githubusercontent.com/19607791/182175825-93fea7e1-7087-4b4b-89e9-8ad754f210c3.png)

**Comment by biesbjerg** [comment]
This is to be expected. Since the active override target range isn't overridden, the chart should not change. I understand you wanting to easily see when an override starts/stop but I don't think the glucose target range bar is right mean to do that and should probably be solved another way. Just my opinion of course :-)
