### ISSUE TITLE
Dev - Cannot Deliver Bolus easily when Omnipod DASH is attached to back

### ISSUE THREAD

**Issue by rolandet** [LoopKit/Loop#1647]
**Describe the bug**
I am testing the Omnipod DASH with the Dev Branch and have noticed some communication issues when the DASH Pod is attached to my back. I have not been able to consistently deliver a Bolus when the DASH is attached to my back. Other locations such as arm, stomach, and thigh do not seem to have such issues. At least for the majority of the times. 

I have tried turning Bluetooth on and off with success.  The only way that I have been able to to deliver the Bolus is to hold the iPhone behind my back but due to FaceI D this is not a usable workaround. The only workable workaround is to hold the iPhone behind my back and deliver the Bolus with my Apple Watch.

Bluetooth technology should have a range up to 30 feet so I believe some comm tweaks are needed with the Loop DASH modules. I have attached some issues reports to the tickets.

**Attach an Issue Report**

* appNameAndVersion: Loop v2.3.0 (57)
* profileExpiration: 2023-03-02 22:15:47 +0000
* gitRevision: d70a156
* gitBranch: N/A
* workspaceGitRevision: 889fd50
* workspaceGitBranch: dev
* sourceRoot: /Users/rteague/git-projects/Loop/LoopWorkspace/Loop
* buildDateString: Wed Mar  2 19:05:21 EST 2022
* xcodeVersion: 13C100

**To Reproduce**
1. Attach DASH Pod to back
2. Attempt to deliver Bolus
3. Receive Pod not connected error in Loop App.

**Expected behavior**
You should be able to deliver a Bolus consistently no matter where the Pod is attached to your body.

**Screenshots**

**Phone**
 - Hardware: iPhone 12
 - OS Version: IOS 15.3.1

**Loop Version**
 - Version Number: Loop v2.3.0 (57)
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: DASH
 - Firmware version: 3.27.0

**Additional context**
[Export-20220321T135500Z.zip](https://github.com/LoopKit/Loop/files/8342769/Export-20220321T135500Z.zip)
[Loop Report 2022-03-21 09_56_07-04_00.md](https://github.com/LoopKit/Loop/files/8342772/Loop.Report.2022-03-21.09_56_07-04_00.md)
[Export-20220322T194637Z.zip](https://github.com/LoopKit/Loop/files/8342773/Export-20220322T194637Z.zip)
[Loop Report 2022-03-22 15_47_09-04_00.md](https://github.com/LoopKit/Loop/files/8342774/Loop.Report.2022-03-22.15_47_09-04_00.md)

**Comment by rolandet** [comment]
Sorry, I meant to mention that. The issue **does not** occur with the DASH PDM. Hence the reason I filed a bug report.

**Comment by marionbarker** [comment]
I suspect your phone.  I did a test this morning (iPhone 11) - I stood across the room with the pod on the part of my body facing away from my husband and had him request a bolus for me.  It went through with no problem.

I also have a test set-up on my desk with an iPhone 8 connected to a water pod.  I held that pod so line-of-sight was front to back and then side to side through my body - no issues commanding a bolus.

**Comment by rolandet** [comment]
@marionbarker Are you saying you suspect my specific iPhone is having an issue with Bluetooth or the iPhone 12 in general? The chipsets between the iPhone 11 and iPhone 12 are different so could this be a general issue with the iPhone 12 and the Loop DASH module? Do you know of any testing that has been done with the iPhone 12 or 13? My other Bluetooth devices do function normally.

**Comment by Kdisimone** [comment]
I’ve tested body blocking and range on dash Loop too. Haven’t had any issues (iPhone 12 max)

**Comment by rolandet** [comment]
I went to the Apple Store today to have them run the diagnostics on my iPhone 12 and everything passed, including Bluetooth so there is nothing wrong with the iPhone hardware wise. They suggested resetting the network settings, erase all settings, and then finally a DFU as a new iPhone if all else fails.

Before I go down that route I did notice something today on the Omnipod DASH  box that seemed odd. The Date is from March 2019. I'm going to contact Insulet about this tomorrow before going to the Pharmacy since I'm had good luck with Insulet in the past with defective pods. The Pharmacy that my Health Insurance provider uses tends to brush these things under the carpet and I know Insulet will act on it and address it with the Pharmacy based on past experience. I have attached a screenshot of the box.
![IMG_0438](https://user-images.githubusercontent.com/4328088/160317575-01c215f5-ee6e-499c-b5b6-21181dece4ae.jpg)

**Comment by marionbarker** [comment]
Your pharmacy should not be sending you expired pods.  It could be the pods - these were manufactured 3 years ago. A lot of old pods will work fine, but you don’t know. I had a box of 5 (donated pods) manuf Dec 2019 where 3 didn’t even wake up on filling and 2 lasted less than 24 hours as water pods on my desk.

**Comment by marionbarker** [comment]
I analyzed the Loop Report and added your pod fault to the [statistics spreadsheet](https://docs.google.com/spreadsheets/d/1CKMYpBQ0MFPpdfmDjETEq5s4iWEDMwVBEuyTI6o8Nt8/edit?usp=sharing)

I see a number of Bluetooth toggle on/off in your second file.  Are you needing to do this to get pod communication working again?

This tends to be more common with the older (NXP board) pods.

I can confirm the firmware on your pod is of the older type:
Pod_FW: 3.27.0, BLE_FW: 8.8.0

**Comment by rolandet** [comment]
@marionbarker Thanks for looking at the logs! Very much appreciated. The Bluetooth on/off was an attempt to get the iPhone to stay connected to the POD. 

In any case, regarding the age of the pods, tell me about it. I talked to Insulet yesterday and they are sending me a set of new pods and will follow up with the mail order pharmacy that I use. I like dealing with Insulet on issues like this as they take things seriously and won't brush it is under the carpet like this particular pharmacy would. I have had other unrelated issues with this pharmacy previously.

The only thing keeping me from saying "mission complete" is that a pod did work on my back with the DASH PDM. But. I think it most likely is the luck of the draw. Some of these older pods work better than others.

Once the new pods arrive I will test and update to this issue report to close the loop (no pun intended) on this issue.

**Comment by Hencowitz** [comment]
I just got our first mail order pharmacy shipment from Caremark.  Is there
a way for me to make sure they didn’t also send us expired pods?

**Comment by rolandet** [comment]
Just check the date on the back of the box.

**Comment by Hencowitz** [comment]
Thanks. I thought maybe it may be different than the box.  Looks like we’re
good then!

**Comment by rolandet** [comment]
@marionbarker My OmniPod DASH replacements arrived and my testing shows that the OmniPod's with the newer TWI Board are much more reliable with Loop. The NXP board seems to have some communication issues with Loop. With that said, the DASH's with the NXP board are still serviceable so I will just them up so that they do not go to waste. I just won't place them on my back. Hopefully there are not too many more DASH's with the NXP board out there at this point. I'm closing this issue out.
