### ISSUE TITLE
Simultaneous Incorrect Pod Expiration Notifications

### ISSUE THREAD

**Issue by gigich** [LoopKit/Loop#1648]
Today I switched from master (2.2.8) to dev (git revision 322064f) and after first pairing of a TWI dash pod I saw also such wrong expiration warnings.

Iphone 7 ios 15.4
Watch s3 os 8.5
xcode 13.3
Dexcom G6

Master 2.2.8 was running since some days with eros pods
Build of dev, eros pod still connected and running
Eros pod deactivated
Omnipod removed from loop
Add Omnipod Dash
Fill and Pair dash pod
After 40 Minutes since pod activating the expiration warning is showed up. There were 2 messages.
After about 2 hours closed app and reopened, until know no more messages.
There are 2 settings for pod expiration in loop:
"Expiration Reminder Default" (1hr)
"Scheduled Reminder" (71 hours after activating)

I do understand these like, the "Expiration Reminder Default" is the one which defines how many hours before the end of 72 hours lifetime will be the "Scheduled" Reminder" set after activating new pods, right?

I have another setup with the exact same Hardware (Iphone 7, 15.4) with same build, running a water pod. The only difference there is, it newer had an eros pod configured. There I did not get such wrong expiration warning.

So probably it is just a problem on switching between eros and dash? Does anybody had this warnings also after using the second or third dash pod?

[Loop Report 2022-03-24 19_33_49+01_00.md](https://github.com/LoopKit/Loop/files/8344492/Loop.Report.2022-03-24.19_33_49%2B01_00.md)

**Comment by damonbayer** [comment]
Zulip discussion: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Simultaneous.20Incorrect.20Pod.20Expiration.20Notifications
