### ISSUE TITLE
Overrides delete after upgrade from master to dev

### ISSUE THREAD

**Issue by gigich** [LoopKit/Loop#1649]
After building dev over master all settings will be still there, except overrides are no more available and have to be set again.
They should be kept

Iphone 7, iOS 15.4
dev build 322064f

It is not that important issue for me, but would be nice to have.

**Comment by DConmy** [comment]
FYI: This is still an issue in v2.30 (57) dev branch.   
LoopWorkspace July 2, 2022 commit.  1649aab9d5beb349557d987e85e4158589cef9f1

**Comment by absmindedprof** [comment]
Confirmed. I experienced this after building on 7/2 as well. 2.3.0 (57)

**Comment by ps2** [comment]
This should be fixed in dev. Would appreciate any testing reports.
