### ISSUE TITLE
Overestimation of IOB

### ISSUE THREAD

**Issue by thebookins** [LoopKit/Loop#166]
I have noticed on occasion the IOB calculation in Loop is incorrect. We are using a 722 pump with an iPhone 4s. The preferred data source is set to Event History. Here's one example.

Bolus of 1.4 U at 6:21 PM resulted in a jump in IOB of 2.8 U (I imagine it was counted twice) and immediate temp to zero:
![img_1590](https://cloud.githubusercontent.com/assets/12263040/18537612/38414d68-7b4a-11e6-8067-545a66cd82ba.jpg)

The reservoir history does not show a drop of this magnitude:
![res](https://cloud.githubusercontent.com/assets/12263040/18537702/acfcfa58-7b4a-11e6-9466-941d8b27410a.jpg)

and the history shows a single bolus at 6:21 PM:
![history](https://cloud.githubusercontent.com/assets/12263040/18537782/f13899b6-7b4a-11e6-8726-eeefd488d9e1.jpg)
![history_detail](https://cloud.githubusercontent.com/assets/12263040/18537795/134cd5f8-7b4b-11e6-9146-ddd695312d74.jpg)

Manually deleting the reservoir history list seems to force Loop to recalculate IOB using pump history alone, resulting in the correct IOB:
![correct](https://cloud.githubusercontent.com/assets/12263040/18537898/02dc847e-7b4c-11e6-926a-74299a3e0402.jpg)

**Comment by loudnate** [comment]
Thanks for filing this. 
> Manually deleting the reservoir history list seems to force Loop to recalculate IOB using pump history alone

Do you remember how many entries you needed to delete?

**Comment by thebookins** [comment]
No, I just deleted all of them (I think they went back to 12 am) but my son
wasn't using Loop during the day at school so there was a gap in the
middle. I'm not sure how many need to be deleted to force a recalculation.

**Comment by loudnate** [comment]
> there was a gap in the middle

Do you remember what time the gap ended?

> I'm not sure how many need to be deleted to force a recalculation.

Just try deleting one reservoir entry next time and let me know what you see.

**Comment by thebookins** [comment]
The gap would have ended around 3pm. Will try deleting one entry next time.
Cheers.

**Comment by ps2** [comment]
@thebookins Have you been able to reproduce this issue?

**Comment by thebookins** [comment]
@ps2 I haven't noticed this again since filing the issue, but I also haven't tried to reproduce it, as I don't have a second rig for testing. Could easily have happened again on small boluses without us knowing. I'll have a look at the code to see if there's any way a bolus could be counted twice. Where should I start looking? Somewhere in LoopKit/InsulinKit?

**Comment by ps2** [comment]
https://github.com/LoopKit/Loop/blob/master/Loop/Managers/LoopDataManager.swift#L195 is the top level entry point into calculating IOB in Loop.

**Comment by thebookins** [comment]
Thanks @ps. I'm wondering if there's an edge case where the dose is counted once from pump history and then a second time from recent reservoir values. Might have to do with the speed of bolus delivery and the timing of pump bolus events vs reservoir events.

**Comment by thebookins** [comment]
@ps2 After a careful read of DoseStore.swift I've realized that the IOB is based on reservoir history alone (if continuous) or pump history alone, so I don't think it's possible for the dose to be counted once on reservoir data and then again on pump history. My best guess for what is happening here is that the reservoir data wasn't continuous, so the IOB was based on event history, and there was some error in deduping the bolus events. Clearing the reservoir history caused loop to crash which deleted the dose caches and forced a recalculation that fixed the problem. Sound plausible?

**Comment by jmatheson** [comment]
Can this be closed?

**Comment by ps2** [comment]
Yes. I think if this was an ongoing issue, we'd be hearing at least some reports of it.
