### ISSUE TITLE
IOB different in widget and loop-dev

### ISSUE THREAD

**Issue by mcdiarmid1** [LoopKit/Loop#1664]
Built Loop-dev on top of Master with Eros pod in situ. No issues with OnBoarding. Widget shows IOB > 2x Loop-dev reported IOB.
No change with rebooting
Delivered insulin amounts are the same in Loop and Apple Health

**Expected behavior**
Widget and Loop IOB values should be the same

**Screenshots**
attached

**Phone**
iPhone 12Pro
iOS 15.4.1

**Loop Version**
appNameAndVersion: Loop v2.3.0 (57)
profileExpiration: 2023-04-06 01:49:50 +0000
gitRevision: cf955ab
gitBranch: N/A
workspaceGitRevision: b445b3e
workspaceGitBranch: dev
buildDateString: Tue Apr 5 20:47:31 PDT 2022

**CGM**
Dexcom G6

**Pump**
 Eros Pods

![B20A5AB9-272F-4158-B32F-810F9D27BBEC](https://user-images.githubusercontent.com/103163115/162116084-d438f863-da0d-46b0-85d4-5b0d7b77b096.jpg)
![CE8AD9A1-5F35-4A32-80FE-B86046B0F66F](https://user-images.githubusercontent.com/103163115/162116111-9756deb1-8d56-4632-9275-788537905794.png)

**Comment by elnjensen** [comment]
This issue still exists with the current Loop dev branch as of today, and the new-style widget.  Attached are screenshots showing the difference in IOB, and an issue report from Loop.

![IOB_widget](https://user-images.githubusercontent.com/2545845/186046040-c8bc718b-356f-4b72-bea7-636481ab7256.jpg)
![IOB_app](https://user-images.githubusercontent.com/2545845/186046042-aa55b7c4-cac9-46f2-85a8-2f5c38e2403d.jpg)
[Loop Report 2022-08-22 210132-0400.md](https://github.com/LoopKit/Loop/files/9398546/Loop.Report.2022-08-22.210132-0400.md)
