### ISSUE TITLE
red loop and no CGM even when Dex is working

### ISSUE THREAD

**Issue by Tashmand** [LoopKit/Loop#1673]
Hi, I have an intermitent issue with loop where it shows no BG readings from Dex and red loop, even though Dex is working fine. I had this on another phone and upgraded to iphone13pro but it still happens (if less). A few loop reports and also screen shots..
[Loop Report 2022-04-14 10:11:56+10:00.md](https://github.com/LoopKit/Loop/files/8485347/Loop.Report.2022-04-14.10.11.56%2B10.00.md)
![37A224EB-7E6E-48B1-8514-ECBB2CA3F0CF](https://user-images.githubuserco
![37A224EB-7E6E-48B1-8514-ECBB2CA3F0CF](https://user-images.githubusercontent.com/33423262/163289890-29606f1b-57cb-4947-b109-e0d5444a1172.png)
ntent.com/33423262/163289810-9eec
![00A80088-71F1-402A-823D-E43BD19E6D14](https://user-images.githubusercontent.com/33423262/163289823-408825be-3c2f-4bfb-b588-a66486384c7c.png)
70ab-d329-478d-a749-0d4a04e3d38a.png)
.

**Comment by Tashmand** [comment]
i should add that it randomly resolves. And also yes, transmitter correct, yes no dexcom share info in, yes, i have deleted and readded the transmitter into loop. yes, have cleared apple helth (brand new phone set up from scratch without downloading any historical data)

**Comment by aviau** [comment]
Keeps happening here too. I'm a long time user and this is new.

Wondering if this is related to the last ios version.

I'm running 2.2.9.

**Comment by aviau** [comment]
On my end I think that I am associating this with my nightscout configuration being wrong.

Theory:
- The nightscout domain url was bad (changed my domain, but forgot to update loop config)
- Loop tries to upload data to nightscout
- Times out or something, wastes "background cpu time" (not sure how IOS works here...)
- Loop's "main loop" code gets stuck on contacting nightscout, never does the rest.

If my theory is right that would be a bug. Managing the loop is certainly more important than uploading data to nightscout. Nightscout being down or misconfigured shouldn't break my loop.

**Comment by Tashmand** [comment]
I agree with you.  I built a new
Nightscout  and that seems to have fixed the bug

Other things I tried that didn’t fix it for long or at all

  *    new phone
  *   New instance of apple health (I set up my new phone from scratch)
  *   New Cgm
  *   New loop build



Natasha Mandie

Managing Director

[iqvQAtAAAAAElFTkSuQmCC]

E ***@***.******@***.***>
P +61 3 8488 9927
M +61 411 113 264



emadvisory.com<https://www.emadvisory.com/>

LinkedIn<https://www.linkedin.com/company/em-advisory>
Twitter<https://twitter.com/em_advisory?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>



EM Advisory Level 7 50 Market St
Melbourne VIC 3000 Australia



AFSL 419715

This e-mail and any attachments to it are private and confidential. If you are not the intended recipient, please immediately notify the sender and destroy the original email and its attachments without reading or saving in any manner; any disclosure or use of any of the information in this email and its attachments is strictly prohibited.

________________________________

**Comment by Stephenjcl** [comment]
I wanted to chime in that I have had a similar experience. I had done all the same troubleshooting as those mentioned above.

Numerous red loops, and very frequent crashing after 24 hours with the newest builds.

Something that seemed to help a lot was deleting my Nightscout from Loop. Now it's not uploading, but my phone is also not overheating and the app seems to be maintaining a connection. This is an odd bug.

**Comment by treycsar** [comment]
I was having this issue as well. I had an old NightScout link in settings, which I had since let lapse and was no longer active, and I deleted that. Once that was gone, that seemed to resolve the issue for me -- no additional red loops over past 24 hours. Will keep an eye on it, but it appears like that was the issue.
