### ISSUE TITLE
Bolus Wizard like calculator without CGM source

### ISSUE THREAD

**Issue by diabeticp** [LoopKit/Loop#1675]
Hello!
Can you please add bolus calculation without cgm data (based on BG or just carb amount calculation). It would really help to bolus from phone without touching pump.
Sometimes, I don't have CGM on me or CGM is really noisy. And for me, it's quite uncomfortable to manually count carbs in iPhone calculator app and then entering bolus. 
It would be awesome to have manual BG entering and have like Medtronic "Bolus Wizard", but in app.
Also, it would be helpful to have receiving BG data from pump sent from compatible BG meter (like OneTouch UltraLink or Contour Plus/Next Link).

**Comment by rodig03** [comment]
Hi,
Just enter the glucose in Apple health- it will be used for calculating the bolus. 
To directly get the glucose from the meter, check the accompanying app to the meter. If it can write to Apple Health glucose, you are done. 
Regards 

Robert 

Von meinem iPhone gesendet

**Comment by diabeticp** [comment]
> Hi, Just enter the glucose in Apple health- it will be used for calculating the bolus. To directly get the glucose from the meter, check the accompanying app to the meter. If it can write to Apple Health glucose, you are done. Regards Robert Von meinem iPhone gesendet
> […](#)

Thanks, just tried adding BG data to Apple Health and somehow it did work. Mostly, my problem is: Why do we need to add data to Apple Health for Loop to work with BG data? Wouldn’t be more practical to have manual BG enter in “Carb Entry” like in AAPS calculator, so people could enter BG from any meter (without opening Apple Health app).
My meter sends BG data directly to the pump (712-722 and Contour Plus/Next Link) and cannot send data to phone. Is there no way for Loop to get BG data from pump (with other data) and use it for calculation?

**Comment by rodig03** [comment]
Hi

It will read the pump data if you use the CGM setting for that (enlite CGM). 
And in one branch (think it is dev) it will ask you to enter the data if the CGM is not working, eg you have set Dexcom and there is no data. 
As loop makes sense only with a CGM adding manual glucose values is considered to be a temporary workaround. But it exists already. 

Von meinem iPhone gesendet

**Comment by diabeticp** [comment]
> Hi It will read the pump data if you use the CGM setting for that (enlite CGM). And in one branch (think it is dev) it will ask you to enter the data if the CGM is not working, eg you have set Dexcom and there is no data. As loop makes sense only with a CGM adding manual glucose values is considered to be a temporary workaround. But it exists already. Von meinem iPhone gesendet
> […](#)
> Am 18.04.2022 um 23:31 schrieb diabeticp ***@***.***>: ﻿ Hi, Just enter the glucose in Apple health- it will be used for calculating the bolus. To directly get the glucose from the meter, check the accompanying app to the meter. If it can write to Apple Health glucose, you are done. Regards Robert Von meinem iPhone gesendet … Thanks, just tried adding BG data to Apple Health and somehow it did work. Mostly, my problem is: Why do we need to add data to Apple Health for Loop to work with BG data? Wouldn’t be more practical to have manual BG enter in “Carb Entry” like in AAPS calculator, so people could enter BG from any meter (without opening Apple Health app). My meter sends BG data directly to the pump (712-722 and Contour Plus/Next Link) and cannot send data to phone. Is there no way for Loop to get BG data from pump (with other data) and use it for calculation? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

I have tried setting CGM source as "Medtronic 722" and waited like 10-15 minutes for Loop to receive BG data from pump. The result is: it didn't work at all. Loop says that it can't receive CGM data from pump (of course, I don't have Enlite or Minilink on me). To be exact *Missing Data: Glucose Data Not Available. Check your CGM data source*. I have also tried enabling CGM option on pump, but it didn't work either. 
Certainly, CGM data is more prefered for open and closed loop, but there are some times when people don't have CGM on them (just don't like it or don't have it by some circumstances for some days, weeks or more). It would be great to have *enter BG* option in Carb entry for more accurate Loop calculation or for freely entering BG data from any meter (without going to AH for it).

**Comment by marionbarker** [comment]
This feature has already been added to Loop-dev. (This is under test by experienced loopers and will be released as Loop 3.0 when deemed ready.  It is a substantial change in architecture and some displays look different. [LoopDocs: Loop dev Preview](https://loopkit.github.io/loopdocs/faqs/dev-menus/))

In Loop-dev, when there is not recent BG, if you tap on carb or manual bolus icon, you will be asked for a BG entry prior to loop making a suggestion.

At that point, you can just enter a BG and save, or continue using Loop's updated suggestion using the just-entered BG.

**Comment by blameitonben** [comment]
It is a very nice redesign, we very much like this tap to add BG feature. Comes in handy when dexcom is in sensor fail, or warm up.

Ben
________________________________
