### ISSUE TITLE
Display last loop time instead of a fixed per loop color strings

### ISSUE THREAD

**Issue by itsmojo** [LoopKit/Loop#1683]
The current Loop dev (currently labeled v2.3.0, presumably eventually v3.0) has an updated HUD with less information being displayed (e.g.no last loop time and no last update times for CGM, basal & pump) for a cleaner display. Although I don't actually like this approach in this case as a Loop user (and as someone providing Loop support or wanting to help those who do), it seems like this matter has been already been decided upon and I'm not going to try to rock the boat now. However, I do think that incremental improvements can be made which shouldn't interfere with the new modus operandi.

The green, yellow & red loops are the quick indicator of loop's health. But the fixed strings when the loop is pressed always giving ranges of time is lame and not particularly helpful after the first time you've read all 3 messages.

![original_green_loop](https://user-images.githubusercontent.com/23020111/167765771-7fb504db-0864-4533-abc9-a2222e69c498.PNG)
![original_yellow_loop](https://user-images.githubusercontent.com/23020111/167765788-193996e2-15fe-41cb-9b0a-a52db12f5f98.PNG)
![original_red_loop](https://user-images.githubusercontent.com/23020111/167765803-7fb6a70a-9b10-498b-8826-d1c5e6c57ce1.PNG)

A minimal approach within the current framework can be used where these 3 messages contain the actual time of the last loop instead of using fixed strings. I've created PR #1682 which will display the following messages for example last loop times of 1, 8 and 16 minutes. During this work, I decided to change the yellow loop message title from "Loop Failure" to "Loop Warning" to better differentiate from the red loop message and to more accurately describe Loop's yellow loop state.

![new-01-min-green-loop](https://user-images.githubusercontent.com/23020111/167767478-0570bd84-db8d-492b-926a-ec1fffca9983.PNG)
![new-08-min-yellow-loop](https://user-images.githubusercontent.com/23020111/167767496-094889d1-d165-469e-911f-e324c554aef9.PNG)
![new-16-min-red-loop](https://user-images.githubusercontent.com/23020111/167767515-e4caca12-9e17-41a1-8779-16f8dd6dcd39.PNG)

Another possible extension of this idea would be to include additional information that formerly used to previously be in the HUD displays such as the last CGM and Pump update times in the Loop Completion HUD detail message. This is a possible examples of what this might look like:

![mock_cgm_pump_update_times](https://user-images.githubusercontent.com/23020111/167767995-6438c066-1f2f-465b-a6b4-a3f95f05973d.PNG)

This is only a mock up as I'd need to probably create some new class or mechanism to keep track of the times from the CGM HUD and the Pump HUD along with the Loop Completion HUD in one place. Perhaps a more verbose message like this could also include the last time Loop set a new temp basal rate or issued an automatic bolus.

Since I'm not sure how to best to this in an acceptable fashion for the Loop braintrust and I'm worried that attempting to do something more like this will end up making it less likely that these fixed Loop Completion strings will be replaced for the v3.0 release, I going to leave this for possible later implementation in the hopes that Loop PR #1682 can land in time for v3.0.

**Comment by TLH54** [comment]
I agree with Joe’s proposed changes to include the additional information and differentiating the Yellow and Red using “Warning” vice “Failure”. However I’d recommend minimizing the words and being more direct. Something like:

		Closed Loop is ON (It’s self explanatory, doesn’t need to be restated.)
	Last successful loop: 1 minute ago.  (Simple, direct, informative.)

		Loop Warning
	Last successful loop: 8 minutes ago.
	Loop will continue trying to complete.
	Tap CGM and Pump icons for more information. (Only if there is more actionable information.)
	You may want to ensure Bluetooth is “on” and functioning.

		Loop Failure
	Last successful loop: 16 minutes ago.
	Loop will continue trying to complete.
	Tap CGM and Pump icons for more information. (Again, only if there is more actionable information.)
	You need to ensure Bluetooth is “on” and functioning.

While “conversational” language is nice, in an app like this, I think people are looking for direct and to the point information and instructions.

Tom

**Comment by 4gra** [comment]
With apologies for bikeshedding, I'd argue that *any* missed loop is still a failure, not a warning: so the differentiation is meaningless when you're looking at last-loop figures (whereas the colours are useful for at-a-glance status).

That small issue aside, I like the return of detailed comms information that has been very important for debugging meatspace issues over the last year of Looping, however simple we'd like the software and its first impressions to be.

(I'll be migrating back to dev soon and will give this patch a road test when I can.)

**Comment by marionbarker** [comment]
I made a few more modifications with a new PR #1684.  The rationale and graphics associated with that code are provided in the PR.
