### ISSUE TITLE
Nightscout Remote CGM Inop

### ISSUE THREAD

**Issue by gestrich** [LoopKit/Loop#1685]
**Describe the bug**

The Nightscout Remote CGM is not working. Credentials will be accepted after adding the CGM but it fails to retrieve glucose values.

The issue appears to be from recent changes in GlucoseEntry.swift which now require a Trend in order to initialize a GlucoseEntry from a raw value. See rileylink_ios commit `fc5804d589fd60c97de2c302dd43db008fc93791`

**To Reproduce**
1. Go to Settings -> CGM -> Nightscout Remote CGM
2. Add your Nightscout credentials.
3. Note your CGM values won't show.

**Expected behavior**
Its expected your recent CGM values be sourced from Nightscout

**Phone**
 - Hardware: iPhone XS
 - OS Version: 15.5

**Loop Version**
 - Version Number: dev Workspace commit 9067a89aebfc564ed7d524d9af59f957cac91a61
 - Repo: LoopKit/Loop

**CGM**
 - Device: Nightscout Remote CGM

**Pump**
 - Manufacturer: Simulator

**Additional context**

**Comment by JohnKitching** [comment]
I'm getting the same.

**Comment by JohnKitching** [comment]
Issue report attached. 

[Loop Report 2022-05-13 08:04:01+01:00.md](https://github.com/LoopKit/Loop/files/8684879/Loop.Report.2022-05-13.08.04.01%2B01.00.md)
t

**Comment by JohnKitching** [comment]
This may be a stupid question but couldn't we use Apple Health as a CGM? 

Lots of apps can write BG there in real time. 
No internet required. 
You already read and write there.

**Comment by ps2** [comment]
I think this commit: https://github.com/ps2/rileylink_ios/commit/d3f443ad92a744ad171036cf8370cb237b1c1416 might fix the issue.

**Comment by gestrich** [comment]
Appears to be fixed in the latest dev. Thanks.

**Comment by JohnKitching** [comment]
Thanks folks.
