### ISSUE TITLE
DND option for Omnipod alarms (alarm override)

### ISSUE THREAD

**Issue by taylorpatterson007** [LoopKit/Loop#1687]
Can Loop override the Omnipod alarms? Seems like they can when there is a screamer by clicking the Deactivation button at the end of life of a pod.

As a Loop user, I want the option to set a Do Not Disturb period so that if my Omnipod expires in the middle of the night, the screamer alarm doesn't wake me up at 3am. Perhaps Loop/Omnipod can obey the iPhone's Sleep/Wake Up settings for DND?

**Comment by MikePlante1** [comment]
That would be a severe safety hazard. If a pod is screaming, it’s because it’s insulin delivery has completely stopped forever. If you pre-snoozed this alarm, you’d likely wake up with a very high bg and at risk of ketones and possible dka.

**Comment by taylorpatterson007** [comment]
Yeah but some people’s bs is better controlled than others such that a 20-30 point rise due to a screamer at midnight isn’t as big a deal for one night.

What if it were an ‘optional setting‘ that rewards you with a good night’s sleep but only works if your past 48hrs bs has been in the target range?

**Comment by MikePlante1** [comment]
> Yeah but some people’s bs is better controlled than others such that a 20-30 point rise due to a screamer at midnight isn’t as big a deal for one night. What if it were an ‘optional setting‘ that rewards you with a good night’s sleep but only works if your past 48hrs bs has been in the target range?
> […](#)

You’re telling me that if you completely suspend your insulin for 8 hours, your bg only rises 30pts?

**Comment by taylorpatterson007** [comment]
My last screamer experience was at 3am and my bs was 110. Took off the pod, didn’t replace it, and woke up at 7:30am at 134. The last midnight time screamer – similar experience. So yeah about 24 points higher over 4.5 hours later, so at that rate over 8 hours it would probably have risen to 165-175 range, still acceptable post-meal level for me personally.

 

I’m absolutely not saying such an alarm override isn’t without risk for some individuals who do not have tight control yet or have sensitivities to glucose much higher than mine, it’s a wide spectrum and your point about safety is of course a vital consideration.

 

But going full closed loop is also risky and we all accept that risk using this software.

 

And by the way – I want to shout out to everyone one of you who contributed to make this happen because before Loop, I was a two-insulin pen user and regular finger pricker and my bs ranged on a regular basis from 40s (severe low) to 350+ and within 2 days going Closed Loop I was in tightly in range. My past 7 days average bs has been 123 and 87% in range.

 

I cannot thank all of you enough for giving me and thousands of others hope living with this disease.

 

Taylor

 

 

From: MikePlante1 ***@***.***>
Reply-To: LoopKit/Loop ***@***.***>
Date: Saturday, May 14, 2022 at 7:50 AM
To: LoopKit/Loop ***@***.***>
Cc: Taylor Patterson ***@***.***>, Author ***@***.***>
Subject: Re: [LoopKit/Loop] DND option for Omnipod alarms (alarm override) (Issue #1687)

 

Yeah but some people’s bs is better controlled than others such that a 20-30 point rise due to a screamer at midnight isn’t as big a deal for one night. What if it were an ‘optional setting‘ that rewards you with a good night’s sleep but only works if your past 48hrs bs has been in the target range?
…

You’re telling me that if you completely suspend your insulin for 8 hours, your bg only rises 30pts?

**Comment by taylorpatterson007** [comment]
I am trying to locate the section of code that controls the response to a screamer to make a custom build that will auto-respond with the DeactivatePod command when the pod broadcasts the case "exceededMaximumPodLife80Hrs" or 0x1C signal. Any help anyone can lend to point me to the monitoring/capture of such an alert from the Pod to the iPhone, would be appreciated.

**Comment by elnjensen** [comment]
Still seems like an interesting option - definitely not a bug report, so could benefit from an “Enhancement“ or “Feature request” tag.
