### ISSUE TITLE
Spike auto bolus

### ISSUE THREAD

**Issue by ABC-190293** [LoopKit/Loop#1696]
Hi
Sorry if this is the wrong place to post this but am in a bit of a panic. My 12 months runs out soon on my loop app so I was going to update it today. But I have read that the spike branch is no longer supported, is that correct? Don't want to attempt it and mess up what I have already.

I'm currently on v2.2.4 spike auto bolus, miao & libre

Thanks in advance for anyone that can point me in the right direction

**Comment by MikePlante1** [comment]
For Libre support, use FreeAPS, which is a version of Loop (not FreeAPS X, which also supports Libre but is a completely different app/algorithm)

**Comment by ABC-190293** [comment]
Thanks for that. Am I looking the right place at this then?

 https://www.loopnlearn.org/build-select/

Dreading this, I'm not the best at these things and thought at least Ive done it before but this looks like something new to learn.
