### ISSUE TITLE
Support Apple Health as a CGM

### ISSUE THREAD

**Issue by JohnKitching** [LoopKit/Loop#1698]
If you'd prefer not to support additional apps acting as CGMs how about reading from Apple Health? 
Lots of apps can write BG there in real time so why not read and use from there?
The big benefit as I see it is no data requirement unlike Nightscout CGM

**Comment by ps2** [comment]
It's not about whether we want to support additional apps or not, it's about what can reliably drive a loop cycle, and if the data can be accessed while the phone is locked. For Apple Health, the latter is not possible, so this is not a workable integration path.

Probably best to keep questions/discussion to zulip, and save tickets for actual descriptions of issues.

**Comment by JohnKitching** [comment]
Sorry. When GitHub offered a template for feature request I thought it would be ok. My bad. Won't happen again.
