### ISSUE TITLE
Various Omnipod beep fixes and improvements

### ISSUE THREAD

**Issue by itsmojo** [LoopKit/Loop#1707]
**Describe the bug**

OmniBLE has a number of Confidence Reminders beep bugs/misbehaviors:
+ When Confidence Reminders are Enabled, manual Temporary Basal Rates don’t emit a completion beep as they should
+ When Confidence Reminders are Disabled, setting the Low Reservoir alert incorrectly uses a .noBeep beep command
   block which will result in a completion beep for any in-progress bolus independent of the Confidence Reminders value
+ When Confidence Reminders are Disabled, setting the Expiration Reminder alert incorrectly uses a .noBeep beep command
   block which will result in a completion beep for any in-progress bolus independent of the Confidence Reminders value
+ When Confidence Reminders are Disabled, acknowledgeAlert() incorrectly uses a .noBeep beep command block
   when acknowledging an active alert which will result in a completion beep for any in-progress bolus
   independent of the Confidence Reminders value
+ If silenceAcknowledgedAlerts() (which is never called synchronously as a direct result of a user invocation) silences an already
   acknowledged alert, it incorrectly uses a beep block which will either result in a spurious beep if Confidence Reminders
   are Enabled or a completion beep for any in-progress bolus independent of the Confidence Reminders value
+ Setting the Expiration Reminder alert is incorrectly logged as a “Program Low Reservoir Reminder” session
+ PodCommSessions send() func is missing the optional expectFollowOnMessage parameter

OmniBLE and OmniKit have the following common long standing beep related issues:
+ Enabling Confidence Reminders (Confirmation Beeps) will incorrectly result in a completion beep
   for an in-progress automatic bolus
+ Any commands using a confirmation beep block will incorrectly result in a completion beep for an in-progress automatic bolus
+ Basal schedule completion beeps are meaningless (as they never normally complete) and should just be removed

Miscellaneous OmniKit updates
+ OmniKit’s “Automatic Bolus Beeps” should be renamed to “Extended Confirmation Beeps”
   for better consistency with the Dash implementation.
+ OmniKit should include basic manual temp basal beep support for if/when this feature is ever added for Eros Omnipod in Loop.

New feature change
+ Extended Confidence Reminders (Extended Confirmation Beeps) should be updated to beep for any automatic delivery
   change made by Loop (i.e., for set & cancel temp basal in addition to automatic boluses) for better consistency and usefulness.

**Attach an Issue Report**
NA

**To Reproduce**
See various descriptions in the **Describe the bug** section for many different examples of incorrect behavior

**Expected behavior**
When Confidence Reminders (Confirmation Beeps) are Enabled, there should be a confirmation beep for any manual
pod interactions initiated by the user (manual bolus, cancel bolus, manual temporary basal rate, cancel manual temp basal,
suspend, resume, enable confidence reminders, clear an alert, read pod status, read pulse log, etc) as well as at the normal
completion of any manual bolus or manual temp basal rate.

When Extended Confidence Reminders (Extended Confirmation Beeps) are Enabled, in addition to confirmation beeps
for the manual user initiated actions listed above, there should be a beep when Loop automatically makes any changes
to the insulin delivery (i.e., automatic bolus, set or cancel temp basal), but not at the normal completion of these automatic
deliveries (to reduce beep fatigue at the completion of typically short automatic boluses and to eliminate any apparent
phantom beeps at the completion of an automatic temp basal on the rare times these occur).

Otherwise there should be no pod beeps (except for applicable pod alerts which are initiated by the pod itself).

**Screenshots**
NA

**Phone**
 - Hardware: NA
 - OS Version: NA

**Loop Version**
 - Version Number: dev
 - Repo: LoopKit/OmniBLE ps2/rileylink_ios

**CGM**
 - Device: NA
 - Manager app: NA

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod DASH and Omnipod Eros
 - Firmware version: NA

**Additional context**
NA

OmniBLE PR with fixes/improvements for above listed items: https://github.com/LoopKit/OmniBLE/pull/47
OmniKit PR with fixes/improvements for above listed items: https://github.com/ps2/rileylink_ios/pull/723

**Comment by marionbarker** [comment]
The PR were merged. Should this be closed?

or is this complaint on Facebook part of this problem that has not been resolved. 

I’ll ask them how old their code is, but there are several folks saying they can’t stop reminder beeps after expiration. 

https://www.facebook.com/groups/TheLoopedGroup/permalink/3239847262898584/

**Comment by itsmojo** [comment]
This issue is specific to various problems in dealing with Confidence Reminders (aka Confirmation Beeps) and it should be closed the PR's were merged with the related fixes.

The problems reported in https://www.facebook.com/groups/TheLoopedGroup/permalink/3239847262898584/ are totally separate & unrelated. These beeps are from some activated pod alert(s) which repeat at various intervals and beep types for each type of alert that would indicate a problem with the new UI alert notification/clearing mechanisms. It would be easy to see which alert(s) are actually causing the repeated beeping if there was a Read Pod Status command in the new UI.

**Comment by jgefaell** [comment]
I have been having an issue since around 10 AM this morning. It's happened once before, but I wasn't sure what was going on. My Eros pod beeps a cadence of four beeps every minute for a couple of minutes or so every 15 minutes. I've been working and not in a position to pay enough attention or switch pods. This started when I entered the 8hr grace period.  To troubleshoot I disabled confidence reminders but that didn't change the behavior. 

I just got the 10U remaining alert and have over an hour left on the pod.

I have an issue report I can attach if needed. This may not belong here, and I can open a new issue also.

## Build Details
* appNameAndVersion: T1Pal Dev Loop Green v2.3.0 (2022092703)
* profileExpiration: 2023-09-28 02:34:39 +0000
* gitRevision: 284d9ef
* gitBranch: N/A
* workspaceGitRevision: ca8a374
* workspaceGitBranch: dev
