### ISSUE TITLE
Worldwide pump switch

### ISSUE THREAD

**Issue by loudnate** [LoopKit/Loop#171]
Place in the pump ID screen.

**Comment by CrushingT1D** [comment]
With labeling of this I know that AU uses US frequencies (despite using EU model numbers), so something to keep in mind. Not sure about outside of EU, NA or AU though.

**Comment by loudnate** [comment]
@crushingt1d can you expand on that? Are the characters "NA" in the number for AU pumps?

**Comment by CrushingT1D** [comment]
@johnmales may be able to answer this question (I am still on my US pump).

**Comment by johnmales** [comment]
Not sure what the question is about Australian pumps. Australian Medtronic pumps use US frequencies - 915Mhz. Pump names from the back of the pump are, for example:
REF MMT-754CAL
SN PAR123456H
CONF W098

Let me know if I can provide any other info.

**Comment by xpucuto** [comment]
I can provide a information regarding the EU pump models and characters in SN . It will take me few days to collect the data but the people from my group respond quite fast.

**Comment by beached** [comment]
Sounds like Canada and Australian might be similar.  US frequencies but EU models.  I have a 754CML that reports as 754
