### ISSUE TITLE
Double bolus for carbs

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#1712]
In the current version of dev, if LoopDataManager is blocked, or backlogged (slow devices, like Eros/MDT can take a while to issue a dose), there is a race condition where it's possible for the carb entry to be saved and the forecast run with both the carbs in CarbStore *and* the "pending" carb that the bolus entry view is holding on to, resulting in a doubly large bolus.

This is not known to affect previous, released versions of Loop, like master/2.x series.

**Comment by kenstack** [comment]
@ps2 - does this bug affect all versions of loop or just more recent dev versions? Thanks for any clarifications.

**Comment by ps2** [comment]
This is just dev.
