### ISSUE TITLE
Deleting Insulin Events Not Subtracting IOB

### ISSUE THREAD

**Issue by Sophieinthecloud** [LoopKit/Loop#1714]
**Describe the bug**
I deleted several boluses from the insulin event history (due to a site failure). The events did delete, but the IOB didn't go down. I had to delete them in Apple Health for the IOB to go down. First bug report. Hope I did it right. 
(please note! The screenshots are not from the same incident time as the issue report)

**Attach an Issue Report**
[Loop Report 2022-06-08 20:12:23-07:00.md](https://github.com/LoopKit/Loop/files/8874146/Loop.Report.2022-06-08.20.12.23-07.00.md)

**To Reproduce**
1. Go to insulin delivery
2. Click on edit
3. click red circle with white minus sign to delete bolus
4. notice that IOB does not diminish
5. Go to Apple Health
6. Delete the same boluses
7.  notice that the IOB does diminish

**Expected behavior**
I would expect the boluses to diminish the IOB after deleting from within the Loop App (insulin events)

**Screenshots**
![IMG_2368](https://user-images.githubusercontent.com/10387075/172952383-a344f436-0928-4f68-8d9e-7ab0af84ab27.PNG)
![IMG_2369](https://user-images.githubusercontent.com/10387075/172952387-a6a92f86-6c10-4800-b47d-168a939fdd32.PNG)
![IMG_2370](https://user-images.githubusercontent.com/10387075/172952390-2e36227e-665c-4f4f-9bb6-56fc0c984dd9.PNG)
![IMG_2371](https://user-images.githubusercontent.com/10387075/172952393-0e7ac4f2-2859-4b5f-aa01-19ee6d80c1a2.PNG)
![IMG_2372](https://user-images.githubusercontent.com/10387075/172952397-97893655-f26b-48d5-ab2f-3d0718483292.PNG)
![IMG_2373](https://user-images.githubusercontent.com/10387075/172952399-6d47129d-53bb-4051-96b1-b804425a6c7b.PNG)
![IMG_2374](https://user-images.githubusercontent.com/10387075/172952402-ee080c87-82ea-4eb8-b6c8-f015c28ee806.PNG)
![IMG_2375](https://user-images.githubusercontent.com/10387075/172952405-37a94750-35b4-4e6f-9eb9-b802ed4b88fa.PNG)

**Phone**
 - Hardware: iPhone XR
 - OS Version:  iOS 15.5

**Loop Version**
 - Version Number: 2.3.0 (57) Loop Dev
 - updated: 6/8/2023

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Dash

**Comment by marionbarker** [comment]
https://loopkit.github.io/loopdocs/faqs/apple-health-faqs/#insulin-and-apple-healthkit
