### ISSUE TITLE
Loop High Temping below correction range

### ISSUE THREAD

**Issue by emilyandbob** [LoopKit/Loop#1723]
[Loop Report 2022-06-17 15 39 39-05 00.md](https://github.com/LoopKit/Loop/files/8931227/Loop.Report.2022-06-17.15.39.39-05.00.md)
![NS](https://user-images.githubusercontent.com/69367417/174398757-3bdbd807-4372-4146-9c0b-149149ed1afe.jpg)

The last two nights (at least) loop is high temping when both BG and prediction are below correction. (Overnight target set to 100-105).

**Comment by joshandeliana** [comment]
I set a higher target from 4-7am. Loop does not appear to be following this target, I often see autobolus when below target, in various parts of the three hour time frame. 
![IMG_5025](https://github.com/LoopKit/Loop/assets/101681801/951df8cf-7a39-4f2f-8cff-0323be397db9)
![IMG_5024](https://github.com/LoopKit/Loop/assets/101681801/7227758f-cee2-4038-b045-f56f81ea953f)

**Comment by joshandeliana** [comment]
Happy to provide additional info as needed. Loop 3.1, at other times of day I see expected behavior, particularly when using high range override for exercise.

**Comment by joshandeliana** [comment]
[Loop Report 2023-06-23 16 13 53-04 00.md](https://github.com/LoopKit/Loop/files/11853010/Loop.Report.2023-06-23.16.13.53-04.00.md)
[Export-20230623T201434Z.zip](https://github.com/LoopKit/Loop/files/11853012/Export-20230623T201434Z.zip)
