### ISSUE TITLE
Glucose Safety Limit 

### ISSUE THREAD

**Issue by paddingtonil** [LoopKit/Loop#1725]
Cannot set the safety limit above 80 

- Version Number: 2.3 
- Repo: dev 6bf0f5f 
![IMG_4060](https://user-images.githubusercontent.com/54187576/174451615-9d006b0a-58ff-4a96-bc63-a931cc45abb2.PNG)

**Comment by MikePlante1** [comment]
Is your pre-meal range set to 80? You can’t set your safety limit below your pre-meal range.

**Comment by paddingtonil** [comment]
Target 90 pre meal 85
