### ISSUE TITLE
App bugs

### ISSUE THREAD

**Issue by maillochaud** [LoopKit/Loop#1728]
Hello.  I installed dev 2.3.0 (57) for a week
 Carthage version 0.36.0
 Mac OS Monterey v12.4
 iOSv15.5
 Xcode v13.4.1.  The application regularly bugs, especially when I open the settings tab, sometimes when changing the POD or when I go to modify a parameter.  I have rebuilt several times but the bugs continue.  I did not uninstall my old Master application on the iPhone.  Thank you for your help
 
Generated: 2022-06-25 07:41:02 +0000
## Build Details
* appNameAndVersion: Loop v2.3.0 (57)
* profileExpiration: 2023-06-23 18:18:18 +0000
* gitRevision: bcb5cf1
* gitBranch: N/A
* workspaceGitRevision: 553cbf2
* workspaceGitBranch: dev
* sourceRoot: /Users/jhmaillochaud/LoopWorkspace/Loop
* buildDateString: Jeu 23 jui 2022 21:00:47 CEST
* xcodeVersion: 13F100

## FeatureFlags
* cgmManagerCategorizeManualGlucoseRangeEnabled: false
* criticalAlertsEnabled: false
* entryDeletionEnabled: true
* fiaspInsulinModelEnabled: true
* lyumjevInsulinModelEnabled: true
* afrezzaInsulinModelEnabled: true
* includeServicesInSettingsEnabled: true
* mockTherapySettingsEnabled: false
* nonlinearCarbModelEnabled: true
* observeHealthKitCarbSamplesFromOtherApps: false
* observeHealthKitDoseSamplesFromOtherApps: true
* observeHealthKitGlucoseSamplesFromOtherApps: true
* predictedGlucoseChartClampEnabled: false
* remoteOverridesEnabled: true
* scenariosEnabled: false
* sensitivityOverridesEnabled: true
* simulatedCoreDataEnabled: false
* siriEnabled: true
* automaticBolusEnabled: true
* manualDoseEntryEnabled: true
* allowDebugFeatures: false
* simpleBolusCalculatorEnabled: false
* usePositiveMomentumAndRCForManualBoluses: true

## Alerts
**Alert Permissions Need Attention**

* identifier: LoopAppManager.riskMitigatingAlert
* issued: 2022-06-21 20:16:52 +0000
* acknowledged: 2022-06-21 20:16:58 +0000
* retracted: 2022-06-21 20:17:47 +0000
* trigger: immediate
* interruptionLevel: timeSensitive
* foregroundContent: {"title":"Alert Permissions Need Attention","acknowledgeActionButtonLabel":"OK","body":"It is important that you always keep Loop Notifications, Critical Alerts, and Time Sensitive Notifications turned ON in your phone’s settings to ensure that you get notified by the app."}
* backgroundContent: {"title":"Alert Permissions Need Attention","acknowledgeActionButtonLabel":"OK","body":"It is important that you always keep Loop Notifications, Critical Alerts, and Time Sensitive Notifications turned ON in your phone’s settings to ensure that you get notified by the app."}
* sound: n/a
* metadata: n/a

**Echec Loop**

* identifier: Loop.loopNotLooping
* issued: 2022-06-23 02:32:44 +0000
* acknowledged: n/a
* retracted: n/a
* trigger: immediate
* interruptionLevel: timeSensitive
* foregroundContent: n/a
* backgroundContent: {"title":"Echec Loop","acknowledgeActionButtonLabel":"ios-notification-default","body":"Loop ne s'est pas complété avec succès depuis 20 minutes"}
* sound: n/a
* metadata: n/a

**Critical Pod Error**

* identifier: Omnipod:pumpFault.Fault Event Code 0x31: Incorrect pod state for command or error during insulin command setup
* issued: 2022-06-23 02:17:29 +0000
* acknowledged: 2022-06-23 02:33:00 +0000
* retracted: n/a
* trigger: immediate
* interruptionLevel: timeSensitive
* foregroundContent: {"title":"Critical Pod Error","acknowledgeActionButtonLabel":"OK","body":"Insulin delivery stopped. Change Pod now."}
* backgroundContent: {"title":"Critical Pod Error","acknowledgeActionButtonLabel":"OK","body":"Insulin delivery stopped. Change Pod now."}
* sound: n/a
* metadata: n/a

**Comment by gigich** [comment]
Uninstall Master and rebuild again

**Comment by maillochaud** [comment]
Thank you for your answer. I just did it but the bugs persist. I can't edit the report. it bugs

**Comment by maillochaud** [comment]
I can't edit the report, it bugs

**Comment by maillochaud** [comment]
I just built a second time and the bugs seem to be gone. Thanks for your help
