### ISSUE TITLE
WatchOS 3 Support

### ISSUE THREAD

**Issue by loudnate** [LoopKit/Loop#173]
The background app refresh overhaul means that the current code hasn't aged gracefully at all.
* Add `os_log` support to assist in debugging issues
* Add background refresh support
* Refactor complication update times:
  * Interleave with background refresh
  * Optimize for waking hours (6 AM – 10 PM)?

**Comment by tomasboudr** [comment]
This will be awesome. 

Would also love support for the Utilitarian Small complication (for use in the corner when using the simple or utility watch face)

Or for the Module Large face complication so that we can include the current bg, the predicted bg, and the last updated time.

**Comment by CrushingT1D** [comment]
wonder if timing can be optimized with when watch is charging as opposed to a set time of day that may differ by person.

**Comment by paulforgione** [comment]
I have no idea what's involved in something like this or what your plans for updated Watch support are, but I think it would be awesome to draw the Predicted Glucose chart in the lower 2/3rds of the Loop app's main screen, just to understand how your number is going to get to the "Eventually" value.

Visualized below:
![img_12673](https://cloud.githubusercontent.com/assets/4359124/19008608/41a16bee-8721-11e6-9586-46e468d48c64.png)
![img_12674](https://cloud.githubusercontent.com/assets/4359124/19008607/419e832a-8721-11e6-9f35-a3f63ff29796.png)

**Comment by loudnate** [comment]
@paulforgione that was always the end goal for that large black area 😄 

watchOS 3 added support for SpriteKit, which I was planning to learn and then tackle the watch graph. hopefully someone can take up that call post-1.0!

@tomasboudr adding additional complications should be a relatively straightforward coding exercise, since all the communication and update mechanics are in place.
