### ISSUE TITLE
Permit correction range lower bound of at least 80 that allows for basal testing with closed loop predictive low glucose suspend (PLGS)

### ISSUE THREAD

**Issue by tabula-raza** [LoopKit/Loop#1738]
**Is your feature request related to a problem? Please describe.**
Proposed guardrails for Correction Range in loop-dev set a lower bound at 87. An edge use case where this poses a problem is if the user wants to set a wide correction range in order to observe CGM trend line over an extended period without any intervention (insulin delivery increase/decrease/suspension) to test/validate basal rates and basal rate changes. 

Open loop operation is not an ideal solution because exposes the user to risk of hypoglycemia. A solution I have used before is to model a "predictive low glucose suspend" feature in Loop by setting a wide correction range, typically ranging from 80 (equivalent of Basal-IQ boundary) to 180 (the maximum allowed value) so as to avoid going far out of range.

**Describe the solution you'd like**
The option to set a lower correction range value (down to the suspend threshold), whether directly, or providing a workaround to the guardrail (e.g. a "basal testing" or "PLGS" mode with limitations (can't be set for longer than e.g. 12 hours? require upper value of correction range be higher than e.g. 160?) that discourage their use to defeat guardrails)

**Describe alternatives you've considered**
I could just use 87 and live with the slightly shorter time series of "clean" data. I've had success without safety issue at 80, and would like the extra margin to observe if/when the line bends. During a slow descent (as can be the case with basal rates that are a little off), 7 points of SGV can be a sizeable margin.

**Additional context**
I also use wide correction ranges to observe ISF and CarbF while having the safety net of closed loop PLGS so I can be flexible/lose track of time without as much worry about safety.

**Comment by marionbarker** [comment]
This can be accomplished with no code change to loop. Use an override for this test. 

https://www.loopandlearn.org/basal-testing-in-closed-loop/

I believe you can close this issue.
