### ISSUE TITLE
FreeAPS app crashes when I try to insert cannula 

### ISSUE THREAD

**Issue by Nwheeldon** [LoopKit/Loop#1739]
Hello! I’m hoping somebody can help me with some issues I’ve been having building my app. 

I am using iPhone 13 pro, Omnipod, freestyle libre 2 and Riley link and trying to get XDrip and FreeAPS. 

I have successfully managed to get xdrip up and running so I then moved on to get FreeAPS. My first go showed a successful build and the app was up and running on my phone. All seemed to be working fine so I disconnected my phone (this is possibly where I went wrong) and went on to set up a new pod. The pod paired ok but when it came to inserting the cannula the app kept crashing. After lots of searching all I could really find was that I should have kept my phone connected to my Mac whilst I was setting up the pod etc. so I decided to start again, I followed all the build steps in step 14 again but then I now get the attached showing up. It says build successful but then it goes to this screen. I can access the app on my phone (whilst plugged in) but it still will let me prime a pod but not insert cannula, the difference being that this time the app doesn’t crash but the cannula just doesn’t insert and it gets stuck in that screen. Now I have disconnected my phone the app is still up and running and I have the option to ‘finish pod set up’ but reluctant to try again and waste another pod. 

Any help would be greatly appreciated, thank you!
![Uploading EEC4C5C8-239D-4B15-9504-702C21F81F87.png…]()

**Phone**
 - Hardware: iphone 13 pro 
 - OS Version: iOS 15.5

**Loop Version**
 - Version Number: FreeAPS V2.2 (204)
 - Repo: [LoopKit

**CGM**
 - Device: freestyle libre 2
 - Manager app: xdrip 

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros 
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by marionbarker** [comment]
Please close this issue. You are getting help on Facebook. If this was a problem with the code, FreeAPS issues get reported in loopnlearn repo, not LoopKit.
