### ISSUE TITLE
Low BGs not accepted by Loop - significant health risk

### ISSUE THREAD

**Issue by JohnKitching** [LoopKit/Loop#1740]
**Describe the bug**
When a BG of 2.2mmol or under is reported by Glucose Direct Loop doesn't accept it as valid and turns basal back on. 

**Attach an Issue Report**
Didn't get one at the time. Sorry. Wasn't number one priority. 

**To Reproduce**
Use Glucose Direct as BG source (client added to Loop Dev) and let BG go under 2.2 (really not recommended!)

**Expected behavior**
Loop shows BG as invalid

**Screenshots**
Sorry, was a bit preoccupied at the time. 

**Phone**
 - Hardware: iPhone 12 Pro Max
 - OS Version: iOS 15.5

**Loop Version**
 - Version Number: Loop v2.3.0 (57)
 - Repo: LoopKit

**CGM**
 - Device: Libre 2
 - Manager app: Glucose Direct

**Pump**
 - Manufacturer: Omnipod
 - Model: Dash
 - Firmware version: 
![image](https://user-images.githubusercontent.com/48366213/177512656-d2a3860c-7fc2-4ebc-a461-ad0f9388db81.jpeg)

**Additional context**

**Comment by ps2** [comment]
Libre is not integrated into this project as published. Could you either report this issue to the project that you're using to get Libre data, or submit an issue report showing the reported glucose?

Is the 2.2 value the "LOW" reading from Libre? If so, then the `.condition` field on the `NewGlucoseSample` that the CGMManager reports should be set to `belowRange`, and then Loop should treat it as "LOW".
