### ISSUE TITLE
activating pre-meal shows incorrect start of override

### ISSUE THREAD

**Issue by Joerg-Schoemer** [LoopKit/Loop#1741]
**Description**
When pre-meal is active and an override is scheduled, the start of the override starts at the end of the pre-meal even when the scheduled start is 1h after the end of the pre-meal.

**To Reproduce**
1. Go to 'overrides'.
2. Create a scheduled override to start in two hours.
3. Activate pre-meal
4. The start of the override is drawn right after the pre-meal

**Expected behavior**
The start of the override should be drawn to start in two hours.

**Screenshots**
scheduled override:
![before activating pre-meal](https://user-images.githubusercontent.com/8568035/177558942-b5b20591-98bf-4c0e-9da5-8b03a3dd9e63.jpeg)

after activating pre-meal:
![after activating pre-meal](https://user-images.githubusercontent.com/8568035/177559154-80b48a85-67b4-4906-b079-74c288013628.jpeg)

**Phone**
 - Hardware: iPhone 13 mini
 - OS Version: 15.5

**Loop Version**
 - Version Number: v2.3.0 (57)
 - Repo: LoopKit/Loop

**Comment by biesbjerg** [comment]
Hello @Joerg-Schoemer 

I've created a pull request (https://github.com/LoopKit/Loop/pull/1757) fixing the reported issue :-)
