### ISSUE TITLE
nightscout carb-correction disappears

### ISSUE THREAD

**Issue by Joerg-Schoemer** [LoopKit/Loop#1742]
**Describtion**
When editing a carb entry in history the carb treatment carb-correction in nightscout disappears.

**To Reproduce**
1. Check nightscout if an carb-correction treatment is present.
1. Go to carbs-history by tabbing on active carbs.
2. Click on an entry and edit the carbs, when a new bolus has to be delivered press 'Save and Deliver'
3. Reload nightscout
4. The carb-correction is gone

**Expected behavior**
New amount of carbs in carb-correction should be visible.

**Loop Version**
 - Version Number: v2.3.0 (57)
 - Repo: LoopKit/Loop

**Comment by ps2** [comment]
I am not seeing this behavior. What version of Nightscout are you using?

**Comment by Joerg-Schoemer** [comment]
nightscout
version 14.2.5
head

**Comment by ps2** [comment]
Are you still seeing this issue, and can reproduce it reliably?

**Comment by Joerg-Schoemer** [comment]
I’ll setup a Nightscout instance and try to reproduce with a simulator tomorrow.

**Comment by Joerg-Schoemer** [comment]
@ps2 I've setup a nightscout instance, started a simulator and tried to reproduce the behaviour, but it works as designed.
Maybe it was because of the bad network coverage we had on the countryside.
I'm sorry that I wasted your time.
