### ISSUE TITLE
Filter type of insulin in history

### ISSUE THREAD

**Issue by Joerg-Schoemer** [LoopKit/Loop#1743]
When viewing the history of insulin delivery it would be very helpful to filter the type of delivery (temp basal, bolus ...)

**Comment by rodig03** [comment]
Hi,

may I ask Why?

Basal varies to compensate high / low glucose. 

Bolus the as well according to the current glucose, planned sport (override). 

And in between you have the microboluses as advanced basal rates compensated by following 0 rate basals. 

So the borders are totally blurred between basal and bolus if you use a Loop with autobolus or Microbolus enabled. 

I doubt you‘ll get more insights than what you can find in the statistics in Apple health. Even these only provide limited insight for the reasons mentioned - they are showing you the sum basal and bolus by day, week, month etc. however

**Comment by absmindedprof** [comment]
Speaking for myself, as an adult user, I sometimes just want to see my meal bolus history and it's easier to read the log than try to slide my finger back and forth along the main display. The full insulin delivery screen is noisy with all the temp basal adjustments and/or auto-boluses.

**Comment by absmindedprof** [comment]
Or to put it another way - one reason to filter is to make it easier to find the Entry your looking for.

**Comment by Joerg-Schoemer** [comment]
What is the purpose of this view?

IMHO each insulin delivery method should have its own type:
* temp basal
* bolus
* micro bolus

**Comment by rodig03** [comment]
Why?
Basal varies to compensate high / low glucose. Bolus the same according to the current glucose, planned sport (override). And in between you have the microboluses as advanced basal rates compensated by following 0 rate basals. 
I doubt you‘ll get more insights than what you can find in the statistics in Apple health. Even these only provide limited insight for the reasons mentioned. 

Von meinem iPhone gesendet
