### ISSUE TITLE
can't uncheck glucose momentum and retrospectie correction

### ISSUE THREAD

**Issue by JohanDegraeve** [LoopKit/Loop#1744]
**Describe the bug**
can't unchecking the glucose momentum or retrospectie correction

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Click on Glucose graph
2. scroll down to the bottom, click 'glucose momentum'. The 'V' goes away
3. go back to home screen
4. do steps 1 and 2 again, the 'V' is there again

**Expected behavior**
The V should go away, and there should be a clear difference in the prediction (especially when trend is going up.

**Screenshots**

**Phone**
 - Hardware: [iPhone SE 2020]
 - OS Version: [15.5]

**Loop Version**
 This is an own version it's based on commit c53fe61701e83cc6c9703a8aedfe056aebb8c8d3

**CGM**
 - Device: [Libre 2]
 - Manager app: [xDrip4iOS]

**Pump**
 - Manufacturer: [Omnipod Dash]
 - Model: [e.g. 723]
 - Firmware version: [4.10.0]

**Additional context**
the same applies to retrospective correction

**Comment by marionbarker** [comment]
Please see this section of LoopDocs. 

https://loopkit.github.io/loopdocs/operation/loop-settings/displays/#predicted-glucose-chart

note these words
Note - these elements are not turned on and off in the Loop predictions. They just modify the graph so you can view the relative effects.

**Comment by JohanDegraeve** [comment]
ok that's clear I didn't read that documentation actually.
