### ISSUE TITLE
"Pump Suspended" Reminder Alerts Continue after deactivating DASH pod while suspended and starting new pod

### ISSUE THREAD

**Issue by tabula-raza** [LoopKit/Loop#1745]
**Describe the bug**
I keep getting iPhone notifications every 15 minutes to resume my pump from suspend. My pump is not suspended; however my prior pod was in a suspend state when I deactivated it. 

**Attach an Issue Report**
Generated a report after clearing notifications. Will attach later (posting from mobile.)
Edit: [Loop Report 2022-07-06 15:58:10-07:00.md](https://github.com/LoopKit/Loop/files/9060105/Loop.Report.2022-07-06.15.58.10-07.00.md)

**To Reproduce**
1. Pair DASH Pod
2. Suspend Pod
3. Select resume pump reminder (I had suspended for 1 hour)
4. Deactivate pod (note: the first "resume pump" notification had already fired, ie one hour had passed since I suspended before I deactivated.)
5. Pair and activate new DASH pod
6. Wait until 15 minutes have passed since first "resume pump" reminder fires. 

**Expected behavior**
I do not get suspension resume alerts after I deactivate the pod that was suspended. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3060874/177658218-d9e2bf47-d5d8-44a2-bfb6-3607a30ddc32.png)
![image](https://user-images.githubusercontent.com/3060874/177658149-a57b37fa-0be5-42b1-b84f-e83ecfcae0ab.png)
![image](https://user-images.githubusercontent.com/3060874/177658094-48e5fb43-f8cc-4ddb-86d7-7332a3e9bedf.png)
Note: active low temp in screenshots are from closed Loop automation, not manual user suspension. 

**Phone**
 - Hardware: iPhone 12 Mini
 - OS Version: iOS 15.5

**Loop Version**
 - Version Number: 2.7.0 (57)
 - Repo: dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod DASH
 - Firmware version: 4.10.0

**Comment by absmindedprof** [comment]
![image](https://user-images.githubusercontent.com/3060874/177658218-d9e2bf47-d5d8-44a2-bfb6-3607a30ddc32.png)

**Comment by absmindedprof** [comment]
Updated with attached issue report.

**Comment by absmindedprof** [comment]
Notifications are still firing at roughly 84 hours past the original pod's activation. For curiosities sake, will see whether suspend/resume on active pod breaks the erroneous notification loop.
