### ISSUE TITLE
Correction Ranges in app do not match those programmed in the Settings.  BG units in both mmol and mg/dL?

### ISSUE THREAD

**Issue by carolinemreed** [LoopKit/Loop#1764]
Hello, I appreciate your support :)
I have the following correction ranges programmed in my Loop settings:
00:00 95-160mg/dL 
07:00 80-100mg/dL 
21:00 95-160mg/dL

When I look at the app this is not what appears to be programmed. 
The only way I can get the app to properly reflect the correct settings is to go in an “edit” the correction range and resave it, only then will it display the correct settings, however for the next time segment they are incorrect again..

You may also see my settings are all in mg/dL however my app displays everything in mmol/dL, this might have to do with the Dexcom app using mmol?  This is not something that bothers me, I am used to both, just want to make sure it won't upset the Loop somehow.

Thank you in advance for your support! 
[Loop Report 2022-08-03 100633+0200.md](https://github.com/LoopKit/Loop/files/9249402/Loop.Report.2022-08-03.100633%2B0200.md)
![Correction Range screen](https://user-images.githubusercontent.com/59747135/183414147-511628aa-1e39-4a5c-84df-5f91534f3afd.png)
![Home screen](https://user-images.githubusercontent.com/59747135/183414148-f59a0da7-cc93-4b60-9417-be2c6418898b.png)
.

**Comment by ps2** [comment]
Where do you see the correction ranges displayed incorrectly? Could you attach a screenshot?

**Comment by carolinemreed** [comment]
Dear Pete,

Thank you for looking into this, yes attached are the screenshots, these
are all taken at the same time of day, within seconds of each other.  I
hope this helps to solve the "mystery".

Warm regards,
Caroline

**Comment by ps2** [comment]
I do not see any screenshots attached. Could you please go to the issue you created here: https://github.com/LoopKit/Loop/issues/1764 and upload them directly?

**Comment by carolinemreed** [comment]
[](url
![Correction Range screen](https://user-images.githubusercontent.com/59747135/183413260-f851b430-2cb4-4846-8667-f30316e3e1cc.png)
![Home screen](https://user-images.githubusercontent.com/59747135/183413262-ca76d8f0-915f-48ec-b7c7-32643e1e29dd.png)
)

**Comment by carolinemreed** [comment]
Based on the screenshots above the correction range for the time (22h) should be reflected as 95-160mg/dL (5.3-8.9mmol/L), however the correction range is appearing more like 80-100mg/dL (4.4-5.5mmol/L) which is the correction range for a different time segment (7am-21h).  Thank you again for your support!

**Comment by carolinemreed** [comment]
Thank you Pete,

I attached them both to the original issue as well as in a comment to the
original issue.  Thank you again for your support!

Best regards,
Caroline
