### ISSUE TITLE
Add RC and Momentum contributions to DosingDecision

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#1766]
DosingDecisions are recorded in critical device logs and form the main component of live data that is uploaded to remote services, like Nightscout's `devicestatus` records. They're very useful for retroactively seeing why Loop adjusted insulin. Carbs and Insulin are reported, which go a long way towards explaining what Loop was "thinking", but sometimes Retrospective Correction and Momentum terms can have a big effect as well. These fields should be added to the Dosing Decision store, and eventually uploaded via the NightscoutService.  Code updates would need to happen in Nightscout to actually display this information.

**Comment by PieterGit** [comment]
I might be able to help with the Nightscout side of it. Please let me know if there is a branch with these messages available, and I'll dive into it.
