### ISSUE TITLE
Therapy Settings not transferred

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1767]
**Describe the bug**
Moving from v2.2.9 to dev (LoopWorkspace commit: 9c48e05d), the therapy settings are discarded.

Please see zulipchat 
[zulipchat Dev App Loss of Therapy Settings at Migration](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Dev.20App.20Loss.20of.20Therapy.20Settings.20at.20Migration/near/292089881)

When testing another reported problem, I discovered the therapy settings were not transferred from Loop master (2.2.9) to Loop-Dev in onboarding.

**Comment by marionbarker** [comment]
Did further testing.
The problem with the therapy settings being discarded happened after LoopWorkspace commit 7fbaa1f1

**Comment by ps2** [comment]
Thanks!

Fixed with https://github.com/LoopKit/Loop/commit/6ae754e4e2e55221a70d9aeeb8e49ad758186503
