### ISSUE TITLE
Dev Aug 4 Commit Crashing Watch App

### ISSUE THREAD

**Issue by shainey** [LoopKit/Loop#1769]
**Describe the bug**
After installing the Dev Aug 4 Commit, it crashes my Loop app on my Apple Watch Series 5. When putting the icon to open Loop, it starts opening and closes itself immediately. When re-installing the Jul 30 Commit, it works fine.

**Attach an Issue Report**
[Loop Report 2022-08-07 151406-0400.md](https://github.com/LoopKit/Loop/files/9277775/Loop.Report.2022-08-07.151406-0400.md)

**To Reproduce**

**Expected behavior**
The Loop app on the watch opens

**Screenshots**
NA

**Phone**
 - Hardware: iPhone 11 Pro Max
 - OS Version: iOS 15.6

**Loop Version**
 - Version Number: Dev Aug 4 Commit 6ae754a

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet Pod
 - Model: Dash
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**
I believe this also occurred on the Jul 31 Commit

**Comment by rolandet** [comment]
I had the same issue today but I rebuilt Loop Dev, after removing the Loop Watch App, and that resolved the issue for me. I also also installed the Loop Watch App onto my Series 5 after 2nd build while my iPhone was attached to my Mac. Not sure if that made the difference but I thought I would mention it. This is not the first time I have had issues rebuilding and installing Dev on my Apple Watch. There must be some data being left over on the Watch that causes these issues.

**Comment by marionbarker** [comment]
Did you try this?
https://loopkit.github.io/loopdocs/build/build_errors/#apple-watch-loop-app-not-running-on-watch

**Comment by shainey** [comment]
Thank you for everyone's assistance on this! 

I am now up and running on this on the 8/4 Commit.  It looks that the issue was due to me updating the  StatusTableViewController.swift code to have the Loop display view show 50% backward in time & 50% forward Vs. the default 20% backward & 80% forward. 

Here's the change I was doing that did work okay before the 7/31 Comment, but not on the ones after it. a.	Loop > Loop > View Controlers > StatusTableViewController.swift (line 314 ) / Let historyHours = max(3, totalHours - futureHours).  

Can something be developed within the menu to let users select where they want this backward/forward display spilt?  For me, going out 4 to 5 hours isn't as helpful as seeing the last few hours trend after a meal or working out.  

Thx again for the help & consideration on this.  Steve
