### ISSUE TITLE
Loop automatically added 91g of carbs

### ISSUE THREAD

**Issue by ryancase22** [LoopKit/Loop#1775]
This is the first issue I’ve had like this in the 3 years I’ve been looping.  It automatically added 91 carbs, and won’t let me edit/delete it.  copied and pasted the Issue Report below, along with a couple screen shots.

**Comment by marionbarker** [comment]
Check Apple health permissions and other apps writing to carbs.

**Comment by ryancase22** [comment]
> 

User error!  I forgot I had MyFitnessPal access to Health turned on earlier.   Thank you! 😅
