### ISSUE TITLE
"future dating" of carbs was limited to one hour

### ISSUE THREAD

**Issue by mcslader** [LoopKit/Loop#1776]
Hi, I was trying to cover my son's pasta last night, which we usually do by giving a partial bolus up front and then putting some more carbs out into the future. Sometimes we put carbs out about 2.5-3 hours into the future, call them "pizza", and then let Loop handle it from there.
Last night was the first time since my most recent build of the dev branch (version 2.3.0 (57), built 08/10/22, b6a3671) where we tried to do this. I was unable to do so because it seemed like the time scroll wheel would not let me set carbs further than one hour into the future. Attached is a screen recording of what I was trying to do on his phone last night. iPhone XR, Loop built using a Mac running OS 12.5, XCode 13.4.1 (13F100).
Sorry if this is a duplicate / if I'm breaking the rules, but I also posted this to ZulipChat as well.

https://user-images.githubusercontent.com/50431938/185486571-de0f37ae-8cf5-409c-9a26-740947463c8b.MP4

**Comment by kevincam** [comment]
I believe this is one of the Tidepool-related guardrails, though I'm not sure why it would be limited to an hour.

**Comment by motinis** [comment]
It's a bit annoying but you can edit existing carb entries and move them forward 1 hour at a time. So just be sure to set it to 1 gram at the beginning to prevent Loop from auto-bolusing / temp-basaling much for it until you get it to the right time.

Otherwise, you can update the code per https://loopkit.github.io/loopdocs/build/code_customization/#default-carb-absorption-times

**Comment by marionbarker** [comment]
Please see PR #1997 
If that or similar PR is acceptable, this issue can then be closed.

**Comment by marionbarker** [comment]
This is a really valuable capability. I use it yo handle fat/protein ride following my evening meal. Is there any way to get this added to DIY loop?
