### ISSUE TITLE
Incorrect Loop Circle on watch with Manual Temp Basal active

### ISSUE THREAD

**Issue by Trpl7ca** [LoopKit/Loop#1779]
When a Manual Temporary Basal is started on the Phone, The green circle opens to show correct Loop status. However, on the watch the circle stays closed which in incorrect.
I would expect the watch to match the correct status of Loop which is open Loop with an open green circle.

13 Pro
Series 7 watch

IOS 15.6.1
Watch 8.7

git revision b584bcd

![incoming-E50755F6-F369-43E1-B0AC-448B54EE8155](https://user-images.githubusercontent.com/52380252/186015441-88019cc9-85a4-407b-b0ee-fda544b2b8dc.PNG)

![IMG_1594](https://user-images.githubusercontent.com/52380252/186015413-07d816bb-4872-44e5-9753-cae12ba259b5.PNG)

**CGM**
G6

**Pump**
 Dash

**Comment by IsThisPaul** [comment]
Can confirm this is still an issue with Apple Watch Ultra and Loop 3. Have investigated but had trouble finding my way around the watch app code and couldn’t resolve.
