### ISSUE TITLE
'carthage bootstrap' command cause errors

### ISSUE THREAD

**Issue by roeyba** [LoopKit/Loop#1780]
**Describe the bug**
I would like to developmy own code directly in a non-workspace repository, as you mentioned in the wiki page: https://github.com/LoopKit/Loop/wiki
i went to terminal, cd to the Loop directory, and run the command 'carthage bootstrap'
it showed my a fatal error :
_________________________________________________
*** Checking out MKRingProgressView at "f548a5c64832be2d37d7c91b5800e284887a2a0a"
*** Checking out LoopKit at "3a67f4ac7a1f2484f8527304eb14f21e30f6ca95"
*** Checking out dexcom-share-client-swift at "b9acf057851271aea0b5759c3062acd58ed9e8f9"
*** Checking out rileylink_ios at "8125112c66f53b0f3e3693fd2486426111a37ca0"
*** Checking out CGMBLEKit at "4fea57fb346ab7480c9740ec813bb58acb7fa686"
*** Checking out Amplitude-iOS at "de32f16cf1d4d83002bafa31b0aab129b991f82b"
*** Checking out G4ShareSpy at "c80eedb4260b47fdad56b1c568275f8ad1b814a5"
*** Checking out SwiftCharts at "0.6.5"
*** xcodebuild output can be found in /var/folders/6j/v9xqt2bs6p7glm6j043s1l380000gq/T/carthage-xcodebuild.NULjGe.log
*** Building scheme "Amplitude_macOS" in Amplitude.xcworkspace
*** Building scheme "Amplitude_iOS" in Amplitude.xcworkspace
A shell task (/usr/bin/xcrun lipo -create /Users/roeybenarieh/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Intermediates.noindex/ArchiveIntermediates/Amplitude_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude /Users/roeybenarieh/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude -output /Users/roeybenarieh/Downloads/BuildLoop/Loop-220815-0856/LoopWorkspace/Loop/Carthage/Build/iOS/Amplitude.framework/Amplitude) failed with exit code 1:
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/roeybenarieh/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Intermediates.noindex/ArchiveIntermediates/Amplitude_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude and /Users/roeybenarieh/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude have the same architectures (arm64) and can't be in the same fat output file

Building universal frameworks with common architectures is not possible. The device and simulator slices for "Amplitude" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.
_______________________________________________________________________

So I used the 'carthage bootstrap --use-xcframeworks' and than there was another error:
__________________________________________________
*** Checking out SwiftCharts at "0.6.5"
*** Checking out rileylink_ios at "8125112c66f53b0f3e3693fd2486426111a37ca0"
*** Checking out dexcom-share-client-swift at "b9acf057851271aea0b5759c3062acd58ed9e8f9"
*** Checking out Amplitude-iOS at "de32f16cf1d4d83002bafa31b0aab129b991f82b"
*** Checking out LoopKit at "3a67f4ac7a1f2484f8527304eb14f21e30f6ca95"
*** Checking out CGMBLEKit at "4fea57fb346ab7480c9740ec813bb58acb7fa686"
*** Checking out MKRingProgressView at "f548a5c64832be2d37d7c91b5800e284887a2a0a"
*** Checking out G4ShareSpy at "c80eedb4260b47fdad56b1c568275f8ad1b814a5"
*** xcodebuild output can be found in /var/folders/6j/v9xqt2bs6p7glm6j043s1l380000gq/T/carthage-xcodebuild.dLWrGw.log
*** Building scheme "Amplitude_macOS" in Amplitude.xcworkspace
*** Building scheme "Amplitude_iOS" in Amplitude.xcworkspace
*** Building scheme "Amplitude_watchOS" in Amplitude.xcworkspace
*** Building scheme "Amplitude_tvOS" in Amplitude.xcworkspace
*** Building scheme "Shared-watchOS" in LoopKit.xcodeproj
*** Building scheme "Shared" in LoopKit.xcodeproj
*** Building scheme "Shared-watchOS" in ShareClient.xcodeproj
*** Building scheme "Shared" in ShareClient.xcodeproj
*** Building scheme "Shared-watchOS" in CGMBLEKit.xcodeproj
*** Building scheme "Shared" in CGMBLEKit.xcodeproj
*** Building scheme "Shared" in G4ShareSpy.xcodeproj
*** Building scheme "MKRingProgressView" in MKRingProgressView.xcodeproj
*** Building scheme "Shared" in RileyLink.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun dsymutil /Users/roeybenarieh/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/rileylink_ios/8125112c66f53b0f3e3693fd2486426111a37ca0/Build/Products/Release-iphonesimulator/OmniKit.framework/OmniKit -o /Users/roeybenarieh/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/rileylink_ios/8125112c66f53b0f3e3693fd2486426111a37ca0/Build/Products/Release-iphonesimulator/OmniKit.framework.dSYM

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6j/v9xqt2bs6p7glm6j043s1l380000gq/T/carthage-xcodebuild.dLWrGw.log
__________________________________________________
the log file:
https://gist.github.com/roeyba/824eec64d033b98ee03c0ca5330cee03

**To Reproduce**
1. cd the Loop directory
2. type carthage bootstrap --use-xcframeworks

**Expected behavior**
no errors while using carthage to handle all dependencies

**Loop Version**
 - Version Number: 2.2.9
 - Repo: [LoopKit/Loop, Katie, etc]

**Comment by ps2** [comment]
Carthage builds are no longer supported. Workspace is the only build method that works currently.
