### ISSUE TITLE
On Unable to Reach Pod screen: Deactivate Pod button should be colored Red, not Blue

### ISSUE THREAD

**Issue by BecCooney** [LoopKit/Loop#1781]
**Describe the bug**
I received the following screenshot from my daughter. She was separated from her devices during swimming, but hadn't seen this screen before, so she captured it. The resolved itself once she came into range of her phone, however, when looking at the screenshot my 13 yr old picked up on the fact that Deactivate Pod is a destructive action, so the button should be colored Red, not Blue.

![IMG_20220822_211517](https://user-images.githubusercontent.com/34292869/186729823-9756c074-7ad2-4e8f-9743-9e2cfbc2d234.jpg)

**Attach an Issue Report**
The behavior itself is expected, this is just a minor UI bug

**To Reproduce**
1. Remove comms between pump and cellular device
2. I believe there is a modal displayed with a `Learn More` button (or something similar)
3. Tap `Learn More`
4. Unable to Reach Pod screen displays. Deactivate pod button should be colored Red, not Blue.

**Expected behavior**
I expect the Deactivate Pod button to be colored Red

**Screenshots**
![IMG_20220822_211517](https://user-images.githubusercontent.com/34292869/186731685-e6068c9b-233f-4f6b-9fa9-c1826d8c7307.jpg)

**Phone**
 - Hardware: iPhone SE (2022)
 - OS Version: 15.6.1

**Loop Version**
 - Version Number: 2.3.0
 - Repo: Dev Workspace (Build 57 - Downloaded 8/15/22)

**CGM**
 - Device:  Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: DASH
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by ps2** [comment]
Fixed for [eros](https://github.com/ps2/rileylink_ios/commit/8fe47d7441f76210566d27e248de59642b7a4328) and [dash](https://github.com/LoopKit/OmniBLE/commit/211173ef5351f8dde1d5bbd6d297e5ab19227f31)
