### ISSUE TITLE
Loss of dose records caused by force kill or crash.

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#1786]
We have at least one [recorded case](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/0x31.20Eros.20pod.20fault.20with.20Loop.20dev) of a user killing the app at an inopportune time; after a temp basal was issued to a pod, but before the PumpManager recorded the pending dose and Loop persisted the state.

To prevent this kind of loss of state, particularly on pumps that do not have their own history, we should persist doses before issuing them. If the app should be killed or crash before Loop marks the dose as successfully issued, the app can use the same technique used in unacknowledged command recovery to determine if the device received the command. We can likely even make use of the same structures for recording the pending command.

**Comment by ps2** [comment]
Another option to deal with this is to check delivery flags on status responses and evaluate for conflict with Loop tracking. But we still loose information like start time, rate, volume, etc.

**Comment by bewest** [comment]
Now that #1834 is closed, does this need additional testing; is there any impact on release?
