### ISSUE TITLE
Profile is never uploaded to Nightscout because defaultRapidActingModel is always null

### ISSUE THREAD

**Issue by diyaps** [LoopKit/Loop#1787]
**Describe the bug**
For new install, loop will never upload profile to Nightscout.
This will cause remote bolus menu cannot be showed in nightscout.
The reason is "defaultRapidActingModel" is always null.

**Attach an Issue Report**
 [Loop](https://github.com/LoopKit/Loop/files/9543186/Loop.Report.2022-09-12.01_38_16.08_00.md) 

**To Reproduce**
1. Install loop on device(New install NOT upgrade)
2. Finish all setup.
3. create and activate a override
4. Check whether you can see "Remote bolus" menu in Nightscout

**Expected behavior**
Profile can be uploaded to Nightscout
Remote bolus can be shown

**Screenshots**

**Phone**
 - Hardware: [iPhone 7]
 - OS Version: [iOS 15.6.1]

**Loop Version**
 - Version Number: [2.3.0(57)]
 - Repo: [LoopKit/Loop]

**CGM**
 - Device: [Remote NS]
 - Manager app: [N/A]

**Pump**
 - Manufacturer: [Medtronic]
 - Model: [723]
 - Firmware version: [2.3A ]

**Additional context**
I checked the code, defaultRapidActingModel is always null. I think this value somehow should be inited.

**Comment by diyaps** [comment]
[](url)
[Loop Report 2022-09-12 01_38_16 08_00.md](https://github.com/LoopKit/Loop/files/9543186/Loop.Report.2022-09-12.01_38_16.08_00.md)

**Comment by ps2** [comment]
Thanks for catching this! Fixed here: https://github.com/ps2/NightscoutService/commit/46580f4f979b4ed27e6a4d68586ccd5e6c4d0c0f
