### ISSUE TITLE
duplicate sgv entries in Nightscout

### ISSUE THREAD

**Issue by Joerg-Schoemer** [LoopKit/Loop#1788]
**Describe the bug**
Loop writes after approximately 3h a duplicate sgv entry. 
One with device: "loop://\<phone name\>" and another with device: "loop://Dexcom/G6/21.0".

**Attach an Issue Report**
[Loop Report 2022-09-11 01:50:59+02:00.md](https://github.com/LoopKit/Loop/files/9550831/Loop.Report.2022-09-11.01.50.59%2B02.00.md)

**Expected behavior**
There should be only one entry of a CGM reading.

**Phone**
 - Hardware: iPhone 7
 - OS Version: iOS 15.6.1

**Loop Version**
 - Version Number: 2.3.0 (57)
 - Repo: LoopKit/Loop
 - Branch: dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Dash

### debugging

get the duplicate readings in your mongodb with:
```js
config.set("displayBatchSize", 10000)

print(
    JSON.stringify(
        db.entries.aggregate( 
            { 
                $match: { 
                    device: { $exists: true },
                    type: 'sgv'
                } 
            }, 
            { 
                $group: { 
                    _id: { $substr: [ '$sysTime', 0, 16 ] }, 
                    oids: { $addToSet: '$$ROOT' }  
                } 
            }, 
            {
                $project: {
                    _id: 1, 
                    oids: 1,
                    size_of_oids: { $size: '$oids'}
                }
            },
            { 
                $match : { 
                    size_of_oids : { $gt: 1 } 
                } 
            },
            {
                $project: {
                    _id: 1, 
                    oids: 1,
                    items: [
                        {
                            created_at: { 
                                $toDate: {
                                    $getField: { 
                                        field: '_id',
                                        input:  { $arrayElemAt: [ "$oids", 0 ] }
                                    }
                                }
                            },
                            device: {
                                $getField: { 
                                    field: 'device',
                                    input:  { $arrayElemAt: [ "$oids", 0 ] }
                                },
                            },
                        },
                        {
                            created_at: {
                                $toDate: {
                                    $getField: { 
                                        field: '_id',
                                        input:  { $arrayElemAt: [ "$oids", 1 ] }
                                    }
                                } 
                            },
                            device: {
                                $getField: { 
                                    field: 'device',
                                    input:  { $arrayElemAt: [ "$oids", 1 ] }
                                },
                            },
                        }
                    ]
                }
            },
            { 
                $sort : { 
                    _id : -1 
                } 
            }  
        ).toArray(),
        null,
        2
    )
)
```
The disadvantage of this script is that it only finds the duplicates if the entries were made within the same minute.
e.g.:
```json
{
    "_id": "2022-09-11T18:18",
    "oids": [
      {
        "_id": "631e2687fc120c674de86ec1",
        "device": "loop://Dexcom/G6/21.0",
        "dateString": "2022-09-11T18:18:35.000Z",
        "type": "sgv",
        "date": 1662920315025.911,
        "direction": "Flat",
        "sgv": 155,
        "trendRate": 0.4,
        "trend": 4,
        "isCalibration": false,
        "utcOffset": 0,
        "sysTime": "2022-09-11T18:18:35.000Z"
      },
      {
        "_id": "631e5120fc120c674d4af74c",
        "device": "loop://Diabetes iPhone 7",
        "type": "sgv",
        "sgv": 155,
        "dateString": "2022-09-11T18:18:33.000Z",
        "date": 1662920313000,
        "isCalibration": false,
        "utcOffset": 0,
        "sysTime": "2022-09-11T18:18:33.000Z"
      }
    ],
    "items": [
      {
        "created_at": "2022-09-11T18:18:47.000Z",
        "device": "loop://Dexcom/G6/21.0"
      },
      {
        "created_at": "2022-09-11T21:20:32.000Z",
        "device": "loop://Diabetes iPhone 7"
      }
    ]
  },
```
The created_at is taken from the ObjectID of mongodb.

**Comment by Joerg-Schoemer** [comment]
This script shows number of entries per device
```js
config.set("displayBatchSize", 10000)

print(
    JSON.stringify(
        db.entries.aggregate( 
            { 
                $match: { 
                    type: 'sgv', 
                    device: { $exists : true } 
                }
            },
            { 
                $group: {
                    _id: { 
                        date: { $substr: [ '$dateString', 0, 10 ] },
                        device: '$device'
                    }, 

                    count: { $sum : 1 }
                } 
            },
            { 
                $sort: { _id: -1 } 
            } 
        )
        .toArray()
        ,null
        , 2
    )
)
```

**Comment by loudestnoise** [comment]
Hmm, I wonder is this related to having "Upload Readings" enabled in DIY Loop Settings - Dexcom G6 - Remote Data Synchronization?

![IMG_CBD510196371-1](https://user-images.githubusercontent.com/194853/189739183-77c8d34a-d621-40e0-82e7-4342efc42c75.jpeg)

**Comment by elnjensen** [comment]
> Hmm, I wonder is this related to having "Upload Readings" enabled in DIY Loop Settings - Dexcom G6 - Remote Data Synchronization?

Hi David - Yes, it is absolutely related to that, and it’s a bug in how that functionality behaves.  The bug is that, with that setting enabled, Loop is uploading duplicates of some of the BG readings, making the Mongo database that Nightscout is using grow faster than it needs to.  The expected behavior would be one uploaded value per unique glucose reading, 288 per day for continuous CGM operation.  Jörg is seeing 400-500 uploaded values per day.

**Comment by elnjensen** [comment]
Here’s some related discussion in Zulip: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Nightscout.20database.20size.20increasing.20with.20Dev

**Comment by ps2** [comment]
In the situation where both Loop and Dexcom are writing to Apple Health (Dexcom with a 3 hour delay), Loop should be deleting values it stored, and letting the Dexcom stored ones remain.  It should also be issuing a "delete" for its own records, and uploading the new Dexcom record.

It would be helpful if someone could dig in and determine which part(s) of the process I just described are not functioning as intended.

**Comment by Joerg-Schoemer** [comment]
Hi Pete,
I‘ve analyzed the data a few month ago and found out, that the timestamp (the ID) of the records in Dexcom and Loop differ within some seconds. Thus, each entry is considered as independent.

**Comment by ps2** [comment]
@Joerg-Schoemer Yep, I'm aware of the timestamp differences. That shouldn't matter; Loop basically deletes any of its values older than the ones that Dexcom writes, so matching them up isn't critical. But deleting its own records from HK should end up in issuing deletes for the Loop equivalent entries in NS.

**Comment by elnjensen** [comment]
> But deleting its own records from HK should end up in issuing deletes for the Loop equivalent entries in NS.

@ps2 Could you point out where this is (or should be) happening?  In looking through the NightscoutUploader code, I can see routines for `deleteTreatments` and `deleteTreatmentsByObjectID`, but no equivalent for `entries`, which I understand to be the NS labeling of glucose values.   The `deleteTreatments` functions get called in [`deleteDoses`](https://github.com/tidepool-org/NightscoutService/blob/a12dc1366af81eaaa392abb5ddd7910f68faf678/NightscoutServiceKit/Extensions/NightscoutUploader.swift#L128) and [`deleteCarbData`](https://github.com/tidepool-org/NightscoutService/blob/a12dc1366af81eaaa392abb5ddd7910f68faf678/NightscoutServiceKit/Extensions/NightscoutUploader.swift#L52), but again, I can't find corresponding calls that seems to deal with glucose entries.  [That file](https://github.com/tidepool-org/NightscoutService/blob/dev/NightscoutServiceKit/Extensions/NightscoutUploader.swift#L128) has `createCarbData`/`deleteCarbData` and `createDoses`/`deleteDoses` pairs, but the section on glucose entries only has `uploadGlucoseSamples` and nothing else. 

It's definitely possible that I'm missing something fundamental about how this is supposed to work, but so far I haven't been able to locate where the NS deletion of glucose samples happens.
