### ISSUE TITLE
App unresponsive after going back from Pod Expiry Reminder without time change (in new Pod process)

### ISSUE THREAD

**Issue by JeD-Q** [LoopKit/Loop#1792]
**Describe the bug**
After pairing a new pod I went into the expiration reminder setting and back without change. The app showed the "Setup complete" screen but was unresponsive. Closing and restart of the app solved the issue and afterwards everything seems to be normal. 

**Attach an Issue Report**
[Loop Report 2022-09-16 11:41:53+02:00.md](https://github.com/LoopKit/Loop/files/9583254/Loop.Report.2022-09-16.11.41.53%2B02.00.md)

**To Reproduce**
1. Pair a new pod
2. Click on expiration reminder
3. Go back without time change
4. See error: unresponsive app

**Expected behavior**
App should allow tapping on button "Finish Setup"

**Screenshots**
Attached
![image](https://user-images.githubusercontent.com/12474913/190618473-8a62cba6-e8f6-4440-9bec-d8c3044f17d5.png)

**Phone**
 - Hardware: iPhone XS
 - OS Version: 15.6.1

**Loop Version**
 - Version Number: 2.3.0 Dev
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: insulet
 - Model: Dash
 - Firmware version: 4.10.0

**Additional context**
It was just my third pod in loop.

**Comment by ps2** [comment]
Thank you for the report. I am unable to reproduce on latest dev. I took a look at the logs, and didn't see anything unusual around the time of, or right before, restart, at 2022-09-16 06:14:31 +0000. 

Will keep this open for others to add to if they encounter this.

**Comment by JeD-Q** [comment]
Thanks for checking. Closing would be ok for me and if I encouter the issue again, I will reopen and try to better describe, what I did. Maybe I missed something in the steps.

**Comment by JeD-Q** [comment]
I tried to reproduce with my described steps for another three pods, but could not reproduce. So maybe my steps where not correctly described.
