### ISSUE TITLE
Add indicator when RileyLink device is not connected

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1793]
**Is your feature request related to a problem? Please describe.**
Per request from Pete Schwamb 
- the rileylink device is suggested to user if it has previously been connected regardless of whether that connection is still active
- need to add an indicator to the user that the connection is not working at that time for MDT pump managers

**Describe the solution you'd like**
Please see this zulipchat link
* https://loop.zulipchat.com/#narrow/stream/144182-development/topic/MDT.20Testing/near/299204186

**Describe alternatives you've considered**

**Additional context**
Batteries on Orange Link Pro needed to be changed

**Comment by ps2** [comment]
This is for the MinimedPumpManager (which uses the UIKit based RL selector).  Eros pump manager already has a connection indicator (although testing now it seems buggy).
