### ISSUE TITLE
Loop suspends pump during bolus

### ISSUE THREAD

**Issue by charlesbdudley** [LoopKit/Loop#1795]
**Describe the bug**
I entered a carb entry, and bolused the recommended amount of 2.6 units. After 1.7 units were delivered, my pump was unexpectedly suspended (without input from me).

**Attach an Issue Report**
[Loop Report 2022-09-17 17:47:35-07:00.md](https://github.com/LoopKit/Loop/files/9592872/Loop.Report.2022-09-17.17.47.35-07.00.md)

**To Reproduce**
I'm unable to reproduce without bolusing for a meal again, but will followup if I notice this happening again.

**Screenshots**

![4294376B-AEE1-4521-A594-7519C915BD69](https://user-images.githubusercontent.com/618478/190881335-e9a35bca-f778-478d-badf-1b68e0b4e10d.PNG)
![822B3F35-B51E-4CA3-8A1F-17E21AFE6EA2](https://user-images.githubusercontent.com/618478/190881337-5413a0b1-3051-4619-ae0b-36b09fd294fe.PNG)

**Phone**
 - Hardware: iPhone 14 Pro
 - OS Version: 16.0.1 (20A371)

**Loop Version**
 - Version Number: 2.2.9
 - Repo: LoopKit/Loop#master

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 522
 - Firmware version: 2.4A1.1

**Comment by elnjensen** [comment]
Any errors on the pump screen?  If the pump detects occlusion (more likely during a bolus than at other times) it will suspend itself. 

I know you're past it now, but maybe something to look for if it happens again.

**Comment by ps2** [comment]
When a bolus is initiated, the bolus progress widget is activated. This widget has no confirmation, and is (purposefully) easy to trigger. This looks like an accidental triggering of that widget.

**Comment by ps2** [comment]
Thanks for the report, and do reopen if you see if happening more and know it's not accidental cancellation.

**Comment by charlesbdudley** [comment]
> 



> Any errors on the pump screen? If the pump detects occlusion (more likely during a bolus than at other times) it will suspend itself.
> 
> I know you're past it now, but maybe something to look for if it happens again.

Thanks for the quick response! Nothing out of the ordinary on the pump itself. I took a photo of it when it suspended:

![image](https://user-images.githubusercontent.com/618478/190934248-be85b546-38d4-4eab-8e95-b14f4966ac54.jpeg)

**Comment by charlesbdudley** [comment]
> When a bolus is initiated, the bolus progress widget is activated. This widget has no confirmation, and is (purposefully) easy to trigger. This looks like an accidental triggering of that widget.

Thanks, Pete. I'm 75% certain I didn't tap the bolus widget to cancel, but definitely not 100% :). I haven't had any issues since, so sounds like it's safe to close. I'll post back if anything changes.
