### ISSUE TITLE
Support for Dexcom G7

### ISSUE THREAD

**Issue by snics** [LoopKit/Loop#1800]
**Describe the solution you'd like**

Similar to the Dexcom G6, the G7 should also be connected.

**Additional context**

According to Dexcom German, it is planned to deliver the G7 in a short time to customers who want to inherit it. So my question is it planned to include this also in Loop?

**Comment by andrew-dixon** [comment]
I've just had an email from Dexcom UK & Ireland saying G7 is now available and it is showing on their online shop, so I would be interested in this support as well.

**Comment by savelik** [comment]
I am ordering G7 in the UK, will wait for compatibility with loop.  I can send a few sensors (they have an embedded transmitter now) to whoever can add the feature.

**Comment by rodig03** [comment]
Of course everyone wants to get it supported. 
Please follow the discussions on zulipchat and on different Facebook groups. 
However, G7 is using a different way to send data to the mobile phones so the G6 way to listen to the data is not working anymore (e.g. there is no transmitter ID anymore). 

As soon as the first devices can be tested, volunteers can capture how data is exchanged and help decode the data traffic.
You can help as much as anyone else in the community. 

There is a `solution that works right` now as well: upload the data to Dexcom (for followers) and set Loop to use then Dexcom Share as input. Works perfectly as long as the device is connected to the internet, but not if not, e.g. in the cellar.

**Comment by gigich** [comment]
There is a separate branch G7 avaiable. You can test it and give feedback!

**Comment by andrew-dixon** [comment]
@gigich I don't see any branch called `G7`, is it just included on in the `dev` branch?

**Comment by sethgagnon** [comment]
https://github.com/LoopKit/LoopWorkspace/pull/25

**Comment by rodig03** [comment]
Hi Nico,Of course everyone wants to get it supported. Please follow the discussions on zulipchat and on different Facebook groups. However, G7 is using a different way to send data to the mobile phones so the G6 way to listen to the data is not working anymore (e.g. there is no transmitter ID anymore). As soon as the first devices can be tested, volunteers can capture how data is exchanged and help decode the data traffic.You can help as much as anyone else in the community. There is a solution that works right now as well: upload the data to Dexcom (for followers) and set Loop to use then Dexcom Share as input. Works perfectly as long as the device is connected to the internet, but not if not, e.g. in the cellar. Von meinem iPhone gesendetAm 21.09.2022 um 17:32 schrieb Nico Swiatecki ***@***.***>:﻿
Describe the solution you'd like
Similar to the Dexcom G6, the G7 should also be connected.
Additional context
According to Dexcom German, it is planned to deliver the G7 in a short time to customers who want to inherit it. So my question is it planned to include this also in Loop?

**Comment by ps2** [comment]
@rodig03 I have decoded the important bits of the G7 protocol, and there *is* a G7 integration working (in an alpha state) on a testing branch (see above).

**Comment by snics** [comment]
@ps2 wanted to ask if this already works well since I have seen that in version 3 of the G7 support team. If it works well I would wash on the G7 in the next supply.

**Comment by savelik** [comment]
> @ps2 wanted to ask if this already works well since I have seen that in version 3 of the G7 support team. If it works well I would wash on the G7 in the next supply.

It works well. But this is the procedure when changing sensors:

1. activate new sensor in the dexcom app
2. Remove the g7 from loop
3. When the sensor is warmed up, force-close loop
4. Open loop, add g7, it will have “searching” status. Within 10 minutes it should start pulling the data

good luck!

**Comment by marionbarker** [comment]
Thanks for the steps. I’ll add that to LoopDocs.
