### ISSUE TITLE
Message on bolus rec screen incorrectly references safety limit when prediction is above limit

### ISSUE THREAD

**Issue by elnjensen** [LoopKit/Loop#1803]
**Describe the bug**
In some circumstances, when the user presses the bolus button to request a manual bolus and no bolus is recommended, the message on the bolus screen will say "Your glucose is below or predicted to go below your glucose safety limit" when in fact all points in the predicted glucose are above the safety limit.   The message should instead be the one that says "Based on your predicted glucose, no bolus is recommended."  Issue report is attached, showing that all predicted points were above safety threshold. 

**To Reproduce**
Not 100% clear how to reproduce, but anecdotally it seems to happen when glucose is trending downward, with eventual BG below target range but above safety limit. 

**Expected behavior**
The message should be "Based on your predicted glucose, no bolus is recommended." 

**Screenshots**

**Phone**
 - Hardware: iPhone 13 mini
 - OS Version: iOS 15.4.1
 
**Loop Version**
 - Version Number: 2.3.0 (57), gitRevision: c145fd9 (with cosmetic modifications of my own) 
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Medtronic 522,  2.1A 1.1 0B 0B

**Additional context**
See also discussion at https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Graph.2Fprediction.20discrepancy.3F 

![IMG_5126](https://user-images.githubusercontent.com/2545845/192398464-d68eb46c-9443-482b-b379-5e78be2e930b.PNG)
![IMG_5127](https://user-images.githubusercontent.com/2545845/192398508-44770f34-881b-4ef9-aa2b-6f6aa05fe9a5.PNG)

[Loop Report 2022-09-24 09:43:32-04:00.md](https://github.com/LoopKit/Loop/files/9650257/Loop.Report.2022-09-24.09.43.32-04.00.md)

**Comment by aug0211** [comment]
👍

**Comment by aug0211** [comment]
![IMG_1565](https://user-images.githubusercontent.com/659845/227784191-5495a0d7-6ea7-48fd-8a5b-7214dcf16d20.jpeg)
![IMG_1566](https://user-images.githubusercontent.com/659845/227784193-4858319a-0c74-4352-99a4-e3247c25bf02.jpeg)
![IMG_1567](https://user-images.githubusercontent.com/659845/227784195-ff10e28a-cf2e-438d-9d6c-1626728895b8.jpeg)
![IMG_1568](https://user-images.githubusercontent.com/659845/227784196-ef9f7df3-bcc9-412c-9920-85b0af7796ef.jpeg)
![IMG_5017](https://user-images.githubusercontent.com/659845/227784200-e41dcf75-9dd3-4359-a7de-b360f974618f.jpeg)
![IMG_50A49707B766-1](https://user-images.githubusercontent.com/659845/227784202-7bb9487f-ab6e-47c1-bd8a-0a366bffd59a.jpeg)

**Comment by aug0211** [comment]
[Loop Report 2023-03-25 20:42:36-04:00.zip](https://github.com/LoopKit/Loop/files/11071993/Loop.Report.2023-03-25.20.42.36-04.00.zip)

**Comment by aug0211** [comment]
Still an issue, not fixed as of 4/24/2023.

**Comment by aug0211** [comment]
+1 agree. Loop should display accurate predictions and messaging for safety warnings.

**Comment by elnjensen** [comment]
Still an issue as far as I can tell.

**Comment by aug0211** [comment]
Agree. This safety issue does not seem to be resolved.

**Comment by aug0211** [comment]
Confirmed this is still an issue in dev.

**Comment by aug0211** [comment]
Issue persists after force close and reopen of Loop.

**Comment by aug0211** [comment]
Appears to resolve after toggling Loop open/closed.

**Comment by aug0211** [comment]
@elnjensen do you use Loop patches? Wondering if this could be related to basal lock causing an out of sync status - something to do with prediction getting mixed up between basal bring on vs off?

**Comment by aug0211** [comment]
Shortly after toggling loop open/closed, this issue arose again. That seems like a short term fix. I did not check to be certain but I believe the next loop cycle, the issue came back.

**Comment by elnjensen** [comment]
@aug0211  No, I don't use Loop patches. I haven't seen the issue for a while, but haven't been looking that closely.  One thing to do is to save an Issue Report when you see it, and then search through there for `PredictedGlucose`, to see the actual values in the forecast and what the minimum is.

**Comment by aug0211** [comment]
Issue again observed tonight.

Loop showed 71 eventual BG prediction.

Loop issue report matches.

Loop's API provides an eventual predicted BG of 44.

Min BG also does not match, though I am unable to find that in the issue report generated.

**Comment by ps2** [comment]
This is basically because we assume low temps will not continue when calculating a manual bolus. The forecast you see on the main loop screen *does* include glucose effects from the future portion of a low temp.

Relatedly, the forecast trace that was being uploaded to NS was using the version that does not include future low/high temps.  This has just changed in dev with this commit: https://github.com/LoopKit/Loop/commit/52ea3be839f971ffc55e464dcde9d23c13e952ee

**Comment by aug0211** [comment]
Awesome. Will plan to test this out once back in the country and report back with our experience. Very excited about this, thanks Pete.

**Comment by aug0211** [comment]
I pulled the latest dev and rebuilt on Monday 10/2.

I applied customizations through the build select script and manually layered in changes I always make - like changing the starting point for carb entry on the Watch down to 2g from 15, adjusting time picker increments from 15 down to 10 minutes, etc.

I think we expected this issue to be done now, but I did still see it yesterday morning 10/4.

I grabbed screen shots and logs, can share directly if helpful.

**Comment by ps2** [comment]
@aug0211 The particular issue described in this ticket of not allowing a bolus when the forecast (not including future low-temps) drops below the suspend threshold is still there; nothing is expected to change in that regard. My note about was about the separate (but also referenced in this ticket) issue of nightscout showing the truncated version; that issue has been fixed, so now you should expect NS to show the same forecast as Loop in this situation.

**Comment by aug0211** [comment]
Ok this was the issue I noticed. NS and Loop BG predictions are not matching. 

![Image](https://github.com/LoopKit/Loop/assets/659845/66d73b0b-fbbb-4a40-ab2d-99cb35f69820)
![Image](https://github.com/LoopKit/Loop/assets/659845/6eeb5f1e-203b-4997-a2cf-990f2f0f0dcb)
![Image](https://github.com/LoopKit/Loop/assets/659845/d112060a-4635-42b3-a602-d455a864d00e)
![Image](https://github.com/LoopKit/Loop/assets/659845/dd7362ea-5f22-4cbb-b860-f1015b7a5039)
![Image](https://github.com/LoopKit/Loop/assets/659845/7226a769-c4f4-4fe8-88fe-b8a7d7c03b94)

If an issue report is helpful, I can DM this to you as well.

**Comment by aug0211** [comment]
Commenting to keep active. Logs were provided October 5 via Zulip DM after this issue was observed again post update.

**Comment by aug0211** [comment]
Commenting to keep active. I do not believe this has been resolved yet.

**Comment by marionbarker** [comment]
Bump

**Comment by oliverstory** [comment]
I have observed this issue and been confused but generally just accepted it as something I didn't fully understand about the algorithm. 

Based on @ps2 's earlier comments the behaviour of the bolus recommendation is as expected. 

Here is a suggestion for a message to explain more precisely what's going on.

    No bolus recommended 
    Low temporary basal rates are currently in place to prevent your glucose falling below the glucose safety limit of XXX

I'm guessing that enacting this change would require comparing the forecast _without currently in place temp basals_ as used to calculate a bolus recommendation to the forecast _with currently in place temp basals_ as presented on the main screen, to distinguish from the case where glucose is below or predicted to be below the glucose safety limit even with current temp basals. So it may not be as simple as @elnjensen 's suggested message, which is correct by being more generic than the current message.

Consolidating @ps2 's explanation of the behaviour:

> This is basically because we assume low temps will not continue when calculating a manual bolus. The forecast you see on the main loop screen does include glucose effects from the future portion of a low temp.
> The particular issue described in this ticket of not allowing a bolus when the forecast (not including future low-temps) drops below the suspend threshold is still there; nothing is expected to change in that regard.

**Comment by ksilive** [comment]
@elnjensen based on ps2 response, do you propose to take this effect of the future lowering of your temp basal in calculating the bolus?
