### ISSUE TITLE
Loop Giving Too Much Insulin Mulitple times so that predicted amount is negative and boluses appearing multiple times in event history

### ISSUE THREAD

**Issue by hloop512** [LoopKit/Loop#1806]
Loop went red. Then orange link was put right next to pod. Loop went green, so hit triangles and gave a bolus. 15 and 20 minutes later auto boluses were made that then showed was going to be -109. Loop went red again. Then again with loop next to pod put in carbs for lunch. No insulin was recommended as expected. But then loop gave two autoboluses again with an expected negative bloodsugar amount. Loop has been running slow on the phone. It is an IPhone 7. 

Also, this is separate issue, but I included with this as it was happening at the same time. In the insulin delivery screen, even history, the boluses will show up multiple times even when they have ony been delivered once, so just repeat entries. I have noticed this happening after I change a pod. After closing and reopening the loop app, it goes back to just showing the boluses once. Sometimes it takes a while for the boluses to reappear and will only show what happend up to the pod change for 10 minutes or so. 

**Attach an Issue Report**
I attached the issues report. I took the report a few hours after as my daughter was not with me. 

**To Reproduce**
Not sure how to reporduce though this has happened once before when loop went red. 
**Expected behavior**
i did not expect it to give so much insulin but only what was needed to put in target range 
![68616970051__87EE7D46-AF5E-47E7-A7A9-DD2E8FA7616A 2 copy](https://user-images.githubusercontent.com/66181160/193145939-9f54e3e0-50d7-4157-b682-3f4b638bfb44.jpg)

**Screenshots**
![68616945562__1E31FCED-E8B1-4A90-9465-5974339FE1D7 copy](https://user-images.githubusercontent.com/66181160/193145962-3457428c-d837-4b1a-a0ca-0147779c8d7a.jpg)

**Phone**
 - Hardware: [e.g. iPhone XS] iPhone 7
 - OS Version: [e.g. iOS 12.0.1] 14.8

**Loop Version**
 - Version Number: [e.g. 1.9.2] v2.2.9
 - Repo: [LoopKit/Loop, Katie, etc] 

**CGM**
 - Device: [e.g. Dexcom G6] Decom g6
 - Manager app: [e.g. Dexcom App, Spike] Dexcom App

**Pump**
 - Manufacturer: [e.g. Medtronic] Omnipod
 - Model: [e.g. 723] pod
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]n/a

**Additional context**
[Loop Report 2022-09-29 14:00:33-07:00.md](https://github.com/LoopKit/Loop/files/9679178/Loop.Report.2022-09-29.14.00.33-07.00.md)

**Comment by akacase** [comment]
#1804 – seems related.
