### ISSUE TITLE
Loop dev crash on iOS 16

### ISSUE THREAD

**Issue by w-aurelien** [LoopKit/Loop#1808]
**Describe the bug**
When building and running loop dev, the app open and instead crashes.

**Expected behavior**
The problem happened after reopening the app. I was just able to do the onboarding.

**Screenshots**
<img width="1139" alt="Capture d’écran 2022-10-01 à 23 30 37" src="https://user-images.githubusercontent.com/100843604/193429418-fbc3b981-962e-4d07-a4cc-1de2a00c3333.png">

**Phone**
Hardware: IPhone 13
OS Version: 16.0.2

**Loop dev commit**
ca8a374

**CGM**
NightScout

**Pump**
No pump add

**Comment by ps2** [comment]
Thanks for the screenshot with stack trace. That's generally very helpful in diagnosing a crash. Unfortunately, I don't see any red flags here. If this can be reproduced, please reopen, and we'll see if we can get to the bottom of it.

**Comment by ps2** [comment]
Crash reports, found in Settings -> Privacy & Security -> Analytics & Improvements -> Analytics Data -> Loop-YYYY-MM-DD-HHMMSS.ips can also help us determine what is causing a crash.
