### ISSUE TITLE
Negative predicted range

### ISSUE THREAD

**Issue by jmKeenan** [LoopKit/Loop#1814]
**Describe the bug**
Daughter have 4.7 units on board, 13g COB, BG 186 (down 11 from previous reading), predicted BG 96-186, eventual BG 96. 40g of carbs were added for 25 minutes in the future, Loop suggested 2.25 dose. Dose was given, expected BG range changed to 48-158, eventual BG 95, current BG 158. Following reading, BG dropped to 149, expected BG ranged changed to -140 - 149, expected  BG -94.

Seems hard to understand the the prediction would change so markedly from one reading to the next (48 to -140)?

First reading after carbs were onboarded, COB was 48, but predicted min max was -130 - 120, expected BG -80

**Attach an Issue Report**
will do this when she comes home from school

**To Reproduce**
Cannot reproduce

**Expected behavior**
Did not expected expected BG to drop to negative numbers after giving a suggested bolus. Expected that expected BG would rise up significantly after carbs were on boarded.  IOB and COB were close to ratio (10:1) with slowing BG and basal temped off for more than 2 hours yet expected BG remained negative. At 90 minutes post last dosing, BG was 88 (-2 from previous), IOB was 1.95, COB was 21g, expected BG was -6 - 88, expected BG -3.

**Screenshots**

**Phone**
 - Hardware: iphone 8
 - OS Version: iOS 16

**Loop Version**
 - Version Number: latest master  (rebulit less than a week ago
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Omnipod
 - Eros
 - Firmware version: ?
<img width="1384" alt="Screen Shot 20
<img width="1411" alt="Screen Shot 2022-10-17 at 9 53 16 AM" src="https://user-images.githubusercontent.com/526176/196208397-d3b1dff4-72f7-491c-a59f-378366eaa08f.png">
22-10-17 at 9 53 31 AM" src="https://user-images.githubusercontent.com/526176/196208352-5708b2a9-6b66-483b-af26-d23f48aa16ee.png">

**Additional context**
<img width="1435" alt="Screen Shot 2022-10-17 at 9 58 40 AM" src="https://user-images.githubusercontent.com/526176/196208289-765b308d-bfef-4abe-a5c6-5e3d5408de4d.png">

**Comment by jmKeenan** [comment]
<img width="1384" alt="Screen Shot 2022-10-17 at 9 53 31 AM" src="https://user-images.githubusercontent.com/526176/196208746-c61696eb-31eb-4edb-8e40-128a8dd8372f.png">

**Comment by jmKeenan** [comment]
[Loop Report 2022-10-17 15:16:07-04:00.md](https://github.com/LoopKit/Loop/files/9803846/Loop.Report.2022-10-17.15.16.07-04.00.md)

**Comment by ps2** [comment]
Thanks. Issue reports are good for capturing the state of Loop at the time of a problem; for diagnosing something in the past, the critical device logs will have a lot more info. If you could capture those, upload them to a file sharing service, and share them with me (zulip DM would be good), I can take a look.

**Comment by jmKeenan** [comment]
@ps2 - we're still on Master, not on Dev - I couldn't figure out how to get critical device logs on Master. Is there a screenshot or something? 

I'm planning to move to dev soon FWIW
