### ISSUE TITLE
Hanging / red loop and apple health app hanging

### ISSUE THREAD

**Issue by scottf51** [LoopKit/Loop#1816]
**Describe the bug**
Loops appears to work normally for a number of hours (up to 24 hours)  and then just randomly starts hanging, at the point at which it hangs Apple Health seems to be unresponsive, which is likely what is causing loop to hang as far as I can see.

**To Reproduce**
Unsure as to the specific trigger , seemed to start having issues around the time I moved between timezone 

Only steps I can give are 

Install dev loop 
installed dexcom one app 
install sensor 
enable apple health 

start using , wait multiple days , maybe even a week , possible change of timezone, then issues start occurred once a day, I have done some more digging which I will outline later which points to a possible dexcom one app bug causing apple health issues.

**Expected behavior**
Loop functions normal / doesn't crash , this may not be under the control of loop, but still wanted to raise a bug report in case the data is useful and could be used to report bug to dexcom.

**Screenshots**
If applicable, add screenshots to help expl
[Loop Report 2022-10-23 00:17:54+01:00.txt](https://github.com/LoopKit/Loop/files/9845431/Loop.Report.2022-10-23.00.17.54%2B01.00.txt)
ain your problem.

**Phone**
 - Hardware: iPhone se 2020
 - OS Version:  iOS 16.0.3

**Loop Version**
 - Version Number:  Loop v2.3.0 (57) 
 - Repo: dev 

**CGM**
 - Device: Dexcom one 
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Dash
 - Firmware version: 

**Additional context**
Since apple health keeps crashing I started trying to clear it an noticed data seemed to keep coming back, so I did a full export of apple health data, this is after disabling iCloud for apple health and clearing 24 hours or so ago. What I see is dexcom one seemingly adding data from the entire past week to 10 days all at the same time , 20 or so mins before the apple health / loop crashed happened.

I grepped out the data specifically showing the times and data and see things like this, just before the crash the dexcom app was spewing data from over a week earlier, I am assuming this is not normal ? Looking at the loop entries they seem to make sense , ie you see start and end time roughly the same time as added to apple health time.

there are 2541 entries added within the space of 13 seconds at 22:03 - 22:04 going back to time of original install / insertions of dexcom one . I am not clear what triggers this data dump, as it can work for hours , sometimes almost a day, before apple health crashes, which I am thinking is likely to be due to this.

```
<Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Dexcom ONE" sourceVersion="852" unit="mmol&lt;180.1558800000541&gt;/L" creationDate="2022-10-22 22:03:57 +0100" startDate="2022-10-13 21:08:02 +0100" endDate="2022-10-13 21:08:02 +0100" value="9.71381">
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Dexcom ONE" sourceVersion="852" unit="mmol&lt;180.1558800000541&gt;/L" creationDate="2022-10-22 22:03:57 +0100" startDate="2022-10-13 21:13:02 +0100" endDate="2022-10-13 21:13:02 +0100" value="9.04772">
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Dexcom ONE" sourceVersion="852" unit="mmol&lt;180.1558800000541&gt;/L" creationDate="2022-10-22 22:03:57 +0100" startDate="2022-10-13 21:18:02 +0100" endDate="2022-10-13 21:18:02 +0100" value="8.77018">
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Dexcom ONE" sourceVersion="852" unit="mmol&lt;180.1558800000541&gt;/L" creationDate="2022-10-22 22:03:57 +0100" startDate="2022-10-13 21:23:02 +0100" endDate="2022-10-13 21:23:02 +0100" value="8.54815">
 <Record type="HKQuantityTypeIdentifierBloodGlucose" sourceName="Dexcom ONE" sourceVersion="852" unit="mmol&lt;180.1558800000541&gt;/L" creationDate="2022-10-22 22:03:57 +0100" startDate="2022-10-13 21:28:02 +0100" endDate="2022-10-13 21:28:02 +0100" value="8.32612">


```
[applehealth.txt](https://github.com/LoopKit/Loop/files/9845448/applehealth.txt)

I have included the dexcom apple health entries in text file 

I can try and raise this to Dexcom, but the chances of me getting a response from anyone other than a person that will ask me to restart and/or re-install are pretty low I would think.

Incidentally the timezone change would have happened on 15th October 2230 UTC - going back 5 hours to EST , but seems this is repeating data from before this. 

Maybe this is just a false alarm, but definitely looks weird. Planning on wiping and re-installing , possibly on a new phone as this is just making things super unstable right now, but happy to grab any other info if I still have it.

Not quite sure the need for Dexcom to be able to write to Apple health, as far as I can see we watch the data for ourselves (since the health data written by dexcom is 3 hours in the past) ? maybe we just use that as a trigger of some sort ? but if I could revoke the apple health permissions from dexcom and still have loop do its thing I may be able to work around this if it is the cause.

**Comment by scottf51** [comment]
Ok, turned off Apple health integration in dexcom one and still seem to be getting bg in loop so far. May have broken something, but if so, it is not apparent yet, so will leave it off and see if it crashes in next 24 hours.

**Comment by scottf51** [comment]
Still not crashing after multiple days so looks like that is it, I reported this to Dexcom through their contact us page, hopefully they will fix, until that point I will leave Apple Health integration disabled in Dexcom one app.

**Comment by ps2** [comment]
Interesting. Thanks for the digging. I think the batch changes on the `hk-auth-crash-fix` branch may help Loop process this large dump as well.

**Comment by bentiff** [comment]
Thank you! Thank you! Thank you!... I have been having the exact same problem for the last month!... Loop working perfectly for 2-3 or even 7-10 days... then bam! crashes and errors, been going out of my tiny mind, restarting phone multiple times, deleting all Apple Health Data over and over again (and yes alot of the time it just re-appears!) It sometimes manages to sort the problem then I relax for a few days and then the problem is back... Last two days I've really struggled to get Loop to work and was preparing for a fresh re-build / install, just revoked Apple Health permission from the Dexcom One app and loop is back pretty much instantly!... Here's hoping it carries on playing nice, but it's looking likely regarding your experience!... Thanks again.
