### ISSUE TITLE
Loop cycles complete just before new CGM values are received

### ISSUE THREAD

**Issue by damonbayer** [LoopKit/Loop#1817]
With Dash integration and autobolus, there are some scenarios where dosing decisions are issued >4 minutes after an old CGM value is received and <1 minute before a new CGP value is received. Thus, all dosing decisions are nearly 5 minutes "behind."

See [Zulip discussion](https://loop.zulipchat.com/#narrow/stream/312259-Omnipod-DASH/topic/Looping.20Interval.20with.20Dash) for issue report and proposed solutions.

**Comment by aug0211** [comment]
This issue may limit Loop’s ability to proactively mitigate hypos.

Basal insulin delivery may end up being left on longer than appropriate by missing a proactive 0 temp basal by one Loop cycle.
