### ISSUE TITLE
Manual Temp Basal Chart/Report Error?

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1819]
**Describe the bug**

When issuing a 0 U/hr manual temp basal (MTB), the reported and charted IOB decrease appears to be 10 minutes in the future. However, when requesting a manual bolus, the appropriate value is suggested. When cancelling MTB partway through, the chart/report appear correct.

**Attach an Issue Report**
Report attached at end.

**To Reproduce**
Scheduled Basal Rate is 12 U/hr.
Configure test phone by deleting all insulin, carb values.
Use a simulated CGM.
Apply 0 U/hr MTB for half hour.
Grab screenshots while testing - these are shown below.

Chart below indicates time since MTB started, reported IOB number, IOB I expect to see. (see first graphic below)

```
delta      IOB    apprxIOB
(minutes)
 0          0.0     0.0
 5         -3.0    -1.0
10         -4.0    -2.0
15         -5.0    -3.0
20         -6.0    -4.0
25         -5.98   -5.0
30         -5.96   -6.0
```

* Wait for IOB chart to report -4.0 U
   * Request a bolus recommendation - it suggests 1.6 U (do not accept)
   * see second graphic below
  
* Cancel the MTB with 20 minutes remaining, (before cancel, chart reports -4.0 U)
   * After cancellation, reported and charted IOB updates to -1.89 U
   * see third graphic below

**Screenshots**

* **Begin the 0 U/hr MTB (left side), used finger to read off the values (right side).**

![Loop_MTB_Report_Issue](https://user-images.githubusercontent.com/19607791/197655738-24ffb670-604d-4c48-b407-f88d9643ab3a.jpg)

* **After chart reports -4.0 U IOB (left side), request a bolus (but do not accept or deliver) (right side)**

![Loop_MTB_BolusRecommend](https://user-images.githubusercontent.com/19607791/197655853-ad79614a-aebf-4358-b5df-52c80aa45240.jpg)

* **While still reporting -4.0 U IOB (left side), cancel the MTB and chart updates to report -1.79 U IOB (right side).**

![Loop_MTB_Cancel](https://user-images.githubusercontent.com/19607791/197655971-e6edeb07-010e-4b1c-9f6a-cd93ebce3a38.jpg)

**Loop Version**
 - Loop-dev, commit ca8a374b

**CGM**
 - simulator

**Pump**
 - rPi DASH pod simulator

**Additional context**
I only tested manual temp basal.
[Loop Report 2022-10-24 17:51:54-07:00.md](https://github.com/LoopKit/Loop/files/9856240/Loop.Report.2022-10-24.17.51.54-07.00.md)

**Comment by ps2** [comment]
This is how the insulin model in Loop works. Insulin has a 10 minute delay, which applies to negative insulin as well. It's understandably not intuitive to think about "negative" insulin having a delay, but that's how the model works.

**Comment by marionbarker** [comment]
Thanks for the explanation.
