### ISSUE TITLE
Add a conservative closed-loop mode (limit automatic corrections, keep basal suspensions)

### ISSUE THREAD

**Issue by MooseV2** [LoopKit/Loop#1824]
**Is your feature request related to a problem? Please describe.**
As an Omnipod user who goes through >200 units of insulin through the lifespan of 1 pod, I often switch from closed loop to open loop when running low on reservoir insulin. My primary goal is to prevent an empty reservoir before 72 hours.

For example, if I have 50 units that needs to last another 24 hours, I can't trust that Loop won't automatically bolus 40 units as corrections, leaving only 10 units available when I need a minimum of 30 units for basal. As a workaround, I can turn switch to open-loop and manually provide a correction with a pen/syringe. However, this raises a problem when my predicted BG drops to an unsafe level, as open-loop will prevent Loop from automatically lowering or suspending the basal.

**Describe the solution you'd like**
A new hybrid mode between closed loop and open loop. I still want:

- Loop to lower my basal when my BG is falling too quickly and predicted BG is below target range
- Loop to suspend my basal when BG is below my suspend range

I do NOT want:

- Loop to automatically apply corrections above the target range
- Loop to suspend the basal for too long, as this can cause a boomerang effect and require an additional correction when the BG overshoots the target range*

[*] The second item may not be feasible, as Loop shouldn't cause a boomerang under "perfect" delivery settings.

As a discussion, perhaps there could be some "conservation factor" logic to determine when a correction should be made. The use case of this mode assumes the user will likely run out of insulin before the pod's EOL, but other factors can improve the QoL when using this mode. For example, corrections up to (eg) 50% higher than the basal rate within a 4 hour window may be permissible (eg up to 2 extra units assuming 1U/hr basal) as the user is unlikely to manually correct with such a low amount. This advanced usage may be outside of the scope of this feature request, and I'd be fine splitting it into a separate issue if there's a risk of bikeshedding this feature.

An additional "future request" would include a setting to automatically enable this new mode (or alert the user to enable this mode) when basal calculations determine that the `reservoir insulin < (required insulin for remaining pod time + some additional margin)`. I.e. ensure the user doesn't accidentally run out of insulin due to automatic corrections in closed loop mode.

**Describe alternatives you've considered**

I manually log my (pen/syringe) correction bolus in the Health app (see note below), which causes Loop to predict a target BG within range and not correct on its own. However, this is only temporary: if my predicted BG is above the correction range before I have the opportunity to manually correct, Loop will takeover and perform the bolus.

**Additional context**

As an alternative to entering data in the Health app, and as a feature which would compliment well with this request, see #1296 . That PR adds the ability to log manually dosed insulin from within Loop, which supports the use case of taking pen/syringe corrections on top of Looping.

**Comment by rajid** [comment]
Along these lines, my wife has been using Loop with Autobolus for a few years now (started when it was a set of changes not yet in the mainline).  She has found that sometimes all of the small autoboluses will use up the battery much faster and thus cause the pod to die early.  I'm wondering if this proposed change may at least indirectly address this as well.

**Comment by elnjensen** [comment]
I believe that most if not all of the goals of this request can be accomplished with existing Loop features, using overrides.  

If you have an override with a very wide correction range, say 100-300 mg/dl, then Loop will suspend insulin as desired to keep you from going low.  But unless you are projected to go *really* high, it wouldn't issue correction boluses or high temp basals. So you'd have to manage the manual doses to keep the forecast from going too high, but I think that would be required with any pod-saving strategy, no matter what you do.   

Regarding direct entry of manual insulin doses in Loop, that feature already exists in the dev branch, so it will be coming in the next release.

**Comment by billybooth** [comment]
> I believe that most if not all of the goals of this request can be accomplished with existing Loop features, using overrides.

👍
