### ISSUE TITLE
No suggestions while in open-loop mode. Glucose far out of range, but no temp basal or correction bolus suggested.

### ISSUE THREAD

**Issue by Nuddel69** [LoopKit/Loop#1827]
**Describe the bug**
I configured the loop app yesterday. Everything's working just fine in terms of normal pump usage, but none of the loop functionality seems to have any effect. No suggestions while in open-loop mode. Glucose far out of range, but no temp basal or correction bolus suggested. Even when setting overrides or pre-meal mode the app refuses to suggest basals. Glucose predictions are far of, though I'm aware this is likely caused by incorrect settings (which I'm currently in the process of adjusting). The bolus calculator works as expected (and so does all other normal pump functions), but I'd like to be able to try the app how it's intended without toggling closed-loop mode. 

**Attach an Issue Report**
[Loop Report 2022-11-11 21:40:34+01:00.md](https://github.com/LoopKit/Loop/files/9993104/Loop.Report.2022-11-11.21.40.34%2B01.00.md)

**Expected behavior**
As per my understanding of the wiki, open-loop mode should suggest temp-basals and boluses just like closed-loop mode, only difference being whether or not it will enact it on it's own. The loop app however, has yet to make a single suggestion on it's own.

**Screenshots**
![9A87F696-6149-4812-80D2-AC0C86E22688_1_102_o](https://user-images.githubusercontent.com/58176052/201427481-4a7052fb-17a1-4b10-929d-c3184dc8e073.jpeg)

**Phone**
 - Hardware: iPhone XS
 - OS Version: iOS 15.4.1

**Loop Version**
 - Version Number: Loop-dev commit ca8a374 (BuildLoopFixedDev script)
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Omnipod Dash

**Additional context**
I'm using the loop-dev version due to my using a dash system; I know it's not recommended, but unless it might be the cause for my current issue I'm willing to keep using it.

**Comment by marionbarker** [comment]
This is by design for Loop dev. 
What you are referring to is a debug feature left available in the prior releases. It was never intended as a training tool. 

https://loopkit.github.io/loopdocs/operation/loop/open-loop/#loop-2-open-loop

**Comment by Nuddel69** [comment]
> This is by design for Loop dev. What you are referring to is a debug feature left available in the prior releases. It was never intended as a training tool.
> 
> https://loopkit.github.io/loopdocs/operation/loop/open-loop/#loop-2-open-loop

Thank you for answering. I'm not quite sure I understand, is the open-loop _designed_ not to give basal suggestions - and if so, what's the point compared to traditional pump therapy? - or is it a feature lacking in loop dev due to it being made for development purposes? 

> When you are operating in Open Loop mode, Loop 2.2.x (or FreeAPS) offers recommendations for insulin delivery adjustment and displays them on the [HUD](https://loopkit.github.io/loopdocs/operation/loop-settings/displays/#heads-up-display).
> 
>     If you tap on the recommendation line, Loop applies that recommendation without asking for confirmation
>     This is true for temp basal and automatic bolus
>     To protect against accidental command of increased or decreased insulin dosing, make sure your phone is locked when not in use

    
I interpretted this section in the docs as saying open-loop mode should give suggestions for boluses and temp-basals. 
Please do forgive my asking dumb questions. I've reade the documentation, but I'm just starting out with the loop system.

**Comment by marionbarker** [comment]
Please - there no dumb questions. One of my volunteer jobs is to make sure LoopDocs is clear to those new to Loop as well as those who have been around for a while. It is very helpful to know which sections need updates. I will work to make this section more clear. 

However - since this is not a "code" issue but a learning issue, I opened an issue in the LoopDocs repository for this topic. Please close this one. (Closing only means the developers don't see it as an open issue. The conversation is still available. )

**Comment by marionbarker** [comment]
The LoopDocs issue that continues this conversation is https://github.com/LoopKit/loopdocs/issues/484

**Comment by Nuddel69** [comment]
Thank you for your help with this and work on loopdocs.
