### ISSUE TITLE
The insulin pump battery loses power quickly

### ISSUE THREAD

**Issue by hua5562** [LoopKit/Loop#1828]
Medtronic 722 uses LOOP, and the battery power consumption of insulin pump is extremely fast. Replace the power battery every 2-3 days, and the insulin pump battery will normally stand by without LOOP.

**Comment by ps2** [comment]
Dev has had some recent changes that might reduce the amount of history fetching. If you are already on dev, please update and see if the battery duration is better.

**Comment by hua5562** [comment]
发自我的iPhone------------------ Original ------------------From: Pete Schwamb  ***@***.***>Date: Wed,Jan 11,2023 0:59 PMTo: LoopKit/Loop ***@***.***>Cc: hua5562 ***@***.***>, Author ***@***.***>Subject: Re: [LoopKit/Loop] The insulin pump battery loses power quickly(Issue #1828)
Dev has had some recent changes that might reduce the amount of history fetching. If you are already on dev, please update and see if the battery duration is better.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/LoopKit/Loop/issues/1828#issuecomment-1378241194",
"url": "https://github.com/LoopKit/Loop/issues/1828#issuecomment-1378241194",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hua5562** [comment]
Thank you very much! I tried to use other insulin pumps to connect the closed loop, which lasted more than seven days! I will try the method you said to see if it is OK! Thank you again for your reply发自我的iPhone------------------ Original ------------------From: Pete Schwamb  ***@***.***>Date: Wed,Jan 11,2023 0:59 PMTo: LoopKit/Loop ***@***.***>Cc: hua5562 ***@***.***>, Author ***@***.***>Subject: Re: [LoopKit/Loop] The insulin pump battery loses power quickly(Issue #1828)
Closed #1828 as completed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/LoopKit/Loop/issues/1828#event-8198075952",
"url": "https://github.com/LoopKit/Loop/issues/1828#event-8198075952",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by prakashdevadas69** [comment]
Any update on this issue.
Even we have seen with Medtronic 722 and loop 3.2.3, battery drains in 2-3 days.
Where as Medtronic 715 battery stays for more days
