### ISSUE TITLE
CGM Simulator Delete does not work

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1829]
**Describe the bug**
Once the CGM simulator is selected as a CGM source, the details of what the simulator provide change as expected.
However, if the CGM simulator is then deleted, the last configuration from the CGM simulator continues to provide glucose readings on that phone in addition to whatever new CGM source is selected and even if no CGM is chosen.

Current solution - completely delete the app from the phone and rebuild.

**Attach an Issue Report**
There are several attached later.

**To Reproduce**
See Details Below

**Expected behavior**
I expect that when I delete any CGM source, that no more glucose should show up on the phone from the deleted source.

**Screenshots**
This is after 3 failed attempts to deleted the CGM Simulator.
The associated Loop Report is called: "Test_3_CGM_Ghosts_Loop Report 2022-11-14 085746-0800" and attached below.
Each CGM simulator setting was chosen so the traces would not overlap. Between each set, the simulated CGM was deleted and a new one added. This screenshot was taken the following morning with phone having no CGM selected overnight.
* Set one: constant of 180 with noise
* Set two: constant of 100 with noise
* Set three: sine wave at 70 with amplitude of 10, period of 2 hours, noise of 5
![IMG_0244](https://user-images.githubusercontent.com/19607791/201736939-d77370ad-a201-476a-8653-ba482b94d0d0.PNG)

**Details to Reproduce**
Nov 14, 2022
Repeat the experiment after completely deleting the app and all data including data from Apple Health.
Still using aq/missed-meal-detection branch for Loop and LoopKit.
* Add CGM: Select Share
  * imports 5 readings
   * wait for next reading at 09:12
   * delete CGM and wait 10 minutes
   * no further glucose entries appear after deletion
* Add CGM: Select NS as CGM
   * This missing 2 readings brought in immediately
   * wait for next CGM reading at 09:26
   * delete CGM and wait 10 minutes
   * no further glucose entries appear after deletion
* Add CGM Sim: Leave simulator at "No Data"
   * wait 10 more minutes, got no data and stale data was indicated
* Modify CGM Sim: change to sine wave 180, amp 10, noise 1, period 2 hr
   * Press done at 09:46
   * First reading at 09:47 was 180
   * Wait for 2 more readings
   * Vaues on graph and in health: 180, 184, 187
* Delete CGM at 09:59 
   * Wait 10 minutes
      * Vaues on graph and in health: 180, 184, 187, 190 at 10:07 
      * note the "ghost" simulator (after delete) comes in at odd times
* Add CGM Sim: sine wave 120, amp 10, noise 1, period 2 hr
   * As soon as add cgm simulator selected, new reading came in at 10:12 of 189
   * Press done at 10:12, but this was after new reading came in
   * rPi simulator had to be restarted (signal loss showing), connected with restart using ./pod -q
   * wait 10 minutes
   * Collect and attach screen shot of main Loop screen and Apple Health, and Loop Report

Screen Shot showing 2 traces from CGM Sim (one ghost, one current)
![IMG_8D21EA8DEE74-1](https://user-images.githubusercontent.com/19607791/201739051-6288d7de-e5b4-441f-9db1-ae9109b13b7f.jpeg)

Screen Shot showing Apple Health
![IMG_0C1F8A8DFFC0-1](https://user-images.githubusercontent.com/19607791/201739085-073bc846-f67d-44e0-831d-8158e8aba507.jpeg)

Associated Loop Report name: "Loop Report 2022-11-14 102929-0800"
[Loop Report 2022-11-14 102929-0800.md](https://github.com/LoopKit/Loop/files/10006071/Loop.Report.2022-11-14.102929-0800.md)

**Loop Version**
/Users/marion/Downloads/ManualClones/Loop-dev-missed-meals/LoopWorkspace
Folder: .
   branch: dev
    commit ca8a374bfc17e3a4950063cd4bcbe2ed835ef507 (HEAD -> refs/heads/dev, refs/remotes/origin/dev, refs/remotes/origin/HEAD)
Folder: Loop
   branch: aq/missed-meal-detection
    commit 759052a62092dd4531fae53653480b55a1079f6f (HEAD -> refs/heads/aq/missed-meal-detection, refs/remotes/aq/aq/missed-meal-detection)
Folder: LoopKit
   branch: aq/missed-meal-detection
    commit 38914b179b8aea0ce5188a0e49c9761f8f0d8c90 (HEAD -> refs/heads/aq/missed-meal-detection, refs/remotes/aq/aq/missed-meal-detection)

**Additional context**
Loop report attached below is from the earlier test prior to deleting the app and all health data.
[Test_3_CGM_Ghosts_Loop Report 2022-11-14 085746-0800.md](https://github.com/LoopKit/Loop/files/10006016/Test_3_CGM_Ghosts_Loop.Report.2022-11-14.085746-0800.md)

**Comment by marionbarker** [comment]
@dabear recommended this change:
```
diff --git a/MockKitUI/View Controllers/MockCGMManagerSettingsViewController.swift b/MockKitUI/View Controllers/MockCGMManagerSettingsViewController.swift
index 07b5ff0..6cb532a 100644
--- a/MockKitUI/View Controllers/MockCGMManagerSettingsViewController.swift     
+++ b/MockKitUI/View Controllers/MockCGMManagerSettingsViewController.swift     
@@ -14,7 +14,7 @@ import LoopKitUI
 import MockKit
 
 final class MockCGMManagerSettingsViewController: UITableViewController {
-    let cgmManager: MockCGMManager
+    weak var cgmManager: MockCGMManager!
 
     private let displayGlucoseUnitObservable: DisplayGlucoseUnitObservable
 
@@ -266,7 +266,7 @@ final class MockCGMManagerSettingsViewController: UITableViewController {
                 cell.textLabel?.text = "Glucose Value Alerting"
                 cell.switch?.isOn = cgmManager.mockSensorState.glucoseAlertingEnabled
                 cell.onToggle = { [unowned cgmManager] isOn in
-                    cgmManager.mockSensorState.glucoseAlertingEnabled = isOn
+                    cgmManager?.mockSensorState.glucoseAlertingEnabled = isOn
                 }
                 cell.selectionStyle = .none
                 return cell
```

tested:
Testing on a 6s running Loop-dev ca8a374 with that change in LoopKit.
* Modified the CGM simulator to frequency of 5 sec
* Exisiting CGM sim is sine wave 120 with amp of 55, noise of 5
* Delete CGM at 06:47, Loop CGM readings stop
* Last Apple Health glucose reading:
   * 06:47 110

* At 06:50, start a new CGM simulator; 180 constant with noise of 5, freq 5 s
* New CGM simulator working as expected.

* Delete simulator and add Dexcom Share, remove simulator data from health
* Only my Share data shows up

**Comment by marionbarker** [comment]
A PR to fix this has been submitted. Closing this issue.

[LoopKit PR 429: Fix Delete for MockCGM, was being retained](https://github.com/LoopKit/LoopKit/pull/429)

**Comment by ps2** [comment]
We should close issues when they land in the appropriate branch.
