### ISSUE TITLE
Loss of dose records caused by deleting pump shortly after bolus completes

### ISSUE THREAD

**Issue by bkhx** [LoopKit/Loop#1834]
I'm reporting a scenario in which Loop gives a bolus but doesn't record it, and so it re-doses via Automatic Bolus (or presumably by Temp Basal Only if that is the Dosing Strategy) resulting in a double dose of insulin actually delivered.

I intended to switch from Medtronic 722 to Omnipod Eros when the Medtronic reservoir became empty.  When the reservoir had 7 units remaining, I entered meal carbs, Loop calculated a bolus of 7.2 units, I accepted this and it was delivered.  (I saw the dosing circle finish and disappear on the Loop screen, and I saw the dosing finish on the pump screen.)  I then turned off the RileyLink and deleted the pump.  Next I turned on the other RileyLink for Omnipod Eros, added that pump and started the first pod in the usual way.  About 20 minutes later I noticed a series of automatic boluses that looked like a re-delivery of the 7.2 units, and the Insulin Delivery > Event History shows that the original bolus of 7.2 units did not appear in the history.

This feels like it has the same underlying mechanism as issue #1786 (Loss of dose records caused by force kill or crash) namely the original dose had not been persisted by the time the Loop display of the dosing circle had completed and disappeared from the screen.

iPhone 11 Pro, iOS 16.1.1, Loop v2.3.0 (57) built unmodified by the BuildLoopFixedDev Script from loopdocs > Loop-dev.

**Comment by ps2** [comment]
This is not have the same underlying mechanism as #1786, and has a different fix. Any pending (unreconciled) doses the MDT PumpManager has need to be reported to Loop as finalized when the PumpManager is removed.

**Comment by ps2** [comment]
Did you happen to capture an issue report for this?  There was a fix recently, and your build number would tell me if you had it or not.
