### ISSUE TITLE
Feature request: ability to enter non-pump insulin via the bolus screen

### ISSUE THREAD

**Issue by bkhx** [LoopKit/Loop#1839]
For me, administering insulin but not from the Omnipod is not a rare event.  If the pod is running out of insulin too soon before pod expiration, I'll take a large meal bolus by syringe to preserve the useful pod life.  And if I want to fix a high that's quickly getting out of control, I'll take some Afrezza.

In the past, the work-around that enabled Loop to account for this was via adding an insulin dose into Apple Health.  Of course we prefer to tell Loop of an insulin dose directly.  In 3.0, this feature is available on the Log Dose screen, but the access path is well-hidden:  Insulin Delivery detail > non-pump insulin > +

Adding non-pump insulin should be more easily discoverable and accessible.  The natural place to access this feature would be via a link or button from the Bolus screen.  This would be an easy two steps (insulin delivery button, non-pump insulin button.)  A further advantage is that this would be in the natural path from the carb entry screen when I want Loop's advice on the insulin quantity before I take Afrezza for a fast-carb meal or when catching up after I forgot to bolus for some carbs that I just ate.

**Comment by CosiP** [comment]
We usually do the same. We do injections when pod reservoir is low and we don’t want to change the pod and we add this in apple health. We also add a blood glucose check when there is no Dexcom in place. As far as being able to put a temp basal indefinitely (no end time discussed in another email) we use this as well.  My 15 years old son does have times were he has highs and lows without knowing what is going on and this feature helps a lot.  It is true that It used to happened more often in the past. Needs changed a lot depending on age.  Thanks again for all you do. This is really amazing work.SofiaOn Nov 23, 2022, at 12:09 PM, bkh ***@***.***> wrote:﻿
For me, administering insulin but not from the Omnipod is not a rare event.  If the pod is running out of insulin too soon before pod expiration, I'll take a large meal bolus by syringe to preserve the useful pod life.  And if I want to fix a high that's quickly getting out of control, I'll take some Afrezza.
In the past, the work-around that enabled Loop to account for this was via adding an insulin dose into Apple Health.  Of course we prefer to tell Loop of an insulin dose directly.  In 3.0, this feature is available on the Log Dose screen, but the access path is well-hidden:  Insulin Delivery detail > non-pump insulin > +
Adding non-pump insulin should be more easily discoverable and accessible.  The natural place to access this feature would be via a link or button from the Bolus screen.  This would be an easy two steps (insulin delivery button, non-pump insulin button.)  A further advantage is that this would be in the natural path from the carb entry screen when I want Loop's advice on the insulin quantity before I take Afrezza for a fast-carb meal or when catching up after I forgot to bolus for some carbs that I just ate.

**Comment by scottf51** [comment]
I use injections most of the time as I can just get the insulin in quicker, I need big doses and the delay getting 20u in leads to bigger spikes. My pump mostly deals with snacks and basal. So I go in and add non pump insulin several times a day.  Sent from my iPhoneOn 23 Nov 2022, at 23:38, CosiP ***@***.***> wrote:﻿
We usually do the same. We do injections when pod reservoir is low and we don’t want to change the pod and we add this in apple health. We also add a blood glucose check when there is no Dexcom in place. As far as being able to put a temp basal indefinitely (no end time discussed in another email) we use this as well.  My 15 years old son does have times were he has highs and lows without knowing what is going on and this feature helps a lot.  It is true that It used to happened more often in the past. Needs changed a lot depending on age.  Thanks again for all you do. This is really amazing work.SofiaOn Nov 23, 2022, at 12:09 PM, bkh ***@***.***> wrote:﻿
For me, administering insulin but not from the Omnipod is not a rare event.  If the pod is running out of insulin too soon before pod expiration, I'll take a large meal bolus by syringe to preserve the useful pod life.  And if I want to fix a high that's quickly getting out of control, I'll take some Afrezza.
In the past, the work-around that enabled Loop to account for this was via adding an insulin dose into Apple Health.  Of course we prefer to tell Loop of an insulin dose directly.  In 3.0, this feature is available on the Log Dose screen, but the access path is well-hidden:  Insulin Delivery detail > non-pump insulin > +
Adding non-pump insulin should be more easily discoverable and accessible.  The natural place to access this feature would be via a link or button from the Bolus screen.  This would be an easy two steps (insulin delivery button, non-pump insulin button.)  A further advantage is that this would be in the natural path from the carb entry screen when I want Loop's advice on the insulin quantity before I take Afrezza for a fast-carb meal or when catching up after I forgot to bolus for some carbs that I just ate.

**Comment by ps2** [comment]
How about a Long press on the insulin delivery button that brings up a selector with options for pump bolus or add non-pump insulin?

**Comment by bkhx** [comment]
That seems like an improvement over the current path, but I have two misgivings.  One is that it is not easily discoverable, it is a hidden feature.  The other is the possibility of a mis-press causing a pump delivery which I would then have to cancel via suspend.  (I don't mind that, but whoever has been inserting all the additional confirmation steps in the dosing path might.)

I'd rather see the current full-width **deliver** button split into a larger left half that says **deliver** and smaller right half that says **non-pump** or something along those lines.
