### ISSUE TITLE
Feature request: improve the experience of logging non-pump insulin to dose for carbs

### ISSUE THREAD

**Issue by novalegra** [LoopKit/Loop#1840]
(I'm typing this up to document a conversation I had with a user of the non-pump insulin feature)

**Is your feature request related to a problem? Please describe.**
When a user wants to log non-pump insulin to dose for carbohydrates, there is no unified experience in Loop. The user has to log the non-pump insulin and then log the carbs separately, since doing the actions in reverse will make Loop start a high-temp basal or an autobolus to cover the carbs. This risk is not obvious to first-time users of the experience and can cause more insulin to be dosed than intended.

**Describe the solution you'd like**

https://github.com/LoopKit/Loop/issues/1839 presents an interesting solution to this issue: integrating the ability to log non-pump insulin in the general bolus screen. I'm not sure the non-pump insulin feature is used so often that it warrants the real estate on such a high-use screen, but it's the best idea I've seen or thought of so far.

Additionally, since non-pump insulin is typically dosed in 1-unit increments, it would be ideal if the recommendation for non-pump insulin could be rounded **down** to the nearest unit.

**Describe alternatives you've considered**
- Addition of an additional button to the insulin history screen's navigation bar to trigger the carb-bolus flow for non-pump insulin
-> having 2 buttons does align with Loop's mental model of 2 buttons to bolus (1 for carb-bolus flow and 1 for bolus flow), but I'm concerned that there isn't room in the nav bar for 2 buttons and it could create confusion among users

- Changing the non-pump insulin flow to always require a carb entry
-> many usecases of the non-pump insulin feature (such as logging an Afrezza correction for high blood sugar or logging an injection due to pump failure) don't require carbs, and I don't think we should force everyone to see the carb entry page every time they try to log non-pump insulin

**Comment by ps2** [comment]
How about a Long press on the insulin delivery button that brings up a selector with options for pump bolus or add non-pump insulin?

**Comment by Trpl7ca** [comment]
Whenever I add  non-pump insulin it is usually because of being stuck on high BG or the insulin is getting low in the pump and I am trying to delay changing the pump to a later time. I don't see the current procedure as a problem and do not always need to add carbs.  Not sure about the long press solution, might be confusing is done accidentally by a caregiver

**Comment by ps2** [comment]
Oops, that comment was meant to go on https://github.com/LoopKit/Loop/issues/1839
