### ISSUE TITLE
"Unable to Reach Pod" error, despite successful insulin delivery, during Dexcom G6 Signal Loss

### ISSUE THREAD

**Issue by two0ten** [LoopKit/Loop#1851]
**Describe the bug**
On Loop v2.3.0 (57), on 2022-11-25 at 12:34pm ET, I noticed a "Unable to Reach Pod" error. However, my Orangelink device was well within range of both my iPhone and Omnipod Eros, and after hitting Back, as a test of connectivity, I was immediately successfully in bolusing 0.05 units.... which tells me the error was likely incorrect?

However, I WAS experiencing temporary connectivity issues with my Dexcom G6 sensor at the time... so was Loop mistaken in the device it was unable to reach?

**Attach an Issue Report**
[Loop Report 2022-11-28 19:33:41-08:00.md](https://github.com/LoopKit/Loop/files/10109517/Loop.Report.2022-11-28.19.33.41-08.00.md)
[Loop Critical Event Logs-2022-11-29-T032946Z.zip](https://github.com/LoopKit/Loop/files/10109520/Loop.Critical.Event.Logs-2022-11-29-T032946Z.zip)

**To Reproduce**
I'm not sure how to reproduce the "Unable to Reach Pod" error.

**Expected behavior**
I did not expect to be able to bolus immediately after receiving this error.

**Screenshots**
I'm including Screenshots of the Unable to Reach Pod error (which I believe was a bug), the Signal Loss I was ACTUALLY experiencing with my Dexcom G6 device at the time, and the Insulin Delivery I was able to enter right after receiving the _alleged_ "Unable to Reach Pod" error.
![IMG_2145](https://user-images.githubusercontent.com/57082938/204433358-706bd6bc-f19e-428a-a45c-39eb9863813a.jpeg)
![IMG_2146](https://user-images.githubusercontent.com/57082938/204433359-c25c7d4c-e4f4-44da-ac54-bc7f544ef2f7.jpeg)
![IMG_2147](https://user-images.githubusercontent.com/57082938/204433361-b8ff681d-07d0-4a04-8a5d-b712b817bf5e.jpeg)

**Phone**
 - Hardware: iPhone 12 Pro
 - OS Version: iOS 16.0 (20A362)

**Loop Version**
 - Version Number: Loop v2.3.0 (57)
 - Repo: LoopKit/Loop dev branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom G6 App 1.10.1 (SW11677)

**Pump**
 - Manufacturer: Omnipod Eros
 - Lot Number: 71347
 - Sequence Number: 1250196
 - PI and PM Version: 2.10.0

**Additional context**
N/A

**Comment by ps2** [comment]
The "Unable to reach pod" screen is transient, and does not have a "back" button.  When it goes away, it means the connection has been restored.  I think you just had a temporary communication failure, which is even possible when the devices are near each other.

**Comment by two0ten** [comment]
@ps2 You're welcome to close this, but your comment that it does not have a "back" button is incorrect: please refer to my first screenshot.

**Comment by ps2** [comment]
Oh yes, you're correct. I meant you can't get out of that state; the back button will take you to the modal dialog on the home page, which you can't close without coming to this page. If you can get out of this state, then communications have been restored.
