### ISSUE TITLE
Loop-dev crash from Correction Range accepted by Onboarding

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1853]
**Describe the bug**
Loop-dev Onboarding accepts Correction Ranges with both min and max values < guardrail min and then crashes when user attempts to edit.

**Background**
When building Loop-dev over earlier versions based on Loop v2.2.x, the user must go through the onboarding steps.
Some Loopers come in with fairly low values that are below the range accepted as guardrails for Loop-dev

**To Reproduce**
1. Delete Loop
2. Build Loop based on v2.2.x
3. Adjust settings out of range
  * Suspend Threshold < 67
  * Correction Range with both values < 87
5. Build Loop dev and progress through onboarding
6. As expected, user cannot accept a Glucose Safety less than 67
   * They are forced to modify to 67 or greater
   * The incoming correction range minimum is forced to Glucose safety (if it was lower before)
   * The incoming correction range maximum is allowed to remain less than 87
7. When attempting to edit the correction range, if the incoming range max is < 87, the app crashes (see graphic)
   * Note - I'm sure I touched the min value picker wheel first when editing.

Example in graphic below:
* Correction Range after onboarding was 68 to 80
* Attempted to edit range
* At crash, debugger reports min value was set to 87 before max value was modified, it remained at 80.

**Phone**
 - Hardware: 8
 - OS Version: iOS 16.1.1

**Loop Version**
 - Version Number: Loop-dev
 - Repo: LoopKit, LoopWorkspace commit ad4e6b8 (29-Nov-2022)

![Screenshot 2022-11-29 at 3 05 06 PM](https://user-images.githubusercontent.com/19607791/204676345-f63e2ead-06a1-4113-98bc-b057b42675f6.png)

**Comment by SwiftlyNoah** [comment]
I just created a [pull request](https://github.com/LoopKit/LoopKit/pull/436) that should fix this crash.
