### ISSUE TITLE
ShareClient fails to update

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1854]
**Describe the bug**
Issue#1: If Dexcom Share is added as a CGM before a Pump is added to Loop, the CGMManager:ShareClientManager does not update after Pump is added.
Issue#2: Walked away from my phone, so DexcomShare stopped providing new readings, Loop stopped updating even after readings resumed with sensor.
* Tested ONLY with a rPi DASH simulator
* I suspect this has been there for a while
   * I remember needing to delete and add back Dexcom Share when testing
    * Not a typical use case

**Expected behavior**
Expect
* to be able to add CGM and pump to Loop in either order
* if dexcom share source is interrupted and then resumes that Loop begin to work without intervention

The intervention required is to delete Dexcom Share as a CGM and then add it back again.

**To Reproduce**
* I built Loop-dev (commit ad4e6b8) to a blank phone, pulled in Therapy from NS, confirmed and saved
   * Added Dexcom Share as CGM
   * Added rPi DASH simulator
   * Left phone in open loop
   * Loop never turned green (waited more than 5 minutes)
* Deleted CGM and added Dexcom Share as CGM
   * Loop turned green immediately

Repeated to confirm, pod insertion completed at 08:39 PST.
Report ShareClientManager statements in debug log up through 08:49 PST.
```
2022-11-30 08:36:58.066920-0800 Loop[1372:280813] [DeviceDataManager] CGMManager:ShareClientManager did update with 2 values
2022-11-30 08:37:06.017885-0800 Loop[1372:280814] [DeviceDataManager] CGMManager:ShareClientManager did update with no data
```

I see the no recent glucose message on the HUD.
Delete CGM and then add it back and get an immediate green loop, and loop stays green
```
2022-11-30 08:51:52.336748-0800 Loop[1372:284698] [DeviceDataManager] CGMManager:ShareClientManager did update with 4 values
2022-11-30 08:52:11.353423-0800 Loop[1372:284777] [DeviceDataManager] CGMManager:ShareClientManager did update with no data
```

Now delete both pump and CGM.
This time add Pump first and then CGM.
Insert completed at 09:23 am PST
Add Dexcom Share as CGM at 09:24 am PST and get an immediate green loop.
```
2022-11-30 09:24:14.159099-0800 Loop[1388:294020] [DeviceDataManager] CGMManager:ShareClientManager did update with 2 values
```

Just happened to walk away from my "real" phone, so Dexcom Share data stopped updating. Even after resuming new CGM data on Share, had to delete and add CGM to get looping to resume on test phone, so added Issue#2 to the list above.

**Comment by kneddla** [comment]
For me loop only takes one reading from Dexcom Share after adding it as a CGM. Then the BG info just ages, loop ring turns amber and then red but no more readings unless I delete / re-add the CGM or unless I kill and restart the app.

**Comment by kneddla** [comment]
Typically people will not want their treatment to depend on Dexcom Share but new loppers will invariably use it as their first CGM after their first build, and this issue will not help their confidence to switch to loop.

**Comment by marionbarker** [comment]
I'm pretty sure this is fixed in dev. I will do some testing and find out.

**Comment by marionbarker** [comment]
This still happens with most recent dev, although before I think CGM had to be deleted and added back, whereas now - just restart the app to get a green loop. Since there are many things that get fixed by an app restart, I'm going to close this issue.

**Details:**

Built most recent dev to test phone on 4-Aug-2023.
commit c8fde98 

**Test 1:**
Loop was green to start (had recent CGM readings and a simulated pump added).
1. Deleted pump and CGM.
1. Add Dexcom Share first.
1. Add Pump (Simulated pump)
2. Loop goes yellow - wait and it goes red

Quit and restart app
* Loop reads glucose from Dexcom Share turns green

**Test 2:**
Turn off WiFi / cell on my real phone to interrupt Dexcom Share.
* wait 15 minutes
* restore Dexcom Share by turning WiFi /cell back on
* wait 10 minutes - stays red

Quit and restart app
* Loop reads glucose from Dexcom Share turns green

**Comment by marionbarker** [comment]
I'm going to reopen this. I think some users are continuing to have issues - and I did need to quit and restart app (as mentioned in previous comment.)

**Comment by ps2** [comment]
I've posted a possible fix.  However, ShareClient is *not* intended for production use. We should probably update the onboarding to make this clear.  Even with a bluetooth pump, like some Dash pods, we will not get a reliable heartbeat.

**Comment by marionbarker** [comment]
Started this testing prior to Pete's comment.

After this zulipchat discussion [Dexcom Share without BT device](https://loop.zulipchat.com/#narrow/stream/148543-Loop/topic/Dexcom.20Share.20without.20BT.20device), I came back to this issue for more testing.

There appears to be an iOS 15.7.x issue.

What works (loop stays green) using Dexcom Share as a CGM:
* real phone running DASH pod
* test phone (iOS 16.6) using rPi DASH simulator
   * with phone unlocked (stays green through several cycles)
   * lock phone and I can see the rPi messages in the terminal issuing dosing commands

What does not work (loop stays red) using Dexcom Share as a CGM, furthermore - there is no update to glucose data shown with addition of Dexcom Share:
* test phone (iOS 15.7.x) using pump simulator
* test phone (iOS 15.7.x) using rPi simulator

**Comment by marionbarker** [comment]
Tested again today. Used the code with patch from [PR 2058 comment](https://github.com/LoopKit/Loop/pull/2058#issuecomment-1731603523).

Summary 
- when using a pump with a heartbeat, Dexcom Share works fine
- when using a pump without a heartbeat, Dexcom Share does not update
   - however, with the same configuration, Nightscout as a Remote CGM - updates happen

Details:

Phone configured with a pump with a heartbeat (rPi Pod simulator)
* Add Dexcom Share as a CGM, Loop turns green at next CGM reading
* Turn off wifi to interrupt the Dexcom Share, Wait for red loop (>16 minutes)
* Turn on wifi, within a few minutes, loop turns green (app is open)
* Lock phone, loop stays green

Using Dexcom Share as a CGM using a pump simulator (no heartbeat)
* Loop goes red even while phone is unlocked and app is open

Using NS as a CGM using a pump with or without a heartbeat (rPi Pod or Pump simulator)
* Loop says green throughout, even while phone is locked
