### ISSUE TITLE
Loop Uploads Old IOB/COB after Treatment

### ISSUE THREAD

**Issue by gestrich** [LoopKit/Loop#1858]
**Describe the bug**

_Note this was reproduced with CGM/pump simulator but I suspect this issue is the same for real hardware_

When carbs or insulin are delivered in Loop, Loop will immediately upload the carbs/insulin delivered on the home view. But it is uploading to Nightscout the IOB/COB prior to the delivery.

This causes confusing feedback in Nightscout where delivered carbs show an update in the graph but the COB will only update to the values just before the delivery. Similarly, delivering insulin will update a bolus entry in the graph but the IOB will update to the IOB prior to the bolus delivery. 

If you wait until the next completed Loop cycle, the numbers will then align between Loop and NS. That mitigates the affect but there could be up to a 5 minute interval where remote treatment decisions could be impacted. We probably also need to explore if "Recommended Bolus" is similarly stale after treatments.

Attached are screenshots that show the debugger submitting NS deviceStatus json with some old values right after I delivered carbs/boluses. 

![Screen Shot 2022-12-04 at 6 57 01 AM](https://user-images.githubusercontent.com/3207996/205489485-1237ccbb-4a18-4120-abdb-bc58b4d86576.jpg)

![Screen Shot 2022-12-04 at 6 55 26 AM](https://user-images.githubusercontent.com/3207996/205489492-124125ac-65ff-444a-8137-c860e1b9b0b1.jpg)

**Attach an Issue Report**

[Loop Report 2022-12-04 07:00:17-05:00.md](https://github.com/LoopKit/Loop/files/10148402/Loop.Report.2022-12-04.07.00.17-05.00.md)

**To Reproduce**

COB

1. Start with 85 carbs on board (Loop and NS match)
2. Deliver 10 carbs in Loop
3. Loop updates to ~95 and NS updates with the old ~85 value

IOB

1. Start with IOB of 6.0 on board (loop and NS match)
2. Delivery 1 unit of insulin
3. Loop IOB updates immediately to IOB of ~7.0. NS is sent the old 6.0 value.

**Expected behavior**

It is expected that after carbs/bolus are delivered that the IOB/COB update on NS.

**Screenshots**

**Phone**
 - Hardware: iPhone XS
 - OS Version: iOS 16.1.1

**Loop Version**
 - Version Number: Latest Dev, LoopWorkspace commit 29802acb880d6833dbe9663dac7afe9a8fbf98a5
 - Repo: LoopWorkspace

**CGM**
 - Device: Simulator
 - Manager app: N/A

**Pump**
 - Manufacturer: Simulator
 - Model: N/A
 - Firmware version: N/A

**Comment by marionbarker** [comment]
I replicated this with "real" hardware: DASH pump, G6 CGM.
Configuration:
* LoopWorkspace commit: 29802ac (2 Dec 2022)
* Patch from PR #1857 applied

On Loop phone, issue 1 g carb.
It appears within a few seconds on NS graph display but COB does not update until next CGM reading arrives.

On Loop phone, issue 0.1 U delivery.
It appears within a few seconds on NS graph display but IOB does not update until next CGM reading arrives.
