### ISSUE TITLE
Feature Request: Add 2 safety features for maxCOB and maxIOB

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1863]
**Is your feature request related to a problem? Please describe.**
1. There have been several instances where a bad CGM reading (or reading in the future) has caused Loop to deliver maxBolus (or 40% of that value) at 5 minute interval, leading to excessive insulin delivery.
1. There have been several instances where user accidentally entered a meal more than once which has caused Loop to deliver excessive insulin.

**Describe the solution you'd like**
Add a user adjustable fail-safe value to Loop.

One idea:

maxIOB:
* Automatic Delivery of insulin checks current IOB and if the recommended automatic bolus would exceed maxIOB, limit automatic bolus to not exceed maxIOB and issue a notification to user.
   * Manual Delivery would not be limited by maxIOB (or perhaps there could be 2 settings, one for automatic and one for manual)
   
maxCOB:
* When accepting a Carb entry or edit, check to see if the COB with that carb entry would exceed the user selected maxCOB and refuse to accept the entry
   * If user wants to proceed with the Carb entry, they could modify setting or loop might offer an accept button for one-time use without modifying maxCOB selection.

**Comment by BiagioL** [comment]
The introduction of  these  two safety features are of great importance and will help avoid bad situations just like the one that  happen to me last month when without realizing it I entered 115 grs. of Carbs instead of the just 15 gr. intended and had my worse Hypoglycemia in 45 years as T1 and 3:1/2 years use of Loop.  Thank you for addressing it.

**Comment by marionbarker** [comment]
With the addition of the Large Meal warning screen to the carb entry screen when entry exceeds 99 g, modify this feature request to limit the automatic dosing.
See PR #1871 and LoopKit PR #442

**Comment by ps2** [comment]
Closing this; for now; the IOB mitigation is under development, and we should have a separate ticket (or tickets) to discuss any carb related mitigations that are still needed.
