### ISSUE TITLE
Feature Request: Setting for Auth Bolus on/off

### ISSUE THREAD

**Issue by mcdiarmid1** [LoopKit/Loop#1877]
I'd like to request that the Auth Bolus on/off is changeable via a loop setting option instead of manually changing the code for every build.

**Comment by bkhx** [comment]
I would use that feature.

When I'm out wearing a mask and I want to take a manual correction, face ID doesn't work in loop (and it doesn't use the watch to unlock the way the phone does) so I end up having to type my very long password, either that or take the mask off.  Being able to turn off the requirement for face ID before going out would be a big improvement.
