### ISSUE TITLE
watchOS 9.1 simulator

### ISSUE THREAD

**Issue by ohadlahavv** [LoopKit/Loop#1879]
Hi,
I tried to install the loop but in the final step I ran into a problem, I tried several times to install according to the instructions but it still doesn't work.
Attach photos.

![WhatsApp Image 2022-12-23 at 02 28 46](https://user-images.githubusercontent.com/121268548/209247625-8b6c7a04-5e0e-4609-9168-40a6651da686.jpeg)
![WhatsApp Image 2022-12-23 at 02 28 46-2](https://user-images.githubusercontent.com/121268548/209247632-15ce4036-0e98-47d3-8499-1956dc896f82.jpeg)
![WhatsApp Image 2022-12-23 at 02 28 46-3](https://user-images.githubusercontent.com/121268548/209247707-4579d5ae-1031-448a-8f2b-10637d3e4ab1.jpeg)
![WhatsApp Image 2022-12-23 at 02 28 46-4](https://user-images.githubusercontent.com/121268548/209247717-2d94dc01-08d4-46c4-9fff-e1cb31f3a437.jpeg)
![WhatsApp Image 2022-12-23 at 02 28 46-6](https://user-images.githubusercontent.com/121268548/209247735-ea5b2f95-998f-4c11-aab6-d59a659e297d.jpeg)

![WhatsApp Image 2022-12-23 at 02 28 46-5](https://user-images.githubusercontent.com/121268548/209247727-290fb8a4-520e-4ad8-90a1-e64a6937b70c.jpeg)

**Comment by bkhx** [comment]
I had an issue like that, and it turns out I forgot to reboot the mac after updating xcode.  After making sure macOS and xcode were at the newest version and rebooting the mac, a fresh run of the the build script worked properly.

**Comment by MeeraVenkatesh** [comment]
I  aslo had the same issues and after updating to latest Xcode, build went
seamlessly.

Regards,

Meera

Grant me the Serenity, to accept the things I cannot change, Courage to
change the things I can, and Wisdom to know the difference.

**Comment by ohadlahavv** [comment]
**updating**

After I updated the Mac version everything ran smoothly.

One problem - it is not possible to install the loop on the watch now
