### ISSUE TITLE
Expiration Notice for TestFlight Builds

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1881]
**Is your feature request related to a problem? Please describe.**
The expiration for the new github Build Action process for building Loop does not notify user when Beta test will expire:
* The TestFlight distribution has an end date of 90 days
* The profile expiration might be a full year in the future (for first build with this method)

**Describe the solution you'd like**
Add a new notification that warns user when app will expire - similar to the notification for Xcode built apps.

**Additional context**
Is there a way to add the TestFlight expiration date to Loop notifications?

**Testing Details**
The expiration profile for my TestFlight app reports as 2023-12-15 in the Loop Report under Build Details.
I looked at: 
* https://developer.apple.com/account/resources/profiles/list
* there are 6 profiles listed that start with match.AppStore.com for Loop through Loop Status Extension with that expiration date.

The TestFlight expiration says 87 days.
* Today is Dec 27, 2022.
* I changed the date (this is a test phone - do NOT do this on a real phone) to March 30, 2023 (93 days in the future).
* I can no longer open the app - message is: "Loop" Beta Has Expired
* Changed time to March 23, 2023 and app opens again

**Comment by ps2** [comment]
Note to self: maybe try reading the mobileprovision file: https://www.process-one.net/blog/reading-ios-provisioning-profile-in-swift/

**Comment by marionbarker** [comment]
This is still an important issue.

**Comment by marionbarker** [comment]
We still need this. Please do not close.

**Comment by marionbarker** [comment]
I submitted PR #2052 as a proposed solution to this issue.

**Comment by marionbarker** [comment]
Closing this because PR #2052 was merged (Loop) and that version of Loop is included in LoopWorkspace. Adds the expiration warning for TestFlight.

**Comment by pjputney** [comment]
Seen in Loop 3.2.2. Negative number is present in the countdown. I used to build with Xcode, but have been doing browser builds for the last year or so and I recently installed using Test Flight about a week ago.

The App is fully functional, but I get a warning modal that the Profile will expire soon multiple times per day when I open the app.
![IMG_2995](https://github.com/LoopKit/Loop/assets/76851291/93270127-d444-40b3-9851-2f43ff8b7f16)

**Comment by marionbarker** [comment]
Sorry about that. Only fixed in dev. 

There is a customization that fixes this for main. 

[TestFlight Expiration](https://www.loopandlearn.org/custom-code/#tf-expire)

[Browser Build Customization](https://www.loopandlearn.org/custom-code/#github-intro)

**Comment by charli144** [comment]
I have the same issue after rebuilding version 3.2.3. i always do browser build, with most recent rebuild, I rebuilt before the profile expired and this started appearing though the app works fine. 

> Seen in Loop 3.2.2. Negative number is present in the countdown. I used to build with Xcode, but have been doing browser builds for the last year or so and I recently installed using Test Flight about a week ago.
> 
> The App is fully functional, but I get a warning modal that the Profile will expire soon multiple times per day when I open the app. ![IMG_2995](https://private-user-images.githubusercontent.com/76851291/300280177-93270127-d444-40b3-9851-2f43ff8b7f16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDQzNzUsIm5iZiI6MTcwNzM0NDA3NSwicGF0aCI6Ii83Njg1MTI5MS8zMDAyODAxNzctOTMyNzAxMjctZDQ0NC00MGIzLTk4NTEtMmY0M2ZmOGI3ZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIyMTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTk1MWIwNzk4YjczODRlODMzN2VhYjYwYzI3MmEyNmYwYTIzOTM1MjE3ZDRhNWE5Mzg3YTYwMjc4MzUwYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DEyjLYsLv2vml_Tt0SjktaPH0Niyk5eExlfKvUYkp0E)

**Comment by marionbarker** [comment]
Bump

**Comment by marionbarker** [comment]
Bump

**Comment by marionbarker** [comment]
This is fixed in Loop 3.4.

**Comment by Pete1977** [comment]
I get a message in my testflight app that it expires in 90 days.
The app makes automatically updates, so what does it means that its expires?
Is it my DIY-Loop app that expires or the the actual testflight app?
