### ISSUE TITLE
Loop keeps crashing after build

### ISSUE THREAD

**Issue by LaraSimons** [LoopKit/Loop#1882]
**Describe the bug**
I have a new iphone (mini 13, ios 16.2) and want to build my loop on it. I have previously used my old iphone SE. I build loop from my macbook air (Ventura 13.1) with the latest version of XCode (14.2). 
The build seems succesfull as xcode said running loop on iphone, and I didnt see any red bugs. When opening loop on my Iphone it did not show my old settings, the app seemed empty (I decided to first install everyting on my new Iphone before transfering my pods). After a few moments the app keeps crashing and shutting down. The first time it happend Xcode was still open and showed a popup messages saying "Terminated due to memory issue". 

**Attach an Issue Report**
Issue report attached and screenshot added. 
[Loop Report 2022-12-29 08:14:26+01:00.md](https://github.com/LoopKit/Loop/files/10318138/Loop.Report.2022-12-29.08.14.26%2B01.00.md)

**To Reproduce**
This happens each time I open Loop. Loop is also not open long enough to add settings

**Expected behavior**
I hoped Loop would just open like before, maybe I had to add some settings, but I did not expect it to crash immediatly

I hope someone can tell me where I did something wrong so loop will work again :-) 

**Screenshots**
<img width="290" alt="Scherm­afbeelding 2022-12-29 om 08 09 34" src="https://user-images.githubusercontent.com/52426060/209918421-a5b54409-7b82-43ab-9754-95a5ee40fbfb.png">

**Phone**
 - Hardware: [e.g. iPhone mini 13]
 - OS Version: [e.g. iOS 16.2]

**Loop Version**
 - Version Number: [V2.2.9]
 - Repo: 

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [Dexcom App]

**Pump**
 - Manufacturer: [omnipod]
 - Model: [eros]
 - Firmware version: 

**Additional context**

**Comment by LaraSimons** [comment]
hmmm.. don't excactly know what I did, but I kept trying to add my pump and it seems to be working now. Still, I am a bit nervous that it will crash again and everything will be gone. If someone sees something strange after reading this issue and has some tips to prevent it, it would be most appreciated.

**Comment by ps2** [comment]
I did spend some time looking into reports from another user experiencing this kind of crash. [sysdiagnose notes](https://gist.github.com/ps2/32876e4d80abe7732702879bb980f7ef)

[Chat](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Terminated.20due.20to.20memory.20issue)
