### ISSUE TITLE
Delived bolus not reflected in IOB or Event History

### ISSUE THREAD

**Issue by CougarX6** [LoopKit/Loop#1886]
**Describe the bug**
Around 7:00pm, I was calculating the bolus for dinner, entered 50 carbs, Loop suggested a bolus of 2.35.  I try to never bolus more than 1.5 to 2.0 units at a time, so I changed the bolus amount to 1.5 and delivered the bolus.  My pod started clicking before the graphic on the Loop app indicated it was delivering the bolus.  I was counting the clicks and 1.5 was delivered, before the graphic caught up.  After the pod finished clicking and with the graphic reading around 1.2 delivered, the graphic went away, seeming to not finish the bolus.  The bolus was not reflected in the IOB/Active Insulin, nor in the Event History.  Also, at that point I clicked the bolus icon, and it still showed a suggested bolus of 2.35.  At the next interval, Loop delivered .95 units, 40% of the suggested 2.35 bolus.  At that point I entered the 1.5 in as Non-Pump Insulin.  Note, these were not done remotely, all entries were done through the Loop app on my phone.

**Attach an Issue Report**

[Loop Report 2023-01-02 20_28_47-05_00.md](https://github.com/LoopKit/Loop/files/10333976/Loop.Report.2023-01-02.20_28_47-05_00.md)

**To Reproduce**
Unsure... change suggested bolus amount and deliver the reduced bolus.  Never had this happen before.

**Expected behavior**
The delivered bolus should be reflected properly in IOB and the event history.

**Screenshots**
![IMG_0322](https://user-images.githubusercontent.com/51462502/210290090-8e930d08-6c80-44a6-89d1-407c485bfdb3.jpg)

![IMG_0323](https://user-images.githubusercontent.com/51462502/210290252-2a899afe-53e1-403a-b0e7-9dfdc9a1cc8b.jpg)

**Phone**
 - Hardware: iPhone 13
 - OS Version: iOS 16.2

**Loop Version**
 - Version Number: 2.3.0 (57) commit# 3770f56
 - Repo: 

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model:  Omnipod Eros
 - Firmware version: 

**Additional context**

**Comment by ps2** [comment]
Thanks for the report. I'm looking into the logs you posted to see if I can see anything unusual. Did Loop restart, or did you notice any other odd behavior at the time other than the bolus IOB going missing?

One thing that might prove helpful is to export your critical event logs; they record all the dosing decisions that Loop makes, among other things. It's a larger zip file that will have to be uploaded to a file sharing service, and then you can share the link with me.

**Comment by ps2** [comment]
I can see from the pod comms log that there was indeed a 1.5U bolus delivered at 7:02pm, and I also see that the dose was not tracked properly in Loop's DoseStore, somehow.  Unfortunately, I don't have enough information to have a theory on what went wrong. A sysdiagnose would maybe give some clues, but those only keep data for a few hours. 

If you (or anyone else) sees this happen again, please capture a sysdiagnose asap.

**Comment by CougarX6** [comment]
Loop did not restart.  After it happened and the IOB didn't update, I closed the Loop App and opened it again, but nothing changed.  It just seemed like the graphic in the app lagged behind the actual clicking of the pod delivering the insulin.  Then it got to about 1.2 of 1.5 and just disappeared.  

I've since switched over to Dash pods, on my second one now and haven't seen anything like that.  Didn't see a repeat after it happened on the Eros pod or at any time since I started Loop in July 2019.

I've got the Critical Event Log saved on my phone (will that still work after all this time?), how do I upload it to a filing sharing service and where do I find one?

**Comment by ps2** [comment]
The critical event logs keep data for about 7 days, so it may have expired.  By file sharing service, I mean something like google drive or dropbox.

**Comment by CougarX6** [comment]
Sorry, never used either.  Setup a Dropbox account. Is this the link you need:

https://www.dropbox.com/s/ty3vr0q9fkj8059/Export-20230110T223249Z.zip?dl=0

**Comment by CougarX6** [comment]
I extracted the zip file, and it contained more zip files, with the oldest being from 1/4/2023, so looks like it missed the event on 1/2.

**Comment by joshandeliana** [comment]
This sounds like what just happened to us this morning. Any other reports or info I need to share?

**Comment by ps2** [comment]
I was able to get to the bottom of this, I believe, with the data reported in a [more recent ticket](https://github.com/LoopKit/Loop/issues/1941). I'm going to close this one as duplicate, to have a [single place to continue discussing this](https://github.com/LoopKit/Loop/issues/1941).
