### ISSUE TITLE
Feature Request: Basal Lock feature when BG is rising

### ISSUE THREAD

**Issue by pgumy** [LoopKit/Loop#1887]
![BB9C28DB-B552-483D-BB44-02BD57F2F1D5](https://user-images.githubusercontent.com/47061401/210541117-71a4376b-9145-4d54-ab79-e9cba9ffb6a6.png)
![8D65B8F2-AC75-421A-BA8B-F982A13FA167](https://user-images.githubusercontent.com/47061401/210541120-66c401ff-5dae-44b5-8950-1eebfacc1108.png)
Everytime Loop predicts f.e. a low in 3-4 hours but BG is rising over target (f.e. after meal), basal is automatically full or partially cut off by loop.

In Loop Patches, there is a functionality "Basal lock" with a customizable threshold BG.

But what I would find really interesting is a Basal Lock functionality everytime and only when BG is rising to avoid the problem I described above. So it would be easier to come earlier down after the rising phase, because the basal-insulin is not missing.

At the moment, I everytime have to go and manually open loop during rising BG (after meal f.e.) and try not to forget to close loop as soon as bg goes slowly down again.

Thanks for considering this input.

**Comment by ps2** [comment]
It sounds like you are encountering a situation where the forecast is often wrong in a particular way (forecasting too low at some point in the future after meals).  Loop's forecast is pretty simple, made up of components you can see. I'd be interested to hear what the difference is between your thinking and Loop's. You are thinking it's ok to not suspend, but Loop, by adding up how much insulin you have on board, and how many carbs, based on the numbers you input for therapy settings, thinks you will go low. Loop is often wrong, and user's have better models about what is really going to happen. This is one of those cases, where I'd love to have a better understanding about what Loop is missing.
