### ISSUE TITLE
Loop Key Access Prompt and Denial During Loop Build

### ISSUE THREAD

**Issue by esera123** [LoopKit/Loop#1893]
**Describe the bug**
I am getting a keychain access prompt while the loop app is building, indicating that the `codesign` tool is trying to use the private key associated with my Apple Development signing identity. I put in my password, but it keeps getting denied. This issue is not allowing my loop to finish building. I have built loop several times over the past few years. First time I remember this happening. I have contacted Apple Developer Support and they have not been helpful. Thank you for any help you can provide.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Hit the build button
2. It gets half way through the build
3. Then I get the password/keychain prompt

**Expected behavior**
I don't remember getting this prompt in past builds 

**Screenshots**

**Phone**
 - Hardware: iPhone 13 Mini
 - OS Version: iOS 16.1

**Loop Version**
 - Version Number: Trying to install Most Recent Version
 - Repo: 

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod UST 400 Pods
 - Firmware version: 

**Additional context**
Screen Shot Attached for Reference
<img width="1424" alt="Screenshot 2022-10-29 at 4 40 46 PM" src="https://user-images.githubusercontent.com/122292934/211351179-0e91c159-6665-417a-89c0-3ff5d5e0c051.png">

**Comment by marionbarker** [comment]
It is asking for your mac login and you must tap Always Allow multiple times as explained in LoopDocs. 

https://loopkit.github.io/loopdocs/build/step14/#codesign-keychain-access

**Comment by esera123** [comment]
Thank you for the help Marion
