### ISSUE TITLE
Dev: Nightscout does not display correct basal rate when temp basal is cancelled

### ISSUE THREAD

**Issue by tekrulik** [LoopKit/Loop#1896]
**Describe the bug**
When a temp basal set by loop is cancelled, the programmed basal rate is now active. Nightscout should stop displaying the temp basal rate and display the programmed basal rate. Instead, Nightscout displays the temp basal rate until the 30 minutes runs out or a new temp basal is set. The Loop pill box indicates temp basal has been cancelled, but the basal pill box and the basal graph do not display the programmed basal rate. They continue to show the temp basal rate. The pump itself (Medtronic 722) shows that the temp basal has been cancelled and the programmed basal rate is running. 

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket. (I will need to grab a report when my son gets home from school and will update issue with it.)

**To Reproduce**
1. Have loop cancel a temp basal rate
2. View Loop pill box and confirm it states temp basal has been cancelled
3. Confirm on pump that temp basal rate has been cancelled and programmed basal rate is running
4. View basal pill box and basal graph on Nightscout. Observe that they display the temp basal rate that was cancelled.

**Expected behavior**
The basal pill box, basal chart, and reports in Nightscout display the programmed basal rate is now running. Temp basal rates are no longer displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/8369005/211915348-9de7d362-b94f-4ab2-93a9-c3fa54e7ea94.png)

**Phone**
 - iPhone 13 mini
 - iOS 15.0.2

**Loop Version**
 - Dev 859dfba (but also existed on 3770f56
 - Repo: Dev Build Script version 1/10/23

**CGM**
 - Dexcom G6
 - Dexcom App

**Pump**
 - Medtronic
 - 722
 - 2.3A

**Additional context**
This happens consistently, each time a temp basal is cancelled and programmed rate is resumed.

**Comment by kenstack** [comment]
Fwiw - I looked at an issue like this in nsapple - an Apple Watch app that was essentially a Nightscout follow app (used the endpoints) - had the same problem with basal rates always lagging substantially after some changes. I'm not sure it's a loop issue - the testing I did showed loop was uploading. I never got to the bottom of it but our best guess was a caching issue in ns. Not sure it's the same issue of course.  Good luck.

**Comment by tekrulik** [comment]
[Loop Report 2023-01-11 192919-0800.md](https://github.com/LoopKit/Loop/files/10397952/Loop.Report.2023-01-11.192919-0800.md)
[Export-20230112T032952Z.zip](https://github.com/LoopKit/Loop/files/10397953/Export-20230112T032952Z.zip)
<img width="1378" alt="Screen Shot 2023-01-11 at 7 26 46 PM" src="https://user-images.githubusercontent.com/8369005/211970092-75b1dc92-0e1f-4890-9014-649a237bd2cd.png">
Attaching phone files - example where basal not displayed correctly at time in the NS screenshot. We are are NS version 14.2.6. We did update NS the day we first built Dev (12/31/22).
