### ISSUE TITLE
Nightscout CGM button does nothing

### ISSUE THREAD

**Issue by jpbazinet** [LoopKit/Loop#1898]
Did the GitHub build of Loop 3.0
Everything worked fine and Loop is working. But when I tried adding Nightscout as CGM, tapping the button did nothing. No additional windows open.
I can add Nightscout under the services area, but not the CGM area.

**Comment by henrycoding** [comment]
I have the same problem!

**Comment by henrycoding** [comment]
This phenomenon happens on iPhone 8, and iPhone SE2, but does not happen on my iPhone 12. So wired！

**Comment by jpbazinet** [comment]
Happens on iPhone 12 mini for me

**Comment by henrycoding** [comment]
Yeap. You can try first installing an old version of the Loop and then upgrading to the latest. Maybe this will make the latest Loop work properly. Looking forward to the response from the community!

**Comment by bedtime4bonzos** [comment]
Same.  iPhone 6s.

**Comment by mereldijkhuizen** [comment]
Same! Does anyone have a solution?

**Comment by marionbarker** [comment]
This seems to be an iPhone 6s problem. NS as a CGM works fine on two of my test phones: models SE and 8; but will not work on my 6s. True for main and dev branches. 

The 6s can only go to iOS 15. My other test phones are running iOS 16.

**Comment by henrycoding** [comment]
> This seems to be an iPhone 6s problem. NS as a CGM works fine on two of my test phones: models SE and 8; but will not work on my 6s. True for main and dev branches.
> 
> The 6s can only go to iOS 15. My other test phones are running iOS 16.

No, it seems that this problem is related to the version of iOS.

iPhone X with iOS 15 has the same issue, but when it upgrades to iOS16, the problem has disappeared.

**Comment by marionbarker** [comment]
I have put in a PR for this. The iOS 15 was the problem.
https://github.com/LoopKit/NightscoutRemoteCGM/pull/17

**Comment by marionbarker** [comment]
This issue is not fixed. Please open it again.
(It was fixed for dev but not for main.)

**Comment by marionbarker** [comment]
Bump

**Comment by ffigueroa** [comment]
This is the error when i try to add Nightscout Remote CGM

`2023-11-24 13:48:58.423201-0300 Loop[1074:70780] [PluginManager] Error loading plugin: Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/var/containers/Bundle/Application/DF03AEBF-3B75-40E3-A016-89A8B80BF477/Loop.app/Frameworks/NightscoutAPIClientPlugin.framework/NightscoutAPIClientPlugin, 0x0109): Symbol not found: (_$sSayxGs7CVarArg10FoundationMc)
  Referenced from: '/private/var/containers/Bundle/Application/DF03AEBF-3B75-40E3-A016-89A8B80BF477/Loop.app/Frameworks/NightscoutAPIClientPlugin.framework/NightscoutAPIClientPlugin'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Foundation'" UserInfo={NSLocalizedFailureReason=No se ha podido cargar el paquete., NSLocalizedRecoverySuggestion=Vuelve a instalar el paquete., NSFilePath=/var/containers/Bundle/Application/DF03AEBF-3B75-40E3-A016-89A8B80BF477/Loop.app/Frameworks/NightscoutAPIClientPlugin.framework/NightscoutAPIClientPlugin, NSDebugDescription=dlopen(/var/containers/Bundle/Application/DF03AEBF-3B75-40E3-A016-89A8B80BF477/Loop.app/Frameworks/NightscoutAPIClientPlugin.framework/NightscoutAPIClientPlugin, 0x0109): Symbol not found: (_$sSayxGs7CVarArg10FoundationMc)
  Referenced from: '/private/var/containers/Bundle/Application/DF03AEBF-3B75-40E3-A016-89A8B80BF477/Loop.app/Frameworks/NightscoutAPIClientPlugin.framework/NightscoutAPIClientPlugin'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Foundation', NSBundlePath=/var/containers/Bundle/Application/DF03AEBF-3B75-40E3-A016-89A8B80BF477/Loop.app/Frameworks/NightscoutAPIClientPlugin.framework, NSLocalizedDescription=No se ha podido cargar el paquete “NightscoutAPIClientPlugin”.}
2023-11-24 13:48:58.423588-0300 Loop[1074:70780] [StatusTableViewController] Failure to setup CGM manager with identifier 'NightscoutAPIClient': UnknownCGMManagerIdentifierError()`

iPhone: 7 Plus
iOS: 15.8
Loop: 3.2.3 (57)

**Comment by marionbarker** [comment]
Bump

**Comment by marionbarker** [comment]
Please see [NightscoutRemoteCGM PR 21](https://github.com/LoopKit/NightscoutRemoteCGM/pull/21).

**Comment by alexmos-com** [comment]
This issue happened to me 2 weeks ago on an iPhone 8 with the latest iOS updates installed (v16 I think), when I built the same Loop (source code) to an iPhone 12 Mini the issue was gone.

**Comment by LuminaryXion** [comment]
Hi, I am using the 7th Generation Touch with iOS15 and am having this issue. As I am limited per the documents that I can only loop on iOS15, I cannot upgrade my OS. Is there a specific dev branch I can use or is there a plan to fix this in the coming days?
