### ISSUE TITLE
Loop 3.0 showing signal loss when Medtronic pump is connected

### ISSUE THREAD

**Issue by pbloom209** [LoopKit/Loop#1902]
when I first connected the pump I did a small bolus the pump was adjusting basal rates etc.  But the pump icon said signal loss.  I waiting ten minutes and no change.  

Deleted the pump reinstalled, did a bolus and the icon connected.  This stayed present for about 2 loop cycles then changed and said signal loss.

When the pump loses the signal the data becomes stale and Loop stops working.

**Phone**
 - Hardware: 14pro
 - OS Version: ios16.2
![IMG_2790](https://user-images.githubusercontent.com/37948551/213341898-133f33fa-5965-455d-99c7-f3b99b6a0ef4.PNG)

**Loop Version**
 - Version Number: 3.0 main
 - Repo: Loop and learn scrip for 3.0

**CGM**
 - Device: G6
 - Manager app: Dexcom app

**Pump**
 - Manufacturer: Medtronic
 - Model: 754
 - Firmware version: 2.6A

![IMG_2788](https://user-images.githubusercontent.com/37948551/213338944-c5e79398-9717-472d-8e47-161ba7028e84.PNG)

![IMG_2789](https://user-images.githubusercontent.com/37948551/213338989-c7db0c94-cbd4-4f81-ae4b-71c6719fd030.PNG)

[Export-20230119T020710Z.zip](https://github.com/LoopKit/Loop/files/10452812/Export-20230119T020710Z.zip)

**Comment by cwrussellgithub** [comment]
I’m experiencing similar problems:
Loop 3.0
Medtronic 522 V2.4A1.1 (full battery tried)
OL and OL Pro both tried with full batteries.
OL and Pro both firmware: 3.2

Often Loop shows green loop and “signal loss” at same time.
Often Loop shows red loop and does t display signal loss.
During both above scenarios, I’m still able to send boils through loop, without moving closer to or interacting with OL.

Any corrective help/guidance would be much appreciated.

**Comment by ELMAR1961** [comment]
I got the same issue while loop is working without problems or red loops

**Comment by ELMAR1961** [comment]
My pump is 754

**Comment by Techdim** [comment]
ditto,
I’m experiencing similar problems
loop 3.2.1
Medtronic 722 V2.4.
iphone14 16.4.1

**Comment by jenimccormick72** [comment]
I am having the same problem.  
Loop 3.2.2
Medtronic 722 v2.4A1.1
Iphone XR
IOS 16.4.1

Is anyone working on this problem?  

Thank you.
