### ISSUE TITLE
Integrating Glucomen Day patch pump EOFLOW2

### ISSUE THREAD

**Issue by MarvelousMarvin** [LoopKit/Loop#1904]
The glucomen day patch pump is has a open source communication. This is a recent pump with many benefits over the dash. (Less adhesive problems, less scar tissue).

Could this be integrated into loopkit?

This one is already in use with AndroidAPS dev. EOPATCH2

**Comment by MarvelousMarvin** [comment]
https://github.com/nightscout/AndroidAPS/pull/1324

Link to AAPS commit

**Comment by bedevos** [comment]
I wonder what is needed to get this assigned?
I would like to hear.

**Comment by elnjensen** [comment]
This is an all-volunteer project, so it depends on people having time, and on access to necessary hardware.  So this would depend on someone stepping up who has time to work on writing and testing the necessary code, *and* who has access to this pump, which seems to be available in only a [small number of countries](https://glucomenday.com/newplatform/glucomen-day-pump/). 

Much of Loop has been written by people who desire certain features and thus are motivated to work on making them happen, so I encourage you to consider working on this if it's important to you.

**Comment by Russ060** [comment]
Where would be a good place to start learning  and understanding the loop
app structure and functions? I personally would like to contribute with my
little programming experience, and advanced math skills.

many thanks
Rajeh

**Comment by bjornoleh** [comment]
> Where would be a good place to start learning and understanding the loop app structure and functions? I personally would like to contribute with my little programming experience, and advanced math skills. many thanks Rajeh

Hi, I’d suggest asking for guidance in the development stream of https://loop.zulipchat.com/
