### ISSUE TITLE
Documentation - Patch Instructions need user to type cd

### ISSUE THREAD

**Issue by pbackstrom** [LoopKit/Loop#1905]
The instructions to copy a line after you enter pwd assume that it begins with cd, which it doesn't.   At least one person has not been able to apply patches because of it.

Suggested:
Highlight the one line that starts with \users in your terminal (do not use the cd line above) and ends with LoopWorkspace and copy it (CMD-c).  Click back on the prompt line and type cd\ and a space, then paste it (CMD-v) and hit return. Next issue the command pwd for print working directory and it should match the directory (the part that starts with /Users and ends with LoopWorkspace) in your terminal.

![Screenshot 2023-01-21 at 5 05 01 PM](https://user-images.githubusercontent.com/53927407/213896127-a2ee40b4-0107-4602-a037-123f77b51263.png)

**Comment by marionbarker** [comment]
Several problems. This is not a Loop Issue and so should be closed. 

Before the section you quoted there are directions: “ If you are returning to add LoopPatches and have closed your terminal from the download, you should follow these steps ” with the correct steps for that case. 

What you quoted is only for people who still have their terminal open following fresh download using build select script and is correct. They are to copy a line provided by the script and then confirm they are in the right place before proceeding. 

Please close this issue. We can continue the discussion in zulipchat. Use the documentation stream and CustomTypeOne LoopPatches topic.
