### ISSUE TITLE
Tidepool Service Setup-Error:"Configuration Error"

### ISSUE THREAD

**Issue by EJM0** [LoopKit/Loop#1909]
checked password and email multiple times and changed it on tidepoolsite.
also used apple keychain autofill feature. but im getting the error every
(latest dev as of posting and build via github actions)

![FED381B9-01E8-49B4-B890-1581A9B463E1_1_201_a](https://user-images.githubusercontent.com/57327565/214022904-42ee7d2c-59a7-4215-aff5-cbce0c2af104.jpeg)

**Comment by gigich** [comment]
Rebuild with actual version. Problem is fixed
