### ISSUE TITLE
Insulin Type not preserved when updating to Loop 3 using teh Browser Build method and Omnipod pump

### ISSUE THREAD

**Issue by senderob** [LoopKit/Loop#1910]
**Describe the bug**
Using Apple Watch 12, iOS 16.1.1
Omnipod Eros pod
Using Fiasp insulin

I built Loop 3.0 from a previous version using the Browser Build method.  I completed the onboarding steps.  I had a Pod on when I built Loop.  Today, when I changed my pod, I happened to look at the Omnipod/Configuration/Insulin Type setting.  It was set to Novolog instead of Fiasp.  I had to manually change the Insulin Type setting back to Fiasp.  I do not know if this will happen again if I rebuild using the browser method.  

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. I cannot reproduce this error as it happened as a result of updating to Loop 3.0 using the browser method.

**Expected behavior**
When updating from a pervious version of Loop to Loop 3.0 using the browser build method, the Omnipod Insulin Model setting should stay the same as it was Before the update. 

**Screenshots**

**Phone**
 - iPhone 12 
 - OS Version: 16.1.1

**Loop Version**
 - Version Number: 2.2.9 updating to 3.0
 - 
**CGM**
 - Device: Dexcom g6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: EROS
 - Firmware version: unknown 

**Additional context**
Prior Loop build was done on an iMac using the Loop Workspace method.
[Loop Report 2023-01-23 14_37_37-06_00.md](https://github.com/LoopKit/Loop/files/10483666/Loop.Report.2023-01-23.14_37_37-06_00.md)

**Comment by jpbazinet** [comment]
I can confirm, the same happened to me. Did the browser build, updating from a previous version and when I changed my pod, I got an alert saying I hadn’t chosen my insulin type yet. When I went to settings, it was set to Novolog and I changed it to Fiasp.
