### ISSUE TITLE
Add: missing battery indicator Medtronic pumps

### ISSUE THREAD

**Issue by Menno86** [LoopKit/Loop#1911]
**Issue: battery indicator for Medtronic users removed?**
In Loop 2 users with a Medtronic pump had a battery indicator on the dash. In Loop 3 this battery indicator has been removed, and is also missing from all the menus. There is no way to get an indication of the pumps battery (only an indication of the RileyLink battery).

**Relevance: essential **
Especially when using lithium batteries, the battery indicator on the pump is incorrect. It simply goes from full to zero without a warning. In Loop 2 users could see if they would make the day in the current Medtronic battery or if replacement was necessary. This prevents the unwanted situation of being confronted with a pump that suddenly dies and can't even give basal while being away from home. 

Therefore I consider this also a important safety feature. 

**Solution**
Please bring back the battery indicator on the dash for Medtronic users (or a indicator in any of the menus).

**Comment by 4gra** [comment]
@Menno86 If you use it, can you confirm if Loop still send this information to Nightscout as it did in v2.x? If so, as a workaround, you might be able to use Nightscout alerts for this purpose.

**Comment by Menno86** [comment]
> 

Nighscout does not show the pump battery percentage, it does show the remaining amount of insuline.

**Comment by Menno86** [comment]
In loop 3.2 the battery percentage has returned! Thank you. It can be found under ‘insuline pump’ in the menu.
