### ISSUE TITLE
Graphical delay when changing insulin type

### ISSUE THREAD

**Issue by alexmichelorg** [LoopKit/Loop#1912]
Upon switching the insulin type and returning to the previous screen, the change appears to not have saved. However when one returns to the main loop screen before reopening the insulin type menu, the change is in fact preserved.

issue presents on a fresh install of Loop 3.0, iOS 16.0.3, after having deleted a previous install of FreeAPS during troubleshooting.

**Comment by drjmetz** [comment]
Can confirm and replicate. Loop 3.2.1(57), iOS 16.2
