### ISSUE TITLE
Loop 3.0.0 Insulin dose wrongly reported on Eros failure 

### ISSUE THREAD

**Issue by AdrianWGit** [LoopKit/Loop#1913]
My Eros pod failed with error 18 during delivery of 5U of insulin   The delivery was probably incomplete as the delivery countdown was part way through.   Also the pump event log showed an elapsed time of 31 seconds which I think represents about 0 .8 U.  See below for log.  However loop shows 5 units administered. The first dose administered once a new pump was paired was 1.4U, so loop didn’t “catch up” later. 

DoseEntry(type: LoopKit.DoseType.bolus, startDate: 2023-01-25 18:30:27 +0000, endDate: 2023-01-25 18:30:58 +0000, value: 5.0, unit: LoopKit.DoseUnit.units, deliveredUnits: Optional(5.0), description: nil, insulinType: Optional(LoopKit.InsulinType.fiasp), automatic: Optional(false), manuallyEntered: false, syncIdentifier: Optional("626f6c757320352e3020323032332d30312d32355431383a33303a32375a"), isMutable: false, wasProgrammedByPumpUI: false, scheduledBasalRate: nil)

626f6c757320352e3020323032332d30312d32355431383a33303a32375a

**Comment by marionbarker** [comment]
Pretty sure that fault is one that resets the registers in the pod. There is no way to read from the pod how much was delivered. 

https://github.com/openaps/openomni/wiki/PDM-Ref-Codes#reset-faults

If you issue and post a Loop Report, that can be confirmed. 

I do not know if there is, or if it feasible to add, an upper estimate of insulin delivered because of time.

**Comment by AdrianWGit** [comment]
Hi Marion

Thank you very much for all you do for the loop community.  Looking at my last and current pods the bolus timing is consistently 0.025U/sec.  Although I  don’t know iif that is always true.  I will keep an eye on future pods.

But I guess the easiest solution is to use the pump event log to calculate the “missing insulin” and take it as an undeclared  bolus using a pen.  As far as I can tell there is no way of deleting IOB within loop.  Deleting the individual pump events doesn’t appear to update IOB.


Best Wishes

Adrian

From: Marion Barker ***@***.***>
Date: Thursday, 26 January 2023 at 14:31
To: LoopKit/Loop ***@***.***>
Cc: AdrianWGit ***@***.***>, Author ***@***.***>
Subject: Re: [LoopKit/Loop] Loop 3.0.0 Insulin dose wrongly reported on Eros failure (Issue #1913)

Pretty sure that fault is one that resets the registers in the pod. There is no way to read from the pod how much was delivered.

https://github.com/openaps/openomni/wiki/PDM-Ref-Codes#reset-faults

If you issue and post a Loop Report, that can be confirmed.

I do not know if there is, or if it feasible to add, an upper estimate of insulin delivered because of time.

**Comment by marionbarker** [comment]
You must delete both the pump event and the corresponding value in Apple Health to remove that event from IOB. This should be done with caution (of course).

https://loopkit.github.io/loopdocs/faqs/apple-health-faqs/#insulin-and-apple-healthkit

You are correct, pods deliver at a rate of one pulse (0.05 U) every 2 seconds after the cannula is inserted. During priming and insertion, the rate is one pulse every second.

**Comment by AdrianWGit** [comment]
Thanks Marion – that is very helpful.  I did read that in a post once, but it got covered in other clutter in my mind!


Best Wishes

Adrian

From: Marion Barker ***@***.***>
Date: Friday, 27 January 2023 at 12:30
To: LoopKit/Loop ***@***.***>
Cc: AdrianWGit ***@***.***>, Author ***@***.***>
Subject: Re: [LoopKit/Loop] Loop 3.0.0 Insulin dose wrongly reported on Eros failure (Issue #1913)

You must delete both the pump event and the corresponding value in Apple Health to remove that event from IOB. This should be done with caution (of course).

https://loopkit.github.io/loopdocs/faqs/apple-health-faqs/#insulin-and-apple-healthkit

You are correct, pods deliver at a rate of one pulse (0.05 U) every 2 seconds after the cannula is inserted. During priming and insertion, the rate is one pulse every second.

**Comment by ps2** [comment]
So yes, I think we could talk about a change to help handle this. Did we ever get an issue report to verify the fault code? For most faults that happen during bolusing, the pod will tell us how much insulin was delivered.  Marion's guess is a good one; if the fault message does not contain the amount remaining, we error on the side of caution (generally it's safer to assume more delivery than less if there is uncertainty) and assume the full amount is delivered. To be able to work on such a feature, we'd want to recreate the situation as closely as possible, so if you did capture an issue report for this, it would be useful.

**Comment by AdrianWGit** [comment]
Hi Pete – another famous looping name!

I didn’t notice any error message about insulin quantity delivered although I was a bit distracted by the pod screaming!
Attached  is the loop report.  I also tried sending the Export report but the email server bounced it.

As an aside – I believe error 018 is a low battery or static error.    I can’t think static is much of an issue in damp old England.  I have noticed that loop is auto-bolusing   every minute (if a bolus is needed) and fairly often sets temp basal every minute or two.  I am using  libre 2 and Xdrip4IOS  client.  Xdrip docs note that libre 2 updates xdrip every minute.   I don’t recall this happening with my old setup of FreeAPS and Libre 2 but I may be wrong.  It certainly didn’t with libre 1.  II can’t help wondering if the 1 min pulse leads to extra comms traffic with the pod and therefore extra stress on the pod battery.  The bolus amount looks right.  Ie I would expect loop to deliver 40% of the calculated insulin requirement in a single bolus every 5 mins.  It now delivers 1/5 of that amount each min.  Although it does lead to lots of 0.05U deliveries!

Best Wishes and many thanks for your dedication to a lifechanging app

Adrian


From: Pete Schwamb ***@***.***>
Date: Friday, 27 January 2023 at 16:03
To: LoopKit/Loop ***@***.***>
Cc: AdrianWGit ***@***.***>, Author ***@***.***>
Subject: Re: [LoopKit/Loop] Loop 3.0.0 Insulin dose wrongly reported on Eros failure (Issue #1913)

So yes, I think we could talk about a change to help handle this. Did we ever get an issue report to verify the fault code? For most faults that happen during bolusing, the pod will tell us how much insulin was delivered. Marion's guess is a good one; if the fault message does not contain the amount remaining, we error on the side of caution (generally it's safer to assume more delivery than less if there is uncertainty) and assume the full amount is delivered. To be able to work on such a feature, we'd want to recreate the situation as closely as possible, so if you did capture an issue report for this, it would be useful.

**Comment by itsmojo** [comment]
An 018 fault is a reset fault (a MCU reset with a Low Voltage Detect) which will reinitialize most all of pod’s data so the bolus not delivered and total insulin delivered values will be reported as zero. However Loop can compute a max bolus delivered value for a mid-bolus reset fault using a time based calculation using its state. This can be done in handlePodFault() when the fault has a zero totalInsulinDelivered (aka is a reset type fault) and podState.unfinalizedBolus is non-nil (the bolus hasn’t be reconciled by Loop yet). The max bolus delivered amount can be computed taking the difference in the time when handlePodFault() is called with podState.fault == nil (i.e., the time that Loop first notices the pod fault) and unfinalizedBolus.startTime (the time the bolus was started) and multiplying by 0.025 U/sec (i.e., two 0.05U pulses/sec for bolus) [N.B. a more complicated version would be needed if Loop ever supports extended boluses]. This value should also be limited to a max of unfinalizedBolus.units (i.e., the entire bolus amount). Another sanity check for this value is a minimum value which can be computed as the difference of podState.lastInsulinMeasurements.validTime (i.e., the time of the last status response) and unfinalizedBolus.startTime and multiplying by 0.025 U/sec. The computed max bolus delivered with a reset fault can then be used for an alternate bolusNotDelivered value (bolus size - max computed bolus delivered) to use in place of the fault.bolusNotDelivered value (which will always be 0 for any reset fault) in the call to handleCancelDosing().

It would be a complete pain to try and test this new code using actual pod reset faults. The better way to go would be update the Dash pod simulator to return a DetailedStatus with various values being zeroed for the reset types faults (013, 014, 015, 016, 018, 030, 034, 052, 054, 059, 060 and 079 for Eros/Dash, but Dash might have some more) to allow for easy reset fault handling in Loop. This particular issue with overly conservative insulin accounting after pod reset faults is not new for Loop 3, but from my personal testing these reset type pod faults might be prominent now for Loop 3 in some circumstances with Eros and older/expired/marginal pods.

**Comment by AdrianWGit** [comment]
Hi All

I had another pod fail today after 2.5 days.  Same 018 error.  Same batch as before, expiry 22/2/23.  Here is the loop report.  Loop had issued an instruction for a 0.05U bolus!

Do you think loop issuing commands to the pump every minute is a potential cause of the failures?  Is this something to be picked up by loop or Xdrip4IOS?  By the way I have the heartbeat on.  I turned it off, but loop still issues commands to the pod every minute.

I may go back to FreeAPS/Xdrip4IOS  when I replace my pod to test if FreeAPS issues pump commands every minute.

Best Wishes

Adrian

From: Pete Schwamb ***@***.***>
Date: Friday, 27 January 2023 at 16:03
To: LoopKit/Loop ***@***.***>
Cc: AdrianWGit ***@***.***>, Author ***@***.***>
Subject: Re: [LoopKit/Loop] Loop 3.0.0 Insulin dose wrongly reported on Eros failure (Issue #1913)

So yes, I think we could talk about a change to help handle this. Did we ever get an issue report to verify the fault code? For most faults that happen during bolusing, the pod will tell us how much insulin was delivered. Marion's guess is a good one; if the fault message does not contain the amount remaining, we error on the side of caution (generally it's safer to assume more delivery than less if there is uncertainty) and assume the full amount is delivered. To be able to work on such a feature, we'd want to recreate the situation as closely as possible, so if you did capture an issue report for this, it would be useful.
