### ISSUE TITLE
6 Omnipod Eros in a row stopped working after about 2 days

### ISSUE THREAD

**Issue by DiaRoller** [LoopKit/Loop#1924]
After the update to loop 3.0 (iPhone 12 Pro, iOS 16.3, loop built with LnL script, incl. CustomTypeOne LoopPatches),my sixt omnipod eros in a raw failed yesterday. All of them failed  after round 2 days or less. Excepting the update to Loop 3.0 there are no differences in my behavior. I have used before the FreeAPS branch. 
I have used pods from 2 different boxes with 2 different expiration dates. Anyway, non of the pods was expired. 

[Export-20230210T193630Z.zip](https://github.com/LoopKit/Loop/files/10713894/Export-20230210T193630Z.zip)
![3412300D-EBE0-4923-BB23-8A2995F77C20](https://user-images.githubusercontent.com/50121568/218264047-965163d2-f0be-439f-ab11-66f86b85070b.png)
![69DAA7DE-60B1-4889-94D0-C1F622529459](https://user-images.githubusercontent.com/50121568/218264052-556bb410-90f3-4af3-b91e-7dc8e6c5506e.png)
![C5BA4613-8640-4BA7-AFC1-E1F79D69EAB3](https://user-images.githubusercontent.com/50121568/218264054-2055e5d8-db29-4ef7-9d02-d8d2a46056d3.png)
![D3970867-9FDF-47EF-8CEB-69E448E671E5](https://user-images.githubusercontent.com/50121568/218264055-9066f386-5bdd-4f72-856c-cf1e32ecf98f.png)
![68CC1DE8-43A1-4474-916C-7935F8EA9755](https://user-images.githubusercontent.com/50121568/218264056-71c9a0e4-ce52-4db1-aad3-1684f3229873.png)
![A3019AFE-D60A-426F-9311-3EB4A827C266](https://user-images.githubusercontent.com/50121568/218264057-9902dac4-8e96-40e8-ab88-7bc7c3e7ec72.png)

**Comment by marionbarker** [comment]
It would be incredibly helpful to have the Loop Reports for these failures:
* https://loopkit.github.io/loopdocs/loop-3/settings/#issue-report

Please review this part of LoopDocs:
* https://loopkit.github.io/loopdocs/faqs/omnipod-faqs/#is-there-an-increase-in-pod-failures-on-loop

**Comment by DiaRoller** [comment]
Meanwhile, further 3 pods failed. In fact, all pods I have used with loop 3.0, failed after about 1 day and 20 hours. 
Please find attached the newer log files. 
Many thanks for your support!
[Export-20230216T062522Z.zip](https://github.com/LoopKit/Loop/files/10762941/Export-20230216T062522Z.zip)
[Export-20230217T025957Z.zip](https://github.com/LoopKit/Loop/files/10762947/Export-20230217T025957Z.zip)
[Loop Report 2023-02-16 07:28:17+01:00.zip](https://github.com/LoopKit/Loop/files/10762956/Loop.Report.2023-02-16.07.28.17%2B01.00.zip)
[Loop Report 2023-02-17 03:59:23+01:00.zip](https://github.com/LoopKit/Loop/files/10762957/Loop.Report.2023-02-17.03.59.23%2B01.00.zip)
[Loop Report 2023-02-17 03:59:23+01:00.zip](https://github.com/LoopKit/Loop/files/10762960/Loop.Report.2023-02-17.03.59.23%2B01.00.zip

**Comment by marionbarker** [comment]
Sorry to be slow getting back to you.
The Radio On % for your Eros pods is pretty high.
Do you leave your phone unlocked with Loop in the foreground a lot? If so, try to leave phone locked with Loop in background.

Please read this section:
https://loopkit.github.io/loopdocs/faqs/omnipod-faqs/#is-there-an-increase-in-pod-failures-on-loop

**Comment by DiaRoller** [comment]
Yes, I leave my phone unlocked with loop in the forderground over the night. I use to check my glucose with an eye, when I turn in bed. But I do that since I‘m a looper, there are about 4 years now. I never had this issue befor upgrading to loop 3.0. The pods are still failing after about 2 days, non of them worked 3 days, as expected. Sent using the mobile mail appOn 27.02.23 at 22:23, Marion Barker wrote:
                
            
            
                
                    From: "Marion Barker" ***@***.***>Date: 27. February 2023To: "LoopKit/Loop" ***@***.***>Cc: "DiaRoller" ***@***.***>,"Author" ***@***.***>Subject: Re: [LoopKit/Loop] 6 Omnipod Eros in a row stopped working after about 2 days (Issue #1924)
                
                
Sorry to be slow getting back to you.
The Radio On % for your Eros pods is pretty high.
Do you leave your phone unlocked with Loop in the foreground a lot? If so, try to leave phone locked with Loop in background.
Please read this section:
https://loopkit.github.io/loopdocs/faqs/omnipod-faqs/#is-there-an-increase-in-pod-failures-on-loop

**Comment by DiaRoller** [comment]
Meanwhile, I’ve changed my behavior and keep the loop app in the background and my iPhone locked almost all the time. Thus, I’m able to keep the pods active for almost 3 days. But still, non of the pods was active for 3 days + 8 hours. Before upgrading to loop 3.0, I usually used the pods 3 days and 8 hours, excepting when the reservoir was empty. I learned that “Loop 3 updates the pod state every 30 sec (DASH) or 60 sec (Eros)”.  I’m wondering if this is new, compared with older loop versions? Might this make the difference?As new glucose values are available  every 5 minutes, I’m wondering why it is necessary to update the pod status every 30/60 seconds? This might also play a certain role: my insulin consum is very high, I need about 60 units a day, so the pod has a lot of work. However, this wasn’t an issue before loop 3.0. Thanks a lot for your help!Sent using the mobile mail appOn 27.02.23 at 22:23, Marion Barker wrote:
                
            
            
                
                    From: "Marion Barker" ***@***.***>Date: 27. February 2023To: "LoopKit/Loop" ***@***.***>Cc: "Author" ***@***.***>,"DiaRoller" ***@***.***>Subject: Re: [LoopKit/Loop] 6 Omnipod Eros in a row stopped working after about 2 days (Issue #1924)
                
                
Sorry to be slow getting back to you.
The Radio On % for your Eros pods is pretty high.
Do you leave your phone unlocked with Loop in the foreground a lot? If so, try to leave phone locked with Loop in background.
Please read this section:
https://loopkit.github.io/loopdocs/faqs/omnipod-faqs/#is-there-an-increase-in-pod-failures-on-loop

**Comment by ps2** [comment]
There are some updates in dev (https://github.com/LoopKit/OmniBLE/pull/81
and https://github.com/ps2/rileylink_ios/pull/774) to not request pod status as frequently.  These changes may result in Pod Faults not showing in Loop in as timely a manner, but should help reduce comms load. Please try using dev and report your findings.

**Comment by Lytrix** [comment]
I have updated to the latest dev and will report back any findings in this issue going forward, instead of my raised [duplicate issue #1936](https://github.com/LoopKit/Loop/issues/1936). Thanks for looking into this!

**Comment by mn-box** [comment]
And? I have the same issue with my Eros pods. Not even 2 days on the last 4 pods. Thanks!

**Comment by marionbarker** [comment]
@mn-box Please update to 3.2.1 as soon as possible.

**Comment by mn-box** [comment]
Super, running 3.2.1 now.

**Comment by mn-box** [comment]
Running 3.2.1, but my first pod stopped after 1 day and 14 hours (Event Code: 0x12; reset due to LVD)

**Comment by marionbarker** [comment]
Please post a Loop Report. 
Loop, Settings, Support, Issue Report. 
save the file snd upload here or zulipchat.

**Comment by mn-box** [comment]
One more, hope that helps!

[Loop Report 2023-03-31 11_40_46+02_00.md](https://github.com/LoopKit/Loop/files/11124934/Loop.Report.2023-03-31.11_40_46%2B02_00.md)

**Comment by mn-box** [comment]
Hi Marion,

Any developments? I have not been able to downgrade and running through my pods quickly. 48 hours is the current max. Let me know if you need more details to help resolve this. 

Thanks!

**Comment by itsmojo** [comment]
Took a quick look at the Loop Reports and noticed lots of one minute intervals between automatic boluses and temp basals. Looping this often creates excessive pod load resulting in depleted pod batteries resulting in the "0x12: Reset due to LVD", "0x34: Reset from unknown cause", and the "0x3d: Problem with pump anchor" pod faults seen in these reports.

The version of Loop being run is Loop v3.2.1 (57), the CGM Manager appears to be xDrip, and the pods are Eros. The cachedGlucoseSamples StoredGlucoseSamples show new BG values as close as one minute apart. Unfortunately Loop v3.2.1 doesn't appear to be enforcing a reasonable minimal loop interval time (i.e., something greater than 4.5 minutes) in this set up which results in the various classical pod faults from an overloaded pod with depleted batteries.

**Comment by marionbarker** [comment]
Sorry I haven’t looked at these. 

My understanding is that xDrip4iOS has a switch to limit CGM output to 5 minutes. If that is not working, I added this customization to LoopDocs. 

https://loopkit.github.io/loopdocs/build/code_customization/#limit-loop-for-faster-cgm

**Comment by mn-box** [comment]
Thanks for the quick analyses. i have adjusted XDrip4iO5 to only share data every 5 minutes. I didn’t realize that this would be an issue for loop (and thought the quicker iterations is always better 😀). Big thanks!

**Comment by mn-box** [comment]
Unfortunately, I am still not making it to 3 days. My last two pods ended in 1,5 days with a Fault Event Code 0x40: Encoder count too high (Ref: 19-02443-14651-064). Please find attached the report.

[Loop Report 2023-04-17 20_18_59+02_00.md](https://github.com/LoopKit/Loop/files/11254204/Loop.Report.2023-04-17.20_18_59%2B02_00.md)

Thanks!

**Comment by marionbarker** [comment]
@mn-box Looks like a Libre without limiting CGM updates to once per 5 minutes.

Consider using this customization if you can't get your Libre client to limit updates.
* [Limit Loop Cycle Time](https://www.loopandlearn.org/custom-code/#loop-cycle-time)

These are the instructions for using this type of customization:
* [Mac-Xcode Builders](https://www.loopandlearn.org/custom-code/#mac-xcode-intro)
* [GitHub Builders](https://www.loopandlearn.org/custom-code/#github-intro)

For introductory material - start at the top of that page (all links above are direct to specific sections on the same page)

**Comment by mn-box** [comment]
Thanks Marion, I have Xdrip4iOS "share to Loop every 5 mins" enabled. But strange enough I see multiple loop adjustments (temp basal / bolus) within 5 mins. I have adjusted the loop code (to limit to 4.8 min), thanks for pointing me in the right direction.

**Comment by philippfo9** [comment]
Having the same problem running Dexcom G6. What could I possibly do?

**Comment by philippfo9** [comment]
Here is my report!

[Loop Report 2024-01-02 19:08:52+01:00.md](https://github.com/LoopKit/Loop/files/13812829/Loop.Report.2024-01-02.19.08.52%2B01.00.md)

**Comment by philippfo9** [comment]
Having the same problem running Dexcom G6, two pods deactivated in the row @marionbarker.
What could I possibly do? Here is my report!
[Loop Report 2024-01-02 19:08:52+01:00.md](https://github.com/LoopKit/Loop/files/13812829/Loop.Report.2024-01-02.19.08.52%2B01.00.md)
