### ISSUE TITLE
App is all white

### ISSUE THREAD

**Issue by BEMikkelsen** [LoopKit/Loop#1925]
Hello. First of all I am not a specialist in x-code or computers. But I want so hard to succeed building the loop application for my little sister to help improve her life with diabetes. So now I have fallowed the recipe and have got the Loop app installed on her iPhone 14, but when I try to use the app its only all a white screen, wich I cant get forward from.  There is no red warnings in x-code and it says that Loop is running on her iPhone. Ive been trying to delete the app and installed it again many times, but it all comes back to this problem. Is there another way to do this maybe? Thanks for your time and help.

**Comment by ps2** [comment]
There is an attempt at fixing this in progress. If you would be up for building and installing the hk-auth-crash-fix branch of LoopWorkspace, I'd love to know if this fixes your issue. See https://loopkit.github.io/loopdocs/version/loopworkspace/?h=branch#clone-loopworkspace as a guide if you're not familiar with building a specific branch.
