### ISSUE TITLE
LOOP freezes and crashes every few minutes

### ISSUE THREAD

**Issue by sorin-florea** [LoopKit/Loop#1926]
**Describe the bug**
Starting a few days ago, loop started freezing and crashing after a few minutes every time I navigate away from the app on my iPhone. I did not update a new version, it just started happening. Due to this, I am no longer able to get a green loop.

I also tried updating but to no avail. I also reinstalled my phone, and the same thing started happening. What I changed recently is that I am using Dexcom ONE (this worked fine for a few days), then I installed xDrip, and 1-2 days afterward it started happening. I have uninstalled xDrip, but it keeps happening the same.

My suspicion is that this is due to my phone having issues, but I am not sure.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Open loop
2. Navigate away
3. Come back after 1 minute (sometime even 10 seconds), the app is frozen and requires to be closed and started again

**Phone**
 - Hardware: iPhone 11 Pro Max
 - OS Version: 16.3 (was happening on 15 as well)
**Loop Version**
 - Version Number: v3.0.0 (57) - was happening on previous 3 as well
 - Repo: LoopKit/Loop
 - 
**CGM**
 - Device: Dexcom One
 - Manager app: Dexcom one app

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros

[Loop Report 2023-02-11 10/06/55+01/00.md](https://github.com/LoopKit/Loop/files/10730116/Loop.Report.2023-02-11.10.06.55%2B01.00.md)
[Loop Report 2023-02-14 08/24/19+01/00.md](https://github.com/LoopKit/Loop/files/10730117/Loop.Report.2023-02-14.08.24.19%2B01.00.md)

[loop-ips.zip](https://github.com/LoopKit/Loop/files/10730126/loop-ips.zip)

**Comment by sorin-florea** [comment]
Update, I think this is possibly due to Dexcom one. Looks like if I remove the CGM or if I uninstall the dexcom one app it does not freeze anymore.

**Comment by ps2** [comment]
I see iOS killing Loop in your crash logs.  There is an attempt at fixing this in progress.  If you would be up for building and installing the `hk-auth-crash-fix` branch of LoopWorkspace, I'd love to know if this fixes your issue.  See https://loopkit.github.io/loopdocs/version/loopworkspace/?h=branch#clone-loopworkspace as a guide if you're not familiar with building a specific branch.

**Comment by sorin-florea** [comment]
@ps2 After re-installing loop I have no crashes now, if I ever get it again I will try your branch.

**Comment by notyou2019** [comment]
> 

Did you have to delete Loop completely or just rebuild/reinstall?

**Comment by ps2** [comment]
@notyou2019 just install
