### ISSUE TITLE
Dash Pod Screaming but no Error/Notice in Loop

### ISSUE THREAD

**Issue by absmindedprof** [LoopKit/Loop#1927]
**Describe the bug**
My pod started screaming (constant high pitched beep), but there is no error or notification in Loop unless I try to issue a pump command (bolus/temp basal/suspend etc) at which point I get a "pod not connected" alert. 

**Attach an Issue Report**
Will attach to comment - on mobile. 

**To Reproduce**
Unclear. 

**Expected behavior**
A pod error will be accompanied with a notification and information in Loop app.

**Screenshots**
![image](https://user-images.githubusercontent.com/3060874/218900845-ed00d3d5-c946-40c4-bdd1-94099ce0e5f6.png)

![image](https://user-images.githubusercontent.com/3060874/218900860-7e0e07e1-2d1f-4f01-af0f-c8d388cefdee.png)

**Phone**
 - Hardware: iPhone 12 Mini
 - OS Version: iOS 16.3.1

**Loop Version**
 - Version Number: 2.3.0
 - Repo: dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Dash
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by marionbarker** [comment]
This sounds like you had a double error.
* Loop has lost the ability to talk to the pod 
* AND there was a pod fault

Loop can only report the FAULT if it can talk to the pod.
At this point, you could do all the red-loop resolutions steps, but with a screaming pod, many people do not bother. And there are some failures where the Pod just won't communicate anyway.

If Loop is able to establish a communication link with the pod and you hear a screaming pod and open Loop, there still might be a 30-sec delay before the pod fault is reported or No Signal is reported. Loop checks frequently (every 30-seconds) when phone is unlocked and Loop is open. With the phone locked, Loop typically checks once every 3 to 5 minutes.)

Also - looks like you are running from a dev build prior to release. Without the Loop Report, can't tell how old the build.

I do not think this is a code problem that can be resolved and this issue should probably be closed.
