### ISSUE TITLE
Dash pod obstruction after ~2 days. 

### ISSUE THREAD

**Issue by david-lively** [LoopKit/Loop#1932]
**Describe the bug**
I'm not sure if this is a bug, but it was weird. A functioning pod just started screaming and Loop said that there was an occlusion. Submitting the report here in case it's a legitimate issue. 

**Occlusion Detected**

* identifier: OmniBLE:pumpFault.Fault Event Code 0x14: Occluded
* issued: 2023-02-24 16:43:44 +0000
* acknowledged: 2023-02-24 16:43:52 +0000
* retracted: n/a
* trigger: immediate
* interruptionLevel: timeSensitive
* foregroundContent: {"title":"Occlusion Detected","acknowledgeActionButtonLabel":"OK","body":"Insulin delivery stopped. Change Pod now."}
* backgroundContent: {"title":"Occlusion Detected","acknowledgeActionButtonLabel":"OK","body":"Insulin delivery stopped. Change Pod now."}
* sound: n/a
* metadata: n/a

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 16.3.1

**Loop Version**
 - Version Number: 3.0
 - Repo: LoopKit/Loop

**CGM**
 - Device: Libre 3
 - Manager app: Glucose Direct

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod DASH
 - Firmware version: 4.10.0

**Additional context**
[Loop Report 2023-02-24 13:32:14-06:00.md](https://github.com/LoopKit/Loop/files/10828237/Loop.Report.2023-02-24.13.32.14-06.00.md)

**Comment by ps2** [comment]
If the pod reports occlusion, and your comms logs indicate it did, then this is Loop behaving as expected. If you don't think there was an actual occlusion, then it's possible the pod had a false detection.
