### ISSUE TITLE
[Omnipod DASH] Parse FirstBlePackage

### ISSUE THREAD

**Issue by bastiaanv** [LoopKit/Loop#1933]
**Describe the bug**
In `BlePackage.swift` file on line 66 is a guard statement that checks if the `fullFragments` is greater than zero, if not it throws an error. But a bit further in the code, on line 74, there is a statement that if `fullFragments` equals zero, it should build the packet as there is only one packet. While I think there will not be a lot of cases where only one packet is send from the Pod, I do think that the last if statement is correct and the guard statement at line 66 should be removed.

Line 66:
```swift
guard (fullFragments > 0) else {
  throw PodProtocolError.messageIOException("Invalid message with 0 fragments")
}
```

Line 74:
```swift
if (fullFragments == 0) {
  let rest = payload[6]
  let end = min(Int(rest) + HEADER_SIZE_WITHOUT_MIDDLE_PACKETS, payload.count)
  guard payload.count >= end else {
    throw PodProtocolError.messageIOException("Wrong packet size")
  }

  return FirstBlePacket(
    fullFragments: fullFragments,
    payload: payload.subdata(in: HEADER_SIZE_WITHOUT_MIDDLE_PACKETS..<end),
    size:  rest,
    crc32: payload.subdata(in: 2..<6),
    oneExtraPacket:  Int(rest) + HEADER_SIZE_WITHOUT_MIDDLE_PACKETS > end
  )
}
```

**Expected behavior**
The guard statement in file `BlePackage` on line 66 should be removed

**Loop Version**
 - Version Number: latest / `dev`-branch
 - Repo: OmniBle

**Pump**
 - Manufacturer: Omnipod DASH
 - Model: N.A.
 - Firmware version: N.A.

**Comment by ps2** [comment]
Does this cause a reproducible issue in actual use?

**Comment by ps2** [comment]
IIRC, I was seeing cases where pod comms would fail, and there would be a packet with all zeros, and continuing would cause problems.

**Comment by ps2** [comment]
Closing this. If there is evidence that 1) the current behavior is problematic and 2) that removing the guard works for both kinds of Dash pods (NXP and TWI), I can consider taking the proposed fix.
