### ISSUE TITLE
Integrate OpenFoodFacts food search API into Loop's "Add Carb Entry" screen (+barcode scan +voice dictation)

### ISSUE THREAD

**Issue by taylorpatterson007** [LoopKit/Loop#1939]
New feature request: As a Loop user I want to be able to search for food types in the Add Carb Entry bolus screen that pulls carbohydrate data from Calorie King's Food API (https://www.calorieking.com/us/en/developers/food-api/) so that I avoid using multiple apps and can improve the accuracy of bolus entries. 

The search return should give me carbs per serving, serving sizes and serving type and the screen modification would also allow me to modify the serving size that then automatically recalculates the carbs needed to be entered in order to correctly bolus.

I searched and was unable to find any other feature requests for a similar capability so I am submitting this here.

(moved the bar code lookup to its own feature request)

**Comment by taylorpatterson007** [comment]
Additional research uncovered this free open source Food API: https://world.openfoodfacts.org/
Hitting a sample URL for Coke Zero with the barcode in the URL (https://world.openfoodfacts.org/api/v0/product/5449000131805.json) results in a very usable response. 

Add barcode camera capture button in carb entry form, scanned barcode puts code in a preformed URL, response is read and the carbohydrates and serving sizes extracted, plugged into the carb entry screen, can be adjusted and recalculated by chaning the serving size, press the give insuling button and bob's your uncle!

**Comment by taylorpatterson007** [comment]
Adding wireframe and additional barcode/voice documentation for the iPhone/Watch
Additional research found to integrate a food search and carb and servings lookup into Loop

Add a food search bar 
Add a serving size bar with adjusters that when pressed, adjust the Amount Consumed entry accordingly

![Screenshot 2023-03-22 at 1 22 40 PM](https://user-images.githubusercontent.com/20686389/227029093-b900957d-661e-4818-8be1-c69ddec57d40.png)


User can use normal manual carb entry, or a new dictation feature to enter words to search the food database with, or a barcode scanner for code lookup. Within the barcode scan screen they can manually enter a barcode number if they wish.
![Screenshot 2023-03-22 at 1 22 47 PM](https://user-images.githubusercontent.com/20686389/227029143-d2cb57b1-e938-4ce9-afcb-8f29ce7a5b0f.png)


Scanning, dictating or entering a barcode number manually into the search bar hits the OpenFoodFacts API and returns the Description (product_name), Serving Size (nutriments:carbohydrates_serving) and Carbs Per Serving (nutriments:carbohydrate) and automatically enters them into the UI for fine tuning by user.
As the user adjusts the serving count, Loop automatically updates Amount Consumed until the user is satisfied with the entry and then hits Continue for injection.

Research found on the OpenFoodFacts API with sample documentation: https://openfoodfacts.github.io/openfoodfacts-server/api/

Example URL for Kirkland Soft & Chewy Granola Bar: https://world.openfoodfacts.org/api/v0/product/096619313952.json

![Screenshot 2023-03-22 at 1 22 55 PM](https://user-images.githubusercontent.com/20686389/227029206-2f52451e-6149-454a-8bd0-96522bc26cb7.png)

Research found to integrate a barcode reader dictation capability with carb/servings lookup into Loop for iPhone OS

Apple Developer barcode documentation: https://developer.apple.com/documentation/vision/vnbarcodeobservation
[Declaration](https://developer.apple.com/documentation/vision/vndetectbarcodesrequest/3750958-results#declaration)
var results: [[VNBarcodeObservation](https://developer.apple.com/documentation/vision/vnbarcodeobservation)]? { get }

[Parsing the Payload](https://developer.apple.com/documentation/vision/vnbarcodeobservation#2923626)
[var payloadStringValue: String?](https://developer.apple.com/documentation/vision/vnbarcodeobservation/2923485-payloadstringvalue)
A string value that represents the barcode payload.

Apple Developer speech recognition documentation: https://developer.apple.com/documentation/speech

**Comment by taylorpatterson-T1D** [comment]
Developed and submitted pull request for AI-Enabled Food Search here: https://github.com/LoopKit/Loop/pull/2325
