### ISSUE TITLE
Bolus not recorded in active insulin, extra insulin delivered

### ISSUE THREAD

**Issue by joshandeliana** [LoopKit/Loop#1941]
Very typical breakfast this morning for my daughter: 40 carbs, carb ratio means 3.45 units and I give an extra unit to superbolus it. I do not remember watching for the orange circle when I dosed. I did notice the 4.45 in Nightscout. Next thing I see is loop did two autoboluses. I checked the active insulin screen (which I thought is the definitive answer on whether a bolus happened) and saw no 7:10am bolus. So I added the rest of what should have been delivered and she went urgent low (gave extra carbs right away). The IOB in Nightscout matches the active insulin report, but symptoms do not. Hopefully I’ve provided enough information. Will definitely be watching for the orange circle from now on but interested to know what happened here?

![C1D78FC1-465F-4BE4-8A66-7848F18A70EE](https://user-images.githubusercontent.com/101681801/224321065-9ef0cfb5-013e-424e-b46e-aa06516eb7ae.jpeg)
![0242481D-0166-4B21-BA85-2A1A8F546136](https://user-images.githubusercontent.com/101681801/224321069-031c0f96-0620-4054-93df-c9ab74886a54.png)
![ADAD61F9-EC3D-41AA-8F9F-96B7AAB7715F](https://user-images.githubusercontent.com/101681801/224321073-8eed1254-61ce-4b19-8843-c070bc8a181a.png)

**Comment by joshandeliana** [comment]
I did try to attach an issue report, not sure if it went through.

**Comment by ps2** [comment]
The issue report does not appear to be attached here. The issue report would be very helpful here. Also, if you can export the critical device logs, that might help as well.

**Comment by joshandeliana** [comment]
[Loop Report 2023-03-10 07 45 18-05 00.md](https://github.com/LoopKit/Loop/files/10943456/Loop.Report.2023-03-10.07.45.18-05.00.md)

**Comment by joshandeliana** [comment]
Figured out how to add it, sorry for the delay! Looper and loop phone are at school until 4pm. Please give me instructions to generate any additional reports at that time. I did see a recent issue report that looked very similar although they were more skeptical and stopped the rest of the additional insulin. I did need to correct with a full 40 carbs, so clearly the dose was delivered initially even though it did not show in the IOB or insulin delivery screen. A similarity I noticed with the other issue report is that we both changed the recommended bolus, but that's something I do all the time and have never had a problem.

**Comment by joshandeliana** [comment]
[Export-20230310T210553Z.zip](https://github.com/LoopKit/Loop/files/10946093/Export-20230310T210553Z.zip)

**Comment by ps2** [comment]
Thanks @joshandeliana ! Sorry you had issues, and I'm glad everyone is safe. Thank you for sharing your logs. I spent a couple hours digging into this tonight. You're correct that the 4.45 bolus *was* delivered. I could see in the logs that Loop successfully sent the command to the pod, and the pod responded properly. After a lot of code review, I've discovered a bug that I believe is the cause of this "disappearing" bolus. It's a very subtle bug, and requires a very specific set of circumstances to trigger.

The bolus was delivered at 2023-03-10 12:11:24 (UTC time). Loop tracks how long it expects a bolus to take to deliver.  In this case, 4.45 U at a rate of 0.05 U every 2 seconds, should take 2 minutes and 58 seconds. By a crazy coincidence, your pod's communication reset with a timing such that Loop requested the status exactly 2 minutes and 58 seconds later. The pod at this point responded that no bolus was being delivered. When Loop is tracking a bolus, and the pod reports that no bolus is ongoing, normally Loop assumes the bolus is complete, and sends it to finalized storage.  However, there is a bug in the code if Loop thinks there is still remaining time on the bolus, it will mark it as unfinished, which ultimately caused it to be eventually dropped.  For this set of events to happen, the status request has to happen in the short time interval (in this case < 1s) between the actual bolus completion and Loop's estimation of the completion.

I am working on a fix that will prevent this from happening in the future. Thanks for helping to improve Loop!

**Comment by blameitonben** [comment]
👏!
________________________________

**Comment by joshandeliana** [comment]
Thank you Pete for the timely and thorough explanation. 

I thought I was being so clever by trusting the active insulin log and not nightscout. I hope that if it hadnt been the school morning rush I would have been more cautious and waited to see how blood sugar responded before giving more insulin. It did take 50+ grams of extra carbs to get her back on track, some of which I had to deliver at the nurse's office after taking her to school. I was a bit nervous to tell the school nurse what was happening as I dont want them asking any questions about loop. I now feel very confident if there are any questions, because commercial systems have glitches too, but you dont get to troubleshoot with the software's creators in those situations! 

Very grateful for loop and all of its contributors!

**Comment by joshandeliana** [comment]
Issue 1886 is the other one I found that looked similar, in case this is helpful.

**Comment by Blanderson86** [comment]
Hi, 

I have had this happen to me/my sons teachers about 4 times the last couple of months. Most recently today. I can attach my issue report

**Comment by Blanderson86** [comment]
[Loop Report 2023-03-12 205531Z.zip](https://github.com/LoopKit/Loop/files/10952123/Loop.Report.2023-03-12.205531Z.zip)

**Comment by ps2** [comment]
A fix for this just landed in dev.  I would appreciate any testing that anyone is able to do with this update. You can test by [building the latest dev](https://loopkit.github.io/loopdocs/version/build-dev/).  Please join the loop zulip chat if you're not already there: (https://loop.zulipchat.com/)
