### ISSUE TITLE
Loop app blank white screen on launch

### ISSUE THREAD

**Issue by SunnyL81** [LoopKit/Loop#1945]
Loop app was bringing up blank white screen on launch after update to loop 3 version.  Seems to be related to Apple health glitch, however I was not able to access the Health App “Data Access & Devices” permissions to turn off permissions to the Loop app.  It would just sit there and spin the waiting circle indefinitely.  I was not able to delete any health data.

Some Googling revealed that it may have been related to my Apple Watch health app.  I unpaired the watch and did not restore from any backup.  After unpairing the watch I was immediately able to access the Apple health “Data Access & Devices” and turn off Loop from iCloud and delete the app data.

I turned on developer mode on the watch and rebuilt the Loop app and it works now.

Just thought it might help to add that this might be a potential solution to the Loop crash / blank screen issue page in loopdocs about the Apple Health Glitch.

**Comment by marionbarker** [comment]
Thanks for reporting this.
