### ISSUE TITLE
Loop crashes when I click on issue report

### ISSUE THREAD

**Issue by metanzi** [LoopKit/Loop#1946]
When I go into support and click on issue report, loop app crashes. Issue report does not pull up.

**Comment by metanzi** [comment]
Resolved. Loop time not the same as phone. Sync time and issue report opened after that.

**Comment by ps2** [comment]
Having your therapy settings/pump on a different time than the phone should be fine, and not cause Loop to crash. Could you check to see if you have crash files from this? They are .ips files that are located in iOS settings -> Privacy & Security ->Analytics & Improvements -> Analytics Data, and should start with "Loop" and have a timestamp of when you were seeing Loop crash.

**Comment by metanzi** [comment]
Yes, there is. How do I send the files?
Thank you
Mara

Sent from my iPhone

On Mar 12, 2023, at 23:30, Pete Schwamb ***@***.***> wrote:

﻿

Having your therapy settings/pump on a different time than the phone should be fine, and not cause Loop to crash. Could you check to see if you have crash files from this? They are .ips files that are located in iOS settings -> Privacy & Security ->Analytics & Improvements -> Analytics Data, and should start with "Loop" and have a timestamp of when you were seeing Loop crash.

**Comment by ps2** [comment]
You'll need to send them to your computer somehow, like via airdrop, or email them. Then you can attach them to this github ticket from your computer.

**Comment by metanzi** [comment]
Thank you
Will do when I get home from work.
Thank you
Mara

Sent from my iPhone

On Mar 13, 2023, at 09:14, Pete Schwamb ***@***.***> wrote:

﻿

You'll need to send them to your computer somehow, like via airdrop, or email them. Then you can attach them to this github ticket from your computer.

**Comment by metanzi** [comment]
Here is the file
{"app_name":"Loop","timestamp":"2023-03-12 15:37:33.00 -0400","app_version":"3.0.0","slice_uuid":"c7fe2aa6-fbfd-3f3b-aaf8-515b4f895120","build_version":"57","platform":2,"bundleID":"com.G4Y86K3X5L.loopkit.Loop","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.3.1 (20D67)","roots_installed":0,"name":"Loop","incident_id":"99B19450-3571-483C-B4CB-CB299197A0A2"}
{
  "uptime" : 56,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone15,2",
  "coalitionID" : 498,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.3.1",
    "releaseType" : "User",
    "build" : "20D67"
  },
  "captureTime" : "2023-03-12 15:37:32.8299 -0400",
  "incident" : "99B19450-3571-483C-B4CB-CB299197A0A2",
  "pid" : 319,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-03-12 15:37:18.5744 -0400",
  "procStartAbsTime" : 1003606304,
  "procExitAbsTime" : 1345655097,
  "procName" : "Loop",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/C3EE4BD8-08A3-412D-8FCD-67E634EE5653\/Loop.app\/Loop",
  "bundleInfo" : {"CFBundleShortVersionString":"3.0.0","CFBundleVersion":"57","CFBundleIdentifier":"com.G4Y86K3X5L.loopkit.Loop"},
  "storeInfo" : {"deviceIdentifierForVendor":"267083E7-035C-4021-BDEE-2C1666E8FFE1","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.G4Y86K3X5L.loopkit.Loop",
  "crashReporterKey" : "05d5a045f5d46cdd7a7c71d08dc834b6db7e6358",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "throttleTimeout" : 2147483647,
  "basebandVersion" : "1.41.02",
  "exception" : {"codes":"0x0000000000000001, 0x000000018ae1dedc","rawCodes":[1,6625025756],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":319},
  "os_fault" : {"process":"Loop"},
  "faultingThread" : 6,
  "threads" : [{"id":5155,"queue":"com.apple.main-thread","frames":[{"imageOffset":3496,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":80412,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":80988,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4844,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502468,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":1},{"imageOffset":507144,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":1},{"imageOffset":528048,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":1},{"imageOffset":4968,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":2},{"imageOffset":3806824,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":3},{"imageOffset":3805900,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":3},{"imageOffset":2912772,"symbol":"main","symbolLocation":180,"imageIndex":4},{"imageOffset":88416,"symbol":"start","symbolLocation":2528,"imageIndex":5}]},{"id":5161,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":5163,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":5164,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":3496,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":80412,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":80988,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4844,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502468,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":1},{"imageOffset":507144,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":1},{"imageOffset":528048,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":1},{"imageOffset":270420,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":7},{"imageOffset":270140,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":64,"imageIndex":7},{"imageOffset":5072548,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":436,"imageIndex":3},{"imageOffset":374040,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":7},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":5167,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":5168,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"triggered":true,"id":5280,"threadState":{"x":[{"value":16140901064495857664},{"value":0},{"value":0},{"value":10738017056},{"value":0},{"value":6170349984},{"value":100},{"value":1},{"value":512},{"value":511},{"value":8960},{"value":2043},{"value":2668546342},{"value":2045},{"value":2670645529},{"value":2668546342},{"value":281},{"value":522190848},{"value":0},{"value":16140901064495857664},{"value":2},{"value":0},{"value":32},{"value":4333131632},{"value":0},{"value":4333128080},{"value":19},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6625025756},"cpsr":{"value":1610616832},"fp":{"value":6170350320},"sp":{"value":6170350192},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6625025756,"matchesCrashFrame":1},"far":{"value":24530190336}},"queue":"com.loopkit.CarbStore.queue","frames":[{"imageOffset":229084,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":664,"imageIndex":8},{"imageOffset":229084,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":664,"imageIndex":8},{"imageOffset":253604,"symbol":"static DailyValueSchedule.zip<A, B>(_:_:)","symbolLocation":1872,"imageIndex":9},{"imageOffset":640696,"symbol":"*\/ infix(_:_:)","symbolLocation":584,"imageIndex":9},{"imageOffset":110644,"symbol":"static DailyQuantitySchedule<>.carbSensitivitySchedule(insulinSensitivitySchedule:carbRatioSchedule:)","symbolLocation":84,"imageIndex":9},{"imageOffset":2360468,"symbol":"CarbStore.carbSensitivitySchedule.getter","symbolLocation":464,"imageIndex":9},{"imageOffset":2460788,"symbol":"closure #1 in CarbStore.generateDiagnosticReport(_:)","symbolLocation":4500,"imageIndex":9},{"imageOffset":133568,"symbol":"thunk for @escaping @callee_guaranteed () -> ()","symbolLocation":48,"imageIndex":9},{"imageOffset":9312,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":10},{"imageOffset":16264,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":10},{"imageOffset":46656,"symbol":"_dispatch_lane_serial_drain","symbolLocation":672,"imageIndex":10},{"imageOffset":49548,"symbol":"_dispatch_lane_invoke","symbolLocation":384,"imageIndex":10},{"imageOffset":93712,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":652,"imageIndex":10},{"imageOffset":3576,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":6},{"imageOffset":2968,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":6}]},{"id":5282,"name":"com.apple.CFSocket.private","frames":[{"imageOffset":6412,"symbol":"__select","symbolLocation":8,"imageIndex":0},{"imageOffset":833172,"symbol":"__CFSocketManager","symbolLocation":636,"imageIndex":1},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":6},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":6}]},{"id":5283,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]},{"id":5290,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":6}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7762837504,
    "size" : 229356,
    "uuid" : "c76e6bed-4635-30c6-8f19-fb829bbe1ae1",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6727774208,
    "size" : 4087808,
    "uuid" : "42ccfc7b-ff32-3d25-8f01-ccb2ad843a8b",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7703429120,
    "size" : 36864,
    "uuid" : "85419099-269b-336d-86b4-0d52d0ff6923",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6763249664,
    "size" : 25116672,
    "uuid" : "cf21ad9c-efbf-3961-a7c0-54bd30cefea9",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4302241792,
    "size" : 4390912,
    "uuid" : "c7fe2aa6-fbfd-3f3b-aaf8-515b4f895120",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/C3EE4BD8-08A3-412D-8FCD-67E634EE5653\/Loop.app\/Loop",
    "name" : "Loop"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7240937472,
    "size" : 536724,
    "uuid" : "4b042f28-0d14-30ec-a1de-3dbb10866ad7",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8039022592,
    "size" : 49152,
    "uuid" : "45ac734e-6649-3ee2-a096-3fd66441ab78",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6630678528,
    "size" : 9740288,
    "uuid" : "e5f615c7-cc5e-3656-8600-41c767812a35",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6624796672,
    "size" : 5672960,
    "uuid" : "56c020fc-0369-3775-b947-148f388a65b3",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4330143744,
    "size" : 3194880,
    "uuid" : "8d6186a6-8cb9-3527-8e42-e0c732397e6d",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/C3EE4BD8-08A3-412D-8FCD-67E634EE5653\/Loop.app\/Frameworks\/LoopKit.framework\/LoopKit",
    "name" : "LoopKit"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6851629056,
    "size" : 290816,
    "uuid" : "ded4d0a5-1420-32ae-83a6-c31d938a1c9a",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  }
],
  "sharedCache" : {
  "base" : 6611140608,
  "size" : 2950873088,
  "uuid" : "c617a1ab-01c8-39d4-93ed-014e0fd16eb7"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=888.8M resident=0K(0%) swapped_out_or_unallocated=888.8M(100%)\nWritable regions: Total=609.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=609.0M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                    1760K        8 \nColorSync                           96K        6 \nCoreAnimation                     13.4M       33 \nCoreData                            32K        1 \nCoreData Object IDs               4112K        2 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           583.3M      181 \nMALLOC guard page                  128K        8 \nSQLite page cache                  896K        7 \nSTACK GUARD                        160K       10 \nStack                             5904K       10 \nVM_ALLOCATE                       1184K        3 \n__AUTH                            2545K      305 \n__AUTH_CONST                      21.3M      513 \n__CTF                               756        1 \n__DATA                            9547K      535 \n__DATA_CONST                      25.6M      543 \n__DATA_DIRTY                      2465K      440 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       338.4M       27 \n__OBJC_CONST                      4703K      325 \n__OBJC_RO                         78.9M        1 \n__OBJC_RW                         2440K        1 \n__TEXT                           550.4M      554 \ndyld private memory                256K        1 \nmapped file                      175.7M       32 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              1.8G     3554 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.loopkit.CarbStore.queue"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6081eda9c724863038027c4f",
      "factorPackIds" : {
        "BIFROST_PROD_2" : "6386a132b2301345401e1862"
      },
      "deploymentId" : 240000982
    },
    {
      "rolloutId" : "61fd92db295c182621ececc3",
      "factorPackIds" : {

      },
      "deploymentId" : 240000344
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by ps2** [comment]
Note to self: this appears to be crashing in `return .carbSensitivitySchedule(insulinSensitivitySchedule: insulinSensitivitySchedule, carbRatioSchedule: carbRatioSchedule)`.   insulinSensitivitySchedule and carbRatioSchedule do not have the same time zone.  Need to review time change update and look for potential places where they could diverge.

**Comment by ps2** [comment]
@metanzi What Loop version was this, and did it have any customizations?

**Comment by metanzi** [comment]
Loop 3 and no customizations.
Mara

Sent from my iPhone

On Mar 18, 2023, at 12:27, Pete Schwamb ***@***.***> wrote:

﻿

@metanzi<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmetanzi&data=05%7C01%7C%7C5a540a48172c4e9ade5108db27cdb762%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638147536718430275%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YEuCUNk2gnwHbO4331MUdI7I4zo8JpkD155Mff4AZuU%3D&reserved=0> What Loop version was this, and did it have any customizations?
