### ISSUE TITLE
App is in English Except Dexcom G7 Settings Page

### ISSUE THREAD

**Issue by mfranzel** [LoopKit/Loop#1951]
Hi,
Everything in the app in 3.2.0 is in English. However, when I go to the G7 settings page, it is all in Spanish. Is this a bug or did I do something wrong?

**Comment by mfranzel** [comment]
![Uploading EDDBA1C5-878F-4038-AB79-14EB47911A7E.jpeg…]()

**Comment by mfranzel** [comment]
![AE77936E-A4B1-45DB-B664-189EA0833F97](https://user-images.githubusercontent.com/66579594/226075923-bd7b3b50-7f01-44df-8898-7e05590a0720.jpeg)

**Comment by loudestnoise** [comment]
https://github.com/LoopKit/Loop/releases/tag/v3.2.1 addresses this per release notes 16 hours ago.

> G7 Plugin localization fixed: was defaulting to Spanish in some cases
