### ISSUE TITLE
Loop 3.2.0 Loop Crashed and insulin adjustments have been paused...

### ISSUE THREAD

**Issue by ebouchut** [LoopKit/Loop#1953]
**Describe the bug**

A few minutes after **successfully** upgrading Loop to 3.2.0 from 3.0.0, Loop crashed (`insulin adjustments have been paused...`).

Here is what I did:
- built Loop 3.2.0 on 2023-03-18 at 15:43 (no errors)
- successfully upgraded Loop to 3.2.0 from 3.0.0
- opened the Loop app on my iPhone to check if everything was ok and it was.  
  All my previous settings, Omnipod DASH and Dexcom G6 were preserved and operational.
- disconnected the iPhone
- quit XCode
- ❌ saw a notification (a few minutes later) on the home screen (2023-03-18 at 16:12) saying a Loop crashed ~12 minutes ago (ie. ~16:00).
- unlocked my iPhone and saw a crash popup in Loop
- clicked `Continue` and experienced no more crash since then

**Attach an Issue Report**

[Loop Report 2023-03-18 16_17_38+01_00.md]
(https://github.com/LoopKit/Loop/files/11009090/Loop.Report.2023-03-18.16_17_38%2B01_00.md)

**To Reproduce**

Cf. bug description.

**Expected behavior**
No crash 

**Screenshots**

> ![2023-03-18-loop_3_2_0-crash-notif-home_screen](https://user-images.githubusercontent.com/73331/226121478-55b0c8d9-be35-4841-91a6-06cd28bb0de6.jpeg)
> ![2023-03-18-Loop-3_2_0-crash-notif-in_app](https://user-images.githubusercontent.com/73331/226121492-e87aba7b-7bc1-4d61-a37b-9f393c2e70c7.jpeg)
</div>

**Phone**
 - Hardware: iPhone 12 Pro Max
 - OS Version: iOS 16.3.1

**Loop Version**
 - Version Number: 3.2.0
 - Repo: "LoopWorkspace/main"

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet 
 - Model: Omnipod DASH  (Lot Number 144023217)
 - Firmware version: 4.10.0

**Additional context**

- After the upgrade, from the top of my head I think I disconnected/connected my iPhone to my Mac several times.

- ‼️ I use a M1 Mac running Ventura 13.2.1. 
I did not find out how to duplicate `Terminal.app` in Ventura (13.2.1), in order to tick the Rosetta checkbox.
    https://loopkit.github.io/loopdocs/build/step1/#configure-terminal-app-for-rosetta.  
Hence I used this workaround https://developer.apple.com/forums/thread/718666 .  
That is instead of duplicating `Terminal.app`, I launched my Terminal app (`iTerm.app`) then ran this command in the shell (zsh):
```shell
arch #=> arm64
env /usr/bin/arch -x86_64 /bin/zsh --login
arch #=> i386
# My understanding is that from now on, all commands run in this shell session will be interpreted by Rosetta and use i386 emulation.
```    
Then proceeded with the Build in this shell (using i386 emulation) https://loopkit.github.io/loopdocs/build/step14/#build-select-script

**Comment by ebouchut** [comment]
FYI, I found no crash log starting with "Loop" in my iPhone "Settings" / "Privacy & Security" / "Analytics & Improvements" / "Analytics Data".

**Comment by ps2** [comment]
This message can happen when iOS *kills* loop for various reasons, like during an upgrade. If the kill happens during dosing, it looks like a crash to Loop, and that's why you see the message.

**Comment by ebouchut** [comment]
@ps2 Thank you for your explanation.

**Comment by gigich** [comment]
When you build Loop with Xcode after installing on the phone it will be started. Then xcode task is still running and if you stop the task or disconnect phone Loop will close. That is normal behavior.
