### ISSUE TITLE
Loop Design Refresh & Detail Changes

### ISSUE THREAD

**Issue by mendelkaplan** [LoopKit/Loop#1966]
Hi All!

I've attached a pdf of some ideas I had to hopefully make Loop feel nicer and more intuitive.

Theres nothing groundbreaking about any of these ideas on their own, but a bunch of small things work to create one big result.

Looking for additional feedback and opinions!

[Loop-Edits.pdf](https://github.com/LoopKit/Loop/files/11040608/Loop-Edits.pdf)

![Loop Refresh](https://user-images.githubusercontent.com/55564308/226924573-b97b98bd-76c7-48e7-bb01-7f1f45fefa4b.png)

**Comment by taylorpatterson007** [comment]
Looks much better and makes more sense. Thank you!
