### ISSUE TITLE
Some Arabic numbers appear in the form of symbols

### ISSUE THREAD

**Issue by abutmim** [LoopKit/Loop#1968]
**Describe the bug**
By using the Arabic language, some numbers appear in the form of symbols, as shown in the pictures
From Insulin Delivery page (Event History)

**Screenshots**
![1](https://user-images.githubusercontent.com/40410642/227319690-01880a1d-4bdc-43e1-b03f-20e45123d801.jpg)
![2](https://user-images.githubusercontent.com/40410642/227319695-897ec36a-f5a1-4f61-88de-17c26ee89f8b.jpg)

**Phone**
 - Hardware: iPhone 11
 - OS Version:  iOS 16.3.1

**Loop Version**
 - Version Number: 3.2.1

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod Dash

**Additional context**
I think if English numbers are used in the App, the problem could be solved.

**Comment by alexyliao** [comment]
Is the issue also present under the Non-Pump Insulin tab for you? We are trying to replicate the issue but are unable to see any events logged under the Event History tab, as I believe in order for events to show under Event History, we need to log insulin doses delivered via an insulin pump (which we do not have) connected to the Loop app, is that correct?
