### ISSUE TITLE
Removing values from AH still visible in Tidepool Web UI 

### ISSUE THREAD

**Issue by dnzxy** [LoopKit/Loop#1970]
**Describe the bug**
I use Loop with the Tidepool Service Plugin enabled. Had compression low this night. Proceeded to remove 2 "wrong" values from AH blood glucose panel. Loop BG data in AH does not have any values for the specified time frame. I waited several minutes. Opened Tidepool but values were still visible. Proceeded to re-check in an incognito browser window with cleared cache, values are still there.

**Attach an Issue Report**
[Loop Report 2023-03-25 15:56:38+01:00.md](https://github.com/LoopKit/Loop/files/11069201/Loop.Report.2023-03-25.15.56.38%2B01.00.md)

**To Reproduce**
1. Go to Apple Health
2. Open Blood Glucose panel
3. Delete a / several value(s)
4. Go to Tidepool Web UI and check for these values.

**Expected behavior**
Values that are removed / not present in AH should also be removed from Tidepool. 

Pete Schwamb [wrote](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Tidepool.20Service.20Plugin/near/344500971):
```quote
Loop will upload the change to the Tidepool backend immediately (or later if you're offline), and it should be available in the database immediately after. You may need to refresh the Tidepool Web UI to see the update, after those steps.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/48965855/227725269-5c46849e-95cf-4f23-a103-c6b62cf4a5a6.png)
Numbers were removed where red line is:
![IMG_0692D612591A-1](https://user-images.githubusercontent.com/48965855/227725316-7d137902-f086-44ad-8d3b-396f22141901.jpeg)

**Phone**
 - Hardware: iPhone 11
 - OS Version: iOS 16.1

**Loop Version**
 - Version Number: 3.2.1
 - Repo: LoopKit/Loop, no patches, no customizations

**CGM**
 - Device:  Dexcom G6
 - Manager app: Dexcom App G6 mg/dl v1.9.3

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Dash
 - Firmware version: 4.10.0

**Comment by ps2** [comment]
Handling deletion/edit of glucose values is not something supported by GlucoseStore or the remote data protocols in Loop yet, so no services are able to process deletes/edits yet.  At some point it would be nice to have a UI for users to manage their glucose data more thoroughly, like removing bad data points, editing mis-entered glucometer readings, or adding glucometer readings at times other than sensor warmup. The storage and remote sync protocols would need to be tackled with this work, too.
