### ISSUE TITLE
Loop keep crashing after a pump occlusion and keep trying to give extra insulin 

### ISSUE THREAD

**Issue by skimaniac** [LoopKit/Loop#1973]
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.
My pump stop for a possible occlusion, I think when loop try to give me a bolus. 
Since that error Loop always give me an error message, even if everything is comme back to normal for the pump ( I change my canula) even loop can give me bolus, but it's crash  at every loop cycle
I try to reboot the phone, stop and restart loop. Nothing seems to work for now. 
**Attach an Issue Report**

Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.
[Export-20230401T211122Z.zip](https://github.com/LoopKit/Loop/files/11130662/Export-20230401T211122Z.zip)

[Loop Report 2023-04-01 17:28:58-04:00.md](https://github.com/LoopKit/Loop/files/11130663/Loop.Report.2023-04-01.17.28.58-04.00.md)

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [iPhone 12 Pro Max]
 - OS Version: [iOS 16.4]

**Loop Version**
 - Version Number: [3.3.0 (57)]
 - Repo: [LoopKit/Loop, dev]

**CGM**
 - Device: [Dexcom G6]
 - Manager app: [Dexcom App]

**Pump**
 - Manufacturer: [Medtronic]
 - Model: [715]
 - Firmware version: [2.3A 1.1 0B 0B]

**Additional context**

I create a report, but I don't know how to attach it from my iPhone, I will try from my computer after. 

![image](https://user-images.githubusercontent.com/44727542/229315307-6aae32c9-bd6e-4794-a297-5ee7b3643c0e.png)

**Comment by skimaniac** [comment]
and the history of bolus on loop is ok with the pump history

**Comment by skimaniac** [comment]
If I calculate my active insuline vs what Loop thing I have, I think I will have a bad evening and night :(

![IMG_5754](https://user-images.githubusercontent.com/44727542/229319655-75c6515b-7d1a-4b94-b958-1f2f4f405a02.PNG)
![IMG_5755](https://user-images.githubusercontent.com/44727542/229319657-5687a2bf-cba0-4faf-9faf-cf13b02e2203.PNG)

**Comment by skimaniac** [comment]
This is what loop think I have for insulin on board and what my pump know I have

![image](https://user-images.githubusercontent.com/44727542/229325775-0681749b-3224-4a72-9000-baf3a57766ee.jpeg)

![image](https://user-images.githubusercontent.com/44727542/229325779-b90b253f-9954-4326-9472-2f482dae5efe.jpeg)

**Comment by skimaniac** [comment]
I use the bolus assistant on my pump to calculate how much insuline I need for my meal

After I use loop to give me insuline. After the insulin delivery, loop show me 5.5 unit on board and then crash. When I restart it, it's show me no insuline on board. 

What should I do now?

![image](https://user-images.githubusercontent.com/44727542/229326590-a63023b0-1288-49aa-92d1-597cc1c99cd8.jpeg)

![image](https://user-images.githubusercontent.com/44727542/229326597-43b1cc31-f1d1-460a-a343-6779aca006c9.jpeg)

**Comment by skimaniac** [comment]
I put loop on open loop for the night because it doesn't take account of a 5 unit of bolus (it wanted to give me a 5u bolus each 5min)

This morning everything seem to came to normal. I will try to watch it more close for today.

**Comment by skimaniac** [comment]
I changed the title to better express the problem.

**Comment by SirBarksALot** [comment]
It happens when event history gets out of sync, reinstalling the app doesn't change a thing as everything is saved in Apple Health so it cannot be deleted. For me it happened when I rewinded the pump twice in a row while changing the reservoir. What worked for me was to rewind one more time, turn off Closed Loop for the day and it worked normally on the following day. Having a manual option to reset the whole app's data would be a great...

**Comment by skimaniac** [comment]
It would also be nice if the error message would be clearer and Loop wouldn't try to give the same bolus every 5 minutes.
