### ISSUE TITLE
Loop with Patches crashes 100% of the time when selecting Settings > Pump.

### ISSUE THREAD

**Issue by damienholloway** [LoopKit/Loop#1996]
**Describe the bug**
Loop with patches crashes each (100% of the ) time I select Settings>Pump icon Pic. 
I tried iPhone 14 with iOS 16.2 with same code and setup and it works well
With iPhone X on iOS 16.4, which I unintentionally let it upgrade to 16.4 :-( , it crashes 100% of the time

**Attach an Issue Report**
[Loop Report 2023-05-13 05:06:52+08:00.md](https://github.com/LoopKit/Loop/files/11467734/Loop.Report.2023-05-13.05.06.52%2B08.00.md)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Pump Icon' <- picture of my pump
3. Loop then closes (or pauses/freezes when connected to laptop and XCODE

**Expected behavior**
I Expect pump setting to open tto allow me to delete and or add a pump

**Screenshots**
![image](https://github.com/LoopKit/Loop/assets/2235166/0d11e8ff-4dcb-4137-8027-2bd56a523dd3)
![image](https://github.com/LoopKit/Loop/assets/2235166/e868444e-f077-4a9a-be7a-c3efcbf5058f)

**Phone**
 - Hardware: iPhone X
 - OS Version:  iOS 16.4 (20E247)

**Loop Version**
 - Version Number: Loop v3.2.1(57)
 - Repo: Loop with patches
   - As specified here  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/loopnlearn/LoopBuildScripts/main/BuildLoop.sh)"
   
**CGM**
 - Device: Dexcom One
 - Manager app: Dexcom One App, selected as G6 in Loop menu

**Pump**
 - Manufacturer: Medtronic
 - Model:  722
 - Firmware version: 2.4A Using Orange Link 1.x

**Additional context**
XCode Version 14.3 (14E222b)
macOS 13.3.1 (22E261)

It was fresh install after deleting previous versions of the app. So I assume there is a place where old data lives, is there a place to delete that? in case something about pump config was corrupted?
By coincidence I saw the issue while it was connected to my mac while xcode was running and it shows the following error

**Thread 1: Fatal error: Schedule incomplete**

as per screen shot below. 
![image](https://github.com/LoopKit/Loop/assets/2235166/edc4d3c1-d62c-49a7-8eca-3c343cd3ab4a)

Not sure if related. Might imply corrupt data somewhere if I knew more about it. 

Console messages from XCODE also attached as it appears to error in a circle around this message.

![image](https://github.com/LoopKit/Loop/assets/2235166/dd85eeee-4e5a-465e-920d-e7e922a1e08b)

Search of git did not raise any possibilities but again, I am not experienced with it.
Any suggestions?

**Comment by marionbarker** [comment]
I think I saw this exact error from someone using a medtronic pump. He had iAPS on his phone and got them when he tried to use Loop. Do you have another app on your phone?

I know others who use iAPS and Loop 3 on the same phone and switch back and forth, but they are using Pods.

Here's the issue that was reported and closed: 
* https://github.com/LoopKit/Loop/issues/1993
