### ISSUE TITLE
Eating soon/multiple workout modes

### ISSUE THREAD

**Issue by msrcgm** [LoopKit/Loop#200]
If there was a way to set multiple temporary targets -- like the existing workout mode -- Loop could have an effective "eating soon" mode where the temporary target was set to 80mg/dl (or some such number as the user defines).

**Comment by msrcgm** [comment]
closing because I found this was already an open issue

**Comment by ps2** [comment]
#177 is the issue covering this, for anyone else stumbling on this issue.
