### ISSUE TITLE
Not receiving data from Libre 3 via GlucoseDirect when using Insulin Pump Simulator

### ISSUE THREAD

**Issue by FokkeZB** [LoopKit/Loop#2001]
**Describe the bug**
When combining the Insulin Pump Simulator and GlucoseDirect for a Abbott FreeStyle Libre 3 sensor, data is received when Loop first opens, but not after that, causing Closed Loop to become disabled (Red Loop).

In contrast, when using an Omnipod DASH, data does continue to come in.

**Attach an Issue Report**
N/A

**To Reproduce**
Configure Loop to use the Insulin Pump Simulator and GlucoseDirect for a Abbott FreeStyle Libre 3 sensor.

**Expected behavior**
Continue to receive data and Closed Loop to work.

**Screenshots**
N/A

**Phone**
 - Hardware: iPhone SE 2022
 - OS Version: iOS 16.3.1

**Loop Version**
 - Version Number: 3.2.2
 - Repo: LoopKit/Loop

**CGM**
 - Device: Abbott FreeStyle Libre 3
 - Manager app: GlucoseDirect

**Pump**
 - Manufacturer: Insulin Pump Simulator
 - Model: N/A
 - Firmware version: N/A

**Additional context**
Looking at the code, I see GCM data is fetched when the app starts (which indeed works), but after that either the pump or the GCM seems to need to trigger it. It seems that the Insulin Pump Simulator is not triggering it, and neither is GlucoseDirect with an Abbott FreeStyle Libre 3 sensor. Apparently Omnipod DASH **is** triggering it. I'm not sure if GlucoseDirect with an Libre 3 or other supported sensor does, or whether it has the same issue. It could be a Libre 3 only problem, since that needs to poll the LibreView API for data. Either way, it might be good for the Insulin Pump Simulator to trigger readings as well, so that it does not depend on the GCM alone?

**Comment by marionbarker** [comment]
The simulator option is limited.

* https://loopkit.github.io/loopdocs/version/simulator/#what-to-expect

Loop requires something to "drive" it to wake up.

I was not aware that any iOS app could talk to a Libre 3. Perhaps thing have changed:
* https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Libre.203

**Comment by FokkeZB** [comment]
Ah, that explains it - thanks!

Yes, GlucoseDirect can work with Libre 3, by polling the undocumented LibreView API for readings: 

- https://github.com/creepymonster/GlucoseDirect#current-features
- https://github.com/creepymonster/GlucoseDirect/blob/main/App/Modules/SensorConnector/LibreConnection/LibreLinkUpConnection.swift

That has been working well for us.
