### ISSUE TITLE
Automating changes to Basals, ISF, and CR

### ISSUE THREAD

**Issue by LilMasala** [LoopKit/Loop#2010]
Hey guys. I'm new to the GitHub community. But im currently stuck on two things I am trying to do/would love help if people want to. Basically im trying to train a neural network to take apple health data as its inputs, as well as ISF, CR, and Basals, and train it on 3 outputs - %low, %high, eROC (difference between optimal rate of change and actual rate of change over a 30 min time period). then using that to optimize ISF, CR, and Basals to bring the three outputs as close to 0 as possible. But to do this, I need to be able to access a lot of apple health data - and im a little confused about where I would edit the loop code so I could add things like sleep, menstrual cycle, exercise type, intensity... in the beginning page. Also, same question about where I would edit the ISF, CR, Basals in the source code. Note that im developing another app to actual run my ML algorithm and optimize those values daily - and those values (as well as the other data) would be stored in a realm database. Thanks everyone!

**Comment by sethgagnon** [comment]
Not sure if you have seen this work:

https://github.com/scaubrey/InsuLearner

**Comment by LilMasala** [comment]
@sethgagnon I have! I think his model is really awesome, but from the looks of it, he doesn't seem to be integrating w apple health which is what I want to do. but you're right in that it would be a good place to start! That's more why I wanted help finding the exact locations of the isf/cr/basal/apple health inputs!
