### ISSUE TITLE
Issues building Loop

### ISSUE THREAD

**Issue by Texbrackdelmonte** [LoopKit/Loop#2011]
Hi All,

New to this, I have followed the instructions to the letter, consider myself technical but cant get this to build

All the steps up until Build work Identities green, certificates green

Error is
Could not find an app on App Store Connect with app_identifier: com.***.loopkit.Loop

I have gone back and created the identities again, and when I try and go to the build app page on Apple, I no longer see that 

When I go to apps store connect apps, I no longer see this bundle
com.TEAMID.loopkit.Loop
When I fist did this it worked fine, then showed me the success screen

I was just re tracing my steps, I have tried doing most of it from scratch but same error

Tearing my hair out is anyone able to assist me?

**Comment by marionbarker** [comment]
I'm sorry you are frustrated. This is your error:

https://loopkit.github.io/loopdocs/gh-actions/gh-errors/#could-not-find-an-app-on-app-store-connect

Follow the steps at that link.  

Please use conversation at zulipchat or FB for these types of questions. Issues should be used for code problem reports or feature requests - not for build help. Once you have this resolved, please close this issue.

https://loopkit.github.io/loopdocs/intro/loopdocs-how-to/#how-to-find-help

**Comment by Texbrackdelmonte** [comment]
I tried that twice, funny enough I had to restart my laptop, then the build worked, go figure, thanks, will close this off now

**Comment by marionbarker** [comment]
it's possible this was an intermittent issue at Apple. Evidently you were not the only one. I suspect the laptop restart was coincidence - but a restart is never a bad thing to try.
