### ISSUE TITLE
update loop failed

### ISSUE THREAD

**Issue by Vergultkurt** [LoopKit/Loop#2012]
Hi, my son's loop app is about to expire soon and I tried to do the update. But I ran into this problem:
Unable to create a valid authorization token for the App Store Connect API.  Verify that the FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY secrets are set correctly and try again.
I re-entered all the right credentials but no success. 
I have included error report but do not know what to do next to solve the problem
Please help or advise
thxs
kurt
<img width="1672" alt="Scherm­afbeelding 2023-06-24 om 10 27 26" src="https://github.com/LoopKit/Loop/assets/129326688/3eb22918-94e1-4c03-9278-7552adb06f02">
<img width="1663" alt="Scherm­afbeelding 2023-06-24 om 10 19 39" src="https://github.com/LoopKit/Loop/assets/129326688/b2c68c16-19f3-459a-a4cb-7d60412caa89">

**Comment by odmuc** [comment]
Please check if you have accepted the updated terms & conditions on the Apple Developer Portal. Unless you accept the terms, Apple won’t let you deploy to App Store Connect.

**Comment by Vergultkurt** [comment]
Hi, I just accepted these updated term & conditions but same error occurs
Any other tips?

**Comment by odmuc** [comment]
Sometimes it takes a few minutes to sync/update your account. So please try again (I had the same issue and this was the solution in my case).

**Comment by Vergultkurt** [comment]
Hi, it worked! Thanks to your tip, odium!

**Comment by Vergultkurt** [comment]
So when updating your 3monthly app, one should always accept most recent term & conditions from Apple developer before starting the update procedure
