### ISSUE TITLE
DASH Pump Fault Event Code 0xcb: Unknown Fault with less than 8 hours from expiration

### ISSUE THREAD

**Issue by rolandet** [LoopKit/Loop#2018]
**Describe the bug**
I experienced three 0xcb Unknown Fault errors with my DASH Pods while traveling. They all occurred when the Pod had less than 8 hours when the Pod was to expire so I am assuming that the Event code 0xcb was related to battery life in the Pod. I normally do not get more than 2.5 days of Pod life before running out of Insulin but in this case I had elevated exercise levels so the POD was lasting longer. The POD had 50+ units of insulin left in each incident.  I am not using any 3rd party apps other than Loop, such as xdrip4ios. I am attaching the Issue Report and Events from one of the incidents.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

[Export-20230624T162955Z.zip](https://github.com/LoopKit/Loop/files/11919785/Export-20230624T162955Z.zip)

[Loop Report 2023-06-24 12_30_48-04_00.md](https://github.com/LoopKit/Loop/files/11919787/Loop.Report.2023-06-24.12_30_48-04_00.md)

**To Reproduce**
Expiration of DASH Pod is less than 8 hours.

**Expected behavior**
I would not expect to receive 0xcb fault when the POD still has not expired.

**Screenshots**

**Phone**
 - Hardware: iPhone 12
 - OS Version: 16.5

**Loop Version**
## Build Details
* appNameAndVersion: Loop v3.2.2 (8)
* profileExpiration: 2023-12-29 15:16:10 +0000
* gitRevision: befcbcb
* gitBranch: N/A
* workspaceGitRevision: 35ea100
* workspaceGitBranch: main
* sourceRoot: /Users/runner/work/LoopWorkspace/LoopWorkspace/Loop
* buildDateString: Mon May  1 01:38:10 UTC 2023
* xcodeVersion: 14B47b

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: DASH
 - Firmware version: TWI Board FW: 4.10.0 BLE FW: 1.4.0

**Additional context**

**Comment by rolandet** [comment]
I had two more 0xcb: Unknown Fault failures since I opened this issue report. One at 7 hours and the other at 9 hours until expiration. I've attached the Loop Report and Critical Events for the 9 hour failure. Did anyone look at the previous logs?

A side question, is there a way to easy way track all the communication events for a Pod? I suspect that Loop is just wearing down the battery on the DASH Pod and would like to track the number and type of comm events.

[Export-20230708T151008Z.zip](https://github.com/LoopKit/Loop/files/11991449/Export-20230708T151008Z.zip)
[Loop Report 2023-07-08 11_09_25-04_00.md](https://github.com/LoopKit/Loop/files/11991450/Loop.Report.2023-07-08.11_09_25-04_00.md)

**Comment by NickyJoel** [comment]
There are a couple of treads on here with this error code and it does seem to be battery life related. The other threads have numerous tips but the one that has helped me from every pod having this error tot now only one in every 3 to 4 pods is widening your target bg. Instead of having one number create a range. This reduces the amount of commands and should extend battery life.

**Comment by rolandet** [comment]
@NickyJoel I feel my range (100-115) is already wide enough and shouldn't need to be widened even further.  I think some comms optimization is needed with the DASH module to reduce battery drain. I do not see this issue with the DASH pods with the Omni DASH PDM when I test with that. I believe the only person who could even remotely address this would be @ps2. If he had the time.

**Comment by marionbarker** [comment]
I downloaded and parsed your two reports. (Been busy).
The battery load is one theory but it seems to be only for some pods. 
Many people do not experience these faults with similar communication (and insulin delivery) load.

One thing I track when I parse the Loop Report is the average number of messages exchanged between Loop and Pod. Values under 60/hour seem "fine" for most pods (but that isn't a hard dividing line.)
* Your reports show about 53 messages / hour.

Your two reports contain 3 0xCB pod faults at 69.1, 63.4 and 62.1 hours.

I understand how frustrating this can be. Your reports are valuable and we appreciate you posting them.

BTW - you posted 2 reports in March 2022 using DASH that indicated one 0x40 fault (probably low-battery).
* The pod that had the fault had average of 67 messages / hour

**Comment by rolandet** [comment]
@marionbarker Thanks for looking at the logs and doing a deep dive. I also wanted to note that I do use the Auto-bolus feature which I’m sure drives additional battery usage. 

Outside of perhaps optimizing the DASH communications driver I’m wondering if it would make sense to have a low power mode slide button feature where we could make Loop perform less communication exchanges. Similar to the low power mode on iOS. Perhaps have it Loop every 10 minutes or something along those lines. I’m just thinking of ways to save the power on the three day.

**Comment by rolandet** [comment]
I'm am still seeing the 0xcb errors from time to time.
