### ISSUE TITLE
Export Critical Event Log Incomplete with dev

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#2020]
**Describe the bug**
When using the Export Critical Event Log under Loop, Settings, Support, and airdropping to my Mac, the report is incomplete with dev. Building main on the same phone, and repeating the steps, I get a different but still incomplete log.

**Attach an Issue Report**
I will attach event logs in the next comment

**To Reproduce**
Symptoms - the export takes the a long time, but most (or all days) are empty json files.

**Expected behavior**
A full 7 days of events should be included in the exported zip.

**Phone**
 - This happens on my "real" phone 11 pro (running dev), iOS 16.5.1
 - This happens on my "test" phone 8, running iOS 16.5.1

**Loop Version**
 - dev, commit d47da45 on "real" phone
 - dev, commit 3602b80 and main, commit ee50fc4 on "test" phone 8 
    - I have been going back and forth between dev and main on this phone and running a bunch of tests
    - There is data for every day
    - The last time (before today) that I built main onto the test phone as 30-June-2023

**CGM**
 - Dexcom G6 - real phone
 - Nightscout as CGM - test phone

**Pump**
 - DASH - real phone
 - Simulated pump - test phone

**Pump**
  - What gets transferred?
  - When running dev on my real phone, only empty json files
  - When running dev on the 8, only information from 20230630
    - I checked my records and that is the last day I was running tests using main
  - When running main on the 8, only information from today and 20230630
  
 
```
marion@MarionMac Downloads % ls -l iPhone*
-rw-r--r--@ 1 marion  staff     6168 Jul  6 08:19 iPhone11pro_real_running_dev_Export-20230706T151934Z.zip
-rw-r--r--@ 1 marion  staff  1038515 Jul  6 07:58 iPhone8_running_dev_Export-20230706T145800Z.zip
-rw-r--r--@ 1 marion  staff  2652754 Jul  6 08:03 iPhone8_running_main_Export-20230706T150315Z.zip

iPhone11pro_real_running_dev_Export-20230706T151934Z:
total 56
-rw-r--r--@ 1 marion  staff  762 Jul  6  2023 20230630T000000Z.zip
-rw-r--r--@ 1 marion  staff  762 Jul  6  2023 20230701T000000Z.zip
-rw-r--r--@ 1 marion  staff  762 Jul  6  2023 20230702T000000Z.zip
-rw-r--r--@ 1 marion  staff  762 Jul  6  2023 20230703T000000Z.zip
-rw-r--r--@ 1 marion  staff  762 Jul  6  2023 20230704T000000Z.zip
-rw-r--r--@ 1 marion  staff  762 Jul  6  2023 20230705T000000Z.zip
-rw-r--r--@ 1 marion  staff  762 Jul  6  2023 20230706T151934Z.zip

iPhone8_running_dev_Export-20230706T145800Z:
total 2072
-rw-r--r--@ 1 marion  staff  1033109 Jul  6  2023 20230630T000000Z.zip
-rw-r--r--@ 1 marion  staff      762 Jul  6  2023 20230701T000000Z.zip
-rw-r--r--@ 1 marion  staff      762 Jul  6  2023 20230702T000000Z.zip
-rw-r--r--@ 1 marion  staff      762 Jul  6  2023 20230703T000000Z.zip
-rw-r--r--@ 1 marion  staff      762 Jul  6  2023 20230704T000000Z.zip
-rw-r--r--@ 1 marion  staff      762 Jul  6  2023 20230705T000000Z.zip
-rw-r--r--@ 1 marion  staff      762 Jul  6  2023 20230706T145800Z.zip

iPhone8_running_main_Export-20230706T150315Z:
total 5480
-rw-rw-r--@ 1 marion  staff  1033109 Aug  6  2023 20230630T000000Z.zip
-rw-rw-r--@ 1 marion  staff      762 Aug  6  2023 20230701T000000Z.zip
-rw-rw-r--@ 1 marion  staff      762 Aug  6  2023 20230702T000000Z.zip
-rw-rw-r--@ 1 marion  staff      762 Aug  6  2023 20230703T000000Z.zip
-rw-rw-r--@ 1 marion  staff      762 Aug  6  2023 20230704T000000Z.zip
-rw-rw-r--@ 1 marion  staff      762 Aug  6  2023 20230705T000000Z.zip
-rw-rw-r--@ 1 marion  staff  1745466 Aug  6  2023 20230706T150315Z.zip
```

**Comment by marionbarker** [comment]
Event logs from iPhone 11 pro (real phone) running dev and iPhone 8 (test phone) running dev and main and Loop Report for test phone after building back dev after switch to main. (No change in behavior for event log following rebuild.)

[iPhone8_running_dev_Export-20230706T145800Z.zip](https://github.com/LoopKit/Loop/files/11970039/iPhone8_running_dev_Export-20230706T145800Z.zip)
[iPhone8_running_main_Export-20230706T150315Z.zip](https://github.com/LoopKit/Loop/files/11970040/iPhone8_running_main_Export-20230706T150315Z.zip)
[iPhone11pro_real_running_dev_Export-20230706T151934Z.zip](https://github.com/LoopKit/Loop/files/11970042/iPhone11pro_real_running_dev_Export-20230706T151934Z.zip)
[iPhone8_running_dev_Loop Report 2023-07-06 08:38:36-07:00.md](https://github.com/LoopKit/Loop/files/11970049/iPhone8_running_dev_Loop.Report.2023-07-06.08.38.36-07.00.md)

**Comment by ps2** [comment]
Found a bug with some changes I made to the ZipFoundation library. `dev` has an update for this now.

**Comment by marionbarker** [comment]
Please see post in zulipchat.
Do you want me to open a separate issue?
