### ISSUE TITLE
Tidepool Service stopped sending Glucose and later Carbs as well

### ISSUE THREAD

**Issue by FokkeZB** [LoopKit/Loop#2021]
**Describe the bug**

From when we started using Loop at version v3.2.2 (still the current `main`) we also used the newly (in v3.2.0) added Tidepool Service.

This worked fine initially, but at some point it stopped sending Glucose data. We addressed this by manually uploading Glucose from LibreView (we use FSL3).

However, since a few days it now stopped sending Carbs as well, which we cannot backfill from another source.

**Attach an Issue Report**

[Loop Report 2023-07-06 22:13:05+02:00.md](https://github.com/LoopKit/Loop/files/11971902/Loop.Report.2023-07-06.22.13.05%2B02.00.md)

**To Reproduce**

1. Install Loop v3.2.2
2. Wait for weeks/days

**Expected behavior**

Continued Glucose and Carbs data in Tidepool.

**Screenshots**

N/A

**Phone**
 - Hardware: iPhone SE 2022
 - OS Version: iOS 16.5.1

**Loop Version**
 - Version Number: v3.2.2 (57)
 - Repo: LoopKit/Loop

**CGM**
 - Device: Abbott FreeStyle Libre 3
 - Manager app: Abbott FreeStyle Libre 3

**Pump**
 - Manufacturer: Omnipod
 - Model: 4
 - Firmware version: N/A

**Additional context**
N/A

**Comment by ps2** [comment]
You might try removing the service and re-adding it.

**Comment by FokkeZB** [comment]
@ps2 that restored carbs, but not glucose.

**Comment by ps2** [comment]
Make sure your cgm has upload readings turned on.

**Comment by FokkeZB** [comment]
@ps2 I don’t see such a setting. We use Glucose Direct with FreeStyle Libre 3

**Comment by ps2** [comment]
I'm not familiar with that setup; it's not part of standard Loop. How are you getting data from Glucose Direct into Loop?

**Comment by FokkeZB** [comment]
Using https://github.com/creepymonster/GlucoseDirectClient which is included in the patched version provided by the customization script at https://www.loopandlearn.org/build-select/

**Comment by ps2** [comment]
So that client hasn't been submitted as a PR to Loop yet, that I'm aware of. We *are* working on including a Libre option in Loop as a standard part, but it does not support Libre 3 yet. I assume that GlucoseDirectClient is only supporting Libre 3 by a web download? I.e. you need to be online to be able to receive glucose values from your local sensor?

Anyways, I'm guessing that somehow the GlucoseDirectClient is telling Loop not to send its BG values to other services. I'd look for some option in its UI to switch this flag. Maybe @creepymonster can help.

**Comment by FokkeZB** [comment]
@ps2 you seem to be right:

https://github.com/creepymonster/GlucoseDirectClient/blob/a92cb50518d23400e5bc584c71b46862445f0c15/GlucoseDirectClient/GlucoseDirectManager.swift#L202

I'll give that a try. Thanks for the hint!

**Comment by FokkeZB** [comment]
@creepymonster I ended up changing the line at https://github.com/creepymonster/GlucoseDirectClient/blob/a92cb50518d23400e5bc584c71b46862445f0c15/GlucoseDirectClient/GlucoseDirectManager.swift#L25

```swift
        shouldSyncToRemoteService = true // rawState[Config.shouldSyncKey] as? Bool ?? false
```

As I had no idea where to change the values of `Config`.
