### ISSUE TITLE
This seems to be an iPhone 6s problem. NS as a CGM works fine on two of my test phones: models SE and 8; but will not work on my 6s. True for main and dev branches.

### ISSUE THREAD

**Issue by henrycoding** [LoopKit/Loop#2022]
No, it seems that this problem is related to the version of iOS.

iPhone X with iOS 15 has the same issue, but when it upgrades to iOS16, the problem has disappeared.

              This seems to be an iPhone 6s problem. NS as a CGM works fine on two of my test phones: models SE and 8; but will not work on my 6s. True for main and dev branches. 

The 6s can only go to iOS 15. My other test phones are running iOS 16.

_Originally posted by @marionbarker in https://github.com/LoopKit/Loop/issues/1898#issuecomment-1627614321_

**Comment by marionbarker** [comment]
@henrycoding Please close this issue. Only one issue is needed.

**Comment by Willbumster** [comment]
Hi
iPhone 6 seems really old, perhaps consider an obsolescence threshold to maximize efficiency?
Ron

Sent from my iPhone

On Jul 9, 2023, at 11:50 AM, Marion Barker ***@***.***> wrote:

﻿

@henrycoding<https://github.com/henrycoding> Please close this issue. Only one issue is needed.
