### ISSUE TITLE
Critical pod error 0xcb

### ISSUE THREAD

**Issue by ElenaFlores25** [LoopKit/Loop#2029]
**Describe the bug**

We are having continual critical pod errors 0xcb.  This usually occurs on day 3 but had a few on day 2, it does not always happen whilst delivering a bolus either, often no bolus is being delivered.  Today was day 2 and was not delivering a bolus.  Have been on dash almost 2 years and only looping since April with Dexcom g6.  When we started looping we only had this a few times but lately it is every pod for I think the last 5 or 6.  I have checked and so far this issue has occurred with at least 3 different boxes/batches of pods (possibly more but I didn't keep record early on when we only had a few).  Since it happening every pod I have kept track of batches.

![IMG_0526](https://github.com/LoopKit/Loop/assets/95002192/c2900b39-2ad0-4e36-a385-65f237f3ad35)

**Attach an Issue Report**
[Loop Report 2023-07-13 21_23_34+10_00.md](https://github.com/LoopKit/Loop/files/12105367/Loop.Report.2023-07-13.21_23_34%2B10_00.md)
[Loop Report 2023-07-20 20_38_14+10_00.md](https://github.com/LoopKit/Loop/files/12105368/Loop.Report.2023-07-20.20_38_14%2B10_00.md)

**To Reproduce**
The pods just scream before expiry and we have no choice but to replace 

**Expected behavior**

we would really like to not have pods scream early and would hope they would last the full 3 days like before looping 

**Phone**
 - Hardware: iPhone 12
 - OS Version: IOS 16.5

**Loop Version**
 - Version Number: 3.2.2
 - Repo: [LoopKit

**CGM**
 - Dexcom G6]
 - Dexcom App

**Pump**
 omnipod dash 
 
**Additional context**

**Comment by ElenaFlores25** [comment]
[Loop Report 2023-07-20 20_38_14+10_00.md](https://github.com/LoopKit/Loop/files/12105361/Loop.Report.2023-07-20.20_38_14%2B10_00.md)
[Loop Report 2023-07-13 21_23_34+10_00.md](https://github.com/LoopKit/Loop/files/12105362/Loop.Report.2023-07-13.21_23_34%2B10_00.md)

**Comment by marionbarker** [comment]
I looked at your pod reports. (One was the same as from out FB / Messenger exchange.)
The times to failure (in hours) was 65.9, 65.4, 66.8 and 53.8.
All were 0xCB faults.
We are not sure what those faults mean.

**Comment by ElenaFlores25** [comment]
> I looked at your pod reports. (One was the same as from out FB / Messenger exchange.)
> The times to failure (in hours) was 65.9, 65.4, 66.8 and 53.8.
> All were 0xCB faults.
> We are not sure what those faults mean.

Thanks Marion.  We are still having the issues.  We actually had 2 that lasted the full time but again yesterday another failure.  I’ve seen a few people posting with the issue so hopefully someone will figure out what is happening over time.
