### ISSUE TITLE
Loop Customization Select Script during installation

### ISSUE THREAD

**Issue by mikemazurkiewicz** [LoopKit/Loop#2033]
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.
I am expecting to see the ability to change the destination directory for the code to be downloaded into.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.
n/a

**To Reproduce**
Open Terminal.
Paste /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/loopandlearn/lnl-scripts/main/BuildSelectScript.sh)"
Select option 4.
Produces error: "No folder containing Loopworkspace found in" & "Failed to execute CustomizationSelect.sh"

**Expected behavior**
Ability to change destination directory.

**Screenshots**
<img width="697" alt="image" src="https://github.com/LoopKit/Loop/assets/24593892/1ca4fb01-3e84-4d5d-aee1-9e010dd2ea94">

**Phone**
 - Hardware: 2017 iMac 5K
 - OS Version: 13.4.1

**Loop Version**
 - Version Number: n/a
 - Repo: LoopKit/Loop
 
**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by bjorkert** [comment]
Hi, thanks for creating this issue. However, the customizations are not a part of official loop. Please create the issue here:
https://github.com/loopandlearn/lnl-scripts

**Comment by mikemazurkiewicz** [comment]
Sorry about that.
