### ISSUE TITLE
Can't choose Nightscout CGM source in Loop 3.2.2

### ISSUE THREAD

**Issue by diabeticp** [LoopKit/Loop#2035]
**Describe the bug**
I'm using Guardian Connect as CGM. It uploads BG to CareLink and Nightscout imports data from CareLink. After pump setup, I've tapped "Add CGM" and chose "Nightscout Remote CGM" and... Nothing happened. I can choose any other CGM source, but not Nightscout.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket. 

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Add CGM'
3. Select 'Nightscout Remote CGM"
4. See error (Nothing)

**Expected behavior**
Adding Nightscout Remote CGM and receive data

**Screenshots**
I'll try to add screen recording.

https://github.com/LoopKit/Loop/assets/81512138/0aec4eed-f75a-48de-890e-8a270478ca91

**Phone**
 - Hardware: iPhone 12 Mini
 - OS Version: iOS 15.3.1

**Loop Version**
 - Version Number: 3.2.2
 - Repo: LoopKit/Loop

**CGM**
 - Device: Guardian Connect
 - Manager app: Nightscout

**Pump**
 - Manufacturer: Medtronic
 - Model: 715 and 754 (both WW)
 - Firmware version: 715 (3.1E) and 754 (2.6A 1.1 0B 0B)

**Additional context**

**Comment by marionbarker** [comment]
This is an iOS 15 problem. There may be a way to modify the code (I don’t know). 

If you update your phone to iOS 16, it will work.

**Comment by diabeticp** [comment]
> This is an iOS 15 problem. There may be a way to modify the code (I don’t know). 
> 
> 
> 
> If you update your phone to iOS 16, it will work. 

It works on previous versions of Loop (like Loop 2.2) on the same phone with same iOS version. I don't think it's iOS related bug.

**Comment by rteague-dr** [comment]
Putting aside whether it's an iOS related bug or not, from a security posture you should always be keeping your iPhone updated with the latest version that contains the latest security fixes.

**Comment by diabeticp** [comment]
> Putting aside whether it's an iOS related bug or not, from a security posture you should always be keeping your iPhone updated with the latest version that contains the latest security fixes.

I have my own benefits sitting on older version of iOS. It's my decision to update iOS or not. 
If it's working on previous versions of iOS, then it's not iOS related bug. It's Loop bug.

**Comment by marionbarker** [comment]
My wording was imprecise. This Loop bug can be fixed by updating to iOS 16. If you want to stay on iOS 15, you can build dev. Or dig through the dev commits to find where it was fixed and make a similar change.

**Comment by marionbarker** [comment]
Please close this issue - it is already listed as Issue #1898
