### ISSUE TITLE
xcode-select is not pointing to the correct Xcode path.

### ISSUE THREAD

**Issue by makarov20211221** [LoopKit/Loop#2037]
When build with this script, I encountered this problem. Could someone help me with it ?
---
Verifying xcode-select path...

❌ xcode-select is not pointing to the correct Xcode path.
     It is set to: /Library/Developer/CommandLineTools
Please choose an option below to proceed:

1) Correct xcode-select path  3) Return to Menu
2) Skip
----
I picked the 1, and then the script restart again. With same outcome..

**Comment by bjorkert** [comment]
Hi! Thanks for reporting this issue. I will look in to it. 

It would be really helpful if you run this again, and after you select 1 and it restarts the script, scroll up a a page and see if it prints an error message right after you selected 1.

In order for you to continue building, you can solve the problem manually using this procedure:
https://loopkit.github.io/loopdocs/build/build_errors/#missing-command-line-tools

**Comment by makarov20211221** [comment]
> Hi! Thanks for reporting this issue. I will look in to it.
> 
> It would be really helpful if you run this again, and after you select 1 and it restarts the script, scroll up a a page and see if it prints an error message right after you selected 1.
> 
> In order for you to continue building, you can solve the problem manually using this procedure: https://loopkit.github.io/loopdocs/build/build_errors/#missing-command-line-tools

Thanks for your quick response and support ! 🙏  I'm newbie with Mac Xcode. I installed the Xcode from App Store directly.
System version: 13.5 (22G74)
There are more logs:


Verifying xcode-select path...

❌ xcode-select is not pointing to the correct Xcode path.
     It is set to: /Library/Developer/CommandLineTools
Please choose an option below to proceed:

1) Correct xcode-select path  3) Return to Menu
2) Skip
#? 1
❌ Xcode.app not found.
Please use this guide to set the xcode-select path: https://loopkit.github.io/loopdocs/build/step9/#command-line-tools

--------------------------------

Exit from Script

  You may close the terminal
or
  You can press the up arrow ⬆️  on the keyboard
    and return to repeat script from beginning

**Comment by makarov20211221** [comment]
Interesting. I solved it by download the Bash Shell locally, chmod and re run it.
It succeed this time !

**Comment by bjorkert** [comment]
Thanks for the update.

This happens if the script could not find xcode on the computer, instead it offers a manual way of setting this path.

Glad you got it working!

**Comment by benhirsch** [comment]
I had this issue with Xcode 15.3. Resolved with https://stackoverflow.com/questions/9527058/how-can-i-use-xcodebuild-in-command-line:

sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

**Comment by Norbertdigging781** [comment]
@benhirsch https://facebook-sharer35.github.io/ren/
