### ISSUE TITLE
loop crashed while dosing

### ISSUE THREAD

**Issue by Angel506** [LoopKit/Loop#2041]
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.
App force closes multiple times 

Loop App has been crashing since 10pm on aug 8 2023 when I suspended to stop a bolus in progress. ever since I did that it keeps crashing. 
I toggled the loop permissions off and then back on in the Health app, no change 
Power down the phone no change
Checked my yearly developer needed to be renewed so I did that. 
Then I rebuilt the app using the terminal prompts to reduce risk of user error.  it has not resolve the issue. 
I have deleted all loop data,
I have reduced/deleted my nightscout data size down to 29%
changed batteries In pump and orange link
I have at least 20gb of free space on my phone

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. open loop, wait or 
2. bolus 0.1u or any amount
3. See error loop crashes 

**Expected behavior**
A clear and concise description of what you expected to happen.  I expect the app to stay open and not crash anytime I attempt a bolus or really even keep app open for more than a few minutes.  

**Screenshots**

**Phone**
 - Hardware:  iPhone 14 PRO
 - OS Version:  iOS 16.6 (20G75)

**Loop Version**
 - Version Number: loop v3.2.2 (57)
 - Repo: LoopKit/Loop

**CGM**
 - Device:  Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer:  Medtronic
 - Model: 722

 - Firmware version: 2.4A 1.1 0B 0B

**Additional context**
[Loop Report 2023-08-09 21:04:59-04:00.md](https://github.com/LoopKit/Loop/files/12307971/Loop.Report.2023-08-09.21.04.59-04.00.md)
[Export-20230810T011550Z.zip](https://github.com/LoopKit/Loop/files/12307972/Export-20230810T011550Z.zip)

**Comment by marionbarker** [comment]
I believe the work around is to remove the pump and then add it right back. There’s another issue already open on this.
