### ISSUE TITLE
Pump simulator not possible to delete or replace

### ISSUE THREAD

**Issue by figgelus** [LoopKit/Loop#2045]
When having setup pump simulator it is not possible to delete or replace the pump. This is with new design on simulator pump. Loop with RC 2.0.

Reproduce:

Add simulator pump, try to remove or replace pump. Comes to page "Nothing here to see"

**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by marionbarker** [comment]
When running dev branch, please follow zulipchat and monitor LoopDocs for updated information. 

https://loopkit.github.io/loopdocs/version/development/#simulators-for-pump-and-cgm
