### ISSUE TITLE
Display of mmol/L in predicated glucose

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#205]
The scale on the display, even after a while, is far too large.  Should reflect range of values or somewhere around there
![image](https://cloud.githubusercontent.com/assets/855156/19014508/af602a8a-87bc-11e6-9d66-8200f5b8c3fc.png)

**Comment by loudnate** [comment]
Please try this again in the dev branch.

**Comment by beached** [comment]
Looks good in dev, I guess that is 13.1.  I didn't see too many changes there, probably shouldn't have issues?

**Comment by beached** [comment]
Ooh ooh, there is a typo.  Retrospective Correction 30 mim not 30 min
