### ISSUE TITLE
Orange Link + MySentry

### ISSUE THREAD

**Issue by marcusfpereira** [LoopKit/Loop#2055]
**Is your feature request related to a problem? Please describe.**
When using a pump with mySentry feature and an Orange Link device there is a lot of Signal Loss and red loop.
The solution is to disable 'Use mySentry' on the device settings.
But I use both Minimed 754 and Ominipod pumps, rotating pumps every week.
When switching betwwin Ominpod and Minimed the mysentry setting turn on again.

**Describe the solution you'd like**
The best case would be Loop detecting it is an Orange Link and then setting mySentry default to false.

**Describe alternatives you've considered**
A second solution would be that mySentry settings not being returned to default True after switching from Mimined to Ominipod. Loop could remember the previous mySentry setting.

**Comment by diabeticp** [comment]
Same here. Recently I got 754WW with 2.6A firmware. I had a lot of signal loss before I turned off MySentry. With MySentry off, everything works kinda well (I still have a random errors, but I think it's more OrangeLink related isssue).
