### ISSUE TITLE
Widget iOS17

### ISSUE THREAD

**Issue by mtobler** [LoopKit/Loop#2070]
**Describe the bug**
Widget doesn't work

**Attach an Issue Report**

**To Reproduce**
Install widget

**Screenshots**
![image](https://github.com/LoopKit/Loop/assets/36859517/0e34deca-350c-4d6c-ae7c-2c0d41fe449e)

**Phone**
 - Hardware: iPhone 14 Pro Max
 - OS Version: iOS 17.0

**Loop Version**
 - Version Number: 3.2.3
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnippd
-  Model: Dash
 - Firmware version: 

**Additional context**

**Comment by tanabay27** [comment]
Hello, i have the same problem with IOS 17.0.1 and iPhone 14 Pro
