### ISSUE TITLE
CGM simulator not working in background?

### ISSUE THREAD

**Issue by sarusso** [LoopKit/Loop#2075]
**Description**
It seems like the the CGM simulator is not working in background. I am seeing missing data points on the Loop app chart and I keep getting "Loop Failure - Loop has not completed successfully in X minutes/hours" notifications. I am not sure if this is a bug, however as a very first approach to the Loop app I would expect to add simulator and see everything working. If this is a technical limitation which applies only to the simulator, then maybe just adding a note would be enough.

**Issue Report**
[Loop Report 2023-09-26 12:31:28+02:00.md](https://github.com/LoopKit/Loop/files/12726520/Loop.Report.2023-09-26.12.31.28%2B02.00.md)

**To Reproduce**
1. Build and install Loop v3.2.3
2. Add a CGM simulator with a sine wave (120 +-50 mg/dl, 5 mins frequency)
3. Add a pump simulator (using default values)
4. Switch away from the Loop app (i.e. do something else with the phone)
5. Either get back on the Loop app after more than 5 minutes and see the missing data points, or wait fo the "Loop Failure" notifications.

**Expected behavior**
No missing data points nor "Loop Failure" notifications

**Phone**
 - Hardware: iPhone 13 Mini
 - OS Version:  iOS 16.6

**Loop Version**
 - Version Number: v3.2.3
 - Repo: LoopKit/Loop (LoopWorkspace repo 279e6c5)

**CGM**
 - N.A. (using the simulator)

**Pump**
 - N.A. (using the simulator)

**Comment by marionbarker** [comment]
The simulator is designed for developers to perform tests. It requires the phone to be unlocked with the app in the foreground. 

There has to be something with a heartbeat (real pump or real CGM) to wake Loop up when phone is locked.

**Comment by sarusso** [comment]
Thank you, I suspected something like that. Maybe we could add a note on the simulator?

Also, does the same apply for Nightscout-based remote CGMs given that they are not "real"?

**Comment by ps2** [comment]
Yes, it does apply for Nightscout remote cgm as well. Any non-bluetooth CGM source in Loop means that the CGM will not provide a heartbeat for Loop.  Some pumps, like most omnipods, or RileyLink-based pumps, can provide a heart beat.  The pump simulator cannot provide a heartbeat.

**Comment by sarusso** [comment]
Ok, now it's clear. Thank you very much for the explanation!
