### ISSUE TITLE
Spurious Override Warning in Add Carb Entry screen

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#2077]
**Describe the bug**
There is an intermittent issue in which the Add Carb Entry screen reports that an override is running when in fact none is running.

**Attach an Issue Report**
N/A

**To Reproduce**
I have been using Favorite Foods on my real phone since it was introduced.
* The "bug" listed above used to happen frequently
   * https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Favorite.20Foods.20Feature/near/385594989
* There was a "fix" made and now it is intermittent.
   * https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Favorite.20Foods.20Feature/near/387528883
   * Later I got one again: https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Favorite.20Foods.20Feature/near/389944430 and I thought I saved the Loop Report, I'll see if I can find it and add it to this issue
   * I will definitely save the next one (got one last night)
* I see it about once a week.
* To resolve, I start an override, cancel the override and enter the carb entry screen again.

**Expected behavior**
If an override is not running, there should not be a warning message about an override when I enter the Add Carb Entry screen.

**Screenshots**
The screen displayed is same as in [LoopDocs section: Override Active Warning](#https://loopkit.github.io/loopdocs/operation/features/carbs/#override-active-warning)

**Phone**
 - Hardware: iPhone 11 Pro
 - OS Version: 16.7

**Loop Version**
 - Commit bfd8db4 of Loop-dev

**Comment by marionbarker** [comment]
I’m not sure this is fixed. But I also don’t remember seeing it for a while.

**Comment by ps2** [comment]
Did you perhaps previously see it happen when you had missed meal notifications enabled?

If we can't reproduce this, then I'm going to take it off the 3.4 list.

**Comment by marionbarker** [comment]
I do have missed meal notifications enabled. I have not seen this issue since (before)  I last posted a comment.
