### ISSUE TITLE
watchOS (10.x) UI issue

### ISSUE THREAD

**Issue by mamckim** [LoopKit/Loop#2082]
**Describe the bug**
The Loop watch app is wrapping the label text "Loop" below the time on my Series 7 (45mm) watch running watchOS 10.1 (beta 1). I noticed the wrapping after moving to branch c15bf6cc97d65df2a9f5957ae3996d4408bdfce0 of Dev, I think.

**Attach an Issue Report**
N/A

**To Reproduce**
1. Launch the loop app/complication on watchOS
2. The label 'Loop' appears incorrectly under the time on the watch.

**Expected behavior**
I believe the 'Loop' label was on the same "line" as the time, but on the left side. 

**Screenshots**
[https://loop.zulipchat.com/user_uploads/8196/sEI6XKjmFEUtQV-1tsHRKRF4/IMG_5986.jpeg](url)

**Phone**
 - Hardware: Series 7
 - OS Version: watchOS 10.1

**Loop Version**
 - Version Number: 3.3.0 (31)
 - Repo: LoopWorkspace/Dev

**CGM**
 - Device: Dexcom G7
 - Manager app: Dexcom App, 

**Pump**
 - Manufacturer: OmniPod
 - Model: Dash
 - Firmware version: 

**Additional context**
I noticed the wrapping after moving to branch c15bf6cc97d65df2a9f5957ae3996d4408bdfce0 of Dev, I think.

**Comment by cachrisman** [comment]
I see this behavior with Loop main v3.2.3 (57). I just updated to WatchOS 10.1 yesterday and also rebuilt and reinstalled Loop.

**Comment by robertdj20** [comment]
This seems to be a WatchOS 10 thing, seeing that multiple people mention it on SO. And without a quick fix apparently. 

https://stackoverflow.com/questions/77221982/wkinterfacecontroller-title-alignment-change-on-watchos-10
https://stackoverflow.com/questions/76993773/watchos-10-beta-wkinterfacecontroller-title-alignment

If I look at some of the default watch apps from Apple (like the Settings app), they also seem to wrap their title below the time.

**Comment by marionbarker** [comment]
Bump

**Comment by Trpl7ca** [comment]
Bump

**Comment by A9qx** [comment]
Bump, still happening on watch OS 10.4 on Apple Watch S9.

**Comment by elnjensen** [comment]
I can confirm that a workaround for this is to remove the title ("Loop") from the two controllers (one with the control buttons and one displaying the graph).   For me, this is preferable to everything getting pushed down.

**Comment by elnjensen** [comment]
Possibly-relevant comment [here](https://forums.developer.apple.com/forums/thread/736472):  "There seems to be no way to put the title back into top-left corner when compiling with watchOS 10SDK. ... I believe they moved the title to where it is now because in watchOS 10 you can (in SwiftUI only) have a layout that has a button in the top-left corner."
