### ISSUE TITLE
G7 Future glucose sample dates. 

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#2083]
It looks like Loop can receive backfill from previous sensors after the new sensor is paired. These backfill messages are parsed with respect to the new sensor's start time, causing future glucose readings.

Loop v3.2.3 (5)
Dexcom G7

logs: https://gist.github.com/ps2/cb8d6db92fe07f1fd64d6110f24138cd

**Comment by marionbarker** [comment]
Link to start of original zulipchat conversation added for reference.

* https://loop.zulipchat.com/#narrow/stream/148543-Loop/topic/Dexcom.20G7/near/396306789

**Comment by marionbarker** [comment]
Is it possible to add to whatever the fix is for G7? I am thinking a more general response where Loop alerts the user that future glucose was identified and asks the user if they wish to delete the value?
