### ISSUE TITLE
Dev Feature - upload sensor start reported as future date

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#2087]
**Describe the bug**
Sometime in the recent past, the sensor start upload to Nightscout was uploaded with a future start.

**Attach an Issue Report**
see attached zip file with Loop Report and Critical logs zipped togerher.

**Expected behavior**
The Nightscout CGM Sensor Start should be correct.

**Screenshots**
Future dates were showing in Nightscout - once deleted the SAGE is correctly displayed,
![IMG_6073](https://github.com/LoopKit/Loop/assets/19607791/901258bd-bfa9-4fc6-a740-db41f053d796)

**Phone**
 - Hardware: iPhone 11 pro
 - OS Version: 16.7

**Loop Version**
 - Version Number: 3.3.0, commit 9a3666d
 - Repo: LoopKit/LoopWorkspace
 - Dexcom G6 CGM
 - DASH pod

[03-sensor-start-in-future-treatment-from-loop.zip](https://github.com/LoopKit/Loop/files/12919652/03-sensor-start-in-future-treatment-from-loop.zip)

**Additional context**
Several others have posted this happened to them and they had future treatments in Nightscout.

**Comment by marionbarker** [comment]
I have had several sensors starts since I opened this without future dates. I have not seen recent complaints, so I will close the issue.

**Comment by marionbarker** [comment]
Oops - I should have looked more closely. My last sensor change also had future dates. I had to delete those for the SAGE display to work correctly.

![future-dates-for-sage](https://github.com/LoopKit/Loop/assets/19607791/c72ffdf4-ef40-4df8-b20d-57a5827d280b)

**Comment by woodduckie** [comment]
Same here

![image](https://github.com/LoopKit/Loop/assets/11234584/1f64727b-bdde-46c9-ad82-aaa2cd71f34b)

Actual date of sensor start was 23-Nov 2023.
![image](https://github.com/LoopKit/Loop/assets/11234584/ad844dbd-beba-40b4-85b9-c15b6e12b03c)

I've updated both Loop dev to 3.3.0 & Nightscout to 15.0.2.  Unfortunately, I haven't been able to determine which is driving...

**Comment by marionbarker** [comment]
When you delete future entries in Nightscout under Admin tools, SAGE shows up again. This happens for every G6 for which I paid attention since this feature was added to dev. I’m not sure the dev version for SAGE ever worked. 

I’m using a G7 right now. That sensor start was fine, so I think it’s just G6.

**Comment by woodduckie** [comment]
G6 only here. 

Same behavior as Marion describes here. When future entry is deleted via admin tools in nightscout, the correct entry is retained and nightscout displays as expected.

**Comment by marionbarker** [comment]
Bump

**Comment by ktomy** [comment]
Same behavior for G6 here

**Comment by marionbarker** [comment]
Bump

**Comment by marionbarker** [comment]
Bump

**Comment by marionbarker** [comment]
Bump

**Comment by ps2** [comment]
There is a stopgap PR that should prevent some of the effects of this issue, but to really solve the issue here, we need to find out what the message is that is being parsed incorrectly. There may be more evidence in the device comms logs in the issue reports, if anyone is able to dig into those.
