### ISSUE TITLE
Pod pairing failed

### ISSUE THREAD

**Issue by robinwo** [LoopKit/Loop#2093]
**Describe the bug**
On trying to connect a new Dash pod to start priming process, I get the error: “ The operation couldn't be completed.
(OmniBLE.SessionEstablishmentException error 1). This happened twice in two weeks now.

**Attach an Issue Report**
Done

**To Reproduce**
Try to setup a new pod. First step to connect a new pod leads to this error. On retry attempts, it says something about incorrect response. On closing & reopening app, it says finish pairing. On trying to finish pairing (insert cannula), it says the pod is not ready & needs disregarding.

**Expected behavior**
Pod to start priming.

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS] IPhone 15
 - OS Version: [e.g. iOS 12.0.1] 17.1.1 

**Loop Version**
 - Version Number: [e.g. 1.9.2] 3.2.3 (58)
 - Repo: [LoopKit/Loop, Katie, etc] Loopkit/loop

**CGM**
 - Device: [e.g. Dexcom G6] FSL
 - Manager app: [e.g. Dexcom App, Spike] GlucoseDirect

**Pump**
 - Manufacturer: [e.g. Medtronic] Omnipod
 - Model: [e.g. 723] Dash
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]
 - 
 
[Loop Report 2023-11-13 10:51:45+01:00(1).zip](https://github.com/LoopKit/Loop/files/13333568/Loop.Report.2023-11-13.10.51.45%2B01.00.1.zip)
![IMG_0105](https://github.com/LoopKit/Loop/assets/2698369/221061fb-5fd0-4cf8-9e9c-a94ee1f73587)
![IMG_0106](https://github.com/LoopKit/Loop/assets/2698369/e0735199-244e-4b3d-93b3-2553e502fefc)

**Additional context**

**Comment by marionbarker** [comment]
I'm going to need help on figuring out if this was a recoverable error and if so, how; or if this is a "bug" where an unusual problem needs a different response on restarting the app. The pod in question is the third pod in the attached log. The parsed messages for that pod are attached below in the csv file. The time-stamp in question is 2023-11-13 08:41:37.

@ps2 and @itsmojo:

This pod completed the pairing but did not proceed to the configuration step (the 0x08, 0x19, etc were not sent), but user was sent to the Insert Cannula screen upon restarting the app.
* csv file with parsed commands for this pod
* [podState_Robin_Wouters_20231113_1051_3.csv](https://github.com/LoopKit/Loop/files/13337585/podState_Robin_Wouters_20231113_1051_3.csv)


Excerpt from the log file:
```
* 2023-11-13 08:41:37 +0000 Omnipod-Dash 17DDBC82 send ffffffff00060704ffffffff82b2
* 2023-11-13 08:41:38 +0000 Omnipod-Dash 17DDBC82 receive ffffffff04170115040a00010400040208965ea10003fc5b00ffffffff808f
* 2023-11-13 08:41:39 +0000 Omnipod-Dash 17DDBC82 send ffffffff0815031317ddbc8214040b0d17092908965ea10003fc5b8195
* 2023-11-13 08:41:41 +0000 Omnipod-Dash 17DDBC82 receive ffffffff0c1d011b13881008340a50040a00010400040308965ea10003fc5b17ddbc82802c
* 2023-11-13 08:41:46 +0000 Omnipod-Dash 17DDBC82 error Unacknowledged message. seq:2, error = messageIOException("Could not write $msgType: sentWithError(OmniBLE.PeripheralManagerError.incorrectResponse)")
```

**Comment by robinwo** [comment]
Bumping this one. This morning had again a pod failing to start priming. Not the errors as in the provided screenshot, only showing 'incorrect response' a couple of times. It then proceeded to inserting cannula, that did not initiate because pod was not ready (only option to discard).

New critical logs export:
[Export-20240102T095948Z.zip](https://github.com/LoopKit/Loop/files/13811256/Export-20240102T095948Z.zip)

**Comment by itsmojo** [comment]
The DeviceLog has two different 08 configure delivery flags command attempts (at 09:08:56 and 09:09:04). The first one gets an Unacknowledged message error while the 2nd one has a pod disconnect/connect/disconnect sequence followed by an Unacknowledged message error. The 08 command must be successfully done before the prime bolus command will be attempted.

In the DeviceLog the failed 08 commands are followed by 2 successful get status commands (at 09:09:15 and  09:10:13) which both receive a pod progress state of primingCompleted = 3 which indicates that pairing has completed but the priming bolus command has not been received. This is totally consistent with the logs showing two failed 08 commands and the prime bolus never being attempted. The next action in the logs after this is the deactivation sequence starting at 09:10:19 with a get pod info 0x50 request followed immediately by a pod deactivate command after the SwiftUI incorrectly advanced to cannula insertion view and the pod had to be discarded.

Loop should never advance to the inserting cannula dialogue until after the priming is actually completed (pod progress status of primingCompleted = 5). This seems to be another example of pod state problems introduced as part of the Loop 3.x rewrite (for SwiftUI?) which still needs to be addressed.
