### ISSUE TITLE
Apple Watch won't install Loop

### ISSUE THREAD

**Issue by bfeinzimer** [LoopKit/Loop#2099]
**Describe the bug**
Unable to add Loop app to Apple Watch Series 8 on Watch OS 10.1.1 (iOS 17.1.1.). Was working on my last watch but had it replaced by AppleCare and unable to get it loaded onto new watch. Have tried multiple unpair/repairing of watch and rebuilding (on two different macs) of Loop-dev (latest, 3.3.0 (57)) to no avail. Every time I attempt to install the watch app, the indicator spins and a pop up dialouge "The app could not be installed at this time. Could not install at this time." pops up. Developer mode is enabled and the watch requested to be trusted with Mac/Xcode and was trusted after each repairing of the watch. 

In the past when this was having issues, the circle indicator would begin to close and fail, now is it just spinning and failing without completing any of the progress indication.

Working from the Build Errors page, when trying to build the watch app directly in Xcode, I get the following error, but the app did finally install. At this point, this is more of an FYI since I solved the issue but it took hours and hours so hopefully this helps someone else.

Failed to install the app on the device.
Domain: com.apple.dt.CoreDeviceError
Code: 3002
User Info: {
    DVTErrorCreationDateKey = "2023-11-26 06:17:55 +0000";
    IDERunOperationFailingWorker = IDECoreDeviceSideInstallAppWorker;
    NSURL = "file:///Users/bf/Library/Developer/Xcode/DerivedData/LoopWorkspace-dpoqmgdqzioisxgrvndjbbzaifjn/Build/Products/Debug-iphoneos/Loop.app/";
}
--
Unable to Install “Loop”
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Please try again later.
Recovery Suggestion: The WatchKit 2.0 app being installed contains an invalid application executable.
--
The WatchKit 2.0 app being installed contains an invalid application executable.
Domain: MIInstallerErrorDomain
Code: 72
User Info: {
    FunctionName = "-[MIInstallableBundle _isValidWatchKitApp:withVersion:installableSigningInfo:isSystemAppInstall:error:]";
    LegacyErrorString = InvalidStubExecutable;
    SourceFileLine = 787;
}
--
Did not validate all slice hashes on executable /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.08R57G/extracted/Payload/Loop.app/Watch/WatchApp.app/WatchApp; unchecked hashes: {
    72057645577535488 = {length = 20, bytes = 0xef36d5da0692171e1148b0845cc78d8535e9ad2d};
    51539607564 = {length = 20, bytes = 0xead5e49e4ef96b0e95d3f2c0a9b51b000eeecf3e};
}
Domain: MIInstallerErrorDomain
Code: 72
User Info: {
    FunctionName = "+[MICodeSigningVerifier _validateBundleExecutable:againstStubAt:trustedHashes:sectionName:signingIdentifier:error:]";
    LegacyErrorString = InvalidStubExecutable;
    SourceFileLine = 564;
}
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_isWireless" = 1;
    "device_model" = "Watch6,9";
    "device_osBuild" = "10.1.1 (21S71)";
    "device_platform" = "com.apple.platform.watchos";
    "dvt_coredevice_version" = "348.1";
    "dvt_mobiledevice_version" = "1643.40.14";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = "arm64_32";
    "operation_duration_ms" = 24216;
    "operation_errorCode" = 72;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.3002.IXUserPresentableErrorDomain.1.MIInstallerErrorDomain";
    "operation_errorWorker" = IDECoreDeviceSideInstallAppWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.watchos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application.watchapp2";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "watchos10.0";
    "sdk_osVersion" = "10.0";
    "sdk_variant" = watchos;
}
--

System Information

macOS Version 14.1.1 (Build 23B81)
Xcode 15.0.1 (22266) (Build 15A507)
Timestamp: 2023-11-25T22:17:55-08:00

![Screenshot 2023-11-25 at 9 57 55 PM](https://github.com/LoopKit/Loop/assets/12087944/f65dd654-ecaf-4c44-96e8-4e5a39a4a41b)

**Comment by chintzboy** [comment]
I had this happen to me as well. It turns out that I needed to go back to my developer account, except the new terms, and then register the watch. There's a way to manually register devices if it doesn't happen gracefully through Xcode. Hope this helps.

**Comment by bfeinzimer** [comment]
Ah yeah, after several times rebuilding Xcode prompted me to re-register the watch while I tired to run the watch app independently. Perhaps troubleshooting instructions can be updated to include this info.

**Comment by sarusso** [comment]
For who don't know how to build and run the Watch App independently (as myself), you need to change the scheme to "WatchApp" in the top "navigation" bar of xCode, where usually you can see "LoopWorkspace" with the little Loop icon.

Then, select your Apple Watch (either as standalone or as "via iPhone", depending on the watch model and OS) and hit the play button. At this point you will have a much more verbose message than just "The app could not be installed at this time", and most likely you need to fiddle with the signing.

For me, what worked was to manually register the new Apple Watch in the Apple Developer Account (here: https://developer.apple.com/account/resources/devices/list), then un-check and re-check the "Automatically manage signing" int the Watch App xCode scheme (under "Signing and capabilities").

Many thanks to @bfeinzimer for pointing in the right direction.

**Comment by jeremybarnum** [comment]
I had this problem too.  Root cause was new watch.  A couple of learnings: accessing developer mode required both going to the bottom of settings to enable some items in the "Developer" menu, and *then* doing the usual step of going to the bottom of the Privacy menu.  Once that all happened, I got the problem described in this issue.  Building directly to watch prompted the registration to the developer account which happened automatically, and then it was fine.  It might be worth updating the build error section of the documentation for watch build errors.
