### ISSUE TITLE
Crash in OmniBLE when setting a temp basal duration of less than 15m

### ISSUE THREAD

**Issue by kingst** [LoopKit/Loop#2100]
**Describe the bug**
When you use a duration of less than 15m in the `enactTempBasal` method of an OmniBLE Pump Manager, it causes a crash. As per [discussion on zulip](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Crash.20when.20tempBasal.20set.20lower.20than.2015m), the shortest valid duration for an Omnipod is 30m, so the calling code is incorrect. However, ideally this incorrect invocation wouldn't cause a crash.

**Attach an Issue Report**
The crash happens at this [line of code](https://github.com/LoopKit/OmniBLE/blob/f9a7ba7eecd9c9e98385a33ccf14deb644876e01/OmniBLE/OmnipodCommon/MessageBlocks/TempBasalExtraCommand.swift#L68).

**To Reproduce**
1. Invoke `enactTempBasal` with a duration of 5m

**Expected behavior**
Return an error without updating the pump's state

**Screenshots**
N/A

**Phone**
 - Hardware: iPhone 14
 - OS Version: iOS 16.4

**Loop Version**
 - Version Number: N/A
 - Repo: LoopKit/OmniBLE

**Pump**
 - Omnipod Dash

**Additional context**
I don't believe that this crash will affect Loop, only other apps that use LoopKit and craft their own durations for temp basal commands.

**Comment by marionbarker** [comment]
Please close this issue. Loop does not request a duration less than the pod can supply.

The pod code is being updated to prevent this causing a problem for other apps that may not limit temp basal durations.

**Comment by kingst** [comment]
Hi @marionbarker, happy to close the issue but @itsmojo asked me to open one when he volunteered to fix it https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Crash.20when.20tempBasal.20set.20lower.20than.2015m/near/405745859

**Comment by itsmojo** [comment]
Created the following PR's that prevent a Loop crash when an unexpected non-zero temp basal duration less of than 15m is used as reported in https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Crash.20when.20tempBasal.20set.20lower.20than.2015m/near/405745859 in addition to preventing other crashes from temp basal durations > 12h. These Omni{BLE,Kit} fixes have already landed in both iAPS dev and FreeAPS dev.

https://github.com/LoopKit/OmniBLE/pull/108
https://github.com/LoopKit/OmniKit/pull/20

This issue should be closed after both of these PR's have landed in Loop dev.

**Comment by itsmojo** [comment]
This issue is not stale, it's just that the PR's to address this issue have been pending for over a month.
https://github.com/LoopKit/OmniBLE/pull/108
https://github.com/LoopKit/OmniKit/pull/20

**Comment by itsmojo** [comment]
The following PR's have both landed and thus this issue should be closed.
https://github.com/LoopKit/OmniBLE/pull/108
https://github.com/LoopKit/OmniKit/pull/20
