### ISSUE TITLE
[Dev] Carb Entry Screen - must double tap Emoji icon when selecting Food Type first 

### ISSUE THREAD

**Issue by rolandet** [LoopKit/Loop#2103]
**Describe the bug**
On the latest Dev build, Carb Entry Screen - must double tap Emoji icon when selecting Food Type first.  Select Food Type first and tap an Emoji icon and the food type emoji will not appear. If you enter the Amount Consumed first the issue does not occur. This behavior is different from the 3.2 release where a single tap does produce the emoji icon.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
 Carb Entry Screen - select Food Type first and tap an Emoji icon and the food type emoji will not appear.

**Expected behavior**
Emoji icon should appear on first tap.

**Screenshots**

**Phone**
 - Hardware: iPhone 12
 - OS Version: iOS 16.7.2

**Loop Version**
 - Version Number: Latest 3.3 Dev build
 - Repo: LoopKit/Loop

**CGM**
 - Device:  Dexcom G6
 - Manager app:Dexcom App

**Pump**
 - Manufacturer: Omnipod Dash

**Additional context**

**Comment by rolandet** [comment]
Update: It would seem that entering the Amount Consumed first does not consistently allow for a single tap on the emoji to work. I just tried it again and even after entering the Amount Consumed first I still had to double tap the food emoji for it to show up.

**Comment by TravisWhip** [comment]
I notice a similar behavior on Dev with adjusting the absorption time. It seems as if there is a short lock out period when selecting one of the default absorption time emojis (pizza for example). It takes between 2-5 seconds before you can adjust the time.

I wonder if this is related to the favorite foods feature processing something in the background?

**Comment by ryangs23** [comment]
I am also having this issue. The first tap on a food emoji when adding a carb entry correctly changes the absorption time, but the emoji does not appear in the "food type" field. It appears on the second tap, and subsequent different food emojis on the same carb entry only require one tap.

**Comment by ryangs23** [comment]
This does not occur if you first tap one of the emojis without a time attached (such as the martini). Emojis without a time associated will appear immediately. And then if you follow it up by tapping one with time attached (such as cheese), it changes the absorption time but the emoji does not appear until the second tap. So, it does seem to be associated with the food emoji changing the absorption time.
