### ISSUE TITLE
add the possibility of entering blood sugar levels from your finger even when there are dexcom readings

### ISSUE THREAD

**Issue by davidprogramme** [LoopKit/Loop#2104]
Hi, as already written in the title it would be very nice if you could give the glycemic reading from the finger even if there are dexcom data. sometimes it happens that the dexcom data is distorted and even if you calibrate it you always risk having a big error if you have to use the bolus calculator for a meal. Even if you calibrate it, the dexcom value in the app loop remains the one previously communicated by dexcom. Sometimes even waiting the usual 5 minutes for the next reading doesn't help much because the next one could also have an error. What I propose is to be able to enter the finger reading at any time and that this reading is used as true blood sugar by the system for at least 5 minutes, bypassing the dexcom reading. So you could have those 5 minutes to be able to more accurately use the bolus calculator to make the correct amount of insulin. It would also be great for the system to readjust the glycemic values ​​if the subsequent dexcom readings after the finger reading were too discordant or with a difference between the two values ​​that was too high. I hope I have explained myself clearly. Thank you

**Comment by marionbarker** [comment]
My procedure if I have a sensor that is really bad (>50 mg/dL off and not accepting calibrations) is to temporarily remove that CGM from Loop. (Fight with it in the sensor app, not the Loop app.)

If you want to force an immediate change to forecast, you can edit apple health to remove those CGM values that are incorrect and replace them with finger stick values.

Maybe if there was a "don't believe the CGM button" that could be pressed in Loop, it might make this easier to achieve, but that would take a bit of design work.
