### ISSUE TITLE
Insert Cannula Slider does not work for languages that go right to left

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#2105]
**Describe the bug**
A picture is worth a thousand words:
Insert Cannula screen for Hebrew

![Screenshot 2023-12-21 at 14 03 06](https://github.com/LoopKit/Loop/assets/19607791/c6ba2f56-5bce-4a85-ac9b-8326e61d403a)

**To Reproduce**
1. Build dev branch (after cannula insertion was changed to a slider)
2. Pair a pod and go to insertion screen
3. The slider does not work correctly when the language goes from right to left

**Expected behavior**
Be able to slide the slider from left to right or right to left - not sure what best approach is.
Right now indicator is all the way to the right and a normal attempt to move it fails.

Based on a hint from the user who complained about this, if you touch the indicator near the left side of the circle and move as fast as possible to the right, you can get it to insert, but obviously - this is not the desired behavior.

Repeated for Arabic as well as Hebrew.

LoopKit/LoopWorkspace, commit 67a4b1f
rPi DASH simulator for testing.

**Comment by marionbarker** [comment]
The PR for OmniBLE and OmniKit are added for cross reference.

* OmniBLE: https://github.com/LoopKit/OmniBLE/pull/99
* OmniKit: https://github.com/LoopKit/OmniKit/pull/13

**Comment by dabear** [comment]
reproduced this in a demoapp.
This app is standalone, and mocks the omnipod integration with swiftui and allows you to test this bug out without inserting an actual pod..


![image](https://github.com/LoopKit/Loop/assets/442324/a3030497-db9b-4cd7-8756-c59d228aa4c0)


https://github.com/dabear/testslider3/commit/0029e9dd7aaf9936a81101162eeee096667d1530

![image](https://github.com/LoopKit/Loop/assets/442324/cb20aa16-7a95-4539-b26f-8ed44a8182cd)

**Comment by dabear** [comment]
reported it upstream here: https://github.com/no-comment/SlideButton/issues/4

**Comment by marionbarker** [comment]
In zulipchat, (in addition to recommending that this be fixed in the upstream repository), it was proposed that instead of 
```
.environment(\.layoutDirection, .leftToRight)
```
the "fix" should use
```
.flipsForRightToLeftLayoutDirection(true)
```

I tested that modification as shown in the graphic below.

We do not have translations for either Arabic or Hebrew for the words in the slider - so they show up as English letters written right to left for both those languages. The slider moves correctly from right to left and inserts the cannula (as tested with the rPi DASH simulator).

![flips-left-for-right-true](https://github.com/LoopKit/Loop/assets/19607791/6b5ea544-dd23-49b3-8c48-6e97a1d48dd0)

**Comment by billybooth** [comment]
This is probably not a perfect translation, but you might try plugging in some Hebrew text (below) to verify that it doesn't flip. My sense is that `.flipsForRightToLeftLayoutDirection(true)` mirror flips the entire container and might not be appropriate for an element that contains text.
```החלק כדי להכניס צינורית```

**Comment by marionbarker** [comment]
I added your Hebrew string to the translation by inserting these lines into `LoopWorkspace/OmniBLE/OmniBLE/he.lproj/Localizable.strings`:
```
/* Cannula insertion button text while ready to insert */
"Slide to Insert Cannula" = "החלק כדי להכניס צינורית";

```

Here is the result:

![add-hebrew-flips-left-for-right-true](https://github.com/LoopKit/Loop/assets/19607791/d78f83a7-5d24-4493-9553-b216726f3317)

**Comment by dabear** [comment]
fixed upstream

**Comment by marionbarker** [comment]
This LoopWorkspace PR pulls in the upstream fix.
*  [LoopWorkspace PR 103: update to rev of SlideButton package that handles rtl languages](https://github.com/LoopKit/LoopWorkspace/pull/103)

**Comment by marionbarker** [comment]
This was fixed when https://github.com/LoopKit/LoopWorkspace/pull/103 was merged.
