### ISSUE TITLE
setting ADULT_CHILD_INSULIN_MODEL_SELECTION_ENABLED didn't work

### ISSUE THREAD

**Issue by miles-bailey** [LoopKit/Loop#2106]
**Describe the bug**
Added child model setting to the xcconfig file

// Add Build-Time features to compilation conditions
ADULT_CHILD_INSULIN_MODEL_SELECTION_ENABLED = YES

Successful rebuild and deploy but no option in the Therapy Settings section to enable Child model

**Attach an Issue Report**
[Loop Report 2023-12-23 10_58_56+08_00.md](https://github.com/LoopKit/Loop/files/13757815/Loop.Report.2023-12-23.10_58_56%2B08_00.md)

**To Reproduce**
Steps to reproduce the behaviour:
1. add ADULT_CHILD_INSULIN_MODEL_SELECTION_ENABLED = YES to xcconfig
2. Rebuild Loop and deploy
3. Check Therapy Settings for expected option

**Hardware**
 - Hardware: iPhone Xs Max
 - OS Version:  iOS 17.1.2

**Loop Version**
 - Version Number: v3.2.3

**CGM**
 - Device: Dexcom G6

**Pump**
 - Simulator mode
 - Manufacturer: Omnipod
 - Model: Dash

**Comment by marionbarker** [comment]
Please review the instructions again. That is not the correct way to add any build time feature.

Add these lines to the end of your `LoopConfigOverride.xcconfig` file.

```

// Add Build-Time features to compilation conditions
SWIFT_ACTIVE_COMPILATION_CONDITIONS = $(SWIFT_ACTIVE_COMPILATION_CONDITIONS) ADULT_CHILD_INSULIN_MODEL_SELECTION_ENABLED
```

Here is the LoopDocs reference.
* https://loopkit.github.io/loopdocs/build/code-customization/#build-time-features

Tested to ensure it still works. This is from the Therapy screen after applying this modification.

![Screenshot 2023-12-23 at 07 39 56](https://github.com/LoopKit/Loop/assets/19607791/bc4d426a-46bf-435b-9cc8-38990b30e857)

**Comment by marionbarker** [comment]
Please close this issue when you get a chance. The information remains on github but is filed as a closed issues.

**Comment by miles-bailey** [comment]
Thanks for the help Marion, new language, new syntax.... 

All working now.
