### ISSUE TITLE
Librelinkup as cgm source

### ISSUE THREAD

**Issue by Samhagberth** [LoopKit/Loop#2107]
**Describe the solution you'd like**
For loop to get the bg values from libre3 and libre 2 by librelinkup. An optional average filter on the latest 5 to 10 minutes would also be preffered before loop and upload to nightscout. 

I have been looping for a while now with nightscout as cgm source with uploaded libre3 bg values from librelinkup to nightscout. Libre 3 bg values often  spikes up or dips down and also falls and rises at great speeds (delta) due to it tries to predict the blood bg and over do it. This you can see later in the historical bg data in the librelinkup app.  Loop does a great job to manage this (more safer now with experimental algorithm)  but it  sometimes leads the automatic bolus to give to much and then zero the basal directly after. 

It also leads to the loop predict a low scenario in the future and will not suggest meal bolus or give too little even with the safety limit of 3.9

**Describe alternatives you've considered**

**Additional context**

**Comment by alexmos-com** [comment]
I think a better solution would be for Loop to connect directly to the Libre sensor or app (Libre app, not Libre Linkup app), not needing an internet connection to get the sensor readings.
