### ISSUE TITLE
Xcode will not recognize connected Apple Watch

### ISSUE THREAD

**Issue by jasonarns** [LoopKit/Loop#2112]
**Describe the bug**
Xcode, version 15.1, is not recognizing a connected Apple Watch series 9 OS 10.3.  I recently purchased a new Apple Watch, series 9.   Subsequently, I had to update my iPhone (14 pro) to iOS 17.2.1.  The watch is running OS 10.2.  I rebuild the Loop app on the phone and it is running without issue; however, the watch is not recognized on Xcode.  When paired with the phone, the watch is not appearing in the devices list in Xcode.  I have attempted every troubleshooting idea (unpair/re-pair the watch, unplugging and replugging phone, restarting all devices including Xcode, uninstalling Xcode and re-installing the software, deleting all provisioning profiles, wiping all downloads and completely restarting, with no fix.  I have waited upwards of 2 hours for the watch to appear in Xcode and it still does not.   The new watch does appear in the 'console' tab; however.   I cannot obtain a UDID # for the new watch without Xcode 'seeing' it and cannot add it to my Apple developer account.   Loop does appear on my watch yet states "Unable to install Loop - this app cannot be installed because its integrity could not be verified."  Developer mode is turned 'ON' on both devices.   I am not sure what else to do at this point and, beyond returning the watch and purchasing another, am not sure what to do to resolve the issue.  
**Attach an Issue Report**
No build issue as this is an Xcode problem.

**To Reproduce**

**Expected behavior**
When I connected by iPhone to the computer, I expected Xcode to recognize and list my new paired Apple Watch and list it in the devices tab.  I also expected Loop to be installed and run on the new watch.  

**Screenshots**
![IMG_3565](https://github.com/LoopKit/Loop/assets/32888756/b82a4104-4433-4af7-91a9-a29310dcee61)

![IMG_3564](https
![IMG_3566](https://github.com/LoopKit/Loop/assets/32888756/8b248d75-67e2-4fea-8023-d170e3706e74)
://github.com/LoopKit/Loop/assets/32888756/d36028a2-359d-4a1b-9ee1-11aad1cb9592)

**Phone**
 - Hardware: iPhone 14 Pro
 - OS Version: iOS 17.2.1

**Watch**
- Hardware: Apple Watch series 9 45mm
- OS Version: OS 10.3

**Loop Version**
 - Version Number: 3.2.3
 - Repo: N/A

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 523
 - Firmware version: 2.4A1.1

**Additional context**

**Comment by paolofvn** [comment]
The problem is solved by making sure you have the Apple computer, iPhone and watch all connected to the same WiFi network, which must allow communication between the devices.
