### ISSUE TITLE
testflight browser build Node.js 16 actions are deprecated 

### ISSUE THREAD

**Issue by feliciaann32** [LoopKit/Loop#2123]
**Describe the bug**
updating second time after 3 month expiration, using test flight github browser build. i accepted apple agreements. i have paid developer account that won’t expire until august. synced fork. the build was successful but with following error below. i receive email saying everything is successful. this previously worked, for 180 days, i had a previous update, my app expired today following previous build renewed 90 days ago

Annotations
2 warnings
[secrets / validate](https://github.com/feliciaann32/LoopWorkspace/actions/runs/7732678328/job/21083116422)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
[build](https://github.com/feliciaann32/LoopWorkspace/actions/runs/7732678328/job/21083132447)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Phone**
 - Hardware: iPhone 13
 - OS Version: 15.6.1

**Comment by feliciaann32** [comment]
i am now reading this link below. my previous update was 90 days ago on october 30 
https://www.loopandlearn.org/custom-code/#add-cgm-323-browser

**Comment by feliciaann32** [comment]
i don’t think the cgm notes are relevant based on the build errors. i’m using main branch. i don’t wish to make any changes. but i followed the notes and retrying to rebuild.

**Comment by feliciaann32** [comment]
failed…

**Comment by marionbarker** [comment]
You can ignore the deprecated warning. We know about it and will take steps before the build action stops working. 

I’m not sure what your comment “failed” means. Looks like you built successfully several times today.

**Comment by feliciaann32** [comment]
the app thinks that it’s expired
![Uploading IMG_7578.jpeg…]()
 still

**Comment by marionbarker** [comment]
Did you open TestFlight and install the updated build into the phone?

**Comment by feliciaann32** [comment]
didn’t know that step. thank you so much. have a great week

**Comment by marionbarker** [comment]
Please close this issue and bookmark this link:

https://loopkit.github.io/loopdocs/gh-actions/gh-update/#how-to-update-or-rebuild

**Comment by feliciaann32** [comment]
ok thank you

**Comment by feliciaann32** [comment]
https://loopkit.github.io/loopdocs/gh-actions/gh-update/#how-to-update-or-rebuild
