### ISSUE TITLE
Modify favourite foods to allow split meal entry.

### ISSUE THREAD

**Issue by JohnKitching** [LoopKit/Loop#2127]
**Is your feature request related to a problem? Please describe.**

Some people don't like entering split meals manually. Some enter three meals in Loop to deal with later carb rises from a single meal. 

**Describe the solution you'd like**

Allow a meal to be split within favourite foods so some carbs are delivered now and some later. 
This could be based on FPU and / or meal size. 

**Describe alternatives you've considered**

**Additional context**

**Comment by marionbarker** [comment]
Bump
