### ISSUE TITLE
IAD settings screen include decimal

### ISSUE THREAD

**Issue by CrushingT1D** [LoopKit/Loop#213]
![image](https://cloud.githubusercontent.com/assets/18058098/19018070/bba30acc-889f-11e6-8c46-654254657cc1.png)
![img_6565](https://cloud.githubusercontent.com/assets/18058098/19018074/02da49a0-88a0-11e6-903f-4878588630b6.PNG)

Should display 3.75 in the settings view.
Discovered in dev branch for v1.0 (believe it worked properly in master 0.13)
Found on iPhone6s, iOS 10.0.3

**Comment by loudnate** [comment]
http://stackoverflow.com/questions/32522965/what-am-i-doing-wrong-with-allowsfractionalunits-on-nsdatecomponentsformatter
