### ISSUE TITLE
More agressive first hour after meal when only partial meal insulin doze has been given

### ISSUE THREAD

**Issue by Samhagberth** [LoopKit/Loop#2130]
When carbs are added at meal time and loop predicts under the safetylimit it will not give the whole insuline amount for the meal, it would be great if loop when the bg is over the safetylimit and going up to set the missing insulin more agressive like 80% every cycle maybe within 1 hour after meal to prevent unneccesary high and swingy bg

**Comment by marionbarker** [comment]
But there are other people (like me) for whom this is not a desirable modification.
* Some people have slow gastric processing
* Some people use medications like Metformin or GLP-1 which slow gastric absorption and limit glucagon production from the liver

My suggestion is to use the tools that are already there.

Option 1: Use premeal target after carb entry
* set your premeal target to match your glucose safety limit
* as soon as you enter carbs for a meal, tap on the premeal icon - this will last for 1 hour or until you enter more carbs

Option 2: Create a named override
* This is the method I used before I added Metformin
* I created a named override called `Meal` set to last 2 hours and at my glucose safety target level
* When I prebolused for my meal, I would enable that override before I entered carbs

Result:
* Loop will only automatically provide insulin when your current glucose is within target range which is typically 20 mg/dL above the glucose safety limit
* With one of these types of target range overrides in place, as soon as your glucose starts to rise, Loop will begin adding insulin to compensate for the prediction

The other half of this is that Loop is very conservative at dosing if your prediction goes below your safety limit. You can manually override Loop's recommendation based on your experience. I would suggest no more than 50% of what you thing that meal needs if Loop is recommending 0 U bolus.

**Comment by Samhagberth** [comment]
Ofcours its different for everybody this could be optional and fits people  with high carb often fast carbs diets like children, the thing with loop is that you want it as simple as possible without many manual tweeks all the time if loops predicts a bg of 20 and waits to long and give the meal insulin in small dozes over one hour it leads to high and then late autocorrection leads to the same situation next meal ( partial insulin meal doze)

**Comment by ksilive** [comment]
Before entering a meal, you could use an individual override. Do you understand and use overrides?

**Comment by Samhagberth** [comment]
Yes I know thats not my point it would be easier than override just to put in the insulin manually acording to carb ratio iob or just watch the predicted bg, but this is not automatic

If you have like me a kid in school they have no the idea about insulin amounts so if loop puts 0,6 u to a meal that needs 2 u because of current prediction due to dipping bg . Often after a few minutes loop predicts a bg an recommend the whole dose 2 but would not set this automaticly but in small doses over 45 min this leads to damaging highs and unnecesary tare on my childs health . To not set the proper amount insulin to meal often is bad for organs etc

loop should protect from damage in both ends . It can not be unsafe to put in the amount of insulin you should have acording to CR if loop predict high bg,  low IOB and are over safety limit
