### ISSUE TITLE
Loop 3.2.3 Install Help

### ISSUE THREAD

**Issue by hagarza8** [LoopKit/Loop#2133]
Need help with installing Loop 3.2.3. We had our son on Loop 2.2.6 running good. We decided to get Dash pods to get rid of the orangelink. Im running Xcode 15.2 with MacOS Sonona 14.2.1. iphone SE 2nd gen iOS 17.3.1. Build succeeds no red errors come up and app automatically opens on phone but stays on the black screen. See attachment. Any help or pointers would be appreciated.

I did not delete the v2 Loop app originally. After v3 app came up with black screen i deleted app and reinstalled, issue remained.

Also now app crashes as soon as I try to open it. I'm sure its something in missing. Again any help would be greatly appreciated. 
![IMG_1299](https://github.com/LoopKit/Loop/assets/58373852/7c4d370b-d472-42cc-80e3-0df38ea02c46)

https://github.com/LoopKit/Loop/assets/58373852/491d855a-3a05-4dab-adf2-65a12a846816

**Comment by marionbarker** [comment]
I see you posted in Facebook and are getting help there. 

Please close this issue.
