### ISSUE TITLE
Cannot change glucose safety limit

### ISSUE THREAD

**Issue by cinderelsa** [LoopKit/Loop#2144]
**Describe the bug**
Inside the glucose safety limit tab under therapy settings, when I tap the value (in my case it’s 67 which was imported from my previous loop build), the value slider thing opens, but it only shows 67 and I cannot change it to a different value.

**Attach an Issue Report**
(Github says it’s doesn’t support the format when I attach the file? I’ll try again later from my computer)

**To Reproduce**
1. Go to settings 
2. Click on therapy settings
3. Click on glucose safety limit
4. Click on the value number
5. see error: instead of number slider there is only the preentered number 

**Expected behavior**
Functional Value slider to change glucose safety limit value between 67 and 110

**Screenshots**

**Phone**
 - Hardware: iPhone SE 2021 
 - OS Version: 17.1.1

**Loop Version**
 - Version Number: 3.3.0 (3), built March 9th
 - Repo: dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod 
 - Model: dash
 - Firmware version: ?

**Additional context**
![IMG_5627](https://github.com/LoopKit/Loop/assets/35226894/1f526e70-7442-40da-bbc2-9a9ad09b3f0f)
![IMG_5628](https://github.com/LoopKit/Loop/assets/35226894/3b298add-7b9a-410b-8572-61072f30ea8c)
![IMG_5629](https://github.com/LoopKit/Loop/assets/35226894/4fcda5b6-d994-4727-8a1f-0befd9999390)

**Comment by marionbarker** [comment]
First raise the value of your premeal target higher than 67.
Then glucose safety limit will have more than one value showing (up to your premeal target). 
Read info box at the link below or tap on info icon for each therapy setting on your phone for more explanation. 

https://loopkit.github.io/loopdocs/loop-3/therapy-settings/#guardrails-for-glucose-safety-limit

Please close this issue if this answers your question.

**Comment by cinderelsa** [comment]
Thank you, that did solve it.
Perhaps it would be a good idea to mention the interrelation of glucose safety limit and premeal target in the info box of the glucose safety limit.
Wanting to change this one value, I did not make the connection to the other on the spot, and I've been looping for six years.
