### ISSUE TITLE
Build LoopCore: Command SwiftCompile failed with a nonzero exit code

### ISSUE THREAD

**Issue by ph1rst** [LoopKit/Loop#2145]
Project failed to build, with error:
LoopCore>LoopSettings: Command SwiftCompile failed with a nonzero exit code

No changes in the project from build in October 2023 with Loop version 3.2.3, except updates to Xcode (version 15.3) and moving to iOS 17.4 simulator.

**Screenshots**
<img width="831" alt="image" src="https://github.com/LoopKit/Loop/assets/79832315/dd4e2b29-b7b2-4fde-907e-7486cbf0b2af">

**Phone**
 - Hardware: iPhone 15 Pro
 - OS Version: 17.4

**Loop Version**
 - Version Number: 3.2.3, lastest

**Comment by marionbarker** [comment]
You selected Loop instead of LoopWorkspace. Top middle of Xcode, there’s a dropdown to the left of the phone/simulator dropdown. That should say LoopWorkspace. 

https://loopkit.github.io/loopdocs/build/build-app/#initial-xcode-screens

Please close this issue if this solves your problem.

**Comment by ph1rst** [comment]
My mistake - building at the wrong level!
