### ISSUE TITLE
Loop does not deactive DASH pod during Replace Pod cancelation

### ISSUE THREAD

**Issue by senderob** [LoopKit/Loop#2147]
**Describe the bug**

1. During Pod Replacement process, after pairing but before insertion steps, a pod did not properly stick to my skin and fell off. I hit the  cancel option and confirmed to deactivate pod.  Loop then reverted to the Pair pod step. 

2. I selected Pair Pod. During pairing the Loop app closed and when I reopened it, the main Loop screen was displayed.  I selected the settings tab and the insert canula screen appeared. 

3. I attempted to apply the 2nd pod and suffered the same adhesion problem.  I had to remove the 2nd pod prior to the clicking on Insert Canula button.  I hit cancel and confirmed to deactivate pod.  Loop displayed the Pair Pod step and I selected Pair Pod with a 3rd pod. 
 
4.-  After hitting the Pair Pod button, Loop gave an error that there were too many pods nearby.  I threw the previous 2 "deactivated" pods roughly 30 feet away and select Retry to pair the 3rd pod.  During the pairing process, the app closed and when I reopened the app, the main Loop screen was displayed.  I selected the settings screen and Loop displayed the Insert Canula screen.  I applied Skin Tac to the 3rd pod, applied the pod and then selected Insert Cannula.  The canula was inserted as expected and Loop resumed normal functionality.  

The 2 DASH pods that were paired and then deactivated are still not deactivated and continue to beep (I assume they are waiting for the insert canular command).  I hope that they will eventually time out and stop beeping periodically.

**Attach an Issue Report**
[Loop Report 2024-03-27 13_18_18-05_00.md](https://github.com/LoopKit/Loop/files/14780061/Loop.Report.2024-03-27.13_18_18-05_00.md)

**To Reproduce**
1. Go to 'Settings...'
5. Click on 'Omnipod DASH...'
6. Scroll down to '.Replace Pod...'
7. Select Replace Pod
8. Select Deactivate Pod
9. Fill a new DASH pod (1) with insulin and Select Pair New Pod
10. When the pod pairing completes completes, press the Continue Button
11. When the Insert Canula screen appears, select Cancel
12. When prompted to Confirm Pod Deactivation, select Deactivate Pod
13. When the pair new  pod screen appears, prepare a new pod (2) and  select Pair New Pod.  Pod pairing will connect with pod (2)  and begin pairing process.  (at some point prior to the completion of pairing, the app may close. If so, reopen the app and select the Settings tab..
14. When the Insert Canula screen appears, select Cancel. 
16. Confirm pod deactivation.  When Loop display the Pair New Pod Screen, prepare a new pod (3) and 
17. Select Pair New Pod.   Loop will display a long error indicating too many active pods with a retry button. Move the previously deactivated Pods out of range and select Retry.
18. After pod pairing completes, select Insert Canula.  Confirm pod is attached propertly and pod should complete canula insertion.
19. Proceed as normal from this point.
20. Deactivate the 2 canceled pods or wait for the 2 canceled pods to time out.  
 
I did not personally try to recreate the behavior. 

**Expected behavior**
During DASH replace pod operation, if the user selects cancel and confirms that the pod should be deactivated.  The pod should NO LONGER send out or respond to any communications.  Loop should not see pods that have been deactivated by canceling them during the Replace Pod operation.

**Screenshots**

iPhone 12 iOS 17.4
Omnipod DASH pod
Loop v. 3.2.3 (7) - Using Loop and Learn Browser Build method

**CGM**
 - Dexcom G7
 - Dexcom G7 app

**Pump**
 - Ominpod DASH via the Loop app
 - I will be opening an issue with Dexcom regarding adhesive failure for the 2 pods that failed to stick.

**Additional context**
Skin where I tried to apply the Omnipod DASH pods was clean and dry.

**Comment by senderob** [comment]
Critical Event Log attached.
[Export-20240327T182634Z.zip](https://github.com/LoopKit/Loop/files/14780297/Export-20240327T182634Z.zip)

**Comment by marionbarker** [comment]
There were messages from 5 pods included in this report.
* pod 1: ran for 42.5 hours, delivered 37.05 U, user deactivated
* pod 2: ran for 53.1 hours, delivered 51.2 U, user deactivated
* pod 3: primed correctly but did not get the commands to insert cannula or to deactivate
  * This must have been an adhesive failure
  * Note - without actually getting subsequent pods to connect, there would be no record of messages when you had "too many pods"
* pod 4: priming started but did not complete - pod faulted (0xd6, decimal 214) - this is "Reset type fault of unknown origin"
   * we don't know what that fault is but it was definitely the pod, nothing you or Loop did
   * this pod was deactivated properly so should not be beeping
* pod 5: nominal start up process

Include csv files for pods 3 and pod 4.
* [podState_senderob_t.202403_27.1_3.csv](https://github.com/LoopKit/Loop/files/14782005/podState_senderob_t.202403_27.1_3.csv)
* [podState_senderob_t.202403_27.1_4.csv](https://github.com/LoopKit/Loop/files/14782009/podState_senderob_t.202403_27.1_4.csv)


Pod 2: Addr 0x17167695, Lot 139940641, Seq 3510497
```
first message: 2024-03-25 12:46:25
last message : 2024-03-27 17:55:29
```

Pod 3: Addr 0x17167696, Lot 139940641, Seq 3400485
```
first message: 2024-03-27 17:57:56
last message: 2024-03-27 18:01:00
```

Pod 4: Addr 0x17167697, Lot 139940641, Seq 3380484
```
first message: 2024-03-27 18:02:41
last message: 2024-03-27 18:06:00
```

Pod 5: Addr 0x17167695, Lot 139940641, Seq 3570494
```
first message: 2024-03-27 18:09:44
still running
```

**Comment by senderob** [comment]
Issue should be resolved in next Loop update (currently in Dev).
