### ISSUE TITLE
Loop Crash when I try to change Correction Range

### ISSUE THREAD

**Issue by MrKakk** [LoopKit/Loop#2175]
**Describe the bug**
Hello everyone,

I have an issue with the Correction Range. Around 4 years ago I put an extremely low range at night. This had worked out in the past version of Loop, when there was no minimum for the Correction Range. 

The blood sugar I was setting back in the days  are smaller than the allowed in the newer Loop versions.

At the moment, I have a Correction Range from 80-85 mg/dl from 00:00-00:30. Minimizing the time is the best I could do with it, because everytime I try to change it on the App, it crashes.

How it would be possible for me to change the data from 00:00-00:30?

Thank you very much in advance.

Alex

**To Reproduce**
1. Go to ‘Settings’
2. Click on 'Diabetes Therapy’
3. Scroll down to 'Correction Range'
4. Change the first entry of the Correction Ranges
5. See error

**Expected behavior**
It crashes everytime when I want to do the step 4.

**Screenshots**
![IMG_3158](https://github.com/LoopKit/Loop/assets/73999702/cb7075fd-1aa0-4bbc-9a51-c2b6d0eda78b)

**Phone**
 - Hardware: iPhone XE 2020
 - OS Version: iOS 17.5

**Loop Version**
 - Version Number: 3.2.3
 - Repo: LoopKit/Loop, dev branch

**CGM**
 - Device: Dexcom G7
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Dash
 - Firmware version: Not sure

**Comment by marionbarker** [comment]
I think this is fixed in the dev branch. 
the dev branch is stable now. 

https://www.loopandlearn.org/2024/06/12/loop-dev-first-time/

**Comment by MrKakk** [comment]
I could fix it by myself.

Just by deleting the Loop app on my phone, and building again. Then you can start your settings from 0.

Issue is closed by myself lol

**Comment by MrKakk** [comment]
> I think this is fixed in the dev branch. the dev branch is stable now.
> 
> https://www.loopandlearn.org/2024/06/12/loop-dev-first-time/

One more time, thank you very much for your kind and helpful reply. 

By deleting the app and reinstalling it I could solve the problem.

have a nice day, Alex
