### ISSUE TITLE
Loop update fail from testflight

### ISSUE THREAD

**Issue by Magnelund** [LoopKit/Loop#2184]
I have rebulid the loop app but when i do the last thing and try to update loop app in testflight it is telling me it fails becauce the app missing
![IMG_0753](https://github.com/LoopKit/Loop/assets/167565627/12d9b0ee-59db-4007-abb2-4040b34ce6f0)

**Comment by marionbarker** [comment]
Issues should be used to report bugs or request features in the code. Not to ask for build help. 

I would try building again (action: build loop) and see if a new build works. I don’t recall seeing your problem before. But please use zulipchat or Facebook to ask for help if that doesn’t work. 

And please close this issue. 

https://loopkit.github.io/loopdocs/intro/loopdocs-how-to/#how-to-ask-for-help
