### ISSUE TITLE
Scale on glucose graphs is off

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#219]
It seems that the scale of the graphs is too large.  This is on both the main screen and the predicated glucose screen and looses detail when the graph is fairly flat.  
![2016-10-06 07 29 57](https://cloud.githubusercontent.com/assets/855156/19154490/b777de8a-8ba8-11e6-8ab2-e2ad281ae1f5.png)

**Comment by channemann** [comment]
The reason for going to an expanded default y-axis for glucose was noise and rate-of-change perception. There is a tradeoff between seeing detail and perceiving small changes as huge jumps. Luckily, the default range can be easily changed here:

https://github.com/LoopKit/Loop/blob/master/Loop/View%20Controllers/StatusTableViewController.swift#L324-L325

Note that there is some rounding / padding that occurs, so you'll need to do some tinkering to tune it in just right.

**Comment by beached** [comment]
I've done that, but isn't this doing the same thing but opposite.  It is flattening the data.  The range of the graph here is 6mmol/L(108mg/dl) where the variance is 1mmol/L(18mg/dl).  I suspect there is a happy medium that does not emphasise large variability due to noise(low isig usually) but allows one to see the values clearly still.   Also the code does not work as intented either as this case should clearly be using 100mg/dl as the min range but it is at 108 due to the conversion to mmol/L somewhere else.

Personally I think this minimum should be closer to 4mmol/L or say 70mg/dl.  Still large but it would knock one row off the graph and give a better picture

**Comment by walker0** [comment]
I think the ability to set min and max easily is great, it definitely solves some of the issue of loop zooming in too much as it used to.  @beached  I also use mmol/L and I have been running it with a reduced maximum, as for me 11mmol/L was too high with such a small graph. I also find that with mmol/L increasing the maximum number of segments so that there is more consistently a 1 mmol/L graduation of the graph lines helps with easy interpretation.

**Comment by beached** [comment]
Or allow pinch-zoom maybe with a reset to norm after you let go.  Then this whole thing is moot

**Comment by jmatheson** [comment]
SwiftCharts v0.6 now has pan and zoom. https://github.com/i-schuetz/SwiftCharts/blob/master/CHANGELOG.md

@ps2 updated to v0.6 this week, so we should be able to add these type of feature easier moving forward.

**Comment by Kdisimone** [comment]
as this topic is fairly old (links are outdated to code), and arguably a bit on the "personal preference" type discussion...I'm going to close the topic and look at adding a customization instruction to loopdocs as an alternative for people who might prefer a scale change.
