### ISSUE TITLE
Issue rebuilding loop - sync upstream changes

### ISSUE THREAD

**Issue by JakeOBrien1** [LoopKit/Loop#2190]
Hi, all. My username is JakeOBrien1. I've attempted to rebuild loop this afternoon as my current version is set to expire. I am stuck on the final step of rebuilding loop under the 'Build Loop' part of actions. The error is under 'sync upstream changes' with the message as follows.

'Error: the process '/usr/bin/sh' failed with exit code 1'

I have looked through the previous error reports but can't seem to find anyone who's had anything similar. I haven't made any changes to my loop recently so not sure if there's any settings that would have changed because of this?

I have read through the updated versions and have updated loop accordingly. I have accepted the updated agreement on my Apple Developer account. I have also updated the identifier under loop status extension with the app groups.

**Expected behavior**
The first time I rebuilt my loop, it followed through with the normal steps that are in the guide. However, this time it has got stuck on the final step. I have attempted to re-do this a few times. I did read that the issue may exist if the Apple Developer agreement hasn't been accepted. I have accepted it and re-attempted several hours later with unfortunately no success.

<img width="987" alt="Screenshot 2024-07-14 at 5 56 41 PM" src="https://github.com/user-attachments/assets/c278e6a0-0ff0-4c97-967a-4e0369dbafe5">

**Phone**
 - Hardware: iPhone 13
 - OS Version: iOS 17.5.1

**Loop Version**
 - Version Number: 3.2.3
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Dash
 - Firmware version: 4.10.0

Would really appreciate any support to help me with this.

Thank you!
Jake

**Comment by ldeheus** [comment]
I seem to have been able to fix this same error for me for now by setting a repository variable. ("SCHEDULED_SYNC" with value "false")

This morning I also tried to update from 3.2.3 to 3.4. I also use the browser build and got the same error.

After adding the "SCHEDULED_SYNC" repository variable with value "false" my build worked again. Detail are described here: https://github.com/ldeheus/LoopWorkspace/blob/main/fastlane/testflight.md#how-to-configure-a-variable

The application builded after that and I have the new version in TestFlight.

Some more background:
I noticed an extra commit which was not in my synced main branch. ("Update LoopWorkspace to 3.5.0 dev Loop")

![20240714-124203-flameshot update-loop-error](https://github.com/user-attachments/assets/42788ebc-3652-463a-a12c-49917e231fa1)

Then I noticed the build/update script tried to update from the "alive" branch and found some more explanation about that in this document:
https://github.com/LoopKit/LoopWorkspace/blob/main/fastlane/testflight.md

Maybe that last commit to the "alive" branch is causing the error.

So in an attempt to prevent the build script from updating the branch first I set SCHEDULED_SYNC to false for now.

Hope that helps building for now and fixing it.
Leon

**Comment by JakeOBrien1** [comment]
Thank you so much @Leon!! You are amazing. Thanks to your help I managed to rebuild loop. Thanks a million 🙏

**Comment by marionbarker** [comment]
Sorry about missing this. We will get the alive problem fixed. 

Easiest work around for now
- let alive be created and build will fail. 
- select alive branch and manually update (there’s a merge conflict - so discard a commit).
- build now works

**Comment by aholycow** [comment]
u´re a lifesaver <33333333 my web build will run out in 7h and i was sooo stressed out by this issue. Thxuuuuuuuuuuu so much
