### ISSUE TITLE
Rebuild error - Help needed

### ISSUE THREAD

**Issue by DasBlueFox** [LoopKit/Loop#2199]
**Describe the bug**
The loop had passed the 90 day mark and it was time to build it again. I as we usual looked if the branch needed to sync and did so. After the sync I started the build and got this error. And don’t quite understand what it means. Any help or solution to what caused the build error is much appreciated. 

**Attach an Issue Report**
Building error message:
[Build: Loop/Loop.xcodeproj#L1](https://github.com/DasBlueFox/LoopWorkspace/commit/8060718e78b44ef45797082817392c1c4b7a7dab#annotation_24406663517)
Provisioning profile "match AppStore com.***.loopkit.Loop.LoopWidgetExtension" doesn't match the entitlements file's value for the com.apple.security.application-groups entitlement. Profile qualification is using entitlement definitions that may be out of date. Connect to network to update. (in target 'Loop Widget Extension' from project 'Loop')

**Comment by bjorkert** [comment]
Hi, the solution to that error can be found here:
https://loopkit.github.io/loopdocs/gh-actions/gh-update/#update-from-32x-to-34

BR/Jonas
