### ISSUE TITLE
Randomly switched glucose units

### ISSUE THREAD

**Issue by DasBlueFox** [LoopKit/Loop#2208]
Hi,
My loop just decided to change units from mmol to mgdl. I of course haven’t touched any settings and tried to solve this problem by myself and I use nightscout, although in the side I still get my glucose readings in mmol the same goes for Apple health app.and my freestyle app as well. Has anyone encountered any similar issues and know how to resolve the problem? Any help appreciated, thanks.

**Comment by DasBlueFox** [comment]
Edit:
It just appeared to be some random bug that showed it on “wrong” units for a while after about 30 minutes I went back in to the loop to take insulin and somehow it switched back to the “correct” unit.

**Comment by marionbarker** [comment]
I have seen this reported on Facebook with the suggestion to quit and restart the app and it fixes it right away.

Almost every display glitch in Loop can be solved with a quit and restart. It still shouldn't do this. I will leave it up to @ps2 whether he want to reopen this as an Issue to be tracked.
