### ISSUE TITLE
Incorrect IOB after change of reservoir

### ISSUE THREAD

**Issue by thebookins** [LoopKit/Loop#221]
Sometimes we use the same reservoir at set change. After priming the line, the insulin in the reservoir is 10 or so units lower than before the set change. Loop records this as IOB, regardless of whether the Preferred Data Source is set to Reservoir or Event History. Loop aggressively low temps in this instance. If the reservoir level is greater than before set change, there is no effect on IOB, as Loop correctly interprets this as a new reservoir.

This could be a x22 issue as we are using a 722 pump. Not sure what the behaviour would be on a x23 with MySentry.

**Comment by ps2** [comment]
Some people work around this by re-using the set line.  The other option right now is to delete the last few reservoir entries to force Loop to use history. 

I think it's worth looking at using the prime events from history to supplement reservoir data.  Just using history alone has issues, too, such as delivery events (like square wave boluses) aren't added until they're finished, which can be up to 9 hours later.  Even regular boluses on older (x22) pumps can be slow if they're large.

A reservoir based view supplemented with history events should be able to filter out primes properly.
