### ISSUE TITLE
RF Comms errors

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#222]
The device will give an RF Comms error when a user tries to click the recommended basal rate during a bolus.  I think the fix would be to not display anything that can transmit until the bolus is done and hide them if they are already there.

**Comment by ps2** [comment]
We don't know how long the bolus is; our comms finish when the pump accepts the bolus.  And actual bolus time varies between pumps (newer pumps are faster for larger boluses).

**Comment by beached** [comment]
I think we might know more than that.  The comms stop and the pump is attempting to deliver.  With sentry enabled we know that the reservoir is going down and if it finishes.  The user could stop it in the middle of delivery.  I am uncertain if the pump sends out an alert to that.

I notice most of the rfcomms errors when the pump first starts sending the bolus commands.  Maybe put a hold on displaying basal recommendations for at least the time to finish the command but maybe then next 5min as almost all bolus's will finish in 5min

One note too is that, I see these recommendations with a closed loop.

**Comment by scottleibrand** [comment]
In addition to the mysentry update after the bolus completes, there is also the ability to do the equivalent of `openaps use pump read_status` and check whether the pump is still bolusing.  If so, there's no need to present an RF comms error.

**Comment by ps2** [comment]
Yes, I think maybe checking status (we do have that command implemented) would allow you to present a nicer message about why the basal rate didn't work. 
PR's accepted!

**Comment by ps2** [comment]
There is much improved messaging in 1.3.2 regarding reasons why temp basals or boluses may have failed.  We now detect pump suspended, bolus in progress, max limit exceeded, etc...
