### ISSUE TITLE
Fast lane Build and Archive Error

### ISSUE THREAD

**Issue by sgoodfr** [LoopKit/Loop#2225]
I am getting the following error when I try to update my loop app. I cannot find any info on this error online!
My app is expired and will not let me open on my phone or in TestFlight.

Can anyone help?
![IMG_7361](https://github.com/user-attachments/assets/53d29bc2-f599-49d1-9eff-2763d8f5f81d)
![IMG_7362](https://github.com/user-attachments/assets/9d1627fe-a086-4755-9ac4-48f8570563b3)

**Comment by sgoodfr** [comment]
Additional Information

Describe the bug
Loop fails to update/rebuild on browser. Error says Fastlane Build and Archive.

Expected behavior
Loop to rebuild!

Phone
Iphone 13 pro iOS 17.5.1
Main Branch
Dexcom G7

Test with other hardware
Tried to build with separate computer and saw same failure.

**Comment by marionbarker** [comment]
## Here is your help
I looked at your repo: https://github.com/sgoodfr/LoopWorkspace/actions

You have not rebuilt in 3 months and there is no indication that you followed the update steps. These include running Add Identifiers, add the LoopGroup to the new identifier, run Create Certificates and then run Build Loop. There are also instructions for steps you need to take (sign any new agreements and once a year, renew certificates).
* https://loopkit.github.io/loopdocs/browser/bb-update/#how-to-update-or-rebuild

Please follow those steps carefully.

Given your error `No matching provisioning profiles found for 'AppStore_com.***.loopkit.Loop.LoopWidgetExtension.mobileprovision'`, I suspect all you need to do is follow the update from 3.2.x to 3.4 link - but if that alone doesn't work, do the entire update process I linked first:
* https://loopkit.github.io/loopdocs/browser/bb-update/#update-from-32x-to-34

## What's new in 3.4.1
Please check LoopDocs for release information:
* https://loopkit.github.io/loopdocs/version/releases/

## Do not try to build from an alive branch

I noticed you tried an alive branch for one of your failed builds. Those are only there to make automatic building work (starting with Loop 3.4.1). Here's more information about them. In future, just ignore them.
* https://loopkit.github.io/loopdocs/browser/automatic/#what-are-the-alive-branches

## Next time - use a different method to ask for help
Issues are not meant to be used for build help questions.

Please direct those to Facebook or zulipchat instead.
Here's the zulipchat link: 
* https://loop.zulipchat.com/#narrow/stream/209438-Build-Issues/topic/Build.20Help.20Needed

Once you have built (or connected with someone for help on a different platform), please close this issue. (Closing it just moves it to the closed status - all the messages are saved.) And more messages can be added.

In future, when you have trouble, start with the build errors page - it tells you how to get help and lists common errors. The rest of the page has details.
* https://loopkit.github.io/loopdocs/browser/bb-errors/#help-with-errors

**Comment by sgoodfr** [comment]
Thanks for the help!
