### ISSUE TITLE
Where exactly is the code for the algorithm located?

### ISSUE THREAD

**Issue by ThomasQuant** [LoopKit/Loop#2229]
Hey, I wanna learn the algorithm (and the way the code is structured, as I haven't used Swift in a long time). Where exactly is the algorithmic code located in the files? Or how is it structured exactly?

**Comment by marionbarker** [comment]
This is not an issue with the code. This type of question should be addressed in zulipchat - I suggest you use this topic in this channel.
* https://loop.zulipchat.com/#narrow/stream/270362-documentation/topic/Loopdocs.20Question

Please close this Issue.
