### ISSUE TITLE
Make Checkmark List Items easier to see

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#2238]
**Is your feature request related to a problem? Please describe.**
It can be hard to see where to tap to change selections, especially in dark mode on an iOS 18 phone.

**Describe the solution you'd like**
Modify the code to make the open circles easier to see.

**Describe alternatives you've considered**
N/A

**Additional context**
This is a one line change to 
https://github.com/LoopKit/LoopKit/blob/3ce43ded238a776f7/LoopKitUI/Views/CheckmarkListItem.swift#L77

The graphics below are from left to right:
* current code of `.stroke()`
* option 1, code of `.stroke(Color.accentColor, lineWidth: 1)`
* option 2, code of `.stroke(Color.accentColor, lineWidth: 2)`

Dark Mode: Silence Pod

![silence_pod_stroke_empty_1_2](https://github.com/user-attachments/assets/0bd0333b-0168-4e5d-9e76-1c99decddbce)

Light Mode: Insulin Selection

![insulin_type_stroke_empty_1_2](https://github.com/user-attachments/assets/0e6e4fa2-935f-43fd-abc4-b186c787385d)

From those screens, I think lineWidth of 1 is best.

Here are a few more screens (in dark mode) with the `lineWidth: 1` modification.

![various_dark_lineWidth_1](https://github.com/user-attachments/assets/7573a571-180d-454c-aae0-fbc21248f61d)

**Comment by elnjensen** [comment]
Agreed, these are really hard to see in Dark Mode with the current design.

**Comment by ps2** [comment]
Yes, I agree it's too faint. It might need a line width increase. I'd still like to stick to standard iOS convention for color, though:

![IMG_2543EA3A14AC-1](https://github.com/user-attachments/assets/e6307442-d005-41e8-8d2c-43b2cf239d41)
![IMG_1677](https://github.com/user-attachments/assets/9e1084e0-190f-483f-ab2d-22d48f1612c1)

**Comment by itsmojo** [comment]
Thanks for running this one down & generating a PR for this Marion. From the provided Loop pics I personally prefer using a lineWidth of 2 for these open circles to make things more clear for my aging & color blind eyes, particularly in dark mode.

**Comment by marionbarker** [comment]
Fixed with https://github.com/LoopKit/LoopKit/pull/549
