### ISSUE TITLE
PCH was compiled with module cache path

### ISSUE THREAD

**Issue by rdraeger** [LoopKit/Loop#225]
I have been getting the following error:

<unknown>:0: error: PCH was compiled with module cache path '/Users/riandraeger/Library/Developer/Xcode/DerivedData/ModuleCache/25EH84K17RKX9', but the path is currently '/Users/rdraeger/Library/Developer/Xcode/DerivedData/ModuleCache/25EH84K17RKX9'
<unknown>:0: error: missing required module 'SwiftShims'

Thanks in advance for your help!
-Rian

**Comment by jlucasvt** [comment]
Rian,  were you able to resolve this issue and can we close this?

**Comment by rdraeger** [comment]
Yes, thanks.

-Rian

Rian Draeger
Interaction Designer   |   Product Design

Dexcom, Inc.
rdraeger@dexcom.com
P: (650) 804-5544
C: (650) 804-5544

From: "Jeremy M Lucas (GetRileyLink)"
Reply-To: LoopKit/Loop
Date: Tuesday, November 15, 2016 at 12:08 PM
To: LoopKit/Loop
Cc: RIAN DRAEGER, Author
Subject: Re: [LoopKit/Loop] PCH was compiled with module cache path (#225)


Rian, were you able to resolve this issue and can we close this?
