### ISSUE TITLE
Inexplicable 6U Bolus

### ISSUE THREAD

**Issue by sbernacki** [LoopKit/Loop#2270]
**Describe the bug**
Last weekend (12/1/2024), my ex's Loop inexplicably gave her a 6U bolus about shortly after she entered a meal correction and after it had already delivered a 1.5U bolus. Her rate of change was going down at the time, and she did not catch the bolus until it was fully delivered, when she started feeling that she was going low. 

In the attached Export file, in DosingDecisions.json, line 247062, at 2024-12-01T16:54:49, Loop logs:
```
           "manualBolusRecommendation": {
                "date": "2024-12-01T16:54:49.668Z",
                "recommendation": {
                    "amount": 1.5,
                    "pendingInsulin": 0
                }
            },
            "manualBolusRequested": 1.5,
```

Then, line 256300, at 2024-12-01T17:00:27, an event logs a recommended 0U bolus but then also indicates that it is going to request a 6U manual bolus:
```
           "manualBolusRecommendation": {
                "date": "2024-12-01T17:00:27.756Z",
                "recommendation": {
                    "amount": 0,
                    "notice": "predictedGlucoseInRange",
                    "pendingInsulin": 0
                }
            },
            "manualBolusRequested": 6,
```
Loop even predicts that in about an hour and 20 minutes, her BG will be in the negative range (line 256383):
```
                {
                    "quantity": -3.57205633593864,
                    "quantityUnit": "mg/dL",
                    "startDate": "2024-12-01T18:20:00.000Z"
                },
```

She denies interacting with Loop at all, and denies making any type of manual bolus request to her Omnipod that would deliver a 6U bolus.

Another weird thing is that while the Loop log indicates the 6U decision was made at around 17:00, the screenshot from her phone shows the 6U bolus being delivered at 17:23 (see the screenshot below).

**Attach an Issue Report**
- [Loop Report 2024-12-02 16_22_30-04_00.md](https://github.com/user-attachments/files/18049381/Loop.Report.2024-12-02.16_22_30-04_00.md)
- [20241202T202349Z.zip](https://github.com/user-attachments/files/18049386/20241202T202349Z.zip)

**To Reproduce**
This issue has not reoccurred, and we do not know how to reproduce it.

**Expected behavior**
Not deliver 6U of insulin that is not called for. 

**Screenshots**
![Going down](https://github.com/user-attachments/assets/697f3522-89f4-4e62-a08e-c24ef1e95af6)
![Insulin Delivery](https://github.com/user-attachments/assets/2a0873d9-0ff6-4c32-bd76-b39c235941fe)

**Phone**
 - Hardware: iPhone14,3
 - OS Version: 17.7.1

**Loop Version**
 - Version Number: v3.4.4 (67)
 - Repo: main 20c313c

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Dash 
 - Firmware version: 4.10.0 1.4.0

**Comment by marionbarker** [comment]
## Summary 

The reports indicate this was a manual bolus. Remind her to glance at the phone and then lock the screen after interacting with Loop and prior to putting the phone away to prevent accidental boluses like this in the future. 

I'm very glad she noticed and was able to take steps before going super-low. Even hitting 50 is not comfortable.

Please close this issue. If you have further questions, you can continue the conversation even after closing the issue.

## Details

Note all the time stamps are UTC, so offset by 4 hours from your local time.

### Critical Log Export

The Doses.json file shows:

{"automatic":false,"createdAt":"2024-12-01T17:29:35.166Z","date":"2024-12-01T17:23:37.730Z","deliveredUnits":6,"doseType":"bolus","duration":240,"insulinType":3,"modificationCounter":52264619,"mutable":false,"raw":"Ym9sdXMgNi4wIDIwMjQtMTItMDFUMTc6MjM6Mzda","title":"Bolus","type":"Bolus","unit":"U","uploaded":false,"value":6,"wasProgrammedByPumpUI":false},

The `"automatic":false` indicates manual.

The second time stamp in Doses.json: "2024-12-01T17:29:35.166Z" was when the bolus was confirmed to be completed and mutable (changeable) was changed to "false".

The keyword `wasProgrammedByPumpUI` is only used for Medtronic pumps and is always false for pods.

### Loop Report

I also parsed the Loop Report which contains 84 hours worth of Loop and Pod exchanges.

The message for the `2024-12-01 17:23:37` event (when bolus was requested) has this information:

{'msgType': '0x1a17', 'msgMeaning': 'SetBolus', 'autoBolus': False, 'prompt_bolus_u': 6.0, 'nonce': '0x494e532e', 'TableNum': 2, 'chsum': 376, 'hhEntries': 1, 'secsX8Left': 1920, 'pulsesPerHhr': 120, 'pulse0': 120, 'xtype': 23, 'xlen': 13, 'reminders': 0, 'promptTenthPulses': 1200, 'promptDelay': 200000, 'extendedTenthPulses': 0, 'extendedDelay': 0, 'mlen': 14, 'msg_body': '1a0e494e532e02017801078000780078170d0004b000030d40000000000000', 'seqNum': 9, 'rawHex': '17674d99241f1a0e494e532e02017801078000780078170d0004b000030d400000000000000002', 'CRC': '0x0002'}

Once again 'autoBolus': False, means a manual bolus.

**Comment by sbernacki** [comment]
@marionbarker Thank you very much for this detailed analysis. I will proceed to close this issue.
