### ISSUE TITLE
App build successful - no Test Flight availability

### ISSUE THREAD

**Issue by KristinHagins** [LoopKit/Loop#2271]
Hi,

This is my first issue post, and I'm not sure this is this proper place. I don't have Facebook. I rebuilt the app through GitHub (twice) today, and I receive both expected Apple emails after a successful build, but I have not received the Test Flight email (either time). It has been several hours. The builds are not available in the TestFlight app. Is this an expected delay? Every other time I've done the build through GitHub (many times), the Test flight email/availability has come prior to the second Apple email. Thanks for any guidance.

**Comment by KristinHagins** [comment]
I can see all three builds from 12/8 and one build from 12/9 in App Store Connect > Test Flight.  They indicate Ready for Submission and have appropriate expiration dates.  I updated TestFlight app on my phone, but none of the four builds are showing up in the TestFlight app to install.  I am running 18.1.1 as of yesterday.  Please let me know if you have any suggestions as my current version expires in a
[AppStore Connect.docx](https://github.com/user-attachments/files/18069045/AppStore.Connect.docx)
 week.  Thanks so much!

**Comment by marionbarker** [comment]
Creating an issue is typically reserved for problems with the code. This sounds like it’s a problem with your Apple configuration. You will get much faster response if you post something in Zulip chat or on Facebook.

Have you signed your new Apple developers agreement. Have you asserted that you are a non-trader. I will drop a few links to LoopDocs for these items. Can you make sure that you are listed as a TestFlight tester for your app.

If you’ve done all the typical reboot the phone, quit and restart TestFlight and nothing seems to help, then I would suggest you call Apple for assistance.

Please close this issue. We can continue the conversation even after you close it. But that lets the developers know that this is not an issue with the code that needs to be addressed.

links that may help
* https://loopkit.github.io/loopdocs/browser/bb-update/#accept-agreements
* https://loopkit.github.io/loopdocs/browser/prepare-app/#digital-service-act-compliance
* https://loopkit.github.io/loopdocs/browser/tf-users/#configure-testflight-group-for-the-app

**Comment by KristinHagins** [comment]
Thanks - closing to find another method of communication.
