### ISSUE TITLE
sporadic app crash after bolus/carb

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#233]
Sometimes after the bolus wizard completes and after the pump is sent the bolus command, pump delivers bolus, the app crashes and returns to the home screen.  The last time i entered a carb entry while below range without a bolus and it crashed too.

**Comment by walker0** [comment]
I have seen this happen too. Unsure about the conditions and haven't been near a computer to grab Xcode logs.

**Comment by CrushingT1D** [comment]
@beached have you made any modifications to the code regarding "below range" you mention above?

**Comment by beached** [comment]
I have not.

**Comment by CrushingT1D** [comment]
I got this bug today. May have been related to carb store. I do not have version referenced by the pull request above so may be mute

**Comment by ps2** [comment]
This one has been fixed
