### ISSUE TITLE
balance of historical data vs prediction is off

### ISSUE THREAD

**Issue by tomasboudr** [LoopKit/Loop#237]
Context: _On an iPhone 6. Nearly always rotation locked to vertical._

Its 5:06pm and I'm seeing only 2 hrs of historical data (3pm to just past 5pm) and 5-11pm for prediction. Is there any way to configure or move that inflection point way over to the right? That much prediction isn't accurate in my mind as 6 hours later I could have taken or not taken insulin and had its effect completely wear off as well. I would advocate for much less prediction (maybe 1-2 hours max) and a lot more historical data be displayed in the 8 hour window of the CGM graph. 

Another case this matters is when I wake up in the morning. I would love to be able to see the night and what my CGM data was and see the corresponding corrections Loop Made to basal, but I can't really see that due to the display. 

I feel like in older versions of Loop this was different and this was shifted in a recent release. I would advocate for shifting it back. 

Thanks for reading my diatribe. All this said, this is amazing technology and I run my life on it! I'm forever in debt to the community.

**Comment by walker0** [comment]
You can adjust this by adding a multiplier to the end of this line. https://github.com/LoopKit/Loop/blob/master/Loop/View%20Controllers/StatusTableViewController.swift#L141

You could also change if it shows the full DIA into the future by adjusting line 142. IF you adjust your DIA the amount of history showing will change with that due to change in the length of prediction.

**Comment by tomasboudr** [comment]
That solves it. 
In StatusTablesViewController.swift line 14 & 142 I added a *1.2 to the end. and set a 1 hour future only Rather than 4 hours or the insulin duration

let totalHours = floor(Double(availableWidth / minimumSegmentWidth)) * 1.2
let historyHours = totalHours - TimeInterval(hours: 1).hours
