### ISSUE TITLE
carb/basal/sensitivity values on settings page are confusing

### ISSUE THREAD

**Issue by sjolundjohn** [LoopKit/Loop#246]
When entering the main settings page, you are shown options to adjust your basal rates, carb ratios, insulin sensitivities etc. If you click into the option, you configure the values. For the purpose of this ticket I will focus only on **carb ratios**

For carb ratios, in settings, it shows 9.44 g/U. See highlight in image below:

If you go into the carb ratios option, you will see that I have x3 ratios set, none of which are 9.44 g/U. The average of these ratios numerically is also not equal. My presumption is that 9.44 u/H is the average over a 24h period?

I find the way that this is displayed to be confusing and not intuitive.

Ideally, on the settings screen I would like the currently active carb/insulin sensitivity/etc value to be shown. If this is not possible then perhaps the first value in the list?

![main_settings](https://cloud.githubusercontent.com/assets/17986135/19965005/3bbb2dbe-a1c5-11e6-9b61-ab1607fc766b.png)

Carb ratio in main settings screen and carb ratio settings page do not match

![carb ratios](https://cloud.githubusercontent.com/assets/17986135/19964918/b8987676-a1c4-11e6-8350-804ca45c4b3e.PNG)

**Comment by ps2** [comment]
Yes, sensitivities and carb ratios lines show a daily average.  Basal rates show daily total. I can see how it's not obvious what is being displayed. 

Displaying the daily total of basal rates is a useful figure to have computed for you and displayed there, so I don't think we'd want to change that one.

As for the daily averages on carb ratios and sensitivities, those are statistics that might also be useful. Might not be. I could see switching it to show the current value, but that's redundant with the actual schedule.

**Comment by sjolundjohn** [comment]
Hi,

I agree that total basal rate is smart (label is basal rates so maybe 'basal profile' may be better, but this is really nitpicking.

I haven't found why one would want daily averages for others, but that doesn't mean others would.

Very low priority task, but confuses me each time as the numbers look off, so wan't to provide the feedback.

Feel free to close.

**Comment by Kdisimone** [comment]
Closing...adding clarifications to the Loop Docs to explain the displayed values.
