### ISSUE TITLE
Add an indicator for an ongoing Bolus

### ISSUE THREAD

**Issue by trixing** [LoopKit/Loop#255]
The main state view should have an indication that a Bolus is in progress.  Currently after hitting "Delivery" the screen disappears and there is no visual confirmation that a Bolus is running.  It would be great to have a bar appear similar to the "recommend basal rate" bar indicating that it is in progress.

**Comment by ps2** [comment]
Related to #273 and #131

**Comment by Kdisimone** [comment]
There is a "Starting Bolus" indicator now  https://github.com/LoopKit/Loop/pull/584
