### ISSUE TITLE
Potential bug in updatePredictedGlucoseAndRecommendedBasal

### ISSUE THREAD

**Issue by trixing** [LoopKit/Loop#260]
In https://github.com/LoopKit/Loop/blob/master/Loop/Managers/LoopDataManager.swift#L542

Either a bug or I don't understand why we do first

        self.predictedGlucose = retrospectiveCorrectionEnabled ? predictionWithRetrospectiveEffect : prediction

but then unconditionally a few lines later

            let tempBasal = DoseMath.recommendTempBasalFromPredictedGlucose(predictionWithRetrospectiveEffect,

doesn't that let us to always recommend the bolus with retrospective effect?  What the magic I'm missing?

**Comment by ps2** [comment]
Thanks!  Yes, this appears to be a serious error.  For tempBasal, not bolus.  I will get a fix submitted soon.
