### ISSUE TITLE
Hi not sure why my loop is still grey. new to this ??

### ISSUE THREAD

**Issue by eugina32** [LoopKit/Loop#264]
[Text File 3.txt](https://github.com/LoopKit/Loop/files/599274/Text.File.3.txt)

**Comment by loudnate** [comment]
You need to enter a pump ID.

**Comment by eugina32** [comment]
Hi even if I'm not setting the pump up yet? I want to use it open loop until I get the required pump
Thank you

**Comment by ps2** [comment]
Loop needs to access the pump to have an idea of insulin on board.  Without that, it cannot do its forecast and recommendations.

**Comment by eugina32** [comment]
ok it won't connect to my pump because it animas vibe so this won't work until i source a medtronic from the states then? so then i can use open loop first? and then after a period of time i can start to close? sorry all very new to this and just average with computers..thanks again

**Comment by scottleibrand** [comment]
There is a feature request open to support open loop mode without a pump: https://github.com/LoopKit/Loop/issues/257 but it hasn't been implemented yet, and AFAIK no one has decided to work on it yet. You might want to comment on that issue with a summary of your use case if you think it would be helpful.

**Comment by scottleibrand** [comment]
Another option, if you can get an Android phone, would be HAPP, which is designed to run in open loop mode.

**Comment by eugina32** [comment]
thank you tried to set up HAPP with an android but the phone was having problems finding her g5 ...tried like ten times the bluetooth could not seem to see it, it was android 6 but didn't want to spend 600 eu on a galaxy as wasn't sure that it would work  . we r all on  iphones and it seemed easier to set up this way..so not sure which way to go now!!... ordered the rileylink ..now must see if i can source a pump.. thank you for the help
