### ISSUE TITLE
Loop Pill in NS not showing data unless recently enacted

### ISSUE THREAD

**Issue by ddaniels1** [LoopKit/Loop#266]
Since the V 1.1 upgrade which allows carbs to show up in NS (very useful for parents of small kids who are at work!) the IOB, COB and other data that normal shows up when you hover over the "Loop" Pill doesn't show up unless the loop was just enacted. 

Any ideas? iS this a NS issue? used to work whether recently enacted or not.  Since IOB pill on NS does not account for temp basals positive or negative impact on true iob this would be useful to have this back, or even better, separate pills for total iob and bolus iob.

**Comment by ps2** [comment]
The IOB pill on NS *does* account for basals. There was a bug fix just yesterday applied, so make sure you have the latest dev version.
