### ISSUE TITLE
Red circle not resolving

### ISSUE THREAD

**Issue by bherrick71** [LoopKit/Loop#268]
Hey,

Been on this a few days, and having a recurring issue. Sometimes I get the red circle even though everything is hooked up in range, and I can't seem to get it to work again. Any idea how to resolve this?

**Comment by eszcloud** [comment]
Gitter is the place to work on problems like this:  https://gitter.im/LoopKit/Loop.

To get you started troubleshooting: What does "hooked up in range" mean? Is Loop currently able to interact with the pump and get recent cgm info? 

Is the time below the current relative basal rate icon at the top recent? Have you checked if the cgm time shown in Loop is updating and recent? Can you get the model number for the pump and download recent history? Have you tried tuning?

**Comment by bherrick71** [comment]
Sorry--answering your questions then moving it over to Glitter.

Yes, Loop is currently able to interact with the pump. The basal rate icon is often not recent. It was 2 hours old up until a few minutes ago. The CGM time is current. I have tuned, and the pump is a medtronic paradigm.

Basically, sometimes it connects and works and sometimes it doesn't.

**Comment by ps2** [comment]
@bherrick71 I agree it's best to try gitter first for these.  Did you manage to figure it out?  If not, you can generate an 'Issue Report' from the Loop Settings menu, and attach it here.

**Comment by CrushingT1D** [comment]
We should probably just close this one.
