### ISSUE TITLE
 loop translation (ITA)

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#269]
Good morning, I wanted to share the file that you can import into xcode to translate
[it.xliff.zip](https://github.com/LoopKit/Loop/files/603047/it.xliff.zip)

**Comment by francescaneri** [comment]
@ps2 @loudnate  @jlucasvt @CrushingT1D you may concern?

**Comment by francescaneri** [comment]
<img width="1280" alt="schermata 2016-11-21 alle 11 20 05" src="https://cloud.githubusercontent.com/assets/9915825/20478981/aa64a608-afdc-11e6-9616-5e7d60afaffd.png">

**Comment by francescaneri** [comment]
<img width="1280" alt="schermata 2016-11-21 alle 11 23 16" src="https://cloud.githubusercontent.com/assets/9915825/20479050/03092a0e-afdd-11e6-9694-8ba01622b978.png">

**Comment by CrushingT1D** [comment]
This one can be closed

**Comment by ps2** [comment]
Tickets are closed when the feature/fix lands in an actual release. Github will automatically close this one, since it's linked to a PR.
