### ISSUE TITLE
workout - 15 minutes - 30 minutes

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#271]
I wanted to add 15 minutes and 30 minutes to this screen for my daughter because 1 hour is really too much. Where can I find the code to correct it? Thanks Matteo
![image](https://cloud.githubusercontent.com/assets/9915825/20481088/bc1d90fe-afe5-11e6-9b58-2521d924d2e8.png)

**Comment by loudnate** [comment]
Matteo,

That code can be found here: https://github.com/LoopKit/Loop/blob/master/Loop/Extensions/UIAlertController.swift

It would be great if you could commit your Italian strings to the codebase for others to benefit! Are you familiar with internationalizing a Cocoa project?

**Comment by loudnate** [comment]
Nevermind, I see you already attached an xliff file! Thank you very much for this wonderful contribution.
