### ISSUE TITLE
Create a lock screen widget to show basic info

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#276]
I've done some basic research on this and it looks like it should be relatively straightforward to create a "Today Extension" that shows basic glucose, IOB, COB info on the iOS lock screen. Creating this issue as a way to track and collaborate any work on this project. I plan to work on this in the near term (but we'll see how that goes).

**Comment by elnjensen** [comment]
I think this is a great idea; I had thought of it before but didn't follow through.  I think something similar to the HUD (top row of icons) in Loop could work well.  Maybe even some of that code could be reused?

Actually maybe the first three icons (loop symbol, BG + trend, current temp rate) and then replace next two with IOB and COB?  Reservoir and battery status aren't as important for quick look. 

What were you thinking of @bharat?

**Comment by bharat** [comment]
For me, the current BG and the graph are the most useful - but I'm open to ideas here.

**Comment by elnjensen** [comment]
I'm ałready using the lock screen widget from the Dexcom G5 app, and those are the two things it shows already, graph and current BG: https://www.dexcom.com/g5-app-update   I guess G4 users wouldn't have those, so this could replace that. But coming from G5, it would add more value if it also included some basic Loop info.

**Comment by bharat** [comment]
Ok - I've got a basic version of this up and running. Right now it only shows the current blood glucose, but it should be relatively easy to add the rest now that I've got the plumbing in place.

Code is here:
https://github.com/bharat/Loop/tree/lock-screen-widget

Currently looks like this:
![Uploading Screen Shot 2016-11-25 at 7.12.16 PM.png…]()

More to come...

**Comment by elnjensen** [comment]
Excellent!  Let me know if you want me to test something at any point.  Thanks for your work on this.

**Comment by bharat** [comment]
Ok - I have all the plumbing in now for the HUD. I'm going to test it out with different units (thus far only been playing with mg/DL) then submit a PR and let somebody pick through it and tell me what to change :-)

Feel free to play with https://github.com/bharat/Loop/tree/lock-screen-widget if you'd like to try it on your iPhone..

![screen shot 2016-11-26 at 5 13 13 pm](https://cloud.githubusercontent.com/assets/54570/20644854/b4726cc0-b3fb-11e6-832c-e128c3d19015.png)

**Comment by loudnate** [comment]
This is wonderful, thank you!

I would recommend at some point that you refactor the HUD (and maybe chart) views into an iOS framework, rather than duplicate them between targets. 

The logical next step from here is to render some/all of this content in a Notification Content Provider, which would be a third target.

**Comment by bharat** [comment]
Agreed - I think there's a lot of cleanup that likely needs to happen. I think that this is roughly ready to go. I've submitted a pull request. Happy to make whatever changes you'd like to get this ready to go.

**Comment by jmatheson** [comment]
Is this and and other related issues closable?

**Comment by ps2** [comment]
I'll let @bharat close this if he's happy where it's at.  Thanks again @bharat!

**Comment by elnjensen** [comment]
Reading through some old issues and wondering whether this one could be closed.   @bharat  What do you think?

**Comment by bharat** [comment]
yup, I think this one is ready to close. thanks for the reminder!
