### ISSUE TITLE
Add safeguard to prevent Loop from accepting mmol target without a decimal

### ISSUE THREAD

**Issue by ELUTE** [LoopKit/Loop#279]
We have seen a situation where a user accidentally entered 55 instead of 5.5 as their target BG. This resulted in no basal being given for 4 hours. User error but it would be great if there was a safeguard against this or a pop up that asks you to confirm the change so that this doesn't happen to someone else.

**Comment by nightscout4pie** [comment]
#1

**Comment by nightscout4pie** [comment]
+1

**Comment by elnjensen** [comment]
What do you think would be a good range to warn on?  Could warn for "odd" values regardless of units.  Maybe warn if less than 80 mg/dl  , 4.4 mmol/l?

Not sure how the preferences interface works, but it may or may not be possible to explicitly check for the presence of a decimal point  - plus allowing for different languages/localizations, the character could be different.  So just a threshold might work.

**Comment by ELUTE** [comment]
I am not sure how it works either... but under 80 might not work if you were trying to set your target to something like 6.0 to 8.0 and set it to 6.0 to 80 accidentally instead.

**Comment by trixing** [comment]
You can explicitly check the preferred units in the code without using heuristics (glucoseStore.preferredUnit).  I'd agree that the target should never be allowed under 80 or the mmol equivalent without hacking the code.

**Comment by elnjensen** [comment]
So following @trixing's point above, and taking @ELUTE's example, it could make sense to set both upper and lower limits for checking.  We know what units the user has specified, so we can accurately interpret the value in those units and check against the appropriate threshold value.  So we could check at the top end for a high upper limit of more than, say 300 mg/dl or 16.7 mmol/l.  Not sure what exactly the right value is, but if the main goal is to ward off this factor-of-ten error from missing the decimal point, they could be pretty wide.
