### ISSUE TITLE
Loop app has a dependency on WatchApp Extension/Model/GlucoseTrend 

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#280]
Seems slightly off to me to have the main Loop app have a dep on the WatchApp Extension. Am I missing something? Should we move that model into Loop/Models?

**Comment by loudnate** [comment]
Because the code is shared between platforms, it has to be linked to both targets. You're issue here is merely one of directory placement, not actually dependency relationships, and I'm sure a PR would be accepted.

**Comment by bharat** [comment]
resolved.

**Comment by ps2** [comment]
Just FYI, github will automatically close tickets like this when their linked PRs are merged into master.

**Comment by bharat** [comment]
ah, thanks for the tip.
