### ISSUE TITLE
Graph time shows am/pm when phone uses 24H regional settings

### ISSUE THREAD

**Issue by danibjor** [LoopKit/Loop#294]
top bar shows 24H time format tough

**Comment by Kdisimone** [comment]
I'm not certain when this issue was resolved, but v1.5.1 shows graph times in 24H now...so issue has been resolved.
![img_f59b31754c5a-1](https://user-images.githubusercontent.com/12402160/34451488-3105e770-ecdc-11e7-9a74-6f3ccb023960.jpeg)
