### ISSUE TITLE
Missing localizability warning

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#295]
I'm seeing the following warning:
![screen shot 2016-12-01 at 4 39 22 pm](https://cloud.githubusercontent.com/assets/54570/20818770/c038a14a-b7e4-11e6-95db-d762c41d10df.png)

Here's the suggested fix:
![screen shot 2016-12-01 at 4 38 17 pm](https://cloud.githubusercontent.com/assets/54570/20818761/a4e1aa22-b7e4-11e6-810d-2d1a313b0019.png)

I'm going to apply the fix and submit a PR for it.

**Comment by Kdisimone** [comment]
@bharat i think this can be closed now, correct?
