### ISSUE TITLE
Honor pump max basal rate

### ISSUE THREAD

**Issue by scottleibrand** [LoopKit/Loop#30]
If the pump has a maximum basal rate that is lower than what is configured in the app, the loop will silently fail.  Loop should probably query the pump's max basal rate and use that if it's lower than what the user configured (and maybe warn).

**Comment by loudnate** [comment]
I'm not sure I want to make users pay the penalty of re-checking max basal each time. The larger feature request here is the ability to sync settings from the pump. I haven't thought through what the right UX should be for that.

**Comment by scottleibrand** [comment]
Maybe just check max basal if you get a received: false on a temp basal enact?  Also maybe check pump status and provide some indication if temps are failing because the pump is suspended or bolusing...

**Comment by Kdisimone** [comment]
with Loop v1.9, max delivery rates are read from pump and synced.
