### ISSUE TITLE
Travis using out-of-date version of Swift

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#301]
Example build:
  https://travis-ci.org/LoopKit/Loop/builds/180501249

Example error:

> ❌  /Users/travis/build/LoopKit/Loop/Loop/Managers/DoseMath.swift:11:8: module compiled with Swift 3.0.1 cannot be imported in Swift 3.0: /Users/travis/build/LoopKit/Loop/Carthage/Build/iOS/InsulinKit.framework/Modules/InsulinKit.swiftmodule/x86_64.swiftmodule

**Comment by Kdisimone** [comment]
resolved
