### ISSUE TITLE
Time Set Bug

### ISSUE THREAD

**Issue by sjolundjohn** [LoopKit/Loop#304]
Earlier today I set the time on the pump with the RL, despite the clock being updated and ok already. I was trying to troubleshoot a problem.

This, I believe, caused a issue in which Loop was not able to pull any history from the pump. I kept getting "unknownEventType (23)" when I tried to get history.

After the problem being flagged in Gitter, I manually changed time on the pump to the wrong time, then updated again via RL. Problem solved.

Potential bug in which you updated the pump time, via RL, when the time is correct, and it stops Loop from funtioning.

**Comment by ps2** [comment]
This is an issue in the RL frameworks. It is being worked here: https://github.com/ps2/rileylink_ios/pull/286

**Comment by beached** [comment]
https://github.com/ps2/rileylink_ios/pull/287
