### ISSUE TITLE
Crash in dev when using mmol/L

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#311]
When mmol/L units are selected as the default unit for blood glucose measurements in HealthKit, loop crashes on startup.

**Comment by ps2** [comment]
@bharat It looks like we can't construct a mmol/L HKUnit. 

http://stackoverflow.com/questions/30177741/how-do-i-construct-a-healthkit-hkunit-for-mmol-l-millimoles-per-liter-for-bloo

We do have a helper for constructing this unit: https://github.com/LoopKit/LoopKit/blob/master/LoopKit/HKUnit.swift#L17

I'm not entirely sure how this used to work; it looks like the unit was passed in to these functions, before, and now it's a string passed in.

**Comment by bharat** [comment]
I have an idea what's going on here. Will work on it today (have a window in a couple of hours)

**Comment by bharat** [comment]
I've reproduced the issue - working on a fix now.

**Comment by danibjor** [comment]
Great!
