### ISSUE TITLE
Wrong carb entry causes Loop to hang

### ISSUE THREAD

**Issue by kajanilssen** [LoopKit/Loop#312]
If a user enters carbs, and then decided to edit carb hours there is a possibility that Loop hangs. 

Example: User enters 10 g of carbs with 180 minutes absorption time, and then decides to change this to 240 by edit manually the number is added to the existing number if the user doesn't delete the previous number. This will then be saved as "180240" absorption time. After save, Loop seems to work fine, but the long absorption time will cause Loop to hang - not communicating with Rileylink, no new BG number is captures, and the phone is slow. After 20 minutes the user will get a Loop has failed warning. Restarting the app makes the GUI strange - the graphs and Nightscout is strange due to that Loop has calculated numbers far into the future it seems. 

Even if the user noticed that the number was wrongly saved, Loop seems to lock up if the user changes absorption time back to 240. Have to force close Loop and restart.

Solution: There should be a max number for carbs absorption time (for example 999).

![img_0068](https://cloud.githubusercontent.com/assets/20521653/21080007/2ff1d10c-bfa4-11e6-9542-0bfb4f232daf.PNG)
![img_0066](https://cloud.githubusercontent.com/assets/20521653/21080009/33c457b4-bfa4-11e6-856e-470838627ce0.PNG)
![img_0067](https://cloud.githubusercontent.com/assets/20521653/21080010/38dfe0ce-bfa4-11e6-9302-67ce983a58f4.PNG)
![looperror1](https://cloud.githubusercontent.com/assets/20521653/21080011/3b43a7b0-bfa4-11e6-8119-0b188c014a64.png)

**Comment by christerjensen** [comment]
Sorry - reported with wrong user (a user I helped solve Nightscout problem yesterday).

**Comment by walker0** [comment]
I have seen this before and experienced the same symptoms. It doesn't seem to crash with only 3 characters in my testing so I think we should limit the text field to 3 characters.  This provides 16.65 hours of possible carb absorption (should be more than long enough for everyone).
