### ISSUE TITLE
Improve the Status Widget to update in real time as Loop data changes

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#320]
Currently, the status widget only updates when it first appears. It should continue to update in real time as the Loop app detects changes and makes adjustments.

**Comment by bharat** [comment]
Looks like this might be non-trivial:
1. http://stackoverflow.com/questions/28736506/kvo-with-shared-nsuserdefaults-in-swift
1. http://www.atomicbird.com/blog/sharing-with-app-extensions

MMWormhole might work for us:
https://github.com/mutualmobile/MMWormhole

Pulling in a new framework for this seems heavy. Alternatively, it might just be easiest to have the extension poll every minute. It's not like the data changes that quickly.

**Comment by ps2** [comment]
Could you update the description to describe the issue being solved?

**Comment by bharat** [comment]
done. lmk if it needs more clarity.

**Comment by ps2** [comment]
So this is only an issue if you keep the status screen up for a while.  Each time you bring it up it's is still refreshing correctly?

**Comment by bharat** [comment]
That is correct. So IMO it's not a critical issue, but if you happen to stay on the status screen for a while you might be looking at expired data. For what it's worth, it also shows the timestamps for all readings so you'd at least have a visual way of knowing that it's out of date, but date stamps are subtle.

**Comment by marionbarker** [comment]
I can't make the widget stay up long enough to test this.  It does refresh each time I call it up.
Can this issue be closed?
