### ISSUE TITLE
Status widget - make the background transparent (similar to other widgets)

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#322]

**Comment by bharat** [comment]
This was a request from @loudnate. Seems reasonable, but I think we'll have to adjust the colors a bit. If I just take the simple approach of making all views use the clear background color, we get this:

![screen shot 2016-12-22 at 4 45 07 pm](https://cloud.githubusercontent.com/assets/54570/21444758/096a35f4-c866-11e6-9ee1-8c022cd7b095.png)

The code for that is here: https://github.com/bharat/Loop/tree/transparent-widget

Here's a (perishable) compare link:
https://github.com/LoopKit/Loop/compare/dev...bharat:transparent-widget?expand=1

a) do we want to continue down that path and
b) who wants to choose the right colors?

**Comment by Kdisimone** [comment]
Transparent background has been implemented.  closing issue.
