### ISSUE TITLE
Status widget - show the glucose prediction graph on request

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#323]
Mimic the Dexcom widget's feature - they have a [More...] link in the title bar of the widget. When you tap that, the widget expands and shows a data graph.

**Comment by elnjensen** [comment]
Looks like this could be closed?  (Just noticed when scanning through old issues.)

**Comment by Kdisimone** [comment]
Yup, done in v 1.3.1  https://github.com/LoopKit/Loop/pull/442
