### ISSUE TITLE
Status widget - "eventually" text has more precision than the app in mg/dL

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#324]
The app says:
"Eventually 98 mg/dL"

The extension says:
"Eventually 97.6 mg/dL"

which is right? I'm assuming the app is. Either way, consistency is good here.

**Comment by bharat** [comment]
I can no longer reproduce this issue. I believe it was fixed in 5838f6d7136bfcede0f69c092ee5e2b576e15510

**Comment by bharat** [comment]
I reproduced the issue. Here's what's happening.

In the Loop App the eventual glucose description string is set by:
1. taking the last point in the predicted glucose array
1. using the [ChartAxisValueDoubleUnit description function](https://github.com/LoopKit/Loop/blob/dev/Loop/Models/ChartAxisValueDoubleUnit.swift#L29) to turn it into a string which relies on
1. ChartAxisValueDouble using the integerFormatter defined [in StatusChartManager](https://github.com/LoopKit/Loop/blob/dev/Loop/Managers/StatusChartManager.swift#L57)

So the result appears to always be an integer. This in and of itself is likely a bug in the experience for mmol/L users who would want to see one decimal place.

In the Loop Status Extension, the eventual glucose description is set by:
1. taking the preferred unit from the context
1. using NumberFormatter.glucoseFormatter, [called here](https://github.com/LoopKit/Loop/blob/dev/Loop%20Status%20Extension/StatusViewController.swift#L87) and [defined here](https://github.com/LoopKit/Loop/blob/dev/Loop/Extensions/NSNumberFormatter.swift#L14)

... this formatter does not define a maximum number of fraction digits.

My sense is that the way that the Loop Status Extension is doing it is more correct in general, since relying on the status chart's internal representation to calculate the "eventual glucose" value seems inappropriate.

I think the right approach is probably to:
1. Add a `preferredMaximumFractionDigits` to [the LoopKit/HKUnit extension](https://github.com/LoopKit/LoopKit/blob/master/LoopKit/HKUnit.swift)
1. Use the min and max fraction digits in [the Loop/NSNumberFormatter extension](https://github.com/LoopKit/Loop/blob/dev/Loop/Extensions/NSNumberFormatter.swift#L14)
1. use `NumberFormatter.glucoseFormatter(for: <preferred unit>)` in both places

Thoughts?

**Comment by apabari** [comment]
Has this one been addressed?  I haven't tried to reproduce it as of yet.  Just seeking to understand if this issue should be marked as closed or not.

Thanks!

**Comment by Kdisimone** [comment]
addressed and closed
