### ISSUE TITLE
Battery level missing from widget

### ISSUE THREAD

**Issue by alternateal** [LoopKit/Loop#325]
1.2.0 looks to have some consistency issues  between the app and the widget - see attached photos 
![img_3137](https://cloud.githubusercontent.com/assets/17626700/21157835/cfbe6db0-c172-11e6-898b-c66b4b281263.PNG)
![img_3138](https://cloud.githubusercontent.com/assets/17626700/21157837/cff4173a-c172-11e6-8d5e-60d80af93d79.PNG)
![img_3139](https://cloud.githubusercontent.com/assets/17626700/21157836/cff4340e-c172-11e6-9e78-bd987aab9c45.PNG)

Battery needs to show on widget and app needs to show same precision as the widget for the "eventually" mmol/L levels.

**Comment by bharat** [comment]
@alternateal: The "eventually" text is covered in #324. Can you rename this issue to something along the lines of "Battery level missing from widget" please?

**Comment by wkcwells** [comment]
Pull request #342 fixes this for x22 pumps, and has been merged.  If this report is specific to x22 pumps, this issue can be closed.

**Comment by alternateal** [comment]
Closed by pull request #342

**Comment by loudnate** [comment]
Please leave issues open until they are merged to master (and subsequently released to users)

**Comment by wkcwells** [comment]
Nate, thanks for keeping us on process.
