### ISSUE TITLE
Calculator function on carb entry screen

### ISSUE THREAD

**Issue by jenm999** [LoopKit/Loop#332]
VERY LOW PRIORITY but maybe easy to do? On the carb entry screen of the t:slim is a + so that you can add up carbs during entry while mentally scanning the components of a meal prior to bolus.

**Comment by Kdisimone** [comment]
this is handled by being able to enter multiple carb portions prior to bolusing.  You can save a carb entry, choose not to give the bolus, and make additional carb entries as needed.  This also allows you to group/separate the carb absorption times of the foods in a given meal effectively, allowing Loop to consider all carb entries/absorptions prior to recommending a bolus.  https://loopkit.github.io/loopdocs/operation/features/carbs/#mixed-carb-meals
