### ISSUE TITLE
Loop failure alert category

### ISSUE THREAD

**Issue by jenm999** [LoopKit/Loop#333]
This might be a Nightscout issue and not a Loop issue. Nightscout distinguishes between ALERTS and ALARMS. Alerts include changes to temp rate, etc. Alarms include highs/lows and "Loop is not looping" and failed bolus. Unfortunately with a child who does not pre-bolus we get high/low alarms rather frequently, and already have alarms set up for that which means we are getting some alarms via Pushover AND Nightscout and the more critical alarms get missed. Would be great for there to be a separate alert category just for loop-related alarms that we could enable in Pushover.

**Comment by Kdisimone** [comment]
Indeed, this is a NS issue.  You can file an issue/enhancement request over in the cgm-remote-monitor repo on Github if you'd still like to pursue this suggestion.  Thanks!
