### ISSUE TITLE
Meal/Bolus fail

### ISSUE THREAD

**Issue by danibjor** [LoopKit/Loop#345]
We have several fails when it comes to entering meals. What I think is the common problem here is that the rileylink is busy fetching glucose readings from the pump, thus the pump/rileylink is busy doing other stuff and fails to give meal bolus. 
When I have checked the phone after a failed delivery, there look to be a pattern where it is about 5 minutes since the last reading (thus suspecting the rileylink is busy working with glucose fetching). Waiting a bit, deleting and re-entering the meal and pushing the suggested meal bolus usually works every time.

**Comment by christerjensen** [comment]
We also suspected this (wrote my theory in the Gitter channel), but Pete says that all commands through Loop is queued.

I do however notice that the fails happen when there already is communication between Rileylink and the pump (my old version of Rileylink has blue LED lights indicating communication). They seems to happen randomly, not very often. I've tried bolusing when there is communication and most go thorough.

**Comment by ps2** [comment]
Could you capture xcode logs of this happening?  Capturing the actual error from the RL when trying to bolus may help identify if there is an issue here.  All interactions with the RL are broken up into 'sessions', and only one session can interact with the RL at a time.  Sessions are groups of commands and responses that are built up into larger tasks like "fetch history" , or "issue bolus".

**Comment by christerjensen** [comment]
I only have a Mac Mini a bit away from where we eat, but I will try and provoke and error - it will probably take a while unfortunately. I noticed that it usually happened when Loop was 4 mins initially.

**Comment by Kdisimone** [comment]
@danibjor has this issue resolved for you?  Can I close this issue?

**Comment by Kdisimone** [comment]
Closing as issue has not been reported by others since the original posting, nor does it appear to be an ongoing issue for original poster based on lack of response.  If this needs to be reopened, please let me know

**Comment by dananitulescu** [comment]
I have problems delivering the bolus. The app tells me "Starting bolus" and after that "Delivering 4U failed, it's safe to retry." Pls help

**Comment by Ancandune** [comment]
> I have problems delivering the bolus. The app tells me "Starting bolus" and after that "Delivering 4U failed, it's safe to retry." Pls help

When I see this, moving the Rileylink closer to my omnipod always fixes the problem.
