### ISSUE TITLE
Lag in carb entry

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#357]
On dev, entered carbs are sometimes not showing up in the graph after entry.

**Comment by Ralfenator** [comment]
Need help, struggling with timing of bolus for carbs on Loop. Previously the bolus screen would pop up instantaneously when carbs were entered and insulin was needed. Now it can take up to 5min or more to figure out he needs insulin based on carb entry. Why are active carbs 0g, with graph clearly showing the 25g entry? No insulin suggested with projected BG of 234? What am I missing?

Pic1: Loop is green, no CoB and no IoB
Pic2: Entered 25g carbs. The insulin bolus suggestion did NOT pop up. Carb graph shows the increase in carbs, but “active carbs” number is at 0g.
Pic3: Entry of 25g in log
Pic4: 2 min later. Graph shows 25g, “active carbs” is 0g, and “projected BG” is 234 mg/dL
Pic5: I check suggested bolus to see if any insulin is expected (typical insulin bolus needed for 25g is 1.25U). 0 and still 0g carbs on board, yet expected BG is 234.
Pic6: 4 min later, still no “active carbs”. Projected BG is 233 and no insulin expected.
Pic7: After 5 minutes, the carb activity finally goes to 25g. I check bolus and give insulin for expected BG of 233.
Pic8: After 6 min, finally “active carbs”, “active insulin” and “projected BG” make sense.

![pic 2](https://cloud.githubusercontent.com/assets/23038775/21617234/2a331afc-d1b3-11e6-8c09-7acd8917f5e3.jpg)
![pic 3](https://cloud.githubusercontent.com/assets/23038775/21617237/2a350b6e-d1b3-11e6-9360-731067353a4a.jpg)
![pic 4](https://cloud.githubusercontent.com/assets/23038775/21617235/2a33d546-d1b3-11e6-8daf-f08e3c7ad41d.jpg)
![pic 5](https://cloud.githubusercontent.com/assets/23038775/21617238/2a35e20a-d1b3-11e6-8bfd-fbaf107b5487.jpg)
![pic 6](https://cloud.githubusercontent.com/assets/23038775/21617236/2a348bf8-d1b3-11e6-818a-59d4723b50e6.jpg)
![pic 7](https://cloud.githubusercontent.com/assets/23038775/21617239/2a3aff10-d1b3-11e6-844a-75a204c16187.jpg)
![pic 8](https://cloud.githubusercontent.com/assets/23038775/21617240/2a3f7568-d1b3-11e6-8c38-01ba51da3694.jpg)
![pic 1](https://cloud.githubusercontent.com/assets/23038775/21617241/2a40b4be-d1b3-11e6-972f-6073be5c8fc3.jpg)

**Comment by Ralfenator** [comment]
sorry, pics no longer in order.

**Comment by loudestnoise** [comment]
Hi @Ralfenator you replied to an issue that @ps2 raised. In order to simplify, you would probably want to bring this up in the Gitter chatroom, but from first glance I would think the reason it's not suggesting a bolus is because at the time of carb entry your BG is below your target range. Loop only suggests a bolus when you're in range.

**Comment by ps2** [comment]
@loudestnoise I asked him to add his info here.  If you read through the details and look at the screenshots, you'll see it's not just the lack of the bolus screen popping up, but the graph not being updated as well.

**Comment by loudestnoise** [comment]
Whoops, sorry. Just trying to be helpful. Carry on!

**Comment by walker0** [comment]
@ps2  I don't see the issue on the screenshots. The carb entry was entered at 7:01 and the graph was correct at 7:02 with a COB of 0 changing to 25 at 7:05 as per delay time in loop?

**Comment by ps2** [comment]
Hmm, perhaps you're right about the delay causing the COB to show 0, but I don't recall that being the case before.  And the no bolus suggested is due to being below range.

**Comment by walker0** [comment]
I have a feeling that it has been that way for a while, I'm not 100% though.

**Comment by walker0** [comment]
I'd have no opposition to it showing instantly as long as future carbs displayed properly

**Comment by mddub** [comment]
The COB series is computed on an every-5-minutes schedule, and the "current COB" is the most recent entry in that series prior to right now. So if you enter carbs at 7:01, it will show the 7:00 value until 7:05, which can be a little misleading if you don't click in and see "at 7:00 AM". Would need to be fixed:
* [here in LoopKit][1]
* [here in Loop for Nightscout COB][2]

The [IOB calculation][3] uses the same logic.

[1]: https://github.com/LoopKit/LoopKit/blob/e8035f39c39c5a82ce7fb1bf93e13b7d5e3bad72/CarbKit/CarbStore.swift#L583-L587
[2]: https://github.com/LoopKit/Loop/blob/4637aba48f22a4b218af1bf49e009bb2cb3f4432/Loop/Managers/LoopDataManager.swift#L258
[3]: https://github.com/LoopKit/LoopKit/blob/391ef516f9573b25f6934598a24c37e69a723598/InsulinKit/DoseStore.swift#L873-L877

**Comment by Kdisimone** [comment]
Closing this issue as the cob appears to be correctly displaying based on timestamps.
