### ISSUE TITLE
Bolus reminder after back in range

### ISSUE THREAD

**Issue by jessiepusateri** [LoopKit/Loop#358]
Boluses for carbohydrates are (understandably) disabled when the glucose reading is below target. However, if, during this time, you enter in carbohydrates and then later forget to give the bolus when you arrive are back in range, Loop has to rely on increased basal rate alone to counteract these carbohydrates. I think it would be useful for Loop to remind you if you were low and returned to range that there are still carbs-on-board that you would have otherwise bolused for you had been in range.

Example:
You are 60 mg/dL.
You eat 30g. Had you been in range, you would have given 3 units.
You are not in range, so you give 0 units.
Once you become in range, Loop increases basals to counteract the remaining 20 carbs left in your system. (20g = 30g - the 10g were used to raise your blood sugars back to normal levels)
The max basal is not enough to counteract these carbohydrates and your blood sugar goes high.

**Comment by marionbarker** [comment]
This can be closed with Loop v2.2.5 which now makes Dosing Strategy = Automatic Bolus available as part of Loop master branch.
