### ISSUE TITLE
Status widget - tapping on widget does not open app except for tapping on mini icon

### ISSUE THREAD

**Issue by wkcwells** [LoopKit/Loop#360]
Related to/regression of PR #334.

Something fishy seems to be going on here since this was addressed by the above PR, but never worked for me.  (And I can't figure out anything that I could have done to break it.)  It works if you tap on the small Loop icon in the upper left of the widget, but that seems to be using some automatic functionality of widgets.

This code in `Loop/Extensions/NSBundle.swift` is always returning `nil` for me:

```
    private var mainAppBundleIdentifier: String? {
        return object(forInfoDictionaryKey: "MainAppBundleIdentifier") as? String
    }
```

**Comment by wkcwells** [comment]
I have a simple change that appears to fix this.  Will PR shortly.

**Comment by wkcwells** [comment]
Diff is here:
https://github.com/LoopKit/Loop/compare/dev...wkcwells:make-widget-tappable?expand=1

DM'd @bharat to take a look given.

**Comment by bharat** [comment]
That looks like the right fix to me. I know I committed that same change, but I suspect I committed it to the wrong branch (my deploy branch) and it didn't go into my PR. Good catch, @wkcwells!

**Comment by Kdisimone** [comment]
Closed, fix was merged.
