### ISSUE TITLE
Don't allow multiple CGM data sources to be active simultaneously

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#361]
Currently it's possible for you to enable the G4 and the G5 data sources concurrently. That's probably ok because who's going to slap a G4 and a G5 on their body? But we've got a change coming to add Enlite support in #349 which will complicate things.

Let's create a UI that allow the user to choose one and only one data source.

**Comment by bharat** [comment]
Ok, it looks like it should be relatively straightforward to do a refactoring of the settings to pull out a couple of new groups. One for the pump (since now the Pump ID and the new Pump battery type are a related set) and one for the CGM. It'd look like this:

![screen shot 2017-01-04 at 7 54 22 pm](https://cloud.githubusercontent.com/assets/54570/21668552/ca5beda6-d2b7-11e6-9f48-a791b33a4926.png)

We can then create rules for the CGM section such that:
1. G5 Transmitter cannot be enabled unless the G5 Transmitter ID is well formed
2. Only one of the CGM options can be enabled at any given time

This creates space for us to add future Enlite support.

**Comment by Kdisimone** [comment]
Resolved with https://github.com/LoopKit/Loop/pull/364 (plus new CGM manager work in current dev changes this selection as well)
