### ISSUE TITLE
Reduce the frequency of 'Pump Reservoir Empty' notifications

### ISSUE THREAD

**Issue by wkcwells** [LoopKit/Loop#362]
If the pump reservoir is empty, these notifications are issued with each run of the loop, which is every 5 minutes (I think).  That results in a lot of notifications.

I have a relatively minor change to reduce this interval, but as this could be a controversial change, would like to get some feedback on this idea in general, and also what the interval should be.

**Comment by wkcwells** [comment]
This could also be applied to the "Pump Battery Low" notifications

**Comment by wkcwells** [comment]
Current prototype implementation is a fixed 20 minute notification interval for both notifications.

**Comment by walker0** [comment]
I don't think it should be changed. Loop won't work in either of those states and If I'm asleep or have missed notifications I'd prefer to know and resolve the situation. You can always quit loop if you don't want to rectify the situation as I don't believe it will work properly anyway.

**Comment by wkcwells** [comment]
@walker0 thanks for your feedback.  The scenario where I ran into this was a half day meeting where it was not convenient to step out to change a set.  The pump and Loop can actually continue to work in both cases.  At "empty reservoir," there is generally some remaining insulin.  At Loop "low battery", there are still quite a few hours left before the pump itself alarms low battery and shuts off the radio (at least for the x22 pumps).   So I knew I was OK with waiting a few hours, and getting an alert every 5 minutes seemed excessive.

**Comment by walker0** [comment]
@wkcwells Ah, I hadn't thought about the new x22 low battery alert. I have a x23 and when the low battery alert comes in the comms stop and loop stops. So if i was getting a battery alert that was annoying me and I couldn't deal with right then I'd probably just quit the loop app. I can see the issue with the x22. I'm not sure how gracefully loop deals with using the insulin after the reservoir is empty, there used to be an issue with that. I think it may have been resolved though.

**Comment by kstdennis** [comment]
I'm on a x22 and the low battery issue is quite troubling. I'd really like to see options to disable the alert for low batt (and to keep this relevant) reservoir too.

**Comment by marionbarker** [comment]
Has this been addressed. Can this be closed?
