### ISSUE TITLE
RileyLink doesn't seem to hold charge for more than an hour or few, 5 days old RL

### ISSUE THREAD

**Issue by jlaes** [LoopKit/Loop#366]
@ps2 My RL doesn't seem to hold a charge in the battery. It's been going dead now everyday earlier and earlier. Today after being charged all night it turned off at around noon, then started working when I connected it to the charger. Then when we left out with my son, 1-1.5 hours later RL was dead again. Back home connected it to a charger and it connected right away and Loop was back on. This has been happening now for the 5th day in a row.

[jlaes-issue-report-text-3EDDF5139FC7-1.txt](https://github.com/LoopKit/Loop/files/694142/jlaes-issue-report-text-3EDDF5139FC7-1.txt)

**Comment by trixing** [comment]
Incidentally I have the same issue with one of my 2 RLs.  It is getting very hot at the IC next to the power switch.  You could try feel the backside if there is any hot spots on yours.

**Comment by ps2** [comment]
Issues with RileyLinks should be brought up in the RileyLink gitter or issues filed on the RileyLink github repo: https://github.com/ps2/rileylink
