### ISSUE TITLE
azure strings

### ISSUE THREAD

**Issue by mhersco2** [LoopKit/Loop#367]
Azure strings need to define the db. Which one should I activate: custom, mysql, sql server or sql database?
Thanks.
Michael

**Comment by walker0** [comment]
This is the current recommended way to set up nightscout for loop.  https://github.com/Kdisimone/Loop/blob/master/NewUserNS.pdf 
Generally people go over the azure usage limit after a short time.

**Comment by mherscloop** [comment]
Thanks. I have now switched to Heroku.

**Comment by walker0** [comment]
Great, In future questions related to set up are better asked on gitter.  https://gitter.im/LoopKit/Loop

**Comment by mherscloop** [comment]
Understood. Thanks. Michael
