### ISSUE TITLE
Status widget - display IOB in widget

### ISSUE THREAD

**Issue by wkcwells** [LoopKit/Loop#369]

**Comment by wkcwells** [comment]
Here is a prototype implementation:

![img_6574 png](https://cloud.githubusercontent.com/assets/10645450/22007379/14d949aa-dc27-11e6-9ee0-0a50992700ab.png)

**Comment by wkcwells** [comment]
The label "IOB" should be "Active Insulin" for consistency with the app.  But that will not fit with "Eventually..."  Alternatively, could have IOB display on a separate line.

**Comment by bharat** [comment]
I'm working on having a "Show more..." link which accordions out and shows a lot more info which can include IOB. Specifically, I like to see the graph which gives me much more interesting trend data. I think I'd prefer to tackle this more holistically than adding one-offs for bits of data. But I'm not the decision maker here :-)

**Comment by elnjensen** [comment]
I'd also vote in favor of showing IOB here - for me that is the key piece of decision-relevant information that isn't already shown on this screen, and there's a natural (IMO) spot for it, as @wkcwells shows in his example.   Thanks for considering it!

**Comment by elnjensen** [comment]
@wkcwells I've added a pull request (#635) that implements this.  Comments welcome.  @bharat   I followed the structure of your code as closely as I could, but there may be subtleties I missed.

**Comment by Kdisimone** [comment]
@elnjensen got it done  https://github.com/LoopKit/Loop/pull/442.  very nice and closing issue
