### ISSUE TITLE
Prescheduled Work Out Mode/Temporary Target (relates to #177 and #331)

### ISSUE THREAD

**Issue by msrcgm** [LoopKit/Loop#373]
Running into an issue where there is pre-scheduled work out situations (e.g., swim team every Monday and Wednesday at 3:30 p.m.).  It would be wonderful if Loop could allow for a prescheduled work out mode temporary target that could be pulled from Calendar or simply manually scheduled in the app.  Also relates to issue 177 and 331 regarding multiple temporary targets (eating soon mode, etc.).

**Comment by amazaheri** [comment]
I am working on some pull mechanism from NightScout same to OpenAPS to enable eating soon early stages that can be used for this purpose as well.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
