### ISSUE TITLE
Vertical scrolling also functions as horizontal swipe

### ISSUE THREAD

**Issue by danamlewis** [LoopKit/Loop#38]
When scrolling vertically in app (and even when specifically selecting a point to touch below the graphs), it acts as a horizontal swipe and selects data/scrolls horizontally on all three graphs. This shows what looks like erroneous data points selected on the graph when scrolling back to the top.

**Comment by alancmclean** [comment]
I find this large interaction area to be helpful since dragging on the graph area would obscure data.  If other people also felt this was a problem, perhaps the buffer below the time axis could be extended to provide a larger drag surface.

**Comment by ps2** [comment]
I *think* the interaction is working as designed. Perhaps I don't understand the issue. If that's the case, reopen the issue and maybe state the problem in 3 parts: 1) What you want to do. 2) What you see when you try to do it. 3) What you expect to see.
