### ISSUE TITLE
Compiling with 8.3 - Module Compiled with Swift 3.0.2 can't be imported into Swift 3.1

### ISSUE THREAD

**Issue by shanselman** [LoopKit/Loop#385]
This is meant to me more informative than anything. I'm learning, so forgive me if this is obvious.

I am running iOS beta 10.3 on my phone, and when I tried to compile Loop::dev I couldn't, because reasons.

I downloaded Xcode-beta and tried there and got "Module Compiled with Swift 3.0.2 can't be imported into Swift 3.1"

So I needed to:

```
scott@Scotts-Macbook-Pro:[Loop] (dev)$ xcrun swift -version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
scott@Scotts-Macbook-Pro:[Loop] (dev)$ sudo xcode-select -switch /Applications/Xcode
Xcode-beta.app/ Xcode.app/
scott@Scotts-Macbook-Pro:[Loop] (dev)$ xcrun swift -version
Apple Swift version 3.1 (swiftlang-802.0.36.2 clang-802.0.35)
Target: x86_64-apple-macosx10.9
scott@Scotts-Macbook-Pro:[Loop] (dev)$ carthage update
```
Then compile from there.

**Comment by Kdisimone** [comment]
I think a note in the wiki for this might be the best place to stash this info.  I'll add it there.
