### ISSUE TITLE
Double Bolus Entry

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#414]
It's possible to trigger the pump into recording the same bolus multiple times.  If, during a large delivery, an RF command triggers history events (like changing time), then the current state of delivery will be appended to the history, but the bolus will continue delivering.  At the end of delivery, the full bolus will be recorded.

Both records have the same timestamp, so it should be possible to filter these out by identifying boluses with identical timestamps  and selecting the largest one.

Need to review the code to see if we are not handling this case correctly.

**Comment by marionbarker** [comment]
This is a very old Issue and may have been addressed.  Can this be closed?
