### ISSUE TITLE
Dynamic carb absorption

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#430]
This has been discussed in gitter and other places. I'll summarize the general outline here for a more permanent record, and as a place to track progress.

Carb absorption varies considerably from person to person and from meal to meal. The model in loop allows for adjusting the absorption duration of a particular carb entry, but it's difficult to know ahead of time how some foods will absorb.  More complex absorption curves can be generated by entering multiple carb entries, but this is intensive work and difficult to get right as well.

By running a retrospective forecast and comparing it to actual observed BG, we can have deviation term that can be used to update inputs to the model, such as CA, ISF, DIA, etc.  The assignment of deviation in the period immediately following carb entry, would more strongly map to carb absorption and CSF.  The assignment also needs to be distributed amongst multiple carb entries.

**Comment by ddaniels1** [comment]
How is this coming?  I think this could be a big breakthrough for loop, especially for young kids

**Comment by BeckyNelson** [comment]
Or those with GP

**Comment by amazaheri** [comment]
I started using the branch couple of days ago and observing so far.

**Comment by Kdisimone** [comment]
Closing this.  Facebook posts and other feedback indicate dynamic carb absorption has been well received and working well for Loopers.  https://github.com/LoopKit/Loop/pull/507
