### ISSUE TITLE
Apple Watch problem

### ISSUE THREAD

**Issue by NovaHowl** [LoopKit/Loop#437]
I have re-compiled the loop app and paired my Apple Watch to my phone, yet it doesn't show up in the list of available apps in the watch app.

**Comment by walker0** [comment]
@NovaHowl you need to make sure that your phone and watch are both running appropriate software. (If iOS 10.3 on phone it is best to use watchOS 3.2). You also need to make sure you click trust on the watch when you connect the phone to the computer. 

This is an issue that is best dealt with over on Gitter at https://gitter.im/LoopKit/Loop

**Comment by NovaHowl** [comment]
had to update my watch. Sorry
