### ISSUE TITLE
Reservoir Outline Color Incorrect During Workout Set

### ISSUE THREAD

**Issue by channemann** [LoopKit/Loop#447]
Extremely minor issue here, witnessed in v1.2. When the reservoir is in the yellow state, and you go to set a workout mode target, the outer boundary of the reservoir icon re-renders in gray.

![img_3739](https://cloud.githubusercontent.com/assets/5387400/24964661/bb22ec90-1f56-11e7-9636-adf255e54400.PNG)

**Comment by walker0** [comment]
This seems to behave differently in 1.3.1 on iOS 10.3.1
![img_8005](https://cloud.githubusercontent.com/assets/17603635/25003471/e621fbd8-2092-11e7-837b-2d11fec3536b.png)

**Comment by ps2** [comment]
Appears to be fixed.
