### ISSUE TITLE
1.3 appears to be including Pending basal in calculations. 1.2 appears not to be.

### ISSUE THREAD

**Issue by rsuvalle** [LoopKit/Loop#452]
This is kind of a continuation of my previous issue...

I rolled back to 1.2 yesterday and the calculations for corrections were completely different and I don't believe it has to do with momentum. I waited it out and tested when BG was stable and in range and it appears that 1.3 uses the pending insulin in it's calculation, which means it's offering smaller or no corrections, whereas 1.2 appears to not be including pending insulin, hence offering a larger correction. As a result on 1.3 my children would be high all the time with Loop making no correction suggestions because there was pending insulin. However, after rolling back to 1.2 Loop is making suggestions that amply correct my children when they are high. I understand I could have my kids add the pending to their boluses, but they are children and they cannot remember or be responsible to add correctly. So no longer does pressing the recommended dose have any real affect for us if I have to manually add the pending. I'm seeing many people with this same issue. Thanks.

**Comment by ps2** [comment]
Here is where pending basal is subtracted from the bolus calculation in 1.2: https://github.com/LoopKit/Loop/blob/v1.2.0/Loop/Managers/DoseMath.swift#L179

So I think the difference you're observing must be coming from somewhere else.  In addition to momentum not being included in 1.3, retrospective correction is not included in the bolus calc as well, even if it is turned on.  Could that be the difference for you?

**Comment by rsuvalle** [comment]
I think I'm understanding what I'm looking at with the code. :) I'll test retrospective correction tonight with 1.2 and 1.3 and see if there's a difference. But whatever the issue is it's making a big impact, in the wrong direction for us. :(

**Comment by jenm999** [comment]
Same experience for us. 1.3 rarely suggests corrections even when IOB is insufficient. And often under boluses or flat out does not bolus at all for carbs because IOB is enough to cover carbs OR high BG but not both.

**Comment by ps2** [comment]
Bolus calculations are now including momentum and retrospective correction once again in v1.3.2
