### ISSUE TITLE
1.3.2 dev - communication with pump seems ok but loop status remains yellow

### ISSUE THREAD

**Issue by francesc0-cgm** [LoopKit/Loop#457]
I updated to 1.3.2 dev on friday. The pump communicates without any problem with the riley (i tried 3 different rileys - tried with a purple and green 0.7p and a brand new 1.0 - singularly and together) but doesn't enact basals. Sometimes the issues is sporadic, sometimes it takes 20 mins to get back to green. Pump is the same 723 as usuals. I updated to last 10.3.1 my iphone 5c last week. anything new in my house that could interfere.
Checked max basals on loop and pump and they are ok.

![18192283_10155128769345772_128444155088898729_o](https://cloud.githubusercontent.com/assets/10731469/25499873/365eef5c-2b8d-11e7-90bd-caa280ad53a7.jpg)
![18192737_10155128773910772_6087205857895572746_o](https://cloud.githubusercontent.com/assets/10731469/25499872/365cd1b8-2b8d-11e7-862f-de03aa133fb5.jpg)
![18192328_10155128774350772_8050565545647704465_o](https://cloud.githubusercontent.com/assets/10731469/25499871/365a2558-2b8d-11e7-9f2e-37ab1ca9699f.jpg)

**Comment by francesc0-cgm** [comment]
It is not linked to 1.3.2 dev because i downgraded to 1.3.0 and i had same problem. 
Could be due to new 10.3.1 on 5c or  the fact i'm trying to use multiple rileys at same time (one green and the others grey, not activated). Now i'm trying to keep all activated.

**Comment by danradigan** [comment]
I'm seeing quite a bit of could not verify temp basal on attempt 2.  My loop is red, but when going into the RileyLink menu I can send button press and get the pump model number.

**Comment by ps2** [comment]
Did this end up being a max-basal rate issue?  Or was there some other resolution?

**Comment by francesc0-cgm** [comment]
It happened when using 2 rileys together.


In data 19 Maggio 2017 7:44:32 PM Pete Schwamb <notifications@github.com> 
ha scritto:

**Comment by Kdisimone** [comment]
Closing this issue as it seems to have been resolved. (two rls at same time, and two loop versions)
