### ISSUE TITLE
Glucose data not being pulled from cloud 

### ISSUE THREAD

**Issue by islagroves** [LoopKit/Loop#459]
I've been running 1.3.0dev with G5 direct data, and G4 xdrip share data from cloud when G5 is failing. Just updated to 1.3.1 and cloud data no longer works. G5 direct is fine, but once toggled off, no glucose data from cloud and hitting glucose button does nothing. Share app on same phone receiving data fine. Reverted to 1.3.0dev and all fine again.

**Comment by walker0** [comment]
If your share account is based outside the US then share currently isn't supported.

**Comment by islagroves** [comment]
I am outside US, but using US share servers. The problem is only with 1.3.1, previous versions of Loop are working fine.

**Comment by melena-barbacil** [comment]
I have the same problem from friday when I set up v1.3.1. I wonder if your pump is 722 or if anybody with 722 pump has loop working correctly

**Comment by islagroves** [comment]
We're using 522, but the pump shouldn't really affect the cgm should it? All pump functions are working fine through RL.

**Comment by melena-barbacil** [comment]
There is a solution in https://github.com/DT1A/loop2nightscout
It is working perfectly for me

**Comment by eyim** [comment]
With the recent upgrade to 1.3.2, we are having the same problem.  If Xdrip uploads glucose values to the Share servers then Loop won't pull those down anymore.  Used to work perfectly.  

Now if you don't select one of the 3 CGMS systems (Enlite, G4, G5) it doesn't seem to pull down the bg values from the share servers while previously it did.

We are on G4.  Located in USA and on USA share servers.

**Comment by ps2** [comment]
Enable G5, but do not enter a transmitter id.

**Comment by eyim** [comment]
Worked perfectly.  Thank you Pete.

**Comment by islagroves** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Pete, you are awesome! So simple, but just relieved weeks of stress! Thank you 😊 


Sent from Yahoo Mail for iPhone


On Saturday, May 27, 2017, 6:34 am, Pete Schwamb <notifications@github.com> wrote:


Enable G5, but do not enter a transmitter id.

**Comment by ps2** [comment]
The solution to enable g5, but not enter a transmitter id is a valid solution for when you want to do share as your only cgm data source.  That will not work offline, as a reminder.
