### ISSUE TITLE
Store preferences in iCloud

### ISSUE THREAD

**Issue by andrew-anguiano** [LoopKit/Loop#463]
Had an edge-case scenario last night of needing to do a restore-from-iCloud on my iPhone. It would be great if Loop's settings could be stored in iCloud to provide a nice backup in case of a phone needing to be restored.

**Comment by goldendel** [comment]
+ 1 on this request.  It would also be very useful going between different loop versions when multiple branches are installed

**Comment by Kdisimone** [comment]
two improvements make this request out-dated...first, Loop automatically uploads your carb ratios, ISFs, and basal rates to Nightscout profile now, as well as overrides. Secondly, the new "Quick Start" option from Apple will allow you to move data and even not lose a current pod, from old phone to new phone 
https://support.apple.com/en-us/HT210216
