### ISSUE TITLE
Nightscout Reports Show Inaccurate Loop Boluses

### ISSUE THREAD

**Issue by chelle0207** [LoopKit/Loop#466]
I was low a lot this afternoon (5/10), so I corrected with 2 clementines.  My insulin-to-carb ratio is 1u/8g.  I entered the carbs in Loop but did NOT bolus.  I did this 1x for each of the clementines.  The Nightscout report shows 8g (1.00u), as if I took 1 unit.  I did not.  The report is NOT showing accurate insulin dosing.  The TREATMENTS report does not have insulin doses listed, just carbs.

On second thought, maybe this is not inaccurate.  Maybe the red numbers are suggested boluses, and the blue ones are actual boluses.

![screen shot 2017-05-10 at 18 09 54](https://cloud.githubusercontent.com/assets/8975324/25923551/ffb46da0-35ab-11e7-9cca-b0c67b54ff2a.png)
 

![screen shot 2017-05-10 at 18 08 06](https://cloud.githubusercontent.com/assets/8975324/25923463/aa17e9f8-35ab-11e7-9b32-5bc9f9621500.png)

**Comment by ps2** [comment]
I'm not sure I see the 1U there. What time is the bolus?

**Comment by chelle0207** [comment]
I think I was looking at the graphics incorrectly.  On the graph, there's
red text for the carbs.  8g (1.00u)  I assumed that meant a bolus.  I
didn't realize the boluses were in blue.  So maybe this isn't an issue at
all.

I ate the clementine (8g) around 17:00 on 5/10.
