### ISSUE TITLE
Freestyle libre  sony smartwach3, nigthwath and looped working?  

### ISSUE THREAD

**Issue by davidmlb** [LoopKit/Loop#476]
Hi everybody, 

 My son has a Freestle libre working with sony smartwatch3 as a CGM, and I can see now in nigthwatch how it is. I whant to learn about loop to install in next time, but I have on question, it’s possible to work with loop with freestyle libre? Somebody has the system working? 
 Regards

**Comment by trixing** [comment]
On Tue, May 16, 2017 at 1:24 PM, davidmlb <notifications@github.com> wrote:

> My son has a Freestle libre working with sony smartwatch3 as a CGM, and I
> can see now in nigthwatch how it is. I whant to learn about loop to install
> in next time, but I have on question, it’s possible to work with loop with
> freestyle libre? Somebody has the system working?
>

You need to get the data on the smartphone into Healthkit.  The rest should
just work (I had this working back a few month ago with the LimiTTer
hardware).


-- 
Jan Dittmer <jdi@l4x.org>, http://l4x.org

**Comment by dabear** [comment]
@davidmlb Yes it's possible.I'm doing this right now, running Loop with libre+sony smartwatch for continous readouts. This setup will require access to internet on both phones at all times, or Loop will temporarily stop working.

My setup is as follows:
Two phones, one android and one iphone.

libre->sw3->librealarm->xdrip+ uploading to nightscout 
iphone+rileylink+ Loop set up to retrieve glucose from dexcom share.

You will also need to get glucose from nightscout into dexcom share. Several ways to do that...
Personally I've modified Loop dependencies to fetch glucose from my own proxy server that speaks the dexcom share protocol and fetches from nightscout. I've made my server software open source and easily installable into azure from here: https://github.com/dabear/NightscoutShareServer


I know the setup is a bit tedious, but it works 👍

**Comment by dabear** [comment]
Loop dev should now contain the necessary code to support custom share servers, see https://github.com/LoopKit/Loop/pull/509

You install the nightscoutshareserver by visiting https://github.com/dabear/NightscoutShareServer. See the comments in Loop here to enable it: https://github.com/dabear/Loop/blob/62918f5a55b5334afb05e049356e3f1fc68d1824/Loop/Models/ServiceAuthentication/ShareService.swift#L48

Loop will then give you an option like this:
![img_0038](https://user-images.githubusercontent.com/442324/27802819-61b46d6c-6026-11e7-832c-ea84342da97a.PNG)

This issue can probably be closed now @davidmlb

**Comment by davidmlb** [comment]
Thanks

**Comment by jcwarrior** [comment]
Hi. I have tried to use this approach with latest iOS and custom share server on Azure. I have problems to connect from iphone to azure custom share server. Server runs well and show glucose values, but Loop doesn't connect on iPhone. Maybe a problem with ssl wildcard certificate on azure?
