### ISSUE TITLE
Request to accommodate manual BG entry in Loop App

### ISSUE THREAD

**Issue by denvergail** [LoopKit/Loop#493]
Having the ability to enter a BG as a manual entry when CGM data is not available or CGM data is significantly different from BG meter would allow for continued Looping with more accurate results.

When playing tennis, a 2 hour time commitment, my CGM often is not reading correctly and reports ???. It is crucial during tennis that I maintain BG in normal range. It is a HUGE distraction to try to calculate what insulin I need to maintain my BG without crashing or going high, especially in light of the dreaded adrenaline rush. With Loop, I'm not paying attention to IOB or current basal rates. They are no longer part of my consciousness, so I cannot quickly estimate my current basal rates or required correction. The only solution I could come up with, at the time, was to input a carb amount to calculate a correction. And, to guess at a temp basal rate. Neither of those entries were anywhere close to accurate.

Likewise, if CGM is reporting a BG level that is significantly different from BG meter, having accurate information as part of Loop would result in more accurate insulin calculations.

Allowing Loop to continue to run with a manual BG entry, despite noise from CGM or CGM reporting wrong BG level, would allow the continued automated calculation with more accuracy and less worry.

**Comment by danielharrelson** [comment]
You can input your glucose in the Health Kit. If there is no connection to CGM data, it will pick it up.

**Comment by Kdisimone** [comment]
Closing issue...Loop is able to read manual BG entries made into the Health App.  I believe this addresses the functionality the original poster was looking for.
