### ISSUE TITLE
Pump error

### ISSUE THREAD

**Issue by dgilley111** [LoopKit/Loop#495]
Received this error and will not change basal settings.  The operation couldn't"t be completed. Pump error: command Refused. Pump error(Minimedkit.pumperrorcode.command refused. Loop worked good for 1 week then refuses comand  to change basal. Dexcom and bogus administration and all graphs work fine.

**Comment by ps2** [comment]
Check your max basal setting.

**Comment by dgilley111** [comment]
Mac basal set at 5.0 no change from before.

**Comment by ps2** [comment]
That error happens when Loop tries to set a temp basal larger than allowed by the pump.  Make sure that your Loop setting matches your pump.  Also make sure the temp basal units are absolute rather than percentage.

**Comment by dgilley111** [comment]
Thanks that seems to have fixed my problem. This is absolutely the best control I have ever seen. I have worn the Medtronic 670 and this is superior. Thanks again
