### ISSUE TITLE
Request: Ability to Turn off BG Guard or allow for a Negative Number for BG Guard

### ISSUE THREAD

**Issue by rsuvalle** [LoopKit/Loop#505]
Would love to see a way to remove the Minimum BG Guard like we used to be able to facilitate in the customizations, or have the ability to enter a negative number. Reason being: before, when I could fully remove the Guard, I would be able to give a complete bolus, even when trending down (below zero). Now with zero being the lowest number, if trending below zero, it will reduce the bolus too much or not suggest a bolus at all. Thanks!

**Comment by scottleibrand** [comment]
Presumably you don't expect BG to actually drop to zero, or you wouldn't be bolusing... Do you have any sense why your predictions are so far off? It seems it might be useful to fix the underlying issue with the predictions, before considering whether it'd be useful to allow Loop to be even more wrong.

**Comment by rsuvalle** [comment]
From what I've seen, a prediction of below zero is pretty common (example: Loop high temps from a sudden spike and you start to drop a little more than expected and there's now too much IOB), but Loop's algorithm is great at preventing that from actually happening. But while it's correcting course and you want to bolus for a snack or a meal, it's sometimes not suggesting the full bolus, like you would get with OpenAPS.

**Comment by ps2** [comment]
There is an adjustment we may make in how we apply insulin effects to BG values; as you approach 0, insulin obviously has less of an effect, and you cannot actually have negative BG. 

However, even with something like that in place, I think in the situations you describe it's hard to imagine eventual bg actually being in a treatable range.  Loop does not bolus off your carbs, but off of eventual bg, so I'm guessing in those situations, even if you disabled the minimum bg guard, that Loop still wouldn't want to bolus.

**Comment by rsuvalle** [comment]
Pete - Would the new Dynamic Carb Absorption feature coming to the next build help alleviate this situation? Meaning will it give affect the amount of the bolus or will it just handle wrong carb absorptions better?

**Comment by ps2** [comment]
Not directly.  If you really want to remove minimum bg guard from bolus recommendations, then these are the lines to comment out: https://github.com/LoopKit/Loop/blob/v1.3.3/Loop/Managers/DoseMath.swift#L169-L171

**Comment by rsuvalle** [comment]
Thanks!
