### ISSUE TITLE
0 Amount Consumed crashes dynamic-carb-absorption 1.3.4dev Loop

### ISSUE THREAD

**Issue by dm61** [LoopKit/Loop#512]
Loop crashes just after meal entry is saved if 0 is entered as Amount Consumed. It then becomes impossible to restart Loop.

**Comment by ps2** [comment]
Good find!  I have a fix in LoopKit in the works to prevent saving a 0-gram carb entry.  Until then, you can delete the offending entry in the Health app.

**Comment by ps2** [comment]
https://github.com/LoopKit/LoopKit/pull/150

**Comment by dm61** [comment]
👍 and thanks for the reminder that Loop stores everything in Health. Last night, in desperation, I reinstalled 1.3.2, deleted the offending entry, and then reinstalled and resumed 1.3.4dev. not the easiest way around :)
