### ISSUE TITLE
Loop turns green only  every fifteen minutes,

### ISSUE THREAD

**Issue by davidmlb** [LoopKit/Loop#513]
Dear all, I installed Loop 3 days ago. I'm using minimed 754, and the loop only close and turns Green every 15 minutes. 

First is Green 5 minutes, then yelow until 14 minutes and then turns Green in the minute 15 ( but if something happens turns red for 15 minutes more). 

I was checking all the possible causes when the loop is not turning green and everything seem s ok, i reed also the follow in the guide:

•MySentry Pair: MySentry Pairing is for x23 and x54 pumps. Follow the directions as shown in the RileyLink command screen for MySentry. You do not have to worry about this command if you are using an x15 or x22 model pump, as they do not have MySentry. If you do not perform a MySentry pairing and have an x23 or x54 pump, your loop will only turn green every 15 minutes.

and I did it, but the problem is not solved.

Any ideas?

**Comment by ps2** [comment]
Sounds like you resolved this (via our FB messaging)
