### ISSUE TITLE
Have to tap and select Server option to add Dexcom Account

### ISSUE THREAD

**Issue by loudestnoise** [LoopKit/Loop#514]
Just built Loop with dynamic-carb-absorption branch #507 and when I went through initial setup to add Dexcom Share account I noticed when I would input my username & password it wouldn't let me save the account before first tapping on Server and selecting US (the only option at the moment)

Video demonstrating issue with me narrating - http://granu.be/lPz5

**Comment by Kdisimone** [comment]
Closed with fix https://github.com/LoopKit/Loop/releases/tag/v1.4.0
