### ISSUE TITLE
After camp

### ISSUE THREAD

**Issue by laurensdexinfo** [LoopKit/Loop#517]
Daughters loop won't pick up after having returned from diabetes camp...it has picked up intermittently but won't adjust basal...only intermittent remote bolus....we have restarted several times...it is a new dexcom sensor and has been entered correctly....anyone with any ideas please help....it was working like gangbusters right before camp

Use the Share button above save this diagnostic report to aid investigating your problem. Issues can be filed at https://github.com/LoopKit/Loop/issues.

Generated: 2017-07-07 11:07:14 +0000

## DeviceDataManager
receiverEnabled: false
latestPumpStatusFromMySentry: nil
latestGlucoseG5: nil
latestGlucoseFromShare: nil
latestGlucoseG4: nil
pumpState: Optional(## PumpState
timeZone: GMT-0700 (fixed)
pumpRegion: North America
pumpModel: 522
lastHistoryDump: 0000-12-30 00:00:00 +0000
awakeUntil: 0000-12-30 00:00:00 +0000
lastWakeAttempt: nil)
preferredInsulinDataSource: Event History
transmitterEnabled: true
transmitterID: Optional("40XA3L")
glucoseTargetRangeSchedule: ["items": [["startTime": 0.0, "value": <__NSArrayI 0x17023a9a0>(
100,
115
)
], ["startTime": 28800.0, "value": <__NSArrayI 0x1702273c0>(
90,
120
)
]], "timeZone": -25200, "workoutRange": <__NSArrayI 0x170230bc0>(
120,
180
)
, "unit": "mg/dL"]
workoutModeEnabled: Optional(false)
maximumBasalRatePerHour: Optional(2.3999999999999999)
maximumBolus: Optional(5.5)
## RileyLinkDeviceManager

timerTickEnabled: false

idleListeningEnabled: false

## RileyLinkDevice
name: RileyLink
RSSI: -66
lastIdle: 0000-12-30 00:00:00 +0000
lastTuned: 0000-12-30 00:00:00 +0000
radioFrequency: 0.0
firmwareVersion: subg_rfspy 1.0 / ble_rfspy 0.9
state: Connected
## StatusExtensionDataManager
appGroupName: group.com.Lauren.LoopGroup
statusExtensionContext: Optional(["reservoir": ["startDate": 2017-07-07 07:43:33 +0000, "capacity": 176, "unitVolume": 40.700000000000003], "loop": ["dosingEnabled": true, "lastCompleted": 2017-07-07 07:45:03 +0000], "batteryPercentage": 1.0, "latestGlucose": ["value": 61.0, "sensor": ["isStateValid": false, "isLocal": true, "stateDescription": "warmup "], "unit": "mg/dL", "startDate": 2017-07-07 07:34:28 +0000], "version": 2, "netBasal": ["percentage": 0.0, "startDate": 2017-07-07 07:00:00 +0000, "rate": 0.0], "eventualGlucose": ["unit": "mg/dL", "startDate": 2017-07-07 07:34:28 +0000, "value": 61.0]])

## NSUserDefaults
["com.loudnate.Naterade.PumpTimeZone": -25200, "com.loopkit.Loop.G5TransmitterEnabled": 1, "com.loudnate.Naterade.InsulinSensitivitySchedule": {
    items =     (
                {
            startTime = 0;
            value = 99;
        },
                {
            startTime = 21600;
            value = 96;
        },
                {
            startTime = 36000;
            value = 96;
        },
                {
            startTime = 43200;
            value = 95;
        },
                {
            startTime = 50400;
            value = 95;
        },
                {
            startTime = 61200;
            value = 85;
        },
                {
            startTime = 75600;
            value = 95;
        },
                {
            startTime = 82800;
            value = 96;
        }
    );
    timeZone = "-25200";
    unit = "mg/dL";
}, "com.loudnate.CarbKit.ModifiedCarbEntries": <__NSCFArray 0x17004f2a0>(

)
, "com.loudnate.Naterade.PumpModelNumber": 522, "INNextHearbeatDate": 521115520.793239, "com.loudnate.Loop.PreferredInsulinDataSource": 0, "com.loudnate.Naterade.ConnectedPeripheralIDs": <__NSCFArray 0x170260480>(
C9559BE9-5016-4D95-A2F3-56E1BB7550F1
)
, "com.loudnate.Loop.RetrospectiveCorrectionEnabled": 0, "com.apple.content-rating.MovieRating": 1000, "com.loopkit.Loop.PumpRegion": 0, "com.apple.content-rating.TVShowRating": 1000, "NSLanguages": <__NSArrayI 0x17003f000>(
en-US,
en
)
, "com.loudnate.Naterade.InsulinActionDuration": 10800, "com.apple.content-rating.ExplicitMusicPodcastsAllowed": 1, "com.loopkit.Loop.BatteryChemistry": 1, "com.loudnate.CarbKit.DeletedCarbEntryIds": <__NSCFArray 0x17004e8b0>(

)
, "ApplePasscodeKeyboards": <__NSCFArray 0x170262c40>(
en_US@hw=Automatic;sw=QWERTY,
emoji@sw=Emoji
)
, "com.loudnate.Naterade.MaximumBasalRatePerHour": 2.4, "AKLastCheckInSuccessDate": 2017-07-07 05:25:08 +0000, "com.loudnate.Naterade.DosingEnabled": 1, "com.loudnate.Naterade.CarbRatioSchedule": {
    items =     (
                {
            startTime = 0;
            value = 26;
        },
                {
            startTime = 21600;
            value = 14;
        },
                {
            startTime = 36000;
            value = 14;
        },
                {
            startTime = 43200;
            value = 17;
        },
                {
            startTime = 50400;
            value = 13;
        },
                {
            startTime = 61200;
            value = 15;
        },
                {
            startTime = 72000;
            value = 15;
        },
                {
            startTime = 73800;
            value = 15;
        }
    );
    timeZone = "-25200";
    unit = g;
}, "AKLastEmailListRequestDateKey": 2017-06-26 16:20:00 +0000, "com.loopkit.Loop.FetchEnliteDataEnabled": 0, "com.loudnate.Naterade.BasalRateSchedule": {
    items =     (
                {
            startTime = 0;
            value = "0.35";
        },
                {
            startTime = 7200;
            value = "0.4";
        },
                {
            startTime = 14400;
            value = "0.4";
        },
                {
            startTime = 19800;
            value = "0.9";
        },
                {
            startTime = 36000;
            value = "0.8";
        },
                {
            startTime = 43200;
            value = "0.6";
        },
                {
            startTime = 59400;
            value = "0.8";
        },
                {
            startTime = 72000;
            value = "0.75";
        },
                {
            startTime = 82800;
            value = "0.5";
        }
    );
    timeZone = "-25200";
}, "com.loudnate.Naterade.PumpID": 543791, "com.loudnate.Naterade.TransmitterID": 40XA3L, "AKLastCheckInAttemptDate": 2017-07-07 05:25:08 +0000, "AKDeviceUnlockState": 1, "AppleTemperatureUnit": Fahrenheit, "com.loopkit.Loop.MinimumBGGuard": {
    units = "mg/dL";
    value = 85;
}, "AddingEmojiKeybordHandled": 1, "NSInterfaceStyle": macintosh, "PKKeychainVersionKey": 3, "INNextFreshmintRefreshDateKey": 521149758.480264, "AppleLanguagesDidMigrate": 14F89, "com.loudnate.Loop.G4ReceiverEnabled": 0, "com.loudnate.CarbKit.CarbEntryCache": <__NSCFArray 0x170082490>(
{
    absorptionTime = 10800;
    createdByCurrentApp = 1;
    externalId = 595e73e0ecb401a3e69b5093;
    sampleUUID = "4D533F6D-D6B1-4DA2-B646-A82A9BE514F6";
    startDate = "2017-07-06 17:31:06 +0000";
    unitString = g;
    value = 30;
},
{
    absorptionTime = 10800;
    createdByCurrentApp = 1;
    externalId = 595eb4b4ecb401a3e69b50ca;
    sampleUUID = "C06F3265-C549-43E2-9D86-FA7E5E1BCD30";
    startDate = "2017-07-06 22:07:44 +0000";
    unitString = g;
    value = 45;
},
{
    absorptionTime = 10800;
    createdByCurrentApp = 1;
    externalId = 595ecd88ecb401a3e69b50d5;
    sampleUUID = "3511F62C-24EE-44FC-8D3A-89E16496FBE3";
    startDate = "2017-07-06 23:53:16 +0000";
    unitString = g;
    value = 40;
}
)
, "com.loudnate.Naterade.MaximumBolus": 5.5, "com.loudnate.Naterade.GlucoseTargetRangeSchedule": {
    items =     (
                {
            startTime = 0;
            value =             (
                100,
                115
            );
        },
                {
            startTime = 28800;
            value =             (
                90,
                120
            );
        }
    );
    timeZone = "-25200";
    unit = "mg/dL";
    workoutRange =     (
        120,
        180
    );
}, "MSVLoggingMasterSwitchEnabledKey": 0, "AppleLocale": en_US, "com.apple.content-rating.AppRating": 1000, "com.apple.content-rating.ExplicitBooksAllowed": 1, "AppleLanguages": <__NSCFArray 0x170262c00>(
en-US
)
]

## LoopDataManager
predictedGlucose: []
retrospectivePredictedGlucose: []
recommendedTempBasal: nil
lastTempBasal: nil
lastLoopCompleted: 2017-07-07 07:45:03 +0000
insulinOnBoard: Optional(InsulinKit.InsulinValue(startDate: 2017-07-07 11:05:00 +0000, value: -0.0030024940002590737))
carbsOnBoard: nil
error: Optional(Loop.LoopError.glucoseTooOld(2017-07-07 07:34:28 +0000))

## DoseStore

* readyState: ready
* insulinActionDuration: 10800.0
* basalProfile: ["items": [["startTime": 0.0, "value": 0.35], ["startTime": 7200.0, "value": 0.4], ["startTime": 14400.0, "value": 0.4], ["startTime": 19800.0, "value": 0.9], ["startTime": 36000.0, "value": 0.8], ["startTime": 43200.0, "value": 0.6], ["startTime": 59400.0, "value": 0.8], ["startTime": 72000.0, "value": 0.75], ["startTime": 82800.0, "value": 0.5]], "timeZone": -25200]
* insulinSensitivitySchedule: ["items": [["startTime": 0.0, "value": 99], ["startTime": 21600.0, "value": 96], ["startTime": 36000.0, "value": 96], ["startTime": 43200.0, "value": 95], ["startTime": 50400.0, "value": 95], ["startTime": 61200.0, "value": 85], ["startTime": 75600.0, "value": 95], ["startTime": 82800.0, "value": 96]], "timeZone": -25200, "unit": "mg/dL"]
* areReservoirValuesContinuous: true

### getRecentReservoirValues

* 2017-07-07 09:23:33 +0000, 40.1
* 2017-07-07 09:18:33 +0000, 40.1
* 2017-07-07 09:13:35 +0000, 40.2
* 2017-07-07 09:08:35 +0000, 40.2
* 2017-07-07 09:03:22 +0000, 40.2
* 2017-07-07 08:58:33 +0000, 40.3
* 2017-07-07 08:53:35 +0000, 40.3
* 2017-07-07 08:48:31 +0000, 40.3
* 2017-07-07 08:43:33 +0000, 40.3
* 2017-07-07 08:38:33 +0000, 40.4
* 2017-07-07 08:33:33 +0000, 40.4
* 2017-07-07 08:28:35 +0000, 40.4
* 2017-07-07 08:23:33 +0000, 40.5
* 2017-07-07 08:18:33 +0000, 40.5
* 2017-07-07 08:13:31 +0000, 40.5
* 2017-07-07 08:08:35 +0000, 40.5
* 2017-07-07 08:03:33 +0000, 40.6
* 2017-07-07 07:58:33 +0000, 40.6
* 2017-07-07 07:53:35 +0000, 40.6
* 2017-07-07 07:48:35 +0000, 40.7
* 2017-07-07 07:43:33 +0000, 40.7
* 2017-07-07 07:38:31 +0000, 40.7
* 2017-07-07 07:33:35 +0000, 40.8
* 2017-07-07 07:28:33 +0000, 40.8
* 2017-07-07 07:03:33 +0000, 40.9
* 2017-07-07 06:58:33 +0000, 41.0
* 2017-07-07 06:53:33 +0000, 41.0
* 2017-07-07 06:48:33 +0000, 41.0
* 2017-07-07 06:43:33 +0000, 41.1
* 2017-07-07 06:38:31 +0000, 41.1
* 2017-07-07 06:33:31 +0000, 41.2

### getRecentPumpEventValues

* (Optional("CalBGForPHPumpEvent(length: 7, rawData: 7 bytes, timestamp: calendar: gregorian (fixed) year: 2017 month: 7 day: 7 hour: 0 minute: 38 second: 7 isLeapMonth: false , amount: 75)"), <InsulinKit.PumpEvent: 0x170096fd0> (entity: PumpEvent; id: 0xd000005915e80000 <x-coredata://1D0F55A4-7B3A-419C-8CA1-E1BFBE3EC13E/PumpEvent/p1459578> ; data: {
    createdAt = "2017-07-07 07:40:02 +0000";
    date = "2017-07-07 07:38:07 +0000";
    duration = 0;
    pumpID = 543791;
    raw = <0a4b47e6 206711>;
    title = "CalBGForPHPumpEvent(length: 7, rawData: 7 bytes, timestamp: calendar: gregorian (fixed) year: 2017 month: 7 day: 7 hour: 0 minute: 38 second: 7 isLeapMonth: false , amount: 75)";
    type = nil;
    unit = nil;
    uploaded = 1;
    value = nil;
}), true)
* (Optional("BGReceivedPumpEvent(length: 10, rawData: 10 bytes, timestamp: calendar: gregorian (fixed) year: 2017 month: 7 day: 7 hour: 0 minute: 38 second: 7 isLeapMonth: false , amount: 75, meter: \"c4d5e7\")"), <InsulinKit.PumpEvent: 0x170096df0> (entity: PumpEvent; id: 0xd000005916240000 <x-coredata://1D0F55A4-7B3A-419C-8CA1-E1BFBE3EC13E/PumpEvent/p1459593> ; data: {
    createdAt = "2017-07-07 07:40:02 +0000";
    date = "2017-07-07 07:38:07 +0000";
    duration = 0;
    pumpID = 543791;
    raw = <3f0947e6 606711c4 d5e7>;
    title = "BGReceivedPumpEvent(length: 10, rawData: 10 bytes, timestamp: calendar: gregorian (fixed) year: 2017 month: 7 day: 7 hour: 0 minute: 38 second: 7 isLeapMonth: false , amount: 75, meter: \"c4d5e7\")";
    type = nil;
    unit = nil;
    uploaded = 1;
    value = nil;
}), true)

### getRecentNormalizedDoseEntries

* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 05:58:33 +0000, endDate: 2017-07-07 06:00:00 +0000, value: 0.45805369127518492, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:00:00 +0000, endDate: 2017-07-07 06:03:31 +0000, value: 0.70805369127518492, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:03:31 +0000, endDate: 2017-07-07 06:08:31 +0000, value: -0.5, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:08:31 +0000, endDate: 2017-07-07 06:13:31 +0000, value: 0.70000000000001705, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:13:31 +0000, endDate: 2017-07-07 06:18:31 +0000, value: -0.5, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:18:31 +0000, endDate: 2017-07-07 06:23:33 +0000, value: -0.5, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:23:33 +0000, endDate: 2017-07-07 06:28:33 +0000, value: 0.69999999999993179, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:28:33 +0000, endDate: 2017-07-07 06:33:31 +0000, value: -0.5, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:33:31 +0000, endDate: 2017-07-07 06:38:31 +0000, value: 0.70000000000001705, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:38:31 +0000, endDate: 2017-07-07 06:43:33 +0000, value: -0.5, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:43:33 +0000, endDate: 2017-07-07 06:48:33 +0000, value: 0.70000000000001705, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:48:33 +0000, endDate: 2017-07-07 06:53:33 +0000, value: -0.5, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:53:33 +0000, endDate: 2017-07-07 06:58:33 +0000, value: -0.5, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 06:58:33 +0000, endDate: 2017-07-07 07:00:00 +0000, value: 0.70000000000001705, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:00:00 +0000, endDate: 2017-07-07 07:03:33 +0000, value: 0.85000000000001708, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:03:33 +0000, endDate: 2017-07-07 07:28:33 +0000, value: -0.10999999999999657, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 25min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:28:33 +0000, endDate: 2017-07-07 07:33:35 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:33:35 +0000, endDate: 2017-07-07 07:38:31 +0000, value: 0.86621621621614719, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 4.933min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:38:31 +0000, endDate: 2017-07-07 07:43:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:43:33 +0000, endDate: 2017-07-07 07:48:35 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:48:35 +0000, endDate: 2017-07-07 07:53:35 +0000, value: 0.85000000000001708, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:53:35 +0000, endDate: 2017-07-07 07:58:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 07:58:33 +0000, endDate: 2017-07-07 08:03:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:03:33 +0000, endDate: 2017-07-07 08:08:35 +0000, value: 0.84205298013246732, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:08:35 +0000, endDate: 2017-07-07 08:13:31 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 4.933min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:13:31 +0000, endDate: 2017-07-07 08:18:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:18:33 +0000, endDate: 2017-07-07 08:23:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:23:33 +0000, endDate: 2017-07-07 08:28:35 +0000, value: 0.84205298013246732, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5.033min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:28:35 +0000, endDate: 2017-07-07 08:33:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:33:33 +0000, endDate: 2017-07-07 08:38:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:38:33 +0000, endDate: 2017-07-07 08:43:33 +0000, value: 0.85000000000001708, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:43:33 +0000, endDate: 2017-07-07 08:48:31 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:48:31 +0000, endDate: 2017-07-07 08:53:35 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.067min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:53:35 +0000, endDate: 2017-07-07 08:58:33 +0000, value: -0.34999999999999998, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 08:58:33 +0000, endDate: 2017-07-07 09:00:00 +0000, value: 0.89567474048435824, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 4.817min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 09:00:00 +0000, endDate: 2017-07-07 09:03:22 +0000, value: 0.8456747404843582, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 4.817min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 09:03:22 +0000, endDate: 2017-07-07 09:08:35 +0000, value: -0.40000000000000002, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5.217min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 09:08:35 +0000, endDate: 2017-07-07 09:13:35 +0000, value: -0.40000000000000002, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 09:13:35 +0000, endDate: 2017-07-07 09:18:33 +0000, value: 0.80805369127518489, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0.1U over 4.967min"), managedObjectID: nil)
* DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-07-07 09:18:33 +0000, endDate: 2017-07-07 09:23:33 +0000, value: -0.40000000000000002, unit: InsulinKit.DoseUnit.unitsPerHour, description: Optional("Reservoir decreased 0U over 5min"), managedObjectID: nil)

## CarbStore

* carbRatioSchedule: ["items": [["startTime": 0.0, "value": 26], ["startTime": 21600.0, "value": 14], ["startTime": 36000.0, "value": 14], ["startTime": 43200.0, "value": 17], ["startTime": 50400.0, "value": 13], ["startTime": 61200.0, "value": 15], ["startTime": 72000.0, "value": 15], ["startTime": 73800.0, "value": 15]], "timeZone": -25200, "unit": "g"]
* defaultAbsorptionTimes: (7200.0, 10800.0, 14400.0)
* insulinSensitivitySchedule: ["items": [["startTime": 0.0, "value": 99], ["startTime": 21600.0, "value": 96], ["startTime": 36000.0, "value": 96], ["startTime": 43200.0, "value": 95], ["startTime": 50400.0, "value": 95], ["startTime": 61200.0, "value": 85], ["startTime": 75600.0, "value": 95], ["startTime": 82800.0, "value": 96]], "timeZone": -25200, "unit": "mg/dL"]
* delay: 600.0
* authorizationRequired: false
* isBackgroundDeliveryEnabled: false

## GlucoseStore

* latestGlucoseValue: Optional(61 mg/dL 080F361F-DD14-4B2A-A487-F19A121F5DF7 "Loop" (32) "xDripG5" metadata: {
    "com.loudnate.GlucoseKit.HKMetadataKey.GlucoseIsDisplayOnly" = 0;
} (2017-07-07 00:34:28 -0700 - 2017-07-07 00:34:28 -0700))
* managedDataInterval: 10800.0
* reflectionDataInterval: 1800.0
* momentumDataInterval: 900.0
* sampleDataCache: []
* authorizationRequired: false

**Comment by ps2** [comment]
Looks like you may have changed the time directly on the pump. Use the 'Change Time' command in your rileylink menu to manage pump timezone, and to hopefully fix your current issue.

**Comment by Kdisimone** [comment]
This issue looks resolved
