### ISSUE TITLE
How to delete reservoir history

### ISSUE THREAD

**Issue by davidmlb** [LoopKit/Loop#522]
Hi, sometimes I need to take out air bubbles from the reservoir, after that the level of it is less than before, then i have a problem because the loop think that the insulin has been deliver and says "Eventually -1700mg/dl" I read that you can solve it going to the insulin delivery and delete the last half hour. I tried it, like when I put from error carbohydrates 2 times, I push the graph, then push edit and then appears "-" in red colour at the beginning of every line. the problem is that in the reservoir doesn’t appears the "-"sign, I push edit but nothing change....

I had selected event history.

Thanks

**Comment by ps2** [comment]
Recent versions of Loop reinstate event deletion, and recognize prime events if you are using event history as your preferred data source.

How are you getting the bubbles out?  By doing a prime?

**Comment by davidmlb** [comment]
I getting out the bubbles, like when i change the reservoir, takein it out, an manally pressing  to getting out, the same proces but not filling with  insulin, so the total insulin will be less than before. 

then is not posible to delete? and why when i did it loop consider the insulin hes been delivered? 

thanks

**Comment by ps2** [comment]
You will need to move the pump motor somehow after you manually press on the reservoir.  Are you using a prime or rewind+prime to do that?

If you are using Loop v1.3.2 or v1.3.3, then Loop will recognize prime events and not count them toward delivery.

**Comment by davidmlb** [comment]
Yes, I do rewind like a reservoir change, i don't know what's prime? it's a fill the cannula? 

the versión is the 1.3.3

**Comment by davidmlb** [comment]
Whith new version 1.4 i can delete. 
Solved
