### ISSUE TITLE
Font issue in HUD

### ISSUE THREAD

**Issue by jmatheson** [LoopKit/Loop#523]
If user has increased font size in their iOS settings it ends up clipping in the HUD.

![image](https://user-images.githubusercontent.com/9138265/28293793-54d3d15e-6b99-11e7-9ab3-7934627f818b.png)

**Comment by russfg** [comment]
I see the issues above, but also the time under my charts is not spaced proportionally. I have the regular size iPhone 7,  with the Settings>Display&Brightness>Text Size  1 below the max.
![890719b2-3937-4018-a54d-38c1e081b07f png](https://user-images.githubusercontent.com/25555257/28982051-ef04f5fe-7919-11e7-8316-82c489e88426.PNG)
![654fd2e4-5e30-4512-bbdc-56905f7b5530 png](https://user-images.githubusercontent.com/25555257/28982056-f3b197b0-7919-11e7-9739-b9f95e107c6c.PNG)

**Comment by gkirma** [comment]
I had this issue as well and decreased the font size but it didn't correct on my Loop screen. Please offer some suggestions? Thank you!
