### ISSUE TITLE
Dynamic carbs graph incorrect for mmol

### ISSUE THREAD

**Issue by dabear** [LoopKit/Loop#525]
I'm on dev. The graph seems squashed:

![img_0044](https://user-images.githubusercontent.com/442324/28465229-45df953e-6e28-11e7-9b1e-3712d4ed557f.PNG)

**Comment by Kdisimone** [comment]
@dabear I assume this issue has been resolved?  Can I close this?

**Comment by dabear** [comment]
Yes. This is fixed. Closed.
