### ISSUE TITLE
Allow high temp when min bg is below target, above min bg guard, and eventual bg is above target.

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#530]
Currently Loop will restrict basal rates to <= currently scheduled rate in this case.

With min bg guard in place now, this restriction is questionable.  Users can specify how low min bg has to be before high temping should be disabled by adjusting min bg guard.

<img width="463" alt="img_6687_png" src="https://user-images.githubusercontent.com/14649/28654658-abfc2256-725b-11e7-9a20-b096b7bf5dcd.png">

**Comment by francesc0-cgm** [comment]
This is what i asked a couple days ago. I'm totally agree to this modification

**Comment by ps2** [comment]
@francesc0-cgm This is how Loop has always been; you were referring to some change you had issues with in dynamic carbs.

**Comment by francesc0-cgm** [comment]
Sorry @ps2 atm when any predicted bg is under the target also if later is over the target and always above min bg guard loop will set neutral temp isn't it?
