### ISSUE TITLE
Selecting Carbs using DCA

### ISSUE THREAD

**Issue by loudestnoise** [LoopKit/Loop#532]
While using DCA when you use plate to create a meal and first select a slow carb, and then select two fast carbs it changes the absorption time to use the fast carb absorption time. You can also recreate this by first selecting a particular carb time, deleting food icon, and then it won't change to a new absorption time until you select a new food icon twice. 

I thought, perhaps incorrectly, that when using the plate the point was to create a meal composed of the various carb absorption speeds and it would take the different times into account. I just re-read @ps2's documentation on the DCA PR #507 and now I think I'm a little confused. Does it use the fast, slow & medium food icons to let it know there are different absorption times in a single meal, or is it recommended to still split up meals that have carbs with different absorption times?

I made a screen recording of myself selecting carbs demonstrating this - http://granu.be/ljqJ

**Comment by ps2** [comment]
There is one absorption time for a given entry.  The food icons are not used at all in any dosing. They are just there for your visual reference.  The fact that the absorption time for the entry changes when selecting icons is just a convenience.

**Comment by loudestnoise** [comment]
Gotcha, when dosing for a meal that has different kinds of carb absorption times, one should still use separate entries then? That way they can decay at different times?

**Comment by ps2** [comment]
You still can, if you think that you have special circumstances or are aiming for tighter control, but I'd recommend in general that people just enter carbs as they like.  Loop adapts as it sees carbs absorb.  You might be able to do a better job than Loop's reactive approach by being proactive and very specific with carb entry, but Loop does do a lot better with inexact entries now.

**Comment by loudestnoise** [comment]
Makes sense, I think what I tend to do is assume that if I'm going to have some slow carbs it's best to choose the longer absorption time, and with Loop and the changes you made in #507 I think it's doing a pretty good job at figuring it all out.
