### ISSUE TITLE
Add graph to watch 

### ISSUE THREAD

**Issue by eszcloud** [LoopKit/Loop#537]
I appreciate the convenience of being able to glance down at my watch to know what my blood sugar is and where it will eventually end up. I would find it helpful to see the shape of the curve between now and BG(eventual). Is my blood sugar going to rise and then drop down to BG(eventual); drop and then rise up to BG(eventual); or almost immediately go roughly to BG(eventual) and then remain there steadily. 

Putting a graph in Loop on the Apple Watch would help differentiate different scenarios in a glance. Below is a mock version of what this would look like as well as the data on the phone which is what I used for the mock-up. 

![loopwatch_mod_pic_small2](https://user-images.githubusercontent.com/14155343/28740722-4d116afe-73bd-11e7-9c9c-0dce182da291.png)

![loopscreenshot_small](https://user-images.githubusercontent.com/14155343/28740723-4eda80aa-73bd-11e7-985e-a516f1e3aecb.png)

**Comment by francescaneri** [comment]
great idea @ps2

**Comment by MrrDonn** [comment]
Cool idea, Im just looking for something like this! Is there any other way how to do it now? Nightscout probably, right? 

For the watch graph - what about graph without numbers on the left side? You have actual sugar level on the top, so you know where you are, and you also haw the blue strip of ideal glycemia so you know if you are low or high... And I think there should be insulin and carbs as well - in different colors. What do you think?
Reason: Just to keep the app simple and clean.

**Comment by bashem** [comment]
I wouldn't need numbers.

**Comment by bharat** [comment]
@elnjensen and I have been working on this. The latest code is here:
https://github.com/bharat/Loop/tree/dev-watch

**Comment by Kdisimone** [comment]
closed with https://github.com/LoopKit/Loop/pull/772

watch graph is in dev now
