### ISSUE TITLE
Add ability to set temp target(s) from watch app

### ISSUE THREAD

**Issue by eszcloud** [LoopKit/Loop#538]
Add the ability to set temp target(s) from the watch app so that it is easier to adjust those on the fly and without needing to pull out a phone, such as enacting an eating soon temp target when walking into a restaurant.

![loopmenu3icons](https://user-images.githubusercontent.com/14155343/28740849-6144d46e-73bf-11e7-8d99-a04ce55ec012.png)

![loopmenu4icons](https://user-images.githubusercontent.com/14155343/28740851-659cc7e2-73bf-11e7-9bd9-69a03c43bc99.png)

**Comment by ddaniels1** [comment]
Great idea. Who is going to do it?

**Comment by apabari** [comment]
I believe this enhancement is already complete now - so this enhancement request could potentially be closed off.

I'm not quite sure who completed it though.  @ps2

**Comment by apabari** [comment]
I believe @mpangburn completed this - see https://github.com/LoopKit/Loop/issues/657

**Comment by ps2** [comment]
Yes, this is working in v1.5.4.  Thanks for the reminder!
