### ISSUE TITLE
Bolus Failures not being reported in 1.4

### ISSUE THREAD

**Issue by rsuvalle** [LoopKit/Loop#541]
Got three bolus failures in a row on 1.4 and none of them got a notification. I only caught it on the third one while looking at NightScout. My daughter may have attempted to bolus while Loop was yellow or red, however in past versions of Loop that either worked or we got a bolus failure notification on the phone. Dunno if this is a bug. I'll post a picture of our NightScout, but in each instance Loop did suggest a bolus which she entered. The last one I personally entered. 
![bolus failure](https://user-images.githubusercontent.com/8316972/28793833-2a0f919c-75e9-11e7-901a-04b3e1654b63.jpg)

**Comment by ps2** [comment]
Are you saying you missed the notification on the phone running Loop, or on a different phone you are using to monitor Loop?

**Comment by rsuvalle** [comment]
Phone running Loop did not display bolus failures. But I think I just figured out the problem and it's human (me) error. New version of Loop was installed with notifications turned off. But I believe my daughter manually turned them off during her looping break. So feel free to delete this issue.

**Comment by ps2** [comment]
Alright, thanks for updating the ticket.
