### ISSUE TITLE
Cancelled Bolus (Suspended Pump) Results in Lingering Pending Insulin Total

### ISSUE THREAD

**Issue by loudestnoise** [LoopKit/Loop#544]
If you issue a bolus from Loop and then decide you want to cancel said bolus by suspending the pump it will for a time (I didn't count, but it was a few minutes) show you that undelivered bolus as pending insulin.

Here's an example I caught with screenshots.

## After cancelled bolus and after editing carb entry for meal

![2017-08-01_15-08-21](https://user-images.githubusercontent.com/194853/28844797-77038be2-76cb-11e7-8546-e8cfc6d96be5.png)

## After a minute or two the pending dropped off and suggested a new bolus

![2017-08-01_15-08-36](https://user-images.githubusercontent.com/194853/28844835-9007b28a-76cb-11e7-898a-e5d0b6304b1f.png)

It made sense to me why it was not suggesting a new bolus, and with the patience of those few minutes I got a new recommendation, but I could see how someone wouldn't realize this is how it works and perhaps be confused.

**Comment by Kdisimone** [comment]
I think this can be helped by the addition to Loopdocs.  good catch.  I'll add it there.
