### ISSUE TITLE
Limit Suspend Threshold

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#545]
There should be a lower limit on minimum bg guard, to prevent setting it dangerously low.  Also, we could give it a default of 70mg/dl.  Renaming it to Suspend Threshold clarifies its use and action more clearly as well.

**Comment by gwynethrocks** [comment]
Great idea.

**Comment by Kdisimone** [comment]
changing title to reflect the new terminology

**Comment by dneth** [comment]
It seems like the same should be done on the upper end as well.  In the middle of the night I had a severe low and while I was fumbling around with my iPhone I somehow changed the suspend threshold from 80 mg/dL to 806 mg/dL and woke up high this morning.  It's clearly user error, but as a protective measure it seems reasonable to prevent the suspend threshold from being set above the lower bound of the correction range.
