### ISSUE TITLE
High basal threshold

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#546]
Currently, when min bg is below the bottom of your range, Loop will limit setting temp basals to only allow as high as current scheduled basal.  For some people, allowing a lower value that is set independently of your target range is desired, allowing Loop to start treating recovery from lows sooner.

**Comment by Kdisimone** [comment]
Yup!  Love this idea.  Will need to clarify for people that this number will be different than minimum bolus guard (or suspend threshold).  Thank you for issue!

**Comment by ddaniels1** [comment]
This should also help when eating a large meal with a long CA time such as mac and cheese. The ability to start high temping earlier when. Bg is rising but between guard and lower end of range when predicted to go above range by dia will help catch the big spike here. This happens for us 3 hours usually after the meal
