### ISSUE TITLE
Deleting carb entry in Dynamic Carb Absorption doesn't remove carbs from carbs on board

### ISSUE THREAD

**Issue by eszcloud** [LoopKit/Loop#547]
When I entered carbs for food from both my watch and on the phone and then deleted one entry, the carbs of the deleted entry still seem to be included in the calculation of carbs on board. (v1.3.4dev)

The screenshot below shows an entry for 37 g carbs (and 37 g total carbs) but 65 g COB. 

![img_0956](https://user-images.githubusercontent.com/14155343/28939887-a810a2f6-7847-11e7-90bf-b269959a4e7a.jpg)

**Comment by ps2** [comment]
This is just a display/cache issue. It will be fixed once the next version of LoopKit is incorporated.

**Comment by eszcloud** [comment]
Good to know. Thanks for following up and having a fix already.
