### ISSUE TITLE
BS reading in future and NOT working

### ISSUE THREAD

**Issue by Telefingers** [LoopKit/Loop#548]
BS seem to be reading in future and will not read the BS from the pump; however, it will pull the active insulin from the pump.  The dates are correct but the time also seems to be off.  Lost and desperate ; )

 ***problem solved by deleting data in the Apple Health App

**Comment by Telefingers** [comment]
![img_5231](https://user-images.githubusercontent.com/20625222/28951678-35ab3604-7892-11e7-81d1-3aa732518cfa.PNG)
![img_5232](https://user-images.githubusercontent.com/20625222/28951676-35a970e4-7892-11e7-8243-375c4c9c88c0.PNG)
![img_5233](https://user-images.githubusercontent.com/20625222/28951680-35ae6f18-7892-11e7-8edd-587026be1d96.PNG)
![img_5234](https://user-images.githubusercontent.com/20625222/28951679-35ad43a4-7892-11e7-9188-3bb8990904c8.PNG)
![img_5235](https://user-images.githubusercontent.com/20625222/28951677-35aa72d2-7892-11e7-905e-1a8dfd2b5b3a.PNG)

**Comment by Telefingers** [comment]
Problem solved...logged in to the Health App to clear the glucose data and then it went back to normal ; )

**Comment by ps2** [comment]
I'm guessing there is a small error in the enlite bg history parsing.  Or maybe we aren't checking all the crc codes.  @tmecklem, I'm guessing there are page CRCs as well as frame CRCs in the cgm history.  Do you know if those are being validated?

**Comment by tmecklem** [comment]
It would be really helpful to have the binary page data. I suspect it's a timestamping issue, but it's really hard to tell without the data in the page. I doubt it's in the CRC since that works the same at the pump history pages but I suppose that's a possibility too.

**Comment by Kdisimone** [comment]
@ps2 looks like this one can be closed?
