### ISSUE TITLE
Loop stopped sending temporal basals. Grey circle for 2 days!

### ISSUE THREAD

**Issue by elenavilla** [LoopKit/Loop#549]
Hi, I had trouble with one sensor, called Dexcom, and deleted and reinstalled the dexcom app (using G5.) Previously, I had updated my phone's os. Now, I can command boluses from the Loop app, and I can see the BG levels, but I have the grey circle, and the app doesn't recommend or use any temporal basal. Still using Loop 1.2. I'm wondering now if what I need is a Loop update.
Below is my Loop issue report. Thanks so much for any help!

Generated: 2017-08-04 07:15:28 +0000  ## DeviceDataManager receiverEnabled: false latestPumpStatusFromMySentry: nil latestGlucoseG5: Optional(xDripG5.Glucose(glucoseMessage: xDripG5.GlucoseRxMessage(status:  0, sequence: 23186, timestamp: 6971920, glucoseIsDisplayOnly: false,  glucose: 112, state: 6, trend: 13), timeMessage: xDripG5.TransmitterTimeRxMessage(status:  0, currentTime: 6971926, sessionStartTime: 6831645), status:  xDripG5.TransmitterStatus.ok, sessionStartDate: 2017-08-02 16:16:27  +0000, state: xDripG5.CalibrationState.ok, readDate: 2017-08-04 07:14:22  +0000)) latestGlucoseFromShare: nil latestGlucoseG4: nil pumpState: Optional(## PumpState timeZone: GMT+0100 (fixed) pumpRegion: North America pumpModel: 722 lastHistoryDump: 0000-12-30 00:00:00 +0000 awakeUntil: 2017-08-04 07:15:40 +0000 lastWakeAttempt: nil) preferredInsulinDataSource: Event History transmitterID: Optional("40P2JH") glucoseTargetRangeSchedule: ["items": [["startTime": 0.0, "value": <__NSArrayI 0x17403c4a0>( 100, 110 ) ], ["startTime": 14400.0, "value": <__NSArrayI 0x174033c00>( 100, 110 ) ], ["startTime": 25200.0, "value": <__NSArrayI 0x174037d00>( 100, 110 ) ], ["startTime": 32400.0, "value": <__NSArrayI 0x174227b60>( 100, 110 ) ], ["startTime": 34200.0, "value": <__NSArrayI 0x174227aa0>( 100, 110 ) ]], "timeZone": 3600, "workoutRange": <__NSArrayI 0x17403c320>( 140, 155 ) , "unit": "mg/dL"] workoutModeEnabled: Optional(false) maximumBasalRatePerHour: nil maximumBolus: Optional(6.0) ## RileyLinkDeviceManager  timerTickEnabled: false  idleListeningEnabled: false  ## RileyLinkDevice name: ElenaLink RSSI: -94 lastIdle: 0000-12-30 00:00:00 +0000 lastTuned: 0000-12-30 00:00:00 +0000 radioFrequency: 0.0 firmwareVersion: subg_rfspy 0.9 / ble_rfspy 0.9 state: Connected ## StatusExtensionDataManager appGroupName: group.com.evilla1.LoopGroup statusExtensionContext: Optional(["reservoir_startDate":  2017-08-04 07:14:39 +0000, "preferredUnitString": "mg/dL",  "netBasal_percentage": 0.0, "reservoir_unitVolume": 93.0,  "latestGlucose_sensor_isStateValid": true, "latestGlucose_sensor_isLocal": true, "eventualGlucose": -47.542909522265148, "latestGlucose_sensor_stateDescription":  "ok ", "latestGlucose_startDate": 2017-08-04 07:14:22 +0000,  "latestGlucose_value": 112.0, "reservoir_capacity": 300, "version": 1,  "latestGlucose_sensor_trendType": 3, "netBasal_rate": 0.0, "netBasal_startDate": 2017-08-04 06:00:00 +0000])  ## NSUserDefaults ["com.loudnate.Naterade.PumpTimeZone": 3600, "PKEnableStockholmSettings": 1, "com.loudnate.Naterade.InsulinSensitivitySchedule": {     items =     (                 {             startTime = 0;             value = 115;         },                 {             startTime = 21600;             value = 140;         },                 {             startTime = 32400;             value = 160;         },                 {             startTime = 72000;             value = 130;         }     );     timeZone = 3600;     unit = "mg/dL"; }, "com.loudnate.CarbKit.ModifiedCarbEntries": <__NSCFArray 0x170057fd0>(  ) , "com.apple.content-rating.ExplicitBooksAllowed": 1, "com.loudnate.Naterade.PumpModelNumber": 722, "INNextHearbeatDate": 523961008.990792, "com.loudnate.Loop.PreferredInsulinDataSource": 0, "com.loudnate.Naterade.ConnectedPeripheralIDs": <__NSCFArray 0x170076e80>( 2F2E1B57-DA51-4269-923A-1670CEABEDD4 ) , "com.loudnate.Loop.RetrospectiveCorrectionEnabled": 1, "com.apple.content-rating.MovieRating": 1000, "com.loopkit.Loop.PumpRegion": 0, "AppleICUForce24HourTime": 1, "com.apple.content-rating.TVShowRating": 1000, "NSLanguages": <__NSArrayI 0x170058b70>( en-US, es-ES, en ) , "AppleKeyboards": <__NSCFArray 0x17009e5a0>( en_US@hw=US;sw=QWERTY, es_ES@hw=Automatic;sw=QWERTY-Spanish, emoji@hw=Automatic;sw=Emoji ) , "com.loudnate.Naterade.InsulinActionDuration": 10800, "com.apple.content-rating.ExplicitMusicPodcastsAllowed": 1, "com.loudnate.CarbKit.DeletedCarbEntryIds": <__NSCFArray 0x170058450>(  ) , "ApplePasscodeKeyboards": <__NSCFArray 0x17009e500>( en_US@hw=US;sw=QWERTY, emoji@sw=Emoji, es_ES@hw=Automatic;sw=QWERTY-Spanish ) , "com.loudnate.Naterade.DosingEnabled": 1, "AKLastCheckInSuccessDate": 2017-08-03 22:50:58 +0000, "com.loudnate.Naterade.CarbRatioSchedule": {}, "com.loudnate.Naterade.PumpID": 588983, "com.loudnate.Naterade.TransmitterID":  40P2JH, "AKLastCheckInAttemptDate": 2017-08-03 22:50:45 +0000,  "AKDeviceUnlockState": 1, "AppleTemperatureUnit": Celsius,  "AddingEmojiKeybordHandled": 1, "NSInterfaceStyle": macintosh,  "PKKeychainVersionKey": 3, "INNextFreshmintRefreshDateKey": 523524193.063684, "AppleLanguagesDidMigrate": 14G60, "com.loudnate.Loop.G4ReceiverEnabled": 0, "com.loudnate.CarbKit.CarbEntryCache": <__NSCFArray 0x17009e550>(}, "MSVLoggingMasterSwitchEnabledKey": 0, "AppleLocale": en_US, "com.apple.content-rating.AppRating": 1000, "AppleKeyboardsExpanded": 1, "AppleLanguages": <__NSCFArray 0x170074c00>( en-US, es-ES ) ]  ## LoopDataManager predictedGlucose: [LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:14:22 +0000, quantity: 112 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:15:00 +0000, quantity: 108.195 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:20:00 +0000, quantity: 103.634 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:25:00 +0000, quantity: 98.4484 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:30:00 +0000, quantity: 92.7669 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:35:00 +0000, quantity: 86.704 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:40:00 +0000, quantity: 80.305 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:45:00 +0000, quantity: 73.6645 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:50:00 +0000, quantity: 66.8678 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 07:55:00 +0000, quantity: 59.9909 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:00:00 +0000, quantity: 53.1003 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:05:00 +0000, quantity: 46.2574 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:10:00 +0000, quantity: 39.5759 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:15:00 +0000, quantity: 33.1033 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:20:00 +0000, quantity: 26.8787 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:25:00 +0000, quantity: 20.9332 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:30:00 +0000, quantity: 15.2901 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:35:00 +0000, quantity: 9.96424 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:40:00 +0000, quantity: 4.96261 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:45:00 +0000, quantity: 0.284073 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:50:00 +0000, quantity: -4.08058 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 08:55:00 +0000, quantity: -8.14861 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:00:00 +0000, quantity: -11.9454 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:05:00 +0000, quantity: -15.5043 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:10:00 +0000, quantity: -18.8668 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:15:00 +0000, quantity: -22.0826 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:20:00 +0000, quantity: -25.2092 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:25:00 +0000, quantity: -28.3123 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:30:00 +0000, quantity: -31.4658 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:35:00 +0000, quantity: -34.7514 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:40:00 +0000, quantity: -38.2591 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:45:00 +0000, quantity: -42.0868 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:50:00 +0000, quantity: -46.3407 mg/dL), LoopKit.PredictedGlucoseValue(startDate: 2017-08-04 09:55:00 +0000, quantity: -47.5429 mg/dL)] retrospectivePredictedGlucose: [] recommendedTempBasal: nil lastTempBasal: nil lastLoopCompleted: 0000-12-30 00:00:00 +0000 insulinOnBoard: Optional(InsulinKit.InsulinValue(startDate: 2017-08-04 07:10:00 +0000, value: 1.1361190782624178)) carbsOnBoard: Optional(CarbKit.CarbValue(startDate: 2017-08-03 17:15:00 +0000, quantity: 0 g)) error: Optional(Loop.LoopError.missingDataError("Loop configuration data not set"))  ## DoseStore  * readyState: ready * insulinActionDuration: 10800.0 *  basalProfile: ["items": [["startTime": 0.0, "value": 0.7],  ["startTime": 7200.0, "value": 0.55], ["startTime": 14400.0, "value":  0.65], ["startTime": 25200.0, "value": 0.65], ["startTime": 34200.0,  "value": 0.75], ["startTime": 50400.0, "value": 0.8], ["startTime":  68400.0, "value": 0.65], ["startTime": 75600.0, "value": 0.65]],  "timeZone": 3600] *  insulinSensitivitySchedule: ["items": [["startTime": 0.0, "value":  115], ["startTime": 21600.0, "value": 140], ["startTime": 32400.0,  "value": 160], ["startTime": 72000.0, "value": 130]], "timeZone": 3600,  "unit": "mg/dL"] * areReservoirValuesContinuous: false  ### getRecentReservoirValues  * 2017-08-04 07:14:39 +0000, 93.0 * 2017-08-04 07:09:37 +0000, 93.1 * 2017-08-04 06:59:37 +0000, 93.2 * 2017-08-04 06:54:37 +0000, 93.3 * 2017-08-04 06:49:39 +0000, 93.3 * 2017-08-04 06:44:31 +0000, 93.4 * 2017-08-04 06:39:38 +0000, 94.6 * 2017-08-04 06:34:44 +0000, 94.7  ### getRecentPumpEventValues  * (Optional("ChangeTimePumpEvent(length:  7, rawData: 7 bytes, timestamp: calendar: gregorian (fixed) year: 2017  month: 8 day: 4 hour: 7 minute: 43 second: 1 isLeapMonth: false )"),  <InsulinKit.PumpEvent: 0x1702941e0> (entity: PumpEvent; id:  0xd000013e81980000 <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218406> ; data: {     createdAt = "2017-08-04 06:44:49 +0000";     date = "2017-08-04 06:43:01 +0000";     duration = 0;     pumpID = 588983;     raw = <1700812b 074411>;     title  = "ChangeTimePumpEvent(length: 7, rawData: 7 bytes, timestamp:  calendar: gregorian (fixed) year: 2017 month: 8 day: 4 hour: 7 minute:  43 second: 1 isLeapMonth: false )";     type = nil;     unit = nil;     uploaded = 1;     value = nil; }), true) * (Optional("NewTimePumpEvent(length:  7, rawData: 7 bytes, timestamp: calendar: gregorian (fixed) year: 2017  month: 8 day: 4 hour: 7 minute: 43 second: 1 isLeapMonth: false )"),  <InsulinKit.PumpEvent: 0x170295e00> (entity: PumpEvent; id:  0xd000013e81a00000 <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218408> ; data: {     createdAt = "2017-08-04 06:44:49 +0000";     date = "2017-08-04 06:43:01 +0000";     duration = 0;     pumpID = 588983;     raw = <1800812b 074411>;     title  = "NewTimePumpEvent(length: 7, rawData: 7 bytes, timestamp: calendar:  gregorian (fixed) year: 2017 month: 8 day: 4 hour: 7 minute: 43 second: 1  isLeapMonth: false )";     type = nil;     unit = nil;     uploaded = 1;     value = nil; }), true) * (Optional("BolusNormalPumpEvent(length:  9, rawData: 9 bytes, timestamp: calendar: gregorian (fixed) year: 2017  month: 8 day: 4 hour: 7 minute: 41 second: 7 isLeapMonth: false ,  unabsorbedInsulinRecord: nil, amount: 1.2, programmed: 1.2,  unabsorbedInsulinTotal: 0.0, type: MinimedKit.BolusNormalPumpEvent.BolusType.Normal,  duration: 0.0, deliveryUnitsPerMinute: 1.5)"),  <InsulinKit.PumpEvent: 0x170298f60> (entity: PumpEvent; id:  0xd000013e81940000 <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218405> ; data: {     createdAt = "2017-08-04 06:44:49 +0000";     date = "2017-08-04 06:41:07 +0000";     duration = 0;     pumpID = 588983;     raw = <010c0c00 87294704 11>;     title  = "BolusNormalPumpEvent(length: 9, rawData: 9 bytes, timestamp:  calendar: gregorian (fixed) year: 2017 month: 8 day: 4 hour: 7 minute:  41 second: 7 isLeapMonth: false , unabsorbedInsulinRecord: nil, amou";     type = Bolus;     unit = U;     uploaded = 1;     value = "1.2"; }), true) * (Optional("BolusWizardEstimatePumpEvent(length:  20, rawData: 20 bytes, timestamp: calendar: gregorian (fixed) year:  2017 month: 8 day: 4 hour: 7 minute: 41 second: 7 isLeapMonth: false ,  carbohydrates: 15, bloodGlucose: 103, foodEstimate: 1.2,  correctionEstimate: 0.0, bolusEstimate: 1.2, unabsorbedInsulinTotal:  0.0, bgTargetLow: 100, bgTargetHigh: 110, insulinSensitivity: 140,  carbRatio: 12.0)"), <InsulinKit.PumpEvent: 0x1702959a0> (entity:  PumpEvent; id: 0xd000013e818c0000 <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218403> ; data: {     createdAt = "2017-08-04 06:44:49 +0000";     date = "2017-08-04 06:41:07 +0000";     duration = 0;     pumpID = 588983;     raw = <5b678729 0704110f 500c8c64 000c0000 00000c6e>;     title = "BolusWizardEstimatePumpEvent(length:  20, rawData: 20 bytes, timestamp: calendar: gregorian (fixed) year:  2017 month: 8 day: 4 hour: 7 minute: 41 second: 7 isLeapMonth: false ,  carbohydrates: 15, blood";     type = nil;     unit = nil;     uploaded = 1;     value = nil; }), true) * (Optional("CalBGForPHPumpEvent(length:  7, rawData: 7 bytes, timestamp: calendar: gregorian (fixed) year: 2017  month: 8 day: 4 hour: 7 minute: 40 second: 59 isLeapMonth: false ,  amount: 103)"), <InsulinKit.PumpEvent: 0x17028f8c0> (entity:  PumpEvent; id: 0xd000013e81880000 <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218402> ; data: {     createdAt = "2017-08-04 06:44:49 +0000";     date = "2017-08-04 06:40:59 +0000";     duration = 0;     pumpID = 588983;     raw = <0a67bb28 270411>;     title  = "CalBGForPHPumpEvent(length: 7, rawData: 7 bytes, timestamp:  calendar: gregorian (fixed) year: 2017 month: 8 day: 4 hour: 7 minute:  40 second: 59 isLeapMonth: false , amount: 103)";     type = nil;     unit = nil;     uploaded = 1;     value = nil; }), true) * (Optional("TempBasalDurationPumpEvent(length:  7, rawData: 7 bytes, duration: 30, timestamp: calendar: gregorian  (fixed) year: 2017 month: 8 day: 4 hour: 5 minute: 24 second: 28  isLeapMonth: false )"), <InsulinKit.PumpEvent: 0x170296620>  (entity: PumpEvent; id: 0xd000013e816c0000  <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218395> ; data: {     createdAt = "2017-08-04 06:35:00 +0000";     date = "2017-08-04 04:24:28 +0000";     duration = 1800;     pumpID = 588983;     raw = <16019c18 050411>;     title = "TempBasalDurationPumpEvent(length:  7, rawData: 7 bytes, duration: 30, timestamp: calendar: gregorian  (fixed) year: 2017 month: 8 day: 4 hour: 5 minute: 24 second: 28  isLeapMonth: false )";     type = TempBasal;     unit = "U/hour";     uploaded = 1;     value = "0.4"; }), true) * (Optional("TempBasalPumpEvent(length: 8, rawData: 8 bytes, rateType: MinimedKit.TempBasalPumpEvent.RateType.Absolute,  rate: 0.40000000000000002, timestamp: calendar: gregorian (fixed) year:  2017 month: 8 day: 4 hour: 5 minute: 24 second: 28 isLeapMonth: false  )"), <InsulinKit.PumpEvent: 0x1702878f0> (entity: PumpEvent; id:  0xd000013e817c0000 <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218399> ; data: {     createdAt = "2017-08-04 06:35:00 +0000";     date = "2017-08-04 04:24:28 +0000";     duration = 0;     pumpID = 588983;     raw = <33109c18 05041100>;     title = "TempBasalPumpEvent(length: 8, rawData: 8 bytes, rateType: MinimedKit.TempBasalPumpEvent.RateType.Absolute, rate: 0.40000000000000002, timestamp: calendar: gregorian (fixed) year: 2017 month: 8 day: 4 ";     type = nil;     unit = nil;     uploaded = 1;     value = nil; }), true)  ### getRecentNormalizedDoseEntries  * DoseEntry(type: InsulinKit.PumpEventType.bolus,  startDate: 2017-08-04 06:41:07 +0000, endDate: 2017-08-04 06:41:07  +0000, value: 1.2, unit: InsulinKit.DoseUnit.units, description: nil,  managedObjectID: Optional(0xd000013e81940000  <x-coredata://4E72F56A-6EC8-4949-8954-E9A2A8E79B49/PumpEvent/p5218405>)) * DoseEntry(type: InsulinKit.PumpEventType.tempBasal, startDate: 2017-08-04 04:24:28 +0000, endDate: 2017-08-04 04:54:28 +0000, value: -0.25, unit: InsulinKit.DoseUnit.unitsPerHour, description: nil, managedObjectID: nil)  ## CarbStore  *  carbRatioSchedule: ["items": [["startTime": 0.0, "value": 12],  ["startTime": 39600.0, "value": 13], ["startTime": 54000.0, "value":  14]], "timeZone": 3600, "unit": "g"] * defaultAbsorptionTimes: (7200.0, 10800.0, 14400.0) *  insulinSensitivitySchedule: ["items": [["startTime": 0.0, "value":  115], ["startTime": 21600.0, "value": 140], ["startTime": 32400.0,  "value": 160], ["startTime": 72000.0, "value": 130]], "timeZone": 3600,  "unit": "mg/dL"] * delay: 600.0 * authorizationRequired: false * isBackgroundDeliveryEnabled: false  ### getRecentCarbEntries   ## GlucoseStore  * managedDataInterval: 10800.0 * reflectionDataInterval: 1800.0 * momentumDataInterval: 900.0 * sampleDataCache: [75 mg/dL 9F9B1FF8-6DBF-445A-883A-746A0AB297B0 "Loop" (31) "xDripG5" metadata: {     "com.loudnate.GlucoseKit.HKMetadataKey.GlucoseIsDisplayOnly" = 0; } (2017-08-04 07:49:22 +0100 - 2017-08-04 07:49:22 +0100), 73 mg/dL 007717A7-5BCC-4522-8478-70434C1D6E49 "Loop" (31) "xDripG5" metadata: {     "com.loudnate.GlucoseKit.HKMetadataKey.GlucoseIsDisplayOnly" = 0; } (2017-08-04 07:54:22 +0100 - 2017-08-04 07:54:22 +0100), 82 mg/dL 4674BBD3-92C6-486B-91DB-0FA86ED0093A "Loop" (31) "xDripG5" metadata: {     "com.loudnate.GlucoseKit.HKMetadataKey.GlucoseIsDisplayOnly" = 0; } (2017-08-04 07:59:22 +0100 - 2017-08-04 07:59:22 +0100), 111 mg/dL "xDripG5" metadata: {     "com.loudnate.GlucoseKit.HKMetadataKey.GlucoseIsDisplayOnly" = 1; } (2017-08-04 08:09:26 +0100 - 2017-08-04 08:09:26 +0100), 112 mg/dL "xDripG5" metadata: {     "com.loudnate.GlucoseKit.HKMetadataKey.GlucoseIsDisplayOnly" = 0; } (2017-08-04 08:14:22 +0100 - 2017-08-04 08:14:22 +0100)] * authorizationRequired: false   Sent from my iPhoneClick here to Reply or Forward10.49 GB (69%) of 15 GB usedManageTerms - Privacy Last account activity: 21 hours agoDetails |

**Comment by davidmlb** [comment]
After an huge analysis, I can conclude that you have not introduced the basal max..... :-)
