### ISSUE TITLE
Idea: Add option to have dexcom share as primary

### ISSUE THREAD

**Issue by joeyovens** [LoopKit/Loop#550]
Add option to have dexcom share as primary glucose source and use transmitter as backup. Live in an area where cell service isnt great for data, but it would allow for more reliable connection when it is or on wifi.

**Comment by jeremybarnum** [comment]
We have defaulted to forcing to the cloud; if fallback to the could were more reliable this would be less of an issue but as it stands for us anyway it would be useful.  Need to go back and check the rileylinktimer modification which I think might be another way to approach this.
