### ISSUE TITLE
Pump Error (minimedkit.pumperrorcode.maxsettngexceeded

### ISSUE THREAD

**Issue by dlohrman** [LoopKit/Loop#551]
Just started looping and all was working well for the first few hours. Got a red loop with the following error. Pump Error (minimedkit.pumperrorcode.maxsettngexceeded

Any help would be greatly appreciated.

**Comment by ps2** [comment]
Your max basal rate setting on your pump must be at least as high as the max basal rate setting in Loop

**Comment by dlohrman** [comment]
Excellent. I was sure it would be operator error. Thanks for the quick reply!
