### ISSUE TITLE
Ability to get BG values from Apple Health.

### ISSUE THREAD

**Issue by rsilvers129** [LoopKit/Loop#553]
If Loop could get BG values form Apple Health, then it could work offline from iosxdripreader. 

https://github.com/JohanDegraeve/iosxdripreader/

**Comment by loudestnoise** [comment]
This should already work. I get BG readings from my One Drop app that are
written to HealthKit and they show up in Loop. It’s just a matter of
enabling ALLOW “LOOP” TO READ DATA and turning on Blood Glucose in the
Health app.

- D

On August 23, 2017 at 4:02:55 PM, rsilvers129 (notifications@github.com)
wrote:

If Loop could get BG values form Apple Health, then it could work offline
from iosxdripreader.

https://github.com/JohanDegraeve/iosxdripreader/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LoopKit/Loop/issues/553>, or mute the thread

**Comment by rsilvers129** [comment]
Hmm. I only asked because I read that this is what was needed to make that work. But I will turn off WiFi and cellular data to Loop and test it.

**Comment by loudestnoise** [comment]
The other important thing would obviously be having iosxdripreader or whatever sources are writing BGs to have that ability. That way Loop can read them.

**Comment by danielharrelson** [comment]
I thought the issue was that Loop is unable to read from the HealthKit once it is a background running app. It must be in the foreground to pull from the HealthKit. JohanDegraeve was saying something about that the other week.

**Comment by rsilvers129** [comment]
I can confirm that I turned off cellular data and WiFi, and Loop was able to see the BG, evidently through Apple Health. 

I will test it in the background.

**Comment by danielharrelson** [comment]
@rsilvers129 I did it the other night. It didn't end up well, I woke up 4 hours later with a high, and loop had not been running for awhile. Give it > 1 hour, and it'll just stop working if loop is in the background.

**Comment by danielharrelson** [comment]
The HealthKit data is only kept locally on the user’s device. For security, the HealthKit store is encrypted when the device is locked. The HealthKit store can only be accessed by an authorized app. As a result, you may not be able to read data from the store when your app is launched in the background; however, apps can still write data to the store, even when the phone is locked. HealthKit temporarily caches the data and saves it to the encrypted store as soon as the phone is unlocked

https://developer.apple.com/documentation/healthkit

So if the phone is locked, loop will not run properly.

**Comment by rsilvers129** [comment]
I just backgrounded Loop, kept Mail in the foreground, and waited over 10 minutes. I went back to Loop, and it was green, and said last loop was a minute ago. 

So it does work when not in the foreground.

As for when the iPhone is locked - I can live with that. If I go skiing in some far away place for the day where there is no cellular signal, it sounds like I can just set my iPhone to not lock?

**Comment by rsilvers129** [comment]
So now I have a problem where iosxdripreader looks like it is not working, but NightScout is being updated with the BG data. Anyone see this happen?

![img_8715](https://user-images.githubusercontent.com/4177461/29640894-0a28e178-882f-11e7-849c-3f546a19cd15.PNG)

**Comment by rsilvers129** [comment]
Loop does this, so I will close it.
