### ISSUE TITLE
Mean display for last 24 hours moving window on HUD.

### ISSUE THREAD

**Issue by rsilvers129** [LoopKit/Loop#554]
When I first started, I was running statistics on NightScout every day. Lately, I have not been doing that. And when I did, my results were slipping somewhat as I was eating more carb.

If we had a readout of the 24, 7 day, and 30 day average and maybe estimated A1C on the screen at all times, it would be easier to see if things are going well, and encourage every day to be a better result. 

Long-term results are made up of the daily results, so I think it would help a lot.

**Comment by Kdisimone** [comment]
I realize this isn't a Loop feature per se, but I'd say that the health app is super useful for this info.  Our endo regularly uses the Health app records when we meet with her.  We use the carbs and BG averages (weekly, monthly, max/min and avg) from there to discuss how we've been doing (in addition to the dexcom downloads they do).

**Comment by Kdisimone** [comment]
Closing this issue.  Information is available in Health app relatively quickly and would be appropriate place given the infrequent need to access it.
