### ISSUE TITLE
Add option to send Dex data to Nightscout

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#565]
Currently one must enter the Dexcom credentials into Nightscout to get the data that is already in Loop but not uploaded as is for Medtronic CGM data.  Would it be possible to have an option to do the upload to Nightscout from Loop?

**Comment by danielharrelson** [comment]
Did you input your APISecret into the NightScout config of loop? My loop uploads data to nightscout (carbs, etc).

**Comment by beached** [comment]
Nightscout works for all other items.  I had to setup nightscout to pull from dex share separately and store the credentials in Nightscout vs Loop, which is more secure and already using them, doing the upload along with the other data

**Comment by Kdisimone** [comment]
closing issue. there has not been any additional requests for this function and CGM data coming from share servers through Nightscout Bridge is a solid solution. Does not require cell/wifi and is robust solution as is.
