### ISSUE TITLE
Inconsistent spacing between Settings sections

### ISSUE THREAD

**Issue by jessiepusateri** [LoopKit/Loop#573]
In the Settings menu, I have noticed that there is no spacing between the "Loop" and "Devices" sections. (see Screenshot: Spacing) This difference is even more noticeable when a user increases their system-wide text size due to the header font size staying the same and the spacing not being present. (see Screenshot: Increased Font Size)

When I looked at the code to find the reason behind this, I discovered that that the "Devices" section header is a custom header to accommodate the spinner. I am wondering if the spinner is necessary and if the default header would make more sense. I included screenshots of what it would look like with/without the spinner in both situations.

Screenshot: Spacing

Custom Header (With Spinner)         | Default Header (Without Spinner)
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/5507833/30000298-c3743382-9034-11e7-8928-9d57de9cac89.png" width="250"/>  |  <img src="https://user-images.githubusercontent.com/5507833/30000299-c6a93e6c-9034-11e7-9093-3f2f627c6c35.png" width="250"/> 

Screenshot: Increased Font Size

Custom Header (With Spinner)         | Default Header (Without Spinner)
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/5507833/30000426-63fceab6-9039-11e7-8335-9a4b0f227f64.png" width="250"/>  |  <img src="https://user-images.githubusercontent.com/5507833/30000346-63a747b2-9036-11e7-9036-89bc28d812ec.png" width="250"/>

**Comment by ps2** [comment]
Great point about the inconsistency in font size and spacing; those are fixable. I think it's reasonable to see a spinner so the user knows we're searching for RileyLinks (especially if the list is empty).
There are vastly improved APIs in iOS 11 that might help in solving this if you want to take a swing at it.

**Comment by jessiepusateri** [comment]
Sounds great, I would love to work on it. Are they any specific parts of the APIs in iOS 11 that I should look at first?

**Comment by ps2** [comment]
This video goes over the new features around Dynamic Type : https://developer.apple.com/videos/play/wwdc2017/245/

**Comment by jessiepusateri** [comment]
Awesome, thanks!

**Comment by Kdisimone** [comment]
outdated issue with pump manager and cgm manager changes to the UI
