### ISSUE TITLE
When bolus fails to deliver with Okay to Try Again - Bolus Amount Changes to 0.00 on Retry

### ISSUE THREAD

**Issue by denvergail** [LoopKit/Loop#588]
I entered carbs into the carb screen, pressed save, received a suggested bolus amount of 2.22u, pressed deliver, authenticated, then got the "Failure to Deliver, Okay to Try Again" message.

I immediately pressed the bolus delivery icon, expecting to see the same recommended bolus amount. Instead it showed 0.00 as the bolus amount. I manually entered the original suggested amount of 2.22u. Pressed deliver, authenticated. I again got the failure error, ok to try again.

Then deleted the original 35g of carb, went back to the carb entry screen and entered the same # of carbs - but the suggested bolus was again 0.00.

I manually entered 2.22u (maybe I entered 2.2u) and pressed deliver, authenticated, and it finally delivered. Pump event pic is attached for the manual bolus amount. Issue report is also attached (time of issue was around 5:48pm MT.) 

![pump event 22 sept 2017 devore](https://user-images.githubusercontent.com/8145371/30769586-62ba745c-9fd9-11e7-8e9a-0285a5256561.PNG)

[issue report 22 sept 2017 devore.pdf](https://github.com/LoopKit/Loop/files/1326246/issue.report.22.sept.2017.devore.pdf)

**Comment by denvergail** [comment]
I forced the error to recreate this morning and took screen shots. Will add later if possible.

**Comment by denvergail** [comment]
![img_1102](https://user-images.githubusercontent.com/8145371/30774569-d0505348-a041-11e7-8582-d2c3abc984a0.PNG)
![img_1103](https://user-images.githubusercontent.com/8145371/30774568-d04f19a6-a041-11e7-8457-05ffccc9b344.PNG)

**Comment by Kdisimone** [comment]
I've just tested this issue on Loop v 1.9 and the issue appears resolved.  Multiple instances of failed bolus still brought up the same recommended bolus amount.  The original issue appears to be resolved now.  Thanks
