### ISSUE TITLE
Loop 1.5 header disappears when iPhone6s+ is rotated

### ISSUE THREAD

**Issue by denvergail** [LoopKit/Loop#592]
iPhone6sPlus

Loop header is visible only when phone is vertical. When phone is rotated, header disappears. 

![img_1138](https://user-images.githubusercontent.com/8145371/30794919-35f8878c-a188-11e7-80b3-af1aeab7b116.PNG)
![img_1139](https://user-images.githubusercontent.com/8145371/30794920-35f8efd8-a188-11e7-9fab-fb018257c311.PNG)

**Comment by ps2** [comment]
This is working as intended.  The horizontal view's design purpose is to show the graphs over a longer timeline, and to do that more effectively, the status bar is hidden.
