### ISSUE TITLE
Loop connection keeps dropping

### ISSUE THREAD

**Issue by dpanzirer** [LoopKit/Loop#595]
For the last 3 weeks Loop has been dropping out at least 1/3 of the time.  I have tried switching pump as well as Riley Links and phone, all with the same result.  Below are 3 reports - from from today, one yesterday and one Monday

[Issue reports Sept 2017.docx](https://github.com/LoopKit/Loop/files/1340502/Issue.reports.Sept.2017.docx)

**Comment by ps2** [comment]
If you are still having issues, please try updating to 11.0.2.  There are reports that this update improves reliability.

**Comment by DConmy** [comment]
I had problems on iOS 11.0.3 as well.   So far (~24 hours), I have not had problems with iOS 11.1.

**Comment by Kdisimone** [comment]
@dpanzirer has this issue resolved?  It's a pretty old issue and i'm hoping obsolete by now as Loop and iOS have undergone some updates in the meantime.  I'll close this out with that assumption, but if I'm incorrect, let me know and I'll reopen.

**Comment by dpanzirer** [comment]
yes this is all old

**Comment by Kdisimone** [comment]
thanks!
