### ISSUE TITLE
Loop 1.5 Suggests Bolus When BG is Below Suspend Threshold

### ISSUE THREAD

**Issue by denvergail** [LoopKit/Loop#596]
1. My Suspend Threshold is set at 80.
2. My BG was below 80 (at 71 or below).
3. I consumed 20 carbs and recorded in Loop.
4. Loop recommended a bolus, but I cancelled it.
5. I opened the bolus screen immediately after that to make sure that what I thought I saw really happened (suggested bolus even though current BG was below suspend threshold).
6. Not only did it suggest another bolus, it INCREASED the suggested amount from the previous suggested bolus amount. Again, I cancelled it.
7. Repeated steps 5-6 a few times. Each time, the suggested amount increased from previous amount.

Please note other variables: At the time of this event, Loop was reporting the anticipated BG at 5 hours into the future at over 200 and had been reporting high future values for several hours. I assume that the future BG value is why I was receiving high temps during this time and is the reason I was low at the time I experienced this suggested bolus event. I finally greatly reduced the absorption time from earlier entries to get the future prediction to normalize. My BG maintained low-ish overnight (below target but not low enough to treat)  after adjusting the absorption time on those earlier entries.

![img_0524](https://user-images.githubusercontent.com/8145371/31091836-811975c8-a769-11e7-91dd-92f245e93595.jpg)
![img_1218](https://user-images.githubusercontent.com/8145371/31091834-80c1bc2a-a769-11e7-96ac-0ffc8fc311d0.PNG)
![img_1219](https://user-images.githubusercontent.com/8145371/31091832-80be6e3a-a769-11e7-9c70-22a45c7d5092.PNG)
![img_1220](https://user-images.githubusercontent.com/8145371/31091831-80bd7dd6-a769-11e7-94a5-10a4f28559b1.PNG)
![img_1221](https://user-images.githubusercontent.com/8145371/31091833-80bebe80-a769-11e7-909e-59256922915b.PNG)

**Comment by ps2** [comment]
The time on the screenshot on the settings is after the time of the bolus recommendation.  Is it possible that the suspend threshold was changed after the recommendation? The code does seem to behave as expected when we test situations like this. So the evidence points to a later settings change.

**Comment by denvergail** [comment]
No change to suspend threshold at any point. I have never changed it. It has always been at 80.

**Comment by denvergail** [comment]
In fact, if you look at the message at the top of each of the bolus screens, it says current BG of 71 is below the correction range. THAT is what got my attention that it was recommending any amount at all.

**Comment by ps2** [comment]
The message on the bolus screen indicates that it is below the correction range, not below suspend threshold.  Those are two different things.

If you can reproduce this, please attach an issue report.  That would help us see what's going on.

**Comment by denvergail** [comment]
I see that. But, the fact stands that my suspend threshold is set to 80 and my BG was 71 while recommending correction. I have a note on the issue report about the projected BG of a high/higher #. Is that a factor?

I will force a low bg # through the health app to see if I can recreate the problem.

Thanks!

**Comment by ps2** [comment]
Loop doesn't support reading BG from HK as a data source, so that may not recreate the problem; you may have other issues.

Loop should still not suggest a bolus if current bg is below suspend threshold, even if eventual bg is higher.

Capturing an issue report from Loop would be the best way for me to be able to identify the issue. Please do not cause a low to test! :)

**Comment by ps2** [comment]
Perhaps capturing an issue report now might highlight if there is some mismatch in settings.

**Comment by denvergail** [comment]
I entered 55 into HK and then managed to get this screen shot which says that my predicted bg of 59 is below suspend threshold. (My real BG is >120). I also entered a meal of 100 carbs so that is showing in this too. I think that is interesting. 

In the original situation I don’t recall seeing that specific message of suspend threshold (but I missed grabbing a screen shot the very first time I saw a recommended bolus.). I will keep my eye on it most definitely. 

Thanks for all your help.

**Comment by jeremybarnum** [comment]
This is unrelated to the issue, but I see your insulin model is fiasp.  Are you actually using fiasp? If not, the differences in peak time could create significant issues.

**Comment by ps2** [comment]
@denvergail your last comment seems to indicate that you wanted to attach a screenshot.  It seems like it didn't come through.

**Comment by denvergail** [comment]
Yes, I am using Fiasp.

Thanks for checking.

**Comment by denvergail** [comment]
Pete: I added the screen shot to my comment a few above. It didn't come through while I was responding via email.

**Comment by denvergail** [comment]
Attaching issue report now. Maybe you can see something I've missed. Thanks again!
[deVore issue report 10-06-17.pdf](https://github.com/LoopKit/Loop/files/1363664/deVore.issue.report.10-06-17.pdf)

**Comment by denvergail** [comment]
Yes to the extent that I was concerned.
