### ISSUE TITLE
Not connection loop-pump

### ISSUE THREAD

**Issue by davidmlb** [LoopKit/Loop#600]
See enclosed the report. I have problems because loop is not receiving bg data and reservoir from pump
Loop v1.5.0

## DeviceDataManager

launchDate: 2017-10-05 18:48:30 +0000

cgm: Optional(Loop.CGM.enlite)

lastError: Optional((date: 2017-10-05 18:54:32 +0000, error: RileyLinkKit.PumpCommsError.noResponse("Sent PumpMessage(carelink, powerOn, 372160, 0201010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)")))

latestPumpStatusFromMySentry: nil

pumpState: Optional(## PumpState

timeZone: GMT+0200 (fixed)

pumpRegion: North America

pumpModel: 554

lastHistoryDump: 0000-12-30 00:00:00 +0000

awakeUntil: 0000-12-30 00:00:00 +0000

lastWakeAttempt: Optional(2017-10-05 18:57:55 +0000))

preferredInsulinDataSource: Event History

## EnliteCGMManager

sensorState: nil

## RileyLinkDeviceManager

timerTickEnabled: true

idleListeningEnabled: true

idleTimeout: 60.0

## RileyLinkDevice

name: RileyLink Esther

RSSI: -65

lastIdle: 2017-10-05 18:56:00 +0000

lastTuned: 2017-10-05 18:57:56 +0000

radioFrequency: 0.0

firmwareVersion: subg_rfspy 1.0 / ble_rfspy 0.9

state: Connecting

## StatusExtensionDataManager

appGroupName: group.com.estherg2.LoopGroup

statusExtensionContext: nil

## LoopDataManager

settings: Loop.LoopSettings(dosingEnabled: false, dynamicCarbAbsorptionEnabled: true, glucoseTargetRangeSchedule: Optional(["items": [["startTime": 0.0, "value": [85.0, 100.0]]], "timeZone": 7200, "overrideRanges": [:], "unit": "mg/dL"]), maximumBasalRatePerHour: Optional(6.0), maximumBolus: Optional(12.0), suspendThreshold: Optional(Loop.GlucoseThreshold(value: 40.0, unit: mg/dL)), retrospectiveCorrectionEnabled: false)

insulinCounteractionEffects: [LoopKit.GlucoseEffectVelocity(startDate: 2017-10-05 18:11:00 +0000, endDate: 2017-10-05 18:16:00 +0000, quantity: -0.167696 mg/min·dL), LoopKit.GlucoseEffectVelocity(startDate: 2017-10-05 18:16:00 +0000, endDate: 2017-10-05 18:21:00 +0000, quantity: 0.0121924 mg/min·dL)]

predictedGlucose: []

retrospectivePredictedGlucose: []

recommendedTempBasal: nil

lastBolus: nil

lastGlucoseChange: nil

retrospectiveGlucoseChange: nil

lastLoopCompleted: nil

lastTempBasal: nil

carbsOnBoard: nil

insulinOnBoard: Optional(InsulinKit.InsulinValue(startDate: 2017-10-05 18:55:00 +0000, value: 0.21056125601503389))

error: Optional(Loop.LoopError.missingDataError(details: "Glucose data not available", recovery: Optional("Check your CGM data source")))

Thanks

**Comment by ps2** [comment]
This looks like the phone is having bluetooth issues. (state: Connecting).  See https://loopkit.github.io/loopdocs/use/green-loop/#bluetooth-failures-rl-or-iphone-issue
