### ISSUE TITLE
If both Dexcom and Enlite data is available, both are displayed/used

### ISSUE THREAD

**Issue by panctronic** [LoopKit/Loop#610]
I'm wearing an Enlite and Dexcom sensor currently. Loop is plotting data from both, and using the lower value (from the Enlite) instead of my preferred option in the settings (the Dexcom).

**Comment by irisbijen** [comment]
What kind of transmitter are you using for the enlite?

**Comment by Kdisimone** [comment]
@panctronic Is this still an issue?  do you have both sliders on in the CGM selection for Loop settings?  Perhaps turning off one of them would help?

**Comment by Kdisimone** [comment]
Resolved.  Single CGM source enforced in upcoming CGM monitor. https://github.com/LoopKit/Loop/pull/364
