### ISSUE TITLE
Pre-entering meal creates bolus suggestion regardless of insulin type

### ISSUE THREAD

**Issue by tim2000s** [LoopKit/Loop#613]
I entered a meal carb amount of 100g 20 mins before I was due to eat using the default absorption and with the Fiasp curves enabled, and Loop suggested a large (12.4u) bolus. 

Based on experience with Fiasp, had I taken that 20mins before eating I’d have been very hypo before the meal had properly started absorbing.

I’d suggest that for Fiasp, a bolus suggestion is only given if carbs are entered a configurable maximum period before eating them, due to the different effects people have seen, with a default max of five minutes.

**Comment by Kdisimone** [comment]
A five minute prebolus cap for us is too short. We can prebolus at least 10min for some foods.

**Comment by Kdisimone** [comment]
And depending on if we are above target significantly, even more

**Comment by ps2** [comment]
If you enter 100g for 20 minutes in the future, the bolus suggestion will be scaled back based on the bolus happening now, and still not allowing the prediction to drop below suspend threshold.

This works for 20 minutes, or 2 hours into the future.

If you see behavior that contradicts this, then it's likely a bug.  Please attach an issue report and screenshots if you think it isn't operating this way.

**Comment by tim2000s** [comment]
I was testing the Dynamic Carb Absorption (DCA) feature, and while knowing that the food I would be eating has a longer absorption than three hours, simply entered the default setting to see what happened. The resultant bolus was obviously large due to the absorption period, and based on prior experience of large boluses with Fiasp, this would have caused a hypo that the dynamic algorithm wouldn't have avoided. 

I don't have a problem with this being the defined behaviour, but the docs probably need updating to inform that if you rely on dynamic carb absorption then you need to consider suggested bolus carefully.

**Comment by dm61** [comment]
@tim2000s was your suspend threshold set to a low value?

**Comment by Kdisimone** [comment]
Closing issue as this is not an unexpected Loop behavior.  Per the poster's suggestion, I will review docs and improve where needed.  Thank you.
