### ISSUE TITLE
loopUI swift 4.0.2 - xcode 9.1

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#616]
Hi @ps2 , can you update it? I was curious to see the new apple icons made available.
thank you Matteo

<img width="814" alt="schermata 2017-11-02 alle 08 46 26" src="https://user-images.githubusercontent.com/9915825/32314951-76943efe-bfaa-11e7-9fad-bae5e6648d65.png">

**Comment by francescaneri** [comment]
ideas  @CrushingT1D?

**Comment by Kdisimone** [comment]
An update to Xcode came out yesterday. Until Loop is updated to match, please do the following:

1.  close Xcode

2.  Open Terminal app

3. Use the command:

cd Downloads/Loop-master

(If your Loop folder is named differently or stored somewhere other than your downloads folder...change the names above accordingly)

4.  Use the command:

carthage bootstrap

5.  Open the Loop project in Xcode and build like usual.

**Comment by francescaneri** [comment]
ok, thank you for trying to do it
