### ISSUE TITLE
pills in nightscout

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#622]
<img width="417" alt="schermata 2017-11-05 alle 10 39 44" src="https://user-images.githubusercontent.com/9915825/32413634-fe90f3c0-c215-11e7-95a5-979ec6b772b6.png">
 
I wanted to ask if it was possible to add as information:
1) Probably Glycemia (Predictive Value)
2) insulin deliver
3) isf
4) target

**Comment by francescaneri** [comment]
<img width="573" alt="schermata 2017-11-05 alle 10 48 40" src="https://user-images.githubusercontent.com/9915825/32413676-fd28b864-c216-11e7-86d2-13ea1a786a38.png">

**Comment by dm61** [comment]
I'll look into adding recommended bolus to the pill. Eventual predicted bg value could also be added. Loop currently does not upload target or isf to NS, so at the moment there is no way to include those in the pill. Uploading forecast components to NS is in the plans for Loop, see #518, so eventually we'll be able to add those to the pill.

**Comment by francescaneri** [comment]
@dm61 Thanks you.

**Comment by Kdisimone** [comment]
Dev branch now uploads ISF, basals, carb ratios to your ns profile. And if an override is running, that information is displayed in override pill. This addresses the (long standing) request to have that information available from Loop in NS.
