### ISSUE TITLE
Possibility to command fill cannula (from loop)

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#624]
I find myself sometimes needing to do a cannula fill to settle bubble problems or poor absorption. I think that being able to control it as a loop can be convenient.

**Comment by francescaneri** [comment]
@Kdisimone nobody cares and closes. obviously you never have bubble problems. lucky you. ;)

**Comment by francescaneri** [comment]
@Kdisimone nobody cares and closes. obviously you never have bubble problems. lucky you. ;)

**Comment by elnjensen** [comment]
@francescaneri  Let's try to keep the discussion here positive.  No one working on a particular issue doesn't necessarily mean that no one cares about it - but there are lots of things people can work on, and not every feature request can be implemented.  In this particular case, I don't think that the cannula fill command is even one of the commands that can activated remotely.  But even if it were, someone would have to spend the time to code it, and that means they wouldn't be spending time on something else.
