### ISSUE TITLE
Request: Nightscout Notes

### ISSUE THREAD

**Issue by danielharrelson** [LoopKit/Loop#625]
Would be nice if there was a place to type in short notes when doing treatments.

Emoji is cool, but sometimes you need some extra text notes :)

**Comment by Kdisimone** [comment]
You can type in notes already.  If you click on the plate icon while entering in a carb, it displays all the custom icons.  At the bottom left corner is an “abc” button that will allow you to type notes in the Food Type line. This note will appear in NS next to the carb entry. 

Alternatively, you can also enter a note using NS careportal at anytime.

**Comment by danielharrelson** [comment]
Fantastic!
