### ISSUE TITLE
Screen jumps & flits when font is enlarged.

### ISSUE THREAD

**Issue by jath622** [LoopKit/Loop#626]
When running Loop 1.5.1dev on iPhone 7+, if you enlarge thee font thru system prefs in iOS, the screen will jump continuously, making it almost impossible to use any of the lower commands such as Read Pump Status, Send Button Press, Change Time. Putting font back to regular size solves the issue.

**Comment by francescaneri** [comment]
can you attach a screenshot?

**Comment by jath622** [comment]
Haven’t been able to figure out how to do it as it’s in .mov format and that’s not an allowed format here.

**Comment by Kdisimone** [comment]
@jath622 this issue has been resolved with updates, correct?

**Comment by jath622** [comment]
Yes, resolved.  Thx Katie.
