### ISSUE TITLE
swift compatibility

### ISSUE THREAD

**Issue by matejkovac** [LoopKit/Loop#627]
Hi, please can somebody help me with this? All is updated to latest versions. Thank you very much.[/Users/Matej/Downloads/Loop-master/LoopUI/Views/ChartPointsContextFillLayer.swift:8:8: Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /Users/Matej/Downloads/Loop-master/Carthage/Build/iOS/SwiftCharts.framework/Modules/SwiftCharts.swiftmodule/arm64.swiftmodule](url)

**Comment by matejkovac** [comment]
![screen shot 2017-11-11 at 19 47 12](https://user-images.githubusercontent.com/33546863/32692789-d5bdc24e-c71e-11e7-85db-a391d65a1fcd.png)

**Comment by Kdisimone** [comment]
This is being addressed on Facebook.

**Comment by schulzedj** [comment]
I've been getting the same issue- gray loop now for a week...darn

**Comment by Kdisimone** [comment]
@schulzedj https://loopkit.github.io/loopdocs/build/installing/#build-errors

**Comment by Kdisimone** [comment]
fixed with update https://github.com/LoopKit/Loop/pull/650 and loopdocs
