### ISSUE TITLE
Feature : Integrate Pump simulation to use Loop in Open loop mode 

### ISSUE THREAD

**Issue by osodebailar** [LoopKit/Loop#633]
I request the feature to use Loop in Open-loop mode for users they have a pump that can't be integrated in Loop Software ( medtronic 640G, Omnipod in the moment etc. )
It is the same feature you can see in Android APS.
I think it is very helpful to drive in Open-loop mode for other pump customers.
It would be a great advantage for many users , because they can stay on iphone and Loop is more easy in use than Android APS  .

**Comment by PatriqB** [comment]
I understand that one should/could support requests - so I would humbly  like to raise my support for this.

**Comment by PatriqB** [comment]
I see that this is also requested in #257

**Comment by ps2** [comment]
Closing as dup of #257
