### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by natsera** [LoopKit/Loop#634]
When I try to run Loop, I get a gray circle and both/either: Missing data: Glucose data not available and Missing data: Reservoir not available 

[LoopIssue.txt](https://github.com/LoopKit/Loop/files/1524308/LoopIssue.txt)

**Comment by elnjensen** [comment]
You'll need to provide more information for people to be able to help you.  What have you tried?  Have you tried all of the things here?  https://loopkit.github.io/loopdocs/use/green-loop/

**Comment by natsera** [comment]
Thanks for your reply, Eric.

The first thing I forgot to say is that I’m not using any Dexcom apps
because of Medicare. So I am using Nightscout Share Server. I have a
rebuilt g5 transmitter.

 I went through the things under pump in the getting a green Loop and the
grey to green Loop sections and  everything is correct so far as I can
tell.

My Nightscout site has been down since about noon. So the missing data
about BGs is from that. I really don’t know how to fix it. I never used to
have this kind of problem when I had an azure Nightscout site.

I have iOS xDrip reader and it follows the NS site, so it’s currently not
registering anything either.

I was looking at Mlab and it speaks of connecting either with Mongo shell
or driver via standard MongoDB URI. I don’t understand that — connect what
to what where?

So I’m wondering if all the problems are because my sites are not
configured properly.

I know my Loop build was successful — some yellow errors but no red ones.
So I need help to make the gears mesh. Bear in mind that I am not a
computer person — just an older lady with hypoglycemia unawareness who
wants to avoid those dangerous lows and highs. I’m confident that I can USE
Loop properly if only I can get it working!

Thank you for any help you can give me. If I think of anything else, I’ll
send you another message.

**Comment by natsera** [comment]
Just looked on Heroku again, and when I clicked on the Pump pill (?) it says undefined. What do I have to do to fix that? It also has Loop as unknown.

**Comment by natsera** [comment]
Heroku just came up again, and I'm getting readings now. So the only problem is that clicking on the gray loop gives Missing data: Reservoir  and BG with a little yellow circle on it. And I'm not getting any corrections from Loop.

**Comment by Kdisimone** [comment]
Resolved in gitter, issue was with NightscoutShareServer settings.
