### ISSUE TITLE
Allow easier customization of low battery warning threshold

### ISSUE THREAD

**Issue by elnjensen** [LoopKit/Loop#645]
On pumps without MySentry, Loop monitors the pump battery voltage and alerts the user to "Change the pump battery immediately" when the voltage hits a hard-coded threshold, [currently set at 1.20 V](https://github.com/ps2/rileylink_ios/blob/master/MinimedKit/BatteryChemistryType.swift#L36) for alkaline batteries.  However, at this point the Minimed pump still shows charge remaining and comms still function; the threshold where the pump stops communicating is when the battery voltage reaches 1.16 V.   Some users may wish to take advantage of the additional battery life, and continue to use the current battery down to at or near this threshold.   In my testing with a 522 pump, I get an additional 12-13 hours of battery life between 1.20 V and 1.16 V. 

However, as currently coded, Loop will continue to warn the user to change the battery very frequently.  It would be nice if it were possible to change the voltage threshold more easily, but since it is in MinimedKit, it requires downloading and compiling that separate framework, which is significantly more complicated for the average user than just making a code customization in the Loop source code itself. 

I see a few possible solutions: 

1.  Move the battery code into Loop.  It's not a lot of code, but this might violate some overall principle of having anything that's Minimed-specific be in a separate framework.  (I don't know if that's a principle or not.)  In Loop, it could be easily customized by a user. 

2.  Leave the battery code in MinimedKit, but change that code so that the threshold voltage (`batteryChemistry.minVoltage`) is a variable that can be changed externally.  Currently it can't be, since it is set in a case statement (for alkaline vs. lithium).  That would require (I think) defining separate `minVoltage` variables specifically for alkaline and lithium batteries.  In that case, the code in MinimedKit/BatteryChemistryType.swift would be slightly less clean, but changing the value externally would be a simple one-liner that could be documented in the Loop docs. 

3.  Leave all the code as-is, but document in Loop docs how to change it.  It's a little ugly since it involves basically replicating some of the MinimedKit code in Loop itself, but it looks like this.  In `DeviceDataManager.swift`, [line 56](https://github.com/LoopKit/Loop/blob/master/Loop/Managers/DeviceDataManager.swift#L56), replace this

```
   return batteryChemistry.chargeRemaining(voltage: status.batteryVolts)
```

with this: 
 
```
          if batteryChemistry == .alkaline {
              // Override RileyLink's voltage percentage calculation, which
              // hits zero at 1.20 V; go all the way down to just before the
              // end of pump comms at 1.16 V.  On 522 pumps, this gives
              // about an hour's warning; customize as your comfort level dictates:
              let alkalineMinVoltage = 1.17
              let computed = (status.batteryVolts - alkalineMinVoltage)/(batteryChemistry.maxVoltage - alkalineMinVoltage)
              return max(min(computed, 1), 0)
          } else {
              return batteryChemistry.chargeRemaining(voltage: status.batteryVolts)
          }
```

4.  Add a preference setting in the app to customize the threshold voltage.  This is the easiest for the user, but the most work to code.  We would probably want to limit the range of possible values for this parameter.  Setting it to 1.16 V or below means that Loop would never alert the user, since once the pump hits that voltage it can no longer communicate.  So 1.17 V should be the floor. 

I'll note that this feature request is similar to #362 opened by @wkcwells , though this is a little narrower in focusing only on battery notifications and how to customize them, whereas that was also about reservoir notifications. 

This is a non-issue for pumps with MySentry, since they don't report zero battery until the pump reaches the 1.16 V threshold. 

I'd be happy to tackle this, but would appreciate thoughts on the best way to do it to be consistent with overall design principles in Loop.

**Comment by AndrewRBraun** [comment]
I am very supportive of option 4, having a preference setting in the app. Unfortunately I am not a techie, so cannot help with this.

**Comment by AndrewRBraun** [comment]
Eric, can you please explain how to do option 3 more clearly for those not used to coding. 
I am confused whether or not to include the text within this wacky symbol { } 
Or do I include all the free text you’ve written?
Thanks, Andrew

**Comment by elnjensen** [comment]
@AndrewRBraun   Just find the line I link to in the first part, and then cut and paste everything in the second box in its place.  Yes, you have to include things that are within those brackets. 

Optionally, you can leave out any lines that start with // , since they are comments in the code that don't do anything.  However, I'd suggest leaving them in, since they help make it clearer to anyone reading those lines what is going on there. 

For what it's worth, I'm now using 1.18 V rather than 1.17 V.  The latter was a little bit of short notice sometimes.
