### ISSUE TITLE
App crashes if Loggly token has an invalid character

### ISSUE THREAD

**Issue by achkars** [LoopKit/Loop#655]
Accidentally copy/pasted a Loggly token with trailing hidden characters.
Caused the app to crash afterwards (see screenshot for details).

Input field should check for invalid characters after user input.

![image](https://user-images.githubusercontent.com/34329790/34458017-3e9c9f5e-ed91-11e7-9a17-e639e11bb82a.png)

**Comment by dabear** [comment]
I don't use loggly, but this silences the error at least:
inside the func url, add:
let token = token.addingPercentEncoding(withAllowedCharacters: .alphanumerics)!

**Comment by ps2** [comment]
Fixed in https://github.com/LoopKit/LogglyService/commit/e780fa2db1e407d36fcbc84a9704742422be8642
