### ISSUE TITLE
Send diagnostic data to Nightscout

### ISSUE THREAD

**Issue by loudnate** [LoopKit/Loop#66]
As a prerequisite to dumping the mLab API integration, we can instead send some of the existing diagnostic data to Nightscout. There's some open issues to resolve:
- It sounds like the Nightscout web UI isn't built to handle the volume of status data that the OpenAPS users are sending. Waiting for these two stakeholders to sort things out might be best.
- iOS 10's new logging and activity tracing (and the macOS Sierra Console app) will be a much more user-friendly way for individuals to read logs. Where is the balance between what needs to be available remotely vs what can be available when the phone is physically plugged into a Mac?
- Some of the diagnostic data should first be made available offline, directly within the app. `CommandResponseViewController` can adapt to this use-case easily.

**Comment by loudnate** [comment]
https://developer.apple.com/reference/os/1891852-logging

**Comment by ps2** [comment]
Yes, Loop sends a fair amount of diagnostic data at this point.

**Comment by Nightfoxy** [comment]
Is there another issue that asks to send the red loop error to the NS pill? That behavior works for MDT pumps but not pods.
