### ISSUE TITLE
BluCon Nighrider Freestyle Libre sensor add

### ISSUE THREAD

**Issue by heba29** [LoopKit/Loop#662]
Would it be possible to include the BluCon Nightrider for the Freestyle Libre (FSL) as blood glucose sensor in the APP? Many T1 in Germany get the FSL paid by the health insurance company. That would be literally a good thing.

**Comment by osodebailar** [comment]
It would be a very good idea . Libre data via Blucon and iosxdreapreader to Loop .

**Comment by heba29** [comment]
Unfortunately I had to give up the ios version, because I got a new DANA R pump. I can now connect the DANA R, FSL, Nightrider with the software xDRIP+ and AndroidAPS via Bluetooth and do a loop. Without the reylink. That's very nice - but the IOS app is much nicer in terms of design. Therefore it would be nice to use the FSL. Maybe with a DANA R or RS in the future.

**Comment by dabear** [comment]
The Spike app for ios (partly based on iosxdripreader) has a built in webserver compatible with dexcom share. You can use this to loop offline.

Loop itself does not currently support libre directly (without using spike/iosxdripreader). While dexcom transmits the calibrated glucose values, the libre with blucon only transmits raw values. Supporting blucon inside loop would require calibrations to be coded for libre inside of Loop.

**Comment by peterhallforone** [comment]
And since iosxdrip also has a Dexcom share function it would be poosible to use it for Loop?

**Comment by dabear** [comment]
Can this be closed?
