### ISSUE TITLE
Errant multiple bolus events when changing time during bolus

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#667]
If you change time using RL while a bolus event is ongoing, the pump errantly records pump bolus events of varying units.  The active insulin appears to be incorrect on the main screen graph however.  This was an experiment delivering a single 1.6 unit bolus.  I watched the pump and confirmed it only delivered a single 1.6 unit bolus.  Perhaps we can have a check that change time commands are locked out if a bolus is in progress?  The first few change time commands that I issued while the bolus was in progress were returned with a comms error, but then the command finally went through.  Looks like the Loop recorded all the attempts, both the ones with the comms error and when change time command went through with success.  Or perhaps some other solution?

![img_8756](https://user-images.githubusercontent.com/12402160/35179769-94b72278-fd55-11e7-8d7c-47e3c295d323.PNG)
![img_8757](https://user-images.githubusercontent.com/12402160/35179771-96b9b0ae-fd55-11e7-8264-5cc5061c67dd.PNG)
![img_8758](https://user-images.githubusercontent.com/12402160/35179773-9a07531a-fd55-11e7-82b1-c8d2d8117d23.PNG)
![img_8760](https://user-images.githubusercontent.com/12402160/35179774-9cf4f47e-fd55-11e7-9916-b8cb18c16ab3.PNG)
![img_8761](https://user-images.githubusercontent.com/12402160/35179775-a0584bde-fd55-11e7-88ab-028e61088e97.PNG)
![img_8763](https://user-images.githubusercontent.com/12402160/35179777-a407b7ba-fd55-11e7-954b-e3f8828630a1.PNG)
![img_8759](https://user-images.githubusercontent.com/12402160/35179778-a6a134ce-fd55-11e7-8231-e01ea5b39d38.PNG)

**Comment by Kdisimone** [comment]
This was done on a 722 pump, btw

**Comment by francesc0-cgm** [comment]
I noticed this last Summer on 723 too.

**Comment by Kdisimone** [comment]
closing this to track on the original issue https://github.com/LoopKit/Loop/issues/414
