### ISSUE TITLE
Bolus suggested when sensor value is below suspend threshold

### ISSUE THREAD

**Issue by chookchook1** [LoopKit/Loop#668]
Loop suggested a bolus for carb which was entered while glucose was at 3.7 even though the suspend threshold is 3.9. This happened about 20 minutes after a period of suspension and signal loss during exerciese. Photo shows levels and projection at time of bolus suggestion. 
![screen shot 2018-01-20 at 21 32 45](https://user-images.githubusercontent.com/20076960/35182459-de8bf3b8-fe29-11e7-9b11-480f05da59a3.png)

**Comment by elnjensen** [comment]
I think this is the same issue as #653.   Thanks for the additional report.

**Comment by chookchook1** [comment]
Thanks for pointing that out. Seeing as issue #653 covers this, I will close this issue.
