### ISSUE TITLE
Prediction Screen Bug ?! -->

### ISSUE THREAD

**Issue by chadharper0131** [LoopKit/Loop#669]
When you click & view the prediction screen, and turn off RC (Retrospective Correction), it changes the prediction on that screen, but when you go back to the main screen the glucose graph doesnt show the"updated" glucose graph (with or without "RC", "Insulin", ''Carbs", turned on or off).(*Caution: I dunno if what i wrote just now makes any sense, just woke up from a nap, not aawwaaakkkeee yet!!) . ---> heres a couple pics.
![image](https://user-images.githubusercontent.com/27801320/35306714-834adc32-005c-11e8-800b-55f32f5b4ae6.png)
![image](https://user-images.githubusercontent.com/27801320/35306725-8ed18fba-005c-11e8-8d98-69e8a1764df8.png)
![image](https://user-images.githubusercontent.com/27801320/35306734-9a87f768-005c-11e8-88b7-86bb46fbb474.png)

**Comment by chadharper0131** [comment]
- [ ] ???
- [ ] ???
- [ ] ???
- [x] ???

**Comment by natetr** [comment]
If you turn off the retrospective correction switch does it still do that? Not just the checkmark.

**Comment by chadharper0131** [comment]
@natetr - yup...  :o(

**Comment by natetr** [comment]
I just tested it. Wait for it to update after your next CGM reading and it should correct to the changes.

**Comment by natetr** [comment]
Did that work for you?

**Comment by Kdisimone** [comment]
closing.  looks like this was a misunderstanding that the slider has to be turned off to actually turn off RC (as it would impact prediction on main screen)...the checkmarks are just for visuals on prediction impacts, the slider is for loop function.
