### ISSUE TITLE
Glucose Momentum in Predicted Glucose screen shows no change

### ISSUE THREAD

**Issue by natetr** [LoopKit/Loop#671]
When clicking on the Glucose Momentum effect on the Predicted Glucose screen I am not shown any changes. 

![gif_1516925729](https://user-images.githubusercontent.com/34628512/35419249-c2ca4f74-01eb-11e8-8ed5-8f8562e5e7a8.GIF)

**Comment by ps2** [comment]
This is either because momentum and prediction are in alignment, or momentum isn’t available (which can be due to a recent calibration)

**Comment by natetr** [comment]
@ps2 thank you. I observed it changing for the first time yesterday evening. I appreciate your response. I will close this.
