### ISSUE TITLE
Shell Script Invocation Error

### ISSUE THREAD

**Issue by noahlisser** [LoopKit/Loop#673]
Hello, I'm new to coding and just tried to install the loop on my iphone.   When I tried to install loop for the first time I get an error that read shell script invocation error, and under that, command /bin/sh failed with exit code 127.  Any help would be greatly appreciated!

<img width="1141" alt="screen shot 2018-02-01 at 9 27 01 am" src="https://user-images.githubusercontent.com/35942067/35686547-1e8d6b48-0732-11e8-8565-a0dbd898bb23.png">

**Comment by noahlisser** [comment]
My bad, went to the website and ran carthage through terminal and fixed the issue.

**Comment by Kdisimone** [comment]
Glad to hear you got it resolved. 👍🏻
