### ISSUE TITLE
Couldn't get loop to loop

### ISSUE THREAD

**Issue by AJM1396** [LoopKit/Loop#674]
1st time of issue loop wouldn't give suggestions or even do anything like the app was frozen but with green loop

**Comment by Kdisimone** [comment]
[DOCTYPE html PUBLIC W3CDTD HTML 401EN httpwwww3org.pdf](https://github.com/LoopKit/Loop/files/1687977/DOCTYPE.html.PUBLIC.W3CDTD.HTML.401EN.httpwwww3org.pdf)

**Comment by Kdisimone** [comment]
Had an missing ISF value
