### ISSUE TITLE
Loop sometimes times out when trying to get BG values from Spike...

### ISSUE THREAD

**Issue by rsilvers129** [LoopKit/Loop#677]
Loop can use Dexcom Share server but with a custom port to get BG values. http://127.0.0.1:1979.

This worked all night for me, but then I got a red loop for 40 minutes. Clicking on the Loop icon, showed the error we per my attached screen capture. 

I killed Spike, and re-started it. Loop went back to green a minute after that. I suspect the problem is that IOS11 is trying to save power and is blocking the connection after some time. Maybe the fix is that Loop should try a few more times to establish a connection?

![28126449_10157117111023662_1873578915_o](https://user-images.githubusercontent.com/4177461/36319071-ce4b562e-130f-11e8-8f13-f72581d65ac6.jpg)

**Comment by miguelkennedy** [comment]
I think this is mainly an issue with Spike... I will try and tweak my code to prevent reconnect the server in case iOS kills it

**Comment by miguelkennedy** [comment]
Just added more checks in the code to see if the internal server is down... if it is then Spike will try to reconnect! This improvement will be released in the next Spike update...

**Comment by Kdisimone** [comment]
Looks like we can close this then.  Thanks!  Reopen if the problem returns.

**Comment by benfiscal** [comment]
I received a similar error message today in Loop using Spike version 3.5.3. I have a iPhone 6s (12.1.2)

"The Operation Couldn't Be Completed. (Spikeclient.Spikeerror Error 0.)

`httpError(Error Domain=NSURLError-Domain Code=-1004 "Could not connect to the server."
UserInfo={NSUnderlyingError=0x-282f37db0 {Error Domain=kCFErrorDomainCFNetworkCode=-1004 "(null)"
UserInfo{_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}},
NSErrorFailingURLSTringKey=http://127.0.0.1:1979/ShareWebServices/Services/General/LoginPublisherAccountByName,NSErrorFailingURLKey=http://127.0.0.1:1979/ShareWebServices/Services/General/LoginPublisherAccountByName,_kCFStreamErrorDomainKey=1, _KCFSTreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.}}`
