### ISSUE TITLE
Request for a notification reminder to eat when pre-bolus time has expired

### ISSUE THREAD

**Issue by kanserh** [LoopKit/Loop#686]
Many of us pre-bolus for meal and then sometimes forget to eat.  It was be a wonderful enhancement to have Loop send you a notification after the pre-bolus time has expired reminding you to eat.  Of course, no need for a notification if the meal time is the same as the entry time.  This could also potentially trigger us to edit the meal entry if we are unable to eat at that time.

**Comment by elnjensen** [comment]
How would you distinguish between a meal pre-bolus and a correction bolus?  Would this only apply if future carbs were also entered at the same time, and then the notification would be at the time that the carbs were entered for?

**Comment by scottleibrand** [comment]
Perhaps there’s no need to distinguish the two situations, and what you’re looking for is a carbsReq notification?

The logic in OpenAPS is: if the predicted BG from insulin alone drops below the minimum allowed threshold, calculate how far in the future that is, add in that many minutes of zero temp (or a minimum of 30m), and then calculate how many carbs are required to get BG back up to target. If that carbsReq is positive, send a push notification to alert the user they need carbs to avoid/mitigate a low.

**Comment by dm61** [comment]
@scottleibrand that sounds good, but wouldn't such notification be triggered immediately after almost any prebolus? I think @kanserh is looking for a simple reminder triggered when current time matches a meal entry time. No need to even look at any boluses, if I understand the request correctly.

**Comment by kanserh** [comment]
Perhaps I am over simplifying this, but in Loop when I enter a meal, I specify the time I will eat that meal.  For me that is usually 30 mins from the time I enter it.  I would love some sort of notification at the time I am supposed to be eating telling me "time to eat".  This would remind me no only to eat, but also to update Loop (the carb entry) should I not be able to eat at the moment.

**Comment by scottleibrand** [comment]
Ok, I misunderstood: I thought we were talking about a prebolus without carb entry (yet) rather than future-dated carbs. I agree that for the future-dated carb entry, a reminder at that time would be needed if you want to make sure they actually got eaten. 

Alternatively, for people who do the pre-bolus without pre-entering carbs, I would assume that the carbsReq notifications would have some sort of snooze after each notification, and probably after a bolus as well, so the notification would only come through after 15-30 minutes if you still haven’t entered the carbs.

**Comment by kanserh** [comment]
@scottleibrand Is it common for people to pre-bolus without entering carbs?  I cannot imagine doing this since Loop would then think you have too much insulin on board (because it doesn't know about the upcoming meal) and start 0 temping you which isn't ideal before a meal.  I would assume pre-bolusing by future dating carbs entries is significantly more common than pre-bolusing without carb entries but perhaps I am missing something?

**Comment by Kdisimone** [comment]
@kanserh I agree with you. @scottleibrand, on Loop it’s just not something people would do (prebolus without entering carbs).  The whole bolus Wizard on Loop starts with a carb entry, and forward-dating carbs is an easy selection on the screen.  It’s pretty different from OpenAPS that way.

**Comment by dm61** [comment]
@kanserh, I agree, I'd not worry about the case of pre-bolusing without entering carbs. Maybe a very new user would do that once, but would quickly realize that was simple a mistake.

**Comment by yogary9** [comment]
Just to add a +1 on this request from @kanserh .  I yesterday posted an "is it possible to..." type of post on the Looped FB page and asked for exactly the same thing that @kanserh describes here.  I was surmising if there is a nice way to accomplish this with IFTTT's help (doesn't appear to be, or at least not something that isn't very complicated), but certainly an implementation inside Loop itself would be the most useful.  Here is the text from my FB post:  "I'm using Loop and trying to prebolus in all cases before eating. One problem that I have is that I prebolus, enter in the carbs, type, and expected time that I'll eat. Then, life interferes with T1D and the next time I remember T1D, my planned eating time had passed me by and I'm headed low. What I'd like is the ability to automagically set an alarm on my iPhone for the eating time that I entered in on my iPhone. I use IFTTT for SAGE, BAGE, and CAGE change NS pills so wondered if I could create an IFTTT Applet triggered off of scheduling a pre-bolus in Loop. But, I'm not aware of that being possible. Is there any way to do what I'm looking for other than manually setting a timer or alarm on my phone?"

**Comment by brookslively** [comment]
What if there was a checkbox on the Add Carb Entry page that was default set to off, but when checked would send a notification reminder at the time set for carb consumption?

**Comment by dnzxy** [comment]
Hi everyone, pretty old issue but great starting point to get my feet wet with iOS development and contributing to Loop. I've started working on this yesterday and hope to have a prototype for this enhancement request in the near future. I'll post here when I can provide an update :)
