### ISSUE TITLE
Undo paste causes <ins> tags to be removed

### ISSUE THREAD

**Issue by ktundwal** [LoopKit/Loop#688]
**Repro steps** (also see attached recording)
1. Insert 3 paras in editor
2. Copy first 2 paras
3. Enable change tracking via button on toolbar
4. Paste copied text after para 3
5. Ensure pasted text is highlighted as "insert" change tracking
6. Add space within pasted text
7. Press Ctrl-Z once to Undo

**Behavior**
Space is remove. 'ins' tag is also deleted. See status bar below

**Expected behavior**
Only space is expected to be removed. NOT ins tag

![ckeditor-change-tracking-bug](https://user-images.githubusercontent.com/1222093/37063170-6e71dd30-214d-11e8-9d6f-64878010cd52.gif)

**Comment by scottleibrand** [comment]
Looks like you opened this under the wrong project.  This is Loopkit/Loop, not https://github.com/ckeditor
