### ISSUE TITLE
eversense sensor add

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#691]
would it be feasible to add sensor eversense? what should I do? thanks @ ps2

https://itunes.apple.com/it/app/eversense-cgm/id1219997410?mt=8

https://itunes.apple.com/it/app/eversense-now/id1348417609?mt=8

**Comment by francescaneri** [comment]
do not you know eversense? will you never use it? @Kdisimone

**Comment by Kdisimone** [comment]
Eversense is not available in the States yet. 

If you can find a way to get it into NS, then you could use NightscoutShareServer to get it into Loop.

**Comment by francescaneri** [comment]
having the application I can get it from health in theory....

**Comment by francescaneri** [comment]
@Kdisimone thanks
