### ISSUE TITLE
Select adjacent carb ratio period when bolusing

### ISSUE THREAD

**Issue by lixgbg** [LoopKit/Loop#693]
Most people have multiple carb ratios, e.g. one covering breakfast 06:00-09:00, snack 09:00-11:00, lunch 11:00-14:00, daytime 14:00-18:00, etc.
If you then one day have breakfast at 09:01 you will be bolused according to snack ratio, and if you try to take more insulin (most people use more insulin at breakfast) Loop will low temp as it thinks you have too much.
Breakfast is just an example, same issue with rest of the day.
If you could select a carb ratio period at the Bolus screen and override the the one Loop picks based on current time, it would become a much more flexible solution and much easier to use.

**Comment by Kdisimone** [comment]
Closing this issue.  Loop has the same behavior as when you use your pump manually.  The time that you enter the meal will be the basis for the bolus calculations.
