### ISSUE TITLE
Feature Request: Sensitivity Slider

### ISSUE THREAD

**Issue by rsilvers129** [LoopKit/Loop#703]
I am of the belief that carb-ratio, insulin sensitivity factor, and basal are all related. Meaning, if you are sick and need more basal, your carb ratio and ISF will change my the same amount.

If I am running low on a given day, and I see the insulin delivery graph below the baseline, I know Loop is holding back on basal to try to keep me in range. So I find that I manually go in and lower my basal, and change my ISF and carb ratio.

It would be great to have a slider on the screen where it is like an exposure compensation control on an SLR camera. 0 is in the middle, and you have +- 20% at either end. The slider would effect all three of these settings at once. 

It would also be good for the code base because it can lead to an "automatic" check box beside the slider where you see the slider move left and right on its own based on what adjustments that it senses you need.

A tie-in would be to have an improved activity mode which would jump the slider to a pre-set setting. For me, I use 1/5 of my normal basal during heavy aerobic activity, and I believe ISF and carb ratio should also change, which is something that doesn't happen in the current activity mode.

**Comment by mpangburn** [comment]
Is this is a separate concern from #593?

**Comment by Kdisimone** [comment]
Going to close this out with implementation of overrides https://github.com/LoopKit/Loop/pull/995
