### ISSUE TITLE
FoundationDB compatibility’s 

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#704]
Hi, is there the possibility to integrate this database with nightscout?

https://github.com/apple/foundationdb

**Comment by elnjensen** [comment]
@francescaneri  Development of Nightscout is separate from Loop. It is at https://github.com/nightscout/cgm-remote-monitor if you want to open this issue there for a feature request.

**Comment by francescaneri** [comment]
@elnjensen thanks.
