### ISSUE TITLE
Display problem on new Watch

### ISSUE THREAD

**Issue by kparisella** [LoopKit/Loop#711]
I’ve set up Loop to display on my new Apple Watch, and Loop shows as complication on the face where it should but only “Loop” and two dashed lines appear on face.  

When that is tapped, the Loop display (with glucose and minutes) appears momentarily before the full Loop app opens.   Then, on the Loop App screen (on the watch), only “Loop “ a light gray circle, and the carbs and bolus buttons appear.  No glucose reading, minutes, or other info. There’s a big space where I believe the glucose should be.  Again, it’s all showing fine on the Loop and Dexcom app on the paired phone.

 The glucose does display fine on the Loop app on the phone, along with the graphs and everything else.  I don’t have a Riley Link yet, so no pump is connected.  

My G5 sensor is working fine, displaying normally on the Dexcom app on both phone and watch.

Phone is new IPhone SE and watch is new Series 3.  I just updated software on both, but it didn’t make a difference of display of Loop on phone, and I didn’t try to see Loop on watch before I did the update.

**Comment by Kdisimone** [comment]
You won’t get watch display totally integrated until the RileyLink arrives.  When RileyLink arrives, then your Loop will display on watch. RileyLink is a necessity

**Comment by kparisella** [comment]
![image](https://user-images.githubusercontent.com/38840696/39409716-038527e2-4bba-11e8-8a62-af11abee3df1.jpg)
![image](https://user-images.githubusercontent.com/38840696/39409731-5456bd3e-4bba-11e8-8fca-7066f6fbd326.jpg)

**Comment by kparisella** [comment]
Ok great thanks .. I see that the loop watch display’s the glucose momentarily when tapped and also in the editing mode on the watch face, but I just realized that the glucose is not live — it’s 120 while my actual glucose is 159 on Loop on the phone (so that momentary display looks like maybe a generic model of how Loop should display as a complication).

Thanks a lot for your quick response and resolution!
