### ISSUE TITLE
troubleshootPumpComms overly aggressive

### ISSUE THREAD

**Issue by trixing** [LoopKit/Loop#723]
troubleshootPumpComms is only looking at the date of the last tune.  The comment for the function makes it look like it should better look at the last successful communication attempt.

What can happen now is that the Rileylink is out of the reach of the phone and Loop directly auto-tunes.  This can (a) be unsuccessful because no RileyLink is in reach and (b) reduce battery life time of the phone, pump and RileyLink.

I'd suggest changing it in a way to track the last successful communication.  That would probably be easier done in RileylinkKit though?

**Comment by Kdisimone** [comment]
@ps2 this would be better tracked in rileylink_ios, correct?

**Comment by ps2** [comment]
Going to close; it should only attempt re-tune after 15 minutes.  Please reopen and attach an xcode log if you are seeing different behavior. And yes, it might make more sense in rileylink_ios, as that's likely where a fix would have to be.

**Comment by trixing** [comment]
https://github.com/ps2/rileylink_ios/blob/483b228f0064afd201c8a7d6a25faf1d1a2a3b93/MinimedKit/PumpManager/MinimedPumpManager.swift#L202

still has the same code.

The only place lastTuned gets updated is here (I think, https://github.com/ps2/rileylink_ios/search?utf8=%E2%9C%93&q=lastTuned&type=)
https://github.com/ps2/rileylink_ios/blob/483b228f0064afd201c8a7d6a25faf1d1a2a3b93/RileyLinkKit/PumpOpsSession.swift#L808

Because state.lastTuned is not updated anywhere else afaict as soon as their is a 14+ minute communication gap it will run a tune:

        // How long we should wait before we re-tune the RileyLink
        let tuneTolerance = TimeInterval(minutes: 14)

        let lastTuned = state.lastTuned ?? .distantPast

        if lastTuned.timeIntervalSinceNow <= -tuneTolerance {

It should imho look at the last successful communication instead.

 I've long fixed this in my code, so sorry, no logs. And feel free to leave closed.
