### ISSUE TITLE
Dexcom app for G6

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#735]
Need to adjust this line for Dexcom G6 app?

https://github.com/LoopKit/Loop/blob/cgmblekit-g6-upgrade/Loop/Models/CGM.swift#L21

it's not opening the Dexcom G6 app when clicking on the BG in Loop

**Comment by Kdisimone** [comment]
hold on...i think i can get this one done myself.  give me a minute

**Comment by Kdisimone** [comment]
Was trying to follow along with this old issue...but I'll try your way too

https://github.com/LoopKit/Loop/issues/20

**Comment by Kdisimone** [comment]
The weird part is that I can't find the applications in iTunes.  Admittedly, i am rarely in itunes for my phone anymore...but they used to have an applications section for your phone where you could click on the apps on your phone.  I don't see that anymore.

**Comment by Kdisimone** [comment]
<img width="1512" alt="screen shot 2018-06-08 at 12 46 35 am" src="https://user-images.githubusercontent.com/12402160/41145875-537d6b7c-6ab6-11e8-8b71-a38a8ce3dff2.png">

I'd be happy to submit a PR, but I don't know how you'd want to deal with discerning between a G5/G6.  We could make it a customization people would need to do when they build?  or ??

**Comment by dabear** [comment]
@Kdisimone untested, but maybe something similar to this to dynamically return g6 url only if that app is installed?


```
private func schemeAvailable(_ scheme: String) -> URL? {
        if let url = URL(string: scheme),
        UIApplication.shared.canOpenURL(url) {
            return url
        }
        return nil
    }

    var appURL: URL? {
        switch self {
        case .g4:
            return URL(string: "dexcomshare://")
        case .g5:
            if let url = schemeAvailable("dexcomg6://") {
                return url
            }
            return URL(string: "dexcomcgm://")
        case .enlite:
            return nil
        }
    }
```

**Comment by Kdisimone** [comment]
closing  https://github.com/LoopKit/Loop/pull/734/files
