### ISSUE TITLE
Timeout after pump battery drain

### ISSUE THREAD

**Issue by nightscoutRCM** [LoopKit/Loop#746]
I went to bed last night with a new pump battery in my hand. Oops. Fell asleep. When I woke up this morning my Riley link still showed a red light on the charger. I changed my pump battery and tried to reconnect and got a timeout. I have restarted the phone, turned off and on Bluetooth, turned off and on the switch on the Riley link, everything I could find in Facebook troubleshooting. I went ahead and ordered a new Riley link but I thought I’d post this here in case anyone can help. Hate to be without it. 🙁

 

Generated: 2018-06-21 12:41:51 +0000

Loop v1.5.2
## DeviceDataManager
launchDate: 2018-06-21 12:32:35 +0000
cgm: Optional(Loop.CGM.g5(Optional("40YDY1")))
lastError: Optional((date: 2018-06-21 12:40:55 +0000, error: RileyLinkKit.PumpCommsError.rileyLinkTimeout))
latestPumpStatusFromMySentry: nil
pumpState: Optional(## PumpState
timeZone: GMT-0500 (fixed)
pumpRegion: North America
pumpModel: 722
lastHistoryDump: 0000-12-30 00:00:00 +0000
awakeUntil: 0000-12-30 00:00:00 +0000
lastWakeAttempt: Optional(2018-06-21 12:40:08 +0000))
preferredInsulinDataSource: Event History
## G5CGMManager
latestReading: nil
transmitter: Optional(xDripG5.Transmitter)
## DexCGMManager
shareManager: Optional(## ShareClientManager
latestBackfill: Optional(ShareClient.ShareGlucose(glucose: 174, trend: 4, timestamp: 2018-06-21 12:39:39 +0000))
)

## RileyLinkDeviceManager

timerTickEnabled: true

idleListeningEnabled: false

idleTimeout: 60.0

## RileyLinkDevice
name: RileyLink
RSSI: -59
lastIdle: 0000-12-30 00:00:00 +0000
lastTuned: 2018-06-21 12:33:31 +0000
radioFrequency: 0.0
firmwareVersion: ble_rfspy 0.9
state: Connected
## StatusExtensionDataManager
appGroupName: group.com.dotconnector.LoopGroup
statusExtensionContext: Optional(["glucose": [["unit": "mg/dL", "startDate": 2018-06-21 04:09:39 +0000, "value": 186.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:14:40 +0000, "value": 185.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:19:40 +0000, "value": 179.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:24:40 +0000, "value": 175.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:29:40 +0000, "value": 173.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:34:40 +0000, "value": 170.0]], "predictedGlucose": ["interval": 300.0, "unit": "mg/dL", "values": [169.83333333333334, 167.25951323565138, 163.58584910958859, 158.86944472736045, 153.19519939691403, 147.56130384070647, 141.96220186074524, 136.38954715636768, 128.8036621440605, 126.5058883815345, 124.4383885327849, 122.60925572970345, 120.98849423431326, 119.56490976434449, 118.39528386912113, 117.41399463234993, 116.55738169900016, 115.82999690472624, 115.2345782753566, 114.77202485970631, 114.43948806552041, 114.23803440497201, 114.16089675921896, 114.20136837269089, 114.35077767686832, 114.5978462947572, 114.77610068626367, 115.99084058183766, 117.28162862786675, 118.74326479172746, 117.16720736839679, 114.06540623333078, 111.0701146470694, 108.16792346168356, 105.32027354715225, 102.64929178167151, 100.09929244840029, 97.51885603919024, 94.952795606602393, 92.381505158195722, 89.784218053790909, 87.139007005472166, 84.092425989510929, 84.103952166261791, 84.138682643866531, 84.171945188427657, 84.203888898270378, 84.234676641107598, 84.264485054039682, 84.293504543554462, 84.321939285527463, 84.350007225221901, 84.377940077288002, 84.405983325764367, 84.434396224076494, 84.463451795037685, 84.493436830848822, 84.524651893098252, 84.557411312762014, 84.590213454591179, 84.567628193103218], "startDate": 2018-06-21 04:35:00 +0000], "reservoir": ["startDate": 2018-06-21 04:23:24 +0000, "capacity": 300, "unitVolume": 23.800000000000001], "loop": ["dosingEnabled": true, "lastCompleted": 2018-06-21 04:24:40 +0000], "batteryPercentage": 0.15384615384615397, "activeInsulin": 5.860220376420088, "targetRanges": [["minValue": 90.0, "maxValue": 120.0, "startDate": 2018-06-20 05:00:00 +0000, "endDate": 2018-06-21 05:00:00 +0000], ["minValue": 90.0, "maxValue": 120.0, "startDate": 2018-06-21 05:00:00 +0000, "endDate": 2018-06-22 05:00:00 +0000]], "netBasal": ["percentage": -0.86486486486486491, "end": 2018-06-21 04:54:40 +0000, "start": 2018-06-21 04:24:40 +0000, "rate": -1.6000000000000001], "version": 4, "sensor": ["trendType": 4, "stateDescription": "OK", "isStateValid": true, "isLocal": false]])

**Comment by ps2** [comment]
It does look like a RileyLink issue.  Sometimes the RL will go back into a locked state right after power cycling; particularly if Loop is running while you restart it. Perhaps try restarting the RL while Loop is not running.

**Comment by nightscoutRCM** [comment]
Ok tried that. I was hopeful because the color in battery level returned, but it didn’t update. Still getting a Riley link timeout in all functions from button press, get pump model or fetch glucose. Here’s the latest issue report:

Loop v1.5.2
## DeviceDataManager
launchDate: 2018-06-22 13:38:04 +0000
cgm: Optional(Loop.CGM.g5(Optional("40YDY1")))
lastError: Optional((date: 2018-06-22 13:41:17 +0000, error: RileyLinkKit.PumpCommsError.rileyLinkTimeout))
latestPumpStatusFromMySentry: nil
pumpState: Optional(## PumpState
timeZone: GMT-0500 (fixed)
pumpRegion: North America
pumpModel: 722
lastHistoryDump: 0000-12-30 00:00:00 +0000
awakeUntil: 0000-12-30 00:00:00 +0000
lastWakeAttempt: Optional(2018-06-22 13:40:49 +0000))
preferredInsulinDataSource: Event History
## G5CGMManager
latestReading: nil
transmitter: Optional(xDripG5.Transmitter)
## DexCGMManager
shareManager: Optional(## ShareClientManager
latestBackfill: Optional(ShareClient.ShareGlucose(glucose: 230, trend: 2, timestamp: 2018-06-22 13:39:36 +0000))
)


## RileyLinkDeviceManager

timerTickEnabled: true

idleListeningEnabled: false

idleTimeout: 60.0

## RileyLinkDevice
name: RileyLink
RSSI: -57
lastIdle: 0000-12-30 00:00:00 +0000
lastTuned: 2018-06-22 13:39:14 +0000
radioFrequency: 0.0
firmwareVersion: ble_rfspy 0.9
state: Connected
## StatusExtensionDataManager
appGroupName: group.com.dotconnector.LoopGroup
statusExtensionContext: Optional(["glucose": [["unit": "mg/dL", "startDate": 2018-06-21 04:09:39 +0000, "value": 186.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:14:40 +0000, "value": 185.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:19:40 +0000, "value": 179.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:24:40 +0000, "value": 175.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:29:40 +0000, "value": 173.0], ["unit": "mg/dL", "startDate": 2018-06-21 04:34:40 +0000, "value": 170.0]], "predictedGlucose": ["interval": 300.0, "unit": "mg/dL", "values": [169.83333333333334, 167.25951323565138, 163.58584910958859, 158.86944472736045, 153.19519939691403, 147.56130384070647, 141.96220186074524, 136.38954715636768, 128.8036621440605, 126.5058883815345, 124.4383885327849, 122.60925572970345, 120.98849423431326, 119.56490976434449, 118.39528386912113, 117.41399463234993, 116.55738169900016, 115.82999690472624, 115.2345782753566, 114.77202485970631, 114.43948806552041, 114.23803440497201, 114.16089675921896, 114.20136837269089, 114.35077767686832, 114.5978462947572, 114.77610068626367, 115.99084058183766, 117.28162862786675, 118.74326479172746, 117.16720736839679, 114.06540623333078, 111.0701146470694, 108.16792346168356, 105.32027354715225, 102.64929178167151, 100.09929244840029, 97.51885603919024, 94.952795606602393, 92.381505158195722, 89.784218053790909, 87.139007005472166, 84.092425989510929, 84.103952166261791, 84.138682643866531, 84.171945188427657, 84.203888898270378, 84.234676641107598, 84.264485054039682, 84.293504543554462, 84.321939285527463, 84.350007225221901, 84.377940077288002, 84.405983325764367, 84.434396224076494, 84.463451795037685, 84.493436830848822, 84.524651893098252, 84.557411312762014, 84.590213454591179, 84.567628193103218], "startDate": 2018-06-21 04:35:00 +0000], "reservoir": ["startDate": 2018-06-21 04:23:24 +0000, "capacity": 300, "unitVolume": 23.800000000000001], "loop": ["dosingEnabled": true, "lastCompleted": 2018-06-21 04:24:40 +0000], "batteryPercentage": 0.15384615384615397, "activeInsulin": 5.860220376420088, "targetRanges": [["minValue": 90.0, "maxValue": 120.0, "startDate": 2018-06-20 05:00:00 +0000, "endDate": 2018-06-21 05:00:00 +0000], ["minValue": 90.0, "maxValue": 120.0, "startDate": 2018-06-21 05:00:00 +0000, "endDate": 2018-06-22 05:00:00 +0000]], "netBasal": ["percentage": -0.86486486486486491, "end": 2018-06-21 04:54:40 +0000, "start": 2018-06-21 04:24:40 +0000, "rate": -1.6000000000000001], "version": 4, "sensor": ["trendType": 4, "stateDescription": "OK", "isStateValid": true, "isLocal": false]])

**Comment by Kdisimone** [comment]
@nightscoutRCM have you gotten your Loop back up and running?  new RL fixed the issue?

**Comment by nightscoutRCM** [comment]
Howdy,

I bought a new riley link. I could not resolve the issue. The new
riley link works, but I have been getting a lot of timeouts or disconnects
it seems when I transition from wifi to data or data to wifi in different
locations. I have to go to the rily link in loop settings and send button
press to pump and then usually I have to try to fetch glucose data multiple
times a day. I figure I need to update to the latest version of everything,
as it's been 6 months or so.

Thanks,

Wendy

**Comment by Kdisimone** [comment]
updating will help.  but also, a very good idea would be to post a photo of the plug and we can check if it is well secured.  often people don't have RL plugged in well and that causes problems.  example...left, not in far enough.  right, well secured.

<img width="1722" alt="screen-shot-2018-10-17-at-4 42 43-pm" src="https://user-images.githubusercontent.com/12402160/47122666-97aea800-d22c-11e8-8daa-79de75b4cfef.png">

**Comment by Kdisimone** [comment]
as far as fetch glucose data...aren't you using Dexcom?  If so, the RL command for fetch glucose data won't do anything (that is for medtronic cgm users only).  You should have your transmitter ID entered in your CGM settings for Loop, that will make it so that Loop can read your CGM without needing internet.  Mentioning that you are having problems going from wifi to cell makes me think you might not have your CGM setup correctly.  Can you add some screenshots of your CGM settings in Loop too?

**Comment by nightscoutRCM** [comment]
Sure! Thanks!

**Comment by Kdisimone** [comment]
Closing as the original issue appears to have been resolved.  If you need help with troubleshooting any further Loop operations, feel free to post in Zulip or Facebook.  You'll probably get a lot quicker engagement on things like RL questions or Loop error messages in those forums.

**Comment by nightscoutRCM** [comment]
Thank you. Closed.
