### ISSUE TITLE
Dev branch issue ? Backfill?

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#750]
Had some strange values logged into health kit from g6.  Using dev branch (current as of this morning...June 23rd) and had future data points added all with the same timestamp into Health App.  I believe the timing of the future data points do correspond to a time when i'd left the area of my Looping phone and RL...so there may have been some backfill involved

![img_3262](https://user-images.githubusercontent.com/12402160/41793001-b961fff2-7628-11e8-9b2e-f92bacb4578a.PNG)
![img_3263](https://user-images.githubusercontent.com/12402160/41793002-b98d8db6-7628-11e8-962a-f0e949a8a31d.PNG)
![img_3264](https://user-images.githubusercontent.com/12402160/41793003-b9ad6154-7628-11e8-97db-e47142b13e05.PNG)
![img_3265](https://user-images.githubusercontent.com/12402160/41793004-b9cb6064-7628-11e8-87f3-b5d533a985d2.jpg)
![img_3266](https://user-images.githubusercontent.com/12402160/41793005-b9e2c164-7628-11e8-8cc5-e6e375a9c59f.PNG)

**Comment by ps2** [comment]
Loop 1.9.4 includes more changes in CGMBLEKit to prevent this.
