### ISSUE TITLE
Rileylink battery dies to quickly 

### ISSUE THREAD

**Issue by tkbateman** [LoopKit/Loop#755]
Battery is over a year old and it dies in a couple of hours. I bought a new battery and it does the same. Does anyone know of a fix, or do I need to buy a new rileylink?

**Comment by tkbateman** [comment]
Thank you. That is what I was thinking. We just ordered a new one. Do you know if the scanners are the airport could affect the RL?  

Travis

**Comment by Kdisimone** [comment]
Sounds like you should try a new combo of charging plugs...new cable, charging block, outlet. 

Scanners are no problem. We’ve been through them a lot and we’ve had large batches of RileyLink go through for travel to hackathons before without incident. They aren’t damaged by scanners. If you’d like, maybe post a photo of the rl taken out of the case, so we can double check if the battery is plugged in far enough?

**Comment by tkbateman** [comment]
I went ahead and bought a new RL.
