### ISSUE TITLE
Newer Riley Link Has Continual rfCommsFailure

### ISSUE THREAD

**Issue by larrysoler** [LoopKit/Loop#765]
My latest Riley Link (the new, small case) is no longer working after working for several weeks.  I'm able to get my old RL working fine.  Keep getting RFCommsFailure on the new RL.  What can I do?

**Comment by ps2** [comment]
Could be a hardware issue if you've gone through all the troubleshooting documentation.

**Comment by Kdisimone** [comment]
The new RLs with firmware 2.0 need Loop v1.5.6 or newer.  Closing this comment as I believe FB discussions also provided the solution.  Thanks

**Comment by larrysoler** [comment]
Thanks for the advice/help.  Got the new RL and its working great.
