### ISSUE TITLE
Set the URL of this GitHub repo

### ISSUE THREAD

**Issue by dandv** [LoopKit/Loop#767]
![image](https://user-images.githubusercontent.com/33569/43361781-7197b496-928e-11e8-8aef-3ed077a630ff.png)

Presumably to https://loopkit.github.io/loopdocs/

**Comment by elnjensen** [comment]
I don't quite understand what you're suggesting here - the URL you give is for the docs, and there's a link to the docs both in the README and on the wiki.   Is there some significance to the particular space you've highlighted with the red box?

**Comment by Kdisimone** [comment]
Except loopdocs has its own GitHub repo so it may be a bit confusing to put the loopdocs url in the loopkit/loop repo 

https://github.com/LoopKit/Loopdocs

**Comment by Kdisimone** [comment]
added
