### ISSUE TITLE
Delivery Limits Issues

### ISSUE THREAD

**Issue by itsmojo** [LoopKit/Loop#774]
# Delivery Limits Issues

The current dev tree has been getting major improvements & rework
to be able to support diverse insulin pump types (e.g., the Omnipod
in addition to the Minimed insulin pumps) and to be more robust and
easier to support.  In the new paradigm, the Loop MAXIMUM BASAL
RATE and MAXIMUM BOLUS settings are set in a new Settings item
called Delivery Limits.  To save changes any changes to the Delivery
Limit settings, the user selects "Save to Pump...". The current
Loop dev semantics are to save the new limit values to the Minimed
pump and if successful, save these values in persistent storage as
the new Loop delivery limits. This new paradigm presumably was
implemented to prevent mismatches between the software (i.e., Loop's)
and the hardware (i.e., pump's) delivery limits. However this new
approach:
* Doesn't make sense for all insulin pumps type
* Is not necessary to prevent delivery limit mismatch problems
* Breaks the useful Loop model that allows for Loop's delivery limits to be less than the pump's

### This new approach doesn't make sense for all insulin pumps types

The Omnipod has no programmable delivery limits on the pump itself,
only some fixed maximum values as defined in the protocol. All the
programmable delivery limits for an Omnipod are actually enforced
by the software controlling the Pod (i.e., the PDM or the Loop app).
So for an Omnipod, having a "Save to Pump..." button in Delivery
Limits to save the new limits is misleading (it implies that the
delivery limits are being saved on the Pod which they are not),
confusing (it makes it sounds like the delivery limits might not
be stored in Loop), and incorrect (since there are no delivery
limits actually stored on the Pod).

### This new approach is not necessary to prevent delivery limit mismatch problems

Forcing the pump's delivery limits to be the same as the Loop's
delivery limits is *a way* to prevent some cases of delivery limit
mismatches on pumps that support programmable delivery limits, but
it is not necessary. All that is required to prevent a mismatch
problem when new delivery limits are set in Loop is to make sure
that the Loop delivery limits are not more than any built-in delivery
or programable pump delivery limits limitations (possibly by updating
the pump delivery limits to match) before the new delivery limits
are saved in Loop's persistent storage.

### This new approach breaks the useful Loop model that allows Loop's delivery limits to be less than the pump's

There are some times when having a Loop delivery limit less than
any programmable pump limit is desirable and useful and this has
always been possible in earlier versions of Loop. This includes
being able to temporarily have Loop's maximum basal rate lower than
even the currently scheduled base basal rate for longer periods of
extensive exercise when using higher workout correction targets
might not be sufficient. I will provide an example from my own
personal use that is now preventing me from being able use to current
Loop dev. When doing mountain hiking, I have found being able to
set a temporary low maximum basal rate is the best method for me
to limit excessively high insulin delivery using Loop before my BG
starts to drop from the heavy exercise required to hike up a mountain.
The problem that I have seen is that if I accumulate too much IOB
while hiking uphill, eventually this insulin will become extremely
effective and will drive my BG values down extremely quickly. After
I reach the top of the mountain (or in some cases a bit before), I
start raising my Loop maximum basal rate, in varying amounts a step
at a time roughly on hour intervals based on how my BG is doing
that day for that particular mountain until I finally have my Loop
maximum basal rate back up to its normal value. This method of
adjusting the Loop maximum basal rate from below the current basal
rate back to its normal value over course of the day has proven a
very effective method during my twice weekly mountain hikes.

I can't pre-program the insulin sensitivity based on time as I don't
know at what time of my hike my insulin sensitivity will be
dramatically increasing nor by what amount (I wouldn't be surprised
if it could be increasing by a factor of 10). Perhaps in the future
this type of scenario might be automatically handled with some sort
of highly dynamic insulin sensitivity handling by Loop.  Using a
high (workout) correction range has not proven sufficient to address
this problem for me either. I do start these mountain hikes with a
high correction range, this is still not enough to prevent Loop
from high-temping me too much after breakfast (typically I eat a
low carb breakfast and take no bolus) and building up too much IOB
before the exercise does enough to slow the BG rise.  If I try to
use a very high workout correction range and my BG value rises past
~200 mg/dL (~11 mmol/L), then I risk getting stuck at a high BG
range where I might have use correction boluses to get me into a
more reasonable BG range.  However at these BG levels I can get
very insulin resistant requiring even more insulin than usual to
correct, but then after the BG level finally drops to a more
reasonable level and the hike progresses, my body will quickly go
from being insulin resistant to the insulin being super effective
which again leads to crashing BG values. In these situations, Loop
will not be able to prevent the low BG by zero-temp'ing as it'll
be too late with all the IOB that accumulated from when I was insulin
resistant. Thus, being able to temporarily set a maximum basal rate
less than my normal basal rate is the only satisfactory way I have
found to handle managing my BG during a morning mountain hike where
I can't afford to accumulate too much IOB before my insulin sensitivity
goes way up and I need to avoid my BG value from rising above ~200
mg/dL during the hike to prevent BG crashing while going after
getting out of insulin resistant mode.

Another reason not to force the hardware delivery limits to always
match the software delivery limits is being able to use the Minimed
pump's delivery limits as an additional safeguard to provide separate
hard delivery limits.  If someone accidentally sets a new incorrectly
high delivery limit in Loop (e.g., by accidentally missing a “.”
or by double pressing a digit), the Minimed pump can still (potentially)
enforce its delivery limit if it isn't blindly overwritten with the
new delivery limit(s) without any verification.

## Proposed Changes

The new Delivery Limits "Save to Pump" function should be replaced 
with a more generic "Save" for all pump types.  The new Delivery
Limits Save operation should first enforce Loop specific limits (if
there are any) and then handle any pump specific delivery limit
checks and adjustments before saving the delivery limit to Loop's
persistent storage.  This seems to be the correct layering in that
this is really more of Loop (software) delivery limit than a pump
(hardware) delivery limit (after all this option is in the CONFIGURATION
section outside of the pump specific section).  Of course, the
underlying verification and handling for the delivery limits can
be pump specific.

For a pump like the Omnipod that does not support programmable
delivery limits, the pump specific delivery limit checking would
simply verify that the new delivery limits don't exceed the documented
delivery limits (e.g., for an Omnipod, the maximum basal rate is
30 U/hr and the maximum bolus is 30 U).

On pumps like Minimed that support programmable delivery limits,
the current pump limits can be updated with the new Loop limits if
needed, but it shouldn't force them to always be exactly the same.
This behavior will match the earlier behavior and will support cases
outlined above.  Loop can check the current Minimed delivery limits
and prompt the user depending on the semantics desired.  In no case
should the user be able to save new Loop delivery limits which
conflict with the Minimed delivery limits (i.e., the Minimed delivery
limits should always be >= Loop's delivery limits) to prevent
conditions where Loop can fail mysteriously later.  One method would
be to prompt the user if the Minimed delivery limits need to be
set/raised to support the new Loop delivery limits (along with
providing the user an option to cancel the Save operation and not
save the updated Loop delivery limits to the Minimed pump in case
the user accidentally set an incorrectly high delivery limit).
Another variation would be to prompt for a Minimed delivery limit
update listing both the current pump delivery limits and proposed
new delivery limits thus giving the user the option to update the
pump settings to match without forcing them to be the same if current
pump limits are compatible (i.e., if new Loop delivery limits are
less than the current Minimed pump delivery limits, updating the
pump's delivery limits to match *could be an option, but it shouldn't
be a requirement*).

**Comment by itsmojo** [comment]
Another issue with always forcing the new maximum basal rate to be successfully saved to the Medtronic pump before it can be used by Loop is when the pump is currently high temp'ing at a rate higher than new max basal delivery limit, you will get a confusing "Max settings exceeded" error trying to save the new lower value using "Save to Pump..." and the new lower limit cannot be saved.

![img_0242 max setting exceeded](https://user-images.githubusercontent.com/23020111/46703330-7a9a2980-cbdb-11e8-89e3-ca7151bdbd8e.PNG)

The hack workaround for now when this situation occurs is to cancel the temp basal on the pump and then attempt to do the "Save to Pump..." operation again. To handle this correctly if Loop is going to insist that it has to successfully set new software limit on the Medtronic pump (which I claim it shouldn't as per my previous discussion), you'd probably need to have Loop cancel the temp basal in effect (and then perhaps reestablish a new temp basal at the new max basal rate if you wanted to do it right) before saving the new max basal rate to the Medtronic pump. A simpler approach would be to just never fail to set new Loop software delivery limit if they cannot be successfully saved to the pump (as long as the values are within the pump's documented limits) and/or to ask the user if they want to attempt to save the new limits to the pump itself.

**Comment by jlucasvt** [comment]
Thanks for the work around @itsmojo.  I think the cases "Proposed Changes"above allows the flexibility of having different limits set for those pumps that support it.   The method of "setting" in this case canceling the current temp and setting the new limits.  I also think that some form of user notification or iconography in the Settings UI over the pump graphic may be helpful to visually note that there is a disparity between the pump and loop delivery limits, that can guide a user to updating the pumps settings if it is supported.  Maybe something as simple as a toggle switch to enable pump settings sync.  This way Loop can sync it's delivery settings with Pump if a user desires.
