### ISSUE TITLE
Riley Link won't connect after 18 hours

### ISSUE THREAD

**Issue by andrewprestonsmith** [LoopKit/Loop#790]
I  keep getting error message "The operation couldn't be completed. Device communication failed: Peripheral did not respond in time."

I already tried turning off/on my iphone as well as closing the loop app which in the past has worked to reconnect the Riley Link w/ them.  The RL was charged overnight. 

More specifically I also received the following message when trying to tune the RL:
Tuning radio…

deviceError(RileyLinkBLEKit.RileyLinkDeviceError.peripheralManagerError(RileyLinkBLEKit.PeripheralManagerError.timeout))

And the following error messages which are recorded on my phone from earlier today:
Generated: 2018-08-24 15:11:58 +0000

Loop v1.5.6
## DeviceDataManager
launchDate: 2018-08-24 15:07:43 +0000
cgm: Optional(Loop.CGM.g5(Optional("41K23M")))
connectedPeripheralIDs: Set(["9A16DFBB-C703-4A89-887C-2E22C4D108FC"])
deviceStates: [:]
lastError: Optional((date: 2018-08-24 15:11:57 +0000, error: RileyLinkKit.PumpCommandError.command(RileyLinkKit.PumpOpsError.deviceError(RileyLinkBLEKit.RileyLinkDeviceError.peripheralManagerError(RileyLinkBLEKit.PeripheralManagerError.timeout)))))
lastTimerTick: 2018-08-24 15:11:22 +0000
latestPumpStatus: nil
latestPumpStatusFromMySentry: nil
pumpBatteryChargeRemaining: Optional(0.18518518518518534)
pumpSettings: Optional(## PumpSettings
pumpID: ✔︎
pumpRegion: North America)
pumpState: Optional(## PumpState
timeZone: GMT-0400 (fixed)
pumpModel: 515
awakeUntil: 0000-12-30 00:00:00 +0000
lastWakeAttempt: nil)
preferredInsulinDataSource: Event History
sensorInfo: nil
## G5CGMManager
latestReading: nil
transmitter: Optional(CGMBLEKit.Transmitter)
providesBLEHeartbeat: false
## DexCGMManager
shareManager: Optional(## ShareClientManager
latestBackfill: nil
)

## RileyLinkDeviceManager

central: Optional(<CBCentralManager: 0x170268240>)

autoConnectIDs: ["9A16DFBB-C703-4A89-887C-2E22C4D108FC"]

timerTickEnabled: true

idleListeningState: disabled

## RileyLinkDevice
name: AndyRileyLink
lastIdle: 0000-12-30 00:00:00 +0000
isIdleListeningPending: false
isTimerTickEnabled: true
isTimerTickNotifying: true
radioFirmware: nil
bleFirmware: Optional(ble_rfspy 0.9)
peripheral: <CBPeripheral: 0x1700f4480, identifier = 9A16DFBB-C703-4A89-887C-2E22C4D108FC, name = AndyRileyLink, state = connected>
sessionQueue.operationCount: 1

Any help is welcome

**Comment by Kdisimone** [comment]
Probably best to ask in Gitter or FB group for this type of question...you'll get faster help.  I'll close this out and hopefully you can post over in those venues so that we can fix your issue, if you haven't already resolved it.

**Comment by Kdisimone** [comment]
and by the way, if you have two Loop apps on in the same iPhone...try deleting the unused one.  One of the potential sources of your message is from that occurrence.
