### ISSUE TITLE
When installing release 1.9 for the first time mmol/l units do not show in graph

### ISSUE THREAD

**Issue by Lytrix** [LoopKit/Loop#791]
I've successfully installed 1.9, but when starting Loop op the phone for the first time, the graph is showing mg/dl after first setup.
I have to close and restart the app to let it show mmol/l correctly.
The watch face does show mmol/l correctly.

**Comment by TravellingEd** [comment]
Same thing happened with me. Once I closed the app and reopened it changed to mmol/L.

**Comment by Lytrix** [comment]
@dabear Could be, I got it also each time after running Loop for a day. So starting Loop after day, running mmol/l it sets it back to mg/dl.
