### ISSUE TITLE
Cannot setup new pump: Failure on Fetch History PumpOps Error 13

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#792]
When the pump doesn't have a long history, Fetch History is failing after page 0 when it tries for page 1.  Logs here

https://gist.github.com/Kdisimone/8f753ae31b4e9892f17fc69a658102df

https://gist.github.com/Kdisimone/1acafd56eb415d532bd5136d8a419cf8

Resulting in 
![img_7e5efc88a869-1](https://user-images.githubusercontent.com/12402160/44828341-4d199380-abcc-11e8-8e35-e98b9c0056c5.jpeg)

**Comment by Kdisimone** [comment]
Cannot get a new pump to Loop yet pending this issue...

 https://gist.github.com/Kdisimone/b515fe6474579b2f215986d95915c4d3

![img_be3e2c4ab640-1](https://user-images.githubusercontent.com/12402160/44927456-71c75580-ad09-11e8-9876-bcee0858b012.jpeg)
![img_4698](https://user-images.githubusercontent.com/12402160/44927462-7429af80-ad09-11e8-81d8-5c314b802365.PNG)
![img_4700](https://user-images.githubusercontent.com/12402160/44927465-7724a000-ad09-11e8-94f2-df6af49486d3.PNG)
![img_4699](https://user-images.githubusercontent.com/12402160/44927471-7a1f9080-ad09-11e8-9dfc-1664a53f174f.PNG)

**Comment by Kdisimone** [comment]
https://gist.github.com/Kdisimone/f2f3d2f1a4c46ce2eec299a488427e40

Page 3, post temp basal history fetch fails with Error Code 13

**Comment by Kdisimone** [comment]
And this Pump Status failure is in there as well.  I'm seeing both.  Can't shake the Pump Error Code 13

https://gist.github.com/Kdisimone/8dbc1e3033baaa28fd5f5a893be930fc

**Comment by Kdisimone** [comment]
I can manually pull both Fetch Recent History and Read Pump Status commands via the RL menu fine.

**Comment by Kdisimone** [comment]
"Success" on fetch history, but still Grey Loop says Unknown Pump error code: 13 when pushed for info...

https://gist.github.com/Kdisimone/7823310f28e01f2c680cfedaacdbf710

**Comment by jlucasvt** [comment]
If you force read history you get the same error. 
![2](https://user-images.githubusercontent.com/19819388/44949102-5424e980-adf8-11e8-84b1-af813612d18d.png)

**Comment by Kdisimone** [comment]
I’ve been troubleshooting two errors at once so take this with a grain of salt about how much is actually necessary for this one issue BUT...deleting app, getting about 20-25 pump events recorded in pump, building Loop 1.5.6 got things going and then updated to 1.9

**Comment by ps2** [comment]
Those two issues are unrelated.

**Comment by ps2** [comment]
Getting more events in your history might cover you; the error is that Loop is asking for a page that has no data.  This will happen for pumps that have a history that has only recently started filling.

**Comment by Kdisimone** [comment]
@ps2 The history never gets past the error.  I'd kind of expect that there would be periodic drops if it were just a "new" page issue. as in rolls to a new page, get the error for awhile but should clear as page fills...but instead the error will stick around unchanged even as the pump events accumulate.

**Comment by Kdisimone** [comment]
resolved with 
https://github.com/LoopKit/Loop/pull/796
