### ISSUE TITLE
MySentry pairing failures for 723

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#793]
Having difficulties on all 723 Mysentry pairings for v1.9.  Have tried 4 723 pumps now.  All similar.  Yes, timeouts are repeated, but when I do get a not-timeout failure it is for "Unknown response during Watchdog listening:_______________" and then a code is in there.

https://gist.github.com/Kdisimone/cd72526deb1434d135fe4332fdc6841d

https://gist.github.com/Kdisimone/db1407f0f8221c3a6addd2dfbf491087

I cannot get a 723 to pair without first putting in an ID in manually beforehand to the Other Devices menu.  I've borrow an ID from another pump that has been mysentry paired with a rl before and then I can get past this issue for a 723.  Otherwise no

**Comment by Kdisimone** [comment]
The most common unknown response I'm getting so far is a78531758d00

**Comment by Kdisimone** [comment]
Also curiously, when the pump is initially going through setup for first time, I can see the tuning results in debugger...it will be in the -46 to -52 range for example.  YET, when MySentry pairing communications are going on, these values (nothing has changed otherwise) drop to horrible -91 type rssi results next to the message.  Is something in the mysentry pairing changing the frequency to communicate?

**Comment by Kdisimone** [comment]
I have literally tried dozens and dozens of times across numerous pumps.  These are all 723s that have been pulled from the shelf to try to use.

**Comment by Kdisimone** [comment]
If you want to recreate for testing, delete the IDs under Other Devices and try adding a 723 fresh.

**Comment by Kdisimone** [comment]
Also, a fix that seems to work is to get pump running on 1.5.6 first and then build with 1.9.

**Comment by ps2** [comment]
I'd suggest that users just add a mysentry id manually rather than installing an old build.

**Comment by Kdisimone** [comment]
Sorry, I should’ve followed up. It didn’t seem very stable with just an added aid. I still need to come back and do more documentation if this.  It has been hampered by the pumpOps 13 issue too so hard to watch debugger and figure which is the controlling issue admittedly. Could be overlapping and masking if error source I suppose.
