### ISSUE TITLE
Enlite: Missing Data -Glucose Data Not Available-Check CGM Data source

### ISSUE THREAD

**Issue by Telefingers** [LoopKit/Loop#800]
Updated all softwares: Mac, iPhone.  Created new Loop(latest update) and new NS.  Tried a new pump and new RL.  Had this issue with my old loop and all new updates/attempts.

Medtronic Pump is showing BS...but nothing transfers over to loop or NS.   BS and time is stuck from last week.

Help please : )  I notice in my remote the old bundle identifier is in there...when building new loop I notice that we no longer have to save a bundle identifier?  All kinds of lost here.

Thanks for the help!

![fullsizeoutput_6dfb](https://user-images.githubusercontent.com/20625222/45271273-5ed02600-b46b-11e8-9825-3b07c4893a24.jpeg)
![fullsizeoutput_6e02](https://user-images.githubusercontent.com/20625222/45271274-5ed02600-b46b-11e8-8159-decb32052726.jpeg)
![fullsizeoutput_6e05](https://user-images.githubusercontent.com/20625222/45271275-5ed02600-b46b-11e8-94e6-e3ce34ae798f.jpeg)
![fullsizeoutput_6e04](https://user-images.githubusercontent.com/20625222/45271276-5ed02600-b46b-11e8-8a7d-de81aa32e321.jpeg)
![fullsizeoutput_6e0c](https://user-images.githubusercontent.com/20625222/45271277-5ed02600-b46b-11e8-9563-c5b1f036a6df.jpeg)
![fullsizeoutput_6e10](https://user-images.githubusercontent.com/20625222/45271278-5f68bc80-b46b-11e8-909c-97a5d4c58ea7.jpeg)
![fullsizeoutput_6e18](https://user-images.githubusercontent.com/20625222/45271279-5f68bc80-b46b-11e8-8a7d-e10fb3488a76.jpeg)

[Loop_Xcode_report 1.pdf](https://github.com/LoopKit/Loop/files/2364862/Loop_Xcode_report.1.pdf)

**Comment by Telefingers** [comment]
Now I am seeing the old Bundle Identifiers are emerging...

**Comment by ps2** [comment]
Could you generate an issue report and attach it?

**Comment by Kdisimone** [comment]
You still have the same BG value from the future. That 5:20pm timestamp is the BG from year 2046. I think you need to purge your pump of that data point. 

Short of leaving the battery out for a long time, I don’t know how you’ll do that

**Comment by Kdisimone** [comment]
@ps2 we went through extensive troubleshooting this issue in FB. She has an issue report in pdf form linked above at the bottom of one of her comments. 

She has a BG in her history from 2046.

**Comment by ps2** [comment]
Ah, good catch, yeah, that might cause some issues.

**Comment by ps2** [comment]
If we can get the CGM pages from the pump, that might help us prevent a 2046 error in the future.

**Comment by Telefingers** [comment]
@ps2 how do I get the CGM pages from the pump?

THANK YOU!

**Comment by ps2** [comment]
Are you using an x23 pump with mysentry support, or x22?

**Comment by ps2** [comment]
To capture a log, first, you'll need to delete all the future bg readings from healthkit.  Then connect your phone to your computer and start Loop from Xcode. If you wait long enough, Loop will try to fetch BG data from your pump, and you should see a lot of output going into the Xcode log window at the bottom.  At some point there should be a "Fetch Enlite History" record in there, and the pages after that are the things we're interested in.

**Comment by Kdisimone** [comment]
Ann- if you can’t figure it out from those instructions, send me a PM in Facebook and I can use TeamViewer to remotely login to your computer and help

**Comment by Kdisimone** [comment]
@Telefingers Ann--has this issue been resolved now?

**Comment by Kdisimone** [comment]
closing...no response
