### ISSUE TITLE
Apple Watch Series 4 complication support

### ISSUE THREAD

**Issue by mpangburn** [LoopKit/Loop#803]
Apple Watch Series 4 comes with two exclusive new Watch faces, Infograph and Infograph Modular. Accompanying these Watch faces are four new complication families for Loop to support:
- Graphic Corner (`CLKComplicationFamily.graphicCorner`)
- Graphic Circular (`CLKComplicationFamily.graphicCircular`)
- Graphic Bezel (`CLKComplicationFamily.graphicBezel`)
- Graphic Rectangular (`CLKComplicationFamily.graphicRectangular`)

More information and sample complications [here](https://developer.apple.com/documentation/clockkit/graphic).

Without having yet experimented with the API, here are some initial thoughts, by complication:
**Graphic Corner**
- `CLKComplicationTemplateGraphicCornerStackText` with the two standard text providers, glucose + trend and time elapsed since update. There might be space for an additional piece of text here, too.

**Graphic Circular**
- `CLKComplicationTemplateGraphicCircularClosedGaugeText` with the closed gauge kept full to mimic the Loop icon, adjusting color to match the closed loop state, and the center text using the current glucose (and ideally trend, space permitting). 
- `CLKComplicationTemplateGraphicCircularOpenGaugeRangeText` with progress around the open ring relative to the current glucose, with the leading and trailing text providers denoting the range bounds (i.e. mimic the example weather complication, but using blood glucose concentration rather than temperature). This design has potential for diabetes apps but comes with a couple challenges for Loop in particular:
    - Loop has no color association for high or low glucose values; since the app uses solid blue for glucose points in all cases, using a gradient of new colors would introduce design complexity.
    - The appropriate bounds for the gauge are not immediately apparent. Making the bounds user-configurable introduces undesirable setup complexity, but making the bounds dynamic makes the complication more difficult to digest at a glance. The best we can do here is pick a reasonable range (say 50...300 mg/dL) and keep it fixed.

**Graphic Bezel**
- `CLKComplicationTemplateGraphicBezelCircularText` with the circular design from above and the additional text used for the time elapsed since the last update. It looks like the text can wrap pretty far around the bezel, in which case we can fit additional pieces of information here (IOB? COB?).

**Graphic Rectangular**
- `CLKComplicationTemplateGraphicRectangularLargeImage` with almost the exact same design as used by the heart rate app in the example complication—glucose value, trend, and time since the update along the top, and a rendered image of the glucose graph. This complication has exciting potential, as the shape of the image really lends itself to a graph; it also poses a significant technical challenge in that the Watch app has limited background execution time for image rasterization and is (unfortunately) still restricted to a budget of 50 guaranteed immediate complication updates per day.

My free time is limited in the next couple weeks, but I hope to start digging into the new APIs soon.

**Comment by elnjensen** [comment]
Thanks for digging into this, @mpangburn. I think your analysis of the options looks really good. Currently the glucose graph in the PR is not an image, but rather a SpriteKit scene, so there would have to be a separate rendering step. And as you say, the update budget will continue to be a challenge - seems like Apple's battery-saving api decisions here make *all* complications less useful because of the lagging updates.

**Comment by francescaneri** [comment]
@mpangburn 
question: 
1)possible to have a loop application follow apple watch face just to read the data of ns that can be used as nightguard?
2)possible to have an app and an apple watch face to follow the children without entering NS?
Thanks in advance.
Matteo

**Comment by beached** [comment]
I've been using the series 4 44mm and a series 0 42mm and had to stop the series 0 recently as the complication stopped updating, even after a reset.  still good to get dexcom alerts though

**Comment by ps2** [comment]
Series 4 complications are in Loop 1.9.4
