### ISSUE TITLE
Option to view actual basal instead of offset from configured basal rate

### ISSUE THREAD

**Issue by dennisgove** [LoopKit/Loop#809]
I'd like an option to view the actual total basal rate instead of the difference applied to the configured basal rate. For example, if my basal rate is currently set to 2 U/hr and Loop calculates that a basal rate of 5.5 U/hr is needed I'd like the main screen to show `5.5 U/hr` instead of `+3.5 U`

This image highlights in green the section I'd like to change. If this option is turned on then the Insulin Delivery chart would also display actual basal instead of difference from configured basal.

![loop-basal](https://user-images.githubusercontent.com/654519/45602792-3360b480-b9f2-11e8-8ef5-dec667d56eda.png)

It'd also be nice if the option allows for the display of both values. Display the basal and it's difference from the configured value.

**Comment by dennisgove** [comment]
If you feel this is a worthwhile feature to add I'd love to take on the implementation of it and send it in a PR.

**Comment by Kdisimone** [comment]
not to be a contrarian...but I prefer the delta vs the absolute value of the temp basal being implemented.  Helps me see how much (magnitude of) correction being applied.

**Comment by sethgagnon** [comment]
Is it possible to show delta and actual? Maybe actual on top and delta on bottom?
