### ISSUE TITLE
fixed blue ligth rileylink

### ISSUE THREAD

**Issue by davidmlb** [LoopKit/Loop#818]
hi. what means fixed blue ligth in rileylink? was working fine for a year and suddently i have no connection. the tunne check give me a timeout.
thanks

**Comment by Kdisimone** [comment]
Search Looped group. This has been addressed several times there. I will add to docs.

**Comment by djespriu** [comment]
thanks Katie. I searched it before to post here and i didnt find  . also I post in looped group without solution. i asked as a blue ligt  rileylink.....also i search on the documents

**Comment by djespriu** [comment]
thanks Katie. I searched it before to post here and i didnt find  . also I post in looped group without solution. i asked as a blue ligt  rileylink.....also i search on the documents

**Comment by djespriu** [comment]
sorry Katie. i search and found someting about errors but not specifically about fixed blue ligth. ok. i found something without solution is not a problem of max basal or insuline curve, because was working for a year. now i ordered a newone because i had one spare with a loot of conections fails. but works

**Comment by djespriu** [comment]
katie. i found your answer now in a post. electrical short, nothing to do?

**Comment by Kdisimone** [comment]
If a reboot of RileyLink doesn’t resolve the stuck ble light, then yes. Likely a short.

**Comment by latainethomas** [comment]
Thank you all I changed battery on    Riley Link and had flashing blue light turned it off and back on blue light went out and everything went back to normal
