### ISSUE TITLE
rileylink time out

### ISSUE THREAD

**Issue by davidmlb** [LoopKit/Loop#819]
Few days ago my rileylink broke down, a friend give me one until I receive the new one. the Riley is new with a firmware  ble_rfspy 2.0, and no connection between riley-pump. I checked several times the serial number  and world-wide are correct area.  I have a good bt signal  (-63dB). When i try to do a tune radio  frequency I have a "rileylinkTimeout" if i switch of and on the riley the sequence of the led is: 

-blue led 2 and green led 4 ( only few milliseconds)
-blue led 5 ( milliseconds)
-fixed green led 3

see below the error report, I so that the time in the error is 2 hours before the real time and the time has the pump, loop, iPhone

Loop v1.5.3dev
## DeviceDataManager
launchDate: 2018-09-27 06:56:10 +0000
cgm: Optional(Loop.CGM.g5(nil))
lastError: Optional((date: 2018-09-27 06:58:19 +0000, error: RileyLinkKit.PumpCommsError.rileyLinkTimeout))
latestPumpStatusFromMySentry: nil
pumpState: Optional(## PumpState
timeZone: GMT+0200 (fixed)
pumpRegion: World-Wide
pumpModel: 
lastHistoryDump: 0000-12-30 00:00:00 +0000
awakeUntil: 0000-12-30 00:00:00 +0000
lastWakeAttempt: Optional(2018-09-27 06:57:40 +0000))
preferredInsulinDataSource: Historia de eventos
## G5CGMManager
latestReading: nil
transmitter: nil
## DexCGMManager
shareManager: Optional(## ShareClientManager
latestBackfill: nil
)

## RileyLinkDeviceManager

timerTickEnabled: true

idleListeningEnabled: true

idleTimeout: 60.0

## RileyLinkDevice
name: RileyLink
RSSI: -63
lastIdle: 2018-09-27 06:58:15 +0000
lastTuned: 2018-09-27 06:56:28 +0000
radioFrequency: 0.0
firmwareVersion: ble_rfspy 2.0
state: Connected
## StatusExtensionDataManager
appGroupName: group.com.davidjespriu2.LoopGroup
statusExtensionContext: nil

## LoopDataManager
settings: Loop.LoopSettings(dosingEnabled: false, dynamicCarbAbsorptionEnabled: true, glucoseTargetRangeSchedule: Optional(["items": [["startTime": 0.0, "value": [95.0, 110.0]], ["startTime": 19800.0, "value": [95.0, 115.0]], ["startTime": 25200.0, "value": [100.0, 120.0]], ["startTime": 28800.0, "value": [95.0, 110.0]]], "timeZone": 7200, "overrideRanges": ["preMeal": [75.0, 75.0], "workout": [110.0, 155.0]], "unit": "mg/dL"]), maximumBasalRatePerHour: Optional(2.3999999999999999), maximumBolus: Optional(1.7), suspendThreshold: Optional(Loop.GlucoseThreshold(value: 82.0, unit: mg/dL)), retrospectiveCorrectionEnabled: true, basalProfileStandard: Optional(["items": [["startTime": 0.0, "value": 0.5], ["startTime": 3600.0, "value": 0.34999999999999998], ["startTime": 10800.0, "value": 0.25], ["startTime": 16200.0, "value": 0.20000000000000001], ["startTime": 27000.0, "value": 0.67500000000000004], ["startTime": 32400.0, "value": 0.67500000000000004], ["startTime": 39600.0, "value": 0.90000000000000002], ["startTime": 46800.0, "value": 0.80000000000000004], ["startTime": 61200.0, "value": 0.75], ["startTime": 68400.0, "value": 0.80000000000000004], ["startTime": 79200.0, "value": 0.80000000000000004]], "timeZone": 7200]), basalProfileA: nil, basalProfileB: nil, activeBasalProfile: Optional(Not Set))
insulinCounteractionEffects: []
predictedGlucose: []
retrospectivePredictedGlucose: []
recommendedTempBasal: nil
lastBolus: nil
lastGlucoseChange: nil
retrospectiveGlucoseChange: nil
lastLoopCompleted: nil
lastTempBasal: nil
carbsOnBoard: nil
insulinOnBoard: nil
error: Optional(Loop.LoopError.missingDataError(details: "Glucose data not available", recovery: Optional("Check your CGM data source")))

## GlucoseStore

* latestGlucoseValue: nil
* managedDataInterval: 0.0
* reflectionDataInterval: 1800.0
* momentumDataInterval: 900.0
* sampleDataCache: []
* authorizationRequired: false

## CarbStore

* carbRatioSchedule: ["items": [["startTime": 0.0, "value": 17.0], ["startTime": 25200.0, "value": 7.0], ["startTime": 34200.0, "value": 9.0], ["startTime": 45000.0, "value": 13.0], ["startTime": 57600.0, "value": 13.0], ["startTime": 59400.0, "value": 13.0]], "timeZone": 7200, "unit": "g"]
* defaultAbsorptionTimes: (fast: 7200.0, medium: 9000.0, slow: 10800.0)
* insulinSensitivitySchedule: ["items": [["startTime": 0.0, "value": 240.0], ["startTime": 27000.0, "value": 200.0], ["startTime": 39600.0, "value": 165.0], ["startTime": 46800.0, "value": 180.0], ["startTime": 61200.0, "value": 195.0], ["startTime": 68400.0, "value": 195.0], ["startTime": 79200.0, "value": 200.0]], "timeZone": 7200, "unit": "mg/dL"]
* delay: 600.0
* authorizationRequired: false
* isBackgroundDeliveryEnabled: false

## DoseStore

* readyState: ready
* insulinModel: Optional(humalogNovologChild(ExponentialInsulinModel(actionDuration: 21600.0, peakActivityTime: 3900.0, initialDelay: 1200.0)
* basalProfile: 
* insulinSensitivitySchedule: ["items": [["startTime": 0.0, "value": 240.0], ["startTime": 27000.0, "value": 200.0], ["startTime": 39600.0, "value": 165.0], ["startTime": 46800.0, "value": 180.0], ["startTime": 61200.0, "value": 195.0], ["startTime": 68400.0, "value": 195.0], ["startTime": 79200.0, "value": 200.0]], "timeZone": 7200, "unit": "mg/dL"]
* areReservoirValuesContinuous: false
* isUploadRequestPending: false
* lastAddedPumpEvents: 0000-12-30 00:00:00 +0000
* lastReservoirObject: nil
* lastReservoirVolumeDrop: 0.0
* mutablePumpEventDoses: []
* pumpEventQueryAfterDate: 2018-09-26 21:51:10 +0000
* primeEventExistsWithinInsulinActionDuration: false
* totalDeliveryCache: nil
* lastPrimeEventDate: nil
* pumpRecordsBasalProfileStartEvents: false
* device: Optional(<<HKDevice: 0x113e3e8c0>, name:RileyLink, manufacturer:Medtronic, firmware:Unknown, software:35.0, localIdentifier:975331>)

### getNormalizedDoseEntries
Error: configurationError

### InsulinDeliveryStore

* lastBasalEndDate: 0000-12-30 00:00:00 +0000

**Comment by jlucasvt** [comment]
David Please update to the latest version of Loop 1.9.x

**Comment by gcastellanos** [comment]
I can confirm this happening with Loop V1.5... will try to update and see how it comes out. Thanks for the info though :)
