### ISSUE TITLE
no future bg value, loop not working

### ISSUE THREAD

**Issue by cog4444** [LoopKit/Loop#822]
[Loop Report 2018-10-01 13_46_10-04_00.pdf](https://github.com/LoopKit/Loop/files/2435133/Loop.Report.2018-10-01.13_46_10-04_00.pdf)

**Comment by ps2** [comment]
Sorry, that didn't come through.  Have her email the issue report to you, save it, then zip it (right click on it and select compress), then attach it here.

**Comment by cog4444** [comment]
She emailed but I'm on a mac and there is no right click just download or google drive.  : (

**Comment by ps2** [comment]
Save it into a folder on your computer, then go into finder, and right click on it. On a mac you can right click by tapping with two fingers on the trackpad.

**Comment by cog4444** [comment]
[Loop Report 2018-10-01 13_46_10-04_00.md.zip](https://github.com/LoopKit/Loop/files/2435192/Loop.Report.2018-10-01.13_46_10-04_00.md.zip)

**Comment by cog4444** [comment]
let me know if above worked  Thanks

**Comment by cog4444** [comment]
Yes it is Katie's branch.  Should I download the most recent one tonight.  She open and closed loop to try and fix.  It's not fixing.  She did all the Riley fixes to no avail.  I'm going to bring her the other Riley and hope that links her back up as she has a soccer game in 40 minutes but I don't know how to fix the loop

**Comment by ps2** [comment]
Have her send you another issue report.  If the launch date on it is very recent as well, then it sounds like Loop is crashing.

**Comment by cog4444** [comment]
if I can reach her I will  thank you

**Comment by ps2** [comment]
Yeah, this one is seconds after launching.  Loop is crashing, unless she restarted it again.  Please get on a stable branch.  If you continue to have issues, please reopen this ticket or create a new one.

**Comment by cog4444** [comment]
okay, I will update everything tonight when she is home.  it's a pity.  it worked beautifully for the past month until this weekend
