### ISSUE TITLE
Crash on app open

### ISSUE THREAD

**Issue by mitchellhenke** [LoopKit/Loop#829]
I've been running Katie's branch `katie` here: https://github.com/Kdisimone/Loop/tree/katie and last night the app started crashing upon opening the app.  I reinstalled the app and everything returned to normal, but I wasn't able to get the report issue information.

Is there a good way to capture any exceptions that happen?  I have some familiarity with software development, but not so much in the realm of iOS development.  I may try to set up something like [Sentry](https://docs.sentry.io/clients/cocoa/) or another error tracking platform on my install to see if I can gather more information should it happen again.

**Comment by Kdisimone** [comment]
How old was your app?  About a week since you’d built previously?

**Comment by mitchellhenke** [comment]
I'm on the most recent version of that branch, commit https://github.com/Kdisimone/Loop/commit/68be9936010501404a3b2887a42704ac2bd8d160

**Comment by mitchellhenke** [comment]
@Kdisimone you are absolutely correct, sorry for the bother.  Thanks for the help 🙂

**Comment by NickyJoel** [comment]
Hi guys,
Unfortunately my app crashes immediately after opening, however the app works fine on my apple watch. I have the free developers account however I only made the account yesterday so don't have the above mentioned 7-day problem yet. Any suggestions?
