### ISSUE TITLE
Backfill G6 data; future BG data

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#834]
Still having sporadic reports of G6 backfilling with future, large BG values.  Most recently, 1.9.3 version has issue.  Issue report linked here...below

[Loop-Report-2018-10-15-2240470200.txt](https://github.com/LoopKit/Loop/files/2484856/Loop-Report-2018-10-15-2240470200.txt)

![44261262_322517675214842_745223301697110016_n](https://user-images.githubusercontent.com/12402160/47046601-62ca2480-d14a-11e8-9826-5aa921085bc3.jpg)

**Comment by Kdisimone** [comment]
For those who encounter this issue...this occurs when the G6 loses connection with your app and when you come back into connection, the backfill occasionally produces large, future BG values.  The loop will stay a green color, but temp basals will not be set.  Do not worry, your Loop is not going to loop based on future BG data.  

To fix the issue, go to your phone's Health app, find the future BG data entries and delete them.  Your Loop will resume after that.

**Comment by ps2** [comment]
Any possibility that the future data was stored on an older version of Loop, and that 1.9.3 was installed as an attempt to resolve the issue?

**Comment by Kdisimone** [comment]
I'll ask

**Comment by Kdisimone** [comment]
@ps2 he built on 1.9.2 originally. I asked what he used to build 1.9.2 and he built from link in loopdocs, not one of my branches. Issue did happen on 1.9.2 originally and he built 1.9.3 in attempt to fix, like you’d suspected.

**Comment by Kdisimone** [comment]
Linking to https://github.com/LoopKit/Loop/issues/750 so that we can track both at once

**Comment by chadharper0131** [comment]
excerpt from the "Loop Report" below:  ---> look carefully at the date(s) 
seems to know it is 10/15/2018, but the future value of inflated BG's are for year (2107). check 9/27/2017 and see if there is data in HK for that date. maybe just a little dating error, which then accidentally projected values 100 years ahead. 
 (
predictedGlucose: [
* PredictedGlucoseValue(start, mg/dL)
* 2107-09-27 20:00:43 +0000, 2969.0
* 2107-09-27 23:00:43 +0000, 2969.0


* latestGlucoseValue: Optional(LoopKit.StoredGlucoseSample(sampleUUID: 5B670F2F-1D21-435C-A49B-2B8E4B56B8FD, syncIdentifier: "80ECT3 2808783933", syncVersion: 1, startDate: 2107-09-27 20:00:43 +0000, quantity: 2969 mg/dL, isDisplayOnly: true, provenanceIdentifier: ""))
----> look at the date(s) ->> 09/27/2107 <<

**Comment by Kdisimone** [comment]
👍👍
