### ISSUE TITLE
Loop crashes on Apple Watch 4

### ISSUE THREAD

**Issue by Squarepusher50** [LoopKit/Loop#838]
Hi!

I’m having a problem with the Apple Watch app.
The App crashes right after touching one of its four buttons.

Bb

**Comment by Kdisimone** [comment]
please list the version of Loop you are using...but I suspect that the solution can be found by following the steps in the following post in fb  https://www.facebook.com/groups/TheLoopedGroup/permalink/2135594346657220/

**Comment by Kdisimone** [comment]
Closing as issue appears to have been resolved.  Other users have indicated Series 4 watch and recent Loop version are working well.  If issue continues, please let me know and we can reopen the issue.
