### ISSUE TITLE
Pull CGM Data from Nightscout

### ISSUE THREAD

**Issue by apabari** [LoopKit/Loop#84]
Discussed with @ps2 , so I thought it would be prudent to log an enhancement request 'formally' as well. :)

Would it be possible to pull CGM data from Nightscout as a source of data for the loop app?

In Canada (and in many other countries) the Dexcom G4 w/share, or Dexcom G5, is not available.  I'm currently using an xDrip with an android phone (and the xDrip+ app) to push data to Nightscout.  (For use in an openAPS rig at the moment.)

I recognize that this means the user has to carry two phones - but I'm doing this anyway for xDrip, as I'm sure others are too.

(Longer-term it would be ideal to be able to replicate the xDrip function in iOS, but I think that's a different enhancement request.)

**Comment by xpucuto** [comment]
I am also interested in this feature for the same reason. I simply don't have G4 with share , neither G5. 
Regarding the xDrip app for iOS , John Costik said its almost done but needs some testing before he uploads it to Github.

**Comment by apabari** [comment]
The workaround for this:
- use xDrip+
- upload CGM data to Dexcom Share servers
- download CGM data into loop from Dexcom Share
