### ISSUE TITLE
Loop crash during display of Bolus screen

### ISSUE THREAD

**Issue by itsmojo** [LoopKit/Loop#846]
**Describe the bug**
Running with a 1.9.2 based version Loop for Omni, had a Loop crash on the Bolus deliver screen. The sequence was a Current Range Pre-Meal was added (there was none there previously), an Add Carb Entry was performed for 45 Carbs for 2 hours which rolled into the the Bolus screen. Right after the Bolus screen was displayed and before anything was touched on this screen, Loop crashed.

**Attach an Issue Report**
[Loop-2018-11-03-104939.ips.txt](https://github.com/LoopKit/Loop/files/2545307/Loop-2018-11-03-104939.ips.txt)

**To Reproduce**
Have not tried to reproduce

**Expected behavior**
No crash! ;-)

**Screenshots**
None available

**Phone**
 - Hardware: iPhone 5s
 - OS Version: iOS 12.0.1

**Loop Version**
 - Version Number: 1.9.2 (private version for Omnipod Eros)
 - Repo: loop-priv

**CGM**
 - Device: G6
 - Manager app: Share

**Pump**
 - Manufacturer: Insulet
 - Model: Eros
 - Firmware version: 2.7.0

**Additional context**
Xcode stack trace with symbols:
[2018-11-03_Bolus_screen_capture_at_Hackathon.docx](https://github.com/LoopKit/Loop/files/2545313/2018-11-03_Bolus_screen_capture_at_Hackathon.docx)

**Comment by ps2** [comment]
Unfortunately, I don't see anything in the stack that looks actionable; seems like there is a retain error, but the culprit is probably gone by the time of the crash.  Have you seen any more occurrences of this?

**Comment by Kdisimone** [comment]
@itsmojo @ps2 I haven't seen anymore reports of this happening so I'm going to close this out for now. I'll reopen (or you all can) if there's any reports of this in updated versions of Loop since this was posted.
