### ISSUE TITLE
Gaps of missing insulin data in HealthKit. 

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#852]
Gaps of missing insulin data in HealthKit. 

<img width="995" alt="screen shot 2018-12-04 at 4 43 13 pm" src="https://user-images.githubusercontent.com/14649/49527747-2b3d4600-f878-11e8-8e2a-edf06a3f22e7.png">

In this case, there is a gap from 3:00 to 3:09 (GMT-8).  I suspect an issue in reconciliation with basal schedule.  There is a basal schedule change at 3am, and a record in HK from 02:59-03:00. 

Nightscout upload from Loop:
<img width="426" alt="https___orcadreams2_herokuapp_com_api_v1_treatments_json_count_100_find_created_at___lte__2018-11-29t11_15_00-05_00" src="https://user-images.githubusercontent.com/14649/49522144-98e37500-f86c-11e8-8531-e6dc4c697d17.png">

Extracted HealthKit records:
<img width="1283" alt="screen_shot_2018-12-04_at_9 43 17_pm" src="https://user-images.githubusercontent.com/14649/49522217-c7615000-f86c-11e8-80f9-11e5717486d6.png">

**Loop Version**
 - Version Number: 1.9.3

**Comment by BecCooney** [comment]
Also seeing HK gaps after set changes and manual pump suspends as well.
