### ISSUE TITLE
Loop can skip/miss Manual Boluses resulting in incorrect IoB

### ISSUE THREAD

**Issue by shanselman** [LoopKit/Loop#853]
**Describe the bug**

I took 5U AT 10:05am manually via audio bolus. The manual bolus shows up in my pump history and Loop sees it in Event History (see pic.) I RARELY bolus this way so I am not sure what the expected behavior is. I would personally expect Loop to see the bolus in history and have it show up as IoB.

I am on 1.9.4dev so I’m feeling this may be related to the “Loop stores insulin in HealthKit” path? Perhaps it’s using HealthKit as the authoritative source and not seeing the Bolus? 

It feels like if Loop misses a manual Bolus (perhaps while the bolus is long running?) and then Loop temp basals and records that temp to HealthKit that it won’t look back in Event History and see the previous manual bolus.

**UPDATE**: I went into HealthKit and manually deleted Insulin Delivery Record’s going back until 10am, then force quit Loop. Loop then recovered and populated IoB correctly. This was an interesting bug/issue as because Loop thought I had no IoB it had Temp Basaled me to 3U/hr which would have been a problem later.

**Attach an Issue Report**

Attached [Loop Report 2018-12-12 11_00_24-08_00.zip](https://github.com/LoopKit/Loop/files/2674523/Loop.Report.2018-12-12.11_00_24-08_00.zip)

**To Reproduce**
Guessing here, will try to repro again. Steps to reproduce the behavior:
1. Enable Loop to log Insulin in HealthKit
2. Largeish _manual_ bolus
3. Loop loops and temp basals shortly after bolus.
4. Loop misses manual loop. Should show manual bolus as IoB but doesn't.

**Expected behavior**
I'd expect loop to look back n number of events in case it missed a manual bolus, rather than using (?) HealthKit as the authoritative source.

**Screenshots**
Note the bolus around 10:05am
![img_2846](https://user-images.githubusercontent.com/2892/49916917-e1dd8f80-fe51-11e8-9fba-c5b6443401dd.PNG)
Bolus recorded here at 10:05am
![img_2847](https://user-images.githubusercontent.com/2892/49916918-e1dd8f80-fe51-11e8-882e-5f5008abdc89.PNG)
Bolus missing from HealthKit. Instead a 1.05U basal is present? Then follow up basals.
![img_2848](https://user-images.githubusercontent.com/2892/49916919-e1dd8f80-fe51-11e8-969b-11af78305403.PNG)
Note missing basal
![img_2849](https://user-images.githubusercontent.com/2892/49916920-e1dd8f80-fe51-11e8-89d6-a1be166a0557.PNG)

**Phone**
 - Hardware: iPhone XS Max
 - OS Version: 12.1.1 (16C50)

**Loop Version**
 - Version Number: 1.9.4
 - Repo: LoopKit/dev

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 522
 - Firmware version: 2.4a 1.1 0B 0B

**Additional context**
I was having a considerable low at the time and Loop had me temped at 0. I was taking the 5U in anticipation of a very large lunch.

**Comment by elnjensen** [comment]
I've had no problem in the past with Loop seeing manual boluses (though it can take a little time before it pulls the history and sees the bolus).   Curious to see if you can reproduce it; I'll try as well with some manual boluses to see what happens.  Was Loop completely successfully (green loop) between when you gave the bolus and when you took the above screenshots?

**Comment by ps2** [comment]
This fix is in Loop dev now. Please test if you can. The issue happens on x22 medtronic pumps when 1) A (large) bolus is started. 2) A temp basal ends before the bolus finishes. 3) Loop fetches pump history as part of a normal loop before the bolus finishes.

**Comment by shanselman** [comment]
Amazing! Glad you found this. It's so awesome to hunt down weird - but significant - bugs like this! THANK YOU! 🥇

**Comment by ps2** [comment]
@fgutteridge go to settings app -> privacy -> health -> Loop, and make sure Loop has all insulin permissions enabled.

**Comment by Kdisimone** [comment]
Sounds like it’s all resolved. Thanks Pete!
