### ISSUE TITLE
Again: Dana RS Support for development

### ISSUE THREAD

**Issue by sboernemeyer** [LoopKit/Loop#857]
Good Morning,
actually i loop with medtronic (what else).
Future use (would be nice):
Dana RS
For myself i am not able to develop in sw kinds
But i have a brand new Dana RS for testing
SW Any-Dana-i is ......
Maybe Someone can help 
Milos Kozak (AAPS) has Driver ....
THx in advance 
Seasons Greetings
Sven

**Comment by Kdisimone** [comment]
I don't believe we need an open issue requesting new pump compatibility. It's pretty much understood at this point that everyone would like to see more widely available pump compatibility.  Closing the issue with the understanding that this has been asked and answered several times before...and not just for DanaRS...other pumps too.  Thank you.
