### ISSUE TITLE
Feature Suggestion: Set Fast, Medium, Slow carb absorption times to 30 minutes, 3 hours, 5 hours.

### ISSUE THREAD

**Issue by brandonarbiter** [LoopKit/Loop#864]
**Feature suggestion**

Currently, Loop carb absorption times are 2, 3, and 4 hours for fast, medium, and slow carbs, respectively. 

I find it really helpful to use the fast carbs for glucose rescue (e.g., eating glucose tabs for a low BG). But that's more like a 30 minute carbs absorption time, not 2 hours. So I customize the setting in the code.

On the other side, the difference between 3 and 4 hours to indicate a slow meal isn't very much. 

I suggest we set the carb absorption times for fast, medium, and slow to 30 minutes, 3 hours, and 5 hours, respectively.

**Comment by Kdisimone** [comment]
The lollipop at 2 hours is too long...but 30 min might be a too fast, but we don’t use that entry often. I’d think something like 60 min might be closer to the wide variety people use for lollipop coverage. Like many fruit are longer than 30min for us. Closer to 1 hour overall for apples and bananas. We use lollipop for fruit and do wish it were quicker than 2 hours, but more like 60min. 

And 5 hours for pizza icon would be too long for us for most of our pizza entries. Currently, 4 hours starts at 5.5 hours for DCA. So if pizza was 5 hours it would start at 7.5 hours. That’s a 2 hour difference. Pretty significant DCA change compared to what people are currently used to using. They would be getting A LOT less up front bolus. So if the idea is to cover later carbs better, that’s going to come at a significant cost of upfront bolus. If you’re getting early lows and late highs, than that may work well...but otherwise you’ll more highs early from smaller upfront bolus. 

Just my two cents.

**Comment by Kdisimone** [comment]
👍👍

**Comment by beached** [comment]
One thing I have noticed is that if one puts the correction carb count in is that loop is going to potential treat for it.  If the reason for the low is incorrect basal, Boris, ISF numbers it may be more likely to bring one low again

**Comment by beached** [comment]
Maybe a way of marking carbs as tracking only.  Such that they may show up in the graphs but will not be acted upon with insulin.  Assuming one isn't rage carbing the low and it shouldn't even cause a high, but even then the system will correct for it.

Is using time as that label the correct analogy?  If I don't want to track correction carbs, why not label them.  If it needs to be stored like that, so be it, but that would be hidden from the interface.

**Comment by Kdisimone** [comment]
Logging the current lollipop carb and setting a workout target for an hour is an easy way to not overtreat low treatments (until the duration is changed 😉)

**Comment by ps2** [comment]
I do think that even low treatment carbs should be part of the algo.  There are many situations where you do want treatment for those carbs if your bg responds fast. If you don't respond fast, there will likely be no additional insulin delivered for the carbs.

**Comment by kenstack** [comment]
@brandonarbiter @ps2 hey Im just catching up on loop conversations - FWIW -  I read the above discussion with interest.  Im surprised you are seeing absorbtion times that are that fast.  Actual absorbtion times, even of pure glucose, are far slower as far as I know.  There has been quite a bit of tracer work done to support modeling over the years (ie you dope carbs with a nuclear tracer then when you take blood measurements for the next few hours after ingestion you can see what % of glucose in the blood is from your body versus the carbs ingested).  Here is an example comparing an OGTT (75g glucose ingestion) versus a meal 
![image](https://user-images.githubusercontent.com/8536751/51210087-db728580-18df-11e9-94b1-19dd9390f41c.png)

reference here http://diabetes.diabetesjournals.org/content/54/11/3265

tons more examples out there all about the same I think 

you can see even during the OGTT which is 75g of pure glucose solution - about as fast as you can get (sugar like snacks will be slower of course) the rate of absorbtion is still going almost 2 hours later.  Now, the shape of the curves are vastly different (pure glucose as you might expect keeps up a higher rate longer then tails off) versus a mixed meal, but look at the times.

the behavior I think you are seeing is that you probably ate the carbs when you were heading down so the net change to BG looks like it ends sooner then it does (you come up but the net change looks smaller and faster), but the reality is the underlying absorbtion is still going on (helping to negate what would have been a continued drop).  You should try it at night when you are flat and see how long it goes (ok - no one is ever perfectly flat but you know what I mean).  Now, these standardized OGTT tests are 75g which are quite large doses which I suppose could affect absorbtion time, but I doubt it would double or triple it.    

IMHO I wouldnt make those absorbtion times too much shorter.  I think the other effect is the carb model in loop assumes a constant absorbtion rate - you can see here for glucose thats kinda true for the first 120 min or so.  Then it drops fast to almost zero.  For a normal meal, not so much - more of the classic curve.   It would be cool to put in the more normal shape of absorbtion for a meal (there are tons of models) and then apply @ps2's dynamic carb model to a more appropriate curve.  Might fit things a bit better, though the dynamic nature of his model does help of course.

**Comment by ps2** [comment]
@kenstack The 75g of glucose is interesting.  That's a lot of sugar.  I would guess there are physiological limits to the rate of absorption that make this draw out that long. I wouldn't be surprised to see a 20g dose (a quarter the size roughly) absorb at a similar rate, so it would finish in a quarter of the time or so. Loop's carb input takes a time, not a rate, which complicates things. But the fast carbs option is most often use for rescue carbs, which are small amounts of carbs (5-15g), so I think setting a shorter term here still makes sense. Add in the fact that this is mostly used in situations of increased sensitivity, and I think that erring on the side of having them clear out of the algorithm quick is probably good. Setting 30m for quick carbs means that loop will let them effect the algorithm in a positive direction for up to 45m of effect.

I'm not planning on changing the defaults for the other meal times. Loop does tend to underestimate the initial rate of absorption for larger meals, so I think that is best addressed by looking at some other changes to the carb model.

**Comment by Nightfoxy** [comment]
If the default for fast is changed to 30 or 60 minutes, I'd like to suggest more items in the food type menu of emojis be moved to the medium category. Items like pancakes, rice, cookies, and others should not have much less than 2 hours applied to them.

**Comment by davidschouten** [comment]
Hey where can I change my absorption times? I keep on changing my 3h and 5h to 2 and 4 so would like to change it, as it makes my insulin strategy not aggresive enough to my opinion. Could use some help thank you!!
