### ISSUE TITLE
Loop 1.9.4 dev - Loop app crashes due to nightscout data backlog

### ISSUE THREAD

**Issue by human911** [LoopKit/Loop#866]
Please review the attach video and logs. 

Loop app will just freeze and then crash.

iPhone 7
iOS 12.1.3
Loop 1.9.4 Dev

Let me know if you need anything else. @ps2 

[LoopCrash.zip](https://github.com/LoopKit/Loop/files/2761115/LoopCrash.zip)

**Comment by ps2** [comment]
This should be fixed in the Loop 1.9.4 release.
