### ISSUE TITLE
G6 BG reading is way off and stuck in Loop app

### ISSUE THREAD

**Issue by brynswartz** [LoopKit/Loop#874]
This morning, I got a sensor error on my G6 app. When the sensor started work g again, my BG reading is showing 2960mg/dL in the Loop app. It’s obviously way off. My BG is actually 176. It’s also been stuck at this since this morning. My G6 app is reading accurately, but Loop is not. I’ve tried restarting the phone, closing and restarting the app, unpairing and repairing the transmitter, deleting the transmitter and using only Dexcom Share, and none of it has worked. How do I fix it?

**Comment by ps2** [comment]
I think you're seeing [this issue](https://github.com/LoopKit/Loop/issues/834), which is fixed in the current release of Loop, 1.9.4
