### ISSUE TITLE
Loop not reflecting a delivered bolus in views & calculations, despite being present in history

### ISSUE THREAD

**Issue by diggabyte** [LoopKit/Loop#876]
**Describe the bug**
This could potentially be a case of over-delivery from a missing a bolus entry. 

- Created a meal entry, delivered the recommended bolus. 
- About 90mins later, I noticed that Loop was aggressively high-temping and did not reflect the correct IOB. Close inspection indicated the insulin graph and IOB both were [missing the bolus entry completely](https://user-images.githubusercontent.com/857573/52149553-4d5e0500-262a-11e9-8320-dca20b25eda4.PNG).
- I immediately checked the pump's bolus history and confirmed it had, in fact, [been delivered](https://user-images.githubusercontent.com/857573/52148148-1128a580-2626-11e9-9773-d6df54bf5749.JPG). 
- I then manually fetched recent history in Loop and also confirmed the [bolus entry was present](https://user-images.githubusercontent.com/857573/52148152-138aff80-2626-11e9-8561-b8856a4e4f87.PNG) and also in the [event history](https://user-images.githubusercontent.com/857573/52149041-d7a56980-2628-11e9-9727-53c8fb50f82c.jpeg). 
- Somehow, Loop had not picked the entry up and on was on track to what seemed like 200% of necessary insulin. I tapped for a recommended bolus which suggested an _additional bolus of 50% of my original bolus_. That would have been WAY too much insulin for COB. My true IOB (actual units delivered) was already at 150% of what would have been necessary for the COB
- Restarted Loop app and the bolus entry is _still_ not showing up in the graph, despite being in the present in history.

**To Reproduce**
Not sure that this will reproduce, but these are the exact steps I took:
1. Add new meal carb entry
2. Cancel recommended bolus (seemed too high for what was on my plate)
3. Immediately delete the carb entry
4. Add new (smaller) meal carb entry
5. Accept + deliver recommended bolus

**Expected behavior**
Loop should never miss a bolus that has been successfully delivered.

**Issue Report**
[Loop Report 2019-02-01 14.txt](https://github.com/LoopKit/Loop/files/2823261/Loop.Report.2019-02-01.14.txt)
[Fetch Recent History.txt](https://github.com/LoopKit/Loop/files/2823262/Fetch.Recent.History.txt)

**Screenshots**
![loop-delivery](https://user-images.githubusercontent.com/857573/52149553-4d5e0500-262a-11e9-8320-dca20b25eda4.PNG)
![pump-bolus-history](https://user-images.githubusercontent.com/857573/52148148-1128a580-2626-11e9-9773-d6df54bf5749.JPG)
![pump-event](https://user-images.githubusercontent.com/857573/52149041-d7a56980-2628-11e9-9727-53c8fb50f82c.jpeg)
![recent-history](https://user-images.githubusercontent.com/857573/52148152-138aff80-2626-11e9-8561-b8856a4e4f87.PNG)

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 12.1.2 (16C101)

**Loop Version**
 - Version Number: 1.9.4-dev
 - Repo: dm61/Loop/integral-retrospective-correction 
[Note: IRC was NOT enabled during this incident]

**CGM**
 - Device: G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 723
 - Firmware version: 2.4A 1.1 0B 0B

**Additional context**
Although I am using a build from the IRC fork, IRC itself was NOT enabled at any time leading up to this incident.

**Comment by diggabyte** [comment]
@dm61 I don't believe this has anything to do with me using your IRC branch (and IRC was toggled off at the time), but just a heads up on this

**Comment by ps2** [comment]
It looks like you might be experiencing the same bug that was reported in #853.  This is fixed in the 1.9.4 release.  You are running an earlier dev version of 1.9.4.  Also, you seem to have a backlog of pump events that need to be uploaded (see PersistedPumpEvents dating back to 2018-10-18 in your issue report). There is a fix that should help with that as well.  Let me know if you don't see the old PersistedPumpEvents clear out after updating.

**Comment by diggabyte** [comment]
@ps2 thanks. Closing issue.
