### ISSUE TITLE
bG displayed is outrageously wrong

### ISSUE THREAD

**Issue by janetkornegay** [LoopKit/Loop#878]
The loop app is showing a number higher than 2800 mg/dL even though Dexcom is fine. If I track the little dots on the app, it shows the correct value. In the chart it is just tracking across the bottom. Insulin doesn’t seem to be adjusting improperly.
I don’t know how to paste my screen shot here, sorry!

**Comment by Kdisimone** [comment]
You’re seeing this issue. https://github.com/LoopKit/Loop/issues/834

Update to Loop v1.9.4 and there’s a long term fix for that. In the meantime delete the future Bg data from Health app.

**Comment by janetkornegay** [comment]
Awesome! Thank you so much!
