### ISSUE TITLE
Uptick in loop errors with v1.9.4

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#880]
**Describe the bug**
Updated to v1.9.4 this evening. Noticing a lot of "couldNotDecode" type error messages. Red Loops are resulting. A higher instance of Loop failing vs. 1.9.3

**Attach an Issue Report**
Loggly for the last 3.5 hours reports 13 instances of this error message.
Loggly on version 1.9.3 had no instances of this error message for entire month of January. And rarely noticed a pattern of repeated failures.

<img width="1538" alt="screen shot 2019-02-05 at 8 28 59 pm" src="https://user-images.githubusercontent.com/12402160/52320537-b45e1f80-2984-11e9-835e-051a00900c6b.png">

**Phone**
 - Hardware: iPhone 7
 - OS Version: iOS 12.1.3

**Loop Version**
 - Version Number: Loop 1.9.4
 - Repo: LoopKit

**CGM**
 - Device: G6
 - Manager app: dexcom app

**Pump**
- Model: 723
- Firmware: 2.3A 1.1 0B 0B

**Comment by ps2** [comment]
This error should only be happening when we get bad packets over the radio, i.e. if there is radio interference, or the signal is too weak.  You are doing comparisons, which is great.  It is *very* important to try to keep the RF environment identical between the two runs, by which I mean do not touch the RL or the pump, as orientation can make drastic changes.  Also, the position of your body in the room can change signal strength a lot

An xcode log would be helpful here.  Most important would be to show the errors, but if you can show an equivalent "clean" run, that would be useful too.

**Comment by Kdisimone** [comment]
I'll hook up a test rig today and gather some data and logs. I'll try a 2.4 pump too and see if that has same decoding frequency.

Looking through Loggly from when we switched back to v1.9.3 to now (about 12 hours total), there have been no errors in Loop (other than the expected Loop failure while she suspended pump for shower). Same environment. But, like you say, logs will help.  I'll get them.

**Comment by Kdisimone** [comment]
Ok, so I'm on 1.9.5dev now, and within an hour of switching to that (from 1.9.3), the drops have started to happen again. Decode errors starting to show...so I just got hooked up to Xcode.  But the first errors that are happening are repeated RL disconnect/connect over and over again.  Same RL, same environment that has been fine for the previous time.  Sitting in house.

Here's the logs for that RL disconnect/connect.  I will keep capturing and see if we get decoding message error logs later.

https://gist.github.com/Kdisimone/8697ab212fc808a6d0a31f6f53d57a5b

**Comment by ps2** [comment]
There are no couldNotDecode errors in that log.  Please keep things separate if you're tracking separate errors.

**Comment by Kdisimone** [comment]
Yes, just captured it because it came right after we'd seen a decoding error message and therefore got into Xcode to start capturing logs.  I don't know whether it would've helped or not, so in the interest of thoroughness, thought it good to include. Wasn't trying to mix to issues together, just trying to not pre-filter data since I may not know which is important to your needs.  and of course, errors have stopped.  If it proves this elusive to log, I'm going to gather this is less likely a persistent than a transient issue. Which would be nice.

**Comment by Kdisimone** [comment]
So, been having decoding errors this morning and managed to keep her phone hooked up to laptop long enough to catch some logs of 3 of the instances. Definitely some poor signal strength with each decode error message. Now, the question I have is why is this more prevalent with 1.9.4/1.9.5dev than when we are running 1.9.3.  Same RL throughout, same teen, same environment...so I'd think the frequency per enviro. location would be similar. We have a good long run of data in loggly to make me feel like this really is an uptick, but is there anything that could be (really) causing it within the code?  I'll still keep watching. I was going to setup an exact same rig but with 1.9.3 and run them side by side, but then they get crosstalk errors so that's not useful lol. 

https://gist.github.com/Kdisimone/d3ba275e35a502476d2db400f3321560

**Comment by Kdisimone** [comment]
I guess I will have to do side by side testing because we are just getting slammed with errors unlike we've ever seen.  20 errors in 3 hours.  I put a new RL on her and she has been diligently carrying it with her to try to eliminate distance as a factor at all.

<img width="1398" alt="screen shot 2019-02-09 at 5 06 14 pm" src="https://user-images.githubusercontent.com/12402160/52528200-3902b380-2c8d-11e9-9f2d-4d9ef6356211.png">

**Comment by Kdisimone** [comment]
Trying new pump and new firmware.

**Comment by Kdisimone** [comment]
Is this a BT issue?

2019-02-10 09:00:28.092455-0800 Loop[2900:1734041] [GlucoseStore] Successfully purged 1 HealthKit objects older than 2019-02-10 14:00:21 +0000
2019-02-10 09:00:28.097428-0800 Loop[2900:1734271] [GlucoseStore] observeUpdates(to:error:): new: 0 deleted: 1 anchor: Optional(<HKQueryAnchor: 0x282f7ac10 584030>) error: nil
2019-02-10 09:00:29.794333-0800 Loop[2900:1734270] [BluetoothManager] Re-connecting to known peripheral F0E6F94D-555D-9270-5AF3-4D7078112053
2019-02-10 09:04:28.402820-0800 Loop[2900:1734272] [RileyLinkDevice] Did UpdateValueFor <CBCharacteristic: 0x280979c20, UUID = C842E849-5028-42E2-867C-016ADADA9155, properties = 0xA, value = <aa>, notifying = NO>
2019-02-10 09:04:28.403558-0800 Loop[2900:1734272] [RileyLinkDevice] Idle error received: rxTimeout
2019-02-10 09:04:28.404059-0800 Loop[2900:1734771] [RileyLinkDevice] Enqueuing idle listening
2019-02-10 09:04:28.404843-0800 Loop[2900:1734272] [PeripheralManager+RileyLink] RL Send (no response expected): 0603000003a980
2019-02-10 09:05:26.527428-0800 Loop[2900:1734775] [BluetoothManager] centralManager(_:didConnect:): <CBPeripheral: 0x281c759a0, identifier = F0E6F94D-555D-9270-5AF3-4D7078112053, name = DexcomME, state = connected>
2019-02-10 09:05:26.546156-0800 Loop[2900:1734775] [PeripheralManager] Configured peripheral has no services. Reconfiguring…
2019-02-10 09:05:26.640692-0800 Loop[2900:1734775] [PeripheralManager] Peripheral configuration completed
2019-02-10 09:05:26.640733-0800 Loop[2900:1734775] [PeripheralManager] Delegate configuration completed
2019-02-10 09:05:26.640798-0800 Loop[2900:1734775] [Transmitter] Listening for control commands in passive mode
2019-02-10 09:05:27.239978-0800 Loop[2900:1734882] [TransmitterManager] transmitter(_:didRead:): New glucose
2019-02-10 09:05:27.240646-0800 Loop[2900:1734882] [DeviceManager] CGMManager:G6CGMManager did update with new data
2019-02-10 09:05:27.242379-0800 Loop[2900:1734775] [PeripheralManager] Error applying peripheral configuration: notReady

**Comment by Kdisimone** [comment]
Missing several loops with this same pattern.  9:00 to the 9:04am message in particular about bluetooth

**Comment by Kdisimone** [comment]
Repeated failure pattern.  Cannot get back to back green loops ever

**Comment by Kdisimone** [comment]
New pump, fresh lithium battery, same RL kept close by.

**Comment by Kdisimone** [comment]
It does not seem as though a new BG value is triggering a pump read

**Comment by Kdisimone** [comment]
Here's an example from Anna's loop (G6 sensor/app, not share)...in this case, pump had been read at 9:47 and then g6 got a reading at 9:50.  The 9:50 CGM data point, did not pump refresh... reservoir data stayed at 9:47 timestamp,  9:55 came around and no new CGM data came in.  9:57pm, without a new 9:55 CGM data point, Loop went ahead and read the pump and set a new temp basal.

![img_6562](https://user-images.githubusercontent.com/12402160/52547921-9b3be100-2d7f-11e9-841d-a01b5f6a4846.PNG)

Then, after that, a new CGM data came in at 10:00 (as it should), but no pump data refresh from that.  Stuck at 10:57.  This pattern is what we keep seeing...new cgm reading doesn't trigger any action.  So at best we are every other BG looping.

![img_4d001ae9d853-1](https://user-images.githubusercontent.com/12402160/52548099-6da36780-2d80-11e9-9254-841226ced6ad.jpeg)

hope that helps.  Logs above in the previous comments should have same pattern showing several times.

**Comment by Kdisimone** [comment]
MySentry issue (solved now) appears to have been a major factor in this. All seems to be back to normal, happy to report.
