### ISSUE TITLE
Basal graph delayed in updating

### ISSUE THREAD

**Issue by cboz718** [LoopKit/Loop#884]
**Describe the bug**
Basal graph is sometimes delayed in updating to show the current temp basal rate

**To Reproduce**
I have not been able to track down the exact timing of when the graph updates but in I notice the basal graph not show the current basal rate the most when it is on the other end of the spectrum. In the example screenshots, the current time was 21:56, loop ran at 21:52, but the rate on the basal graph was still showing the rate that started at 21:46. If I force close loop and relaunch, the graph will update to show the current temp basal as I would expect.

**Expected behavior**
I would have expected that the basal graph be updated as soon as the temporary basal was set on the pump. While not an undue burden to look at both the graph and the current rate set at the top of the screen, I might just glance at the graph to see what loop has been doing with my basal. I have come to expect the next 30 minutes of set temp basal (in case of a disconnect) to be graphed out as well and this graph indicates that I was set to get a neutral or near neutral basal, where the reality is I was set at +1.45 u/h. I did not expect a 10 minute delay in a graph update, especially with a green loop.

**Screenshots**
![img_3112](https://user-images.githubusercontent.com/19609620/52834811-3a771600-30a9-11e9-8998-c9b723898997.PNG)

**Phone**
 - Hardware: iPhone X
 - OS Version: 12.1.4

**Loop Version**
 - Version Number: 1.9.4
 - Repo: Katie / Anna

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.4A

**Additional context**
Happy to help investigate any additional information needed. Thanks!
[Loop Report 2019-02-14 21:52:57-06:00.pdf](https://github.com/LoopKit/Loop/files/2867817/Loop.Report.2019-02-14.21.52.57-06.00.pdf)

**Comment by Kdisimone** [comment]
resolved by fix above
