### ISSUE TITLE
Loop crashes on Apple Watch Series 0

### ISSUE THREAD

**Issue by Lytrix** [LoopKit/Loop#886]
**Describe the bug**
Loop crashes on an Apple Watch Series 0. It builds and installs without errors, but when starting Loop on the watch it shows the loader icon and then crashes.

**Attach an Issue Report**
not applicable

**To Reproduce**
1. Click on Loop icon on Apple Watch
2. Showing loading icon
3. Crashes and returning to main screen

**Expected behavior**
Loop showing up on an Apple Watch Series 0

**Screenshots**

**Phone**
 - Hardware: iPhone 6
 - OS Version: iOS 12.1.4

**Loop Version**
 - Version Number: 1.9.4
 - Repo: Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 754
 - Firmware version: 2.4A WB

**Additional context**
Ran the proposed debugger as @mpangburn suggested on Xcode to capture the error. T
his what was returned after starting up Loop on the Watch:
```
dyld: Symbol not found: _OBJC_CLASS_$_CLKComplicationTemplateGraphicCircular
  Referenced from: /private/var/containers/Bundle/Application/34DBD240-07EE-44E8-852F-BD08CB1B459D/WatchApp.app/PlugIns/WatchApp Extension.appex/WatchApp Extension
  Expected in: dyld shared cache
 in /private/var/containers/Bundle/Application/34DBD240-07EE-44E8-852F-BD08CB1B459D/WatchApp.app/PlugIns/WatchApp Extension.appex/WatchApp Extension
```

**Comment by mpangburn** [comment]
Appreciate the report. Can you try the following?
- Select top-level Loop project in Xcode
- Select 'WatchApp Extension' under Targets
- Under the 'Linked Frameworks and Libraries' section, click the '+' and type 'ClockKit' and press 'Add'
- In the 'Status' column of the new row where ClockKit been added, change 'Required' to 'Optional'
- Build and run on-device again

**Comment by Lytrix** [comment]
This works! build it again and all works as expected again.

**Comment by Lytrix** [comment]
Created an PR for this:
https://github.com/LoopKit/Loop/pull/887

**Comment by KensingtonB** [comment]
Same issue happened to me today after installing jojo-beeps.  Thanks for the fix!

**Comment by alexwaltsilver** [comment]
Is there an update for this with Xcode 11? As you can no longer choose "required" or "optional". Instead you have "do not embed", "embed and sign" or "embed without signing"

**Comment by gonz01d** [comment]
@alexwaltsilver I was wondering the same, this is all I can find so far : [link](https://stackoverflow.com/questions/57687170/do-not-embed-embed-sign-embed-without-signing-what-are-they-what-th)

**Comment by gonz01d** [comment]
@alexwaltsilver FWIW I left the setting as `do not embed` and was able to build, deploy and debug the app on my Series 0 watch

**Comment by Kdisimone** [comment]
closed as issue is resolved. Loopdocs will be updated for new Xcode language
