### ISSUE TITLE
Dexcom can't reconnect while Tx ID is in Loop

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#895]
**Describe the bug**
We have had two instances (and I've troubleshooted a few others recently, too) where Loop turns red. I look at loop error message and get "cgmblekit.transmittererror Error 1: unknown characteristic" message (screenshots below). Dexcom app is showing Signal Loss during this time and not getting data. Dexcom transmitter has failed first, it would seem, to start this cascade.

HOWEVER, (this is the bug part), Dexcom app will not find the transmitter signal again until I clear out the transmitter ID from Loop.  This behavior also happens when trying to pair a new transmitter in Dexcom. If you've put the transmitter ID in Loop settings first before pairing transmitter in Dexcom...no pairing request will appear in Dexcom.

Once I delete the transmitter ID from Loop settings, Dexcom will get the signal again and I can add the transmitter back to Loop settings.

Tonight's instance: noticed the red loop around 30 minutes after last BG reading. Toggled BT on phone off/on. Waited 10 minutes (to try two 5-min periods of tx) to see if it would connect on its own (BLE scanner confirmed tx was still operating). Dexcom didn't recover from Signal Loss.  Deleted the transmitter ID from Loop and Dexcom reconnected within very next tx round (less than 5 min).

Previous time: noticed red loop about 55 minutes after last BG reading. Same recovery attempts/steps as described above.  

**Attach an Issue Report**

[Loop Report 2019-02-26 19:27:42-08:00.pdf](https://github.com/LoopKit/Loop/files/2908473/Loop.Report.2019-02-26.19.27.42-08.00.pdf)

**To Reproduce**
A bit hard to reproduce, since you have to have active signal loss in Dexcom to start this bug. However, probably easiest to reproduce with a reset transmitter put into Loop settings first and then try to get a pairing request from Dexcom app...it won't appear.  I've seen this in both G5 and G6 (however, tonight's system was on G6)

**Expected behavior**
Expected that Loop's transmitter ID entry would not be blocking or impeding Dexcom's ability to repair or regain signal.

**Screenshots**
![img_6726](https://user-images.githubusercontent.com/12402160/53464399-f49e4400-39fe-11e9-83ee-7f3f77b99f11.PNG)
![img_6727](https://user-images.githubusercontent.com/12402160/53464406-f831cb00-39fe-11e9-9c3f-e4cbe25f4488.PNG)
![img_6728](https://user-images.githubusercontent.com/12402160/53464411-fc5de880-39fe-11e9-8402-ecde250585e5.PNG)

**Phone**
 - Hardware: iphone 7
 - OS Version: 12.1.4

**Loop Version**
 - Version Number: 1.9.5
 - Repo: kdisimone/holly

**CGM**
 - Device: G6
 - Manager app: Dexcom G6 app

**Pump**
 - Manufacturer: Medtronic
 - Model: 723
 - Firmware version: 2.4

**Comment by jwedding** [comment]
This needs to be addressed. If nothing else, when a transmitter age hits 75 days in Loop, we should throw an alert to remind people. This could be a "Ignore for Now," "Don't Remind Me Again" warning. 

I'm willing to bet we are costing Dexcom money in sending out new Tx. It wouldn't take long until they correlate the Bridge Pulls many loopers are doing with this and quit replacing Tx.

**Comment by Kdisimone** [comment]
Sorry, I should've come back and closed this. When @ps2 did the firefly transmitter updates, he also included a fix for this. You can now get a pairing request in dexcom app even when the transmitter ID is in Loop settings. 👍
