### ISSUE TITLE
Dexcom share value different the value in loop next to loop

### ISSUE THREAD

**Issue by jcohan** [LoopKit/Loop#896]
**Describe the bug**
When there is no internet or wireless connectivity but there is bluetooth, the cgm  value to the right of the loop is not the same as the value in dexcom share.  Dexcom share gets its value from Bluetooth from the transmitter but Loop cgm value does not get updated( because internet is not accessible via cellular signal or wireless ).

The problem when there is no cell signal or wireless is that cgm value is stale

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

1. Turn on airplane mode
2. Start up dexcom share
3. Start up loop
4. Wait 

**Expected behavior**
If there is no internet or wireless the loop cgm value should get value from dexcom transmitter like dexcom share

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS] iPhone XR 
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2] 1.9.4
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6] dexcom g6
 - Manager app: [e.g. Dexcom App, Spike]. Dexcom

**Pump**
 - Manufacturer: [e.g. Medtronic] Medtronic
 - Model: [e.g. 723] 722
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by Kdisimone** [comment]
This is not a function of Loop nor a bug. 

This has to do with dexcom’s decision to retrospectively smooth cgm data displayed in share servers. The smoothed day will or can be different than the original transmitter data. Loop runs from original transmitter data, not retroactively smoothed data. 

You can read more about Dexcom’s data smoothing in the notes section at the very bottom of this page. https://developer.dexcom.com/get-egvs
