### ISSUE TITLE
G6 calibrations not picked up

### ISSUE THREAD

**Issue by rumil** [LoopKit/Loop#898]
Even though G6 does not require calibrations, sometimes it is still useful to calibrate it.
When entering calibration in Dexcom G6 app, Loop doesn't seem to intercept it correctly.

I did a calibration in G6 app at 18:13 ("Ostatnia kalibracja" is "Latest calibration"):
![img_1601](https://user-images.githubusercontent.com/4641980/53829244-01331700-3f80-11e9-9bcd-3c18f2a156a9.PNG)
You can clearly see in BG graph when this happened:
![img_1599](https://user-images.githubusercontent.com/4641980/53829308-27f14d80-3f80-11e9-9c6a-e27faa02bd37.PNG)
However viewing G6 information in Loop does not show any calibration events:
![img_1600](https://user-images.githubusercontent.com/4641980/53829349-3dff0e00-3f80-11e9-81ea-865e2855406b.PNG)
 
**Attach an Issue Report**
[Loop Report 2019-03-05 19_41_09+01_00.txt](https://github.com/LoopKit/Loop/files/2932357/Loop.Report.2019-03-05.19_41_09%2B01_00.txt)

**To Reproduce**
1. Calibrate in official Dexcom G6 app
2. Go to Loop -> Settings -> Dexcom G6 - no calibration information is present

**Expected behavior**
Loop should intercept calibration event

**Phone**
 - Hardware: iPhone X
 - OS Version: iOS 12.1.4

**Loop Version**
 - Version Number: 1.9.4
 - Repo: katie-anna

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom app

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.2A 1.1 0B 0B

**Comment by shaun-22** [comment]
For what it's worth: I've experienced this as well on the omnipod-testing branch. Can also provide issue report if helpful, though I'm guessing this is a well known issue at this point. 

@ps2, I know that momentum effect isn't calculated if one of the last 3 points is a calibration point, but do calibration points impact calculation of retrospective correction at all? E.g. if calibration has caused a 50 point drop in BG during the 30 min look-back window, will retrospective correction consider that a forecast error?

**Comment by sraka1** [comment]
@ps2 @mpangburn I still see this in dev and autobolus. I then have RC discrepancies of up to 2 mmol. I think this could have a pretty severe adverse effect if the calibration induced RC actual BG is higher than predicted (delivering too much insulin - hypoglycemia), perhaps Tidepool could address this and backport into DIY. I think resetting RC on a calibration would be a safe bet. (Ignore the Integral part in screenshot...just testing, behaviour is same on all branches)

![1D658D9E-5FFC-4C7E-BBDB-F14D32DC644F](https://user-images.githubusercontent.com/788904/83734055-c0c4bc00-a64e-11ea-861b-ec5e8e3da1eb.png)

**Comment by elnjensen** [comment]
For what it’s worth, I regularly have big calibration jumps like that on G6 as well - factory calibration on a new sensor is almost always too high, so I calibrate on the first few days with big downward drops.

**Comment by loyalchallenger** [comment]
> For what it’s worth, I regularly have big calibration jumps like that on G6 as well - factory calibration on a new sensor is almost always too high, so I calibrate on the first few days with big downward drops.

Same for me, which also results in false dexcom alarms going off all night.

**Comment by ps2** [comment]
@sraka1 Yes, you are correct that RC is *not* disabled when a calibration is part of the recent history, and it is indeed something we're looking at changing.

**Comment by marionbarker** [comment]
I captured a log after a calibration event. I’d been out of contact of Loop just prior to calibration. So I captured a second log 15 minutes later (coincident with posted screenshot). Let me know if you want one or both. (These are still running 4+MB each even though I’m no longer running Tidepool code.)

![4D2B282C-2957-4DAE-8A43-15C5BB4C1155](https://user-images.githubusercontent.com/19607791/83791591-cfab6e80-a64e-11ea-8aa5-b98ac6b262b5.png)

**Comment by elnjensen** [comment]
OK, attached is an Issue Report from a recent case where I see the original issue - calibration on Dexcom G6 that is not picked by Loop.   Calibration was at 5:10 PM EDT (21:10 UTC).  


[Loop Report 2020-06-09 17:54:12-04:00.txt](https://github.com/LoopKit/Loop/files/4755077/Loop.Report.2020-06-09.17.54.12-04.00.txt)


![IMG_3755](https://user-images.githubusercontent.com/2545845/84205617-793d9600-aa7b-11ea-8ae4-27d845447482.PNG)



![IMG_3756](https://user-images.githubusercontent.com/2545845/84205650-8c506600-aa7b-11ea-837f-d43a64e7145c.PNG)
