### ISSUE TITLE
14hrs grey loop

### ISSUE THREAD

**Issue by diabeteco** [LoopKit/Loop#901]
**Describe the bug**
for 3 days i had to replace the Dexcom G6 Sensor. I entered the new TransmitterID into the loopapp settings. Friday 8th, 8pm start the looperrors. first with red loops till the next morning and then there where a grey loop.
try to install an other loop version (from eric jensen (1.9.3) to holly (1.9.5) to Loop-Master (1.9.4)) and i still have a red loop
I can enter carbs, i can start a bolus and everything. scan for radiosignals,  which pumpmodel i have, pumpstatus, basalplan etc

**Attach an Issue Report**
[Loopissuereport.zip](https://github.com/LoopKit/Loop/files/2948818/Loopissuereport.zip)

**To Reproduce**
What i've done:
- turned on/off Bluetooth
- turned on/off rileylink in the loopapp an on the hardware
- turned on/off the iphone
- restarted loopapp AND dexcomapp

**Screenshots**
![fullsizeoutput_21f2](https://user-images.githubusercontent.com/11704973/54090951-4b4e3b00-437a-11e9-9337-1d40078bdb49.jpeg)

**Phone**
 - Hardware: iPhone XS Max
 - OS Version: iOS 12.1.4

**Loop Version**
 - Version Number: 1.9.3 // 1.9.5 // 1.9.4
 - Repo: Eric Jensen // Holly // Master

**CGM**
 - Device: Dexcom G6
 - Manager app: DexcomG6 App

**Pump**
 - Manufacturer: Medtronic
 - Model: 754
 - Firmware version: 2.6A 1.1 0B 0B

**Comment by ishinne** [comment]
Update:
switched to a 722 pump and have the same issues

**Comment by Kdisimone** [comment]
Your issue report says "dosingEnabled: false" which means you are in open looping mode. 

Toggle your loop settings for closed/open loop.  Also, what are your Health app settings (permissions) for Loop? Check them in Health app.

**Comment by Kdisimone** [comment]
And please upload an updated Issue Report after checking those and toggling loop settings slider for closed loop

**Comment by ishinne** [comment]
yes i was in an open loop, but the loop was still red/fgrey. atm its grey since couple of hours :(
loop can write and read the healthapp

**Comment by ishinne** [comment]
[Loop Report 2019-03-11 20:00:07+01:00.pdf](https://github.com/LoopKit/Loop/files/2953797/Loop.Report.2019-03-11.20.00.07%2B01.00.pdf)

**Comment by Kdisimone** [comment]
Loop can read/write what in Health App?  Screenshot helpful

**Comment by ishinne** [comment]
![IMG_0296](https://user-images.githubusercontent.com/11704973/54150639-3ab0ca00-4439-11e9-9cf4-3d2765395f37.PNG)

**Comment by Kdisimone** [comment]
Can you please upload screenshot of a radio tune?

**Comment by ishinne** [comment]
![IMG_0298](https://user-images.githubusercontent.com/11704973/54150870-d4787700-4439-11e9-90c4-7a24fbb54a50.PNG)
![IMG_0297](https://user-images.githubusercontent.com/11704973/54150894-dd694880-4439-11e9-957c-ad46f3bd7cd8.PNG)

**Comment by ishinne** [comment]
@Kdisimone the loopapp works very well since the November 14th 2018. But after my first G6 Transmitterchange, the problems begun :-(

**Comment by ps2** [comment]
Make sure your transmitter id is correct. You have `80QNE2`.  Is maybe the `0` supposed to be a `O`?

**Comment by ishinne** [comment]
@ps2 all G6 Transmitters, here in Germany starts with 80 (eight-zero)

**Comment by karrakerc** [comment]
Loop Version: 1.9.4
Pump: Minimed 523
Rileylink Firmware: subg_rfspy 0.9 / ble_rfspy 0.9
Dexcom G6

This issue started happening to me as well, first ti went red for a number of hours as I was near the end of my sensor life, replaced sensor, and I still cannot get it back to a green loop.  When I tap on the grey loop it says, "The Operation couldn't be completed. (Shareclient.shareerror error 1.) loginError (errorCode:"SSO_AuthenticateMaxAttempsExceeded")"

It says that in diagnostic report as well.  I've tried Closing the apps out, turning off bluetooth, and then firing up the loop followed by the Dexcom app. Any insights would be appreciated.
[Loop Report 2019-03-12 114933-0500.md.txt](https://github.com/LoopKit/Loop/files/2957942/Loop.Report.2019-03-12.114933-0500.md.txt)

**Comment by diabeteco** [comment]
the 722, that i'm using now atm says, when i tap on the red loop "Device Error - Pump did not respond in time". Funny fact: in the Settings i can fetch recent history, get pump model, send button press, read pump status successfully.
[Loop Report 2019-03-12 14:01:54+01:00.md.txt](https://github.com/LoopKit/Loop/files/2957998/Loop.Report.2019-03-12.14.01.54%2B01.00.md.txt)

**Comment by Kdisimone** [comment]
@karrakerc delete your CGM in Loop Settings, add it back with just the transmitter ID.  If you want to then go back and add your Dexcom Share Credentials after you Loop turns green, go ahead.

**Comment by Kdisimone** [comment]
@diabeteco do you have two loop apps on your phone or one?

**Comment by diabeteco** [comment]
@kdisimone only one

**Comment by Kdisimone** [comment]
Your pump ID is garbled in Issue Report. Odd, but I'd delete that pump and see if you can get that fixed up by adding it back fresh.
![IMG_2351](https://user-images.githubusercontent.com/12402160/54231640-1b13b300-44c6-11e9-9631-7e34291bdbdf.jpg)

**Comment by diabeteco** [comment]
pumpID is just a √
that the id is garbled must be a failure from the ".md.txt" becuase .md files are not allowed for an upload :(

**Comment by Kdisimone** [comment]
@diabeteco Not said poorly, but it will sound that way...there's not much to go on for what you're doing there and feels like I'm not seeing everything I'd need to in order to dig deeper. If I were in your shoes, I'd disconnect RL from Loop app, delete CGM from Loop settings, and delete Loop app.  Then rebuild all fresh.  Super fresh with a master build. Make sure RL is charged.

**Comment by karrakerc** [comment]
> 
> 
> @karrakerc delete your CGM in Loop Settings, add it back with just the transmitter ID. If you want to then go back and add your Dexcom Share Credentials after you Loop turns green, go ahead.

I've done this twice today and it still hasn't turned Green. I made sure my Rileylink was charged and it's reporting Dexcom Data that is no more than a minute old.

**Comment by Kdisimone** [comment]
You’ve left your dexcom credentials empty, correct?

**Comment by karrakerc** [comment]
That’s correct, to be safe though I’ve deleted and re-added the cgm, there was no sharing account set up in the loop can settings so I left that as is, and then I went over to the dexcom app and turned sharing off in the settings there as well.

**Comment by diabeteco** [comment]
Thank you @Kdisimone . i've deleted the loop app and rebuild it complete new. now it was a green for an hour ... since 11min yellow with a decoding error.
"invalid response during pumpmessage (carelink, pumpack, 3 bytes, 1 bytes)

installed the loop-master from the loop docs
