### ISSUE TITLE
Glucose data is 3 hours behind

### ISSUE THREAD

**Issue by jspfree2** [LoopKit/Loop#905]
I am using Dexcom G6 and my glucose data in the loop app is exactly 3 hours behind. I have both the transmitter ID and dexcom Share account info entered into the loop app correctly. My nightscout data at the right time using the same Decom Share username and password.

I apologize I am very code naive as a good friend set up the code in Xcode.

I am hoping its something simple in the coding?

Coudl someone please offer suggestions. 

Many thanks in advance - the pic below shows the CGM graph with data at 5.30am but its actually 8.30am 

![image](https://user-images.githubusercontent.com/48617945/54518163-914b6600-495b-11e9-8293-7dd22ef22ff3.png)

**Phone**
 - Iphone 7 
IOS 12.1.4

**Loop Version**
 - V1.9.4

**CGM**
 - Dex G6
 - Dexcom App

**Pump**
 - Medtronic VEO
 - V2.5A 1.1 0B 0B

I am awaiting my Riley link to set up the pump but obviously, need the glucose data to be up to time.

**Comment by elnjensen** [comment]
This will fix itself when you have your RileyLink.  Without regular communication with a RL, the Loop app doesn’t stay awake in the background, and thus it doesn’t intercept the BG signals from the Dexcom in real time. Instead, it can only get glucose data from HealthKit, which Dexcom app only writes to with a three-hour delay.

**Comment by Kdisimone** [comment]
Thanks for replying @elnjensen. I'll close this issue at this time as the response should have resolved the original question.  If @jspfree2 has any issues after the RL arrives and Loop setup with it, we can reopen or make a new issue.
