### ISSUE TITLE
Insulin and Carbohydrate graphs trail off left edge of screen when returning to app

### ISSUE THREAD

**Issue by paulforgione** [LoopKit/Loop#907]
**Describe the bug**
When returning to the Loop app, there will sometimes be visual artifacts in the Insulin and Carbohydrate graphs on the homescreen of the Loop app. Part of the charts are rendered off the left edge of the graph, beneath the Y axis labels and up to the edge of the display.

**Attach an Issue Report**
Issue report cannot be generated while this display issue is still visible. Once a report can be generated, the app has come back into memory and refreshed the graphs.

**To Reproduce**
1. Open Loop app, allow everything to load.
2. Leave the Loop app, switch to a few different apps, or wait some period of time (at least 5 minutes, for another CGM reading / Pump temp basal to occur)
3. Return to the Loop app
4. Note that Loop may have been kicked out of memory on the iPhone. This is expected behavior. 
However, while Loop is loading back in, said charts may appear with the above mentioned glitches. It is also not possible to capture an Issue Report until things are loaded again.

**Expected behavior**
Graphs should appear as they were when you last left the Loop app, until Loop has been brought back into memory, and new CGM / insulin data has been loaded.

**Screenshots**
![IMG_0251](https://user-images.githubusercontent.com/4359124/54766804-54d56f80-4bd2-11e9-8f44-2b5d3a11e954.PNG)

**Phone**
 - Hardware: iPhone XS Max
 - OS Version: iOS 12.1.4

**Loop Version**
 - Version Number: 1.9.5DEV
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom G6

**Pump**
 - Manufacturer: All pumps

**Additional context**

**Comment by ps2** [comment]
This seems related to https://github.com/LoopKit/Loop/issues/1243, which covers the extension of the basal line to the left of the graph, and a fix was included in Loop 2.2. I have not seen Active Insulin and Active Carbohydrate graphs do this, at least recently. Is this still an issue for those graphs?
