### ISSUE TITLE
CGM Dexcom data 3 hours behind even though Riley Link now setup

### ISSUE THREAD

**Issue by jspfree2** [LoopKit/Loop#909]
I have set everything up and all is working:
Riley link to VEO Pump
Dexcom G6 is linked

But
![Uploading IMG_
![IMG_1227](https://user-images.githubusercontent.com/48617945/55027920-58b42800-4ffe-11e9-8a3d-0195f2320cb2.PNG)
![IMG_1229](https://user-images.githubusercontent.com/48617945/55027921-58b42800-4ffe-11e9-9d06-d8e5b8a4306c.PNG)

1228.PNG…]()
![Uploading IMG_1227.PNG…]()
![Uploading IMG_1229.PNG…]()
![Uploading IMG_1229.PNG…]()
![Uploading IMG_1228.PNG…]()
![Uploading IMG_1227.PNG…]()

![IMG_1228](https://user-images.githubusercontent.com/48617945/55027918-581b9180-4ffe-11e9-8096-50201e3acf7a.PNG)

My Dexcom CGM data is 3 hours behind.

It was suggested once my Riley link was connected it would catch up. But this has not happened.

iPhone 7
OS 12.1.4
 - OS Version: [e.g. iOS 12.0.1]

Loop V1.9.4

Dexcom G6 using Dexcom APP - Bot transmitter and Dexcom account entered

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by Kdisimone** [comment]
You need to turn on Loop's ability to read and write BG values in your Health app.

**Comment by Kdisimone** [comment]
https://loopkit.github.io/loopdocs/build/health/
