### ISSUE TITLE
Loop does not work; white screen

### ISSUE THREAD

**Issue by Ruud3** [LoopKit/Loop#911]
**Describe the bug**
This morning Loop did not want to start on my iPhone . When clicking the icon a white screen appears and quickly thereafter disappears again. 
When I swipe up Loop appears between the other programs , however when I select it, the white screen appears and disappear again.
My Dexcom G6 has not worked properly last night (only a few measurements) and has to be replaced.
BG was high this morning and according Nightscout the Loop has not made any pump changes since 23:37h last night

**Attach an Issue Report**
I can’t open the Loop program.

**Phone**
 - iPhone X
 - iOS 12.2

**Loop Version**
 - Version Number: ? Installed the program 6 days ago

**CGM**
 - Dexcom G6
 - Dexcom App

**Pump**
 - Medtronic
 - 722
 - Firmware version:  2.4A 1.1 0B 0B

**Comment by elnjensen** [comment]
Sounds like you may have hit the end of your 7-day period between builds if you’re using a free rather than paid Apple Developer license. Try rebuilding the app and reinstalling to your phone. If your phone is at iOS 12.2 you may need Loop 1.9.5.

**Comment by Ruud3** [comment]
Thanks Eric,
I’ve a paid account. My iPhone apparently was updated automatically to IOS 12.2.
I’ve updated the program and it is running now.

Thanks


 Ruud
