### ISSUE TITLE
Incorrect BG displayed in Loop

### ISSUE THREAD

**Issue by ElizabethZ85** [LoopKit/Loop#913]
My sensor glucose from Dexcom G6 is thousands of points off compared to the number displayed in my Loop app.  What is causing this?

**Comment by ps2** [comment]
Sounds like you're experiencing the issue described here: #834. Please remove the future BG value from HealthKit, and upgrade your Loop app to prevent this from happening in the future.

**Comment by ElizabethZ85** [comment]
Yes, that fixed it.  Thank you!


Sent from Yahoo Mail for iPhone


On Saturday, March 30, 2019, 21:13, Pete Schwamb <notifications@github.com> wrote:


Sounds like you're experiencing the issue described here: #834. Please remove the future BG value from HealthKit, and upgrade your Loop app to prevent this from happening in the future.
