### ISSUE TITLE
tomato app/loop

### ISSUE THREAD

**Issue by davidmlb** [LoopKit/Loop#915]
My son is a looper for  2 years, 

after testing all cgm, de best and acurate is freestyle for us, and very important for us is the possibility to work offline with loop.

untill now we're working with spike, but teh future for spike seems not clear. 

I think tomato app can work with loop but not directly (offline) you need to send first data to Nightscout. 

Could be possible that tomato could work directly (ofline) with loop? 

thanks

**Comment by JoernL** [comment]
I've read that tomato app now supports pebble/garmin/fitbit watch support via internal offline server http://127.0.0.1:11111. This should be easy integrate into loop app as bg source?

**Comment by davidmlb** [comment]
but the internal server is only abailable in Android App, I think

**Comment by Kdisimone** [comment]
In order for a CGM to be integrated into Loop, and for the SAFETY of the users, Loop will need the algorithm used to turn raw data into bg values to be the manufacturer’s algorithm. If it’s not their’s, it should be a fairly high bar for showing either that it is equivalent (accounting for all the sensor’s measurements, including temperature, age, etc), or independently shows accuracy in some way. The system must function offline. If the system requires calibration, then there must be controls that don’t let the system provide data when the proper calibration is not performed. Using an algorithm that is basically a simple slope/intercept algorithm means the user should be very considerate about sensor calibration hygiene, and watch for signs that the calibration may be off. Any CGM integration using that kind of algorithm should have UI controls, as well as specific user documentation/training around calibration.

**Comment by ps2** [comment]
The above is repeating what I've said before, and I think it still holds true. We *would* like to open Loop up for use with other sensors, so more people have access, but there are significant safety concerns that need to be mitigated when doing so, especially if there is calibration involved.

**Comment by paulvugteveen** [comment]
> I've read that tomato app now supports pebble/garmin/fitbit watch support via internal offline server http://127.0.0.1:11111. This should be easy integrate into loop app as bg source?

Do you know where I can find detailed information about connecting my tomato app to garmin? Originally I was going to connect with xdrip, but my bluetooth wont stay connected to xdrip and so I've been using the tomato app.
