### ISSUE TITLE
Medtronic 554 not responding to Riley Link Scan 

### ISSUE THREAD

**Issue by jspfree2** [LoopKit/Loop#921]
My looping has been working perfectly for 3 months. No changes in any pump settings etc. Then yesterday the Riley Link cannot find the pump - Medtronic 554.

I have tried
1. Fetching data
2. Tuning Riley Link
3. Changing the battery
4. Moving out of other RF technology
5. Ensuring all devices are fully charged

I have attached the report.

![IMG_1314](https://user-images.githubusercontent.com/48617945/56486664-4d0a3300-64d0-11e9-8142-e30189634a91.PNG)

**Phone**
Iphone 7
12.1.4

Loop
V1.9.4

Dexcom G6 - using the APP

Medtronic 554
V2.5A

**Comment by Kdisimone** [comment]
sorry, no error report is attached here. I'll be closing this out for now as it would appear to be an issue associated with this particular pump as opposed to 554 v2.5A pumps in general. We can reopen if other 554 v2.5A pumps report problems and can provide debugging logs from xcode. Thanks
