### ISSUE TITLE
Loop Crashes after OmniPod setup Drawing Charts

### ISSUE THREAD

**Issue by npassero** [LoopKit/Loop#922]
**Describe the bug**
First setup of OmniPod device. Activated a new Pod, primed, and ready to go. First Pod so entered all of the settings (Bolus, correction, insulin type, etc.). After saving all of the data the UI crashes and does not load the charges. 

**Attach an Issue Report**
Unable to generate an issue report. UI is locked up. Grabbed logs from Xcode (attached). 
[2019-04-22-Loop.txt](https://github.com/LoopKit/Loop/files/3105452/2019-04-22-Loop.txt)

**To Reproduce**
1. Setup OmniPod Eros
2. Setup Bolus/Rates/Schedule
3. Click Done
4. UI Does not Load - Error in XCode debug logs

**Expected behavior**
After Pod setup, display generic information.

**Phone**
 - Hardware: iPhone SE
 - OS Version: 12.2

**Loop Version**
 - Version Number: 1.10.0dev
 - Repo: Loop-OmniPod-Testing

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: N/A

**Comment by loudestnoise** [comment]
Wonder if it’s freaking out because your Pump data date is - 

Loop.LoopError.pumpDataTooOld(date: 0001-01-01 00:00:00 +0000)

**Comment by ps2** [comment]
You mention an "Error in Xcode logs". Were you able to save this?  And @loudestnoise that date just indicates it hasn't read from the pump yet

**Comment by ps2** [comment]
Catching this crash in xcode and seeing a stack trace would help.

**Comment by npassero** [comment]
Screenshot of Xcode debug.

<img width="1404" alt="Screen Shot 2019-04-23 at 7 52 29 AM" src="https://user-images.githubusercontent.com/1819417/56578955-df780880-659c-11e9-83c1-271ed0443be7.png">

**Comment by Lytrix** [comment]
I think you might have switched the upper/lower values of one of the correction ranges. That will make Loop crash. If you delete Loop from your phone (to remove these settings) and rebuild, does that work?

**Comment by npassero** [comment]
Is there a way to modify this at runtime or to modify the datastore to try and correct the information without a reinstall? Otherwise I can do another setup.

**Comment by Lytrix** [comment]
No, all settings are stored on your phone and cannot be accessed. Rebuilding is the fastest option. And because carthage has already build the frameworks, it will take only a few minutes now.

**Comment by npassero** [comment]
Resolved it by reinstalling - 

Correction Range was previously set to 120-80 and was causing the interface to fail to draw the chart based on the rules. Would recommend a check on this interface to ensure value A <= value B. 

Human error..

**Comment by naromero77** [comment]
I ran into this issue today. Even with the re-install of the app. Is there anyway to re-pair a pod that was previously set-up?

**Comment by npassero** [comment]
No way to access the existing Pod for boluses since the interface is locked up. The basal program will continue to run in the background. You are better off uninstalling/reinstalling Loop and setting up a new Pod. 

You can setup the Pod Configuration before activating a new Pod. Restart the app and confirm it loads successfully before registering your next Pod to make sure the configuration was done correctly.

**Comment by Kdisimone** [comment]
Closing issue as https://github.com/LoopKit/Loop/commit/324ef2f6f601f7199d94b8a35b4971ae03fc8c2a resolves the ability to enter ranges backwards
