### ISSUE TITLE
Watch App bolus precision doesn't match Omnipod's

### ISSUE THREAD

**Issue by shaunlichti** [LoopKit/Loop#925]
**Describe the bug**
When using the bolus interface on the Loop Apple Watch app, it is possible to dial in a bolus amount with greater precision (0.025 units) than Omnipod can actually deliver. Issue occurs when selecting a bolus value < 1 unit.

**Attach an Issue Report**
N/A

**To Reproduce**
1. Go to Loop app on Apple Watch
2. Tap on Bolus
3. Use digital crown on the side of the watch to dial the bolus down to a value < 1 unit. 
4. Observe dose increments of 0.025 units.

**Expected behavior**
All possible bolus dose selections will conform to the delivery constraints of the given active pump. 

**Screenshots**
![IMG_4340](https://user-images.githubusercontent.com/48635533/56624824-66ee6780-65ef-11e9-9239-cd3165013564.PNG)

**Phone**
 - Hardware: iPhone XS
 - Software: iOS 12.2
 - Watch Hardware: Apple Watch Series 4
 - Watch OS: 5.2

**Loop Version**
 - Version Number: 1.10.0DEV
 - Repo: LoopKit/Loop/omnipod-testing

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros

**Additional context**
This is based on my understanding that Omnipod's delivery precision is 0.05u/pulse. Apologies if I've misunderstood something here!

**Comment by CaspianGeben** [comment]
I would like to add a +1 on this issue
