### ISSUE TITLE
A different way of calculating insulin on board – using u/kg of insulin on board to determine rate of decay?

### ISSUE THREAD

**Issue by jspfree2** [LoopKit/Loop#926]
A different way of calculating insulin on board – using u/kg of insulin on board to determine rate of decay?

I have been looping for 3 months now and love it!

The main challenge I am having is getting the insulin on board set correct.

The man issue is that the research shows the peak action time and total duration of action is determined by the insulin dose per kg of body weight. A picture from the attached paper compare Fiasp and Aspart below showing this reasonably clearly.

![Capture](https://user-images.githubusercontent.com/48617945/56645091-e96d3a80-6674-11e9-9e8f-626bac25d68e.PNG)
[Aspart vs Fiasp - all about u per kg.pdf](https://github.com/LoopKit/Loop/files/3111353/Aspart.vs.Fiasp.-.all.about.u.per.kg.pdf)
 

As my usual meal doses +/- adjusted basals is about 3-5 units and I weigh 100kg, my u/kg is about 0.03-0.05u/kg – therefore my peak action should shorter 50-60mins and total duration about 240 mins normally.

This is why the 6 hours curves do not work for me and why the walsh with too late peak action is not ideal, even if set at 4 hours. I know you can change this in the coding – which I am going to do. Putting peak at 55mins and total duration at 240mins.

This will solve most issues BUT it will not solve when:

1.	I have a huge meal of 15units (0.15u/kg) and I would need the peak at 75 mins and total duration at 300mins
2.	A tiny snack of 1.5 units (0.015u/kg) where a peak of 45 mins and total duration of 200mins would be ideal

Is there anyway the coding could look at:
1.	Asking for the users weight on set up and every 6months (to keep up to date) so that each time a extra insulin above normal basal is given it works out the u/kg and then applies a u/kg decay of insulin to that amount? 
a.	This would require curves for u/kg ranges e.g.
i.	0.0-0.05 = peak 45mins total duration 200mins
ii.	0.05-0.1 = peak 55mins total duration 240mins	
iii.	0.1-0.15 = peak 70mins total duration 300mins	
iv.	0.15-0.2 = peak 80mins total duration 360mins	
v.	0.2-0.25 = peak 90mins total duration 400mins
vi.	0.25+ = peak 100mins total duration 440mins

I unfortunately cannot code but work as a specialist dietitian in diabetes and would be happy to work with someone to flesh out this idea.

Cheers

John

**Comment by scottleibrand** [comment]
A couple comments:

Firstly, it does not appear that this study actually evaluated the time of peak insulin activity in a statistically rigorous way: they were focused on other endpoints, and the graph doesn’t allow us to tell with enough precision how much the peak time varies between dose sizes, even in the idealized euglycemic clamp situation, and even with super-high doses of 2-8x as much insulin as most people would bolus at one time for an average meal. 

Secondly, this study was done using injection pens, not insulin pumps. We know that Fiasp behaves differently when infused through a pump, where the depot is being continuously perfused with the Fiasp excipients (via basal insulin infusion), than in a pen injection, where the excipients are flushed from the depot before the insulin has finished absorbing. This effect likely accounts for some of the relatively faster speed of action of smaller pen injections, but would not necessarily translate to the behavior seen with pump boluses. Also, to the extend absorption speed is a function of depot size, the presence of a basal insulin depot would further mitigate the differences in speed between pump boluses of different sizes. 

If you’re interested, autotune has an experimental function that allows it to tune insulinPeakTime and insulinEndTime: you could try running that on a VM against your NS data and see what it finds. Unfortunately I don’t think there’s enough data available to autotune different sized meals separately, so the best we can do is estimate an overall average value for each parameter.

**Comment by scottleibrand** [comment]
This article may also be of interest regarding my comments about how fast the excipients get flushed from the depot: https://rdcu.be/bmlzb
