### ISSUE TITLE
omninod public testing branch: cancelled bolus appears in active insulin

### ISSUE THREAD

**Issue by naromero77** [LoopKit/Loop#932]
**Describe the bug**
If you cancel a bolus, you should **not** expect to see it appear in the active insulin graph. However, it does appear **both** for the total amount of the bolus and the partially administered bolus (incorrect) In the event history, you will see **only** the partially administered bolus (correct)

If you shutdown down Loop, and restart it. You only get the partially administered bolus appearing in the active insulin graph (correct).

Just my two cents, looks like a race condition.

**Attach an Issue Report**
Sorry -- first time filing an issues and didn't capture the report.

**To Reproduce**
1. Administer bolus
2. Cancel immediately
3. See active insulin graph.

If it's a race condition, you will have to try this many times to reproduce it.

**Expected behavior**
You should only see the insulin from the partially administered bolus in the active insulin graph.

**Screenshots**
Sorry, don't have this either.

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.2

**Loop Version**
 - Version Number: omnipod-testing
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App
**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Eros
 - Firmware version: idk

**Comment by naromero77** [comment]
seems very similar to this issue:
https://github.com/LoopKit/Loop/issues/927

**Comment by naromero77** [comment]
This is with the Jojo branch, but its basically the same problem.

First time it happened, it failed on the authentication of my wife's thumb print. Bolus of 1.1 was delivered, but then counted twice in the active insulin.

Second time, no authentication failure. But it counted the bolus of 4.75 twice.
![Image-1](https://user-images.githubusercontent.com/7633854/57575727-e82e6280-7415-11e9-920c-293945aafd37.jpg)

[Loop Report 2019-05-11 17_38_05-05_00.md.txt](https://github.com/LoopKit/Loop/files/3169517/Loop.Report.2019-05-11.17_38_05-05_00.md.txt)
[Loop Report 2019-05-11 17_09_33-05_00.md.txt](https://github.com/LoopKit/Loop/files/3169518/Loop.Report.2019-05-11.17_09_33-05_00.md.txt)

**Comment by yaelirt** [comment]
Had this issue today. Jojo branch. Entered a bolus that failed (had a notification and also no clicks), gave another one and deleted the first entry, but the active insulin is still calculated as if both boluses were delivered.
