### ISSUE TITLE
Setting Carb Ratio to 0g/u will crash loop sporadicaly

### ISSUE THREAD

**Issue by micro17** [LoopKit/Loop#941]
Hi
at first setup i set the carb rating to 0 as i was not sure. When set to 0 loop is crashing every time I opened it. Reproducible.

Thanks

Max

**Comment by RobCvdV** [comment]
O dear. That is also very dangerous. Setting a zero ratio for carb ratios or insuline sensitivity will make loop think you need an infinite amount of insuline. Read the docs carefully. It's a good thing loop crashed or else you might have.
