### ISSUE TITLE
Feature Request: Hourly max basal/bolus limits

### ISSUE THREAD

**Issue by crossfamily888** [LoopKit/Loop#943]
Latest Loop software (as of 5/2/19); Omnipod and Dexcom G6

Our children don't always eat their school meals to completion; there are times depending on the meal where the nurse may bolus after the meal. This results in a crash because of the following conditions:

1. Child eats
2. BG rises above threshold
3. Max basal kicks in
4. Child is bolused for meal, and receives appropriate insulin dose for carbs

The "extra" basal received between item 3 and 4 end up causing a hypo, because the food is partially already covered by the max basal by the time the meal bolus occurs. 

If we were able to set lower max basal limits during school hours, we could avoid hypos that occur for this reason.

We do not want to universally change the max basal limit because this is helping keep the kids in range when they help themselves to food and don't tell us (which happens constantly - they're 6 and 7)... It catches the rise very early and we can correct when we notice.

**Comment by scottleibrand** [comment]
Regardless of the limits you place on the automated portion of the system, it is dangerous for caregivers to be manually dosing insulin for a meal without regard to IOB.  You should (also) ensure that the nurses are checking IOB before dosing for the carbs, and subtracting out any positive IOB from their meal bolus.  As I understand it, this is done automatically by Loop's bolus wizard, so I would have to assume that they've been ignoring the bolus wizard recommendations and manually setting the bolus amount?  If so, that is dangerous and something they should stop doing.

**Comment by Kdisimone** [comment]
I’ll reiterate what Scott has said above. Your nurse should not be bolusing “for the carbs” but rather “for what Loop recommends”. 

And the nurse should be entering the carbs dated at the time the food was consumed. So she should (1)enter the carbs when food was eaten and bolus later or (2)enter the carbs when the bolus will be given, but backdate the timestamp to the time the meal was eaten. 

Please speak with your school nurse and get them to adapt. Their way needs to change as a reflection of an automated delivery system. Now insulin will be delivered without the need of a nurse pushing buttons...so s/he needs to change their ways to prevent overbolusing.

**Comment by Kdisimone** [comment]
If nurse is going to choose option (1), make sure she’s not double entering carbs.
