### ISSUE TITLE
Failed bolus uncertain 

### ISSUE THREAD

**Issue by claraloop** [LoopKit/Loop#944]
**Describe the bug**
Bolus error uncertain
No clicks heard bg did not drop after 30-40 min
Event was logged as 1,4 units uncertain
It stayed there . Husband erased it he was trying to make loop forget it so that it would bolus our son insulin again.
It still shows in apple health. It was given today at 16:55 1,4 units

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: iPhone 5 se
 - OS Version: iOS 12.1

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: omnipod

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: omnipod
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by claraloop** [comment]
I can’t find the attachment icon?

1f0527572c030e010001b1
* 2019-05-02 16:41:06 +0000 receive 1f052757300a1d080189b800002973ff8041
* 2019-05-02 16:50:12 +0000 send 1f05275734030e01008197
* 2019-05-02 16:50:15 +0000 receive 1f052757380a1d080189b800002997ff82c9
* 2019-05-02 17:00:15 +0

**Comment by claraloop** [comment]
Can’t attaché at the moment will try later from computer

**Comment by tkk41** [comment]
here the same, **initiated a bolus, but didn't start**.
RL was close to the pod approx 50 cm

I have run "Test Command" (see screenshot)
Attached is the issue report (created after running the Test Command)

![Test Command](https://user-images.githubusercontent.com/42779757/57674077-6bbaa000-761e-11e9-8486-53166addee5f.JPG)

[Loop Report 2019-05-13 09_23_15+02_00.pdf](https://github.com/LoopKit/Loop/files/3176048/Loop.Report.2019-05-13.09_23_15%2B02_00.pdf)
