### ISSUE TITLE
Feature Request: Upload Loop settings to nightscout Profile

### ISSUE THREAD

**Issue by ELUTE** [LoopKit/Loop#945]
Manual profile entries in Nightscout can be tedious and often cause confusion when settings do not match those in Loop. Would be amazing if Loop could upload CR/ISF/Basal etc. to Nightscout profiles. 

Thank you!

**Comment by ArkonPhoenix** [comment]
Yes, especially if the ability to have Multiple Basal Profiles gets added to the Loop app itself. Then it would only make sense to have NS update with this info as this is also changed from one profile to the other.
