### ISSUE TITLE
Carb entries over maximum limit show an alert that cannot be dismissed

### ISSUE THREAD

**Issue by panctronic** [LoopKit/Loop#946]
**Describe the bug**
Entering a carb size >250g creates an onscreen alert that cannot be closed. The only resolution is to force close the app.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Click new carb entry
2. Enter a value >250g (2,356g for example)
3. Click save

**Expected behavior**
An error appears that can be dismissed, so the input can be corrected.

**Screenshots**
![IMG_1483](https://user-images.githubusercontent.com/26213122/57171289-db7f8e00-6dc7-11e9-9055-f6a03bbf51a9.PNG)

**Phone**
 - Hardware: iPhone XS
 - OS Version: 12.2

**Loop Version**
 - Version Number: 1.10.0
 - Repo: LoopKit/Loop omnipod-testing branch

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: n/a

**Additional context**

**Comment by vpdn** [comment]
This bug seem to have popped up with a refactoring done in https://github.com/LoopKit/Loop/commit/bf4166bc77f89e22971f2030ad006967881ff082. The `UIViewController.swift` helper has been replaced but the 'OK' not readded.

**Comment by Kdisimone** [comment]
fixed by PR mentioned above, tested and confirmed
