### ISSUE TITLE
"Bolus in Progress" Yellow Loop, but no ongoing bolus

### ISSUE THREAD

**Issue by shaun-22** [LoopKit/Loop#948]
**Describe the bug**
Several times I've had a yellow loop that reports "Bolus in Progress" when tapped, despite there not being a currently running bolus. 

In the case from screenshots attached, the last bolus was enacted at 10:15:31 PM. However, at 10:20 (several mins after the Bolus had completed) I was still in yellow loop and getting the error. 

**Attach an Issue Report**
https://drive.google.com/open?id=1ZErGR0aGgUvK7Z7K1qTZyYIU5MgQe0tC

**To Reproduce**
Not sure exact steps to reproduce. Occurs sporadically after a bolus has recently been issued and completed. 

**Expected behavior**
Loop does not incorrectly advise that a bolus is in progress when there is no bolus currently in progress.

**Screenshots**
![IMG_4516](https://user-images.githubusercontent.com/48635533/57199213-6039eb80-6f31-11e9-83a5-17c56249d718.PNG)
![IMG_4521](https://user-images.githubusercontent.com/48635533/57199240-a7c07780-6f31-11e9-9f15-27b8a8f6875e.PNG)
![IMG_4519](https://user-images.githubusercontent.com/48635533/57199242-ac852b80-6f31-11e9-895d-15a0f32ac986.jpg)

**Phone**
 - Hardware: iPhone XS
 - Software: iOS 12.2

**Loop Version**
 - Version Number: 1.10.0DEV
 - Repo: omnipod-testing

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros

**Additional Context**
It did occur to me that perhaps this error message is held over from the last time Loop attempted to run (3 mins prior to screenshot?) when there *was* in fact a bolus in progress... However, if that's the case, I still think the messaging should be reconsidered.

**Comment by Kdisimone** [comment]
Correct, the yellow loop error message is telling you the reason for why that Loop attempt at that timestamp could not enact.
