### ISSUE TITLE
Omnipod Pairing Failure (note running Jojo branch)

### ISSUE THREAD

**Issue by scline45** [LoopKit/Loop#953]
**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

https://gist.github.com/scline45/f1d8d5f550d35eecb608089a185973df

**Comment by Kdisimone** [comment]
attached gist indicated a paired pod. If this issue happens again and new information is obtained, feel free to update
