### ISSUE TITLE
Manually entering BG in Apple Health. BG data gets deleted in Apple Health

### ISSUE THREAD

**Issue by cfaagaard** [LoopKit/Loop#956]
Been looping for 7 months. 
During warm up of a new Dexcom G6 sensor, I manually entered BG in Apple Health.

I then noticed that several days of BG data in Apple Health were deleted just before the manually entered BG.
First I thought that I somehow made a mistake and deleted it myself.
But now I know of at least 3 other loopers who have experienced the same issue.
So I thought I better submit a bug report.
Here is a link for the facebook post with screenshots and other contacts:
https://www.facebook.com/groups/TheLoopedGroup/permalink/2233264173556903/

The BG-data also gets deleted in Tidepool, but that is maybe because of the sync between the tidepool mobil app and Apple Health.

The BG-data is not deleted in Nightscout.

**Phone**
 - Hardware:  iPhone X
 - OS Version:  iOS 12.0.1

**Loop Version**
 - Version Number:  1.9.5
 - Repo: LoopKit/Loop, Master

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic 
 - Model: 522

**Comment by ps2** [comment]
You need to allow Dexcom to store to HealthKit.

**Comment by cfaagaard** [comment]
Thank you for replying. I am pretty sure I have done this (will double check when I get access to my kids phone).

**Comment by cfaagaard** [comment]
sorry for the late reply. 
I do have dexcom as source in health, but is says "passive"??? See picture. 
![IMG_20190517_192543](https://user-images.githubusercontent.com/25353502/57946270-35aa4400-78dc-11e9-9aba-664294d6e806.jpg)

**Comment by cfaagaard** [comment]
Confirmed (multiple times) that this is not a bug in Loopkit, and the solution "You need to allow Dexcom to store to HealthKit." is working.

Should I close the issue or do you want to do it? @ps2

**Comment by ps2** [comment]
Thanks!
