### ISSUE TITLE
Minimum Low Targets

### ISSUE THREAD

**Issue by jwedding** [LoopKit/Loop#957]
Target ranges should have a minimum low built in to the default settings, and documentation on where to remove that threshold in code if desired. This could be 50, it could be 60, but allowing entries without validation is a risk.

**Comment by shaun-22** [comment]
100% agree. This is the kind of spot where adding a common sense guard rail like that has no negative impact on UX but is a huge boost to safety. My vote would be for at least 60.

**Comment by ps2** [comment]
Yes, this is planned work.

**Comment by Kdisimone** [comment]
Implemented here https://github.com/LoopKit/Loop/commit/324ef2f6f601f7199d94b8a35b4971ae03fc8c2a
