### ISSUE TITLE
Omnipod Pairing Isssue - 1.10.0DEV - XCODE LOG

### ISSUE THREAD

**Issue by katwigginton** [LoopKit/Loop#958]
**Describe the bug**
When pairing the Omnipod continually get the error "No response from pod. Please being your pod closer to RileyLink and try again.". 

**Attach an Issue Report**
https://gist.github.com/katwigginton/0c6b99217410adc94ce86f727a3f6915

**To Reproduce**

**Expected behavior**
Pod to pair.

**Screenshots**

**Phone**
 - Hardware: iPhone
 - OS Version: 12.1.2

**Loop Version**
 - Version Number: 1.10.0
 - Repo: DEV

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Additional context**
This happens at work surrounded by servers, computers, printers, etc.

**Comment by johntwohy** [comment]
I’ve gotten the same error on 2 different pods. Tried turning Bluetooth off/on, rileylink off/on, moving rileylink closer to and in different spots around pod. 

iPhone 6S, iOS ver 12.3.1
Loop ver 1.10.0
Dexcom G6 with Dexcom app

Both were pod lot # L44715. Pod did turn on after inserting insulin (based on beeping)

**Comment by Kdisimone** [comment]
Thank you.  That suggestion for troubleshooting is already in Loopdocs.org https://loopkit.github.io/loopdocs/troubleshooting/pod-pairing/

**Comment by johntwohy** [comment]
Oh shoot, thank you! I searched loopdocs for some key words but didn’t find it on my first try
