### ISSUE TITLE
Apple Watch won't install Loop

### ISSUE THREAD

**Issue by Marcitecture** [LoopKit/Loop#962]
Iphone 7 plus IOS 12.3
Apple watch series 2 IOS 4.3.2

Loop downloads, and when the download bar is complete, it freezes until I reopen the app to find it is not installed and has an "install" button next to loop again. 

I saw the previous post from December 2017 with the same issue however they fixed it by unpairing, then repairing the phone and watch. This did not fix my issue. Any help would be grand!

**Comment by Kdisimone** [comment]
updating watchOS, unpairing, re-pairing, rebuilding Loop app (don't forget that step!), and then Loop will install on the watch. I've done this a few times recently.

**Comment by barrywalstead** [comment]
So I have a similar issue. 

Running Watch OS 4.3.2
IOS: 12.3.1
Xcode: 10.2.1

I build Loop and it runs and installs fine, but even after updating everything, unpairing and repairing the watch AND rebuilding Loop all that happens on the watch is the icon fills the screen, shrinks and spins then goes back to the app list.

I rebuilt Loop twice today trying to make it work.

Also, when I launch Xcode I always see: "Installing Symbols for WatchOS 4.3.2 (15U70)

Help!

**Comment by cmpoyner** [comment]
I also have this issue.  Have tried unpairing/repairing then rebuilding.  Loop attempts to install to watch, takes 5-10 minutes, install circle completes and then turns back into the install button.

**Comment by ebing28** [comment]
Having exact same issue as @cmpoyner ^^^

**Comment by jj314** [comment]
Same issue, unpair repair and rebuild did not help.
iOS: 13.2.3
Watch OS: 6.1

**Comment by revjkramer** [comment]
Same issue

**Comment by grizzly129** [comment]
Check out the LoopDocs Build Errors page:
https://loopkit.github.io/loopdocs/build/build_errors/

At the very bottom of the page, find: "Apple Watch, Loop app not installing". Having the watch "Trust this Computer" did the trick for me on both an iPhone 5 SE running iOS 13.1.2 and iPhone X running iOS 13.3.

Watch OS: 6.0.1, Series 3
