### ISSUE TITLE
Basal increase based on one reading in 1 hour

### ISSUE THREAD

**Issue by kblinova** [LoopKit/Loop#963]
I am filing this issue on behalf of my partner Emily Coles. 
Today between 7:38 pm and 8:48 pm her Loop issued a basal increase of 2.718 U/hr based on just one reading from her Dexcom G6. At 7:48 her BG was 70, at 8:18 pm it was 96 and at 8:48 it was 73. The Loop appears to have increased the basal rate on the change from 70 to 96, then lost connection to Dexcom, so it left the basal adjusted for 30 minutes. That resulted in additional insulin of ~1.35 U that Emily did not need because she was already pretty low.

I am not sure if Loop already recognizes that the readings are not consecutive, but the BG momentum should not be calculated based on reading more than 5-10 min apart. Certainly not the readings that were 30 min apart. 

I am attaching the Loop report and hope that something can be gathered from it.

Thank you for all the hard work!

[Loop Report 2019-05-22 22_01_59-07_00.md.zip](https://github.com/LoopKit/Loop/files/3210385/Loop.Report.2019-05-22.22_01_59-07_00.md.zip)

**Comment by ps2** [comment]
Thank you for reporting this. I took a look at your issue report, and your accounting appears correct. Loop issued a 2.75 U/hr temp basal at 8:18.  

For loop to consider momentum it its forecast, there must be 3 or more samples (bg readings) within the last 15 minutes.  As you say, at 8:18pm, there was only one sample, so Loop would not have considered momentum in its forecast. 

A more likely reason for the high temp is negative iob and carbs.  There was a 0 U/hr temp basal set at 7:02pm, which lasted a half hour, and there were 20 of carbs entered at 7:11pm. In situations with high sensitivity (relative to scheduled isf), carbs tend to not expire fast enough. We are likely going to be changing the fast carb absorption to 30 minutes, which would have probably helped you here (looks like the carbs were fruit).

Let me know if that helps explain why Loop took the action it did.

**Comment by kblinova** [comment]
Hi Pete, thank you for a quick response!

I can try to explain Emily's situation.  It seems that Emily was super insulin sensitive on Tuesday and Wednesday due to the hormones triggered by the start of her period. During the two days, she just could not keep her BG up no matter how much she ate.  I am not sure what the remedy in Loop is for such a situation. She tried putting herself in exercise mode, but it seems like any amount of insulin would send her down. The only thing that seemed to help was to jack up her ISF to 80.

Do you have any suggestions on what to do in a case like that? And would having a whole separate profile for ISF values on days like that be helpful? She has another common scenario where she bikes for 8-10 hours and the next day is super insulin resistant (probably due to inflammation in the body trying to recover from the effort). For a day like that we would want another profile for insulin-resistant ISFs.

So, currently she has three settings for her ISF in the 24-hour window: night, day and late evening. I think those relative settings stay generally valid, but we would want to have those values scaled up for an insulin-sensitive day and scaled down for an insulin-resistant day.

Is there is already a way to achieve that in current Loop, please let me know!

Thanks again!

**Comment by ps2** [comment]
For recurring patterns of increased or decreased sensitivity, there is a feature in the works called Temporary Overrides. https://www.youtube.com/watch?v=GCYPTHVQERs, implemented by @mpangburn.  It is currently in review for landing in the dev branch of Loop. Some people have incorporated this into [their builds](https://github.com/Kdisimone/Loop/wiki) already, if you want to try it out.
