### ISSUE TITLE
Add confirmation upon successful changed basal schedule "sync with pod"

### ISSUE THREAD

**Issue by yeagerm** [LoopKit/Loop#964]
There is a popup if the communication with the pod was unsuccessful

**Comment by marionbarker** [comment]
I believe this can be closed. Not sure which Loop version updated this, but pretty robust now.
Once Sync with Pod is tapped, it becomes disabled and the <Settings button is no longer presented to the user.
User waits (spinning indicator) for success or is notified of a failure.
