### ISSUE TITLE
Does iPhone's low-power mode affect Loop operation?

### ISSUE THREAD

**Issue by seanknox** [LoopKit/Loop#965]
I enable low-power mode most of the time on my iPhone. Does this affect Loop network operations?

**Comment by shaun-22** [comment]
Yes. You will almost certainly notice yellow loops (loop not successfully completing) if you have low power mode on.

**Comment by seanknox** [comment]
That's good to know, thanks. Do you know if this is mentioned in the documentation? If not, I can look at adding it.

**Comment by idoodler** [comment]
The Loop app could trigger a `LocalNotification` if the Low Power Mode is detected to prevent those issues.

**Comment by ps2** [comment]
Loop does not depend on any of the documented effects of Low Power Mode, so it should not be adversely affecting Loop.  There may be important reasons the user is needing to enable Low Power Mode, and we should try to work with them.
