### ISSUE TITLE
Omnipod Pairing Issue (jojo-1.10.0-dev-branch)

### ISSUE THREAD

**Issue by naromero77** [LoopKit/Loop#967]
**Describe the bug**
New pod failed to pair. I have tried this previously with omnipod-public-test branch and jojo-1.00 without an issue. Tried turning bluetooth on/off and power cycling Riley Link

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
Pair new pod, hit pair, wait.
[Loop Report 2019-05-25 07_14_18-05_00.md.txt](https://github.com/LoopKit/Loop/files/3219384/Loop.Report.2019-05-25.07_14_18-05_00.md.txt)

**Expected behavior**
Expected pod to pair on first attempt.

**Screenshots**

**Phone**
 - Hardware: iPhone SE
 - OS Version: 12.3

**Loop Version**
 - Version Number: 1.10.0-dev-branch
 - Repo: Katie

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: N/A

**Additional context**
Seems like multiple people have had this issue.
https://github.com/LoopKit/Loop/issues/958
https://github.com/LoopKit/Loop/issues/953

**Comment by Kdisimone** [comment]
Same with other issues; this issue is closed as it is a temporary issue and there's no issue reports or debugging logs captured here to help make improvements with. If you capture these data when the issue presents next time, then you can reopen this issue and include.
