### ISSUE TITLE
Inconsistent title placement on pump configuration screens

### ISSUE THREAD

**Issue by itsmojo** [LoopKit/Loop#974]
**Describe the bug**
While trying to track down why sometimes there is a partial blue button at the bottom of the Pod Pairing screen when setting up an Omnipod on a 5s or an SE and other times there is nothing of the blue button showing, I think I was able to identify where the problem starts. Any time a user does an Add Pump and has to go thru the RileyLink Setup screen, the titles that are normally on the top middle will end up being in a large bold test on the 2nd line for this screen and all the subsequent screens until the pump is fully configured. This causes everything on the various pump setup pages to scroll down. When configuring an Omnipod on a 5s/SE, what remains of the blue Pair button on the Pod Pairing screen on the bottom scrolls completely off the screen when the title is misplaced. After the pump is fully configured, the screen titles continue to stay in the top middle for all subsequent Pod configurations until the pump is deleted and an Add Pump with a Rileylink Setup screen is run again.

**To Reproduce**
1. Build Loop V.10.0DEV for the omnipod-testing branch for the iPhone SE Simulator.
2. Depending on the initial state, go thru a sequence to force you to select the Omnipod from the Add Pump menu. This can be done by deleting any current pump or starting with a fresh Loop install.

![Add Pump](https://user-images.githubusercontent.com/23020111/58401531-fb931d80-8012-11e9-8d02-11794596d443.png)

3. Click on Add Pump and select Omnipod and you will be taken to the RileyLink Setup screen which is the first screen where the title is displayed at the start of the second line in a large bold font. After this, the rest of the pump setup screens will have the screen title at the beginning of the second line in a large bold font instead of in the top middle.

![RileyLink Setup on 2nd line](https://user-images.githubusercontent.com/23020111/58401559-0f3e8400-8013-11e9-82a9-5b0ee729d6ff.png)

4. Configure some dummy Pod Settings for Delivery Limits and Basal Rates (if necessary) and then hit Continue. Notice that the "Pod Settings" title is not displayed in the top middle as it should.

![Pod Settings on 2nd line to review settings](https://user-images.githubusercontent.com/23020111/58401756-807e3700-8013-11e9-951c-960f5a0edf26.png)

5. On the next Pod Pairing screen note that the "Pod Pairing" title is displayed on the beginning of the second line and not in the top middle as it normally is. Note that on a SE/5s, the Pair button at the bottom gets pushed off the screen and cannot be seen without scrolling.

![Pod Pairing on 2nd line](https://user-images.githubusercontent.com/23020111/58401768-8d028f80-8013-11e9-8448-bf58e1df25fb.png)

6. Scroll up and hit Pair and continue thru the rest of the simulated Pod setup sequence, scrolling up as needed to click on the bottom button to proceed to the next step. Note that the screen titles will continue to appear at the beginning of the 2nd line instead of the top middle for this Pod setup.

![Insert Cannula on 2nd line](https://user-images.githubusercontent.com/23020111/58401786-9a1f7e80-8013-11e9-9e43-e2d2a31369f1.png)
![Setup Complete on 2nd line](https://user-images.githubusercontent.com/23020111/58401794-a0155f80-8013-11e9-9087-1c53765dff35.png)
![Pod Settings on 2nd line upon completion](https://user-images.githubusercontent.com/23020111/58401839-b8857a00-8013-11e9-87ba-9d0e26bfe356.png)

7. Click Done to get back to the Settings screen (which now has its title centered and seems to clear this display problem for the pump configuration menus) and then click on the Omnipod to get the Pod Settings screen that is now properly displayed with the title in the upper middle as it should.

![Settings in top middle](https://user-images.githubusercontent.com/23020111/58402095-61cc7000-8014-11e9-91fc-aea533020e24.png)
![Pod Settings in top middle](https://user-images.githubusercontent.com/23020111/58402106-66912400-8014-11e9-87b0-f4422d7884f2.png)

**Expected behavior**
The screen titles should be staying in the top middle and not on the 2nd line. You can see all the Pod setup screens with the title in the top middle by simply ending the current Pod session and then setting up a new Pod by continuing on to the Pod Pairing screen as shown in the following screenshots as the RileyLink Setup screen will not be used again until the pump is deleted.

![Pod Pairing on top middle](https://user-images.githubusercontent.com/23020111/58403024-845f8880-8016-11e9-9a26-0535f1d9e39e.png)
![Insert Cannula on top middle](https://user-images.githubusercontent.com/23020111/58403029-875a7900-8016-11e9-9a96-5e686d117a42.png)
![Setup Complete on top middle](https://user-images.githubusercontent.com/23020111/58403034-8a556980-8016-11e9-9109-a00082eb3524.png)

If you want to see the Pod setup screens with the titles incorrectly placed on the 2nd line, you will need to do Switch from Omnipod Pumps -> Delete Omnipod -> Add Pump to get to the RileyLink Setup screen which seems to be the first one in the sequence with the misplaced title that then affects all the subsequent Pod setup screens. Note that the same incorrect title placement can be seen when setting up a Medtronic pump if the RileyLink Setup screen is visited in the sequence (i.e., switching between Pod types for each simulated run should continue to show the problem each time a Add Pump operation is done. An Omnipod pump with a SE was used for demo purposes as the effect of the incorrect title placement is most noticeable when it completely pushes the Pair button off the screen.

**Phone**
 - Hardware: All iPhone tested, but an SE/5s (Simulator or real) show the most dramatic effects
 - OS Version: Reproduced on the Simulator (12.2), SE (12.3.1), and 5s (12.2 and 12.3.1)

**Loop Version**
 - Version Number: V.10.0DEV
 - Repo: both LoopKit/Loop (omnipod-testing branch) & JoJo

**CGM**
 - Device: never configured
 - Manager app: never configured

**Pump**
 - Manufacturer: doesn't matter, but Omnipod used for demonstration purposes
 - Model: NA

**Additional context**
This issue was the reason why there was no Pair button seen as reported in https://loop.zulipchat.com/#narrow/stream/144120-omnipod_dev/topic/iPhone.20SE.20Pod.20Pairing.20screen/near/166330440 as the new user was switching from Medtronic to Omnipod on his iPhone SE and had to go thru the RileyLink Setup screen when setting up the new Pump.

Issue https://github.com/LoopKit/Loop/issues/973 could potentially be an example of this problem or perhaps related the more generic issue that the table view rows for errors and progress aren’t set up for auto sizing based on content, and doing so creates problems with the method those views use to add padding to keep the button at the bottom.

**Comment by ps2** [comment]
The expected visual design is actually the one with the bolder text. That is the design implemented for setup screens in Loop, but hasn't been applied to pod replacement flow, it looks like.

**Comment by itsmojo** [comment]
Adjusted the issue title

**Comment by itsmojo** [comment]
Adjusted issue title to match reality
