### ISSUE TITLE
Can't connect to Nightscout if Nightscout URL has trailing slash

### ISSUE THREAD

**Issue by seanknox** [LoopKit/Loop#977]
**Describe the bug**
User gets `Nighscoutuploadkit.Uploaderror error 0` when setting up Nightscout if the Nightscout URL has a trailing slash (e.g. `https://myappname.herokuapp.com/` vs `https://myappname.herokuapp.com`)

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Go to settings
2. Tap to set Nightscout
3. Enter NS URL with a trailing slash

**Expected behavior**
Loop accepts Nightscout URL or sanitizes it (removes the trailing slash).

**Actual behavior**
Loop returns `Nighscoutuploadkit.Uploaderror error 0`. I've tried multiple different (new) Nightscout sites and confirmed the API Key is correct.

**Screenshots**

<img width="414" alt="image" src="https://user-images.githubusercontent.com/1231630/58514680-79f8d800-8157-11e9-8c4e-0ef40c9159dc.png">

**Phone**
 - Hardware: iPhone XR
 - OS Version: iOS 12.2

**Loop Version**
 - Version Number: v1.10.0dev (omnipod-testing)
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom app

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: 

**Additional context**

**Comment by seanknox** [comment]
Loop issue: https://gist.github.com/seanknox/bb108af38f2536ff912d0ade39be33a2

**Comment by seanknox** [comment]
This seems like Loop can't authenticate to Nightscout. I've confirmed the API is correct by logging into the Nightscout web UI.

**Comment by loudestnoise** [comment]
I had this issue and I had recently changed my API key. I found that I had to restart my NS instance for the new API key to take. I see though you’re using Heroku, whereas I am running NS on my own Linux VPS.

**Comment by Kdisimone** [comment]
Make sure your URL doesn’t have a trailing slash in Loop settings too

**Comment by seanknox** [comment]
It was the trailing slash in the URL! Great find.

**Comment by Kdisimone** [comment]
Well, to be fair to the docs...it is in there. ;) https://loopkit.github.io/loopdocs/operation/loop-settings/services/#nightscout

**Comment by seanknox** [comment]
True, though a user really shouldn't have to ensure that text input like this is sanitized; the app should do that. I'm going to see if I can make that happen.

**Comment by ArkonPhoenix** [comment]
I wish you could edit what you have entered. It took me three tries of typing the URL in several variations and the lengthy API Secret. As you have to Delete and start over.
