### ISSUE TITLE
Feature Request: Pre-bolus alarm

### ISSUE THREAD

**Issue by iphotostuff** [LoopKit/Loop#979]
**Use case:** 
When a user is delivering a meal/snack bolus, allow for a pre-bolus alarm to be set on the bolus delivery screen

**Scope:** 
All users that pre-bolus meals/snacks (hopefully everyone)

**Why:** 
There's a very high correlation of people that bolus and people that set alarms for pre-bolusing. Instead of forcing a user to use another app, it would be far more convenient to add a single toggle state (sticky) for users. Users could set the time, but most likely it would be a nice feature added. 

**Included in Design:**
• Bolus delivery screen settings 
• Indicator of pre-bolus timer countdown 

**Not included in Design:**
• Setting actual alarm time
• Native alarming when user is not in app (notification and audio alarm in iOS)

![Alarm](https://user-images.githubusercontent.com/2902978/58526161-16dd6480-819c-11e9-84c6-79117b0c3f68.png)

![Alarm progress](https://user-images.githubusercontent.com/2902978/58525826-1db7a780-819b-11e9-913c-8ae967db374d.png)

**Comment by Kdisimone** [comment]
closing this out with a note to continue this discussion on the already open issue for the same topic.  https://github.com/LoopKit/Loop/issues/686
