### ISSUE TITLE
Feature Requst: extended bolus

### ISSUE THREAD

**Issue by stephencrw** [LoopKit/Loop#980]
With the PDM there was the ability to have a bolus split by a percentage with the remaining injected over a period of time. E.g. a 12 unit meal split with 30% up front and the remaining over x hours.

**Comment by shaun-22** [comment]
You may want to check out the LoopTips page that explains how Loop’s mechanism for dealing with slower absorbing foods differs from traditional pump therapy solutions like extended/square wave blouses. Essentially Loop is achieving the same end (spreading insulin delivery over time to respond to food as it digests) but doing it in a smarter way through its dynamic carb absorption mode and high temp basals. 
https://kdisimone.github.io/looptips/how-to/bolus/

**Comment by Rdeboer180** [comment]
I too would like a feature like this added. I love my loop but per my doctor and still trying to figure out my pumps optimal settings, I use Closed loop during the day and Open Loop. Is there any way the feature could be added to only show when loop is closed? or as a test branch. If we are alone in wanting a feature like this please ignore.

**Comment by Rdeboer180** [comment]
Or... be an option to add in the customize settings?

**Comment by loyalchallenger** [comment]
The extended bolus option really works better for me since I'm on a low basal dose of  .15u/hr. If I set an increased temp basal, I would get my next click 15mins later than if I set an extended bolus. It allows me to receive more insulin when I need it, instead of spacing it out and waiting too long to react.
