### ISSUE TITLE
Add Bolus Increment options for Omnipod

### ISSUE THREAD

**Issue by ArkonPhoenix** [LoopKit/Loop#981]
In the OEM Omnipod PDM, you can choose your Bolus Increment to be 0.05, 0.10, 0.50, or 1.00.

In the current version of Loop, you do not get a choice, it always does 0.05 increments when delivery a bolus. Which make it take longer to bolus. I can see this being good for safety reasons. But this also can lead to various user errors when the user is impatient and wants to bolos more or tap around.

Now me personally, I wouldn't want to use 0.50 or 1.00. But we did use the 0.10 setting before Loop and felt that was good balance between safety and speed.

Thanks for your consideration.

**Comment by ps2** [comment]
The Bolus Increment setting does not change bolus delivery rate. It's just a UI feature.

**Comment by alevar1975** [comment]
Dear Pete,

My name is Alen. I use the Loop app with a Medtronic Pump to manage my Diabetes.
I’m more than satisfied. Currently, I’m waiting for my OmniPod RileyLink to test the dev branch.

I live in Germany. I want to offer my help to translate and localise the LoopDocs into German. I understand that there is a fast growing Loop community in Germany. One obstacle is that the LoopDocs are only available in English. 

I think translating and localising the LoopDocs into several European languages would make it easier for many people to apply the Loop app.

Please let me know whether you need my help.

I hope to hear from you soon.

Kind regards,

Alen

**Comment by ps2** [comment]
There is a discussion in Zulip on this. https://loop.zulipchat.com/#narrow/stream/144111-general/topic/Multilingual.20Documentation
