### ISSUE TITLE
Building and Publishing to Apple TestFlight Errors for Omnipod-testing Branch

### ISSUE THREAD

**Issue by jordantrizz** [LoopKit/Loop#982]
When building Loop-omnipod-testing and trying to submit to the Apple Store so you can use Test Flight an error occurs.

ERROR ITMS-4236: "Invalid value '1.10.0dev' for bundle_short_version_string" at SoftwareAssets

I was able to change the version to 1.10.0!

 ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '2.2.0dev' in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

Unfortunately, I'm stuck here.

The reason I'm using Test Flight is because I don't have access to a Mac. So I'm using https://www.macincloud.com/ to build and deploy with a developer account.

Let me know what I need to do to rectify this!

**Comment by Kdisimone** [comment]
You should find a Mac to borrow. Sorry. Distribution of medical software isn’t something supported here, and TestFlight is a distribution method.
