### ISSUE TITLE
Loop crashes when only entering a minimum Pre-Meal override (with no maximum set)

### ISSUE THREAD

**Issue by sn0crash** [LoopKit/Loop#984]
**Describe the bug**
Loop crashes when only entering a minimum Pre-Meal override (with no maximum set).

**To Reproduce**
1. Go to Settings -> Correction Range -> Overrides
2. Set a minimum Pre-Meal override number (e.g. 70)
3. Do not set a maximum Pre-Meal override
4. Go back to main page
5. Tap the Pre-Meal button

**Expected behavior**
App should crash. It will crash at launch when you try loading the app again.

**Screenshots**
n/a - easy to reproduce

**Phone**
 - Hardware: iPhone X
 - OS Version: iOS 12.3

**Loop Version**
 - Version Number: 1.10.0DEV
 - Repo: LoopKit/Loop (omnipod-testing)

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Comment by andreascarsetto** [comment]
The same problem occurs if in the indicated range the first value is greater than the second one. With the configuration attached, the app kept on crashing at startup from 3.30pm until 5.00pm, out of that time slot it works perfectly

![IMG_0023](https://user-images.githubusercontent.com/16019002/59932200-f759f480-9446-11e9-94ee-3ae3d971ef25.jpg)

**Comment by IndyT1DNerd** [comment]
Agree, I had same crash with Lower bound larger than upper bound.  Application would not launch after that.

**Comment by Kdisimone** [comment]
And following the format of min-max that is shown in grey text prior to entering a value is also helpful to avoiding crash.

**Comment by Kdisimone** [comment]
Resolved with this commit https://github.com/LoopKit/Loop/commit/324ef2f6f601f7199d94b8a35b4971ae03fc8c2a
