### ISSUE TITLE
Cannot switch back to normal keyboard after using other keyboards

### ISSUE THREAD

**Issue by BarbraWalton** [LoopKit/Loop#986]
**Describe the bug**
After using the Bitmoji keyboard in another app on an iPhone, attempting to enter in carbs in the "Add Carb Entry" screen brings up the bitmoji keyboard and there's no way to switch out of it. 

Closing and re-opening the Loop app did not fix it.

Workaround: Go to another app, changing the keyboard back to the default keyboard and then typing something (had to type something, just changing didn't work) fixed the issue.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. With Bitmoji installed, go to another app on the phone.
2. Use the bitmoji keyboard to choose a bitmoji and paste it into the app
3. Return to Loop
4. Go to Add Carb Entry screen
5. Try to enter carbs; the bitmoji keyboard is shown and there's no way to change it. 

**Expected behavior**
I would expect the Globe icon to appear in the bottom left corner of the screen and allow you to change the keyboard

**Screenshots**
![image](https://user-images.githubusercontent.com/4070184/59034030-24e45280-8838-11e9-93b6-38a791dbf982.png)

**Phone**
 - iPhone X
-  iOs 12.3.1

**Loop Version**
 - Version Number: not sure where to find this?
 - Repo: omnipod-testing

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Eros pods
 - Firmware version: ?

**Additional context**

**Comment by Kdisimone** [comment]
closing this as I can recreate the desired behavior using current dev branch and ios 13. 


![IMG_8062](https://user-images.githubusercontent.com/12402160/66509810-994e2d00-ea88-11e9-8813-2cc8e23c5c40.PNG)
