### ISSUE TITLE
Loop crashes on startup (Release build, omnipod-testing branch), Exception Type:  EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by vbaderks** [LoopKit/Loop#987]
**Describe the bug**
This is my first try to build and use the Loop app. The LoopDocs were not clear if one should build the "release" or the "debug" configuration. My initial try was to build the "release" version. After building and deploying the app to the iPhone, the Loop app would crash sometimes during startup.

**Attach an Issue Report**
N/A: The Loop app crashes during startup, report function not available. iOS crash dump is attached.

**To Reproduce**
1. Get the latest Loop source code (omnipod-testing branch)
2. Update the build configuration in Xcode to build the "release build"
3. Build the Loop app with Xcode 10.2.1
3. Deploy the Loop app on a iPhone SE with iOS 12.3.1
4. Start the Loop app. Sometimes it will crash during startup, with Exception Type:  EXC_BAD_ACCESS in the .ips crash log file.

**Expected behavior**
The Loop app can always be started normally.

**Screenshots**
N/A.

**Phone**
 - Hardware: iPhone SE 32GByte (iPhone8,4)
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: 1.10 Dev
 - Repo: https://github.com/LoopKit/Loop/tree/omnipod-testing

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: N/A
 - Model: N/A
 - Firmware version: N/A
=> Pump was not attached/configured when crash occurred.

**Additional context**
I rebuild the Loop app in the "debug" configuration and deployed it to the iPhone to get better crash dump info. Until now however the "debug" build has worked fine and no crash was seen during startup.
Please let me know if you need more info.

[Loop-2019-06-02-191031.ips.txt](https://github.com/LoopKit/Loop/files/3271632/Loop-2019-06-02-191031.ips.txt)

**Comment by cyoung1024** [comment]
Do you happen to have a space in the name of your Loop project’s folder, be it in between words or an accidental one left hanging at the end ?

**Comment by vbaderks** [comment]
I double checked, but there are no spaces in the full directory name. Is there something else I can check?

**Comment by Kdisimone** [comment]
has this been resolved? I assume so. This sounds like a build error and posting screenshots would help to troubleshoot. And loopdocs don't specifically mention release or debug building because you do not have to choose between the two...default selection is just fine. If you are running into errors, that is not the place to look for source of error. Please reopen if your build errors have persisted, otherwise I'll be closing this issue.

**Comment by vbaderks** [comment]
The default Xcode project configuration builds the "debug" release. Your are right that the loopdocs don't mention which configuration to build (omission in the docs?).
Normally one would use debug builds during testing and release builds when the app is finished and ready to be uploaded to the App Store. In release builds Xcode will apply additional optimization to the application. 

Currently my development environment for iOS is limited, which makes it hard for me to assist in determining if the EXC_BAD_ACCESS exception is caused by a defect in the Loop app, that is only visible in release builds, or that the problem is was caused by an incorrect Xcode configuration on my system.

You can keep this issue closed.
