### ISSUE TITLE
Please move Suspend Pump away from Deactivate Pod.

### ISSUE THREAD

**Issue by ArkonPhoenix** [LoopKit/Loop#989]
When choosing to Suspend a pod for a while, you have to dig into the Pump Settings to get the Suspend option. Its already an issue I feel that you have to dig so far to get this option, but even more troublesome that its literally on top of the Replace Pod option. Any chance these two options can be further apart from each other?

**Comment by purplechap** [comment]
You can click on both the Pod and Pod Age icons at the top of the main screen which navigates directly to the Pod settings. I agree that some separation might be helpful as I have click on the opposite - I went to replace a pod and click on Suspend Delivery by mistake.

**Comment by ArkonPhoenix** [comment]
Closing issue as they are further apart now using the current Dev Branch.
