### ISSUE TITLE
"pump suspended" error + pairing failure xcode logs

### ISSUE THREAD

**Issue by cinderelsa** [LoopKit/Loop#990]
**Describe the bug**
I'm experiencing pod pairing failures after running into the bogus "pump suspended" message which started after suspending/resuming pod insulin delivery. Haven't been able to pair a pod since then and I would like to know if my RileyLink just coincidentally broke or if this has to do with the pump suspended error.
MDT still connects and I have found that the "pump suspended" message will disappear after a while when using the MDT.
However, during all this I ran into a situation where Loop successfully commanded a bolus to the MDT while it was in fact suspended (attaching a video).

I have already rebuilt Loop from scratch in an attempt to fix this, but no success.

**Issue Report**
I'm attaching two:
1) issued after failed pod pairing attempts
2) issued when no pump was connected at all, but app still showed "pump suspended"
[Loop Report 2019-06-17 09:27:46+02:00(Omnipod-pairing-failure).txt](https://github.com/LoopKit/Loop/files/3297021/Loop.Report.2019-06-17.09.27.46%2B02.00.Omnipod-pairing-failure.txt)
[Loop Report 2019-06-17 09:28:44+02:00(no pump connected).txt](https://github.com/LoopKit/Loop/files/3297022/Loop.Report.2019-06-17.09.28.44%2B02.00.no.pump.connected.txt)

**To Reproduce**
I'm not sure. Here's how I _think_ it happened for me:
1. Suspended delivery on a pod, then resumed (I'm assuming something went wrong here because communications kept failing from then on)
2. Tried deactivating pod (failed)
3. Deleted Omnipod from Loop
4. Added Omnipod again, tried pairing a new pod (failed)
5. Deleted Omnipod, connected MDT
6. Noticed bogus "pump suspended" message

**Expected behavior**

**Screenshots**
![IMG_2564](https://user-images.githubusercontent.com/35226894/59589435-33f5bb00-90ea-11e9-9ce5-90dd3fa076e6.PNG)
![IMG_2583](https://user-images.githubusercontent.com/35226894/59589436-33f5bb00-90ea-11e9-8b4b-daf1c308138e.PNG)

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.2

**Loop Version**
 - Version Number: 1.10.0
 - Repo: Dev-JoJo

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic /// (Omnipod Eros pods)
 - Model: 522
 - Firmware version: 2.4A 1.1 0B 0B

**Additional context**

Gist (failed pairing attempts, "pump suspended" on main screen):
https://gist.github.com/cinderelsa/ee2661f7d7cbc812aaecec608eb7a0d4

Video (I gave a bolus command from Loop while pump was suspended, to see what would happen. What you see in this video is Loop autonomously resuming delivery and commanding the bolus - instead of notifying me that delivery was suspended):
https://www.dropbox.com/s/ylh63e73wybtsmr/IMG_2590.MOV?dl=0

**Comment by terese-wallace** [comment]
Terese had this happen also. I did not save the version of the last loop build we put on her phone which was running when she first hit the problem. However, it was the omnipod-testing branch.

**Comment by terese-wallace** [comment]
Today the omnipod from yesterday came off, so we had to setup another one anyway. This time we uninstalled the Loop app from the iPhone and then re-installed it from XCode.  Re-entered all the settings. This time there was no "suspended" status that could not be cancelled. And the new omnipod paired successfully in the usual way.
