### ISSUE TITLE
Eversense Request

### ISSUE THREAD

**Issue by timmy354321** [LoopKit/Loop#991]
Now that this is approved for use in the US, is there any possibility of adding eversense integration? or known third party ways to get the data into the loop for offline use? Thanks!

**Comment by Asakusa22** [comment]
I'd be very interested, too. There are some in Europe who use Eversense with AAPS https://androidaps.readthedocs.io/en/latest/EN/Configuration/BG-Source.html#for-users-of-eversense-br

**Comment by barrywalstead** [comment]
I too am really interested in Eversense for Loop.

**Comment by DrunoL** [comment]
Also am I
