### ISSUE TITLE
Enhancement Request: Protect Configuration Settings from Accidental Changes

### ISSUE THREAD

**Issue by gregwaehner** [LoopKit/Loop#992]
This is an enhancement request. Many end-users of loop are younger kids. Would like a way to protect the configuration settings from accidental changes due to looking around, searching for where a setting actual is, etc. The protection could be a prompt like " do you want to change settings?", or it could be a manually set passphrase (like Nightscout API secret). Personally, trying to stay clear of FaceID because if the phone user accidentally makes the change, their face is more than likely registered and used for bolus configuration. I think of this like parental controls to ensure any changes are intended and allowed.

**Comment by Kdisimone** [comment]
closing this issue as it is a duplication of https://github.com/LoopKit/Loop/issues/692
